Add "elevated privileges" to extensions and make managing extensions one
paranext/paranext-core pull request #1012
Opened 2024-07-17 19:57 UTC by lyonsil

Adds the notion of "elevated privileges" for extensions to give them abilities if requested in their manifest. The first of these privileges gives extensions the right to manage new extensions via installing, enabling, and disabling them.

This is intended to resolve https://github.com/paranext/paranext-core/issues/965. Note that this doesn't add any events, though, because I think we're going to want to get a better sense of use cases before putting in events. This is kind of nuanced, and we want to make sure whatever events are added make sense. For example, the code that activates an extension after it is installed in asynchronous and not directly awaitable, so emitting an event than an extension is "installed" might be misleading if it isn't activated yet. Maybe we just want to add activation events instead of installation events? Anyway, the uncertainty is why I held off on adding anything.

Because all other extension management functions were grouped together, I put the function to enumerate extensions in the same group instead of putting it separately in PAPI as the ticket suggested. We can move it if desired, but it's not clear to me what the use case is of enumerating extensions if you can't do anything about it, and it's annoying to look in two very different places for functions related to extension management.

Elevated privilege strings/IDs for extensions are stored in `paranext-core/src/shared/models/elevated-privileges.model.ts`. I'm assuming as we add more privileges, they will be updated in the same file. Although all the code using these (for now) is in the extension host, I assumed this was a good place to share the types with extensions.

Once this is merged I can add something to the extension template to give more details on how to use this. The general idea is that you add the privilege string to `manifest.json` under the `elevatedPrivileges` property (which is an array of strings). If the extension host sees this, it will populate the `elevatedPrivileges` property in the `ExecutionActivationContext` when an extension is activated. The extension can use the functions given there to install, enable, disable, and enumerate extensions available in the system.

2024-07-17 22:36 UTC, tjcouch-sil requested changes
Awesome! Nice quick thinking to get this rolling asap.

Without being able to enumerate extensions (without elevated privileges), it might be weird/bad dx to make an optional extension dependency. That being said, I don't have any use cases for such right now. It's just the main thing I have in mind regarding making that functionality available. I guess probably YAGNI

Where do you plan to add details in the template? I'd think it would be best to add some stuff in the extension template wiki if you want to add something :) honestly, though, I have just been leaning on the fact that we have the auto-docs from the TSDocs to do most documenting of my new features recently :grimacing: probably not a great practice haha

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1012#-:-O21WScO0e1vPDevLHKR:bazyttg)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`src/extension-host/extension-types/extension-activation-context.model.ts` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21oZ2J9iY8JcuXiZbx:-O21oZ2J9iY8JcuXiZby:b-odqsgk) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/extension-host/extension-types/extension-activation-context.model.ts#L11)):*
> ```XML
>   /** Used to save and load data from the storage service. */
>   executionToken: ExecutionToken;
>   /** Special permissions required by an extension based on its manifest */
> ```

Fleshing out this TSDoc by explaning what you add in the manifest might be one place you could add enough to make this self-documenting :) since you had the nice idea of making all the keys of this object the same as the privilege strings.
___
*[`src/extension-host/extension-types/extension-manifest.model.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21XAdZCmpB_Gk1GePY:-O21XAd_31hi9joMHIsa:b-qsrucg) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/extension-host/extension-types/extension-manifest.model.ts#L19)):*
> ```XML
>   main: string;
>   /** List of special permissions required by the extension to work as intended */
>   elevatedPrivileges: string[];
> ```

I suggest here you do the following here instead to specify the exact strings available. Would give more clarity on what is actually available to specify here:

```typescript
elevatedPrivileges: `${ElevatedPrivilegeNames}`
```

[Source](https://stackoverflow.com/a/75722379)
___
*[`src/extension-host/services/extension.service.ts` line 750 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21jr4x7tnGUxp0q7Pl:-O21jr4x7tnGUxp0q7Pm:bksdyrs) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/extension-host/services/extension.service.ts#L750)):*
> ```XML
>     await nodeFS.readDir(disabledExtensionsUri, (uri) => uri?.toLowerCase().endsWith('zip'))
>   ).file;
>   const disabled = extractExtensionDetailsFromFileNames(disabledExtensions);
> ```

I wonder if it would be worth also filtering out `installedExtensions` from here. Just thinking if someone puts a file in the wrong place for some reason or some other weird thing happens. Not a big deal.
___
*[`src/extension-host/services/extension.service.ts` line 1116 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21kZJr3NH_6ux5wPT0:-O21kZJr3NH_6ux5wPT1:bhb6ef0) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/extension-host/services/extension.service.ts#L1116)):*
> ```XML
>     if (isInitialized) return;
> 
>     await normalizeExtensionFileNames();
> ```

Why does this need to happen? To prevent duplicates? Should this also happen when a new extension is added to the installed extensions folder since we're watching it for new extensions?
___
*[`src/shared/models/elevated-privileges.model.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21lbRl-P1Hlpv0CNkY:-O21lbRl-P1Hlpv0CNkZ:b-m6p1fu) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/shared/models/elevated-privileges.model.ts#L5)):*
> ```XML
> /** String constants that are listed in an extension's manifest.json to state needed privileges */
> export enum ElevatedPrivilegeNames {
>   manageExtensions = 'ManageExtensions',
> ```

Why PascalCase? I suggest lowerCamelCase since we use that pretty much everywhere including in the manifest file. (I think the values in the enum are what will need to be in the manifest because of how you're using the enum in `extension.service.ts`. Sorry if I'm wrong and I'm just wasting time haha)
___
*[`src/shared/models/manage-extensions-privilege.model.ts` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21pLDlB-wkG2QSxvu_:-O21pLDlB-wkG2QSxvua:b-7g7t0j) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/shared/models/manage-extensions-privilege.model.ts#L18)):*
> ```XML
>  */
> export type InstalledExtensions = {
>   packaged: ExtensionIdentifier[];
> ```

I know what packaged extensions are because I can read the TSDocs you added in `extension.service.ts`, but this may be the only place where this "packaged" term comes up in the TSDocs that extension developers can see. I recommend elaborating on what exactly is and is not a packaged extension since that could be confusing for devs :)
___
*[`src/shared/models/manage-extensions-privilege.model.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21m5ft1R266ZtrNq9r:-O21m5ft1R266ZtrNq9s:b-k03kue) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/shared/models/manage-extensions-privilege.model.ts#L28)):*
> ```XML
>  * @param extensionUrlToDownload URL to the extension ZIP file to download
>  * @param fileSize Expected size of the file
>  * @param fileHashes Hash value(s) of the file to download
> ```

Currently as implemented, this function only uses one hash even if two are provided, right? It doesn't say so, but the fact that I can provide two in an object and the way this TSDoc doesn't really mention anything seems to imply in my mind that providing both hashes would mean both would be compared. Is there a particular benefit to providing an object with multiple hashes over just providing the algorithm (could be a union of strings like `'sha256' | 'sha512'` so people know their options) and the hash as two parameters? Maybe to leave it open for us to verify all hashes they provide in the future? If so, might be nice to add a note that we aren't actually using both if two are provided. But not a big deal.


<!-- Sent from Reviewable.io -->

2024-07-18 16:49 UTC, lyonsil reviewed
We could always expose extension enumeration in more than one place later if we want. It just seems weird to make people look in multiple places for the function, I think.

I was going thinking about adding something to the README, but honestly I haven't looked closely enough to pick the best place. Maybe I'll just touch the wiki. Not sure.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1012#-:-O25jPy2CMIRm1Hubchw:b-qlf2be)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/extension-host/extension-types/extension-activation-context.model.ts` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21oZ2J9iY8JcuXiZbx:-O25b1Vo7Jfnd4fQ0qvG:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/extension-host/extension-types/extension-activation-context.model.ts#L11)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Fleshing out this TSDoc by explaning what you add in the manifest might be one place you could add enough to make this self-documenting :) since you had the nice idea of making all the keys of this object the same as the privilege strings.
</blockquote></details>

Done
___
*[`src/extension-host/extension-types/extension-manifest.model.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21XAdZCmpB_Gk1GePY:-O25VD9WBDvthCF4y-a7:b-t7ocyw) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/extension-host/extension-types/extension-manifest.model.ts#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I suggest here you do the following here instead to specify the exact strings available. Would give more clarity on what is actually available to specify here:

```typescript
elevatedPrivileges: `${ElevatedPrivilegeNames}`
```

[Source](https://stackoverflow.com/a/75722379)
</blockquote></details>

Very nice! I didn't realize that syntax would work.
___
*[`src/extension-host/services/extension.service.ts` line 750 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21jr4x7tnGUxp0q7Pl:-O25ZW57D12lJrdBqiOu:blrkxi7) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/extension-host/services/extension.service.ts#L750)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I wonder if it would be worth also filtering out `installedExtensions` from here. Just thinking if someone puts a file in the wrong place for some reason or some other weird thing happens. Not a big deal.
</blockquote></details>

Done - Yeah, probably not a big deal, but not hard to add.
___
*[`src/extension-host/services/extension.service.ts` line 1116 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21kZJr3NH_6ux5wPT0:-O25WA8K7Pp5g2URLbsG:b-hq4ry3) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/extension-host/services/extension.service.ts#L1116)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why does this need to happen? To prevent duplicates? Should this also happen when a new extension is added to the installed extensions folder since we're watching it for new extensions?
</blockquote></details>

For almost all users this should never rename any files. What I noticed, though, is that if someone (e.g., a developer) drops in a ZIP file into their installed extensions directory and that file doesn't match the expected naming convention, weird/bad things happen with the enable/disable process. This code will rename a "misnamed" extension ZIP file that someone copied there so that enable/disable will work as intended.

The alternative to this (which might be more robust but will also be more complex and a little slower) would be to always build a map of file names to actual extension names/versions inside of the directories before performing any actions. That is, parse every extension ZIP in one or both directories whenever running the extension management functions. This way seemed like a simpler approach.
___
*[`src/shared/models/elevated-privileges.model.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21lbRl-P1Hlpv0CNkY:-O25XmVHCuM_wIdmVvoF:byic081) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/shared/models/elevated-privileges.model.ts#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why PascalCase? I suggest lowerCamelCase since we use that pretty much everywhere including in the manifest file. (I think the values in the enum are what will need to be in the manifest because of how you're using the enum in `extension.service.ts`. Sorry if I'm wrong and I'm just wasting time haha)
</blockquote></details>

Yes, this is intended to contain an array of strings from the enum.

I think I had this string both as camelCase and PascalCase at various times during development. I'm fine changing it back to camelCase. I don't feel strongly about it.
___
*[`src/shared/models/manage-extensions-privilege.model.ts` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21pLDlB-wkG2QSxvu_:-O25cqNy30pWwPdqP2Q3:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/shared/models/manage-extensions-privilege.model.ts#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I know what packaged extensions are because I can read the TSDocs you added in `extension.service.ts`, but this may be the only place where this "packaged" term comes up in the TSDocs that extension developers can see. I recommend elaborating on what exactly is and is not a packaged extension since that could be confusing for devs :)
</blockquote></details>

Done
___
*[`src/shared/models/manage-extensions-privilege.model.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21m5ft1R266ZtrNq9r:-O25dtFP9jMuK6tMcRVN:bnc1th4) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/shared/models/manage-extensions-privilege.model.ts#L28)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Currently as implemented, this function only uses one hash even if two are provided, right? It doesn't say so, but the fact that I can provide two in an object and the way this TSDoc doesn't really mention anything seems to imply in my mind that providing both hashes would mean both would be compared. Is there a particular benefit to providing an object with multiple hashes over just providing the algorithm (could be a union of strings like `'sha256' | 'sha512'` so people know their options) and the hash as two parameters? Maybe to leave it open for us to verify all hashes they provide in the future? If so, might be nice to add a note that we aren't actually using both if two are provided. But not a big deal.
</blockquote></details>

I added more details here to the docs. The purpose of providing multiple is that our marketplace only stores one hash value for a file now. I think it's sha512, but the guys talked about sha256, too. In the future we may find that we want to move to a new algo (sha1024?) for new extensions. In that case we still want to accept the existing hash values for existing extensions, but we also want to support new hash algorithms that we start using. This was a cleanest way I could think of to handle that.


<!-- Sent from Reviewable.io -->

2024-07-18 16:49 UTC, lyonsil reviewed
whoops, meant to say "multiple places for extension management functions"

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1012#-:-O25juRZ7nlQIZoRPPQv:bqksqgy)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2024-07-18 21:40 UTC, tjcouch-sil approved these changes
Looks great! Just one thing to clarify a bit further regarding renaming extensions. But if there is no action needed from your perspective, feel free to get it in :) thanks for all the adjustments!

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1012#-:-O26mPZ035tUBTbsfsVI:b-19vjyo)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/extension-host/services/extension.service.ts` line 1116 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21kZJr3NH_6ux5wPT0:-O26kkBB7Z3-U3f2qI0n:b-djlsyi) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/extension-host/services/extension.service.ts#L1116)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

For almost all users this should never rename any files. What I noticed, though, is that if someone (e.g., a developer) drops in a ZIP file into their installed extensions directory and that file doesn't match the expected naming convention, weird/bad things happen with the enable/disable process. This code will rename a "misnamed" extension ZIP file that someone copied there so that enable/disable will work as intended.

The alternative to this (which might be more robust but will also be more complex and a little slower) would be to always build a map of file names to actual extension names/versions inside of the directories before performing any actions. That is, parse every extension ZIP in one or both directories whenever running the extension management functions. This way seemed like a simpler approach.
</blockquote></details>

Gotcha! Works to simply the process. My question still remains, though: shouldn't this also happen when someone drops a new extension in? They could just put in an extension zip with whatever crazy name they want
___
*[`src/shared/models/manage-extensions-privilege.model.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21m5ft1R266ZtrNq9r:-O26lQVu7DA4rPLBgM6N:b-8qrq1d) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/shared/models/manage-extensions-privilege.model.ts#L28)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I added more details here to the docs. The purpose of providing multiple is that our marketplace only stores one hash value for a file now. I think it's sha512, but the guys talked about sha256, too. In the future we may find that we want to move to a new algo (sha1024?) for new extensions. In that case we still want to accept the existing hash values for existing extensions, but we also want to support new hash algorithms that we start using. This was a cleanest way I could think of to handle that.
</blockquote></details>

I was thinking something like the following might be a bit clearer, but it doesn't really matter (and I very well may be misunderstanding what you're trying to account for). Thanks for adding the clarification :) we can just forget about it

```typescript
export type SupportedHashAlgorithm = 'sha256' | 'sha512';

export type InstallExtensionFunction = (extensionUrlToDownload: string, fileSize: number, hashAlgorithm: SupportedHashAlgorithm, fileHashValue: string) => Promise<void>;
```


<!-- Sent from Reviewable.io -->

2024-07-18 22:00 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1012)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/extension-host/services/extension.service.ts` line 1116 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21kZJr3NH_6ux5wPT0:-O26p5Ro8JpBixHAOmsm:banmf8c) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/extension-host/services/extension.service.ts#L1116)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Gotcha! Works to simply the process. My question still remains, though: shouldn't this also happen when someone drops a new extension in? They could just put in an extension zip with whatever crazy name they want
</blockquote></details>

I'm working under the assumption that normal people aren't going to drop in extensions regularly into this folder. If they do for some reason, then the next time the platform restarts the name will be adjusted. Trying to adjust file names when extensions are already loaded/running seemed out of scope - too many things get read and cached to know if we're keeping it all straight.

Assuming someone does drop in a crazy file name then that extension will still load and run. The marketplace extension might get cranky, though.

I think this is a case of "if it becomes important to deal with that situation differently I'm happy to open a ticket and think about it again." For the most part, though, I see this as YAGNI.
___
*[`src/shared/models/manage-extensions-privilege.model.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/1012#-O21m5ft1R266ZtrNq9r:-O26pwlb2bIawn16SIUW:b-7nsa8o) ([raw file](https://github.com/paranext/paranext-core/blob/32d8e2594e720094dd21157e8760e389bb39732c/src/shared/models/manage-extensions-privilege.model.ts#L28)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I was thinking something like the following might be a bit clearer, but it doesn't really matter (and I very well may be misunderstanding what you're trying to account for). Thanks for adding the clarification :) we can just forget about it

```typescript
export type SupportedHashAlgorithm = 'sha256' | 'sha512';

export type InstallExtensionFunction = (extensionUrlToDownload: string, fileSize: number, hashAlgorithm: SupportedHashAlgorithm, fileHashValue: string) => Promise<void>;
```
</blockquote></details>

What I have seems closer to how I remember "crypto algorithm negotiation" working in other protocols which is why I went that way. What you're suggesting would probably work fine, too. I think I'll just leave it as for now.


<!-- Sent from Reviewable.io -->

2024-07-18 22:00 UTC, merged