463 repeated words
paranext/paranext-core pull request #1020
Opened 2024-07-19 16:33 UTC by rolfheij-sil

2024-07-29 19:51 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020)* status: 0 of 36 files reviewed, 4 unresolved discussions

___
*[`extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-1jQt4Vaibhl1rd3w:-O3-1jQt4Vaibhl1rd3x:b-4ksvru) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx#L104)):*
> ```XML
> ];
> 
> const extractItems = (text: string, target: string | undefined = undefined): string[] => {
> ```

This is a pretty weak algorithm to find repeated words. I'm thinking about finding the logic for it in PT9 source code, but not sure if that's worth the effort right now


<!-- Sent from Reviewable.io -->

2024-07-29 19:52 UTC, rolfheij-sil reviewed
The code basically has zero comments right now, so I'm looking to add those Soon™

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020#-:-O3-24v3CJy01Cjlqzgr:b-nj7ukx)* status: 0 of 36 files reviewed, 4 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-07-29 21:51 UTC, lyonsil requested changes
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020)* status: all files reviewed, 7 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/main.ts` line 89 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-Lo7w08wC-a6eg78s:-O3-Lo7w08wC-a6eg78t:bpkypze) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L89)):*
> ```XML
>   return papi.webViews.getWebView(
>     webViewType,
>     { type: 'float', floatSize: { width: 700, height: 800 } },
> ```

Should we be hard coding dialog sizes like this?
___
*[`extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-1jQt4Vaibhl1rd3w:-O3-FBUTDByP0sy1QflA:b-do8bno) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx#L104)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

This is a pretty weak algorithm to find repeated words. I'm thinking about finding the logic for it in PT9 source code, but not sure if that's worth the effort right now
</blockquote></details>

Whatever the logic is, you probably want this to live in a `ts` file so you can reuse it in running the check itself. Otherwise it has to be duplicated.
___
*[`lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-SMd27KM22k24r3IZ:-O3-SMd27KM22k24r3I_:bjjbm27) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx#L19)):*
> ```XML
> };
> 
> const extractNumber = (text: string): number => {
> ```

Code that is working directly on USFM text seems like it would be better in some sort of `ts` file so it can be reused in multiple places than a `tsx` file.
___
*[`lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx` line 52 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-Ry1j1j0FINY8it_f:-O3-Ry1k2CMumz6xl_q2:b-api40k) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx#L52)):*
> ```XML
>       currentVerse = 0;
>     }
>     if (line.startsWith('\\v')) {
> ```

When I look at my test projects I can see that not all of them have verses starting on new lines. That is the norm, but I don't think the USFM spec requires it work this way from what I can tell. The same is true for chapters.


<!-- Sent from Reviewable.io -->

2024-07-29 22:40 UTC, irahopkinson requested changes
Looking good.

> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020#-:-O3-dWzRAkjjtA-Kh1jY:br2sbrj)* status: all files reviewed, 15 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/character-inventory.component.tsx` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-RX6E2hNzd_KtFAKz:-O3-RX6E2hNzd_KtFAL-:b-c4wsov) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/character-inventory.component.tsx#L29)):*
> ```XML
>   {
>     accessorKey: 'item',
>     header: ({ column }) => {
> ```

Nit use the simplified arrow function notation when only one thing is returned and no other code is needed, i.e.
```ts
    header: ({ column }) => (
      <Button onClick={() => column.toggleSorting(undefined)}>
        {itemLabel}
        {getSortingIcon(column.getIsSorted())}
      </Button>
    ),
```
It's ok to leave it as is if you are expecting to need to add other code inside the arrow function later. Here and below.
___
*[`extensions/src/platform-scripture/src/character-inventory.component.tsx` line 127 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-U6qn-Hhk0AzruElV:-O3-THlJ-75MzlYjjLd-:b-v53yup) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/character-inventory.component.tsx#L127)):*
> ```XML
> };
> 
> interface CharacterInventoryProps {
> ```

Nit we default to using `type` declarations unless it really is being used as an interface or needs to be dynamically added to.
___
*[`extensions/src/platform-scripture/src/inventory.web-view.tsx` line 46 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-V8TC0fGynlAq8SD9:-O3-V8TC0fGynlAq8SDA:b-iizlmr) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/inventory.web-view.tsx#L46)):*
> ```XML
>   let validItemsSetting: keyof ProjectSettingTypes;
>   let invalidItemsSetting: keyof ProjectSettingTypes;
>   if (webViewType === 'platformScripture.characterInventory') {
> ```

Nit this pattern (of only checking against one thing - `webviewType`) is usually better as a `switch` statement, esp. since we will be adding to this.
___
*[`extensions/src/platform-scripture/src/inventory.web-view.tsx` line 62 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-VnCQAojJQKbbEP83:-O3-VnCQAojJQKbbEP84:b-syq5s7) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/inventory.web-view.tsx#L62)):*
> ```XML
>   const [scope, setScope] = useState<string>('book');
>   const [text] = usePromise(
>     useCallback(async () => {
> ```

Nit use the simplified arrow function return notation.
___
*[`extensions/src/platform-scripture/src/inventory.web-view.tsx` line 75 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-VyUh2n4i0cTZocLl:-O3-VyUh2n4i0cTZocLm:bttcidb) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/inventory.web-view.tsx#L75)):*
> ```XML
>       approvedItems={validItems.split(' ')}
>       onApprovedItemsChange={(items: string[]) => {
>         if (setValidItems) setValidItems(items.join(' '));
> ```

You can use this simplified conditional call notation (here and below)
```ts
setValidItems?.(items.join(' '));
```



_Code quote:_
```XML
if (setValidItems) setValidItems(items.join(' '));
```
___
*[`extensions/src/platform-scripture/src/main.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-YydE-KLLckfC2xIW:-O3-YydE-KLLckfC2xIX:b-mvddto) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L51)):*
> ```XML
> };
> 
> const repeatableWordsValidator: ProjectSettingValidator<
> ```

Any reason you use an arrow function here and normal functions below? Use consistent declaration methods. Default to using standard functions unless arrow functions are needed.
___
*[`extensions/src/platform-scripture/src/main.ts` line 144 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-_8Go0tjBWyIfgWU-:-O3-_8Go0tjBWyIfgWU0:b9o9o8s) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L144)):*
> ```XML
> 
>   const characterInventoryWebViewProvider = new InventoryWebViewProvider(
>     'Character Inventory',
> ```

These title strings should be localized?



_Code quote:_
```XML
'Character Inventory'
```
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-aHfR5DaVcc9n_VMP:-O3-aHfR5DaVcc9n_VMQ:b-jaf4vz) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L37)):*
> ```XML
> };
> 
> export type Status = true | false | undefined;
> ```

I understand the need for status to be tristate rather than boolean but what does it mean for status to be `true` or `false`? What about using the `statusFilter` values directly here, i.e. `export type Status = 'approved' | 'unapproved' | 'unknown';`?


<!-- Sent from Reviewable.io -->

2024-07-30 16:45 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020)* status: 23 of 36 files reviewed, 11 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/src/platform-scripture/src/character-inventory.component.tsx` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-RX6E2hNzd_KtFAKz:-O31bObt1QeI1NKZMnNT:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/character-inventory.component.tsx#L29)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nit use the simplified arrow function notation when only one thing is returned and no other code is needed, i.e.
```ts
    header: ({ column }) => (
      <Button onClick={() => column.toggleSorting(undefined)}>
        {itemLabel}
        {getSortingIcon(column.getIsSorted())}
      </Button>
    ),
```
It's ok to leave it as is if you are expecting to need to add other code inside the arrow function later. Here and below.
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/character-inventory.component.tsx` line 127 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-U6qn-Hhk0AzruElV:-O31c4RfCc8howh3grbS:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/character-inventory.component.tsx#L127)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nit we default to using `type` declarations unless it really is being used as an interface or needs to be dynamically added to.
</blockquote></details>

Done
___
*[`extensions/src/platform-scripture/src/inventory.web-view.tsx` line 46 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-V8TC0fGynlAq8SD9:-O31cVND80C61FaPYbpA:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/inventory.web-view.tsx#L46)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nit this pattern (of only checking against one thing - `webviewType`) is usually better as a `switch` statement, esp. since we will be adding to this.
</blockquote></details>

Done
___
*[`extensions/src/platform-scripture/src/inventory.web-view.tsx` line 62 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-VnCQAojJQKbbEP83:-O31cdSTBLgf86M7tTvW:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/inventory.web-view.tsx#L62)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nit use the simplified arrow function return notation.
</blockquote></details>

Done
___
*[`extensions/src/platform-scripture/src/inventory.web-view.tsx` line 75 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-VyUh2n4i0cTZocLl:-O31cw0096Zac8nen7ga:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/inventory.web-view.tsx#L75)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

You can use this simplified conditional call notation (here and below)
```ts
setValidItems?.(items.join(' '));
```
</blockquote></details>

Done
___
*[`extensions/src/platform-scripture/src/main.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-YydE-KLLckfC2xIW:-O31dUV94dkywRpKsK5I:b-jlhsno) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L51)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Any reason you use an arrow function here and normal functions below? Use consistent declaration methods. Default to using standard functions unless arrow functions are needed.
</blockquote></details>

Not really, no. I was just keeping in line with the code that was already there
___
*[`extensions/src/platform-scripture/src/main.ts` line 89 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-Lo7w08wC-a6eg78s:-O31d0_65vyiIN1idXG5:bbs0b9k) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L89)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Should we be hard coding dialog sizes like this?
</blockquote></details>

I talked to TJ about this and for it seems to be what we want to do. Without defining explicit dimensions, the webview will default to something unusably small
___
*[`extensions/src/platform-scripture/src/main.ts` line 144 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-_8Go0tjBWyIfgWU-:-O31h-sk5vXhlWJ0FcdN:bo9395m) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L144)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

These title strings should be localized?
</blockquote></details>

Oops, absolutely. Done.
___
*[`extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-1jQt4Vaibhl1rd3w:-O33W5oYD60fW2g0F0x-:b-mi8lo5) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx#L104)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Whatever the logic is, you probably want this to live in a `ts` file so you can reuse it in running the check itself. Otherwise it has to be duplicated.
</blockquote></details>

Yes, we definitely want to do that, but at this point I'm not sure what the best place to put it is. I don't think it's general enough code for it to live in platform-bible-utils, and we don't have a dedicated place for checking code yet, afaik.
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-aHfR5DaVcc9n_VMP:-O31hDT34-NZMErOp-Qv:b-e1ritw) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L37)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I understand the need for status to be tristate rather than boolean but what does it mean for status to be `true` or `false`? What about using the `statusFilter` values directly here, i.e. `export type Status = 'approved' | 'unapproved' | 'unknown';`?
</blockquote></details>

Yeah, good to make it more explicit. Done.
___
*[`lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx` line 52 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-Ry1j1j0FINY8it_f:-O32xsTT-69TK5Cuopvr:b-s8f36q) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx#L52)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

When I look at my test projects I can see that not all of them have verses starting on new lines. That is the norm, but I don't think the USFM spec requires it work this way from what I can tell. The same is true for chapters.
</blockquote></details>

Thanks for pointing that out! I've changed the code so that the text is split o [...]

2024-07-31 04:08 UTC, irahopkinson requested changes
> Reviewed 12 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020)* status: all files reviewed, 8 unresolved discussions (waiting on @lyonsil and @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/character-inventory.component.tsx` line 39 at r3](https://reviewable.io/reviews/paranext/paranext-core/1020#-O35uEi49hkEey98ubyZ:-O35uEi49hkEey98uby_:bfi1cs0) ([raw file](https://github.com/paranext/paranext-core/blob/2f7d400f7c5b80319d81b1c1588de9520bea4551/extensions/src/platform-scripture/src/character-inventory.component.tsx#L39)):*
> ```XML
>   {
>     accessorKey: 'unicodeValue',
>     header: ({ column }) => {
> ```

You'll have to get rid of the `{ }` brackets to make this return the button.
___
*[`extensions/src/platform-scripture/src/main.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-YydE-KLLckfC2xIW:-O35wmcE0anq-TvNS1xL:b604fo4) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L51)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Not really, no. I was just keeping in line with the code that was already there
</blockquote></details>

Actually you added this arrow function in this PR whereas the one below that was existing is a standard function and you added 2 other standard functions. You should really make them consistent so change this to a standard function. I've made this non-blocking so you can approve it yourself.


<!-- Sent from Reviewable.io -->

2024-08-02 17:25 UTC, rolfheij-sil reviewed
New issues for [adding comments](https://github.com/paranext/paranext-core/issues/1038) and [adding unit tests](https://github.com/paranext/paranext-core/issues/1037)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020#-:-O3J0muN2xzV3YXLwTiz:b-we68ql)* status: 22 of 41 files reviewed, 6 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/src/platform-scripture/src/character-inventory.component.tsx` line 39 at r3](https://reviewable.io/reviews/paranext/paranext-core/1020#-O35uEi49hkEey98ubyZ:-O37fxWP50ebP1A8X4MN:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/2f7d400f7c5b80319d81b1c1588de9520bea4551/extensions/src/platform-scripture/src/character-inventory.component.tsx#L39)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

You'll have to get rid of the `{ }` brackets to make this return the button.
</blockquote></details>

Done
___
*[`extensions/src/platform-scripture/src/main.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-YydE-KLLckfC2xIW:-O37i2YtDyuBV7TADVtC:b2d8rx2) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L51)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Actually you added this arrow function in this PR whereas the one below that was existing is a standard function and you added 2 other standard functions. You should really make them consistent so change this to a standard function. I've made this non-blocking so you can approve it yourself.
</blockquote></details>

What I mean to say is that the existing Project Setting Validator functions were arrow functions, so I kept in line with that.
And the existing functions for opening the WebViews were standard functions, so I kept in line with that too.
Are you suggesting I change all Validator functions, including the pre-existing ones, to standard functions?
___
*[`lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-SMd27KM22k24r3IZ:-O3I2_SR3jSteo0a32oX:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx#L19)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Code that is working directly on USFM text seems like it would be better in some sort of `ts` file so it can be reused in multiple places than a `tsx` file.
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx` line 37 at r3](https://reviewable.io/reviews/paranext/paranext-core/1020#-O33ZlBz3n0jZXQ9Y8Bp:-O3I2V2ADSolygBU1wX9:bb33q1x) ([raw file](https://github.com/paranext/paranext-core/blob/2f7d400f7c5b80319d81b1c1588de9520bea4551/lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx#L37)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This code doesn't do what you expect. Try it in https://www.typescriptlang.org/play. You need double back slashes, and "id" will be treated as "i" and "d" separately.

Although this isn't super complicated code, it's nice for code like this to be in a `ts` file that includes tests to catch small mistakes. While we might not know exactly where we want all checks, could you move all the text parsing/manipulation code to `ts` files in this extension and add a few unit tests?
</blockquote></details>

Thanks, I've extracted it to a separate ts file. I'll create a new issue for adding unit tests that I'll work on when I'm back from my vacation


<!-- Sent from Reviewable.io -->

2024-08-02 17:26 UTC, rolfheij-sil reviewed
Also, thank you so much for reviewing. I know this was a huge PR again. I seem to struggle to keep my PRs small. Sorry, and thanks again!!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020#-:-O3J77Me-jFYGGmf9gVK:b-touyee)* status: 22 of 41 files reviewed, 6 unresolved discussions (waiting on @irahopkinson and @lyonsil)



<!-- Sent from Reviewable.io -->

2024-08-02 22:38 UTC, lyonsil submitted a review, later dismissed
Thanks for the updates! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020#-:-O3KEZPd2NC8sO1ZCOTY:bdzwnwj)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

___
*[`extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-1jQt4Vaibhl1rd3w:-O3KDH-S9dtyiNPc4LxE:bypupn7) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx#L104)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Yes, we definitely want to do that, but at this point I'm not sure what the best place to put it is. I don't think it's general enough code for it to live in platform-bible-utils, and we don't have a dedicated place for checking code yet, afaik.
</blockquote></details>

Thanks - we'll refactor as needed. It's just nice to keep data-focused logic out of UI-focused code.
___
*[`lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx` line 37 at r3](https://reviewable.io/reviews/paranext/paranext-core/1020#-O33ZlBz3n0jZXQ9Y8Bp:-O3KELHkBib3Y2IaIDO8:b-9755fn) ([raw file](https://github.com/paranext/paranext-core/blob/2f7d400f7c5b80319d81b1c1588de9520bea4551/lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx#L37)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Thanks, I've extracted it to a separate ts file. I'll create a new issue for adding unit tests that I'll work on when I'm back from my vacation
</blockquote></details>

Thank you!


<!-- Sent from Reviewable.io -->

2024-08-04 21:17 UTC, irahopkinson submitted a review, later dismissed
> Reviewed 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020)* status: all files reviewed, 5 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/main.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-YydE-KLLckfC2xIW:-O3UEis3-VtXdH-i3-gj:bmu4nsf) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L51)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

What I mean to say is that the existing Project Setting Validator functions were arrow functions, so I kept in line with that.
And the existing functions for opening the WebViews were standard functions, so I kept in line with that too.
Are you suggesting I change all Validator functions, including the pre-existing ones, to standard functions?
</blockquote></details>

Only in this file. Resolve this as you see fit.
___
*[`extensions/src/platform-scripture/src/main.ts` line 99 at r4](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3UBet8EtKxE5VazEMc:-O3UBet8EtKxE5VazEMd:b-kywf2i) ([raw file](https://github.com/paranext/paranext-core/blob/2e2a7531992925379c09f740625a99956556db7f/extensions/src/platform-scripture/src/main.ts#L99)):*
> ```XML
>   webViewType: string;
> 
>   constructor(title: LocalizeKey, webViewType: string) {
> ```

Nit probably better to rename this to `titleKey` also so users of the class know what to provide.



_Code quote:_
```XML
title
```
___
*[`extensions/src/platform-scripture/src/main.ts` line 102 at r4](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3UC8k0BRyEpe7gkcsy:-O3UC8k0BRyEpe7gkcsz:b-bqf1d3) ([raw file](https://github.com/paranext/paranext-core/blob/2e2a7531992925379c09f740625a99956556db7f/extensions/src/platform-scripture/src/main.ts#L102)):*
> ```XML
>     this.titleKey = title;
>     this.webViewType = webViewType;
>   }
> ```

Nit you can simplify all this (including the property declarations) to this:
```ts
constructor(public titleKey: LocalizeKey, public webViewType: string) {}
```
This constructor declares the properties and assigns them the incoming values.



_Code quote:_
```XML
  titleKey: LocalizeKey;
  webViewType: string;

  constructor(title: LocalizeKey, webViewType: string) {
    this.titleKey = title;
    this.webViewType = webViewType;
  }
```


<!-- Sent from Reviewable.io -->

2024-08-05 19:23 UTC, irahopkinson requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/main.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-YydE-KLLckfC2xIW:-O3Yxxom9d2rX1mWljaT:b-780c1) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L51)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Only in this file. Resolve this as you see fit.
</blockquote></details>

There is no need to change these if you are just going to leave them assigned to a `const`. The simpler declaration here is
```ts
async function repeatableWordsValidator(newValue): ProjectSettingValidator<'platformScripture.repeatableWords' | 'platformScripture.nonRepeatableWords'> {
  return typeof newValue === 'string';
}
```
If that doesn't work for validators leave them as they were. I did say you could resolve this yourself if you wanted to leave them as they were. I've changed this to blocking as this isn't better.


<!-- Sent from Reviewable.io -->

2024-08-07 08:39 UTC, Sebastian-ubs commented
Hi @rolfheij-sil I have some style improvements, that could be merged into this or to main after this was merged:
- https://github.com/paranext/paranext-core/pull/1048

Actually I think the repeated words PR is already too big and long running.

2024-08-07 16:19 UTC, tjcouch-sil reviewed
Make some adjustments in Rolf's absence. Let's see if we can get this in for Sebastian to get unblocked :)

Note: for some reason, the `split(text, /[\s]+/)` in `inventory-utils.ts` is not working for me. I made a unit test that runs it successfully, and changing it to `text.split(/[\s]+/)` works. I don't know what's wrong. Just noting in case Rolf has any ideas. I'd like to get this in and investigate later, though.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020#-:-O3hc_WS-6696wcsGuDm:b7m5nw5)* status: 40 of 42 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/src/platform-scripture/src/main.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-YydE-KLLckfC2xIW:-O3hAZQNAi14UnTVkGMP:b-7q8zap) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L51)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

There is no need to change these if you are just going to leave them assigned to a `const`. The simpler declaration here is
```ts
async function repeatableWordsValidator(newValue): ProjectSettingValidator<'platformScripture.repeatableWords' | 'platformScripture.nonRepeatableWords'> {
  return typeof newValue === 'string';
}
```
If that doesn't work for validators leave them as they were. I did say you could resolve this yourself if you wanted to leave them as they were. I've changed this to blocking as this isn't better.
</blockquote></details>

These were arrow functions so they could get their type from `ProjectSettingValidator`. I reformatted them all (Rolf told me it was ok if we make some minor adjustments to get this through if we need, and Sebastian is waiting on this to do some other stuff) to be consistent arrow functions.


<!-- Sent from Reviewable.io -->

2024-08-07 18:31 UTC, irahopkinson submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/platform-scripture/src/main.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/1020#-O3-YydE-KLLckfC2xIW:-O3i5ao9DYAP84dI8Fed:b96skep) ([raw file](https://github.com/paranext/paranext-core/blob/945097e2a2b98c04b314eb280d99611f013cbdd5/extensions/src/platform-scripture/src/main.ts#L51)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

These were arrow functions so they could get their type from `ProjectSettingValidator`. I reformatted them all (Rolf told me it was ok if we make some minor adjustments to get this through if we need, and Sebastian is waiting on this to do some other stuff) to be consistent arrow functions.
</blockquote></details>

Looks like these need to be arrow functions. @rolfheij-sil sorry for messing with this.


<!-- Sent from Reviewable.io -->

2024-08-07 21:48 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1020#-:-O3ioB_T5xikxY08rCMh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-07 21:57 UTC, merged