#881: Moved component into advanced folder
paranext/paranext-core pull request #1025
Opened 2024-07-24 04:37 UTC by tombogle

removed some diagnostic text from header columns, and added some classes to get the scrollbar to appear when contents don't fit in the webview (this is a baby step toward actually getting the table body to scroll, which is what we really want).

2024-07-25 09:43 UTC, Sebastian-ubs commented
Hi,
moving looks good.
I will not comment on missing alias imports as most of them should be fixed when https://github.com/paranext/paranext-core/pull/1026#pullrequestreview-2196671921 is merged (either you or I would need to pull the other ones changes in).

Things related to scrolling I was wondering if we can have a look together. Should be doable even in html 😉
Could you check out how shadcn is doing it? E.g.
- in the "mail" table https://ui.shadcn.com/examples/mail
- in the "playlists" nagivation https://ui.shadcn.com/examples/music
- for the whole dashboard-5 https://ui.shadcn.com/blocks#dashboard-05

2024-07-25 12:29 UTC, tombogle commented
Re: scrolling, since there is now a separate issue for this (#1024) and the original issue has been moved to done, I'm going to stop trying to get it to work as part of this issue. It is "kind of" working now.

2024-07-25 17:18 UTC, Sebastian-ubs requested changes

2024-07-25 17:18 UTC, Sebastian-ubs commented on lib/platform-bible-react/src/components/advanced-components/scripture-results-viewer/scripture-results-viewer.component.tsx
> +                    /* For sticky column headers to work, we probably need to change the default definition of the shadcn Table component. See https://github.com/shadcn-ui/ui/issues/1151 */
please check with Rolf, as he mentioned he solved it

2024-07-25 17:18 UTC, Sebastian-ubs commented on lib/platform-bible-react/src/index.ts
> +export { default as ScriptureResultsViewer } from './components/advanced-components/scripture-results-viewer/scripture-results-viewer.component';
use alias imports

2024-07-25 17:18 UTC, Sebastian-ubs commented on lib/platform-bible-react/src/index.ts
> +} from './components/advanced-components/scripture-results-viewer/scripture-results-viewer.component';
use alias imports

2024-07-25 18:01 UTC, tombogle commented on lib/platform-bible-react/src/components/advanced-components/scripture-results-viewer/scripture-results-viewer.component.tsx
> +                    /* For sticky column headers to work, we probably need to change the default definition of the shadcn Table component. See https://github.com/shadcn-ui/ui/issues/1151 */
Since his changes haven't been merged yet, I figured this could be a follow-on task. Since the headers do not currently even get displayed in Platform, it's a pretty low priority.

2024-07-25 18:16 UTC, tombogle commented on lib/platform-bible-react/src/index.ts
> +export { default as ScriptureResultsViewer } from './components/advanced-components/scripture-results-viewer/scripture-results-viewer.component';
I don't understand what you're suggesting. These exports seem to be following the same pattern as all the other ones.

2024-07-26 06:39 UTC, Sebastian-ubs approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 14 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1025#-:-O2hl1vzDxT5so81nu-2:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2024-07-26 06:41 UTC, Sebastian-ubs commented on lib/platform-bible-react/src/index.ts
> +export { default as ScriptureResultsViewer } from './components/advanced-components/scripture-results-viewer/scripture-results-viewer.component';
sorry, I overlooked that those are exports, not imports.

2024-07-26 06:44 UTC, Sebastian-ubs approved these changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1025)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`lib/platform-bible-react/src/index.ts` line 36 at r3](https://reviewable.io/reviews/paranext/paranext-core/1025#gh-1691854162:-O2hlwbEAlRaf2OqEX02:bb6ywmx) ([raw file](https://github.com/paranext/paranext-core/blob/e454f726c2e2244faaa9f1d3206f422ce710b449/lib/platform-bible-react/src/index.ts#L36)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

sorry, I overlooked that those are exports, not imports. 
</blockquote></details>

LGTM
___
*[`lib/platform-bible-react/src/index.ts` line 44 at r3](https://reviewable.io/reviews/paranext/paranext-core/1025#gh-1691854510:-O2hlyU1CkgWbGPJSUTh:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/e454f726c2e2244faaa9f1d3206f422ce710b449/lib/platform-bible-react/src/index.ts#L44)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

use alias imports
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/advanced-components/scripture-results-viewer/scripture-results-viewer.component.tsx` line 407 at r3](https://reviewable.io/reviews/paranext/paranext-core/1025#gh-1691853521:-O2hliq_0FqIEWFi4SMf:bb6ywmx) ([raw file](https://github.com/paranext/paranext-core/blob/e454f726c2e2244faaa9f1d3206f422ce710b449/lib/platform-bible-react/src/components/advanced-components/scripture-results-viewer/scripture-results-viewer.component.tsx#L407)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Since his changes haven't been merged yet, I figured this could be a follow-on task. Since the headers do not currently even get displayed in Platform, it's a pretty low priority.
</blockquote></details>

LGTM


<!-- Sent from Reviewable.io -->

2024-07-26 12:43 UTC, merged