feat: added more components
paranext/paranext-core pull request #1034
Opened 2024-07-31 20:53 UTC by ssikande

added footer, more-info, message, and version history
![image](https://github.com/user-attachments/assets/f2952702-74f2-4b71-8fab-429735c1f189)

2024-07-31 21:41 UTC, jolierabideau reviewed
Seeing these prettier warnings in all the files because `classNames` are out of order. Install the these VSCode extensions: 
- Tailwind CSS Intellisense
- Prettier ESLint

![Screenshot 2024-07-31 at 5 34 06 PM](https://github.com/user-attachments/assets/986fe203-7c76-4aa9-84da-65603aaa389d)

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/footer.component.tsx
> +  versionHistory: Record<string, { date: string; description: string }>;
Need comments on the props

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/footer.component.tsx
> +    <div className="pr-border-t pr-pt-4 pr-pb-4">
Do you have the Tailwind CSS Intellisense vscode extension? I'm seeing prettier errors that classNames in a bunch of lines are in the wrong order.

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/footer.component.tsx
> +  versionHistory: Record<string, { date: string; description: string }>;
Isn't this type supposed to be VersionHistory type ?

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/message.component.tsx
> +export default function Message({ message }: MessageProps) {
What message is this specifically? When is this used? We need a more specific name here

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/more-info.component.tsx
> +  moreInfoUrl: string;
Need comments on these props

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/more-info.component.tsx
> + * @param extension The extension object that contains the details of the extension
This needs updated

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx
> +  description: string;
Need comments on these props

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx
> +export type VersionHistoryType = Record<string, VersionInformation>;
Can this just be called `VersionHistory`

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/index.ts
> +export { default as VersionHistory,
Need a new line here, prettier error

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/preview/components/advanced.component.tsx
> +          <VerticalTabsTrigger value="Marketplace Components">Marketplace Components</VerticalTabsTrigger>
Maybe you should combine these into one marketplace components tab and add the buttons in there

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/preview/components/advanced/marketplace.example.component.tsx
> +import MoreInfo from "@/components/advanced-components/extension-marketplace/more-info.component";
prettier errors - need ' not "

2024-07-31 21:41 UTC, jolierabideau commented on lib/platform-bible-react/src/preview/components/advanced/marketplace.example.component.tsx
> +      <Footer publisherDisplayName="Publisher" fileSize={123} locales={['es', 'en', 'fr','ur']} versionHistory={{'1.0': {date: '2021-01-01', description: 'Initial release'}}} />
prettier errors - new lines

2024-08-01 12:57 UTC, Sebastian-ubs commented
To be able to use those newly added components in marketplace, I guess you will have to run `rpm run build` in `paranext-core` root directory and check in the output files as well.

2024-08-01 13:14 UTC, jolierabideau requested changes
> Reviewed 7 of 7 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1034)* status: all files reviewed, 2 unresolved discussions (waiting on @ssikande)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/message.component.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1034#gh-1699130230:-O3D3EgNBMTgpEREmA0x:b-lhixcu) ([raw file](https://github.com/paranext/paranext-core/blob/3f095ac126abe850145b315848b0a7aadfaf243f/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/message.component.tsx#L9)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

What message is this specifically? When is this used? We need a more specific name here
</blockquote></details>

Still need to address this
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1034#gh-1699132517:-O3D3SA57edXua6bShsK:b-vfofkt) ([raw file](https://github.com/paranext/paranext-core/blob/3f095ac126abe850145b315848b0a7aadfaf243f/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx#L9)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Can this just be called `VersionHistory`
</blockquote></details>

This still needs to be addressed


<!-- Sent from Reviewable.io -->

2024-08-01 13:17 UTC, ssikande reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1034)* status: all files reviewed, 2 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/message.component.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1034#gh-1699130230:-O3D49JtEmc3wVgj_w1H:by2eqh6) ([raw file](https://github.com/paranext/paranext-core/blob/3f095ac126abe850145b315848b0a7aadfaf243f/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/message.component.tsx#L9)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Still need to address this
</blockquote></details>

oops this is for the no extensions found message. I was wondering if this component needs to be generalized for other use cases then it should named something different too


<!-- Sent from Reviewable.io -->

2024-08-01 13:19 UTC, ssikande reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1034)* status: all files reviewed, 2 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1034#gh-1699132517:-O3D4puL0E5k9T6-qz12:b-dcwl2s) ([raw file](https://github.com/paranext/paranext-core/blob/3f095ac126abe850145b315848b0a7aadfaf243f/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx#L9)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

This still needs to be addressed
</blockquote></details>

the component is already named VersionHistory, is there something else i can name it


<!-- Sent from Reviewable.io -->

2024-08-01 13:20 UTC, jolierabideau requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1034)* status: all files reviewed, 2 unresolved discussions (waiting on @ssikande)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/message.component.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1034#gh-1699130230:-O3D56MkExHh7_5IClUF:b-5jv9x3) ([raw file](https://github.com/paranext/paranext-core/blob/3f095ac126abe850145b315848b0a7aadfaf243f/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/message.component.tsx#L9)):*
<details><summary><i>Previously, ssikande wrote…</i></summary><blockquote>

oops this is for the no extensions found message. I was wondering if this component needs to be generalized for other use cases then it should named something different too
</blockquote></details>

Oh I see, let's keep it as NoExtensionsFound for now so that it's clear what it is
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1034#gh-1699132517:-O3D5FAw4rJCR3S9xCEg:b-sbpss0) ([raw file](https://github.com/paranext/paranext-core/blob/3f095ac126abe850145b315848b0a7aadfaf243f/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx#L9)):*
<details><summary><i>Previously, ssikande wrote…</i></summary><blockquote>

the component is already named VersionHistory, is there something else i can name it
</blockquote></details>

It's named `VersionHistoryType` it should just be `VersionHistory`


<!-- Sent from Reviewable.io -->

2024-08-01 13:55 UTC, ssikande reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1034)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1034#gh-1699132517:-O3DCtUKDp_BjO8DWS-j:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/3f095ac126abe850145b315848b0a7aadfaf243f/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx#L9)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

It's named `VersionHistoryType` it should just be `VersionHistory`
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/message.component.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1034#gh-1699130230:-O3DCr972qPPk2shsUIA:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/3f095ac126abe850145b315848b0a7aadfaf243f/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/message.component.tsx#L9)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Oh I see, let's keep it as NoExtensionsFound for now so that it's clear what it is
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-01 13:55 UTC, jolierabideau reviewed
One more thing- it would be helpful to our test team if we could add an `id` prop onto the components

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1034#-:-O3DCHWL3UsmgVE4C21t:b-vcuzut)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-01 13:56 UTC, ssikande reviewed
Which ones would you like to do that for?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1034#-:-O3DDWYb63-CVrOmgBrU:b-s4m5tf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-01 13:57 UTC, captaincrazybro commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/version-history.component.tsx
> +export type VersionHistoryType = Record<string, VersionInformation>;
This would conflict with the component named `VersionHistory`

2024-08-01 13:57 UTC, captaincrazybro submitted a review, later dismissed
LGTM!

2024-08-01 15:03 UTC, jolierabideau approved these changes
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1034)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-01 15:11 UTC, merged