feat: make buttons inherit stuff
paranext/paranext-core pull request #1035
Opened 2024-08-01 15:56 UTC by ssikande

As per Sebastians code:https://github.com/paranext/paranext-core/tree/make-disable-button-inherit-button
Made changes so the buttons also inherit more props

2024-08-01 17:00 UTC, jolierabideau requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1035)* status: all files reviewed, 2 unresolved discussions (waiting on @ssikande)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/1035#-O3DsKUl-K7pHsXH-Rlt:-O3DsKUm0dv0Scl3ho6n:b-46ax2h) ([raw file](https://github.com/paranext/paranext-core/blob/b979c9230856c9e63db09acafdc39bb4df31d00a/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L37)):*
> ```XML
> };
> 
> export type FilterDropdownProps = {
> ```

I know the DropdownMenu doesn't have an id included. But can we extend the Dropdown menu props on this as well, like how you did in the buttons? And then keep the id the way you have it right now 
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 54 at r1](https://reviewable.io/reviews/paranext/paranext-core/1035#-O3Ds2kd3ohqqC-P13lJ:-O3Ds2kd3ohqqC-P13lK:bt3g9fa) ([raw file](https://github.com/paranext/paranext-core/blob/b979c9230856c9e63db09acafdc39bb4df31d00a/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L54)):*
> ```XML
> export default function FilterDropdown({ id, groups }: FilterDropdownProps) {
>   return (
>     <div id={id}>
> ```

Interesting that the DropdownMenu doesn't have an `id` on it. Can you add a todo here to remove that when we add an id on the shadcn dropdown menu.


<!-- Sent from Reviewable.io -->

2024-08-01 21:09 UTC, jolierabideau requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1035)* status: all files reviewed, 1 unresolved discussion (waiting on @ssikande)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/1035#-O3DsKUl-K7pHsXH-Rlt:-O3ElCWT80s4Uy_KmybN:bxorr8n) ([raw file](https://github.com/paranext/paranext-core/blob/b979c9230856c9e63db09acafdc39bb4df31d00a/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L37)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I know the DropdownMenu doesn't have an id included. But can we extend the Dropdown menu props on this as well, like how you did in the buttons? And then keep the id the way you have it right now
</blockquote></details>

Ohh there aren't props exported for just `DropdownMenu`?  Then let's wait on this, sorry about that. There are different things available on the `DropdownMenu` and `DropdownMenuContent` so I don't want to extend `DropdownMenuContent`


<!-- Sent from Reviewable.io -->

2024-08-01 21:33 UTC, ssikande reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1035)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/1035#-O3DsKUl-K7pHsXH-Rlt:-O3Er5e56EOPBNXvINOA:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/b979c9230856c9e63db09acafdc39bb4df31d00a/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L37)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Ohh there aren't props exported for just `DropdownMenu`?  Then let's wait on this, sorry about that. There are different things available on the `DropdownMenu` and `DropdownMenuContent` so I don't want to extend `DropdownMenuContent`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-02 08:26 UTC, Sebastian-ubs requested changes

2024-08-02 08:26 UTC, Sebastian-ubs commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/buttons/enable-button.component.tsx
> +  id,
is there a benefit of mentioning "id" specifically here (and for the other buttons)? It should already come with `props` coming from ButtonProps as an optional parameter, right?

2024-08-02 08:26 UTC, Sebastian-ubs commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx
> +      {' '}
this whitepace string should not be needed

2024-08-02 12:45 UTC, ssikande commented on lib/platform-bible-react/src/components/advanced-components/extension-marketplace/buttons/enable-button.component.tsx
> +  id,
i added these as per Jolie's comment for testing. Jolie mentiioned that Roopa uses optional ids on the components to test them. But if the ButtonProps already contains an id parameter for testing i can go ahead and remove those changes!

2024-08-02 13:24 UTC, ssikande reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1035)* status: all files reviewed, 2 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 55 at r3](https://reviewable.io/reviews/paranext/paranext-core/1035#gh-1701491585:-O3IFqJG9XsBgHiIFQRd:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4624295c1573e8dd8f5bc6a297fc553e1599497e/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L55)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

this whitepace string should not be needed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-02 13:52 UTC, ssikande reviewed
> Reviewed 1 of 11 files at r1, 10 of 10 files at r4, all commit messages.
> Dismissed @Sebastian-ubs from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1035)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-02 13:55 UTC, Sebastian-ubs approved these changes
> Reviewed 1 of 11 files at r1, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1035)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-02 13:55 UTC, merged