try to link about tab to menu (not working)
paranext/paranext-core pull request #1060
Opened 2024-08-08 16:38 UTC by Sebastian-ubs

2024-08-09 13:52 UTC, Sebastian-ubs commented
![grafik](https://github.com/user-attachments/assets/445687ba-58ed-42ec-82ff-b5d8e237dedd)
😢

2024-08-09 16:55 UTC, Sebastian-ubs commented
Now this works.

TODOs:
- [ ] rename "about" to "showAboutDialog" to adher to the [code style guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide)
- [ ] check if layout works without a last single tab (in here switched to "test tab 1", but if possible remove this)
- [ ] get a PR review

So either keep this pr open until I am back in September or work on those remaining things on your own :-)

2024-09-11 08:09 UTC, Sebastian-ubs commented
Also without tabs Platform can be started and new tabs can be added via "Open Scripture Editor" or "Open Resource Viewer"

![grafik](https://github.com/user-attachments/assets/de15aedb-1a9e-40c6-9c8b-72210acdebce)

Completely idependent of this change: Throwing away the last tab produces and error, but everything seems to continue to work
> react-dom.development.js:86 Warning: Attempted to synchronously unmount a root while React was already rendering. React cannot finish unmounting the root until the current render has completed, which may lead to a race condition.
    at div
    at DockBox (http://localhost:1212/renderer.dev.js:54158:9)
    at div
    at DockLayout (http://localhost:1212/renderer.dev.js:54706:9)
    at DockLayoutWrapper (http://localhost:1212/renderer.dev.js:113249:106)
    at PlatformDockLayout (http://localhost:1212/renderer.dev.js:113999:72)
    at Main
    at RenderedRoute (http://localhost:1212/renderer.dev.js:102295:5)
    at Routes (http://localhost:1212/renderer.dev.js:102985:5)
    at Router (http://localhost:1212/renderer.dev.js:102919:15)
    at MemoryRouter (http://localhost:1212/renderer.dev.js:102814:5)
    at App

2024-09-11 08:27 UTC, Sebastian-ubs commented
Note that new dialogs open up each time, that you click the menu entry, but I think this is fine for now - maybe even good for playing with many windows

2024-09-11 18:06 UTC, tjcouch-sil requested changes
Thanks for the hard work on this! Looks like a good improvement! Few things to adjust.

Sadly, for some reason, when I delete `dock-saved-layout` from localstorage, refresh, open the about tab, then open the scripture editor, the about tab disappears and no scripture editor appears. Things get even weirder after that. I haven't seen this problem before, but I also pretty much haven't ever closed all my tabs since I discovered long ago the problem with not being able to dock things once you close all tabs. Because this seems to make more apparent the unstable situation with no tabs, I think we will need to wait to merge this til after we make the demo branch.

> Reviewed 2 of 10 files at r2, 9 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060#-:-O6XFHFcCY_TQOXF04cd:b6irpdu)* status: all files reviewed, 4 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`extensions/src/platform-scripture/src/main.ts` line 146 at r5](https://reviewable.io/reviews/paranext/paranext-core/1060#-O6XEXaY3eC8LrfQXdvQ:-O6XEXaY3eC8LrfQXdvR:bea9aep) ([raw file](https://github.com/paranext/paranext-core/blob/6b1a55ccec97b479b6061cd4961de8916e37537e/extensions/src/platform-scripture/src/main.ts#L146)):*
> ```XML
>   );
> 
>   const showAboutDialogPromise = papi.commands.registerCommand('platform.about', async () =>
> ```

This command belongs in core, not in an extension. Could you maybe move this to the dialog service? Maybe similar to how these web view service commands are registered https://github.com/paranext/paranext-core/blob/link-about-tab-to-menu/src/renderer/services/web-view.service-host.ts#L1344
___
*[`extensions/src/platform-scripture/src/main.ts` line 147 at r5](https://reviewable.io/reviews/paranext/paranext-core/1060#-O6XF4xa5O-waQBC-Q1n:-O6XF4xa5O-waQBC-Q1o:b-epwv8z) ([raw file](https://github.com/paranext/paranext-core/blob/6b1a55ccec97b479b6061cd4961de8916e37537e/extensions/src/platform-scripture/src/main.ts#L147)):*
> ```XML
> 
>   const showAboutDialogPromise = papi.commands.registerCommand('platform.about', async () =>
>     papi.dialogs.showAboutDialog(),
> ```

I believe this needs to be returned in order to make this command function properly wait on the dialog.
___
*[`extensions/src/platform-scripture/src/types/platform-scripture.d.ts` line 653 at r5](https://reviewable.io/reviews/paranext/paranext-core/1060#-O6XF05M1i98NZGZgGiG:-O6XF05M1i98NZGZgGiH:b-5qnunp) ([raw file](https://github.com/paranext/paranext-core/blob/6b1a55ccec97b479b6061cd4961de8916e37537e/extensions/src/platform-scripture/src/types/platform-scripture.d.ts#L653)):*
> ```XML
> 
>   export interface CommandHandlers {
>     'platform.about': (projectId?: string | undefined) => Promise<string | undefined>;
> ```

This would also move to `papi-shared-types.ts` when moving the command. Also please add a JSDoc :)
___
*[`src/shared/services/dialog.service-model.ts` line 37 at r5](https://reviewable.io/reviews/paranext/paranext-core/1060#-O6X9XoxE_h00kjqraKP:-O6X9XoyDO88AV-JfjDE:b-q7276y) ([raw file](https://github.com/paranext/paranext-core/blob/6b1a55ccec97b479b6061cd4961de8916e37537e/src/shared/services/dialog.service-model.ts#L37)):*
> ```XML
>    *
>    * @param options Various options for configuring the dialog that shows
>    * @returns Returns the user's selected project id or `undefined` if the user cancels
> ```

Is anything returned from the about dialog? Should this be changed?


<!-- Sent from Reviewable.io -->

2024-09-11 18:08 UTC, tjcouch-sil reviewed
Maybe the disappearing is somehow related to it being a dialog. We should probably adjust things so opening a dialog doesn't change the latest place a tab was opened. That way, new tabs won't open as a tab in the same group as dialogs.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060#-:-O6XG8if7GVkM1m1r283:b38e3jf)* status: all files reviewed, 4 unresolved discussions (waiting on @Sebastian-ubs)



<!-- Sent from Reviewable.io -->

2024-11-14 00:20 UTC, irahopkinson commented
@Sebastian-ubs nudge on this PR. If you aren't finishing this soon then perhaps close it?

2024-11-15 09:59 UTC, Sebastian-ubs commented
Thanks, I wanted to work on it, but has no prio right now. Changes done in here are still valid, but seem not enough. Will wait until https://github.com/paranext/ux/issues/94 gets priority.

2024-12-12 17:07 UTC, Sebastian-ubs commented
@tjcouch-sil when we have the home screen, could we switch the default "about" tab out with the "home" and finish putting about in a dialog?

2025-01-04 01:06 UTC, tjcouch-sil commented
@Sebastian-ubs seems reasonable! Might need an issue and to be prioritized

2025-04-09 16:16 UTC, rolfheij-sil reviewed
> Reviewed 1 of 1 files at r8, 85 of 85 files at r10.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060)* status: 86 of 102 files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/main.ts` line 146 at r5](https://reviewable.io/reviews/paranext/paranext-core/1060#-O6XEXaY3eC8LrfQXdvQ:-ONQCuoqD1GmSwbru7uS:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/6b1a55ccec97b479b6061cd4961de8916e37537e/extensions/src/platform-scripture/src/main.ts#L146)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This command belongs in core, not in an extension. Could you maybe move this to the dialog service? Maybe similar to how these web view service commands are registered https://github.com/paranext/paranext-core/blob/link-about-tab-to-menu/src/renderer/services/web-view.service-host.ts#L1344
</blockquote></details>

Done
___
*[`extensions/src/platform-scripture/src/main.ts` line 147 at r5](https://reviewable.io/reviews/paranext/paranext-core/1060#-O6XF4xa5O-waQBC-Q1n:-ONQD-Lj4Gb78UnPFyU6:b-d8u2no) ([raw file](https://github.com/paranext/paranext-core/blob/6b1a55ccec97b479b6061cd4961de8916e37537e/extensions/src/platform-scripture/src/main.ts#L147)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe this needs to be returned in order to make this command function properly wait on the dialog.
</blockquote></details>

I don't think this is relevant anymore
___
*[`src/shared/services/dialog.service-model.ts` line 37 at r5](https://reviewable.io/reviews/paranext/paranext-core/1060#-O6X9XoxE_h00kjqraKP:-ONQ6iip0_IL6a3WF6xw:b4yukk5) ([raw file](https://github.com/paranext/paranext-core/blob/6b1a55ccec97b479b6061cd4961de8916e37537e/src/shared/services/dialog.service-model.ts#L37)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is anything returned from the about dialog? Should this be changed?
</blockquote></details>

I've trimmed the definition down to the essentials
___
*[`extensions/src/platform-scripture/src/types/platform-scripture.d.ts` line 653 at r5](https://reviewable.io/reviews/paranext/paranext-core/1060#-O6XF05M1i98NZGZgGiG:-ONQ74rW3YJz0i50WQyD:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/6b1a55ccec97b479b6061cd4961de8916e37537e/extensions/src/platform-scripture/src/types/platform-scripture.d.ts#L653)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This would also move to `papi-shared-types.ts` when moving the command. Also please add a JSDoc :)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2025-04-09 16:53 UTC, rolfheij-sil reviewed
I've revived the branch, processed the review comments and made some additional improvements. It's working as intended, but I'm unsure about two things:

1. I see the `Home` tab open when the dock layout info in local storage is empty, so that's good. However, we haven't explicitly set the `Home` tab to open as default, like we had the `About` tab configured as a default before. Do we need to do this still? And if so, where do we configure this?
2. The `platform.about` command returns an error after 10 seconds, so something is wrong with the command. Could it have something to do with the return type being `void`? Perhaps this is currently not supported for dialogs, maybe? See screenshot below.
![image.png](https://files.reviewableusercontent.io/images/reviewable/108285668/z2npKG6eVd0YT5xPdXr3_LiD/image.png)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060#-:-ONQS60X1UdW0vLeU5wL:bmg4amg)* status: 86 of 102 files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2025-04-09 16:57 UTC, rolfheij-sil reviewed
> Reviewed 1 of 12 files at r6, 5 of 12 files at r11, 3 of 4 files at r12, 1 of 1 files at r13, 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060)* status: all files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2025-04-09 17:51 UTC, tjcouch-sil requested changes
Thanks for the updates! We're close!!

1. I'd say we should indeed change things so `Home` opens if localstorage is empty. You'll need to look in localstorage at the structure for a home tab and put it in `test-layout.data.ts`, replacing the about tab at the bottom of the file.
2. This is happening because the dialog doesn't return anything unless you close it and there's a bug that makes dialogs fail to submit if they're open for more than 10 seconds. It needs to submit something. Answered in a comment on the about dialog file

> Reviewed 1 of 12 files at r6, 1 of 1 files at r8, 85 of 85 files at r10, 5 of 12 files at r11, 3 of 4 files at r12, 1 of 1 files at r13, 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060#-:-ONQdlZPDz354smZf-hz:bi8wfeo)* status: all files reviewed, 3 unresolved discussions

___
*[`src/renderer/services/dialog.service-host.ts` line 405 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONQdGb04lxoOhBUdH2M:-ONQdGb04lxoOhBUdH2N:b-qmvsob) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/services/dialog.service-host.ts#L405)):*
> ```XML
>   });
> 
>   registerCommand('platform.about', showAboutDialog);
> ```

This needs to be awaited and unsubscribed like the request handlers above. Please move this up and do the same kind of `unsubPromises.push` thing as is done with the dialog request handlers above.
___
*[`src/renderer/components/dialogs/about-dialog.component.tsx` line 39 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONQbC_4EJv4ge9mN326:-ONQbC_5B2-f7rbElbK3:b1baolp) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/components/dialogs/about-dialog.component.tsx#L39)):*
> ```XML
> };
> 
> function AboutDialog() {
> ```

One way you could solve the long request error is by pulling in the prop `submitDialog` here and running it immediately on first render in a `useEffect`.

Example of `submitDialog`: https://github.com/paranext/paranext-core/blob/pt-3038-software-version-info/src/renderer/components/dialogs/select-project.dialog.tsx#L22
___
*[`src/renderer/components/dialogs/about-dialog.component.tsx` line 96 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONQc0Wu9S-rpFV5iKca:-ONQc0Wu9S-rpFV5iKcb:b6zyb1) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/components/dialogs/about-dialog.component.tsx#L96)):*
> ```XML
>   ...DIALOG_BASE,
>   tabType: ABOUT_DIALOG_TYPE,
>   defaultTitle: 'About',
> ```

This needs to be localized. I imagine there is already a string for it; just need to get it localized somehow. Looks like `DialogOptions.title` already can accept a LocalizeKey, so it may be easy


<!-- Sent from Reviewable.io -->

2025-04-09 22:07 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060)* status: all files reviewed, 4 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`src/renderer/services/dialog.service-host.ts` line 242 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONRZ9eMCgA6On3C2-U1:-ONRZ9eMCgA6On3C2-U2:bvusept) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/services/dialog.service-host.ts#L242)):*
> ```XML
> // on the dialogService - see `dialog.service-model.ts` for JSDoc
> async function showAboutDialog(): Promise<void> {
>   return showDialog(ABOUT_DIALOG.tabType);
> ```

There is no response to go back to the user for this dialog, right? Some dialogs return data (e.g., which project did the user select?). I don't think this returns anything. In that case, you could probably wrap `showDialog` in an IIFE that includes try/catch internally and return immediately. There is no need for the network service to wait for `showDialog` to return since there is nothing interesting/useful to return. That should get rid of the time out error.


<!-- Sent from Reviewable.io -->

2025-04-10 12:11 UTC, rolfheij-sil reviewed
Thanks for helping out!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060#-:-ONUamXi865NVjqwgDlR:b-hlo2yt)* status: 87 of 102 files reviewed, 4 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`src/renderer/services/dialog.service-host.ts` line 242 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONRZ9eMCgA6On3C2-U1:-ONUag7a19ff3Hydria8:bhrp3k1) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/services/dialog.service-host.ts#L242)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

There is no response to go back to the user for this dialog, right? Some dialogs return data (e.g., which project did the user select?). I don't think this returns anything. In that case, you could probably wrap `showDialog` in an IIFE that includes try/catch internally and return immediately. There is no need for the network service to wait for `showDialog` to return since there is nothing interesting/useful to return. That should get rid of the time out error.
</blockquote></details>

Yep, I think that works
___
*[`src/renderer/services/dialog.service-host.ts` line 405 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONQdGb04lxoOhBUdH2M:-ONUWmU77lQS60UXebtu:btwaud0) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/services/dialog.service-host.ts#L405)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This needs to be awaited and unsubscribed like the request handlers above. Please move this up and do the same kind of `unsubPromises.push` thing as is done with the dialog request handlers above.
</blockquote></details>

I don't know what to do here exactly. Can we take a look at it together? I looked at `web-view.service-host.ts` for inspiration, and it basically does a simple `registerCommand` like this for the commands
___
*[`src/renderer/components/dialogs/about-dialog.component.tsx` line 39 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONQbC_4EJv4ge9mN326:-ONU_Qe86T1i03BT3hxy:b-s0igzu) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/components/dialogs/about-dialog.component.tsx#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

One way you could solve the long request error is by pulling in the prop `submitDialog` here and running it immediately on first render in a `useEffect`.

Example of `submitDialog`: https://github.com/paranext/paranext-core/blob/pt-3038-software-version-info/src/renderer/components/dialogs/select-project.dialog.tsx#L22
</blockquote></details>

I don't think this does what you expect it to do. I believe it immediately closes the dialog again, before it even opens on screen
___
*[`src/renderer/components/dialogs/about-dialog.component.tsx` line 96 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONQc0Wu9S-rpFV5iKca:-ONURXoS4rrNB1El8c-i:b-gth5tw) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/components/dialogs/about-dialog.component.tsx#L96)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This needs to be localized. I imagine there is already a string for it; just need to get it localized somehow. Looks like `DialogOptions.title` already can accept a LocalizeKey, so it may be easy
</blockquote></details>

Yep, seems to work


<!-- Sent from Reviewable.io -->

2025-04-10 14:17 UTC, tjcouch-sil reviewed
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060)* status: 87 of 102 files reviewed, 2 unresolved discussions (waiting on @lyonsil and @rolfheij-sil)

___
*[`src/renderer/components/dialogs/about-dialog.component.tsx` line 39 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONQbC_4EJv4ge9mN326:-ONV0NL712KvVHUzVXsL:b1y6xh6) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/components/dialogs/about-dialog.component.tsx#L39)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

I don't think this does what you expect it to do. I believe it immediately closes the dialog again, before it even opens on screen
</blockquote></details>

Ah I see. In that case, it looks like you could do one of the following:

1. Do what Matt said for now and just wrap every call to open the about dialog in an IIFE. Leaves some strings hanging for sure, but at least it's a quick fix.
2. Figure out some clever way to overwrite `submitDialog` in `ABOUT_DIALOG` below. It comes from `DIALOG_BASE` right now. It seems it would be rather complicated but not impossible to make this DRY. Maybe you could make a factory function for `loadDialog`.
3. Edit `submitDialog` on `DIALOG_BASE` to have an optional second parameter `shouldClose` (default `true`) that lets the dialog control whether it should close on submission. Feels kinda weird to be honest, but it's probably easier than 2 and solves the problem more widely than 1.

I lean toward just leaving it with 1 for now especially since you already did it. Marking this as resolved.


<!-- Sent from Reviewable.io -->

2025-04-10 16:17 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060)* status: 87 of 102 files reviewed, 2 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`src/renderer/services/dialog.service-host.ts` line 405 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONQdGb04lxoOhBUdH2M:-ONVUXgw1cy3Ttx1Qm2M:b-203cz8) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/services/dialog.service-host.ts#L405)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

I don't know what to do here exactly. Can we take a look at it together? I looked at `web-view.service-host.ts` for inspiration, and it basically does a simple `registerCommand` like this for the commands
</blockquote></details>

Thanks for helping me fix and understand this
___
*[`src/renderer/components/dialogs/about-dialog.component.tsx` line 39 at r14](https://reviewable.io/reviews/paranext/paranext-core/1060#-ONQbC_4EJv4ge9mN326:-ONVUSjJ8z0dGY2Edf5G:b-df2dcm) ([raw file](https://github.com/paranext/paranext-core/blob/742f0e3cae402f3e09a0f4cb029108f4a10198b5/src/renderer/components/dialogs/about-dialog.component.tsx#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ah I see. In that case, it looks like you could do one of the following:

1. Do what Matt said for now and just wrap every call to open the about dialog in an IIFE. Leaves some strings hanging for sure, but at least it's a quick fix.
2. Figure out some clever way to overwrite `submitDialog` in `ABOUT_DIALOG` below. It comes from `DIALOG_BASE` right now. It seems it would be rather complicated but not impossible to make this DRY. Maybe you could make a factory function for `loadDialog`.
3. Edit `submitDialog` on `DIALOG_BASE` to have an optional second parameter `shouldClose` (default `true`) that lets the dialog control whether it should close on submission. Feels kinda weird to be honest, but it's probably easier than 2 and solves the problem more widely than 1.

I lean toward just leaving it with 1 for now especially since you already did it. Marking this as resolved.
</blockquote></details>

Thanks for explaning all that! Leaving 1 as the solution for now :thumbsup: 


<!-- Sent from Reviewable.io -->

2025-04-10 16:18 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :tada:

> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060#-:-ONVUlmK2KcY1YzFhkev:bck4n45)* status: 87 of 102 files reviewed, 1 unresolved discussion (waiting on @lyonsil, @rolfheij-sil, and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2025-04-10 19:57 UTC, rolfheij-sil approved these changes
> Reviewed 1 of 12 files at r6, 4 of 12 files at r11, 3 of 4 files at r12, 5 of 6 files at r14, 1 of 2 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1060)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-04-10 19:57 UTC, merged