Provide the ability to run ParatextChecks and cleanup JSON serializing
paranext/paranext-core pull request #1069
Opened 2024-08-14 18:19 UTC by lyonsil

This PR enables running Paratext checks against projects provided by ParatextData.

2024-08-15 05:07 UTC, irahopkinson requested changes
Thanks for all your good work here. Nice to see us reducing our use of Newtonsoft - is it still used anywhere?

> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069#-:-O4JLIka-_3SDM0tG3fy:b-rxde9d)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Checks/CheckInputRange.cs` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4Ikbdt7Kq2OF9PhC_m:-O4Ikbdt7Kq2OF9PhC_n:b347obo) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckInputRange.cs#L12)):*
> ```Smalltalk
> 
>         if (start.ChapterNum <= 0)
>             throw new ArgumentOutOfRangeException(nameof(start), "ChapterNum must be > 0");
> ```

Do we need to distinguish between this error and the next, e.g. "Start ChapterNum must be > 0" and "End ChapterNum must be > 0"?
___
*[`c-sharp/Checks/CheckInputRange.cs` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4JNJ2p1KwiWmxWHYv2:-O4JNJ2p1KwiWmxWHYv3:b-8vj431) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckInputRange.cs#L29)):*
> ```Smalltalk
>     public VerseRef? End { get; }
> 
>     public bool IsWithinRange(string projectId, int bookNum, int chapterNum)
> ```

BTW I would advocate for using `book` (string) instead of `bookNum` since people can't understand `bookNum`. The argument can easily be converted to `bookNum` (`Canon.BookIdToNumber(book)`) here if that is easier to work with.
___
*[`c-sharp-tests/Checks/CheckInputRangeTests.cs` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4JMkQVEUrrjZP0dUEK:-O4JMkQVEUrrjZP0dUEL:b-yl9u0h) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp-tests/Checks/CheckInputRangeTests.cs#L26)):*
> ```Smalltalk
>         string? verseRefEnd,
>         string projectId,
>         int bookNum,
> ```

BTW it would be easier to parse these tests if this was `book` (string) instead of `bookNum`.


<!-- Sent from Reviewable.io -->

2024-08-15 15:06 UTC, lyonsil reviewed
I did a search across all of our code to remove it. I think TJ still has some uses of it in one or two of his PRs that will have to be updated. He can't remove use of it in his PRs unless this goes in first, and if his go in first I can update this PR to remove his uses.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069#-:-O4LPlyf4Yt67DJevQA2:b-rseozt)* status: 28 of 30 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`c-sharp/Checks/CheckInputRange.cs` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4Ikbdt7Kq2OF9PhC_m:-O4LQ27p5GOBuoz7XYNc:b7h9hwj) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckInputRange.cs#L12)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Do we need to distinguish between this error and the next, e.g. "Start ChapterNum must be > 0" and "End ChapterNum must be > 0"?
</blockquote></details>

I'm not expecting us to ever hit these errors, but you never know, so I updated the exception messages.
___
*[`c-sharp/Checks/CheckInputRange.cs` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4JNJ2p1KwiWmxWHYv2:-O4LQAfQAEKUJwo3KaSB:b-v9vpl2) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckInputRange.cs#L29)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I would advocate for using `book` (string) instead of `bookNum` since people can't understand `bookNum`. The argument can easily be converted to `bookNum` (`Canon.BookIdToNumber(book)`) here if that is easier to work with.
</blockquote></details>

Unfortunately I don't have good control over this. I created this method based on the `TextChanged` event from `ParatextData`. I use this method to decide if a `TextChanged` event indicates that scripture was updated that is within the range that we're configured to run checks on. The `TextChangedEventArgs` structure contains a `ScrText`, `BookNum`, and `ChapterNum`. I could use the `ScrText` to convert the book from a number to a string I suppose, but I would just convert it right back here.

I don't know of any other uses of this function other than working with `TextChanged`. All checks that exist outside of `Paratext.Checks.dll` will not use this code.

I added a comment to this function to explain the situation in more detail if this comes up again later.
___
*[`c-sharp-tests/Checks/CheckInputRangeTests.cs` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4JMkQVEUrrjZP0dUEK:-O4LS0eB5kstM2Aq6859:b-i5cl57) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp-tests/Checks/CheckInputRangeTests.cs#L26)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW it would be easier to parse these tests if this was `book` (string) instead of `bookNum`.
</blockquote></details>

Agreed. As I mentioned in the comment on `IsWithinRange()`, the parameters are integers because that's what `ParatextData` provides in the `TextChanged` event. I am just trying to replicate that structure here. I could use strings here and convert, but it didn't seem worth it just for a test. I thought sticking with the first 3 books of the Bible for book IDs in the tests would make things easy enough to understand.


<!-- Sent from Reviewable.io -->

2024-08-15 16:13 UTC, tjcouch-sil requested changes
It would be very nice to have a little summary documentation comment about what each class is for :) it's hard to tell at a glance what they are supposed to do and how they are different from one another. I sorta get the big picture right now (though I can't say without looking more closely at how they are used what the difference is between `CheckInputRange` and `CheckLocation`, for example), but I'll forget it all in a week and would have to look at everything over again to know how it fits into the system as a whole.

> Reviewed 30 of 30 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069#-:-O4LLEEe7AdbYGLD5B74:b-apfht0)* status: all files reviewed, 6 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`c-sharp/Checks/CheckLocation.cs` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LLTrm3T2ET4SMXfDv:-O4LLTrm3T2ET4SMXfDw:boev4wq) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckLocation.cs#L20)):*
> ```Smalltalk
>             return false;
> 
>         return VerseRef.BBBCCCVVV == other.VerseRef.BBBCCCVVV && Offset == other.Offset;
> ```

Do you know if BBBCCCVVV factors in Versification? I imagine not. Or maybe we're just pushing versification for now since we have been pushing it all this time so far :) maybe we should make comments that include the link to the versification epic where we see places we'll need to change so we can keep track more easily...  https://github.com/paranext/roadmap/issues/93 in case you're interested in linking it
___
*[`c-sharp/Checks/CheckRunner.cs` line 120 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LZlTxDe0nkdp89wUX:-O4LZlTxDe0nkdp89wUY:bdxxcf5) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckRunner.cs#L120)):*
> ```Smalltalk
> 
>         foreach(var projectId in _activeRanges.Select(range => range.ProjectId).Distinct())
>             GetOrCreateDataSource(projectId).ScrText.TextChanged -= RerunChecks;
> ```

Because of the limitations of `TextChanged` we discussed recently (such as not running events when Send/Receive happens or other things but only when someone runs something that boils down to `ScrText.PutText` or whatever it's called), I suggest maybe it's worth considering how to expose the data provider's event in C# and use that instead. That way, everyone in P.B can be on the same page in that we're all listening to that event. Would that satisfy your needs here?
___
*[`c-sharp/Checks/CheckRunner.cs` line 182 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LaquKA18CiJlrYElM:-O4LaquKA18CiJlrYElN:b-xdarcw) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckRunner.cs#L182)):*
> ```Smalltalk
>             if (resultsRemoved)
>                 PapiClient.SendEvent(_checkResultsUpdatedEvent);
>             return ResponseToRequest.Succeeded("AvailableChecks");
> ```

Just checking; is there an intended return type for this method? It seems to just return a string in all cases that doesn't apparently seem particularly useful.
___
*[`c-sharp/Checks/CheckRunner.cs` line 272 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LeJRmEsrmAjWRjSiV:-O4LeJRmEsrmAjWRjSiW:bujr5nn) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckRunner.cs#L272)):*
> ```Smalltalk
> 
>         if (totalAfterRunning == totalBeforeRunning)
>             return removedItems.Count != 0;
> ```

Is it particularly significant for this return to be correct? If so, I wonder if this could give false negatives - could there be a case where the check returns the same number before and after but those results are different? Maybe it doesn't matter enough right now and this is something for another time? If so, maybe worth adding a comment?
___
*[`c-sharp/JsonUtils/CheckInputRangeConverter.cs` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LftcG0FxSgnpBUCEn:-O4LftcH3a8a8m9kihon:b-z2qvoz) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/JsonUtils/CheckInputRangeConverter.cs#L33)):*
> ```Smalltalk
>             VerseRef? end = string.IsNullOrEmpty(endJson)
>                 ? null
>                 : JsonSerializer.Deserialize<VerseRef>(endJson, s_serializerOptions);
> ```

Oh snap are we always supposed to pass these serializer options into the dotnet JSON serializer and deserializer?? I did not know that. Can we instead make a class whose methods we use everywhere instead of using `System.Text.Json` directly? Similar to our util serialize and deserialize in TS. Then we don't have to worry about subtly accidentally missing some places (especially if someone who doesn't touch the C# much doesn't know to do that); it will be much easier to tell that something is not as we intend. We can just see if the file uses `System.Text.Json`, and that would be a pretty obvious smell that something is off! :) maybe worth doing in a follow-up or another time depending on your energy for reworks right now haha
___
*[`c-sharp/JsonUtils/ProjectDataScopeConverter.cs` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LfTLREU16tkBcw8wJ:-O4LfTLREU16tkBcw8wK:b-1htcte) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/JsonUtils/ProjectDataScopeConverter.cs#L7)):*
> ```Smalltalk
> namespace Paranext.DataProvider.JsonUtils;
> 
> internal class ProjectDataScopeConverter : JsonConverter<ProjectDataScope>
> ```

What was wrong with converting `ProjectDataScope` such that you needed this? How am I supposed to know when I need one of these? This seems very heavy and annoying to write :joy:
___
*[`c-sharp-tests/Projects/ParatextDataProviderTests.cs` line 676 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LiLdZ9K9g1kwbTfjf:-O4LiLdZ9K9g1kwbTfjg:b-80wzsp) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp-tests/Projects/ParatextDataProviderTests.cs#L676)):*
> ```Smalltalk
> 
>             var result = provider.SetProjectSetting(
>                 JsonSerializer.Serialize(VisibilitySettingName),
> ```

Do these `Serialize` calls need to have the serialization options passed to them? 4 in this file
___
*[`c-sharp-tests/Services/ProjectSettingsServicesTests.cs` line 14 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LiV-vAnzVyOsiA65r:-O4LiV-vAnzVyOsiA65s:b-z4x4d1) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp-tests/Services/ProjectSettingsServicesTests.cs#L14)):*
> ```Smalltalk
>         {
>             DummyPapiClient papiClient = new();
>             var newValueJson = JsonSerializer.Serialize("Spanish");
> ```

Do these `Serialize` calls need to have the serialization options passed to them? 11 in this file
___
*[`extensions/src/platform-scripture/src/checks/check-aggregator.service.ts` line 114 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4Lj-9H8gXRhphybybc:-O4Lj-9H8gXRhphybybd:b-m1ye9t) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/extensions/src/platform-scripture/src/checks/check-aggregator.service.ts#L114)):*
> ```XML
>         const checkRunnerDetails = allNetworkObjects[propertyName];
>         if (this.checkRunners.has(checkRunnerDetails.id)) return;
>         // Some check runners might be in extensions we didn't know about at compile time
> ```

You should add the dotnet check runner to `platform-scripture.d.ts`, then this will know about the two check runners that are currently available, right? I don't know that TS will  [...]

2024-08-15 19:47 UTC, irahopkinson submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069#-:-O4M_C508EryLWWfqp_6:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Checks/CheckInputRange.cs` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4Ikbdt7Kq2OF9PhC_m:-O4MWy2q6OrSCbnczTOZ:b-qmmo1t) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckInputRange.cs#L12)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm not expecting us to ever hit these errors, but you never know, so I updated the exception messages.
</blockquote></details>

Gotcha, thanks for making the change.
___
*[`c-sharp/Checks/CheckInputRange.cs` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4JNJ2p1KwiWmxWHYv2:-O4MXXkuBjcbRnXpS4d-:b-upthi6) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckInputRange.cs#L29)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Unfortunately I don't have good control over this. I created this method based on the `TextChanged` event from `ParatextData`. I use this method to decide if a `TextChanged` event indicates that scripture was updated that is within the range that we're configured to run checks on. The `TextChangedEventArgs` structure contains a `ScrText`, `BookNum`, and `ChapterNum`. I could use the `ScrText` to convert the book from a number to a string I suppose, but I would just convert it right back here.

I don't know of any other uses of this function other than working with `TextChanged`. All checks that exist outside of `Paratext.Checks.dll` will not use this code.

I added a comment to this function to explain the situation in more detail if this comes up again later.
</blockquote></details>

That makes sense, thanks for adding the comment.
___
*[`c-sharp/Checks/CheckLocation.cs` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LLTrm3T2ET4SMXfDv:-O4MZ6Oj2aUFAhdH9_du:bppzyzt) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckLocation.cs#L20)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do you know if BBBCCCVVV factors in Versification? I imagine not. Or maybe we're just pushing versification for now since we have been pushing it all this time so far :) maybe we should make comments that include the link to the versification epic where we see places we'll need to change so we can keep track more easily...  https://github.com/paranext/roadmap/issues/93 in case you're interested in linking it
</blockquote></details>

To my mind checking BBBCCCVVV only works if you also check that versification is the same. However, I don't know what a location check is supposed to be checking.
___
*[`c-sharp-tests/Checks/CheckInputRangeTests.cs` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4JMkQVEUrrjZP0dUEK:-O4MXxNC0TZjeB3vJmj2:bs5oox3) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp-tests/Checks/CheckInputRangeTests.cs#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Agreed. As I mentioned in the comment on `IsWithinRange()`, the parameters are integers because that's what `ParatextData` provides in the `TextChanged` event. I am just trying to replicate that structure here. I could use strings here and convert, but it didn't seem worth it just for a test. I thought sticking with the first 3 books of the Bible for book IDs in the tests would make things easy enough to understand.
</blockquote></details>

Yep, keeping to the first 3 did help. However, I would say tests are a great place to add extra code if it makes reading easier. I'm fine with it now since I already read it.


<!-- Sent from Reviewable.io -->

2024-08-15 21:50 UTC, lyonsil reviewed
I added comments on the new classes in the `Checks` folder. I also commented on/resolved everything not related to serialization. I'll take a separate pass over resolving the serialization comments/suggestions as I need to be in a slightly separate frame of mind for those.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069#-:-O4MULDu5bjddE90o79a:ba9at7h)* status: all files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/Checks/CheckLocation.cs` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LLTrm3T2ET4SMXfDv:-O4MAqOj3-Y8kr8DShvm:bwptp42) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckLocation.cs#L20)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do you know if BBBCCCVVV factors in Versification? I imagine not. Or maybe we're just pushing versification for now since we have been pushing it all this time so far :) maybe we should make comments that include the link to the versification epic where we see places we'll need to change so we can keep track more easily...  https://github.com/paranext/roadmap/issues/93 in case you're interested in linking it
</blockquote></details>

Good point - BBBCCCVVV doesn't take it into account. I just added `Versification` here as part of equality checking and hashing.

Ideally `VerseRef` would have implemented `IEquatable` or something like that so that equality checks aren't only about "are these the same objects?" and could instead be "do these represent the same locations in scripture?". It doesn't, though, and at this point the code base is so big I have no idea what might break if I added it. So I'm stuck doing something like this which tries to treat `VerseRef`s as their data (essentially value types) instead of their object ID/location in memory (reference types).
___
*[`c-sharp/Checks/CheckRunner.cs` line 120 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LZlTxDe0nkdp89wUX:-O4MC2AdAY2Y_ieuk3ZC:b-og2zlf) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckRunner.cs#L120)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Because of the limitations of `TextChanged` we discussed recently (such as not running events when Send/Receive happens or other things but only when someone runs something that boils down to `ScrText.PutText` or whatever it's called), I suggest maybe it's worth considering how to expose the data provider's event in C# and use that instead. That way, everyone in P.B can be on the same page in that we're all listening to that event. Would that satisfy your needs here?
</blockquote></details>

Although it's imperfect, I think I'd rather stick with events that give some sense of what scripture changed for now and wait to switch to something else until we have some similar concept in play. I'm envisioning someone enabling checks on a whole project (or at least several books) and getting hammered because someone edited one book but keeps running checks on all the other books. Remember that UX talked with us a few times about having checks always running in the background instead of only as discrete points when someone clicks a button.

If you think this is really going to be a problem we can talk about it further. I just hate to rerun all checks on all active books anytime any verse in any other book changes.
___
*[`c-sharp/Checks/CheckRunner.cs` line 182 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LaquKA18CiJlrYElM:-O4MDRmwDfzSHOyG_pKL:bckn1yx) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckRunner.cs#L182)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Just checking; is there an intended return type for this method? It seems to just return a string in all cases that doesn't apparently seem particularly useful.
</blockquote></details>

This is part of the implementation of the `ICheckRunner` interface from TS:
```
    /** Disable the check with the given checkId from producing results for the given project. */
    disableCheck: (checkId: string, projectId?: string) => Promise<void>;
```

I was mistaking return types here for the notifications that go out because of how this works with PDPs. This has been updated to send out data updated notifications. I'm still returning the same strings, though, because at least for `set` calls I think the return value might be meaningful, and it's not going to be obvious why we don't do it for enable/disable methods but do it for set methods.
___
*[`c-sharp/Checks/CheckRunner.cs` line 272 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LeJRmEsrmAjWRjSiV:-O4MM0lZDTR1MLaqZ_7i:b-wo9y7y) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckRunner.cs#L272)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is it particularly significant for this return to be correct? If so, I wonder if this could give false negatives - could there be a case where the check returns the same number before and after but those results are different? Maybe it doesn't matter enough right now and this is something for another time? If so, maybe worth adding a comment?
</blockquote></details>

Yes, it is important for this to be correct. Otherwise the UI won't know to load updated check results/errors.

We pass in the `recorder` parameter to `Run`, and that parameter must implement the interface `IRecordCheckError`. That interface has no way to remove results from it, just to record new errors. That means when `check.Run` executes all the items that are in `recorder` can't be removed/updated by the check that is running. The only way to remove/update items is to use methods that the checks don't know about. So the scenario you bring up (i.e., the check creates the same number of new issues and removes the old ones) can't happen.

If a check re-adds the same errors it produced previously, then the last line of this method checks to see if all of the errors added by the check are the same ones it added previously.
___
*[`extensions/src/platform-scripture/src/checks/check-aggregator.service.ts` line 114 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4Lj-9H8gXRhphybybc:-O4MNoZQ7oeHudGD-hPZ:byc1dt4) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/extensions/src/platform-scripture/src/checks/check-aggregator.service.ts#L114)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You should add the dotnet check runner to `platform-scripture.d.ts`, then this will know about the two check runners that are currently available, right? I don't know that TS will be smart enough even then to be able to do this, but the point stands; theoretically, all data providers provided from an extension should be discoverable because they should put all their data providers in their `.d.ts` files.

I think the comment for disabling this should be something more along the following lines: "We filtered down to just check runner data providers' ids above, so we know this is a check runner".

----

This is why I wondered at some point if we need to expose `data-provider.service.ts`'s `getByType`... Or something similar. Maybe we make another shared interface that maps the network object type to data provider type. Right now, there isn't really a TS-aware way to make these aggregations of data providers with the same api outside of core (we do it in core with PDPFs, for example). I dunno; I'd say this part is worth considering another time.
</blockquote></details>

I updated the comment.

There are two complaints I had  [...]

2024-08-15 22:19 UTC, irahopkinson approved these changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2024-08-15 22:20 UTC, irahopkinson approved these changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2024-08-16 01:42 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069)* status: 20 of 36 files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`c-sharp/JsonUtils/CheckInputRangeConverter.cs` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LftcG0FxSgnpBUCEn:-O4NE6gx1phnmlv36VqZ:bx2ds8z) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/JsonUtils/CheckInputRangeConverter.cs#L33)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oh snap are we always supposed to pass these serializer options into the dotnet JSON serializer and deserializer?? I did not know that. Can we instead make a class whose methods we use everywhere instead of using `System.Text.Json` directly? Similar to our util serialize and deserialize in TS. Then we don't have to worry about subtly accidentally missing some places (especially if someone who doesn't touch the C# much doesn't know to do that); it will be much easier to tell that something is not as we intend. We can just see if the file uses `System.Text.Json`, and that would be a pretty obvious smell that something is off! :) maybe worth doing in a follow-up or another time depending on your energy for reworks right now haha
</blockquote></details>

Wow, welcome to another minor [programming](https://github.com/dotnet/runtime/issues/31094) [controversy](https://stackoverflow.com/questions/58331479/how-to-globally-set-default-options-for-system-text-json-jsonserializer).

Since Microsoft doesn't provide a way to set our own default JSON deserialization options, I'm going to go with one of the suggestion from StackOverflow and use extension methods to make this simpler so we don't forget to include SerializationOptions. I know Tim doesn't like extension methods, and while I agree in general they can get out of control, I think this might be the best compromise here.
___
*[`c-sharp/JsonUtils/ProjectDataScopeConverter.cs` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LfTLREU16tkBcw8wJ:-O4Nj7nrAQ0llHjZyIbn:bh7r5r5) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/JsonUtils/ProjectDataScopeConverter.cs#L7)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

What was wrong with converting `ProjectDataScope` such that you needed this? How am I supposed to know when I need one of these? This seems very heavy and annoying to write :joy:
</blockquote></details>

Good question - Actually it turns out we don't need this class. It came about during a temporary state that I was in with these changes, but where things stand now we don't need it.
___
*[`c-sharp-tests/Projects/ParatextDataProviderTests.cs` line 676 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LiLdZ9K9g1kwbTfjf:-O4NjU0zC1v-3hMEfDcz:bfzy3o1) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp-tests/Projects/ParatextDataProviderTests.cs#L676)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do these `Serialize` calls need to have the serialization options passed to them? 4 in this file
</blockquote></details>

It didn't matter because they were just strings. Regardless, with my latest updates I'm converting all of our code to use the new extension methods for consistency.
___
*[`c-sharp-tests/Services/ProjectSettingsServicesTests.cs` line 14 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LiV-vAnzVyOsiA65r:-O4NjtIQ0jPftmZdfZrb:bogn0cn) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp-tests/Services/ProjectSettingsServicesTests.cs#L14)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do these `Serialize` calls need to have the serialization options passed to them? 11 in this file
</blockquote></details>

It didn't matter because they were just strings and integers. Regardless, with my latest updates I'm converting all of our code to use the new extension methods for consistency.


<!-- Sent from Reviewable.io -->

2024-08-16 01:56 UTC, lyonsil reviewed
Serialization updates are done now, too.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069#-:-O4Ntarp70YGVC3y0aL4:b-pv5nwj)* status: 19 of 36 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2024-08-16 02:48 UTC, irahopkinson approved these changes
> Reviewed 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2024-08-16 17:47 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks for all the adjustments and responses :) and thanks for the hard work on this! It's exciting!

> Reviewed 7 of 8 files at r3, 16 of 17 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1069#-:-O4RIIEvALxPcKwGP0wQ:b27hx04)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`c-sharp/Checks/CheckRunner.cs` line 120 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LZlTxDe0nkdp89wUX:-O4Qw47yAFAs4Agk_cKw:ba8sya2) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckRunner.cs#L120)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Although it's imperfect, I think I'd rather stick with events that give some sense of what scripture changed for now and wait to switch to something else until we have some similar concept in play. I'm envisioning someone enabling checks on a whole project (or at least several books) and getting hammered because someone edited one book but keeps running checks on all the other books. Remember that UX talked with us a few times about having checks always running in the background instead of only as discrete points when someone clicks a button.

If you think this is really going to be a problem we can talk about it further. I just hate to rerun all checks on all active books anytime any verse in any other book changes.
</blockquote></details>

It's probably fine for now. I envisioned basically doing the same thing `subscribe<data_type>` does in TS and getting the new data and seeing if it's different from the most recently run data. But it's not a big deal. I see the TS runner also just reruns everything. We will probably need to revise all this stuff at some point anyway, so I imagine it makes enough sense to leave it for now.
___
*[`c-sharp/Checks/CheckRunner.cs` line 182 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LaquKA18CiJlrYElM:-O4R2KLL5ZI4fFoWdbeQ:by5s5kf) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckRunner.cs#L182)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This is part of the implementation of the `ICheckRunner` interface from TS:
```
    /** Disable the check with the given checkId from producing results for the given project. */
    disableCheck: (checkId: string, projectId?: string) => Promise<void>;
```

I was mistaking return types here for the notifications that go out because of how this works with PDPs. This has been updated to send out data updated notifications. I'm still returning the same strings, though, because at least for `set` calls I think the return value might be meaningful, and it's not going to be obvious why we don't do it for enable/disable methods but do it for set methods.
</blockquote></details>

Gotcha, thanks!
___
*[`c-sharp/Checks/CheckRunner.cs` line 272 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LeJRmEsrmAjWRjSiV:-O4R9gdf7FSL12jx3PHb:b8p9cqg) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/Checks/CheckRunner.cs#L272)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Yes, it is important for this to be correct. Otherwise the UI won't know to load updated check results/errors.

We pass in the `recorder` parameter to `Run`, and that parameter must implement the interface `IRecordCheckError`. That interface has no way to remove results from it, just to record new errors. That means when `check.Run` executes all the items that are in `recorder` can't be removed/updated by the check that is running. The only way to remove/update items is to use methods that the checks don't know about. So the scenario you bring up (i.e., the check creates the same number of new issues and removes the old ones) can't happen.

If a check re-adds the same errors it produced previously, then the last line of this method checks to see if all of the errors added by the check are the same ones it added previously.
</blockquote></details>

Ah I see. Sorry to bother.
___
*[`c-sharp/JsonUtils/CheckInputRangeConverter.cs` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4LftcG0FxSgnpBUCEn:-O4RBN6Y56wm2jCsWMIy:bgud42d) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/c-sharp/JsonUtils/CheckInputRangeConverter.cs#L33)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Wow, welcome to another minor [programming](https://github.com/dotnet/runtime/issues/31094) [controversy](https://stackoverflow.com/questions/58331479/how-to-globally-set-default-options-for-system-text-json-jsonserializer).

Since Microsoft doesn't provide a way to set our own default JSON deserialization options, I'm going to go with one of the suggestion from StackOverflow and use extension methods to make this simpler so we don't forget to include SerializationOptions. I know Tim doesn't like extension methods, and while I agree in general they can get out of control, I think this might be the best compromise here.
</blockquote></details>

Thank you :) that sounds like a good solution.

It's funny you say Tim doesn't like extension methods. On my interview with Darren and Tim upon applying for this position, one of the few programming questions they asked me was what a provided code block was doing, and it was an extension method :joy:
___
*[`extensions/src/platform-scripture/src/checks/check-aggregator.service.ts` line 114 at r1](https://reviewable.io/reviews/paranext/paranext-core/1069#-O4Lj-9H8gXRhphybybc:-O4RERGRCIKng6IBgBAB:be8z1te) ([raw file](https://github.com/paranext/paranext-core/blob/020e3433cb7bb2626b880e640c29fc73594c74d0/extensions/src/platform-scripture/src/checks/check-aggregator.service.ts#L114)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I updated the comment.

There are two complaints I had to dismiss here from TS and eslint:
1) "Hey you can't call `get` unless the string is known by TypeScript to be a key of `DataProviders`."
2) "Hey you can't cast this data provider as `ICheckRunner` because you don't know which of the known data provider interfaces it implements."

Whether or not I added the .NET checkRunner to a d.ts file, the exact same problems will pop up. For 1) we don't know what network object IDs we will get of type `checkRunner`. It could be some network object ID of an extension that I never knew about in `platformScripture`. That naturally leads to 2) because if I don't know what the key is, I don't know what kind of data provider it is intending to be at compile/analysis time.

I can add the data provider to the d.ts file, but it has no bearing on these errors. Honestly it feels kind of pointless with the way `ICheckRunner`s have been designed. That is, they are intended to be dynamically discovered, created, and used. Adding it gives the impression that the .NET `ICheckRunner` is special and you can/should target it separately from all the other `ICheckRunner`s. I don't think that's what we want or should encourage people to do. It could easily lead people down the wrong path of "I need to find all the `ICheckRunner`s I want to support and explicitly create DPs for them by name." That's not what the design is and effectively would cause them to recreate `checkAggregatorService` in some form. A check is a check is a check regardless of where it came from. At least that's how I'm thinking about it.

We could expose `getByType`, but all it would really do is just type cast to whatever you said, right? If so, making callers do w [...]

2024-08-16 19:11 UTC, merged