Move thread ownership from Main to PapiClient
paranext/paranext-core pull request #107
Opened 2023-03-28 21:35 UTC by lyonsil

Move thread ownership from Main to PapiClient

2023-03-28 23:32 UTC, irahopkinson requested changes
Looking good, just 4 questions

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107#-:-NReZ2FI0gUjfXu4Z_WC:b-fxqbhc)* status: all files reviewed, 4 unresolved discussions (waiting on @FoolRunning and @lyonsil)

___
*[`c-sharp/Program.cs` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReLu1F872RzF5y-nfS:-NReLu1F872RzF5y-nfT:b-9vlo1p) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/Program.cs#L13)):*
> ```Smalltalk
>     public static async Task Main()
>     {
>         using (PapiClient papi = new())
> ```

We might want to call this `papiClient` to distinguish it from PAPI itself. However that might be a destinction without a difference here (unlike the TS).
___
*[`c-sharp/Program.cs` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReM_zl3b_JLUW2IWI3:-NReM_zl3b_JLUW2IWI4:b9a9l5u) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/Program.cs#L22)):*
> ```Smalltalk
>                 if (connectTask.Exception != null)
>                     Console.Error.WriteLine(connectTask.Exception);
>                 return;
> ```

Should we make this DRYer since there is another copy below? I guess we can't exit out of this method from a called method if we turned the whole thing into an assert method or something but we could do  `if (TaskError(connectTask, "Paranext data provider could not connect")) return`



_Code quote:_
```Smalltalk
            if (!await connectTask)
            {
                Console.Error.WriteLine("Paranext data provider could not connect");
                if (connectTask.Exception != null)
                    Console.Error.WriteLine(connectTask.Exception);
                return;
            }
```
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReSnC7CtJsxMVMNzfs:-NReSnC7CtJsxMVMNzft:b-uk245s) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/MessageTransports/PapiClient.cs#L34)):*
> ```Smalltalk
>     private int _clientId = NetworkConnectorInfo.CLIENT_ID_UNSET;
>     private int _nextRequestId = 1;
>     private bool _disposedValue = false;
> ```

A better name might be `IsDisposed` (as in add the status word `is`) see our [naming guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties). Also note further down it says not to use `g_` or `s_` prefixes for static fields.

FYI: I suspect we also don't use the `_` prefix on private properties since they already are camelCase to indicate this but I haven't found that in the guide yet. Actually this [guide](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions#word-choice) says don't use underscore at all and this [guide](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties) says properties should all be PascalCase.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 72 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReTVnC-JO5LR2Mdg3u:-NReTVnC-JO5LR2Mdg3v:bcn290u) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/MessageTransports/PapiClient.cs#L72)):*
> ```Smalltalk
>     // }
> 
>     private void Dispose(bool disposing)
> ```

A better name would be `isDisposing` see our [naming guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties).


<!-- Sent from Reviewable.io -->

2023-03-29 04:09 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107)* status: all files reviewed, 4 unresolved discussions (waiting on @FoolRunning and @irahopkinson)

___
*[`c-sharp/Program.cs` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReLu1F872RzF5y-nfS:-NRfYITb6yB0faDU2que:b-i5bryw) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/Program.cs#L13)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

We might want to call this `papiClient` to distinguish it from PAPI itself. However that might be a destinction without a difference here (unlike the TS).
</blockquote></details>

Sure, I can change it.
___
*[`c-sharp/Program.cs` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReM_zl3b_JLUW2IWI3:-NRfYTOk2Dj2qFEUKXj7:bz6h087) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/Program.cs#L22)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Should we make this DRYer since there is another copy below? I guess we can't exit out of this method from a called method if we turned the whole thing into an assert method or something but we could do  `if (TaskError(connectTask, "Paranext data provider could not connect")) return`
</blockquote></details>

Sure, I can make the `TaskError` method your suggest.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReSnC7CtJsxMVMNzfs:-NRfSdLz0EAXAy3VhjAm:b75gjnm) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/MessageTransports/PapiClient.cs#L34)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

A better name might be `IsDisposed` (as in add the status word `is`) see our [naming guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties). Also note further down it says not to use `g_` or `s_` prefixes for static fields.

FYI: I suspect we also don't use the `_` prefix on private properties since they already are camelCase to indicate this but I haven't found that in the guide yet. Actually this [guide](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions#word-choice) says don't use underscore at all and this [guide](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties) says properties should all be PascalCase.
</blockquote></details>

All of the code implementing `IDisposable` was generated from Visual Studio except for the specific objects to dispose.  I kept the generated code largely as provided.  Also, these aren't properties, they are fields.  The [C# guidelines for fields](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#camel-case) says:

```
Use camel casing ("camelCasing") when naming private or internal fields, and prefix them with _.

When working with static fields that are private or internal, use the s_ prefix and for thread static use t_.
```

So I think I'm actually following the guidelines.  If they were public, then it would be different:

```
When naming public members of types, such as fields, properties, events, methods, and local functions, use pascal casing.
```

The guidelines you pointed out are specific to properties.  The difference is demonstrated on [Stack Overflow here](https://stackoverflow.com/questions/295104/what-is-the-difference-between-a-field-and-a-property).

Lower down on the page you referenced it says:
```
Internal and private fields are not covered by guidelines.
```

Since these are private fields, those guidelines do not apply here.

From a purely personal standpoint, I find it VERY helpful to make sure that member fields have a prefix and variables and fields declared within a function do not have a prefix.  In C++ underscores are commonly used at the end (https://google.github.io/styleguide/cppguide.html#Variable_Names), but in C# I have generally seen them at the beginning.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 72 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReTVnC-JO5LR2Mdg3u:-NRfY27K6x2gRwcaOvXz:bplc0s) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/MessageTransports/PapiClient.cs#L72)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

A better name would be `isDisposing` see our [naming guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties).
</blockquote></details>

As mentioned above, this name came from the code generated by Visual Studio.  I'm happy to change it, though.


<!-- Sent from Reviewable.io -->

2023-03-29 04:51 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning and @lyonsil)

___
*[`c-sharp/Program.cs` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReLu1F872RzF5y-nfS:-NRfeKaH9PjevhzownG5:bj2vx1e) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/Program.cs#L13)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Sure, I can change it.
</blockquote></details>

NVM, I've changed my mind and think it's fine as is. Sorry.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReSnC7CtJsxMVMNzfs:-NRff3tr9dPw7lpEyjn-:b9v1ufr) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/MessageTransports/PapiClient.cs#L34)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

All of the code implementing `IDisposable` was generated from Visual Studio except for the specific objects to dispose.  I kept the generated code largely as provided.  Also, these aren't properties, they are fields.  The [C# guidelines for fields](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#camel-case) says:

```
Use camel casing ("camelCasing") when naming private or internal fields, and prefix them with _.

When working with static fields that are private or internal, use the s_ prefix and for thread static use t_.
```

So I think I'm actually following the guidelines.  If they were public, then it would be different:

```
When naming public members of types, such as fields, properties, events, methods, and local functions, use pascal casing.
```

The guidelines you pointed out are specific to properties.  The difference is demonstrated on [Stack Overflow here](https://stackoverflow.com/questions/295104/what-is-the-difference-between-a-field-and-a-property).

Lower down on the page you referenced it says:
```
Internal and private fields are not covered by guidelines.
```

Since these are private fields, those guidelines do not apply here.

From a purely personal standpoint, I find it VERY helpful to make sure that member fields have a prefix and variables and fields declared within a function do not have a prefix.  In C++ underscores are commonly used at the end (https://google.github.io/styleguide/cppguide.html#Variable_Names), but in C# I have generally seen them at the beginning.

</blockquote></details>

Alrighty, no problem. I was probaly thinking about TS when I called them properties and then looked up that guideline, sorry about that. Is there a conflict between the 2 guidelines then when it comes `s_` prefix? Either way go with what you have since it is inline with the simpler guideline you linked to.

Could you call it `_isDisposed` to make it more readable or is it best to leave it alone if it was auto-generated?


<!-- Sent from Reviewable.io -->

2023-03-29 15:39 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning and @irahopkinson)

___
*[`c-sharp/Program.cs` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReM_zl3b_JLUW2IWI3:-NRhzg225e0PimCtQfcS:b-vghvij) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/Program.cs#L22)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Sure, I can make the `TaskError` method your suggest.
</blockquote></details>

While trying to implement this helper method I learned more about `async` and `await`.  I didn't properly understand how exception handling works with those keywords.  So I won't implement this helper exactly as suggested, but I am changing this code to remove the unnecessary repeated code and make this DRYer (which was the original point).
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReSnC7CtJsxMVMNzfs:-NRi-Zuf07XVC5jvfjmt:b-onxixk) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/MessageTransports/PapiClient.cs#L34)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Alrighty, no problem. I was probaly thinking about TS when I called them properties and then looked up that guideline, sorry about that. Is there a conflict between the 2 guidelines then when it comes `s_` prefix? Either way go with what you have since it is inline with the simpler guideline you linked to.

Could you call it `_isDisposed` to make it more readable or is it best to leave it alone if it was auto-generated?
</blockquote></details>

I don't think there is a contradiction [here](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-fields) because it says:
```
Internal and private fields are not covered by guidelines
```

I am taking the wording here to mean "not covered by *these* guidelines," as there is guidance specifically on private field names [here](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#camel-case).

I will rename the field to `_isDisposed` as you suggest.  It is a little clearer.  It doesn't actually hurt anything to change the auto-generated code, but as a general rule of thumb I leave it alone except for parts that were intended to change.


<!-- Sent from Reviewable.io -->

2023-03-29 16:04 UTC, lyonsil reviewed
As part of the DRYer changes, I also removed some unnecessary and incorrect exception handling.  At this point I think exceptions should flow through the normal way (inside and outside of async code) in all areas where we don't intend to catch the exceptions.  Any remaining exceptions that flow through should allow for better "fail fast" scenarios that @FoolRunning mentioned last week.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107#-:-NRi5fB66M9hDZLs8aAR:b9mbmna)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @FoolRunning and @irahopkinson)



<!-- Sent from Reviewable.io -->

2023-03-29 22:00 UTC, irahopkinson reviewed
LGTM but I'd like a C# developer like @FoolRunning to review and do the approving.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107#-:-NRjNXTi7VE_oGrsh5ao:bhoqtzk)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning and @lyonsil)

___
*[`c-sharp/Program.cs` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReM_zl3b_JLUW2IWI3:-NRjLnLQ48AefofQqnkj:b-oz8o77) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/Program.cs#L22)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

While trying to implement this helper method I learned more about `async` and `await`.  I didn't properly understand how exception handling works with those keywords.  So I won't implement this helper exactly as suggested, but I am changing this code to remove the unnecessary repeated code and make this DRYer (which was the original point).
</blockquote></details>

Good catch
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReSnC7CtJsxMVMNzfs:-NRjM7s_2R3w64e_ZdmP:b-nbbry) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/MessageTransports/PapiClient.cs#L34)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I don't think there is a contradiction [here](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-fields) because it says:
```
Internal and private fields are not covered by guidelines
```

I am taking the wording here to mean "not covered by *these* guidelines," as there is guidance specifically on private field names [here](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#camel-case).

I will rename the field to `_isDisposed` as you suggest.  It is a little clearer.  It doesn't actually hurt anything to change the auto-generated code, but as a general rule of thumb I leave it alone except for parts that were intended to change.
</blockquote></details>

Thanks for that - good to know there is no conflict between the 2 there. The changed names are is more readable.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 72 at r1](https://reviewable.io/reviews/paranext/paranext-core/107#-NReTVnC-JO5LR2Mdg3u:-NRjMgt25hUmzXaRmFgB:bt3tnsh) ([raw file](https://github.com/paranext/paranext-core/blob/2e7d6fc3f7020c45346162722433a79544c5c0fe/c-sharp/MessageTransports/PapiClient.cs#L72)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

As mentioned above, this name came from the code generated by Visual Studio.  I'm happy to change it, though.
</blockquote></details>

Thanks, the changed name is more readable.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 134 at r3](https://reviewable.io/reviews/paranext/paranext-core/107#-NRjN626-jWSbwBPEFzX:-NRjN626-jWSbwBPEFzY:bqxrkfl) ([raw file](https://github.com/paranext/paranext-core/blob/cf2a907c47072a191148b2b20028898dfe1ad1a5/c-sharp/MessageTransports/PapiClient.cs#L134)):*
> ```Smalltalk
>         Console.WriteLine("PapiClient disconnecting");
> 
>         // Start a graceful disconnection process before isDisposing
> ```

nit: this should still say "... before disposing". Accidental search and replace change?


<!-- Sent from Reviewable.io -->

2023-03-30 14:04 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning and @irahopkinson)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 134 at r3](https://reviewable.io/reviews/paranext/paranext-core/107#-NRjN626-jWSbwBPEFzX:-NRmpArg2R-yH92rUdxl:b-nugtdg) ([raw file](https://github.com/paranext/paranext-core/blob/cf2a907c47072a191148b2b20028898dfe1ad1a5/c-sharp/MessageTransports/PapiClient.cs#L134)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

nit: this should still say "... before disposing". Accidental search and replace change?
</blockquote></details>

Indeed that is what happened - I'll fix this.


<!-- Sent from Reviewable.io -->

2023-03-30 14:12 UTC, lyonsil reviewed
I believe all of the items you brought up have been resolved now.  We'll see what Tim and/or others have to say.

Note that I plan to squash all of these commits into one before merging.  I'm leaving them as separate commits for the short term to make it easier to see what changed between iterations as I responded to comments.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107#-:-NRmqcEq9BZcTj9G81Bt:bbcz19t)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @FoolRunning and @irahopkinson)



<!-- Sent from Reviewable.io -->

2023-03-30 19:51 UTC, irahopkinson reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @FoolRunning)



<!-- Sent from Reviewable.io -->

2023-03-30 19:54 UTC, irahopkinson reviewed
You can enable auto-merge with squash in GitHub, this will signal your intention and make it happen automatically on approval. A very nice recent feature addition I'm enjoying using.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107#-:-NRo3rvxBWkbW1rzcRoO:bfxmmlp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @FoolRunning)



<!-- Sent from Reviewable.io -->

2023-04-04 14:18 UTC, FoolRunning requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 47 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NS7txsw2GCfqyBWj1-e:-NS7txsw2GCfqyBWj1-f:b-d9xnqg) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L47)):*
> ```Smalltalk
>     {
>         _webSocket = new ClientWebSocket();
>         _messageHandlingThread = new(new ThreadStart(HandleMessages));
> ```

I think you should be able to get rid of the ``new ThreadStart`` here and just pass in the method directly.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 70 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NS7uIjs9xSLmXRMr9YN:-NS7uIjs9xSLmXRMr9YO:b-3gpmte) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L70)):*
> ```Smalltalk
>     //     // Do not change this code. Put cleanup code in 'Dispose(bool isDisposing)' method
>     //     Dispose(isDisposing: false);
>     // }
> ```

I realize this code was auto-generated, but if you aren't using the destructor, then it should be simplified to just using the ``Dispose()`` method (with no parameters).
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 74 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NS7uvrv7qAxGLmQVDsT:-NS7uvrv7qAxGLmQVDsU:b-8fk1ma) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L74)):*
> ```Smalltalk
>     private void Dispose(bool isDisposing)
>     {
>         if (!_isDisposed)
> ```

This should be an early return if it's already disposed.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 137 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NSBbP9O3RrtKnDdsgPa:-NSBbP9O3RrtKnDdsgPb:bqbdm25) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L137)):*
> ```Smalltalk
>         _cancellationTokenSource.Cancel();
>         _messageHandlingComplete.Set();
>         await _webSocket.CloseAsync(
> ```

I think there's a race condition here if the message thread is in the process of handling a websocket event and we suddenly close it. It would probably be best to do a ``_messageHandlingThread.Join()`` before the close to make sure the thread is completely shut down before closing the websocket.


<!-- Sent from Reviewable.io -->

2023-04-04 14:43 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @FoolRunning and @irahopkinson)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 47 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NS7txsw2GCfqyBWj1-e:-NSBi6G5BIKcjUWflB1O:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L47)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I think you should be able to get rid of the ``new ThreadStart`` here and just pass in the method directly.
</blockquote></details>

Done
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 70 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NS7uIjs9xSLmXRMr9YN:-NSBdsyl9gnMaXuFbjpu:b-l67qx0) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L70)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I realize this code was auto-generated, but if you aren't using the destructor, then it should be simplified to just using the ``Dispose()`` method (with no parameters).
</blockquote></details>

I thought about doing that, but I left it all as boilerplate as breadcrumbs to future maintainers.  `Dispose` is easy to screw up from my recollection, and following this standard pattern keeps you safe.  I figured leaving some extra, currently unused code was better than hoping someone who might need it in the future remembers to put it back.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 74 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NS7uvrv7qAxGLmQVDsT:-NSBePWBDqDLW53Hy8aP:b-8um6g5) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L74)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

This should be an early return if it's already disposed.
</blockquote></details>

Done - It was already essentially doing that since nothing is run if `_isDisposed` is true, but I flipped the `if` block to be clearer about it.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 137 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NSBbP9O3RrtKnDdsgPa:-NSBg8ovBC9HtkTZ-cA9:b-i516er) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L137)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I think there's a race condition here if the message thread is in the process of handling a websocket event and we suddenly close it. It would probably be best to do a ``_messageHandlingThread.Join()`` before the close to make sure the thread is completely shut down before closing the websocket.
</blockquote></details>

Done - Yes under normal circumstances this is better.  I'm giving the `Join` a timeout, though, so that we close the web socket one way or another in case of an unexpected hang in message handling.  We don't want a zombie client hanging around.


<!-- Sent from Reviewable.io -->

2023-04-04 15:47 UTC, FoolRunning approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 70 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NS7uIjs9xSLmXRMr9YN:-NSBvpr94PlOHQzUCL1E:b-h7hnbh) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L70)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I thought about doing that, but I left it all as boilerplate as breadcrumbs to future maintainers.  `Dispose` is easy to screw up from my recollection, and following this standard pattern keeps you safe.  I figured leaving some extra, currently unused code was better than hoping someone who might need it in the future remembers to put it back.
</blockquote></details>

I guess that's okay for now.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 74 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NS7uvrv7qAxGLmQVDsT:-NSBwUtJ3k1F_gWhLSWb:b-84uk0z) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L74)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Done - It was already essentially doing that since nothing is run if `_isDisposed` is true, but I flipped the `if` block to be clearer about it.
</blockquote></details>

Yeah, it's to avoid nesting as much as possible.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 137 at r4](https://reviewable.io/reviews/paranext/paranext-core/107#-NSBbP9O3RrtKnDdsgPa:-NSBwhgzCMz2wDIUpsNd:b-3hcy5h) ([raw file](https://github.com/paranext/paranext-core/blob/2697e4bccef18f33b112173d04fc2c1025c0db86/c-sharp/MessageTransports/PapiClient.cs#L137)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Done - Yes under normal circumstances this is better.  I'm giving the `Join` a timeout, though, so that we close the web socket one way or another in case of an unexpected hang in message handling.  We don't want a zombie client hanging around.
</blockquote></details>

Yes, I agree that was best.


<!-- Sent from Reviewable.io -->

2023-04-04 15:49 UTC, FoolRunning commented
Sorry it took so long to get this through.

2023-04-04 16:12 UTC, lyonsil reviewed
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2023-04-04 16:14 UTC, lyonsil commented
@irahopkinson Please unblock when you have a chance.  I believe you were just blocking while waiting for another reviewer.

2023-04-04 22:18 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/107#-:-NSDLOyb-L5OZRI8DI1j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2023-04-04 22:18 UTC, merged