add type checking
paranext/paranext-core pull request #1088
Opened 2024-08-25 21:16 UTC by irahopkinson

- fixes #1085
- include core, extensions, platform-bible-utils, platform-bible-react
- fix existing type checking errors
- add typecheck to pre-commit

use `noImplicitReturns` instead of `consistent-return`

2024-08-26 13:21 UTC, jolierabideau approved these changes
Thanks Ira!

> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088#-:-O5DqCbm6mMoJVmjUAHi:b-y4yusl)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/lib/update-from-templates.ts` line 69 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5DpAXi8cOHdhP7tNKb:-O5DpAXi8cOHdhP7tNKc:bo4w3nr) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/update-from-templates.ts#L69)):*
> ```XML
>         if (
>           includes(
>             errorMessage,
> ```

You could also get the error message with `getErrorMessage` from `platform-bible-utils`


<!-- Sent from Reviewable.io -->

2024-08-26 16:28 UTC, tjcouch-sil requested changes
Thanks for the hard work on this! Hopefully this will make it harder to break things :)

Once all of this is said and done, would you mind making the appropriate changes in the templates too please? Like updating the git utils code and such.

> Reviewed 29 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088#-:-O5EVa7T2_o5TpBPZZZY:bprkh1e)* status: all files reviewed, 7 unresolved discussions (waiting on @irahopkinson and @jolierabideau)

___
*[`tsconfig.json` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ENXcVB7qOsOJdBhIx:-O5ENXcVB7qOsOJdBhIy:b-cx89jk) ([raw file](https://github.com/paranext/paranext-core/blob/2cf01cbb5a67514af1a75254f8afb2c31a5a98c2/tsconfig.json#L51)):*
> ```jsonc
>     "lib/platform-bible-react",
>     "lib/platform-bible-utils",
>     "lib/papi-dts"
> ```

Why remove this? Core probably shouldn't have access to `papi-dts` because `papi-dts` is generated off of core. Changing types might cause there to be two different definitions of a type until you re-run `build:types`, which would probably get really annoying. I'm also surprised it doesn't show errors that there are two definitions of types in general to be honest.

If the intention was to add type checking for `papi.d.ts` (which I think is a good idea as we sometimes get errors in there, I think), I suggest potentially adding another `typecheck:papi-dts` or something
___
*[`tsconfig.lint.json` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EOjke5u2_ujVJFd-J:-O5EOjke5u2_ujVJFd-K:bl180w9) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/tsconfig.lint.json#L4)):*
> ```JSON
>   "extends": "./tsconfig",
>   "compilerOptions": {
>     "skipLibCheck": true
> ```

Oh maybe this is the reason there aren't errors about duplicate definitions of types. Why add this?
___
*[`extensions/tsconfig.json` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EOvcC60ybJdtpI7EY:-O5EOvcDAozN3prQHlwU:b-y7qbxm) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/tsconfig.json#L26)):*
> ```jsonc
>     "typeRoots": [
>       // Include default type declarations
>       "../node_modules/@types",
> ```

This is not the default path for type declarations anymore to my understanding. I suggest adding another line right below this one or changing the comment on this line.
___
*[`extensions/lib/add-remotes.ts` line 14 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EVnXu4a6nY3rK7BQH:-O5EVnXu4a6nY3rK7BQI:bue2it5) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/add-remotes.ts#L14)):*
> ```XML
>   let exitCode = 0;
> 
>   // Helper function to handle remote addition
> ```

What happened to all this? Did typescript report errors on this or something?
___
*[`extensions/lib/git.util.ts` line 93 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ERBBD9gpEEUn8tJpK:-O5ERBBD9gpEEUn8tJpL:b-g4uwub) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L93)):*
> ```XML
>     if (!quiet && result.stderr) console.log(result.stderr);
>     return result;
>   } catch (error: unknown) {
> ```

Why add `unknown` here? Is TS requiring that or something? I thought it implicitly understood it was `unknown`.
___
*[`extensions/lib/git.util.ts` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EPrv2Deb6iH0vfAA9:-O5EPrv2Deb6iH0vfAAA:b-8s6c1i) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L104)):*
> ```XML
>       );
>     } else {
>       throw new Error('An unknown error occurred while executing git command');
> ```

Could you add the error in at the end of the string in hopes that it will give some more specific info to the user?

I'm particularly concerned about these git-related errors because not all of them will be easily repeatable since they're interacting with stuff on file system, in git state, and online. I'd like to make absolutely certain we can give whatever error information is available to us.
___
*[`extensions/lib/git.util.ts` line 146 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EQjciBe4bXi4XILCP:-O5EQjciBe4bXi4XILCQ:bxca5d9) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L146)):*
> ```XML
>       console.error(`Error on git fetch on ${SINGLE_TEMPLATE_NAME}: ${error.message}`);
>     } else {
>       console.error(`An unknown error occurred while fetching from ${SINGLE_TEMPLATE_NAME}`);
> ```

Why make this change? Isn't it good to print the error in all contexts? I think the difference between `e.toString()` and `e.message` is just that the message doesn't have "Error: " at the start, which I'd consider to be not worth all the trouble.

If you'd like to keep this change, could you please add the error in at the end of the string here in hopes that it will give some more specific information to the user?
___
*[`extensions/lib/update-from-templates.ts` line 69 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5DpAXi8cOHdhP7tNKb:-O5ERPOg-F_VTUuZAxBe:b1hk0cc) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/update-from-templates.ts#L69)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

You could also get the error message with `getErrorMessage` from `platform-bible-utils`
</blockquote></details>

I'm still not understanding the motivation to change the code here. Would like to understand better.

(Also note `platform-bible-utils` is not available yet in all contexts in which this code will be running. This code is from the multi template)
___
*[`extensions/lib/update-from-templates.ts` line 87 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ERjIF-GUXOIdBXslL:-O5ERjIF-GUXOIdBXslM:b3scw4j) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/update-from-templates.ts#L87)):*
> ```XML
>       } else {
>         console.error(
>           `An unknown error occurred while pulling from ${SINGLE_TEMPLATE_NAME} to ${ext.dirName}`,
> ```

Same comment as in other places; would like to have the error printed out if these error reworks are not reverted.
___
*[`extensions/src/hello-world/src/web-views/hello-world.web-view.tsx` line 264 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ESBdq51MvilJDSNe8:-O5ESBdq51MvilJDSNe9:bg1s3bp) ([raw file](https://github.com/paranext/paranext-core/blob/2cf01cbb5a67514af1a75254f8afb2c31a5a98c2/extensions/src/hello-world/src/web-views/hello-world.web-view.tsx#L264)):*
> ```XML
>         <Checkbox labelText="Test Me" />
>         <Switch /> {/* no label available */}
>         <ComboBox title="Test Me" options={['option 1', 'option 2']} />
> ```

This prop was not available, right? This seems like a significant oversight worth filing a bug on if I am understanding correctly.
___
*[`lib/platform-bible-react/tsconfig.json` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ET1pb2FsVUUM7nL2S:-O5ET1pb2FsVUUM7nL2T:b-f8nck0) ([raw file](https://github.com/paranext/paranext-core/blob/2cf01cbb5a67514af1a75254f8afb2c31a5a98c2/lib/platform-bible-react/tsconfig.json#L5)):*
> ```jsonc
>   "compilerOptions": {
>     "baseUrl": "./src",
>     "rootDir": "./src",
> ```

What is the effect of removing this line here and in utils? Is it redundant? I would have guessed this change would make `rootDir` stay up at repo top level since we're extending that tsconfig. If that would be the case, I think all the built files would be two extra folders deep, [...]

2024-08-27 02:23 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088)* status: all files reviewed, 6 unresolved discussions (waiting on @jolierabideau and @tjcouch-sil)

___
*[`tsconfig.json` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ENXcVB7qOsOJdBhIx:-O5GMu182m38OaJDOiAO:b-owcyc0) ([raw file](https://github.com/paranext/paranext-core/blob/2cf01cbb5a67514af1a75254f8afb2c31a5a98c2/tsconfig.json#L51)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why remove this? Core probably shouldn't have access to `papi-dts` because `papi-dts` is generated off of core. Changing types might cause there to be two different definitions of a type until you re-run `build:types`, which would probably get really annoying. I'm also surprised it doesn't show errors that there are two definitions of types in general to be honest.

If the intention was to add type checking for `papi.d.ts` (which I think is a good idea as we sometimes get errors in there, I think), I suggest potentially adding another `typecheck:papi-dts` or something
</blockquote></details>

I think I was just diagnosing and didn't put it back. BTW, having `lib/papi-dts` in this exclude section doesn't actually stop it from being included in core if it's imported in core code - importing overrides exclude. However, it's a good idea to type check it. Done.
___
*[`tsconfig.lint.json` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EOjke5u2_ujVJFd-J:-O5GUhxj2wZUf4ELtjBT:blgumoi) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/tsconfig.lint.json#L4)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oh maybe this is the reason there aren't errors about duplicate definitions of types. Why add this?
</blockquote></details>

If you don't, it checks all the files in libraries including in `node_modules` and there is always some problems there that we can't easily fix.
___
*[`extensions/tsconfig.json` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EOvcC60ybJdtpI7EY:-O5GVD9nBH1atbaF4zfz:bukbr8d) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/tsconfig.json#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is not the default path for type declarations anymore to my understanding. I suggest adding another line right below this one or changing the comment on this line.
</blockquote></details>

Now that this repo is an npm workspace the only valid `node_modules` folder is at the root. When you add types from DefinitelyTyped this is the folder they go in so that seems to me like the default type location. What am I missing?
___
*[`extensions/lib/add-remotes.ts` line 14 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EVnXu4a6nY3rK7BQH:-O5GWG1037U3MHJ-ICrT:b-147n4t) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/add-remotes.ts#L14)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

What happened to all this? Did typescript report errors on this or something?
</blockquote></details>

Yes, the previous code was causing type checking errors.
___
*[`extensions/lib/git.util.ts` line 93 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ERBBD9gpEEUn8tJpK:-O5GW7acCCDckgUe356c:bu9kfve) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L93)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why add `unknown` here? Is TS requiring that or something? I thought it implicitly understood it was `unknown`.
</blockquote></details>

Just making that explicit so we know that we need to check the type of `error` before using it.
___
*[`extensions/lib/git.util.ts` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EPrv2Deb6iH0vfAA9:-O5GWwcLAU2t3jg2n7g4:bpxp5y7) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L104)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Could you add the error in at the end of the string in hopes that it will give some more specific info to the user?

I'm particularly concerned about these git-related errors because not all of them will be easily repeatable since they're interacting with stuff on file system, in git state, and online. I'd like to make absolutely certain we can give whatever error information is available to us.
</blockquote></details>

I specifically left it out so we don't throw another exception while we are dealing with the first one. If we ever get one of these a diagnostic step could be to temporarily add it in to see if it reveals anything.
___
*[`extensions/lib/git.util.ts` line 146 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EQjciBe4bXi4XILCP:-O5GXM1jCzrhjt4FFQpF:b-o2p2hj) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L146)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why make this change? Isn't it good to print the error in all contexts? I think the difference between `e.toString()` and `e.message` is just that the message doesn't have "Error: " at the start, which I'd consider to be not worth all the trouble.

If you'd like to keep this change, could you please add the error in at the end of the string here in hopes that it will give some more specific information to the user?
</blockquote></details>

Again I left it out because we don't know the type so we are limited in what we can do and we don't want to hide this error by causing another exception.
___
*[`extensions/lib/update-from-templates.ts` line 69 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5DpAXi8cOHdhP7tNKb:-O5GYZm18B0k85mtqALA:b-glli1y) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/update-from-templates.ts#L69)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm still not understanding the motivation to change the code here. Would like to understand better.

(Also note `platform-bible-utils` is not available yet in all contexts in which this code will be running. This code is from the multi template)
</blockquote></details>

I think I have explained in the previous comments.
___
*[`extensions/lib/update-from-templates.ts` line 87 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ERjIF-GUXOIdBXslL:-O5GYlcmDirdEqN0SFV1:b-fct2so) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/update-from-templates.ts#L87)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Same comment as in other places; would like to have the error printed out if these error reworks are not reverted.
</blockquote></details>

See other comments.
___
*[`extensions/src/hello-world/src/web-views/hello-world.web-view.tsx` line 264 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ESBdq51MvilJDSNe8:-O5GYsuvBbxxF_L8s9Xv:bbyocs9) ([raw file](https://github.com/paranext/paranext-core/blob/2cf01cbb5a67514af1a75254f8afb2c31a5a98c2/extensions/src/hello-world/src/web-views/hello-world.web-view.tsx#L264)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This prop was not available, right? This seems like a significant oversight worth filing a bug on if I am understanding correctly.
</blockquote></details>

Yes, the prop doesn't exist. ComboBox is a deprecat [...]

2024-08-27 15:46 UTC, tjcouch-sil requested changes
> Reviewed 3 of 32 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @jolierabideau)

___
*[`tsconfig.lint.json` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EOjke5u2_ujVJFd-J:-O5JPZat01ojIfuAWbWk:bgbzng4) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/tsconfig.lint.json#L4)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

If you don't, it checks all the files in libraries including in `node_modules` and there is always some problems there that we can't easily fix.
</blockquote></details>

Hmm can you exclude `node_modules`? I'm thinking it would probably be good to check our code in context of the `.d.ts` files that we create.

(Marking this as open instead of blocking)
___
*[`extensions/tsconfig.json` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EOvcC60ybJdtpI7EY:-O5JSEapA8gaVMSoNDbM:b-1jsrte) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/tsconfig.json#L26)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Now that this repo is an npm workspace the only valid `node_modules` folder is at the root. When you add types from DefinitelyTyped this is the folder they go in so that seems to me like the default type location. What am I missing?
</blockquote></details>

Ah I was under the impression that they recently changed `typeRoots` so it doesn't search up the path anymore but just searches `node_modules/@types` and that's it. Sorry.
___
*[`extensions/lib/git.util.ts` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EPrv2Deb6iH0vfAA9:-O5JThur8R0ckjbJu9Bm:bmg7eoy) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L104)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I specifically left it out so we don't throw another exception while we are dealing with the first one. If we ever get one of these a diagnostic step could be to temporarily add it in to see if it reveals anything.
</blockquote></details>

All I'm suggesting to do in this one is change this one line to the following:

```ts
throw new Error(`An unknown error occurred while executing git command. ${error}`);
```

Is there any reasonable context in which putting a variable in a string template literal will cause an error to occur? My understanding is that we very commonly all over our code just string template literal the error into the message to give extra information about the error that gets thrown. If someone were to throw an object whose `toString` throws an error, that would cause this to fail. But I'd suggest that's not worth worrying about.

I would probably suggest just reverting in the other spots where a similar change to this occurred since they already pretty much had this same thing and are just more complex with the new code. But an alternate option would be just to string template literal the `error` into those as well like in my suggested code here.
___
*[`extensions/src/hello-world/src/web-views/hello-world.web-view.tsx` line 264 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ESBdq51MvilJDSNe8:-O5JTBz90k5vzTl1YX_U:b5i15pr) ([raw file](https://github.com/paranext/paranext-core/blob/2cf01cbb5a67514af1a75254f8afb2c31a5a98c2/extensions/src/hello-world/src/web-views/hello-world.web-view.tsx#L264)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yes, the prop doesn't exist. ComboBox is a deprecated MUI component. If you think it's worth fixing then please file an issue.
</blockquote></details>

https://github.com/paranext/paranext-core/issues/1092 :)


<!-- Sent from Reviewable.io -->

2024-08-27 23:03 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088)* status: all files reviewed, 5 unresolved discussions (waiting on @jolierabideau and @tjcouch-sil)

___
*[`tsconfig.lint.json` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EOjke5u2_ujVJFd-J:-O5L3OzFDWiT6TnKTrH4:b9noszu) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/tsconfig.lint.json#L4)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Hmm can you exclude `node_modules`? I'm thinking it would probably be good to check our code in context of the `.d.ts` files that we create.

(Marking this as open instead of blocking)
</blockquote></details>

Yeah, I didn't like adding this but I reasoned that some type checking is better than none. We might be able to improve this by using both `typeRoots` and `types`. I'll investigate a bit more...
___
*[`extensions/tsconfig.json` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EOvcC60ybJdtpI7EY:-O5KzW_W1QSLGDLrjCMa:b-rtqbiz) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/tsconfig.json#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ah I was under the impression that they recently changed `typeRoots` so it doesn't search up the path anymore but just searches `node_modules/@types` and that's it. Sorry.
</blockquote></details>

No problem. If you don't specify `typeRoots` https://www.typescriptlang.org/tsconfig/#typeRoots suggests it searches up the tree. Prior to looking at this again I was under the same impression that they changed this. Maybe they changed something related to this - I don't actually remember.
___
*[`extensions/lib/git.util.ts` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EPrv2Deb6iH0vfAA9:-O5L1ulIDQl5nFbYhLx5:bi984rd) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L104)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

All I'm suggesting to do in this one is change this one line to the following:

```ts
throw new Error(`An unknown error occurred while executing git command. ${error}`);
```

Is there any reasonable context in which putting a variable in a string template literal will cause an error to occur? My understanding is that we very commonly all over our code just string template literal the error into the message to give extra information about the error that gets thrown. If someone were to throw an object whose `toString` throws an error, that would cause this to fail. But I'd suggest that's not worth worrying about.

I would probably suggest just reverting in the other spots where a similar change to this occurred since they already pretty much had this same thing and are just more complex with the new code. But an alternate option would be just to string template literal the `error` into those as well like in my suggested code here.
</blockquote></details>

I understand what you are suggesting. If we did that and `error` doesn't have a `toString()`function then this would throw another exception which would hide the original exception. Are you ok with that?


<!-- Sent from Reviewable.io -->

2024-08-29 00:06 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088)* status: 23 of 49 files reviewed, 4 unresolved discussions (waiting on @jolierabideau and @tjcouch-sil)

___
*[`tsconfig.lint.json` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EOjke5u2_ujVJFd-J:-O5M9GTx5cV03b0iILNd:bafqclh) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/tsconfig.lint.json#L4)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yeah, I didn't like adding this but I reasoned that some type checking is better than none. We might be able to improve this by using both `typeRoots` and `types`. I'll investigate a bit more...
</blockquote></details>

This is looking better now. I couldn't remove it from `/extensions` - the biggest issue was all the imports of `'<someFile>?inline'`. I have one more idea to try but it seems a long shot so if that works I'll do a follow-up PR.


<!-- Sent from Reviewable.io -->

2024-08-29 00:12 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088)* status: 23 of 49 files reviewed, 4 unresolved discussions (waiting on @jolierabideau and @tjcouch-sil)

___
*[`tsconfig.lint.json` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EOjke5u2_ujVJFd-J:-O5QSK392uT0OwUdqOUj:b-cpxzah) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/tsconfig.lint.json#L4)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is looking better now. I couldn't remove it from `/extensions` - the biggest issue was all the imports of `'<someFile>?inline'`. I have one more idea to try but it seems a long shot so if that works I'll do a follow-up PR.
</blockquote></details>

I have it working for `extensions` now. And as a bonus, I have a clear reference to all the types that need fixing in the BNF repo (I think I have a way to fix that now - I just need time to work on it).


<!-- Sent from Reviewable.io -->

2024-08-29 02:54 UTC, irahopkinson reviewed
I'll create PRs for the 2 templates and once they are merged I'll redo this PR including those updates (now that I think we have things worked out).

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088#-:-O5R-Aq734CSzlaZDajM:b2s89o7)* status: 20 of 49 files reviewed, 4 unresolved discussions (waiting on @jolierabideau and @tjcouch-sil)

___
*[`extensions/lib/add-remotes.ts` line 14 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EVnXu4a6nY3rK7BQH:-O5QyxCkDr0do8LLcVWy:byw22q7) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/add-remotes.ts#L14)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yes, the previous code was causing type checking errors.
</blockquote></details>

I turns out with all the changes we are now only type checking `src` files so I've reverted this. I will take some of the good changes and apply them to the template.
___
*[`extensions/lib/git.util.ts` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EPrv2Deb6iH0vfAA9:-O5Qy5KWEX2IRJexkq2A:byw22q7) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L104)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I understand what you are suggesting. If we did that and `error` doesn't have a `toString()`function then this would throw another exception which would hide the original exception. Are you ok with that?
</blockquote></details>

I turns out with all the changes we are now only type checking `src` files so I've reverted this. I will take some of the good changes and apply them to the template.
___
*[`extensions/lib/git.util.ts` line 146 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EQjciBe4bXi4XILCP:-O5QyVnd-2iX-Zvsx_EP:byw22q7) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L146)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Again I left it out because we don't know the type so we are limited in what we can do and we don't want to hide this error by causing another exception.
</blockquote></details>

I turns out with all the changes we are now only type checking `src` files so I've reverted this. I will take some of the good changes and apply them to the template.
___
*[`extensions/lib/update-from-templates.ts` line 69 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5DpAXi8cOHdhP7tNKb:-O5QyXCH8tClyBbkv0yq:ba1h4vc) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/update-from-templates.ts#L69)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I think I have explained in the previous comments.
</blockquote></details>

I turns out with all the changes we are now only type checking `src` files so I've reverted this.
___
*[`extensions/lib/update-from-templates.ts` line 87 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5ERjIF-GUXOIdBXslL:-O5QyYesA-f5m2QZ21DL:ba1h4vc) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/update-from-templates.ts#L87)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

See other comments.
</blockquote></details>

I turns out with all the changes we are now only type checking `src` files so I've reverted this.


<!-- Sent from Reviewable.io -->

2024-11-11 18:14 UTC, tjcouch-sil reviewed
> Reviewed 4 of 26 files at r3, 29 of 32 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088)* status: 46 of 54 files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`extensions/lib/git.util.ts` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/1088#-O5EPrv2Deb6iH0vfAA9:-OBQvaSw4Z2Id4sf9Ab6:b-riuky0) ([raw file](https://github.com/paranext/paranext-core/blob/623200b02bb0f016d29ebfe2785cab7dd914acd6/extensions/lib/git.util.ts#L104)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I turns out with all the changes we are now only type checking `src` files so I've reverted this. I will take some of the good changes and apply them to the template.
</blockquote></details>

I suggest the likelihood that an object can't be string templated is extremely low and not worth worrying about.
___
*[`src/renderer/global-this.model.ts` line 77 at r6](https://reviewable.io/reviews/paranext/paranext-core/1088#-OBQu7TF8eIsCmO4njVQ:-OBQu7TG9chIjvjNk-pS:b-j8czxg) ([raw file](https://github.com/paranext/paranext-core/blob/74e11c28f6d2d2957defc2ac6cae0c003ba806fd/src/renderer/global-this.model.ts#L77)):*
> ```XML
>   // @ts-expect-error ts(2300) we're declaring React here because it may not always be available in
>   // all contexts
>   var React: typeof ReactModule;
> ```

Why remove this? We included it so people know we have set up `globalThis.React` for if they want to use it for some reason. I see you made some other React type adjustments I didn't understand, so I figure there's probably something going on here I don't understand.


<!-- Sent from Reviewable.io -->

2024-11-11 18:26 UTC, jolierabideau submitted a review, later dismissed
> Reviewed 5 of 26 files at r3, 3 of 32 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-11 18:32 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/renderer/global-this.model.ts` line 77 at r6](https://reviewable.io/reviews/paranext/paranext-core/1088#-OBQu7TF8eIsCmO4njVQ:-OBRStAQ4iGHe06k6P6K:bsheieh) ([raw file](https://github.com/paranext/paranext-core/blob/74e11c28f6d2d2957defc2ac6cae0c003ba806fd/src/renderer/global-this.model.ts#L77)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why remove this? We included it so people know we have set up `globalThis.React` for if they want to use it for some reason. I see you made some other React type adjustments I didn't understand, so I figure there's probably something going on here I don't understand.
</blockquote></details>

I had to add `src/@types/react.d.ts` to overcome the problem described in that file. It's doing that through a global also so that it can override and then ignore the type checking error and this line was in conflict with that global. A brute-force fix for this would be to skip lib checks. Another option would be for me to add the TS ignore to `node_modules/@types/react/index.d.ts:46` and patch the package. BTW first I had to remove the `@ts-expect-error ts(2300)` here as it is no longer erroring.


<!-- Sent from Reviewable.io -->

2024-11-11 21:50 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 26 files at r3, 3 of 32 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1088#-:-OBSCFxw1pM8XylPpGah:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-11 22:01 UTC, merged