742 use localizations (Core localizations)
paranext/paranext-core pull request #1098
Opened 2024-08-30 17:34 UTC by katherinejensen00

Applied localization to strings that seemed relevant. I tried to catch them all, but is is possible I missed some. Feel free to suggest more. This PR is just for the localizations in core (not the ones in extensions).

2024-09-03 03:30 UTC, irahopkinson requested changes
Wow, what a lot of work. Just 3 things to take care of.

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098#-:-O5pvZjmCoEbIp9loYXj:b-qy4zqy)* status: all files reviewed, 3 unresolved discussions (waiting on @katherinejensen00)

___
*[`extensions/src/hello-world/src/web-views/hello-world.web-view.tsx` line 211 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5psPHO3frVoKuKrBZt:-O5psPHO3frVoKuKrBZu:by86c54) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/extensions/src/hello-world/src/web-views/hello-world.web-view.tsx#L211)):*
> ```XML
>     useMemo(
>       () => ({
>         prompt: `${localizedSelectProjectsPrompt}`,
> ```

Err, you don't need to enclose a single string variable in backticks. Simplify this to `prompt: localizedSelectProjectsPrompt,`.
___
*[`extensions/src/platform-scripture-editor/src/main.ts` line 133 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5pt8imD2PbpoNtlr5T:-O5pt8imD2PbpoNtlr5U:b1mj1ar) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/extensions/src/platform-scripture-editor/src/main.ts#L133)):*
> ```XML
>         ).getSetting('platform.name')) ?? projectId
>       }${isReadOnly ? '' : ` ${localizedEditable}`}`;
>     } else title = isReadOnly ? `${localizedResourceViewer}` : `${localizedScriptureEditor}`;
> ```

You don't need either backtick string insertion here.
___
*[`src/renderer/components/web-view.component.tsx` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5pthw_1QzDpU3IW-0U:-O5pthw_1QzDpU3IW-0V:bp99tpr) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/src/renderer/components/web-view.component.tsx#L41)):*
> ```XML
>     title && isLocalizeKey(title) ? [title] : [webViewKey],
>   );
>   const defaultTitle = !title
> ```

This looks like you should remove the not (!) from `title` or swap the cases. Hmmm, the tests you removed might have picked up this issue.


<!-- Sent from Reviewable.io -->

2024-09-03 19:55 UTC, katherinejensen00 reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[`src/renderer/components/web-view.component.tsx` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5pthw_1QzDpU3IW-0U:-O5tS5pZ-kJNJ9EhEJmz:bxqq8dr) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/src/renderer/components/web-view.component.tsx#L41)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This looks like you should remove the not (!) from `title` or swap the cases. Hmmm, the tests you removed might have picked up this issue.
</blockquote></details>

Oops. Good catch!


<!-- Sent from Reviewable.io -->

2024-09-03 22:39 UTC, irahopkinson approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098)* status: all files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`src/renderer/components/web-view.component.tsx` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5pthw_1QzDpU3IW-0U:-O5u1TPH0ymdtNEb-e89:b-hwpxpu) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/src/renderer/components/web-view.component.tsx#L41)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Oops. Good catch!
</blockquote></details>

Strictly `||` is a boolean operation. It's better to use `??` here.


<!-- Sent from Reviewable.io -->

2024-09-04 20:17 UTC, tjcouch-sil requested changes
Thanks for all the hard work on this! Looking forward to having this in soon!

> Reviewed 21 of 21 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098#-:-O5yfeyjDc03LmedWiHB:b7zp30y)* status: all files reviewed, 6 unresolved discussions (waiting on @katherinejensen00)

___
*[`extensions/src/platform-scripture-editor/src/main.ts` line 128 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5tOKOVDdUAIrdRC1GX:-O5tOKOVDdUAIrdRC1GY:ba32u0x) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/extensions/src/platform-scripture-editor/src/main.ts#L128)):*
> ```XML
>     let title = '';
>     if (projectId) {
>       title = `${
> ```

When concatenating localized strings in any other way than newline (colon, parentheses, plain space, quotes, hyphen, etc.), it is generally best to use string formatting with a format localized string to concatenate the strings in a localizable manner. That way, if the strings are concatenated in a way that doesn't make sense in a locale, they can change how the string is concatenated and format it differently.

Example: [string key](https://github.com/paranext/paratext-bible-internal-extensions/blob/bd3989092457764f720b0d9d5383e39f4155dd99/src/paratext-bible-send-receive/contributions/localizedStrings.json#L86) and [usage](https://github.com/paranext/paratext-bible-internal-extensions/blob/bd3989092457764f720b0d9d5383e39f4155dd99/src/paratext-bible-send-receive/src/components/send-receive-view.component.tsx#L221)
___
*[`src/renderer/components/web-view.component.tsx` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5tTxKbDh_c1lJ5nYDs:-O5tTxKbDh_c1lJ5nYDt:ba32u0x) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/src/renderer/components/web-view.component.tsx#L43)):*
> ```XML
>   const defaultTitle = !title
>     ? title
>     : `${webViewType || contentType} ${localizedStrings[webViewKey]}`;
> ```

When concatenating localized strings in any other way than newline (colon, parentheses, plain space, quotes, hyphen, etc.), it is generally best to use string formatting with a format localized string to concatenate the strings in a localizable manner. That way, if the strings are concatenated in a way that doesn't make sense in a locale, they can change how the string is concatenated and format it differently.

Example: [string key](https://github.com/paranext/paratext-bible-internal-extensions/blob/bd3989092457764f720b0d9d5383e39f4155dd99/src/paratext-bible-send-receive/contributions/localizedStrings.json#L86) and [usage](https://github.com/paranext/paratext-bible-internal-extensions/blob/bd3989092457764f720b0d9d5383e39f4155dd99/src/paratext-bible-send-receive/src/components/send-receive-view.component.tsx#L221)
___
*[`src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx` line 109 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5xEwlh0q3fcKhFIzav:-O5xEwlh0q3fcKhFIzaw:b-inj0v3) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx#L109)):*
> ```XML
> function getLocalizedChecks(basicChecks: BasicCheck[]): BasicCheck[] {
>   basicChecks.forEach((c) => {
>     const [localizedStrings] = useLocalizedStrings(isLocalizeKey(c.name) ? [c.name] : []);
> ```

This looks to be conditionally rendering the `useLocalizedStrings` hook (running a variable number of times depending on the length of `basicChecks`), which is error-prone. Is there a way you can refactor to use one `useLocalizedStrings` call instead?

Also this function is a hook since it is a function used in a React component that uses other hooks - could you please rename it to start with "use" if you end up keeping it after refactoring?
___
*[`src/shared/models/docking-framework.model.ts` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5xFQcN9YjSeulbAxjN:-O5xFQcN9YjSeulbAxjO:blbrcm) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/src/shared/models/docking-framework.model.ts#L41)):*
> ```XML
>    */
>   tabIconUrl?: string;
>   /** Text to show on the title bar of the tab */
> ```

Please mention here that you can provide a `LocalizeKey` and it will be localized automatically.
___
*[`src/shared/models/web-view.model.ts` line 40 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5xFofR8HfH-sAcU7th:-O5xFofR8HfH-sAcU7ti:blbrcm) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/src/shared/models/web-view.model.ts#L40)):*
> ```XML
>    */
>   iconUrl?: string;
>   /** Name of the tab for the WebView */
> ```

Please mention here that you can provide a `LocalizeKey` and it will be localized automatically.


<!-- Sent from Reviewable.io -->

2024-09-06 17:37 UTC, tjcouch-sil requested changes
Thanks for the adjustments!

> Reviewed 33 of 33 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098#-:-O67PHBz-iW1CXbp6F5L:b-7kl0el)* status: all files reviewed, 11 unresolved discussions (waiting on @katherinejensen00)

___
*[`assets/localization/en.json` line 78 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67EDdK4JKAGwU3DLyA:-O67EDdK4JKAGwU3DLyB:b-wsl9fe) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/assets/localization/en.json#L78)):*
> ```JSON
>   "%webView_menuItemName_project%": "Project",
>   "%webView_menuItemName_projectAssignmentsAndProgress%": "Assignments and Progress",
>   "%webView_title_projectId_formatString%": "{projectId} {editable}"
> ```

This string is related to `platformScriptureEditor` so it should go in its localization file. Please also rename it to indicate it is specific to the platform scripture editor webview.

One option (open to interpretation; this is not an exact science) may be `%webView_platformScriptureEditor_title_format%`. That indicates it is related to a web view, which web view it is related to, it is used in the title, and it is a format string. No need to include `projectId` since that is a quality of the string itself and not particularly related to the purpose this string serves which is being the formatter string for the web view title of the editor.
___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 4 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67DNp1EwHVAO-j5xs_:-O67DNp1EwHVAO-j5xsa:bb390ol) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/extensions/src/hello-world/contributions/localizedStrings.json#L4)):*
> ```JSON
>   "metadata": {
>     "%helloWorld_webViewMenu_project%": {
>       "fallbackKey": "%mainMenu_menuItemName_project%"
> ```

These will also need to be reverted to go along with the key rename reverts.
___
*[`extensions/src/hello-world/contributions/menus.json` line 88 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67BZNVAD_EgW1oketK:-O67BZNVAD_EgW1oketL:b-okeqvu) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/extensions/src/hello-world/contributions/menus.json#L88)):*
> ```JSON
>           },
>           {
>             "label": "%webView_menuItemName_openProjectSettings%",
> ```

As a general principle, once we add localized string keys (into main where they are more permanent; within a PR is fine), we don't want to remove or rename them unless there is a particularly compelling reason to do so in order to avoid breaking changes (like if it has been translated into other locales or if other things are using the key like some other extension we can't Ctrl+F to find ourselves). Please revert this change and the key change corresponding to it.

Will shorten this comment for other occurrences I notice of removing/renaming pre-existing keys. Sorry for the confusion :p
___
*[`extensions/src/platform-scripture-editor/contributions/localizedStrings.json` line 18 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67G9L0-W1wCc6NpVEe:-O67G9L0-W1wCc6NpVEf:b2lq3b7) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/extensions/src/platform-scripture-editor/contributions/localizedStrings.json#L18)):*
> ```JSON
>       "%webView_platformScriptureEditor_publisherInfo%": "Publisher Info",
>       "%webView_platformScriptureEditor_copyrightInfo%": "Copyright Info",
>       "%webView_platformScriptureEditor_editable%": "(Editable)",
> ```

Here are a few more examples of naming keys according to purpose:

`webView_platformScriptureEditor_editable` -> `%webView_platformScriptureEditor_title_editable_indicator%`

The new key describes that this string is supposed to be used as the indicator in the title of the web view that the Scripture in it is editable. Gives more context as to how the key will be used so people hopefully will have a better chance at knowing what it is used for without having to go look at the code and find it. By contrast, the existing key just indicates the string says "editable" but doesn't give much context as to how the string is used. Without looking at the code, it is hard to know if it is used in the title, in the web view somewhere, etc. The particular words used in a string are not generally needed in the key, but rather the purpose the key serves should be explained in the key

`webView_platformScriptureEditor_resourceViewer` -> `webView_platformScriptureEdtior_title_readonly_no_project`

The new key indicates that this is the title that is used if there somehow happens to be no project but it is supposed to pull up the resource viewer (readonly).

`webView_platformScriptureEditor_scriptureEditor` -> `webView_platformScriptureEdtior_title_editable_no_project`

The new key indicates that this is the title that is used if there somehow happens to be no project but it is supposed to pull up the editor (editable).
___
*[`extensions/src/platform-scripture-editor/src/main.ts` line 128 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5tOKOVDdUAIrdRC1GX:-O67JdBP1Ckd_8sFVa1k:b-vsu5ts) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/extensions/src/platform-scripture-editor/src/main.ts#L128)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

When concatenating localized strings in any other way than newline (colon, parentheses, plain space, quotes, hyphen, etc.), it is generally best to use string formatting with a format localized string to concatenate the strings in a localizable manner. That way, if the strings are concatenated in a way that doesn't make sense in a locale, they can change how the string is concatenated and format it differently.

Example: [string key](https://github.com/paranext/paratext-bible-internal-extensions/blob/bd3989092457764f720b0d9d5383e39f4155dd99/src/paratext-bible-send-receive/contributions/localizedStrings.json#L86) and [usage](https://github.com/paranext/paratext-bible-internal-extensions/blob/bd3989092457764f720b0d9d5383e39f4155dd99/src/paratext-bible-send-receive/src/components/send-receive-view.component.tsx#L221)
</blockquote></details>

Thanks for the update!
___
*[`lib/platform-bible-react/src/components/mui/gridMenu.component.render.test.tsx` line 50 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67CRIY5rY1GZvTCrH9:-O67CRIY5rY1GZvTCrHA:bkou3y5) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/lib/platform-bible-react/src/components/mui/gridMenu.component.render.test.tsx#L50)):*
> ```XML
>         label: '%mainMenu_Paratext%',
>       },
>       { html: screen.getByRole('menu', { name: 'platform.window' }), label: '%mainMenu_menuItemName_window%' },
> ```

Although these are just tests, these may also need to be reverted to keep in sync with the others that need to be reverted
___
*[`lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json` line 5 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67B29N4mIPbi5_xqmK:-O67B29N4mIPbi5_xqmL:b-fhk874) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json#L5)):*
> ```JSON
>     "columns": {
>       "paratext.paratext": { "label": "%mainMenu_Paratext%", "order": 0 },
>       "platform.window": { "label": "%mainMenu_menuItemName_window%", "order": 1 },
> ```

Generally once we add localized string keys, we don't want to remove them to avoid breaking changes. Please revert these column label keys.
___
*[`src/extension-host/data/core-project-settings-info.data.ts` line 9 at r3](https://reviewable.io/reviews/par [...]

2024-10-15 20:01 UTC, katherinejensen00 reviewed
Thanks so much for all of the detailed comments and reviews!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098#-:-O9GlN9uEkf41IFGDzbu:b-7o0710)* status: 5 of 42 files reviewed, 10 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`assets/localization/en.json` line 78 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67EDdK4JKAGwU3DLyA:-O9FmLo85gvCm6TMTNA6:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/assets/localization/en.json#L78)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This string is related to `platformScriptureEditor` so it should go in its localization file. Please also rename it to indicate it is specific to the platform scripture editor webview.

One option (open to interpretation; this is not an exact science) may be `%webView_platformScriptureEditor_title_format%`. That indicates it is related to a web view, which web view it is related to, it is used in the title, and it is a format string. No need to include `projectId` since that is a quality of the string itself and not particularly related to the purpose this string serves which is being the formatter string for the web view title of the editor.
</blockquote></details>

Done.
___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 4 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67DNp1EwHVAO-j5xs_:-O9G1_3VBKiLvjtmnwTv:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/extensions/src/hello-world/contributions/localizedStrings.json#L4)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

These will also need to be reverted to go along with the key rename reverts.
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture-editor/contributions/localizedStrings.json` line 18 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67G9L0-W1wCc6NpVEe:-O9G7VEWEb8yUg_LNW1G:b-un9dd7) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/extensions/src/platform-scripture-editor/contributions/localizedStrings.json#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Here are a few more examples of naming keys according to purpose:

`webView_platformScriptureEditor_editable` -> `%webView_platformScriptureEditor_title_editable_indicator%`

The new key describes that this string is supposed to be used as the indicator in the title of the web view that the Scripture in it is editable. Gives more context as to how the key will be used so people hopefully will have a better chance at knowing what it is used for without having to go look at the code and find it. By contrast, the existing key just indicates the string says "editable" but doesn't give much context as to how the string is used. Without looking at the code, it is hard to know if it is used in the title, in the web view somewhere, etc. The particular words used in a string are not generally needed in the key, but rather the purpose the key serves should be explained in the key

`webView_platformScriptureEditor_resourceViewer` -> `webView_platformScriptureEdtior_title_readonly_no_project`

The new key indicates that this is the title that is used if there somehow happens to be no project but it is supposed to pull up the resource viewer (readonly).

`webView_platformScriptureEditor_scriptureEditor` -> `webView_platformScriptureEdtior_title_editable_no_project`

The new key indicates that this is the title that is used if there somehow happens to be no project but it is supposed to pull up the editor (editable).
</blockquote></details>

Those are really helpful examples! Thank you!
___
*[`extensions/src/platform-scripture-editor/src/main.ts` line 128 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5tOKOVDdUAIrdRC1GX:-O664GT_B3pypS2e9Ccx:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/extensions/src/platform-scripture-editor/src/main.ts#L128)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Thanks for the update!
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json` line 5 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67B29N4mIPbi5_xqmK:-O9GCkQK2PRTwgHHzCWG:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Generally once we add localized string keys, we don't want to remove them to avoid breaking changes. Please revert these column label keys.
</blockquote></details>

Done.
___
*[`src/extension-host/data/core-project-settings-info.data.ts` line 9 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67AmKx80J3N0qiXN-3:-O9GGDwB6ry5CzP_qIYu:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/src/extension-host/data/core-project-settings-info.data.ts#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Generally once we add localized string keys, we don't want to remove them to avoid breaking changes. Please revert these.
</blockquote></details>

Done.
___
*[`src/extension-host/data/menu.data.json` line 4 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67Jtnn8k8Ra2NKT7jb:-O9GJD2cCIq8FDOPro59:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/src/extension-host/data/menu.data.json#L4)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Generally once we add localized string keys, we don't want to remove them to avoid breaking changes. Please revert these.
</blockquote></details>

Done.
___
*[`src/renderer/components/web-view.component.tsx` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5tTxKbDh_c1lJ5nYDs:-O666ahq1IUHBm2LlKwI:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/src/renderer/components/web-view.component.tsx#L43)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Great, thanks!
</blockquote></details>

Done.
___
*[`src/renderer/components/web-view.component.tsx` line 38 at r3](https://reviewable.io/reviews/paranext/paranext-core/1098#-O67KZHu8xzA4t4brFjp:-O9Ga9ncAAsc-DZhpMmr:b-9wpqvn) ([raw file](https://github.com/paranext/paranext-core/blob/6b1c89ef38ecd7aebd2294ed2db9c4a73c3aee60/src/renderer/components/web-view.component.tsx#L38)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I can't seem to find where this localized string is defined - where is it? I figured it was in `en.json`, but I don't see it there.
</blockquote></details>

It shows up at the bottom of en.json for me. Does it need to change?
___
*[`src/shared/models/docking-framework.model.ts` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5xFQcN9YjSeulbAxjN:-O66EB-H-pb7h8uCed4c:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/eeff67ee850eee67ca0cfe6faee7f17dda54cc0c/src/shared/models/docking-framework.model.ts#L41)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Done.
___
*[`src/shared/models/web-view.model.ts` line 40 at r1](https://reviewable.io/reviews/paranext/paranext-core/1098#-O5xFofR8HfH-sAcU7th:-O66EK2P5mqvth-mfZSk:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob [...]

2024-10-17 15:10 UTC, tjcouch-sil requested changes
Thanks for all the updates! Hopefully we're almost there :) feel free to discuss with me as desired!

> Reviewed 9 of 22 files at r4, 28 of 28 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098#-:-O9Q0p1L1Duthz6JH5nP:b-cpmax5)* status: all files reviewed, 13 unresolved discussions (waiting on @katherinejensen00)

___
*[`assets/localization/en.json` line 4 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9Q-uni5GzU5ORdaLqB:-O9Q-uni5GzU5ORdaLqC:boeeueb) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/assets/localization/en.json#L4)):*
> ```JSON
>   "%about_versionLabel_format%": "Version: {version}",
>   "%about_licenseLabel_format%": "License: {license}",
>   "%bookSelector_dialogPrompt_selectOneOrMoreBooksToRunBasicChecksOn%": "Select one or more books to run basic checks on",
> ```

It looks to me like many of these are still written with the entire contents of the string in the key. Please take another look over them and revise any that seem to unnecessarily have the entire string contents within the key. Two giveaways that make it seem apparent the key needs to be revised:
1. The key is extremely long like this one. It could possibly be fine with something like maybe `%bookSelector_dialogPrompt_selectBooksForChecks%` or something shorter that conveys the purpose of the string without needing to write every word out
2. The key has punctuation written into it. For example, `%bookSelector_submitButton_chooseEllipsis%` can probably be rewritten to `%bookSelector_submitButton_choose%` or something. I don't really know the exact purpose of this string, but hopefully this conveys the idea. Same with things that contain "slash", "parentheses", etc. It's not necessary to mirror the contents of the string so literally.
___
*[`assets/localization/en.json` line 87 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9MCf0eA8nOoPM8wjus:-O9MCf0eA8nOoPM8wjut:b-vx1drn) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/assets/localization/en.json#L87)):*
> ```JSON
>   "%webView_menuItemName_edit%": "Edit",
>   "%webView_openProjectSettings%": "Open Project Settings",
>   "%webView_menuItemName_project%": "Project",
> ```

Looks like this key was changed - needs to be reverted to `%webView_project%`. Unless there is a strong reason to change strings, its uses should probably also be changed back
___
*[`assets/localization/en.json` line 88 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9MCkyh1iHHzL3RhdnK:-O9MCkyh1iHHzL3RhdnL:b-w2j045) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/assets/localization/en.json#L88)):*
> ```JSON
>   "%webView_openProjectSettings%": "Open Project Settings",
>   "%webView_menuItemName_project%": "Project",
>   "%webView_menuItemName_projectAssignmentsAndProgress%": "Assignments and Progress",
> ```

Looks like this key was changed - needs to be reverted to `%webView_projectAssignmentsAndProgress%`. Unless there is a strong reason to change strings, its uses should probably also be changed back
___
*[`assets/localization/es.json` line 25 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9PwFOp06n74eRIOhj2:-O9PwFOp06n74eRIOhj3:b4en94u) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/assets/localization/es.json#L25)):*
> ```JSON
>   "%settings_platform_group1_description%": "Configuraciones generales del software fundamental",
>   "%settings_platform_interfaceLanguage_description%": "Lista de locales usados al localizar la interfaz en orden descendente de prioridad. 'en' (inglés) siempre se añade al final, de modo que si no se encuentra una traducción en ninguno de los idiomas especificados, aparecerá en inglés.",
>   "%settings_platform_label_group1%": "Configuraciones de Platform",
> ```

Looks like this string key was renamed and needs to be reverted
___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 16 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9PwayZCJJ1O9mKBHJW:-O9PwayZCJJ1O9mKBHJX:b-1f96tf) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/extensions/src/hello-world/contributions/localizedStrings.json#L16)):*
> ```JSON
>       "%mainMenu_createNewHelloWorldProject%": "Create New Hello World Project",
>       "%mainMenu_deleteHelloWorldProject%": "Delete Hello World Project",
>       "%helloSomeone_greetingLoading%": "Greeting loading",
> ```

Since these strings are about the hello world extension and don't seem to be intended to be used more widely in particular, please prefix all of them with `helloWorld_`. Like this one would probably best be called `helloWorld_greetingLoading`. Then there are the `quickVerse_` and `scripture_` ones that should probably be renamed. Then the `selectProject_` ones are probably good to have `selectProject_` on them, so the prefix can be added like `helloWorld_selectProject_title`
___
*[`extensions/src/platform-scripture/src/checks/inventories/character-inventory.component.tsx` line 80 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9PxXZu8A_RUMmlVz7H:-O9PxXZv7cK7xqt5ep4p:b-uthvc5) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/extensions/src/platform-scripture/src/checks/inventories/character-inventory.component.tsx#L80)):*
> ```XML
> }: CharacterInventoryProps) {
>   const [characterInventoryStrings] = useLocalizedStrings(
>     useMemo(() => CHARACTER_INVENTORY_STRING_KEYS, []),
> ```

Not a big deal, but just fyi this `useMemo` shouldn't be necessary since the array is created outside the function component so its reference is stable. If this `useMemo` is necessary and there are problems without it, might be indicating there is some other problem that needs to be addressed.

This part of the react docs kinda explains what I'm talking about with having stuff created outside the function component not changing on re-renders and therefore not needing to be in dependencies (aka not needing to be artificially stabilized via `useMemo` https://react.dev/learn/removing-effect-dependencies#:~:text=you%20can%20move%20roomId%20out%20of%20your%20component%20to%20prove%20that%20it%E2%80%99s%20not%20reactive
___
*[`extensions/src/platform-scripture/src/checks/inventories/repeated-words-inventory.component.tsx` line 68 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9PxcOv2i5su4pN8aeU:-O9PxcOv2i5su4pN8aeV:by4spb7) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/extensions/src/platform-scripture/src/checks/inventories/repeated-words-inventory.component.tsx#L68)):*
> ```XML
> }: RepeatedWordsInventoryProps) {
>   const [repeatedWordsInventoryStrings] = useLocalizedStrings(
>     useMemo(() => REPEATED_WORDS_INVENTORY_STRING_KEYS, []),
> ```

This looks to be another unnecessary `useMemo` as mentioned in other comments
___
*[`lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json` line 95 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9MCuk47JH3cIpEQZf5:-O9MCuk47JH3cIpEQZf6:bi00hcw) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json#L95)):*
> ```JSON
>   "defaultWebViewTopMenu": {
>     "columns": {
>       "platform.project": { "label": "%webView_menuItemName_project%", "order": 1 },
> ```

Looks like this key was changed - needs to be reverted to `%webView_project%` Same with three others below in this file that were changed
___
*[`src/extension-host/data/core-project-settings-info.data.ts` line 9 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9Pg78B06FN8L9mnAiD:-O9P [...]

2024-10-25 22:48 UTC, katherinejensen00 reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098)* status: 18 of 44 files reviewed, 14 unresolved discussions (waiting on @tjcouch-sil)

___
*[`assets/localization/en.json` line 4 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9Q-uni5GzU5ORdaLqB:-OA4d_x38mIoj0UCSpIf:b-b7qkgm) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/assets/localization/en.json#L4)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It looks to me like many of these are still written with the entire contents of the string in the key. Please take another look over them and revise any that seem to unnecessarily have the entire string contents within the key. Two giveaways that make it seem apparent the key needs to be revised:
1. The key is extremely long like this one. It could possibly be fine with something like maybe `%bookSelector_dialogPrompt_selectBooksForChecks%` or something shorter that conveys the purpose of the string without needing to write every word out
2. The key has punctuation written into it. For example, `%bookSelector_submitButton_chooseEllipsis%` can probably be rewritten to `%bookSelector_submitButton_choose%` or something. I don't really know the exact purpose of this string, but hopefully this conveys the idea. Same with things that contain "slash", "parentheses", etc. It's not necessary to mirror the contents of the string so literally.
</blockquote></details>

I think I better understand the purpose of the keys. I started shortening a bunch of names, but then I realized I was changing some of the names I had reverted in the last code review so then I went and just tried to fix the most egregiously long keys. If there are more that it would be good to rename, I am happy to do that I just started to get nervous about what was okay to change and what wasn't ( I also know my last suggested changes didn't fit the new guidelines so maybe that was the real problem, I'm not sure). One example 'project\_settings\_platform\_group1\_description' could change to 'project\_settings\_platform\overall\_description' to be more specific. All that to say, I am happy to change anything. Thanks for being so patient in helping me learn the new system!
___
*[`assets/localization/en.json` line 39 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-OA4o1Za-P6cq0LOFlqr:-OA4o1Za-P6cq0LOFlqs:bmjxioj) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/assets/localization/en.json#L39)):*
> ```JSON
>   "%mainMenu_Layout%": "Layout",
>   "%mainMenu_menuItemName_aboutPlatformBible%": "About Platform.Bible",
>   "%mainMenu_menuItemName_downloadSlashInstallResources%": "Download/Install Resources",
> ```

I noticed a lot of my changes that had something like menuItemName or settingName got asked to be reverted so I went ahead and reverted the name changes on these by removing the menuItemName from each of the mainMenu keys.
___
*[`assets/localization/en.json` line 87 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9MCf0eA8nOoPM8wjus:-OA4iD4H3TRlzwKksp4h:b-49vczl) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/assets/localization/en.json#L87)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this key was changed - needs to be reverted to `%webView_project%`. Unless there is a strong reason to change strings, its uses should probably also be changed back
</blockquote></details>

I was trying to add consistency/convention, but I can see how that doesn't actually add a lot of clarity and does make it longer. I will revert it.
___
*[`assets/localization/en.json` line 88 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9MCkyh1iHHzL3RhdnK:-OA4i8x5ABvDm0cYsc9l:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/assets/localization/en.json#L88)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this key was changed - needs to be reverted to `%webView_projectAssignmentsAndProgress%`. Unless there is a strong reason to change strings, its uses should probably also be changed back
</blockquote></details>

Done.
___
*[`assets/localization/es.json` line 25 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9PwFOp06n74eRIOhj2:-OA4ilbG9YNzxR-26-ZE:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/assets/localization/es.json#L25)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this string key was renamed and needs to be reverted
</blockquote></details>

Done.
___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 16 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9PwayZCJJ1O9mKBHJW:-OA4keNZAQvBUr4xME6A:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/extensions/src/hello-world/contributions/localizedStrings.json#L16)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since these strings are about the hello world extension and don't seem to be intended to be used more widely in particular, please prefix all of them with `helloWorld_`. Like this one would probably best be called `helloWorld_greetingLoading`. Then there are the `quickVerse_` and `scripture_` ones that should probably be renamed. Then the `selectProject_` ones are probably good to have `selectProject_` on them, so the prefix can be added like `helloWorld_selectProject_title`
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json` line 95 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9MCuk47JH3cIpEQZf5:-OA4lehT0G1tV7RSzwF8:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json#L95)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this key was changed - needs to be reverted to `%webView_project%` Same with three others below in this file that were changed
</blockquote></details>

Done.
___
*[`src/extension-host/data/core-project-settings-info.data.ts` line 9 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9Pg78B06FN8L9mnAiD:-OA4m-p-4OCCUZTNAzvK:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/src/extension-host/data/core-project-settings-info.data.ts#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like the group label and `platform.name`'s `label` were not reverted.
</blockquote></details>

Done.
___
*[`src/extension-host/data/menu.data.json` line 5 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9PhGpC7f4hBv1Ae5FY:-OA4ockM1Ick-aTIvjrL:b-2iayst) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/src/extension-host/data/menu.data.json#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This string key and the following two in this group have different capitalization from what was here before. Please revert them
</blockquote></details>

Not sure what happened there, but I am happy to revert it. Good catch!
___
*[`src/extension-host/data/menu.data.json` line 29 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9Ph8p_8CeqeFxCdiDB:-OA4ppPY3OjgBZjHAwar:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/src/extension-host/data/menu.data.json#L29)):*
<de [...]

2024-10-31 18:04 UTC, tjcouch-sil requested changes
Awesome! Almost there :)

> Reviewed 26 of 26 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098#-:-OAYjS8bDXKp2kwTC9dW:birei3k)* status: all files reviewed, 10 unresolved discussions (waiting on @katherinejensen00)

___
*[`assets/localization/en.json` line 4 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-O9Q-uni5GzU5ORdaLqB:-OAYhlg835PudkFu2Dcg:b-bj2yxx) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/assets/localization/en.json#L4)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

I think I better understand the purpose of the keys. I started shortening a bunch of names, but then I realized I was changing some of the names I had reverted in the last code review so then I went and just tried to fix the most egregiously long keys. If there are more that it would be good to rename, I am happy to do that I just started to get nervous about what was okay to change and what wasn't ( I also know my last suggested changes didn't fit the new guidelines so maybe that was the real problem, I'm not sure). One example 'project\_settings\_platform\_group1\_description' could change to 'project\_settings\_platform\overall\_description' to be more specific. All that to say, I am happy to change anything. Thanks for being so patient in helping me learn the new system!
</blockquote></details>

Thank you for your patience! Sorry for so many rounds of review. We'll make it happen :)

Some pre-existing string keys could be revised to be more specific, but it is generally worth leaving them alone to preserve existing functionality. It's probably best to leave existing keys alone almost always unless there is a very compelling reason to change something.
___
*[`assets/localization/en.json` line 12 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYRzO63egFvqEwQpcO:-OAYRzO63egFvqEwQpcP:b1dx5iz) ([raw file](https://github.com/paranext/paranext-core/blob/9698215dd50285f515914bbb8c3ca17946854ed3/assets/localization/en.json#L12)):*
> ```JSON
>   "%mainMenu_help%": "Help",
>   "%mainMenu_layout%": "Layout",
>   "%mainMenu_openProject%": "Open Project",
> ```

Looks like `%mainMenu_openProject%` has been removed and needs to be re-added here and in `es.json` (the menu item that was removed does not need to be readded, though. Just the string needs to stay)
___
*[`assets/localization/en.json` line 18 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYRgYY4_7DTHB0TGYz:-OAYRgYY4_7DTHB0TGZ-:b-xqzcbx) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/assets/localization/en.json#L18)):*
> ```JSON
>   "%mainMenu_help%": "Help",
>   "%mainMenu_layout%": "Layout",
>   "%mainMenu_aboutPlatformBible%": "About Platform.Bible",
> ```

Looks like this key `%mainMenu_aboutPlatformBible%` was changed from  `%mainMenu_about%` main and needs to be reverted.
___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 7 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYji-A75vf0gT3Umon:-OAYji-A75vf0gT3Umoo:blx1l23) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/extensions/src/hello-world/contributions/localizedStrings.json#L7)):*
> ```JSON
>     },
>     "%mainMenu_openHelloWorldProject%": {
>       "fallbackKey": "%mainMenu_openProject%"
> ```

This fallback is appropriate and should be preserved.
___
*[`extensions/src/hello-world/contributions/projectSettings.json` line 3 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYgjU47LNGlVkuAxst:-OAYgjU47LNGlVkuAxsu:bfrcjsh) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/extensions/src/hello-world/contributions/projectSettings.json#L3)):*
> ```JSON
> [
>   {
>     "label": "%helloWorld_project_settings_helloWorld_group1_label%",
> ```

All these string keys already mentioned that they were for hello world extension. Please revert (remove `helloWorld_` from the front)
___
*[`extensions/src/hello-world/contributions/settings.json` line 3 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYgvOHBgueSgv6wVtZ:-OAYgvOHBgueSgv6wVt_:bfrcjsh) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/extensions/src/hello-world/contributions/settings.json#L3)):*
> ```JSON
> [
>   {
>     "label": "%helloWorld_settings_hello_world_group1_label%",
> ```

All these string keys already mentioned that they were for hello world extension. Please revert (remove `helloWorld_` from the front)
___
*[`extensions/src/platform-scripture-editor/contributions/localizedStrings.json` line 22 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYUVueDJQQOhTA1syd:-OAYUVuf3TcGDFBQRtOI:b-b6ff8y) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/extensions/src/platform-scripture-editor/contributions/localizedStrings.json#L22)):*
> ```JSON
>       "%webView_platformScriptureEditor_title_readonly_no_project%": "Resource Viewer",
>       "%webView_platformScriptureEditor_title_editable_no_project%": "Scripture Editor",
>       "%webView_title_type_formatString%": "{projectId} {editable}",
> ```

I think I suggested some changes in a bit of an unclear way that confused things. `%webView_title_type_formatString%` should be used in `web-view.component.tsx` (a core file) and should be added only to `en.json` (it is properly in that file now, but it should not be in this file). `%webView_platformScriptureEditor_title_format%` should be used in `platform-scripture-editor/src/main.ts` and should only be here in this file. These two format strings have different format replacer names, and they need to be matched up appropriately to their respective file. Since `%webView_title_type_formatString%` is used in `web-view.component.tsx` with `type` and `defaultTitle` as replacers, the string needs to have those replacers in it (which it does in `en.json`). `%webView_platformScriptureEditor_title_format%` was used in `platform-scripture-editor/src/main.ts` before some changes occurred probably because of my unclear instructions. It should be used there instead of `%webView_title_type_formatString%` because its replacers are `projectId` and `editable`. So this file should have `%webView_platformScriptureEditor_title_format%` in it wiht these two replacers `{projectId}` and `{editable}` like it does now but the key is wrong.

Sorry for the unclear feedback! Hope this helps get things straightened out.
___
*[`lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json` line 130 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYWWZk67aqZXkXJEQo:-OAYWWZk67aqZXkXJEQp:b-qnwgwa) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json#L130)):*
> ```JSON
>     "items": [
>       {
>         "label": "%general_insertNote%",
> ```

Looks like this key was changed from main and needs to be reverted to `%insertNote%`
___
*[`src/extension-host/data/core-project-settings-info.data.ts` line 14 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYXCGjAg5xSWmcXbEz:-OAYXCGjAg5xSWmcXbF-:b-ojxqgo) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/src/extension-host/data/core-project-settings-info.data.ts#L14)):*
> ```XML
>     'platform.name': {
>       label: '%project_settings_platform_name_label%',
>       default: '%project_settings_platform_defaultSettingName_noName%',
> ```

Looks like this key was changed from main and needs to be reverted.
___
*[`src/extension-host/data/menu.data.json` line 102 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYXKtJ85AsgVqC4 [...]

2024-11-08 21:20 UTC, katherinejensen00 reviewed
> Dismissed @tjcouch-sil from a discussion.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098)* status: all files reviewed, 9 unresolved discussions (waiting on @tjcouch-sil)

___
*[`assets/localization/en.json` line 12 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYRzO63egFvqEwQpcO:-OB7GVlTDDTE08ZMy_Ap:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/9698215dd50285f515914bbb8c3ca17946854ed3/assets/localization/en.json#L12)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like `%mainMenu_openProject%` has been removed and needs to be re-added here and in `es.json` (the menu item that was removed does not need to be readded, though. Just the string needs to stay)
</blockquote></details>

Done.
___
*[`assets/localization/en.json` line 18 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYRgYY4_7DTHB0TGYz:-OBCdJhIAac2pmoeuHlZ:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/assets/localization/en.json#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this key `%mainMenu_aboutPlatformBible%` was changed from  `%mainMenu_about%` main and needs to be reverted.
</blockquote></details>

Done.
___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 7 at r5](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYji-A75vf0gT3Umon:-OB7GskkC4NeZb5hTJ5x:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a3d57915af202b544b34d8b7304c3b0286bb8d97/extensions/src/hello-world/contributions/localizedStrings.json#L7)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This fallback is appropriate and should be preserved.
</blockquote></details>

Done.
___
*[`extensions/src/hello-world/contributions/projectSettings.json` line 3 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYgjU47LNGlVkuAxst:-OB7HIVw3kWU5dKk9kP1:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/extensions/src/hello-world/contributions/projectSettings.json#L3)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

All these string keys already mentioned that they were for hello world extension. Please revert (remove `helloWorld_` from the front)
</blockquote></details>

Done.
___
*[`extensions/src/hello-world/contributions/settings.json` line 3 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYgvOHBgueSgv6wVtZ:-OB7JXY_E01TWOktDXTF:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/extensions/src/hello-world/contributions/settings.json#L3)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

All these string keys already mentioned that they were for hello world extension. Please revert (remove `helloWorld_` from the front)
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture-editor/contributions/localizedStrings.json` line 22 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYUVueDJQQOhTA1syd:-OBBvlhnElOdpgxgsyBH:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/extensions/src/platform-scripture-editor/contributions/localizedStrings.json#L22)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think I suggested some changes in a bit of an unclear way that confused things. `%webView_title_type_formatString%` should be used in `web-view.component.tsx` (a core file) and should be added only to `en.json` (it is properly in that file now, but it should not be in this file). `%webView_platformScriptureEditor_title_format%` should be used in `platform-scripture-editor/src/main.ts` and should only be here in this file. These two format strings have different format replacer names, and they need to be matched up appropriately to their respective file. Since `%webView_title_type_formatString%` is used in `web-view.component.tsx` with `type` and `defaultTitle` as replacers, the string needs to have those replacers in it (which it does in `en.json`). `%webView_platformScriptureEditor_title_format%` was used in `platform-scripture-editor/src/main.ts` before some changes occurred probably because of my unclear instructions. It should be used there instead of `%webView_title_type_formatString%` because its replacers are `projectId` and `editable`. So this file should have `%webView_platformScriptureEditor_title_format%` in it wiht these two replacers `{projectId}` and `{editable}` like it does now but the key is wrong.

Sorry for the unclear feedback! Hope this helps get things straightened out.
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json` line 130 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYWWZk67aqZXkXJEQo:-OBCUWOw9yFSQPYiBG2z:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/lib/platform-bible-react/src/components/mui/sample.composed.full.menu.json#L130)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this key was changed from main and needs to be reverted to `%insertNote%`
</blockquote></details>

Done.
___
*[`src/extension-host/data/core-project-settings-info.data.ts` line 14 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYXCGjAg5xSWmcXbEz:-OBCVxnH8cFE4TwpijlI:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/src/extension-host/data/core-project-settings-info.data.ts#L14)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this key was changed from main and needs to be reverted.
</blockquote></details>

Done.
___
*[`src/extension-host/data/menu.data.json` line 102 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYXKtJ85AsgVqC48wj:-OBCW8Gn5PvxbPKdu2Jg:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/src/extension-host/data/menu.data.json#L102)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

As in the other file, looks like this key was changed from main and needs to be reverted to `%insertNote%`
</blockquote></details>

Done.
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 82 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYX_-e-hvS3NoI2MTi:-OBCd-De39cQHA9DfYfz:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/src/renderer/components/dialogs/select-project.dialog.tsx#L82)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The usage of this string key is not specific to the hello world extension. I'd recommend something more along the lines of `%selectProject_title%` or something :)

I think I may have figured something out that might have been a source of confusion throughout this PR:

There are some contexts in which a localized string should be used that are similar between core and extensions, but those strings will not always be the same, so they should use different keys when the strings should be different. So for example, here and in Hello World, there is a need to provide a title to a select project dialog. Here, we are providing a pretty general title for a generic select project dialog, so we should just put `%selectProject_title%` -> 'Select Project' in `en.json` (which is what needs to be changed). But in the Hello World extension, we need a specific name for the dialog, so we need to put`%helloWorld_ [...]

2024-11-08 22:17 UTC, tjcouch-sil requested changes
Awesome!! Thanks for the adjustments. Just one more thing to tweak in `en.json`, and this should be good to go!

> Reviewed 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098#-:-OBCqYEG0-p3v8rHTM2A:b-sl0pcp)* status: all files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 82 at r6](https://reviewable.io/reviews/paranext/paranext-core/1098#-OAYX_-e-hvS3NoI2MTi:-OBCq70w3KkGTXus2KcH:bblf7hi) ([raw file](https://github.com/paranext/paranext-core/blob/cedca4bbf8ddc3d6cdae7b43f46652f02edb5e7d/src/renderer/components/dialogs/select-project.dialog.tsx#L82)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Almost there! Looks like one more thing needs to be adjusted here. I put a comment where that adjustment needs to be made.
___
*[`assets/localization/en.json` line 39 at r7](https://reviewable.io/reviews/paranext/paranext-core/1098#-OBCqEYj2-DD8scf8gAY:-OBCqEYj2-DD8scf8gAZ:b-80gkw3) ([raw file](https://github.com/paranext/paranext-core/blob/9652a615b5786de756cc698bace3c7a8deba014d/assets/localization/en.json#L39)):*
> ```JSON
>   "%selectBooks_title_selectBooks%": "Select Books",
>   "%selectMultipleProjects_title_selectProjects%": "Select Projects",
>   "%helloWorld_selectProject_title_selectProject%": "Select Project",
> ```

Looks like this needs to be changed to `%selectProject_title%` to match its use in `src/renderer/components/dialogs/select-project.dialog.tsx`. Everything else looks great!


<!-- Sent from Reviewable.io -->

2024-11-08 22:22 UTC, katherinejensen00 reviewed
Thanks for being so patient! 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098#-:-OBCrXLqELpyjAasUiu6:b6dmz0q)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`assets/localization/en.json` line 39 at r7](https://reviewable.io/reviews/paranext/paranext-core/1098#-OBCqEYj2-DD8scf8gAY:-OBCrQQ-8VE04aOVqnUf:bxqq8dr) ([raw file](https://github.com/paranext/paranext-core/blob/9652a615b5786de756cc698bace3c7a8deba014d/assets/localization/en.json#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this needs to be changed to `%selectProject_title%` to match its use in `src/renderer/components/dialogs/select-project.dialog.tsx`. Everything else looks great!
</blockquote></details>

Oops. Good catch!


<!-- Sent from Reviewable.io -->

2024-11-08 22:23 UTC, tjcouch-sil submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> looks like just merge conflicts left to deal with!! :tada:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098#-:-OBCs2MY4FTv70hMaec7:bpbgic5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-11 18:18 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1098#-:-OBRRhyn-GbBrdIPTWvo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-11 18:18 UTC, merged