Integrate Configure Checks web view
paranext/paranext-core pull request #1099
Opened 2024-08-30 21:01 UTC by rolfheij-sil

2024-09-02 20:02 UTC, irahopkinson reviewed
Looking good - one small tidy-up

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099#-:-O5oK2VP4L0UmiYfmCii:b5einyv)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5oGdTCCXP8i4dkVPgZ:-O5oGdTCCXP8i4dkVPg_:b-dfbfqg) ([raw file](https://github.com/paranext/paranext-core/blob/2bbe5065c180f0bec3585baab29dce077b90b88e/extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts#L44)):*
> ```XML
>         (await (
>           await papi.projectDataProviders.get('platform.base', projectId)
>         ).getSetting('platform.name')) ?? projectId;
> ```

This is pretty ugly code - await inside an await and taking up 4 lines (you probably just copied this from elsewhere). Assign the first await then use it, i.e.
```ts
const pdp = await papi.projectDataProviders.get('platform.base', projectId);
projectName = (await pdp.getSetting('platform.name')) ?? projectId;

```



_Code quote:_
```XML
      projectName =
        (await (
          await papi.projectDataProviders.get('platform.base', projectId)
        ).getSetting('platform.name')) ?? projectId;
```


<!-- Sent from Reviewable.io -->

2024-09-02 22:12 UTC, rolfheij-sil reviewed
Thanks for already taking a look! I'm not done yet, but I like to create the PR soon so that I have an overview of what I already did. And so that others can take an early look :smile: 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099#-:-O5omRXGAB3CTGQ2UZzZ:bm6rg7m)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5oGdTCCXP8i4dkVPgZ:-O5omIWv1qfW_1JTVvg3:b-6xlu6n) ([raw file](https://github.com/paranext/paranext-core/blob/2bbe5065c180f0bec3585baab29dce077b90b88e/extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts#L44)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is pretty ugly code - await inside an await and taking up 4 lines (you probably just copied this from elsewhere). Assign the first await then use it, i.e.
```ts
const pdp = await papi.projectDataProviders.get('platform.base', projectId);
projectName = (await pdp.getSetting('platform.name')) ?? projectId;

```
</blockquote></details>

You're right, that's pretty ugly. I fixed it and changed other occurrences of it too


<!-- Sent from Reviewable.io -->

2024-09-02 22:15 UTC, irahopkinson reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-04 23:28 UTC, irahopkinson requested changes
Thanks for all this work. A few things to look at.

> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099#-:-O5zM5v9-eeX-PAqwVfV:brvsyfc)* status: all files reviewed, 12 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 19 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5ywgr0-zXA248K9tpq:-O5ywgr0-zXA248K9tpr:b9k6oso) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L19)):*
> ```XML
>   const [projectId] = useWebViewState('projectId', '');
>   const [projectName] = useWebViewState('projectName', '');
>   const [selectedChecks, setSelectedChecks] = useState<string[]>([]);
> ```

BTW should `selectedChecks` be pulled from settings so the user doesn't have to select them every time? Perhaps this is out of scope for this issue?
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 21 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5yvrd7Ci1aDzgCMrdF:-O5yvrd7Ci1aDzgCMrdG:btz7bop) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L21)):*
> ```XML
>   const [selectedChecks, setSelectedChecks] = useState<string[]>([]);
> 
>   // eslint-disable-next-line no-type-assertion/no-type-assertion
> ```

Add a reason comment why type assertion is needed rather than the type already being correct. Better yet, fix the types so assertion is not needed - perhaps use generic types so this line would be `const checkRunner = useDataProvider<ICheckRunner>('platformScripture.checkAggregator');`. That might not be possible but it would be better.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 41 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zEGqH7Nv9G-LuKq_S:-O5zEGqH7Nv9G-LuKq_T:byq55hv) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L41)):*
> ```XML
>   );
> 
>   const findCheckId = (checkLabel: string): string | undefined => {
> ```

I think this function needs to use `useCallback` as it is since otherwise it will get re-declared every render. For me a better option would be to pass in `availableChecks` as an argument and then move this declaration outside the webview component (and make it a regular function).



_Code quote:_
```XML
findCheckId
```
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 52 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zF2A-3s8D91FxfqAd:-O5zF2A-3s8D91FxfqAe:bpstj8s) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L52)):*
> ```XML
>   };
> 
>   const updateSelectedChecks = (checkLabel: string, selected: boolean) => {
> ```

I think this function also needs to use `useCallback`.



_Code quote:_
```XML
updateSelectedChecks 
```
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 54 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zFE746TUIbCYzbbPE:-O5zFE746TUIbCYzbbPF:b-wch68c) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L54)):*
> ```XML
>   const updateSelectedChecks = (checkLabel: string, selected: boolean) => {
>     const checkId = findCheckId(checkLabel);
>     if (!checkId) throw new Error(`No available check found with checkLabel ${checkLabel}`);
> ```

nit I like to add a blank line after a throw (or an early return) to make it really obvious there is a disconnect before the next line of code.
___
*[`extensions/src/platform-scripture/src/checks/check-aggregator.service.ts` line 38 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zGAhD7us4wOjEYWe2:-O5zGAhD7us4wOjEYWe3:b-2m2b5m) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/check-aggregator.service.ts#L38)):*
> ```XML
>     ranges: CheckInputRange[],
>   ): Promise<DataProviderUpdateInstructions<CheckRunnerDataTypes>> {
>     logger.error('setActiveRanges on Aggregator:', JSON.stringify(ranges));
> ```

Was this intentionally added or is this debug code? If it's intentional, why does it always log an error?
___
*[`extensions/src/platform-scripture/src/checks/extension-host-check-runner.service.ts` line 204 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zGUTu7xEqDioQVBAC:-O5zGUTu7xEqDioQVBAD:b-2m2b5m) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/extension-host-check-runner.service.ts#L204)):*
> ```XML
>     ranges: CheckInputRange[],
>   ): Promise<DataProviderUpdateInstructions<CheckRunnerDataTypes>> {
>     logger.error('setActiveRanges:', JSON.stringify(ranges));
> ```

Was this intentionally added or is this debug code? If it's intentional, why does it always log an error?
___
*[`extensions/src/platform-scripture/src/checks/configure-checks/book-selector.component.tsx` line 91 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zGeX7BiVU3WJ-RAaN:-O5zGeX7BiVU3WJ-RAaO:bdkxxwy) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/configure-checks/book-selector.component.tsx#L91)):*
> ```XML
>                     .map((bookId: string) => Canon.bookIdToEnglishName(bookId))
>                     .join(', ')
>                 : 'No books are selected'}
> ```

Does this need L10n?



_Code quote:_
```XML
'No books are selected'
```
___
*[`extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx` line 20 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zH_kp0IGcdqjayJMY:-O5zH_kp0IGcdqjayJMZ:b-4aeeaa) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx#L20)):*
> ```XML
> };
> 
> type ConfigureChecksProps = {
> ```

nit I agree with moving this below the exported type but I also prefer types to be just under imports since they are commonly moved to other files and then imported so I'd also move the `const` above to below this type.
___
*[`extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx` line 43 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zLMmL1ZK9X_I82NK5:-O5zLMmL1ZK9X_I82NK6:b731173) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx#L43)):*
> ```XML
>   const [scrRef] = useSetting('platform.verseRef', defaultScrRef);
> 
>   const [useCurrentBook, setUseCurrentBook] = useState<boolean>(false);
> ```

BTW this is an unfortunate use of the word "use" since it has a particular meaning in React. Can we think of another verb or rename the variable some other way? (I know you inherited this variable.)



_Code quote:_
```XML
useCurrentBook
```
___
*[`extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx` line 101 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zKOocDQSatkIJZuws:-O5zKOocDQSatkIJZuwt:b-ca7kp3) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/c [...]

2024-09-05 13:26 UTC, rolfheij-sil reviewed
Thanks for reviewing!

> Reviewed 1 of 19 files at r1, 5 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099#-:-O61M55c-BN91XFGUszJ:b-yz40g0)* status: all files reviewed, 10 unresolved discussions (waiting on @irahopkinson)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 19 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5ywgr0-zXA248K9tpq:-O61HtA80MxbjP3EG-pp:boukv0k) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L19)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW should `selectedChecks` be pulled from settings so the user doesn't have to select them every time? Perhaps this is out of scope for this issue?
</blockquote></details>

Yes I thought about that but I think it's out of scope. Since the checking service doesn't have any awareness of which checks are active and which ones are not (or at least it doesn't have a public function that exposes which checks are enabled/disabled), the state management here might be a little complicated
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 21 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5yvrd7Ci1aDzgCMrdF:-O61IjpT2Sdho8acrDp9:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L21)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Add a reason comment why type assertion is needed rather than the type already being correct. Better yet, fix the types so assertion is not needed - perhaps use generic types so this line would be `const checkRunner = useDataProvider<ICheckRunner>('platformScripture.checkAggregator');`. That might not be possible but it would be better.
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 41 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zEGqH7Nv9G-LuKq_S:-O61J1Il2Civh37pFzv4:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L41)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I think this function needs to use `useCallback` as it is since otherwise it will get re-declared every render. For me a better option would be to pass in `availableChecks` as an argument and then move this declaration outside the webview component (and make it a regular function).
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 52 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zF2A-3s8D91FxfqAd:-O61JXDK80_AaVPcy3SI:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L52)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I think this function also needs to use `useCallback`.
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/checks/check-aggregator.service.ts` line 38 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zGAhD7us4wOjEYWe2:-O61Jc_lBeYQThYO0lyT:b-de690t) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/check-aggregator.service.ts#L38)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Was this intentionally added or is this debug code? If it's intentional, why does it always log an error?
</blockquote></details>

Sorry, that was debug code. Removed it.
___
*[`extensions/src/platform-scripture/src/checks/extension-host-check-runner.service.ts` line 204 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zGUTu7xEqDioQVBAC:-O61Jg-59HZtARy4TadY:b-de690t) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/extension-host-check-runner.service.ts#L204)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Was this intentionally added or is this debug code? If it's intentional, why does it always log an error?
</blockquote></details>

Sorry, that was debug code. Removed it.
___
*[`extensions/src/platform-scripture/src/checks/configure-checks/book-selector.component.tsx` line 91 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zGeX7BiVU3WJ-RAaN:-O61KEbj8Qpw4KGLmePj:buanpin) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/configure-checks/book-selector.component.tsx#L91)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Does this need L10n?
</blockquote></details>

This was debug code too. Removed it.
___
*[`extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx` line 43 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zLMmL1ZK9X_I82NK5:-O61LKL05ZBrMV9L2cye:bjza95r) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx#L43)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW this is an unfortunate use of the word "use" since it has a particular meaning in React. Can we think of another verb or rename the variable some other way? (I know you inherited this variable.)
</blockquote></details>

Agreed. Decided to go with `rangeIsCurrentBook`. As per our conventions it should be `isRangeCurrentBook` but that sounded somewhat confusing to me
___
*[`extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx` line 101 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zKOocDQSatkIJZuws:-O61LXZoCVT7ipDpAtJK:bbgzdxq) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx#L101)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

nit should be lower case, i.e. `ids`.
</blockquote></details>

Removed the variable entirely
___
*[`extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx` line 109 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zIqBNDNaldkkr-h4Y:-O61M-CO0fDHgD_DXkAr:boti150) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx#L109)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

L10n?
</blockquote></details>

I removed the line entirely. It basically says the same thing as it says in the toolbar of the web view, which is localized


<!-- Sent from Reviewable.io -->

2024-09-05 14:27 UTC, tjcouch-sil requested changes
This is awesome! Very excited for this. Just a handful of comments.

> Reviewed 13 of 19 files at r1, 2 of 3 files at r2, 7 of 13 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099#-:-O61_F9XEapfexi4t3qO:bxxu7ag)* status: all files reviewed, 11 unresolved discussions (waiting on @irahopkinson and @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 21 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5yvrd7Ci1aDzgCMrdF:-O61RH4X1kHftOcuPlKw:b-dbboy9) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L21)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually I'm surprised to see `as ICheckRunner` is needed in the first place. Does the object returned not have the right type already? It probably should, so maybe something is going wrong and needs a bug filed or something if so.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 53 at r4](https://reviewable.io/reviews/paranext/paranext-core/1099#-O61Wxl-AGbchvTroKNd:-O61Wxl-AGbchvTroKNe:bo9q1zk) ([raw file](https://github.com/paranext/paranext-core/blob/dbae0555384d7cd5e18f3f764f319610d25551f3/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L53)):*
> ```XML
>   const [activeRanges, setActiveRanges] = useData('platformScripture.checkAggregator').ActiveRanges(
>     undefined,
>     [defaultScriptureRange],
> ```

As annoying as it is, wrapping in an array makes this have a new reference every render. It's probably not a huge deal since this is just *used* once at the first render of this component, but this does create a new array pointlessly every render.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts` line 42 at r4](https://reviewable.io/reviews/paranext/paranext-core/1099#-O61XqkKAyzqMYMJ9WBH:-O61XqkKAyzqMYMJ9WBI:bjcniru) ([raw file](https://github.com/paranext/paranext-core/blob/dbae0555384d7cd5e18f3f764f319610d25551f3/extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts#L42)):*
> ```XML
>       projectName = (await pdp.getSetting('platform.name')) ?? projectId;
> 
>       title += ` - ${projectName}`;
> ```

When concatenating localized strings in any other way than newline (colon, parentheses, plain space, quotes, hyphen, etc.), it is generally best to use string formatting with a format localized string to concatenate the strings in a localizable manner. That way, if the strings are concatenated in a way that doesn't make sense in a locale, they can change how the string is concatenated and format it differently.

Example: [string key](https://github.com/paranext/paratext-bible-internal-extensions/blob/bd3989092457764f720b0d9d5383e39f4155dd99/src/paratext-bible-send-receive/contributions/localizedStrings.json#L86) and [usage](https://github.com/paranext/paratext-bible-internal-extensions/blob/bd3989092457764f720b0d9d5383e39f4155dd99/src/paratext-bible-send-receive/src/components/send-receive-view.component.tsx#L221)


----

Sorry, this is a rule I haven't recorded anywhere yet... :( I have been meaning to make a section in the code style guide about various localized string rules since last week, but I have been sick.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts` line 51 at r4](https://reviewable.io/reviews/paranext/paranext-core/1099#-O61Y9-I7A2Ltd-WBwcO:-O61Y9-I7A2Ltd-WBwcP:byp5qxl) ([raw file](https://github.com/paranext/paranext-core/blob/dbae0555384d7cd5e18f3f764f319610d25551f3/extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts#L51)):*
> ```XML
>       styles: configureChecksWebViewStyles,
>       state: {
>         projectId,
> ```

Putting `projectId` here before `...savedWebView.state` means `savedWebView.state.projectId` will overwrite `projectId` if it exists. Looking at your code, I don't think this is your intention. I'd recommend swapping these two lines so `...savedWebView.state` happens first then `projectId` gets precedence in the final value (if this is your intention).
___
*[`extensions/src/platform-scripture-editor/contributions/localizedStrings.json` line 15 at r4](https://reviewable.io/reviews/paranext/paranext-core/1099#-O61ZYsq4yWxX39rIvWa:-O61ZYsq4yWxX39rIvWb:bgupz8c) ([raw file](https://github.com/paranext/paranext-core/blob/dbae0555384d7cd5e18f3f764f319610d25551f3/extensions/src/platform-scripture-editor/contributions/localizedStrings.json#L15)):*
> ```JSON
>       "%webView_platformScriptureEditor_charactersInventory%": "Inventory: Characters",
>       "%webView_platformScriptureEditor_repeatedWordsInventory%": "Inventory: Repeated Words",
>       "%webView_platformScriptureEditor_configureChecks%": "Configure Checks",
> ```

When a menu item's primary purpose is to open a dialog (or web view in our case), it should have an ellipsis. Is that still the case here? I think it is, but I'm not sure. Just checking in. Also on the line below
___
*[`extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx` line 43 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zLMmL1ZK9X_I82NK5:-O61Z4RTDl7pYOfBydWy:b-6jlliu) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx#L43)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Agreed. Decided to go with `rangeIsCurrentBook`. As per our conventions it should be `isRangeCurrentBook` but that sounded somewhat confusing to me
</blockquote></details>

`shouldUseCurrentBook`? `isRangeInCurrentBook`? Doesn't matter that much to me; just ideas in case anything seems interesting
___
*[`extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx` line 101 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5zKOocDQSatkIJZuws:-O61ZJcY35-vy5aaVMv4:bh3igcs) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/checks/configure-checks/configure-checks.component.tsx#L101)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Removed the variable entirely
</blockquote></details>

⚰️🪦


<!-- Sent from Reviewable.io -->

2024-09-05 15:33 UTC, lyonsil approved these changes
Thanks for putting up the first part of this work, Rolf. It looks great overall. I added a few thoughts but nothing new/blocking.

> Reviewed 13 of 19 files at r1, 2 of 3 files at r2, 7 of 13 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099#-:-O61oAkN5U2rbLmm5E9n:b-1g3ueh)* status: all files reviewed, 10 unresolved discussions (waiting on @irahopkinson and @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 19 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5ywgr0-zXA248K9tpq:-O61iLOj0e1TMABt_m5y:b-wvxr7x) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L19)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Yes I thought about that but I think it's out of scope. Since the checking service doesn't have any awareness of which checks are active and which ones are not (or at least it doesn't have a public function that exposes which checks are enabled/disabled), the state management here might be a little complicated
</blockquote></details>

@rolfheij-sil The `AvailableChecks` data type includes which checks are enabled/disabled per project.
```typescript
  export type CheckDetails = {
    /** Name or {@link LocalizeKey} of the name of the check to display in UI */
    checkName: string | LocalizeKey;
    /** Description or {@link LocalizeKey} of the description of the check to display in UI */
    checkDescription: string | LocalizeKey;
  };

  export type CheckDetailsWithCheckId = CheckDetails & {
    /** Unique ID of the check within the set of all possible checks */
    checkId: string;
  };

  export type CheckRunnerCheckDetails = CheckDetailsWithCheckId & {
    /** List of project IDs that one particular check is enabled to evaluate */
    enabledProjectIds: string[];
  };

  export type CheckRunnerDataTypes = {
    AvailableChecks: DataProviderDataType<undefined, CheckRunnerCheckDetails[], never>;
    ActiveRanges: DataProviderDataType<undefined, CheckInputRange[], CheckInputRange[]>;
    CheckResults: DataProviderDataType<undefined, CheckRunResult[], never>;
  };
```

Having said that, I'm not suggesting that this PR should include settings/state management for the service. I don't think it's immediately necessary, and I think we have a little time to think about where we want that to reside. It could be the check service. It could be something else. Whatever it is will have to consider that checks and projects may not be available immediately when initializing, so there will have to be some sort of delayed initialization.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 21 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5yvrd7Ci1aDzgCMrdF:-O61kH6k2HBB3eRbp1iB:b5jexn1) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L21)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Actually I'm surprised to see `as ICheckRunner` is needed in the first place. Does the object returned not have the right type already? It probably should, so maybe something is going wrong and needs a bug filed or something if so.
</blockquote></details>

When Rolf and I were looking at this, I believe `useDataProvider` only gave access to the "normal" data types, not the extra two functions `enableCheck` and `disableCheck`. Type casting was the only way for TS to recognize those two functions that we saw. I don't think we tried Ira's suggestion at the time, though. If it works, great. If it doesn't, then we can open a ticket.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 62 at r4](https://reviewable.io/reviews/paranext/paranext-core/1099#-O61nov61aW_VDY5ALWN:-O61nov7222_-5y7LpUr:b-gn8ag2) ([raw file](https://github.com/paranext/paranext-core/blob/dbae0555384d7cd5e18f3f764f319610d25551f3/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L62)):*
> ```XML
> 
>       if (selected) {
>         checkRunner.enableCheck(checkId, projectId);
> ```

If we keep the current design, you'll want to use the return value here to see what errors/warnings come from the check. This design requires that we disable/re-enable a check to get its latest warnings/errors.
___
*[`extensions/src/platform-scripture-editor/contributions/localizedStrings.json` line 15 at r4](https://reviewable.io/reviews/paranext/paranext-core/1099#-O61ZYsq4yWxX39rIvWa:-O61nKHRBRpwRWIGW8p-:b1rcvlo) ([raw file](https://github.com/paranext/paranext-core/blob/dbae0555384d7cd5e18f3f764f319610d25551f3/extensions/src/platform-scripture-editor/contributions/localizedStrings.json#L15)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

When a menu item's primary purpose is to open a dialog (or web view in our case), it should have an ellipsis. Is that still the case here? I think it is, but I'm not sure. Just checking in. Also on the line below
</blockquote></details>

@Sebastian-ubs ? @merchako ? @ianhewubs ? Any opinions here? Seems like a style guide-type question.


<!-- Sent from Reviewable.io -->

2024-09-05 19:34 UTC, irahopkinson requested changes
> Reviewed 3 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 21 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5yvrd7Ci1aDzgCMrdF:-O62eHVh-obuGHub2sco:bfsa9xr) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L21)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Ira's suggestion doesn't work, unfortunately
</blockquote></details>

Err, if you change `useDataProvider` to accept a generic type `T` then you can at least do the type assert there and then you would have only one comment for type assertion rather than everywhere you use it. Also if you later fix the types properly you can usually retain the generic type because it won't need to be specified (making it backward compatible where uses have already specified it).


<!-- Sent from Reviewable.io -->

2024-09-05 19:37 UTC, irahopkinson submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 21 at r3](https://reviewable.io/reviews/paranext/paranext-core/1099#-O5yvrd7Ci1aDzgCMrdF:-O62gBm25FJQD_8rDGeq:b-hyrv2y) ([raw file](https://github.com/paranext/paranext-core/blob/3cd8c69868bf266a5acacdb58c81f6ebe14c5f71/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L21)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Err, if you change `useDataProvider` to accept a generic type `T` then you can at least do the type assert there and then you would have only one comment for type assertion rather than everywhere you use it. Also if you later fix the types properly you can usually retain the generic type because it won't need to be specified (making it backward compatible where uses have already specified it).
</blockquote></details>

I see it already has a generic type so it will likely need to be fixed properly.


<!-- Sent from Reviewable.io -->

2024-09-05 21:19 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 13 files at r3, 5 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099#-:-O632Rw-12aHqonlhZ8y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-05 21:27 UTC, irahopkinson approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1099)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-05 21:30 UTC, merged