Add comment about removal of tailwind class from input component
paranext/paranext-core pull request #1173
Opened 2024-09-27 14:51 UTC by rolfheij-sil

2024-09-27 15:51 UTC, tombogle commented on lib/platform-bible-react/src/components/shadcn-ui/input.tsx
> +          // Removed pr-h-10, as it might the component look very different than other shadcn components. This was not discussed this with UX
I think you meant to  say: Removed pr-h-10, as it made the component look very different than other shadcn components. This was not discussed with UX.

2024-09-27 15:56 UTC, tjcouch-sil requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1173#-:-O7o85t01FERFsS2gGN1:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/shadcn-ui/input.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1173#-O7o9Nwa5fW6WdjiKfH3:-O7o9Nwa5fW6WdjiKfH4:b-38nwdj) ([raw file](https://github.com/paranext/paranext-core/blob/4d93d5f746e904680c0983fcbacb94175b3c0321/lib/platform-bible-react/src/components/shadcn-ui/input.tsx#L12)):*
I don't understand from this comment what is the reason for removing this. Also it would be good to indicate what the change does to the component. Sorry I didn't mention this before. Did you say you removed it so we could change the height in other places? If so, maybe this could be an effective comment:

> Removed pr-h-10, making the input a few pixels shorter, because we need to be able to resize this easily in other places.

Why not discuss with UX? Could be as simple as passing by Sebastian (hopefully) real quick. Here's a comparison image for the sake of discussing with UX. I tested with smaller font size and determined that smaller font size does not change the height. Also, you can't type multiple lines in this, so that wouldn't have an effect on the height either.

![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/uckALNBEKT3xxU_aCEAyhBgz/image.png)


<!-- Sent from Reviewable.io -->

2024-09-27 15:57 UTC, tjcouch-sil reviewed
Sorry, accidental LGTM :grimacing: I did request some changes

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1173#-:-O7oBmav3sRDAVwqnvFT:b-hiftbl)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)



<!-- Sent from Reviewable.io -->

2024-09-27 18:51 UTC, tjcouch-sil submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1173#-:-O7oop928n7FI4KSw4Yl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)



<!-- Sent from Reviewable.io -->

2024-09-27 19:40 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1173)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`lib/platform-bible-react/src/components/shadcn-ui/input.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1173#-O7o9Nwa5fW6WdjiKfH3:-O7oIgUO4z1ZK-L735TF:b-bufvvp) ([raw file](https://github.com/paranext/paranext-core/blob/4d93d5f746e904680c0983fcbacb94175b3c0321/lib/platform-bible-react/src/components/shadcn-ui/input.tsx#L12)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I don't understand from this comment what is the reason for removing this. Also it would be good to indicate what the change does to the component. Sorry I didn't mention this before. Did you say you removed it so we could change the height in other places? If so, maybe this could be an effective comment:

> Removed pr-h-10, making the input a few pixels shorter, because we need to be able to resize this easily in other places.

Why not discuss with UX? Could be as simple as passing by Sebastian (hopefully) real quick. Here's a comparison image for the sake of discussing with UX. I tested with smaller font size and determined that smaller font size does not change the height. Also, you can't type multiple lines in this, so that wouldn't have an effect on the height either.

![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/uckALNBEKT3xxU_aCEAyhBgz/image.png)
</blockquote></details>

This is the behavior I observed

with pr-h-10

![image.png](https://files.reviewableusercontent.io/images/reviewable/108285668/vbQtLzEpjnkn3LQWbBg9ClI0/image.png)

without pr-h-10

![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/108285668/NGJt-r2apVM3TAublvV85vnX/image.png)

However, I just ran it by Sebastian, and it seems like this was not related to just pr-h-10, I think it had more to do with pr-twp. So I will actually restore pr-h-10, as that seems to be more in line with the other shadcn components
___
*[`lib/platform-bible-react/src/components/shadcn-ui/input.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1173#gh-1778837427:-O7oCkbK4s_kj5Qnyv_e:b-szwlbs) ([raw file](https://github.com/paranext/paranext-core/blob/4d93d5f746e904680c0983fcbacb94175b3c0321/lib/platform-bible-react/src/components/shadcn-ui/input.tsx#L12)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I think you meant to  say: Removed pr-h-10, as it made the component look very different than other shadcn components. This was not discussed with UX.
</blockquote></details>

Thanks for checking my spelling. I can't do words today. The comment has been removed, so that should fix it too


<!-- Sent from Reviewable.io -->

2024-09-27 22:23 UTC, tombogle commented
*[`lib/platform-bible-react/src/components/shadcn-ui/input.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1173#gh-1778837427:-O7p_2uM9LM--j1tVN5K:b-3r0f3m) ([raw file](https://github.com/paranext/paranext-core/blob/4d93d5f746e904680c0983fcbacb94175b3c0321/lib/platform-bible-react/src/components/shadcn-ui/input.tsx#L12)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Thanks for checking my spelling. I can't do words today. The comment has been removed, so that should fix it too
</blockquote></details>

My understanding from the component guidelines document was that we were supposed to document this kind of change. No?


<!-- Sent from Reviewable.io -->

2024-09-28 00:08 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1173)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`lib/platform-bible-react/src/components/shadcn-ui/input.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1173#gh-1778837427:-O7pwTD40wL8F08aMy0w:bnox271) ([raw file](https://github.com/paranext/paranext-core/blob/4d93d5f746e904680c0983fcbacb94175b3c0321/lib/platform-bible-react/src/components/shadcn-ui/input.tsx#L12)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

My understanding from the component guidelines document was that we were supposed to document this kind of change. No?
</blockquote></details>

Yes, we should document any changes we make to shadcn code. However, this issue was about adding a comment to a change that had been made in a previous pr. Today I found out that change was actually unneccessary, and so I reverted the change by putting pr-h-10 back. So the code is back to how we got it from shadcn when we installed the component, and so a comment is not needed here


<!-- Sent from Reviewable.io -->

2024-09-30 15:16 UTC, tjcouch-sil submitted a review, later dismissed
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1173)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2024-09-30 15:29 UTC, tjcouch-sil approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1173)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2024-09-30 17:53 UTC, tombogle approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-30 17:53 UTC, merged