First draft of adding support for comments in PT9 projects
paranext/paranext-core pull request #1175
Opened 2024-09-27 20:41 UTC by lyonsil

There are a few known issues with comment support provided by this PR for now:
- PT9 comments give offsets in USFM space, not verse text space. Once we have text in USJ format, though, there isn't a simple way to work back in USFM space. So some comments are not going to be located on the text where you would expect.
- PT9 comments may be located immediately before USFM markup, so we might not find the end of the selected text properly for the comment since we don't have access to the markup in USJ space.
- To avoid problems with data loss given the last two issues, this change purposefully doesn't allow you to edit or delete comments in PT9. You can view and add comments in P.B but not edit or delete them. (The UI might say it is deleted, but if you change chapters and go back, the comment is still there.) Once we have more confidence on how to approach the previous two problems, we can enable comment updating/deleting.
- You can only add new comment threads, not more comments added onto threads. For some reason, when the `onUsjChange` callback runs when you add comments to threads, the second argument (the list of comments) is coming back undefined. I'll need to look at this with @irahopkinson to figure out what's up. You can view threads of existing comments, though.
- PT9 comments are stored in HTML/XML form. We are only displaying comments as raw text. So you might see some XML markup in comment text from PT9 projects.
- Unit test coverage isn't as good as it should be for the new UsjDocument utilities. I just created unit tests for the first few functions I created when I was getting started building the utilities.

Because I don't know if we're going to merge this as-is, I haven't created tickets for any of these things yet.

2024-09-30 03:00 UTC, irahopkinson requested changes
It would be good to talk about this with you. I have reviewed individual code here but there is so much it is hard for me to see how it works as a whole.

> Reviewed 24 of 24 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175#-:-O8-rRwGDX_YqsZh2_US:b-lnpfn2)* status: all files reviewed, 24 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 233 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zO9_a41ZjcKZa1fAz:-O7zO9_a41ZjcKZa1fB-:b-42f112) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/c-sharp/Projects/ParatextProjectDataProvider.cs#L233)):*
> ```Smalltalk
>         if (!string.IsNullOrEmpty(selector.CommentId))
>             comments = comments.FindAll((c) => selector.CommentId == c.Id);
>         Console.WriteLine($"Returning {comments.Count} comments: {string.Join(",", comments)}");
> ```

BTW is this a debug line or is it still needed?
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 262 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zQ9kCADsLEg8Cwc9U:-O7zQ9kD9-tMLUU-0kUc:b-42f112) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/c-sharp/Projects/ParatextProjectDataProvider.cs#L262)):*
> ```Smalltalk
>                 continue;
>             _commentManager.AddComment(ic);
>             Console.WriteLine($"Saving comment: {ic}");
> ```

BTW is this a debug line or is it still needed?
___
*[`extensions/src/legacy-comment-manager/src/main.ts` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zR1sS-XYXKjA_JyL0:-O7zR1sT1mt8naiR5Q1U:baf5np5) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/legacy-comment-manager/src/main.ts#L5)):*
> ```XML
> export async function activate() {
>   logger.info('Legacy comment manager is activating!');
>   /*
> ```

Looks like this is debug and should be reverted.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 53 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-a56MAh7mSmxPtYWH:-O8-a56MAh7mSmxPtYWI:bfhfmx2) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L53)):*
> ```XML
> }
> 
> type EditorComment = {
> ```

BTW I'd put most/all of this comment stuff in its own file and import it here since we may want to use it elsewhere. That would also reduce the clutter here (even if we don't need it elsewhere).
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 218 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-l50lBe-OVfMGbUpv:-O8-l50lBe-OVfMGbUpw:b-40go8h) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L218)):*
> ```XML
>   const anchorNode = { type: 'ms', marker: anchorMarker, [idType]: anchorId };
>   const currentContent = contentArray[contentIndex];
>   // If it's an end anchor and the comment didn't specify where it goes, pick a place
> ```

BTW when would a comment not specify an end location?
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 312 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-lelX6RCzB14WYCil:-O8-lelX6RCzB14WYCim:bi6ef1o) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L312)):*
> ```XML
>       if (!setUsjRaw) return;
>       const usjDoc = new UsjDocument(newUsj);
>       // Remove the milestones that we inserted before writing back to the PDP
> ```

Are you using the `assets-excluded/custom.sty` file for any projects you want to use comments with?
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 398 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-oS9w4TaRg7JvMMr8:-O8-oS9w4TaRg7JvMMr9:b-2sxegr) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L398)):*
> ```XML
>       setLegacyComments(newLegacyComments);
> 
>       if (usjChanged) setUsj?.(newUsj);
> ```

This looks like it will set the usj twice (once here and again in `onUsjChange`) and that would be a bad idea. Also here it is doing it without the debounce which will also cause problems.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 406 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-mhGuASe4Kbkm2Sra:-O8-mhGuASe4Kbkm2Srb:b-x8bjx1) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L406)):*
> ```XML
>   const onUsjChange = useCallback(
>     (newUsj: Usj, newComments: Comments | undefined) => {
>       // There is a bug where the editor's onChange runs when the state is externally set, so let's
> ```

BTW I believe this is no longer needed but I have not had time to check it and I didn't want to break things just before the demo.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 429 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-qjWx662icKTAawlQ:-O8-qjWx662icKTAawlR:bbnzjol) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L429)):*
> ```XML
>     // but we need to compare in such a way that the same object across iframes works fine
>     if (usj && !deepEqualAcrossIframes(usj, editorUsj.current)) {
>       updateCommentsInUsj(usj, undefined);
> ```

What is this meant to be doing? It looks like it is relying on side-effects?
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zpdtd8EgKrXdOKy7S:-O7zpdtd8EgKrXdOKy7T:bhwh1h0) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L1)):*
> ```XML
> /* eslint-disable @typescript-eslint/member-ordering */
> ```

BTW you should add a comment why this has been disabled or order them appropriately. My guess is that static methods should be grouped above instance methods.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7ziP9_EGqwE--e_0Lg:-O7ziP9_EGqwE--e_0Lh:br1s6us) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L19)):*
> ```XML
> } from './usj-document.model';
> 
> const NODE_TYPES_NOT_CONTAINING_VERSE_TEXT = ['figure', 'note', 'sidebar', 'table'];
> ```

BTW I don't use this UPPER_SNAKE_CASE syntax for `const` arrays and objects because it is only the pointer to the array/object that is constant and not its content (which can still be changed). So I just use the usual camelCase for these.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 28 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-G8Wu3kf2AWFW9fwu:-O8-G8Wu3kf2AWFW9fwv:bhlebg0) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L28)):*
> ```XML
>  * be the root Usj object. `index` represents the index numeric inside  [...]

2024-09-30 15:57 UTC, lyonsil reviewed
Thanks for the detailed review! I would definitely like to talk this through. 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175#-:-O82d_Iw1rnCKxxXToxs:b9hrz2z)* status: all files reviewed, 24 unresolved discussions (waiting on @irahopkinson)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 233 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zO9_a41ZjcKZa1fAz:-O82ECcUDF0TqqG2REVl:b-kqhyaz) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/c-sharp/Projects/ParatextProjectDataProvider.cs#L233)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW is this a debug line or is it still needed?
</blockquote></details>

Ah, it's leftover debug code. I should remove it.
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 262 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zQ9kCADsLEg8Cwc9U:-O82ET7xBlCuiGCv7EVk:bau2gbf) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/c-sharp/Projects/ParatextProjectDataProvider.cs#L262)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW is this a debug line or is it still needed?
</blockquote></details>

Leftover debugging - I can remove it
___
*[`extensions/src/legacy-comment-manager/src/main.ts` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zR1sS-XYXKjA_JyL0:-O82EWXeC7FYRe22YbdF:b2yuzec) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/legacy-comment-manager/src/main.ts#L5)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Looks like this is debug and should be reverted.
</blockquote></details>

I was considering leaving this in on purpose. If someone needs to work on the data provider it would be nice to have a way to quickly test that, and it's easier to use a code block like this than to figure out how to write it again. Having said that, it's not critical to leave it in.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 53 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-a56MAh7mSmxPtYWH:-O82HQtOAIrjfmGB9n8s:bah8t2) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L53)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I'd put most/all of this comment stuff in its own file and import it here since we may want to use it elsewhere. That would also reduce the clutter here (even if we don't need it elsewhere).
</blockquote></details>

I'm happy to reorganize and split into more files. I think it would be good to talk this through with someone before I just start moving things. I am doubtful about reuse, but for sure reorganizing could be nice.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 218 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-l50lBe-OVfMGbUpv:-O82Gipv7p6CNHVvoKZb:b-ak7648) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L218)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW when would a comment not specify an end location?
</blockquote></details>

I don't know all the cases where this is true in PT9, but I've seen projects with comment XML files containing comments without `ContextAfter` values. From what I can see, the main sources of those comments are send/receive conflicts. But that doesn't seem to be the only case.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 312 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-lelX6RCzB14WYCil:-O82Hmid5b8Xcz3uNhfZ:bxiopvo) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L312)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Are you using the `assets-excluded/custom.sty` file for any projects you want to use comments with?
</blockquote></details>

No, but this is part of the larger issue related to offsets in PT9 comments files working in USFM space. If we want to move forward with this PR, I think we'll need a specific follow up ticket to resolve that problem, and what you mention here should probably be part of that ticket.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 398 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-oS9w4TaRg7JvMMr8:-O82aZa96SOdXX2VX_DU:b-ghf882) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L398)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This looks like it will set the usj twice (once here and again in `onUsjChange`) and that would be a bad idea. Also here it is doing it without the debounce which will also cause problems.
</blockquote></details>

This is worth talking through.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 406 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-mhGuASe4Kbkm2Sra:-O82bXb57cnYiLXiXgUy:b-v45dvd) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L406)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I believe this is no longer needed but I have not had time to check it and I didn't want to break things just before the demo.
</blockquote></details>

If you want me to remove it let me know.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 429 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-qjWx662icKTAawlQ:-O82aotbCZ3lgRb7zDHQ:b-coc9wm) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L429)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

What is this meant to be doing? It looks like it is relying on side-effects?
</blockquote></details>

Whenever USJ is pushed into the editor, I need to inject `updateCommentsInUsj` into the process so I have a chance to add the anchors to the USJ. Although comments are `undefined` here, the source of comments data can be external (i.e., the data provider).
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zpdtd8EgKrXdOKy7S:-O82IlgD6G-DeEfoewe-:b-pc1hhz) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW you should add a comment why this has been disabled or order them appropriately. My guess is that static methods should be grouped above instance methods.
</blockquote></details>

I don't love this rule, but I have been following it normally. I strongly dislike it for this class in particular and decided to disable it. Class methods really ought to be organized by pur [...]

2024-09-30 16:41 UTC, tjcouch-sil requested changes
Didn't get through everything, but I need to go for now. Will resume later! Thanks for all this great work!

> Reviewed 21 of 24 files at r1, 2 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175#-:-O82nZSwES9N1SPDF5wb:b-kmozmx)* status: all files reviewed, 27 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 212 at r1](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7pZ-Qs1Ay2cRI-GWJi:-O7pZ-Qs1Ay2cRI-GWJj:bpvtdvz) ([raw file](https://github.com/paranext/paranext-core/blob/15b391f09202a27f9cb572cf4e0563dba9039877/c-sharp/Projects/ParatextProjectDataProvider.cs#L212)):*
> ```Smalltalk
>     #region Comments
> 
>     public ResponseToRequest GetComment(string jsonSelector)
> ```

Should this be called "GetComments" since it returns an array and you set an array of comments with it? I do recognize you can pass an id and get one comment back, but it's still in an array even then. Bit awkward, but 
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 230 at r1](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7p_2Ej1D0rihKw6kvA:-O7p_2Ej1D0rihKw6kvB:b-oni0kv) ([raw file](https://github.com/paranext/paranext-core/blob/15b391f09202a27f9cb572cf4e0563dba9039877/c-sharp/Projects/ParatextProjectDataProvider.cs#L230)):*
> ```Smalltalk
>             matchingVerseRef = selector.BookId;
> 
>         comments = comments.FindAll((c) => c.VerseRefStr.StartsWith(matchingVerseRef));
> ```

It looks to me like `CommentSelector`'s `BookId` has a default value in C# but is marked as required in TypeScript. This code seems to indicate that `BookId` is required since it always filters comments by book. Should the default value be removed from C#? Or maybe set to empty string and checked here to make sure it is present or something? Or I could definitely be reading something wrong
___
*[`extensions/src/legacy-comment-manager/src/types/legacy-comment-manager.d.ts` line 80 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O82Q-L85FloGL0l_Bc0:-O82Q-L85FloGL0l_Bc1:b-gb6vjs) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/legacy-comment-manager/src/types/legacy-comment-manager.d.ts#L80)):*
> ```XML
> 
>   export interface ProjectDataProviderInterfaces {
>     'legacyCommentManager.Comment': ILegacyCommentProjectDataProvider;
> ```

Generally we do lowerCamelCase on both sides for these id strings - I'd think that's the way to go here as well unless there's a particular reason for it to be upper.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 398 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-oS9w4TaRg7JvMMr8:-O82dmSCEXJU_UGVVaZ4:bvq6za8) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L398)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This is worth talking through.
</blockquote></details>

Probably need to cancel or flush the debounce here, which I believe is not currently supported in our `debounce`. You could attach it to the returned function like this https://stackoverflow.com/a/41853194 same way [`lodash` does their debounce](https://lodash.com/docs/4.17.15#debounce).
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 429 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-qjWx662icKTAawlQ:-O82g8n45IqkVX-H2qGh:b2fc6le) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L429)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Whenever USJ is pushed into the editor, I need to inject `updateCommentsInUsj` into the process so I have a chance to add the anchors to the USJ. Although comments are `undefined` here, the source of comments data can be external (i.e., the data provider).
</blockquote></details>

This is indeed difficult to read. I think it might be difficult because of the lack of clear rules regarding how the parameters passed in are used and how they interact with the component's state and the conditional side effects. The usj passed in is sometimes set to the usj in the component but not always, and it depends on the legacy comments under the hood. The comments passed in are new format comments, but it is difficult to understand what exactly their relationship to the function is.

It seems like maybe there are three things going on in this function:
1. Make sure anchors are in the usj for all legacy comments
2. Overwrite the legacy comments with the new editor-format comments
3. IF the new comments are different than the legacy comments, set the usj if this function changed it irrespective of if this usj passed in is different than the usj in this component's state

I would suggest renaming the function, considering splitting `updateCommentsInUsj` up a bit, and maybe making the interactions between parameters and state more consistent. Or possibly even consider making it a stateless function where you pass in everything you need and pulling the function out of the component.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 495 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O82jX1s107lxkZ_v1Oc:-O82jX1s107lxkZ_v1Od:b-x9jmf4) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L495)):*
> ```XML
>       {/* Workaround to pull in platform-bible-react styles into the editor */}
>       <Button className="pr-hidden" />
>       <Editorial
> ```

I don't remember 100% if this works, but you may be able to do something like the following here to reduce repetition:

```tsx
const EditorComponent = isReadOnly ? Editorial : Marginal;

return (
  <>
    ...stuff
    <EditorComponent
      propshere
    />
  </>
);
```
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7ziP9_EGqwE--e_0Lg:-O82kFDH6T0eszqp3vmx:b-ucavuv) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L19)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This might be a carryover of C# style. I don't have a strong preference here and can change it.
</blockquote></details>

We discussed this a while ago with one of my PRs. We settled on that you could use `Object.freeze` on the array and keep it upper snake case.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 265 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-INW7DtQFFWJ79LdC:-O82kqAZ9h-L0VZ9nkgq:b1is69b) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L265)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I originally write it exactly like you suggest, but I changed the syntax to how it is now to avoid a linting issue saying I wasn't using destructuring. I can change it back and disable the lint error.
</blockquote></details>

Gotta love javascript
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 479 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-VFcD24ztG1HaigB_:-O82miqF4oOZtlcLOOrJ:b-gfm9ot) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts# [...]

2024-09-30 18:11 UTC, lyonsil reviewed
Thanks for the feedback. Maybe the 3 of us can talk after stand up today?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175#-:-O837MwM-W8PNtDQtnG2:btyxi0d)* status: all files reviewed, 27 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 212 at r1](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7pZ-Qs1Ay2cRI-GWJi:-O8319Wu72_WW14Pg2SS:b-si3t46) ([raw file](https://github.com/paranext/paranext-core/blob/15b391f09202a27f9cb572cf4e0563dba9039877/c-sharp/Projects/ParatextProjectDataProvider.cs#L212)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should this be called "GetComments" since it returns an array and you set an array of comments with it? I do recognize you can pass an id and get one comment back, but it's still in an array even then. Bit awkward, but
</blockquote></details>

The singular vs plural nature of our DP naming convention suggested to me that the DP data type should be `Comment`, not `Comments`. That means the auto-generated code will call `getComment` on the DP. I could rename it to `GetComments` here, but then this would be (I think) the only case where the DP function name doesn't match the C# function name.

Perhaps you're saying the data type itself should be `Comments`, not `Comment`. If that's the case, I thought we settled on using singular nouns here. Is that not the case? I'm happy to change it, but I thought I was sticking to the convention.
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 230 at r1](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7p_2Ej1D0rihKw6kvA:-O833Arr5JRJoMIeLnWr:b-xy2wqs) ([raw file](https://github.com/paranext/paranext-core/blob/15b391f09202a27f9cb572cf4e0563dba9039877/c-sharp/Projects/ParatextProjectDataProvider.cs#L230)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It looks to me like `CommentSelector`'s `BookId` has a default value in C# but is marked as required in TypeScript. This code seems to indicate that `BookId` is required since it always filters comments by book. Should the default value be removed from C#? Or maybe set to empty string and checked here to make sure it is present or something? Or I could definitely be reading something wrong
</blockquote></details>

Yeah, I probably should remove the default value or change it to empty/null.
___
*[`extensions/src/legacy-comment-manager/src/types/legacy-comment-manager.d.ts` line 80 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O82Q-L85FloGL0l_Bc0:-O833TrX77Tpx_-xKYdU:b-53pimq) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/legacy-comment-manager/src/types/legacy-comment-manager.d.ts#L80)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Generally we do lowerCamelCase on both sides for these id strings - I'd think that's the way to go here as well unless there's a particular reason for it to be upper.
</blockquote></details>

Sure, I can change it. No good reason.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 429 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-qjWx662icKTAawlQ:-O834JXI2BwbHDIqlE5O:b-7tzte) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L429)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is indeed difficult to read. I think it might be difficult because of the lack of clear rules regarding how the parameters passed in are used and how they interact with the component's state and the conditional side effects. The usj passed in is sometimes set to the usj in the component but not always, and it depends on the legacy comments under the hood. The comments passed in are new format comments, but it is difficult to understand what exactly their relationship to the function is.

It seems like maybe there are three things going on in this function:
1. Make sure anchors are in the usj for all legacy comments
2. Overwrite the legacy comments with the new editor-format comments
3. IF the new comments are different than the legacy comments, set the usj if this function changed it irrespective of if this usj passed in is different than the usj in this component's state

I would suggest renaming the function, considering splitting `updateCommentsInUsj` up a bit, and maybe making the interactions between parameters and state more consistent. Or possibly even consider making it a stateless function where you pass in everything you need and pulling the function out of the component.
</blockquote></details>

It would be easier to simply the function if `onUsjChanged` had a separate callback for `onCommentsChanged`. As it is, it is possible that USJ + comments changed, only USJ changed, only comments changed, or nothing changed. And even if the USJ didn't change (technically),it might be a copy of the USJ without anchors, so I need to insert them.

Step 2) listed above is very much not finalized as we aren't overwriting anything for the moment. It's more of "push all comments  back to the data provider whether they are new comments or old comments." The DP's job (in C#) is to figure out which comments are new and which ones are old.

I'm not saying this is perfect, but TBH I found the existing card hard to follow/read. I'm sure some of that is just React for me, but it's unclear to me when each of the different functions runs. So I build what seemed best for the state of things.

Having said all this, I can take another stab at refactoring. But it would be good to have a sense of whether the base this code is running on is intended to change or stay the same (e.g., one callback with USJ + comments or two).
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 495 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O82jX1s107lxkZ_v1Oc:-O836P_E1JG6_Gc5zE09:bkvg5w9) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L495)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I don't remember 100% if this works, but you may be able to do something like the following here to reduce repetition:

```tsx
const EditorComponent = isReadOnly ? Editorial : Marginal;

return (
  <>
    ...stuff
    <EditorComponent
      propshere
    />
  </>
);
```
</blockquote></details>

This is basically what was there before my changes. It didn't work, so I added the repetition to make it work. It did not like what we were doing for `onUsjChanged`, IIRC.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 479 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-VFcD24ztG1HaigB_:-O836pBa1z8dGq2PDdOC:b-qoiduz) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L479)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe `.toString()` here is redundant. Sorry for the javascript confusion. Hope you like 16 ways to do anything.

Unfortunately my understanding is that `[object` mess is because of `toString()` on an object. You need to `JSON.stringify` objects to get them to look nice. The only situation in which that is not the case (to my understanding) is when you literally print an object like `console.log(objHere)` because `console` has special integrations that allow it to do fancy things.

Numbers, strings, and arrays have better `toString()` functions. However, if  [...]

2024-09-30 18:49 UTC, tjcouch-sil reviewed
> Reviewed 2 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 27 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`lib/platform-bible-utils/src/usj-document.ts` line 479 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-VFcD24ztG1HaigB_:-O83Dp0b0ikbDsfB3xXe:bi4qd49) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L479)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It probably is redundant, but I'm back again to I don't want to memorize when I need to use `toString` or `JSON.stringify` and when I don't. I'm pretty sure I've run into cases other than `console` where a function does magic things so you don't need to convert a parameter to a string.
</blockquote></details>

Redundancy isn't really my concern, and this particular context isn't my concern either as what you have done here works fine. I'm just highlighting that I believe this is not the solution you are looking for; I made that demo to illustrate this point. If you always use `.toString()`, you will run into `.toString()` giving you `[object Object]` again before long. To avoid weird printouts that I don't want, here's what I pretty much always do:

- Objects and arrays in most cases*: `JSON.stringify`

- Hopefully everything else: just use it (this also has the benefit of working for `undefined`, too, which you can't run `.toString()` on)

Basically I just use value types, and I `JSON.stringify` reference types. ish.*

\* JavaScript be JavaScript, so I gotta have a disclaimer in case there are some crazy cases I don't have in mind

![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/9V1s1oIJBCL4U2206OOnM1TC/image.png)

![JavascriptProgrammingGIF.gif](https://files.reviewableusercontent.io/images/reviewable/104016682/2dFhM-KfBxF5NNPLH3gruTk4/JavascriptProgrammingGIF.gif)


<!-- Sent from Reviewable.io -->

2024-09-30 19:33 UTC, tjcouch-sil requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 29 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`lib/platform-bible-utils/src/usj-document.ts` line 217 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O83Oh_u5L_SnrY4WMee:-O83Oh_u5L_SnrY4WMef:b6cxzen) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L217)):*
> ```XML
>    *         A        <- Consider "A" to be `node`
>    *     / / | \ \
>    *     B C D E F    <- Consider these to be MarketObjects inside the `content` array own by "A"
> ```

typo Marke**t**Object (and on following line)

Also should "own" be "owned"? No big deal; just checking
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 231 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O83Ppy-7xyHp_9_lh_J:-O83Ppy-7xyHp_9_lh_K:bouddc8) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L231)):*
> ```XML
>     parent: MarkerObject | Usj,
>     skipTypes: string[] = [],
>   ): { node: MarkerObject; parent: MarkerObject | Usj } {
> ```

I see this one-off return type and wonder if maybe it could be combined with the new `StackItem` Ira mentioned (or whatever you call it) so you would have node, parent, and index. If that seems useful. Just a thought!


<!-- Sent from Reviewable.io -->

2024-09-30 19:33 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 28 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`lib/platform-bible-utils/src/usj-document.ts` line 231 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O83Ppy-7xyHp_9_lh_J:-O83Q84N0Q_8OUvnTYjI:b-r8hzvh) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L231)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I see this one-off return type and wonder if maybe it could be combined with the new `StackItem` Ira mentioned (or whatever you call it) so you would have node, parent, and index. If that seems useful. Just a thought!
</blockquote></details>

Oops, sorry; this was meant to be an "info" comment, not a blocking one


<!-- Sent from Reviewable.io -->

2024-09-30 21:07 UTC, tjcouch-sil reviewed
> Reviewed 3 of 24 files at r1, 5 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 29 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`lib/platform-bible-utils/src/usj-document.ts` line 397 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O83RyL59_Qm9DhHg-bA:-O83RyL59_Qm9DhHg-bB:b-zea9iz) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L397)):*
> ```XML
>   }
> 
>   nodeToVerseRefAndOffset(
> ```

The naming of `parent` and `child` here don't seem very self-explanatory or clear here. I'm guessing child is essentially the "focus" of the method like `node` in other methods. Can this be simplified such that you don't have to pass `parent` in? Should `child` be renamed `node` to match other parameter names?
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 449 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-SxXlCbXK6PTGkQYp:-O83UPD4ElJgBr7LZ7ZO:b-j88cr1) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L449)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Well, that's what I was thinking at first, too, but we aren't actually handing over a complete `Usj` object when we pass chapters around (which is what is done now). Perhaps I should change the constructor to take `Usj` or `MarkerObject` to be more correct. But to do that we probably also need to change the webview since it says we are passing around `Usj` objects when they aren't full `Usj` objects. Regardless, a chapter of USJ content will not include the book ID unless it is chapter 1.
</blockquote></details>

Does USJ require a certain scope? I don't know any definition of a "full" USJ document. Whole chapter? Whole book? Just a verse? Just one marker? Now that I think about it, I don't know that I have noticed any requirements for how much stuff is in a US* "document" in general...

The USFM docs syntax tree seems to indicate USFM must have book marking while USX doesn't necessarily have to have book marking. https://docs.usfm.bible/usfm/3.1/doc/index.html I wonder what the deal is here regarding full interoperability of these standards. Maybe the information I found from these syntax trees is just kinda there because they did something and this question has been overlooked? I dunno.


<!-- Sent from Reviewable.io -->

2024-09-30 23:09 UTC, irahopkinson requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 23 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`extensions/src/legacy-comment-manager/src/main.ts` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zR1sS-XYXKjA_JyL0:-O845U7ZEtLTLoSnTWri:bhkzeix) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/legacy-comment-manager/src/main.ts#L5)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I was considering leaving this in on purpose. If someone needs to work on the data provider it would be nice to have a way to quickly test that, and it's easier to use a code block like this than to figure out how to write it again. Having said that, it's not critical to leave it in.
</blockquote></details>

Okey dokey
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 0 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O848s5B87wQV6CfDAej:-O848s5C5_gc5epo7XLF:bj0hupp) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L0)):*
I would suggest we rename this file and class to use something other than "document" as that will get confusing when we move to Yjs documents (which mean something specific) and might be created from this class. Maybe `usj-data.ts` and `class UsjData`? Other options: data, state, info, record.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 71 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zmfCeAVZPwl9tgImW:-O846T6p0vznln6kXlRF:btn5jp1) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L71)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

As I understand the API, it should not be possible for `unwrappedResults` to be `undefined` if `wrappedResults` was not `undefined` or an array of length 0.
</blockquote></details>

Gotcha
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 265 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-INW7DtQFFWJ79LdC:-O846Ypu-4j5JVM8TzjA:b-u37g9l) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L265)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Gotta love javascript
</blockquote></details>

Leave it as is then. I just need to make that clear in my own head.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 269 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-J7GD7JzVOyReXxT3:-O846pph4icG5LNMTrIx:buh7bcr) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L269)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This one I did on purpose so that the comment line would be at the same level as the comment line for the `if` block. I find it easier to understand comments meant to occur at the same "level" of the code if they are indented exactly the same.  When comments occur inside of a block, I assume it is some smaller concern within the block, not about the block as a whole. That is, the comment here makes more sense when comparing to the `Look at the node's children` comment for the `if` block. If I put it inside of the `else` block, the natural assumption (at least to me ) is that the comment applies to the next line or two within the code block, and it doesn't make as much sense when trying to make sense of that comment with `nextNode = undefined`.
</blockquote></details>

Gotcha, what about just removing the blank line then so its still connected with the `if`?
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 662 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-ZZu525gpcSNfX-sh:-O848Gao3jC3Ny_2R7Fk:b-r7t56j) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L662)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

In `Usj`, members of `content` arrays are of type `MarkerContent`. `MarkerContent` is `string | MarkerObject`. So equality comparisons will work different if the content you're comparing are strings instead of objects. Strings are treated as value types for equality comparisons. If content arrays only had objects, then `===` checking would be sufficient since it compares references.

I could ONLY perform the `jsonPath` equality check and not the `node` equality check, but that will be slower since I have to constantly transform the working stack. So I want to do the fast equality check first and follow that up with the definitive `jsonPath` check to be certain.
</blockquote></details>

Oh gotcha, you are expecting nodes to be text/strings here (not objects).
___
*[`lib/platform-bible-utils/src/usj-document.test.ts` line 851 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zeAt3DHfAhdsH5NmA:-O84AlzJEj1Jl78Zljk4:b32w1t) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.test.ts#L851)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I thought about breaking all these out to separate tests, but it seemed rather pedantic. More on that below.
</blockquote></details>

Ok
___
*[`lib/platform-bible-utils/src/usj-document.test.ts` line 869 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zf8S_8asxAby8xnzn:-O84AsQOC35STWp5umv-:bfwf456) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.test.ts#L869)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

When I was a tester years ago, I settled on "chunky tests" making more sense than "slim tests" in general. I know it's a style thing, so others might write tests with a different style.

In these tests specifically things are grouped by purpose. If something earlier fails in a test, I don't really care if the later things pass or fail. The general functionality covered by the test is broken. Having a longer set of which things passed or failed related to that functionality can actually slow me down as I have to parse out more of what is happening for things that pass vs fail. I'd rather have 10 tests, each of which do 10 things within the same domain defined by the test, than 100 small things. Also, "chunky" tests allow you to work through scenarios from one step to the next without having to recreate state which "slim tests" would do.
</blockquote></details>

I'm good with that.
___
*[`lib/platform-bible-react/src/components/mui/contextMenu.component.open.render.test.tsx_disabled` line  at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zhnFtAPPr-Gp5LRyH:-O84AxsP2INsM6excXDn:baefm0q) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-react/src/components/mui/contextMenu.component.open.render.test.tsx_disabled#L)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

The only 2 tests I disabled were MUI tests. I worked for a couple of hours unsuccessfully trying to get them to run. Since we're moving away from MUI anyway, I decided to disable them and move forward. If we need to re-enable them I could use some help. Jest is upset because the JSX runtime is provided from outside the mock calls, and I don't see any way to pull it in solely from within the mock calls. Various AIs also suggest [...]

2024-10-01 14:46 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: 23 of 35 files reviewed, 23 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`lib/platform-bible-react/src/components/mui/contextMenu.component.open.render.test.tsx_disabled` line  at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zhnFtAPPr-Gp5LRyH:-O87Xhrb6GbsMRwgTg94:b-wga9tq) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-react/src/components/mui/contextMenu.component.open.render.test.tsx_disabled#L)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I didn't realize these where MUI. I'm happy to just remove them both.
</blockquote></details>

After making the jest config changes we talked about yesterday, I didn't need to disable any tests. So this change has been reverted.


<!-- Sent from Reviewable.io -->

2024-10-01 14:51 UTC, tjcouch-sil requested changes
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 21 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 212 at r1](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7pZ-Qs1Ay2cRI-GWJi:-O87PldE-4bW-lw5Fv0q:b-s6z788) ([raw file](https://github.com/paranext/paranext-core/blob/15b391f09202a27f9cb572cf4e0563dba9039877/c-sharp/Projects/ParatextProjectDataProvider.cs#L212)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

The singular vs plural nature of our DP naming convention suggested to me that the DP data type should be `Comment`, not `Comments`. That means the auto-generated code will call `getComment` on the DP. I could rename it to `GetComments` here, but then this would be (I think) the only case where the DP function name doesn't match the C# function name.

Perhaps you're saying the data type itself should be `Comments`, not `Comment`. If that's the case, I thought we settled on using singular nouns here. Is that not the case? I'm happy to change it, but I thought I was sticking to the convention.
</blockquote></details>

Oh yeah, sorry; I was suggesting changing the data type name to `Comments` and all related spots. I don't remember settling on singular nouns or any motivations to do so; do you remember any context to that conversation to help jog my memory? A quick survey of various data providers shows many that are plural - `AvailableChecks`, `ActiveRanges`, `CheckResults`, `LocalizedStrings`, `Names` (on example hello world PDP, not a real one)


<!-- Sent from Reviewable.io -->

2024-10-01 16:51 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: 24 of 35 files reviewed, 10 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 233 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zO9_a41ZjcKZa1fAz:-O87a5Oj3jCkXR9giFXd:ba3dfob) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/c-sharp/Projects/ParatextProjectDataProvider.cs#L233)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ah, it's leftover debug code. I should remove it.
</blockquote></details>

Removed
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 262 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zQ9kCADsLEg8Cwc9U:-O87aFbL5xhpvFqvrChG:ba3dfob) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/c-sharp/Projects/ParatextProjectDataProvider.cs#L262)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Leftover debugging - I can remove it
</blockquote></details>

Removed
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zpdtd8EgKrXdOKy7S:-O87dpFt-riMC4Nnheav:b-okrenz) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L1)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I don't love this rule, but I have been following it normally. I strongly dislike it for this class in particular and decided to disable it. Class methods really ought to be organized by purpose (i.e., functions that perform similar functions should be close together). It doesn't really matter if they are static vs instance methods, public vs private, etc. If all functions related to the same concept have to be spread out in multiple places in a class it can meaningfully hurt maintainability/understandability of a class. I can add a comment about it here.
</blockquote></details>

Added a comment to explain the reason for disabling the rule
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7ziP9_EGqwE--e_0Lg:-O87e5YD3NvTsUrKuWfA:bam79sr) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We discussed this a while ago with one of my PRs. We settled on that you could use `Object.freeze` on the array and keep it upper snake case.
</blockquote></details>

Added a call to `Object.freeze`.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 28 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-G8Wu3kf2AWFW9fwu:-O87f3X82h-ky8TCGc6t:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L28)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I can change it.
</blockquote></details>

Done
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 123 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zqs2y6kxPUBaP73rb:-O87hTwPBOk9baRw7G66:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L123)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I can look at changing this.
</blockquote></details>

Done
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 217 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O83Oh_u5L_SnrY4WMee:-O87hfY_8jKhRGZIKT37:b-hnrxha) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L217)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

typo Marke**t**Object (and on following line)

Also should "own" be "owned"? No big deal; just checking
</blockquote></details>

Good eye! Fixed
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 231 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O83Ppy-7xyHp_9_lh_J:-O87i4Di0pmTLlfYwL-q:b-4catdv) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L231)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oops, sorry; this was meant to be an "info" comment, not a blocking one
</blockquote></details>

Thanks for the suggestion and clarification. I'd like to leave that type as-is because 1) as a general practice, I like to keep often created types as small as possible to help the hardware to optimize/cache things, and 2) I don't want to confuse the purpose of the type or how it gets used. I think the confusion could come because if you have the child, why do you need the index at all? But then I need the index to turn working stacks into parent maps. But then if I have the index, why do I need the child? And in some contexts (like this one) if I don't need the index, why is it there?
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 265 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-INW7DtQFFWJ79LdC:-O87kTVC8-o_GGEo5iIe:b-cdnoi9) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L265)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Leave it as is then. I just need to make that clear in my own head.
</blockquote></details>

I was going to change it back to how I had it originally since we both had the same inclination, but I forgot this triggers two eslint errors. One is about destructuring, and the other is about `content` possibly being undefined (which isn't possible based on the `if` block). So I left it as-is and added a comment to help future readers (including us!) who might look at this and become confused.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 269 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-J7GD7JzVOyReXxT3:-O87l28j0FDMO6Yfhez4:btw0mch) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L269)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Gotcha, what about just removing the blank line then so its still connected with the `if`?
</blockquote></details>

That's a fair point. Blank line removed.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 397 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O83RyL59_Qm9DhHg-bA:-O87mzoDBpihHKiPKhM-:bn3kx6a) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L397)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The naming of `parent` and `child` here don't seem very self-explanatory or clear here. I'm guessing child is essentially the "focus" of the method like `node` in other methods. Can this be simplified such that you don't have to pass `parent` in? Should `child` be renamed `node` to match other parameter names?
</blockquote></details>

Yes, the naming here should be changed to what you suggest. I think this was one of the first functions I wrote, and I missed this aspect of clean up. Good catch.

Removing `parent` altogether is not possible. The problem is that `child` (n [...]

2024-10-01 18:48 UTC, lyonsil reviewed
I think all changes have been made now that we discussed except for everything in the webview. I'm waiting to touch that until Ira's updates are in and we talk some more.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175#-:-O88PBS82ptLN3Kab1Sv:b-et869t)* status: 20 of 35 files reviewed, 10 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 212 at r1](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7pZ-Qs1Ay2cRI-GWJi:-O88G4cR53eHVR4nQnm0:bn71vpr) ([raw file](https://github.com/paranext/paranext-core/blob/15b391f09202a27f9cb572cf4e0563dba9039877/c-sharp/Projects/ParatextProjectDataProvider.cs#L212)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oh yeah, sorry; I was suggesting changing the data type name to `Comments` and all related spots. I don't remember settling on singular nouns or any motivations to do so; do you remember any context to that conversation to help jog my memory? A quick survey of various data providers shows many that are plural - `AvailableChecks`, `ActiveRanges`, `CheckResults`, `LocalizedStrings`, `Names` (on example hello world PDP, not a real one)
</blockquote></details>

Ok - I remember thinking "oh I have to make this singular to follow the convention" but I don't remember what made me think that. Maybe it was the naming convention of the other C# project interfaces:

```c#
/// <summary>
/// Standardized set of methods exposed by a Project Data Provider for a project
/// </summary>
public static class ProjectInterfaces
{
    /// <summary>
    /// The name of the `projectInterface` representing the essential methods every Base Project Data
    /// Provider must implement
    /// </summary>
    public const string BASE = "platform.base";
    public const string USFM_BOOK = "platformScripture.USFM_Book";
    public const string USFM_CHAPTER = "platformScripture.USFM_Chapter";
    public const string USFM_VERSE = "platformScripture.USFM_Verse";
    public const string USX_BOOK = "platformScripture.USX_Book";
    public const string USX_CHAPTER = "platformScripture.USX_Chapter";
    public const string USX_VERSE = "platformScripture.USX_Verse";
    public const string PLAIN_TEXT_VERSE = "platformScripture.PlainText_Verse";
}
```

That's probably why I capitalized `Comment" originally, too. :laughing: 

Anyway, I agree plural is better here, so I'm making the change.  I updated the interface to `legacyCommentManager.comments` now, too. :smile: 
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 397 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O83RyL59_Qm9DhHg-bA:-O88JwT3EiAZvYCxby4y:bg42xss) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L397)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Yes, the naming here should be changed to what you suggest. I think this was one of the first functions I wrote, and I missed this aspect of clean up. Good catch.

Removing `parent` altogether is not possible. The problem is that `child` (now `node`) is of type `MarkerContent`. `MarkerContent` can be a string or an object. If it's a string, then it won't be in the parent map because strings are treated as value types, not reference types. If I include strings in the parent map, then any time there are duplicate strings in the USJ only the last one would be kept. The parent map requires working with references to objects within `this.usj`. A string can never be a parent, so I know once I get a parent object, I can do everything else I need using a parent map. That's why the core functions I expose from `jsonpath-plus` include getting the parent of a JSONPath query. A generic query could return a string, a number, a boolean, OR an object of some sort. If a JSONPath query returns a value type and it's not one of the specific `ContentJsonPath` queries, I have no idea how to find the parent unless you give it to me or give me a JSONPath query to run.

Note that there is another function that requires a JSONPath query instead of `node` and `nodeParent`. That function converts the query to `node` and `nodeParent`.
</blockquote></details>

After thinking more about this, I can allow `nodeParent` to be undefined and **try** to lookup the parent on behalf of the caller. It won't always work depending on the input, and it will never work if `node` is a string. But there could be situations where someone has a real node from inside the USJ that they want to pass in without trying to find the parent themselves.


<!-- Sent from Reviewable.io -->

2024-10-01 23:18 UTC, irahopkinson reviewed
> Reviewed 12 of 12 files at r3, 3 of 11 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 7 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`jest.config.ts` line 25 at r5](https://reviewable.io/reviews/paranext/paranext-core/1175#-O89ML633HUY0vaNjnFc:-O89ML633HUY0vaNjnFd:boo9a7w) ([raw file](https://github.com/paranext/paranext-core/blob/02fe28c8d898c4ffa7897c7ba0756eb320e2b3d5/jest.config.ts#L25)):*
> ```XML
>     '^platform-bible-react$': '<rootDir>/node_modules/platform-bible-react/dist/index.js',
>     '^platform-bible-utils$': '<rootDir>/node_modules/platform-bible-utils/dist/index.js',
>     '^jsonpath-plus$': '<rootDir>/node_modules/jsonpath-plus/dist/index-browser-umd.cjs',
> ```

BTW I would expect this to point to the ESM file (like the ones above) rather than the CJS file but if it's working then I guess this is fine?
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 28 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-G8Wu3kf2AWFW9fwu:-O89GPmA0l8MaNO-qDWd:bitjlbg) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L28)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Actually I was meaning delete the `WorkingStack` type and replace all usages of `WorkingStack` with `StackItem[]` to make it clear within context that the type is an array.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 123 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zqs2y6kxPUBaP73rb:-O89JRhn3kwPaAf81R7b:b-fs6ulb) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L123)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I think my suggestion with only one return is simpler but this is fine too.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line  at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O848s5B87wQV6CfDAej:-O89FkOm7bXCq20flZ-c:b-83sjoh) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Renamed to `UsjReaderWriter`. I have a particular dislike for using `data` in names because it is too generic. This seemed somewhat akin to `XmlReaderWriter` classes/utilities I've used in the past, so that seemed like a good alternative.
</blockquote></details>

Nice!
___
*[`lib/platform-bible-utils/src/usj-document.test.ts` line 15 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zbmEV10Ka29UpXWWB:-O89KvIxAKykcxkNMNcP:bakmwhn) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.test.ts#L15)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I ran this USJ through a JSON prettifier which I believe alphabetized properties. When data is really long I guess I find alphabetized things to be better than grouped things because I know if I missed something.
</blockquote></details>

Alphabetized is better but this doesn't look to be to me.
___
*[`lib/platform-bible-utils/src/usj-reader-writer.ts` line 60 at r5](https://reviewable.io/reviews/paranext/paranext-core/1175#-O89H6Hf5QDaxFYZpx-H:-O89H6Hf5QDaxFYZpx-I:b-xakieu) ([raw file](https://github.com/paranext/paranext-core/blob/02fe28c8d898c4ffa7897c7ba0756eb320e2b3d5/lib/platform-bible-utils/src/usj-reader-writer.ts#L60)):*
> ```XML
>   constructor(usj: Usj) {
>     this.usj = usj;
>   }
> ```

FYI you can actually remove the `usj` field declaration above and simplify this to:
```ts
constructor(private readonly usj: Usj) {}
```
This declares and assigns the field in the constructor. I happen to like the simpler syntax but you can ignore this since what you have is equivalent and more explicit.



_Code quote:_
```XML
  constructor(usj: Usj) {
    this.usj = usj;
  }
```


<!-- Sent from Reviewable.io -->

2024-10-04 20:22 UTC, tjcouch-sil submitted a review, later dismissed
Thanks for all the updates :)

> Reviewed 3 of 11 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175#-:-O8OBgSf3TSg0rPqjx2x:bw19864)* status: all files reviewed, 6 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 212 at r1](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7pZ-Qs1Ay2cRI-GWJi:-O8O8eW_CxoxluSfq6ss:b-wfcvib) ([raw file](https://github.com/paranext/paranext-core/blob/15b391f09202a27f9cb572cf4e0563dba9039877/c-sharp/Projects/ParatextProjectDataProvider.cs#L212)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ok - I remember thinking "oh I have to make this singular to follow the convention" but I don't remember what made me think that. Maybe it was the naming convention of the other C# project interfaces:

```c#
/// <summary>
/// Standardized set of methods exposed by a Project Data Provider for a project
/// </summary>
public static class ProjectInterfaces
{
    /// <summary>
    /// The name of the `projectInterface` representing the essential methods every Base Project Data
    /// Provider must implement
    /// </summary>
    public const string BASE = "platform.base";
    public const string USFM_BOOK = "platformScripture.USFM_Book";
    public const string USFM_CHAPTER = "platformScripture.USFM_Chapter";
    public const string USFM_VERSE = "platformScripture.USFM_Verse";
    public const string USX_BOOK = "platformScripture.USX_Book";
    public const string USX_CHAPTER = "platformScripture.USX_Chapter";
    public const string USX_VERSE = "platformScripture.USX_Verse";
    public const string PLAIN_TEXT_VERSE = "platformScripture.PlainText_Verse";
}
```

That's probably why I capitalized `Comment" originally, too. :laughing: 

Anyway, I agree plural is better here, so I'm making the change.  I updated the interface to `legacyCommentManager.comments` now, too. :smile:
</blockquote></details>

Gotcha. Makes sense that it would be tricky :) not a ton of examples yet either
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 397 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O83RyL59_Qm9DhHg-bA:-O8O7IDbBX_vFfXhM_Il:b-76fi9p) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L397)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

After thinking more about this, I can allow `nodeParent` to be undefined and **try** to lookup the parent on behalf of the caller. It won't always work depending on the input, and it will never work if `node` is a string. But there could be situations where someone has a real node from inside the USJ that they want to pass in without trying to find the parent themselves.
</blockquote></details>

Ah interesting! Thanks for the insight!


<!-- Sent from Reviewable.io -->

2024-10-08 21:15 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: 19 of 36 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`jest.config.ts` line 25 at r5](https://reviewable.io/reviews/paranext/paranext-core/1175#-O89ML633HUY0vaNjnFc:-O8bngrP4ZbYarSvg5-9:b-xonr34) ([raw file](https://github.com/paranext/paranext-core/blob/02fe28c8d898c4ffa7897c7ba0756eb320e2b3d5/jest.config.ts#L25)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I would expect this to point to the ESM file (like the ones above) rather than the CJS file but if it's working then I guess this is fine?
</blockquote></details>

I tried the ESM initially, and tests fail to run with the error:
```
    Details:

    /home/lyonsm/paranext-core/node_modules/jsonpath-plus/dist/index-browser-esm.js:2550
    export { JSONPath, SafeScript };
    ^^^^^^

    SyntaxError: Unexpected token 'export'
```
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 53 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-a56MAh7mSmxPtYWH:-O8hyS42B311C1-NnpRQ:bwysei6) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L53)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm happy to reorganize and split into more files. I think it would be good to talk this through with someone before I just start moving things. I am doubtful about reuse, but for sure reorganizing could be nice.
</blockquote></details>

Reorganization complete
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 398 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-oS9w4TaRg7JvMMr8:-O8hy_H83jJqJm1uvX-F:bb7yxbf) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L398)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Probably need to cancel or flush the debounce here, which I believe is not currently supported in our `debounce`. You could attach it to the returned function like this https://stackoverflow.com/a/41853194 same way [`lodash` does their debounce](https://lodash.com/docs/4.17.15#debounce).
</blockquote></details>

This function has been reworked given Ira's updates to the editor control and our previous discussion.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 406 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-mhGuASe4Kbkm2Sra:-O8hyqgQ9ZfSyhDxsmxU:b-nupqxn) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L406)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If you want me to remove it let me know.
</blockquote></details>

This was removed with a rebase.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 429 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-qjWx662icKTAawlQ:-O8hyxRC05JQWUxpWIq0:busyo3e) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L429)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It would be easier to simply the function if `onUsjChanged` had a separate callback for `onCommentsChanged`. As it is, it is possible that USJ + comments changed, only USJ changed, only comments changed, or nothing changed. And even if the USJ didn't change (technically),it might be a copy of the USJ without anchors, so I need to insert them.

Step 2) listed above is very much not finalized as we aren't overwriting anything for the moment. It's more of "push all comments  back to the data provider whether they are new comments or old comments." The DP's job (in C#) is to figure out which comments are new and which ones are old.

I'm not saying this is perfect, but TBH I found the existing card hard to follow/read. I'm sure some of that is just React for me, but it's unclear to me when each of the different functions runs. So I build what seemed best for the state of things.

Having said all this, I can take another stab at refactoring. But it would be good to have a sense of whether the base this code is running on is intended to change or stay the same (e.g., one callback with USJ + comments or two).
</blockquote></details>

This has been reworked.
___
*[`lib/platform-bible-utils/src/usj-document.ts` line 28 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8-G8Wu3kf2AWFW9fwu:-O8boSCf3uqu06WfpZgW:b-js1ep3) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.ts#L28)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Actually I was meaning delete the `WorkingStack` type and replace all usages of `WorkingStack` with `StackItem[]` to make it clear within context that the type is an array.
</blockquote></details>

I use the term `WorkingStack` in enough places in the code I think I'd like to leave it as-is.
___
*[`lib/platform-bible-utils/src/usj-document.test.ts` line 15 at r2](https://reviewable.io/reviews/paranext/paranext-core/1175#-O7zbmEV10Ka29UpXWWB:-O8bpUuvCv8bJaEv1Lpx:b5oou1z) ([raw file](https://github.com/paranext/paranext-core/blob/d7698782103fe2e148a20c92f83aa98a9f05410c/lib/platform-bible-utils/src/usj-document.test.ts#L15)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Alphabetized is better but this doesn't look to be to me.
</blockquote></details>

You're right. I thought it was alphabetized, but clearly it isn't. Now it is.
___
*[`lib/platform-bible-utils/src/usj-reader-writer.ts` line 60 at r5](https://reviewable.io/reviews/paranext/paranext-core/1175#-O89H6Hf5QDaxFYZpx-H:-O8boeCO6ZpPlpJDJoGb:b-r9cd35) ([raw file](https://github.com/paranext/paranext-core/blob/02fe28c8d898c4ffa7897c7ba0756eb320e2b3d5/lib/platform-bible-utils/src/usj-reader-writer.ts#L60)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

FYI you can actually remove the `usj` field declaration above and simplify this to:
```ts
constructor(private readonly usj: Usj) {}
```
This declares and assigns the field in the constructor. I happen to like the simpler syntax but you can ignore this since what you have is equivalent and more explicit.
</blockquote></details>

Yes, I like the more explicit syntax.


<!-- Sent from Reviewable.io -->

2024-10-09 05:12 UTC, irahopkinson requested changes
> Reviewed 17 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 141 at r6](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8jcKou7b7CBFP65ulc:-O8jcKou7b7CBFP65uld:b6sog00) ([raw file](https://github.com/paranext/paranext-core/blob/79f49c2024d8bc22b2eb73a813a45383cbe682a8/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L141)):*
> ```XML
> 
>   const updateComments = useCallback(
>     (newComments: Comments | undefined, usjWithAnchors: Usj | undefined = usj) => {
> ```

When this function is attached to `onCommentChange`, since its only argument is `comments`, therefore here `usjWithAnchors` will always be `usj` but that will be the previous `usj` since `onCommentChange` fires before USJ is updated. That doesn't seem like the right thing to default it to here.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 162 at r6](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8jdXV4EA6Vi4kkbSfe:-O8jdXV4EA6Vi4kkbSff:bcf0i7i) ([raw file](https://github.com/paranext/paranext-core/blob/79f49c2024d8bc22b2eb73a813a45383cbe682a8/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L162)):*
> ```XML
> 
>       // Nothing to do
>       if (legacyCommentsToAdd.length === 0) return;
> ```

What if a comment is not new but has been modified, e.g. has a new reply? I don't this code would save it.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 197 at r6](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8jee0x-_rBrzjC5L_Y:-O8jee0x-_rBrzjC5L_Z:bfek467) ([raw file](https://github.com/paranext/paranext-core/blob/79f49c2024d8bc22b2eb73a813a45383cbe682a8/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L197)):*
> ```XML
>   // Update the editor if a change comes in
>   useEffect(() => {
>     // We don't know if the USJ or comments will change first, but the USJ has to be correct before
> ```

I don't think you are using this `useEffect` for its purpose. This is meant to only be fire if USJ changes (such as the user picked another chapter) and then this fires to update the USJ which will cause the editor component to reload. We don't want the editor to reload on other changes as it takes too long and will reset the cursor location.
___
*[`lib/platform-bible-utils/src/usj-reader-writer.ts` line 505 at r6](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8jZK3G5GnCwaEg7VDR:-O8jZK3G5GnCwaEg7VDS:b-7fgnln) ([raw file](https://github.com/paranext/paranext-core/blob/79f49c2024d8bc22b2eb73a813a45383cbe682a8/lib/platform-bible-utils/src/usj-reader-writer.ts#L505)):*
> ```XML
>     let foundAnotherChapter = false;
>     let jsonPath: ContentJsonPath = '';
>     const expectedVerse = verseRef.verse;
> ```

BTW `verseRef.verse` will not always be same as `verseRef.verseNum.toString()`, e.g. if `verseRef` is a range, sequence and/or segment then that is what will be in `verseRef.verse`. I'm guessing that is probably what you want here though.


<!-- Sent from Reviewable.io -->

2024-10-15 17:15 UTC, tjcouch-sil requested changes
We're so close!! Thanks for the perseverance on this. Sorry for the delays.

> Reviewed 13 of 17 files at r6, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175#-:-O9GAQQU7zbgFVE8CBzR:b-nvf4zt)* status: all files reviewed, 7 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 141 at r6](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8jcKou7b7CBFP65ulc:-O9G4eGC0yOax31hzVww:bsjq9g0) ([raw file](https://github.com/paranext/paranext-core/blob/79f49c2024d8bc22b2eb73a813a45383cbe682a8/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L141)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

As I understand things now, comments can update in 3 situations:
1) The PDP detects a change and sends an event over the network.
2) The editor detects a change and fires `onUsjChange`.
3) The editor detects a change and fires `onCommentChange`.

Situation 1 is handled by the `useEffect` call discussed in this PR further down. I don't need to save anything back to the comment PDP in situation 1 since the updates originated in the PDP.

Situations 2 and 3 require updating comments back in the PDP since the updates are originating in the editor. `updateComments` is here to save data back to the PDP. The PDP requires comments to have verse references, and I can only get those verse references if I have USJ to look them up.

From what I've seen, if a new comment thread starts, then `onUsjChange` runs first (i.e., situation 2). This is important because if `onComments` runs first, then I have no way to find a verse reference for that comment. Because `onUsjChange` does run first, though, then I will get the new USJ passed here. The default argument is not used.

I think your concern is situation 3 (i.e., `onCommentChange` runs without any updates to USJ first). The only times I've seen this happen are:
A) When a new comment/reply is added to an existing thread, and
B) When I rewrite all of the comments back to the editor from the PDP data stream

In both A) and B), taking the "old" USJ is fine because it actually isn't old. The comment anchors are already in place. I didn't need any new comment anchors.
</blockquote></details>

Maybe Ira is suggesting this order would cause a problem:

1. User adds a new comment thread, triggering `onUsjChange`. `editorUsj.current` gets set to the new usj and `debouncedSetUsj` gets run with the new usj
2. User adds a new comment on that same thread, triggering `onCommentChange`. `editorUsj.current` is up-to-date, but `usj` is not yet since `debouncedSetUsj` hasn't happened, which also hasn't caused the latest usj to go back to the backend and get updated and come back to the frontend to reassign the variable `usj`
3. `debouncedSetUsj` finishes, which then sends the new usj to the backend and back to the frontend to the variable `usj`.

So maybe there is a debouncing problem where `usjWithAnchors` and therefore `usjRW` could be outdated and not have the newest comment thread anchor in it. So then `convertEditorCommentsToLegacyComments` wouldn't find a spot for the new comment thread.

Seems hard to do but possible. Maybe instead of `usj`, the default for `usjWithAnchors` needs to be `editorUsj.current`.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 143 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9FywyO61uu1aDJAx4q:-O9FywyO61uu1aDJAx4r:b-be62wj) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L143)):*
> ```XML
>     (newComments: Comments | undefined, usjWithAnchors: Usj | undefined = usj) => {
>       // Cannot convert between legacy and current comments without access to corresponding USJ
>       if (!usjWithAnchors) return;
> ```

In some of these cases, is there a potential for data loss? Might we at least want to log warnings or something in some cases? So if something like this does happen, we can investigate with more information available to us
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 187 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9G3XRh1XviqjYO9msQ:-O9G3XRh1XviqjYO9msR:b-73s7qy) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L187)):*
> ```XML
>   const onUsjChange = useCallback(
>     (newUsj: Usj, newComments: Comments | undefined) => {
>       insertCommentAnchors(newUsj);
> ```

Do we need this line? `newUsj` should be the editor's usj which has the current `legacyComments` anchors in it already, right? And `insertCommentAnchors` only adds current `legacyComments` anchors, not the new comment anchor (which should also be already in the `newUsj` because the editor added it), right?

Or is this just here as a security to make sure the comments get put in even if new comments come in while we're adding a comment?
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 208 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9G8_dR3Dd9QmfHdmmS:-O9G8_dR3Dd9QmfHdmmT:b-3zl8pa) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L208)):*
> ```XML
>       editorRef.current &&
>       (!deepEqualAcrossIframes(usj, editorUsj.current) ||
>         !deepEqualAcrossIframes(legacyComments, editorLegacyComments.current))
> ```

This line is intended to mean essentially "if the legacy comments according to the PDP are not the same as the legacy comments represented in the editor right now" (then update the editor's current represented legacy comments), right? If this is the case, I believe you need to set `editorLegacyComments.current` to whatever comes in as `newComments` transformed to be legacy comments in `updateComments` (whether or not it should short circuit and not do the rest of the stuff in that function). Right now, the only place that `editorLegacyComments.current` is updated is right here, so this will always be true if there are comment changes because the PDP will always tell us there are new comments when comments are added even by this editor.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 210 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9G9Y37-Hv0xNBMtrU3:-O9G9Y37-Hv0xNBMtrU4:bjp2oah) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L210)):*
> ```XML
>         !deepEqualAcrossIframes(legacyComments, editorLegacyComments.current))
>     ) {
>       insertCommentAnchors(usj);
> ```

I think `insertCommentAnchors(usj)` needs to happen before doing the `deepEqualAcrossIframes` because `editorUsj.current` will always have the anchors already inserted, right? So I guess they would never be equal since the usj coming from the PDP never has the anchors and `editorUsj.current` always has them.


<!-- Sent from Reviewable.io -->

2024-10-15 17:58 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 7 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 141 at r6](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8jcKou7b7CBFP65ulc:-O9GCRDK7T_--MDB7oa9:b-1bwe8v) ([raw file](https://github.com/paranext/paranext-core/blob/79f49c2024d8bc22b2eb73a813a45383cbe682a8/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L141)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Maybe Ira is suggesting this order would cause a problem:

1. User adds a new comment thread, triggering `onUsjChange`. `editorUsj.current` gets set to the new usj and `debouncedSetUsj` gets run with the new usj
2. User adds a new comment on that same thread, triggering `onCommentChange`. `editorUsj.current` is up-to-date, but `usj` is not yet since `debouncedSetUsj` hasn't happened, which also hasn't caused the latest usj to go back to the backend and get updated and come back to the frontend to reassign the variable `usj`
3. `debouncedSetUsj` finishes, which then sends the new usj to the backend and back to the frontend to the variable `usj`.

So maybe there is a debouncing problem where `usjWithAnchors` and therefore `usjRW` could be outdated and not have the newest comment thread anchor in it. So then `convertEditorCommentsToLegacyComments` wouldn't find a spot for the new comment thread.

Seems hard to do but possible. Maybe instead of `usj`, the default for `usjWithAnchors` needs to be `editorUsj.current`.
</blockquote></details>

How can a comment be added to the same thread in less than 300 milliseconds? I can change the default, but I feel like I'm missing something with this concern. Also I guess I've been assuming that we're removing the debounce in the not too distant future, so I haven't been trying to consider it closely here.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 143 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9FywyO61uu1aDJAx4q:-O9GCxWY4rRrMHL24KSx:b-mv8u3d) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L143)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

In some of these cases, is there a potential for data loss? Might we at least want to log warnings or something in some cases? So if something like this does happen, we can investigate with more information available to us
</blockquote></details>

I can add logging, but if somehow we're passing around comments and no USJ is available, I have to believe something bigger is going on that a log message here isn't going to uniquely identify.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 187 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9G3XRh1XviqjYO9msQ:-O9GE6d3C2WReH2Kj5cp:bz323f5) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L187)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do we need this line? `newUsj` should be the editor's usj which has the current `legacyComments` anchors in it already, right? And `insertCommentAnchors` only adds current `legacyComments` anchors, not the new comment anchor (which should also be already in the `newUsj` because the editor added it), right?

Or is this just here as a security to make sure the comments get put in even if new comments come in while we're adding a comment?
</blockquote></details>

When the editor creates a new comment, it creates a particular ID for that comment that doesn't align with comment IDs in Paratext. So the IDs in the comments (and anchors) get rewritten. Essentially the comment data flow on a change is:
- Editor triggers save to PDP with IDs of some sort (editor created for new comments or PT created for previously loaded ones).
- PDP saves the data (including PT writing its own IDs)
- C# triggers a "Comments changed" event
- PDP loads the data with the new PT-determined IDs because it sees that the comments differ
- We insert comment anchors with the PT-determined IDs

In this particular case we're probably able to skip this line since the reloading hasn't happened yet. However, it is just easier/safer to ensure the proper anchors are in place than to think through every way a comment or USJ might change and trigger re-rendering, including the order in which everything is going to run. It's far easier to ensure the anchors are in place here than to remove this and then figure out in which crazy situation not all the anchors I thought were in place are actually in place.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 208 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9G8_dR3Dd9QmfHdmmS:-O9GHGWyA31G0NW5fe73:b1ue8xu) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L208)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This line is intended to mean essentially "if the legacy comments according to the PDP are not the same as the legacy comments represented in the editor right now" (then update the editor's current represented legacy comments), right? If this is the case, I believe you need to set `editorLegacyComments.current` to whatever comes in as `newComments` transformed to be legacy comments in `updateComments` (whether or not it should short circuit and not do the rest of the stuff in that function). Right now, the only place that `editorLegacyComments.current` is updated is right here, so this will always be true if there are comment changes because the PDP will always tell us there are new comments when comments are added even by this editor.
</blockquote></details>

Because the PDP is changing comment IDs (not my choice, forced by the PT comment code - see my earlier discussion on this), I purposefully wait to save everything until it's here. What the editor thinks are its current comments after a new comment is inserted can never match PT since PT will come up with its own comment IDs.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 210 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9G9Y37-Hv0xNBMtrU3:-O9GJGt3BpFCel31WZWE:b-oa8t7b) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L210)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think `insertCommentAnchors(usj)` needs to happen before doing the `deepEqualAcrossIframes` because `editorUsj.current` will always have the anchors already inserted, right? So I guess they would never be equal since the usj coming from the PDP never has the anchors and `editorUsj.current` always has them.
</blockquote></details>

Yes, I can move the anchor insertion earlier.


<!-- Sent from Reviewable.io -->

2024-10-15 18:23 UTC, tjcouch-sil requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 141 at r6](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8jcKou7b7CBFP65ulc:-O9GPKYN9PUdwQtZ-2f7:bxogw5o) ([raw file](https://github.com/paranext/paranext-core/blob/79f49c2024d8bc22b2eb73a813a45383cbe682a8/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L141)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

How can a comment be added to the same thread in less than 300 milliseconds? I can change the default, but I feel like I'm missing something with this concern. Also I guess I've been assuming that we're removing the debounce in the not too distant future, so I haven't been trying to consider it closely here.
</blockquote></details>

I would suggest changing the default simply for accuracy's sake and for the theoretical possibility that something could go wrong, not for a particularly real concern. But Ira can pick up with his thoughts since it's his blocking comment.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 143 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9FywyO61uu1aDJAx4q:-O9GPcIg2CLnJawJbXpH:b9vd67j) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L143)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I can add logging, but if somehow we're passing around comments and no USJ is available, I have to believe something bigger is going on that a log message here isn't going to uniquely identify.
</blockquote></details>

Agreed that there is probably something not good happening, but I would just like to see a warning when it smells like blood. The third guard clause seems like it would probably be more helpful to have a warning as that has a bit more precise a meaning.

(Changed from blocking to open - I don't think I meant to make this blocking)
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 187 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9G3XRh1XviqjYO9msQ:-O9GMa5Q9pFT0nJ6B7sn:br1hoju) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L187)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

When the editor creates a new comment, it creates a particular ID for that comment that doesn't align with comment IDs in Paratext. So the IDs in the comments (and anchors) get rewritten. Essentially the comment data flow on a change is:
- Editor triggers save to PDP with IDs of some sort (editor created for new comments or PT created for previously loaded ones).
- PDP saves the data (including PT writing its own IDs)
- C# triggers a "Comments changed" event
- PDP loads the data with the new PT-determined IDs because it sees that the comments differ
- We insert comment anchors with the PT-determined IDs

In this particular case we're probably able to skip this line since the reloading hasn't happened yet. However, it is just easier/safer to ensure the proper anchors are in place than to think through every way a comment or USJ might change and trigger re-rendering, including the order in which everything is going to run. It's far easier to ensure the anchors are in place here than to remove this and then figure out in which crazy situation not all the anchors I thought were in place are actually in place.
</blockquote></details>

Oh interesting. I either forgot or didn't realize the editor IDs are being overwritten. Thanks!
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 208 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9G8_dR3Dd9QmfHdmmS:-O9GMwXc8fdLCSO4TNgq:bz1ruoq) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L208)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Because the PDP is changing comment IDs (not my choice, forced by the PT comment code - see my earlier discussion on this), I purposefully wait to save everything until it's here. What the editor thinks are its current comments after a new comment is inserted can never match PT since PT will come up with its own comment IDs.
</blockquote></details>

Would new comments on an existing thread cause an id to change? I could be wrong. If that is so, then new comments on an existing thread could reasonably pass deep equal check here, right? Whereas how it is currently written, I don't think it will ever pass on any update to the comments.

Admittedly, I don't quite understand the incentive not to keep `editorLegacyComments` up to date with what comments are represented in the editor (maybe because it takes time to transform? In that case, could you just save the current editor comments in new form and transform them to legacy comments when needed? I think they're only needed here anyway). But I'd suggest either keeping them up to date for the benefit I mentioned in the previous paragraph or changing the name of this variable to something like `legacyCommentsPrev` or something because it does not seem to me that it represents the editor's current state of comments as it is currently coded. It would probably be misleading if we looked at this variable name later because `editorUsj` does represent the editor's current state of USJ, so there would be a mismatch between the names and the meanings.


<!-- Sent from Reviewable.io -->

2024-10-15 19:31 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: 34 of 36 files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 141 at r6](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8jcKou7b7CBFP65ulc:-O9GeUE2CFt8IQEZqs8f:b-bu91xm) ([raw file](https://github.com/paranext/paranext-core/blob/79f49c2024d8bc22b2eb73a813a45383cbe682a8/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L141)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I would suggest changing the default simply for accuracy's sake and for the theoretical possibility that something could go wrong, not for a particularly real concern. But Ira can pick up with his thoughts since it's his blocking comment.
</blockquote></details>

Updated
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 143 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9FywyO61uu1aDJAx4q:-O9GcarS64ypMNWp4Jd5:b802a7t) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L143)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Agreed that there is probably something not good happening, but I would just like to see a warning when it smells like blood. The third guard clause seems like it would probably be more helpful to have a warning as that has a bit more precise a meaning.

(Changed from blocking to open - I don't think I meant to make this blocking)
</blockquote></details>

Comments added


<!-- Sent from Reviewable.io -->

2024-10-15 21:09 UTC, irahopkinson submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175#-:-O9H-nExCszjTJs4v0gx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 197 at r6](https://reviewable.io/reviews/paranext/paranext-core/1175#-O8jee0x-_rBrzjC5L_Y:-O9H-fpc6FdrK3KjIU-M:btn5jp1) ([raw file](https://github.com/paranext/paranext-core/blob/79f49c2024d8bc22b2eb73a813a45383cbe682a8/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L197)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

As I understand it, `useEffect` will run once at first and then whenever anything in the dependency array changes. I added `legacyComments` to the dependency array, so I modified the purpose of this `useEffect`. If I create another `useEffect` for comments, it must include `usj`, too, as I have to modify incoming `usj` changes to insert comment anchors. I can't set the comments on the editor control until I know for certain that all the anchors have been added. So leaving `legacyComments` out of this `useEffect` seems pointless since I'm basically going to do the same thing in the other one if I create it.

If I don't have any `useEffect` call watching for changes to`legacyComments`, then I will not reliably load comments initially from the PDP. I don't know if the comments or USJ will load first, and if the comments load first I can't process them because the editor will complain about missing anchors. So from the PDPs they have to be considered together.

Note that `useEffect` fires even now in `main` whenever I'm typing and the USJ changes. The `deepEqualsAcrossIframes` call prevents the editor from actually setting the USJ unless it has changed from the PDP, though. I'm doing the same thing with comments here.
</blockquote></details>

Gotcha


<!-- Sent from Reviewable.io -->

2024-10-15 21:51 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: 29 of 36 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 208 at r8](https://reviewable.io/reviews/paranext/paranext-core/1175#-O9G8_dR3Dd9QmfHdmmS:-O9GcmvF89XAv7YtgMSl:b-urdy69) ([raw file](https://github.com/paranext/paranext-core/blob/7cf299d0faee346db625ed9df943845a5932aecb/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L208)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Would new comments on an existing thread cause an id to change? I could be wrong. If that is so, then new comments on an existing thread could reasonably pass deep equal check here, right? Whereas how it is currently written, I don't think it will ever pass on any update to the comments.

Admittedly, I don't quite understand the incentive not to keep `editorLegacyComments` up to date with what comments are represented in the editor (maybe because it takes time to transform? In that case, could you just save the current editor comments in new form and transform them to legacy comments when needed? I think they're only needed here anyway). But I'd suggest either keeping them up to date for the benefit I mentioned in the previous paragraph or changing the name of this variable to something like `legacyCommentsPrev` or something because it does not seem to me that it represents the editor's current state of comments as it is currently coded. It would probably be misleading if we looked at this variable name later because `editorUsj` does represent the editor's current state of USJ, so there would be a mismatch between the names and the meanings.
</blockquote></details>

Changed the name of the variable


<!-- Sent from Reviewable.io -->

2024-10-16 00:11 UTC, irahopkinson submitted a review, later dismissed
> Reviewed 7 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2024-10-16 18:01 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks! phew. hard work

> Reviewed 1 of 2 files at r9, 6 of 7 files at r11, 1 of 2 files at r12, 1 of 1 files at r13, 8 of 8 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1175#-:-O9LUT_G3L8d0AeT8p3k:bxyiqxf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-16 18:03 UTC, merged