Add markers check inventory
paranext/paranext-core pull request #1210
Opened 2024-10-11 19:25 UTC by rolfheij-sil

I still need to add a bunch of comments on stuff that is exposed to the outside from PBR, but the code should be ready like this.

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-core/1210)

2024-10-25 01:15 UTC, irahopkinson requested changes
Thanks for all your good work on this.

> Reviewed 6 of 25 files at r1, 2 of 17 files at r2, 3 of 15 files at r3, 4 of 15 files at r5, 14 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1210#-:-OA0DmFE0PlGiTgZV-dV:b-xnqb1c)* status: all files reviewed, 20 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/main.ts` line 153 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-M2nH4kagU8liNMzI:-OA-M2nH4kagU8liNMzJ:b-s87syu) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/main.ts#L153)):*
> ```XML
>     repeatedWordsInventoryWebViewType,
>   );
>   const markersInventoryWebViewProvider = new InventoryWebViewProvider(
> ```

BTW this is likely out of scope for this PR but when I open an inventory I can see what ScrRef it's for but I can't see which project it is for. Could that be added to the window title (or somewhere else)?
___
*[`extensions/src/platform-scripture/src/checks/inventories/character-inventory.component.tsx` line 34 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-OAq7C-RxGYmmof1f:-OA-OAq7C-RxGYmmof1g:b-zb5wbu) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/character-inventory.component.tsx#L34)):*
> ```XML
>  * @param approvedItems Array of approved items, typically as defined in `Settings.xml`
>  * @param onApprovedItemsChange Callback function that stores the updated list of approved items
>  * @param unapprovedItems UnapprovedItems Array of unapproved items, typically as defined in
> ```

This word at the beginning of the description seems redundant and can be remove.



_Code quote:_
```XML
UnapprovedItems
```
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 36 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-PFbQ8b-1CtqZN7QQ:-OA-PFbQ8b-1CtqZN7QR:b69q37o) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L36)):*
> ```XML
> ];
> 
> const defaultScrRef: ScriptureReference = {
> ```

We use this `const` as defined here in at least 5 places. How about we make this DRYer and move it to `platform-bible-utils` (or somewhere else)?



_Code quote:_
```XML
defaultScrRef
```
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 48 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-sWadBxipfy-xDjvG:-OA-sWadBxipfy-xDjvH:bm2uxo1) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L48)):*
> ```XML
>   unapprovedItems: string[],
> ): InventoryTableData[] => {
>   if (!text || text === '') return [];
> ```

BTW the second half of this conditional is covered by the first so you can remove it.



_Code quote:_
```XML
text === ''
```
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 81 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-twf44iNyAohFEUO5:-OA-twf44iNyAohFEUO6:b8lzybh) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L81)):*
> ```XML
>     }
> 
>     let match: RegExpExecArray | null = markerRegex.exec(line);
> ```

You could add `?? undefined` to the end of this line (and change its type) so the following line wouldn't need the `eslint-disable`. I also wonder if this regex and even its use could be nicely wrapped in a utils file somewhere. We will likely need to use this again.
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 84 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-v2waESi2UEQdyDju:-OA-v2wb9VdoVzrDTB4N:b9ph4yr) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L84)):*
> ```XML
>     // RegExp.exec returns null when no match is found
>     // eslint-disable-next-line no-null/no-null
>     while (match !== null) {
> ```

This would read more cleanly as `while (match) {`. Is there a case where you specifically need to check for not null?
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 87 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-vZwG75OxDVR2Kdez:-OA-vZwG75OxDVR2Kdf-:b-fqdm1l) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L87)):*
> ```XML
>       // For this code to work correctly we need our regular expression to match a single marker
>       // on each per match
>       if (match.length > 1) throw new Error('Multiple markers found in a single match');
> ```

BTW a following blank line would show this code discontinuity better especially with this single line `if`.
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 140 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-xtlSEZDgcmfcdgNs:-OA-xtlTCXRpmwNk4gAf:b1vewtx) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L140)):*
> ```XML
>  * @param approvedItems Array of approved items, typically as defined in `Settings.xml`
>  * @param onApprovedItemsChange Callback function that stores the updated list of approved items
>  * @param unapprovedItems UnapprovedItems Array of unapproved items, typically as defined in
> ```

The first word of the description seems redundant. Remove it.



_Code quote:_
```XML
UnapprovedItems
```
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 163 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-yLQa-_f-SI514Uao:-OA-yLQa-_f-SI514Uap:b-qkicze) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L163)):*
> ```XML
>     cell: ({ row }) => {
>       const marker: string = row.getValue('item');
>       return getDescription(markerNames, marker) || 'Unknown marker';
> ```

Does this need to be localized?



_Code quote:_
```XML
'Unknown marker'
```
___
*[`extensions/src/platform-scripture/src/checks/inventories/repeated-words-inventory.component.tsx` line 22 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA0-1qH5lY0nslFOdXn:-OA0-1qH5lY0nslFOdXo:b9c5yk9) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/repeated-words-inventory.component.tsx#L22)):*
> ```XML
> // Matches a sequence of letters surrounded by word boundaries followed by that exact same
> // sequence of letters surrounded by word boundaries
> const repeatedWordsRegex: RegExp = /\b(\p{L}+)\b(?=\s\b\1\b)/gu;
> ```

FYI thanks for the regex description.
___
*[`extensions/src/platform-scripture/src/checks/inventories/repeated-words-inventory.component.tsx` line 32 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA0-TIi9s3XbaFiw6V_:-OA0-TIi9s3XbaFiw6Va:b1vewtx) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scri [...]

2024-10-25 18:31 UTC, rolfheij-sil reviewed
Thanks for reviewing, Ira!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1210#-:-OA3Ebwb5Pvaa3WBxBj9:b94sy72)* status: all files reviewed, 15 unresolved discussions (waiting on @irahopkinson)

___
*[`extensions/src/platform-scripture/src/main.ts` line 153 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-M2nH4kagU8liNMzI:-OA31TgC0xe_1ZLDFfjY:b3ymnxg) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/main.ts#L153)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW this is likely out of scope for this PR but when I open an inventory I can see what ScrRef it's for but I can't see which project it is for. Could that be added to the window title (or somewhere else)?
</blockquote></details>

Good idea. I added it in `src\platform-scripture\src\inventory.web-view-provider.ts`
___
*[`extensions/src/platform-scripture/src/checks/inventories/character-inventory.component.tsx` line 34 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-OAq7C-RxGYmmof1f:-OA31emy8fcgM5H2V6mR:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/character-inventory.component.tsx#L34)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This word at the beginning of the description seems redundant and can be remove.
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 36 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-PFbQ8b-1CtqZN7QQ:-OA37vMr71cs-1Bfm0_f:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L36)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

We use this `const` as defined here in at least 5 places. How about we make this DRYer and move it to `platform-bible-utils` (or somewhere else)?
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 81 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-twf44iNyAohFEUO5:-OA38RkX-4khU3P_Pc9Z:bqnnyz6) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L81)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

You could add `?? undefined` to the end of this line (and change its type) so the following line wouldn't need the `eslint-disable`. I also wonder if this regex and even its use could be nicely wrapped in a utils file somewhere. We will likely need to use this again.
</blockquote></details>

Done. I can see us moving the regeular expressions to a central location at some point, but since I don't have a clear idea of what that location should be I will leave them here for now.
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 84 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-v2waESi2UEQdyDju:-OA38djBB-L0A-1oXEe7:b-hrsykf) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L84)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This would read more cleanly as `while (match) {`. Is there a case where you specifically need to check for not null?
</blockquote></details>

I thought checking it like that made the most sense, since regex.exec return `RegExpExecArray | null`. But with the `?? undefined` I can change it to `while (match)`
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 87 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-vZwG75OxDVR2Kdez:-OA38xbV7YajN9yVButP:b-qu6n94) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L87)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW a following blank line would show this code discontinuity better especially with this single line `if`.
</blockquote></details>

Good point. Done.
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 140 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-xtlSEZDgcmfcdgNs:-OA390ZC3J5vcZABgpZn:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L140)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

The first word of the description seems redundant. Remove it.
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 163 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA-yLQa-_f-SI514Uao:-OA39aAw4b_8Xmpn_euC:byvyago) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L163)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Does this need to be localized?
</blockquote></details>

Yes. Done.
___
*[`extensions/src/platform-scripture/src/checks/inventories/repeated-words-inventory.component.tsx` line 22 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA0-1qH5lY0nslFOdXn:-OA39fst1kViNa4P3Ja5:b-9nhkj3) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/repeated-words-inventory.component.tsx#L22)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

FYI thanks for the regex description.
</blockquote></details>

![thank-you.gif](https://files.reviewableusercontent.io/images/reviewable/108285668/Oeq5TWHwOE3T-L-bQWsAstRm/thank-you.gif)
___
*[`extensions/src/platform-scripture/src/checks/inventories/repeated-words-inventory.component.tsx` line 32 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA0-TIi9s3XbaFiw6V_:-OA39yDPA2bhunOXafMm:b-3qle4m) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/extensions/src/platform-scripture/src/checks/inventories/repeated-words-inventory.component.tsx#L32)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

The first word of the description seems redundant. Remove it.
</blockquote></details>

Done. Is it clear that I've been copy/pasting this? :joy: 
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts` line 25 at r6](https://reviewable.io/reviews/paranext/paranext-core/1210#-OA034hj2bDqq5ND_ygH:-OA3A6id8iz4VmQZsoJq:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/53a1d4cf4725157a274522e61fafaf8360db8200/lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts#L25)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

grammar: "...should *be* stored..."
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts` line 99 at [...]

2024-10-29 23:39 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 27 of 27 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1210#-:-OAPdRsfC7qGOYK7-erC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-29 23:39 UTC, merged

2024-10-31 18:10 UTC, tjcouch-sil reviewed
I decided to come do a quick look over the data provider-related stuff. There's something that might need some adjustment. Thanks for the hard work on all this!!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1210#-:-OAYlFhP-0fTtd-JrlgH:b8r05sj)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx` line 205 at r7](https://reviewable.io/reviews/paranext/paranext-core/1210#-OAYkwXS2Kjay45IQpBp:-OAYkwXS2Kjay45IQpBq:bfackem) ([raw file](https://github.com/paranext/paranext-core/blob/f64f5d317002cb50add94d8d249efd92f34fe293/extensions/src/platform-scripture/src/checks/inventories/marker-inventory.component.tsx#L205)):*
> ```XML
>       if (!projectId) return;
>       const PDP = await papi.projectDataProviders.get('platformScripture.MarkerNames', projectId);
>       const newMarkerNames = await PDP.getMarkerNames(scrRef.bookNum);
> ```

Ah yes, I imagine this may be what I was talking about with the difficulties using `useProjectData`. You may be able to replace this with `useProjectData` if you update the marker data types.
___
*[`extensions/src/platform-scripture/src/types/platform-scripture.d.ts` line 97 at r7](https://reviewable.io/reviews/paranext/paranext-core/1210#-OAYkICYALasLXRsgRz8:-OAYkICZ-0jwzcSH41Tg:b-5kfj9k) ([raw file](https://github.com/paranext/paranext-core/blob/f64f5d317002cb50add94d8d249efd92f34fe293/extensions/src/platform-scripture/src/types/platform-scripture.d.ts#L97)):*
> ```XML
>   export type MarkerNamesProjectInterfaceDataTypes = {
>     /** Gets an array of string that contain information about markers */
>     MarkerNames: DataProviderDataType<string[], string, string>;
> ```

This data type does not match the methods in `IMarkerNamesProjectDataProvider`. This probably would cause trouble using `useProjectData` but might not show up if you're directly using the methods like `pdp.getMarkerNames` or something. Please update


<!-- Sent from Reviewable.io -->