Create Data Provider API
paranext/paranext-core pull request #122
Opened 2023-04-01 01:53 UTC by tjcouch-sil

- Created `DataProviderService` that exposes on the papi a way to manage data of a particular type.
- Run `papi.dataProvider.registerEngine('<data_type>', <your_data_provider_engine>)` to register an engine object which can get, set, and force updates
- The data provider that is created on the papi from the data provider engine can get, set, and subscribe to changes
- Data providers have selectors that inform the data provider of the selection of data the method call pertains to
- Created `useData` hook to nicely wrap using a data provider in a `useState`-like api
- Created `useEventAsync` hook to use events with asynchronous subscribing and unsubscribing
- Created test greetings provider and "quick verse" (gets verse text from a free online api) provider as well as some renderer code and a new web view to test them
- Various little fixes

2023-04-03 03:39 UTC, irahopkinson requested changes
Thanks for all your work on this!

For some reason I can't try this out because I can't see the extensions. Perhaps we could pair to figure this out?

There is a bit of promise/then here. I know we only just talked about prefering async/await last week. Would it be a good idea to hit that in an immediate follow-up PR?

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122#-:-NS2tD79DqlmQ9P9SiVQ:b-lq910v)* status: all files reviewed, 25 unresolved discussions (waiting on @tjcouch-sil)

___
*[`package.json` line 87 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS2fvJJ1ZjTUv8NIf68:-NS2fvJJ1ZjTUv8NIf69:b-ape9nn) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/package.json#L87)):*
> ```JSON
>     "electron-updater": "^5.3.0",
>     "electron-window-state": "^5.0.3",
>     "fast-deep-equal": "^3.1.3",
> ```

FYI: this was already a dependency of other `devDependencies`. We now make it production.
___
*[`extensions/hello-someone/hello-someone.js` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS2ic0e59dRkjkN5A6o:-NS2ic0e59dRkjkN5A6p:bpxa4ms) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L12)):*
> ```JavaScript
> const unsubscribers = [];
> 
> class GreetingsDataProviderEngine {
> ```

I know this is only test code but strictly speaking this doesn't need to be a class (it has no constructor or any other class specific stuff) and all the extra that comes with that in JS. This can simply be declared as an object. Hmm... maybe it does need to be a class since you are using `this.people` inside an arrow function.
___
*[`extensions/hello-someone/hello-someone.js` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS2wFIZ1XyQKAHK1O9Q:-NS2wFIZ1XyQKAHK1O9R:b9jtjm2) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L26)):*
> ```JavaScript
>     if (selector === '*') return false;
> 
>     if (data !== this.people[selector.toLowerCase()]) {
> ```

Use nominal flow here to help with reability. You dealt with the first exception above which is good. Then check the next `if (data === this.people[selector.toLowerCase()]) return false;`

Then the remaining nominal code will not be indented:
```
this.people[selector.toLowerCase()] = data;
return true;
```
___
*[`extensions/hello-someone/hello-someone.js` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3wOe968vSZIQcI5jV:-NS3wOe968vSZIQcI5jW:b-xxy40h) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L37)):*
> ```JavaScript
>    * @param {string} selector
>    */
>   get = async (selector) => {
> ```

`IDataProviderEngine` indicates this should not be an arrow function. Does this not apply here or is this testing that limitation?
___
*[`extensions/hello-someone/hello-someone.js` line 46 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS2orzZDBn63m_yz4JB:-NS2orzZDBn63m_yz4JC:b-f0u8lv) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L46)):*
> ```JavaScript
>   testRandomMethod = async (things) => {
>     const result = `Greetings data provider got testRandomMethod! ${things}`;
>     logger.log(result);
> ```

Use `logger.info` to make the level obvious. Replace all `logger.log(` with `logger.info(` in **all** files. But do that _after_ merging in `main`.
___
*[`extensions/hello-someone/hello-someone.js` line 61 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS359AT3-7cp24bpxTH:-NS359AT3-7cp24bpxTI:bzew1uf) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L61)):*
> ```JavaScript
>   papi.webViews.addWebView({
>     contentType: 'html',
>     contents: `<html>
> ```

Consider importing this from an HTML file.
___
*[`extensions/hello-someone/hello-someone.js` line 112 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS34Gmk1lF4O8XVPJ_v:-NS34Gmk1lF4O8XVPJ_w:bwt2t4) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L112)):*
> ```JavaScript
>               const name = greetingsInput.value;
>               const setGreetingsInput = document.getElementById('set-greetings-input');
>               greetingsDataProvider.set(name.toLowerCase(), setGreetingsInput.value).then((success) => {
> ```

style: change to something like `isSuccessful`



_Code quote:_
```JavaScript
success
```
___
*[`extensions/quick-verse/quick-verse.js` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3GqXA19qkV--ResYP:-NS3GqXA19qkV--ResYQ:bx6s4o4) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/quick-verse/quick-verse.js#L16)):*
> ```JavaScript
>    * Verses stored by the Data Provider.
>    * Keys are Scripture References.
>    * Values are { text: '<verse_text>', changed?: boolean }
> ```

style: `isChanged`
___
*[`extensions/quick-verse/quick-verse.js` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3IDEeAc4E74HgQDWE:-NS3IDEeAc4E74HgQDWF:b-imbjjq) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/quick-verse/quick-verse.js#L57)):*
> ```JavaScript
> 
>     // Only heretics change Scripture, so you have to tell us you're a heretic
>     if (!data.heresy) return false;
> ```

style: `isHeresy`, also in JSDoc above.
___
*[`extensions/quick-verse/quick-verse.js` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3JHAgBC2G59-TRrod:-NS3JHAgBC2G59-TRroe:bp3bf20) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/quick-verse/quick-verse.js#L59)):*
> ```JavaScript
>     if (!data.heresy) return false;
> 
>     if (
> ```

Again, change this to nominal flow.
___
*[`extensions/quick-verse/quick-verse.js` line 94 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3Ldnz6rki0vc_dCsg:-NS3Ldnz6rki0vc_dCsh:b-vqxsjs) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/quick-verse/quick-verse.js#L94)):*
> ```JavaScript
>         );
>         const verseData = await verseResponse.json();
>         const text = verseData.text.replace(/\n/g, '');
> ```

Can use `replaceAll` function these days rather than a regex.



_Code quote:_
```JavaScript
replace(/\n/g, '')
```
___
*[`src/renderer/hooks/papi-hooks/useData.ts` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3TrACAbDiZloJP99M:-NS3TrACAbDiZloJP99N:b-64ajx9) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/renderer/hooks/papi-hooks/useData.ts#L20)):*
> ```XML
>  * @param subscriberOptions various options to adjust how the subscriber emits updates
>  *
>  *    WARNING: MUST BE WRAPPED IN A useState, useMemo, etc. The reference must not be updated every render
> ```

I don't understand what this warning is included for on the return? The existing example usage doesn't do any wrapping that I can see.
___
*[`src/renderer/hooks/papi-hooks/useData.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3Wk9z-I_mNPUT-i7t:-NS3Wk9z-I_mNPUT-i7u:b-w1wc60) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/renderer/hooks/papi-hooks/useData.ts#L42)):*
> ```XML
> 
>   // Get the data provider info for this data type
>   // Note: do nothing if w [...]

2023-04-03 17:38 UTC, JohnThomson reviewed
I only got through the bits before useData but you may as well see what I thought so far.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122#-:-NS7BT-b0iz0PFOxRIBk:by7j6wp)* status: all files reviewed, 27 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/hello-someone/hello-someone.js` line 38 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS6yE3cBACnWbSfl1Z6:-NS6yE3cBACnWbSfl1Z7:b-t2kvw3) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L38)):*
> ```JavaScript
>    */
>   get = async (selector) => {
>     if (selector === '*') return this.people;
> ```

I suppose it is guaranteed that this object will be serialized and deserialized before the client sees it, so we're not giving the client a way to trash our internal data by handing over the object?
___
*[`extensions/hello-someone/hello-someone.js` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS6zAj8DoWUbywVLHgK:-NS6zAj8DoWUbywVLHgL:blykfsm) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L59)):*
> ```JavaScript
>   );
> 
>   papi.webViews.addWebView({
> ```

It strikes me as bizarre that a data-provider is inserting a web view that appears to be a UI...perhaps it is just intended as a demonstration of the data it can provide? Is this something a real data-provider would do? If not at least comment.
If it's intended as a demo I think it would be a better demo to show that a separate UI component could interact with the data provider.
___
*[`extensions/hello-someone/hello-someone.js` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7-RVO9yt1L0-gOqpO:-NS7-RVO9yt1L0-gOqpP:b4bh5gm) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L90)):*
> ```JavaScript
>             greetingsButton.addEventListener("click", () => {
>               const greetingsInput = document.getElementById('greetings-input');
>               greetingsDataProvider.get(greetingsInput.value.toLowerCase()).then((message) => {
> ```

Let's be consistent about using either 'then' or 'await' syntax.
___
*[`extensions/hello-someone/hello-someone.js` line 124 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7-vM402B92EeoqQbV:-NS7-vM402B92EeoqQbW:b-jrj9wd) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L124)):*
> ```JavaScript
>               allGreetings.innerHTML = greetingsString;
>               print(greetingsString);
>             });
> ```

Something to think about here: There could be thousands of people in the system, yet typically only one changes at a time. Serializing the whole list feels wasteful. (Imagine serializing all of Scripture any time some client wants to know when it changes.) I think there should be some way to request notification when any greeting changes, but get a message that just has the data about the one person whose greeting changed.
I'm not sure this is achievable without abandoning the idea that 'set' just returns true if something changed rather than explicitly raising an event.
Another aspect of this problem: the current API assumes that keys are simple, except for the '*' special case. But suppose it gets just a little more complicated. Say the greetings module gets extended to store relationships as well. You can now set({"bill", friend}, "joe") which establishes that joe and bill are friends. You can get({"bill", friend}) which returns a list of people bill is friends with. We'll suppose that friendships are bidirectional, so one result of that call is that get({"joe", friend}) will now include bill.
But what if something has done a subscribe({"joe", friend})? How does the backing store know that subscriber should be notified when set({"bill", friend}, "joe") returns true?
My thinking is that as soon as the data relationships inside a provider get at all complicated, you really need to allow the set code to figure out what events need raising. I suppose there could still be a special case where the only needed notifications are to clients who subscribed to that exact key or "*" but I'm not sure the simplification is worth the cost of having two mechanisms.
___
*[`extensions/hello-someone/hello-someone.js` line 183 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS76eIM-tQ38ZFNPIJ1:-NS76eIM-tQ38ZFNPIJ2:bxvzswj) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L183)):*
> ```JavaScript
>       unsubPromises
>         .map((unsubPromise) => unsubPromise.unsubscriber)
>         .concat([greetingsDataProviderInfo.dispose]),
> ```

This suggests that the greetingsDataProviderInfo will be gotten rid of altogether. But might there not be other subscribers? I'm thinking we want a pair of terms different from get/dispose for "give me a connection to X"/"done using X"
Also, what happens if a subscriber neglects to do this? Or if something closes its window and it never gets a chance to?
___
*[`extensions/quick-verse/quick-verse.js` line 122 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7AuRH4DojBUVppFNV:-NS7AuRH4DojBUVppFNW:b-u7bp6k) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/quick-verse/quick-verse.js#L122)):*
> ```JavaScript
> 
>   return Promise.all(
>     unsubPromises.map((unsubPromise) => unsubPromise.promise),
> ```

I don't really understand what you're doing here, but I don't see how it can be useful to run map on an array you just forced to be empty.


<!-- Sent from Reviewable.io -->

2023-04-03 19:53 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 32 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/renderer/hooks/papi-hooks/useData.ts` line 56 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7H4W0D1_3LejJnAm5:-NS7H4W0D1_3LejJnAm6:baxyjxg) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/renderer/hooks/papi-hooks/useData.ts#L56)):*
> ```XML
>   // Make const variables of the data provider so TypeScript knows they won't change
>   const dataProvider = dataProviderTemp;
>   const isDisposed = isDisposedTemp;
> ```

I think you can just do const [dataProvider, isDisposed] = dataType.
___
*[`src/shared/services/DataProviderService.ts` line 106 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7YkKR1JupdrnLuuHR:-NS7YkKR1JupdrnLuuHS:bnc86my) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/services/DataProviderService.ts#L106)):*
> ```XML
>     const unsubscribe = onDidUpdate(callbackWithUpdate);
> 
>     if (getDataImmediately) {
> ```

If getDataImmediately is false, looks like dataPrevious will not be initialized until the first callbackWithUpdate. I'm surprised the compiler doesn't have a fit about that. But is it actually a problem? If it's actually possible to get a callback when the data hasn't (deeply) changed, could a random initial value make it seem that something has changed when it hasn't? Or that it hasn't when it really has? Probably more likely if, say, TGetValue can legitimately be undefined or a number.
___
*[`src/shared/services/DataProviderService.ts` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7Yc6i8vWfKpsa3HZz:-NS7Yc6n5k5HVGh1Yrzt:bimte2r) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/services/DataProviderService.ts#L108)):*
> ```XML
>     if (getDataImmediately) {
>       // Get the data to run the callback immediately so it has the data
>       const data = await dataProviderContainer.networkObject.get(selector);
> ```

shouldn't we set dataPrevious here?
___
*[`src/shared/services/DataProviderService.ts` line 153 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7_sXfEINsy5nMFZjJ:-NS7_sXfEINsy5nMFZjK:b-1q8le8) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/services/DataProviderService.ts#L153)):*
> ```XML
>     },
>     /** Layered get that runs the engine's get */
>     get: dataProviderEngine.get.bind(dataProviderEngine),
> ```

Feels like, with a little finagling here, you could use the result from the dataProviderEngine to set the dataPrevious of the subscriber. Then,
- If the client has read the data at all, you always have a dataPrevious. getDataImmediately can possibly go away
- You don't need two calls to get when getDataImmediately is true.
___
*[`src/shared/services/DataProviderService.ts` line 224 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7ddvlA8h2DTwBlKui:-NS7ddvlA8h2DTwBlKuj:bwzpeh4) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/services/DataProviderService.ts#L224)):*
> ```XML
>     throw new Error('Data provider engine does not have a get function');
>   if (!dataProviderEngine.set || typeof dataProviderEngine.set !== 'function')
>     throw new Error('Data provider engine does not have a set function');
> ```

Sure it's not valid to have a read-only data provider? E.g. for a reference Scripture text.


<!-- Sent from Reviewable.io -->

2023-04-03 23:21 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: 16 of 28 files reviewed, 32 unresolved discussions (waiting on @irahopkinson and @JohnThomson)

___
*[`extensions/hello-someone/hello-someone.js` line 38 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS6yE3cBACnWbSfl1Z6:-NS7tIM11x8aqNqv5Uj2:brh5sem) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L38)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose it is guaranteed that this object will be serialized and deserialized before the client sees it, so we're not giving the client a way to trash our internal data by handing over the object?
</blockquote></details>

Actually, if another extension main file (code run from the extension host) runs this, it will receive the full object itself! I suppose maybe it is the extension devs' responsibility to write their extensions so other extensions can't access their objects in ways they don't want. I will shallow clone `people` and make a note here; should we do anything else about it? I suppose we could alternatively model returning a [proxy whose `set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/set) doesn't work.
___
*[`extensions/hello-someone/hello-someone.js` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS6zAj8DoWUbywVLHgK:-NS8-Yvl3UPlK4x8FIpt:bby486q) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L59)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It strikes me as bizarre that a data-provider is inserting a web view that appears to be a UI...perhaps it is just intended as a demonstration of the data it can provide? Is this something a real data-provider would do? If not at least comment.
If it's intended as a demo I think it would be a better demo to show that a separate UI component could interact with the data provider.
</blockquote></details>

Do you consider it to be a problem that an extension defines both a data provider and a web view that ingests that provider? I think it might make sense to separate them in many cases, but I don't think it is quite necessary that they would have to be separated.

Side note: this PR does demonstrate an extension (`quick-verse.js`) providing data and another extension (`hello-world.js` and the renderer itself). :)
___
*[`extensions/hello-someone/hello-someone.js` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7-RVO9yt1L0-gOqpO:-NS81S4_D8DkziRcdCpq:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L90)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's be consistent about using either 'then' or 'await' syntax.
</blockquote></details>

Done.
___
*[`extensions/hello-someone/hello-someone.js` line 124 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7-vM402B92EeoqQbV:-NS89NYe-SWteJS5QDNg:btud83) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L124)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Something to think about here: There could be thousands of people in the system, yet typically only one changes at a time. Serializing the whole list feels wasteful. (Imagine serializing all of Scripture any time some client wants to know when it changes.) I think there should be some way to request notification when any greeting changes, but get a message that just has the data about the one person whose greeting changed.
I'm not sure this is achievable without abandoning the idea that 'set' just returns true if something changed rather than explicitly raising an event.
Another aspect of this problem: the current API assumes that keys are simple, except for the '*' special case. But suppose it gets just a little more complicated. Say the greetings module gets extended to store relationships as well. You can now set({"bill", friend}, "joe") which establishes that joe and bill are friends. You can get({"bill", friend}) which returns a list of people bill is friends with. We'll suppose that friendships are bidirectional, so one result of that call is that get({"joe", friend}) will now include bill.
But what if something has done a subscribe({"joe", friend})? How does the backing store know that subscriber should be notified when set({"bill", friend}, "joe") returns true?
My thinking is that as soon as the data relationships inside a provider get at all complicated, you really need to allow the set code to figure out what events need raising. I suppose there could still be a special case where the only needed notifications are to clients who subscribed to that exact key or "*" but I'm not sure the simplification is worth the cost of having two mechanisms.
</blockquote></details>

Regarding "I think there should be some way to request notification when any greeting changes, but get a message that just has the data about the one person whose greeting changed.", you can provide the subscribe option `receiveEqualUpdates`, and your callback will be run on any updates even if your data didn't change :)

I don't understand the complex relationship example, so I would love to hear more about this! Part of me wonders if the selector events concept I have been considering would solve the issues about different kinds of events going out. Part of me wonders if we need something deeper. Would be good to brainstorm about your concerns together!
___
*[`extensions/hello-someone/hello-someone.js` line 183 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS76eIM-tQ38ZFNPIJ1:-NS8ARt0BukC027qHjsv:b-firqj) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L183)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This suggests that the greetingsDataProviderInfo will be gotten rid of altogether. But might there not be other subscribers? I'm thinking we want a pair of terms different from get/dispose for "give me a connection to X"/"done using X"
Also, what happens if a subscriber neglects to do this? Or if something closes its window and it never gets a chance to?
</blockquote></details>

Actually, `greetingsDataProviderInfo.dispose` disposes of the data provider itself and sends events out to subscribers on `greetingsDataProviderInfo.onDidDispose`. Another good reason to get rid of the whole `Info` pattern and just modify the object! :) Made issue #125
___
*[`extensions/quick-verse/quick-verse.js` line 122 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7AuRH4DojBUVppFNV:-NS8DqJGCpnbNj6wI-La:bs1v8hw) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/quick-verse/quick-verse.js#L122)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't really understand what you're doing here, but I don't see how it can be useful to run map on an array you just forced to be empty.
</blockquote></details>

This is boilerplate I pulled from another extension file. Honestly, the return from `activate` on extensions needs to be reworked completely. #126, #50, #54
___
*[`src/renderer/hooks/papi-hooks/useData.ts` line 56 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7H4W0D1_3LejJnAm5:-NS8G6EK6HtAWmrUZ48H:b9ortzn) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/rende [...]

2023-04-05 01:21 UTC, irahopkinson requested changes
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 18 unresolved discussions (waiting on @JohnThomson and @tjcouch-sil)

___
*[`extensions/hello-someone/hello-someone.js` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS2ic0e59dRkjkN5A6o:-NSDXExK6Fn_rfsAjUL5:b-hmt8pf) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L12)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I tried changing it to an object, and it seems it didn't work with `people` as a member of the object. When I took `people` out and put it in its own object, it worked just fine. I imagine this is likely related to the weirdness between how functions are bound on classes vs as independent arrow functions. Trying to use `this.people` instead of moving it out of the object produced an undefined error as you suspected.

I would say it is cleaner and easier to reason about if it's a whole class instead of a number of objects. That being said, I guess people can do whatever they want as long as it works. Maybe our supported route should be classes, though, for encapsulation and such.

That being said, I will change this to an object permanently to ensure we support it if that seems valuable, though. It's nice to support the full language. Please push back if you think I should change it back to a class! But we already have a class in `quick-verse.js` :)
</blockquote></details>

Nice job getting that to work. Until we have a good reason not to, I think it's good to support both objects and classes.
___
*[`extensions/hello-someone/hello-someone.js` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3wOe968vSZIQcI5jV:-NSDZVxLCYOP6x1IN5fk:b-gt1vq) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L37)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is there a difference in TypeScript definitions between methods and arrow functions? And yes, I made this an arrow function to test flexibility with the way people want to use the api.

I made this into an object, so I put the arrow function on `get` in `quick-verse.js`.
</blockquote></details>

Yes there is a difference. I'm fine with it being an arrow function for testing.
___
*[`extensions/hello-someone/hello-someone.js` line 112 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS34Gmk1lF4O8XVPJ_v:-NSDbGAo6noDW4T1aa2Y:b-clb2md) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L112)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'd like to consider making `success` a special exception because it is already what it is named in `Response`. It feels more concise and straight-forward than `isSuccessful`. Let me know your thoughts :)
</blockquote></details>

Err... we created that type so it's easy for us to change it to follow our guidelines in that type declaration. However here, I'm particularly interested in making the tenary operator more readable 2 lines below. It's made difficult by its inline use. Can you do something about that?
___
*[`extensions/hello-someone/hello-someone.js` line 22 at r2](https://reviewable.io/reviews/paranext/paranext-core/122#-NSDXZuSE5--5wuxmhqi:-NSDXZuSE5--5wuxmhqj:bm8oofb) ([raw file](https://github.com/paranext/paranext-core/blob/ed80cbdd808c01e97ab9708221fefeb068b0ff89/extensions/hello-someone/hello-someone.js#L22)):*
> ```JavaScript
>    * @param {string} data
>    */
>   set: async (selector, data) => {
> ```

This wasn't an arrow function before and you can have async methods in objects. It isn't obvious to me that this needs to be an arrow function (nor the 2 below either). From looking through the code briefly it looks like the method is always called off the object and not passed around anywhere. Also they are no longer using `this` either so I think they can all be object methods. Is that right?

It's fine if this is for test purposes. But having at least one arrow function and one object method might test more. What do you think?
___
*[`src/shared/models/IDataProvider.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3t2RU8zpZObNTCj7S:-NSDgPWdA56ZKOpN-sOh:b-rve2ra) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/models/IDataProvider.ts#L12)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Yeah, this one was hard to name. I negated it to `receiveEqualUpdates` and added more explanation. Does the name itself read better naturally? Does the explanation clear up any confusion?

Aw, I just realized these booleans don't align with the naming conventions either... :( do we really need to put "should" on the front of every one of these? Seems like this is getting kinda unwieldy. I wonder if maybe we should make an exception when booleans are in objects...? Or maybe just specifically in `options`?
</blockquote></details>

Thanks for the rename and updated description. Good improvement. However I think the word `Equal` is what makes it difficult. What about `receiveAllUpdates`? It might also help to specify what happens when it's `false` - will I receive updates only based on my selector or none at all?

In terms of name guidelines, adding `will` or `can` would suffice, i.e. `willGetDataImmediately` and `willReceiveAllUpdates`.
___
*[`src/shared/services/DataProviderService.ts` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3yG6pAzACyzIe50Zz:-NSDwK_dCjV0I_mHchWt:bc57i46) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/services/DataProviderService.ts#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I am definitely interested in considering other options for doing this kind of thing, but I think we pretty much need to wait on a connection to do just about anything. I don't know if it is feasible not to wait on the NetworkService.

`has` reaches out to the network to figure out if any process has the data provider (implementation in `NetworkObjectService.has`), so it needs to be asynchronous.
</blockquote></details>

If `papi` starts by awaiting to initialize the network, can't everything after that assume it's ready?
___
*[`src/shared/services/DataProviderService.ts` line 148 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS42LliCq2I7kSvuQ_b:-NSDxlvNAOZYv5ZFjjbK:bgro81s) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/services/DataProviderService.ts#L148)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I prefer to leave it as `dpeSetResult` because its purpose is to forward the return value from dpeSet out from its own function. A data provider's `set` function makes a thin layer over the engine's `set`, so it seems sensible in my mind to leave it as agnostic as possible. With `dpeSetResult`, if `set` changes its signature in the future, we wouldn't need to rename this variable.

I did realize I could make this implementation even more agnostic by using `...args` instead of naming the parameters, so I did that.
</blockquote></details>

Sounds reasonable and now the whole thing looks more generic too - good spotting on the `args` to help with that.
___
*[`src/shared/services/DataProviderService.ts` line 85 at r2](https://reviewable.io/reviews/paranext/paranext-core/122#-NSDwstwElVly11gSFtf:-NSDwstwElVly11gSFtg:bpxyei9) ([raw file](https://github.com/p [...]

2023-04-05 22:56 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 16 unresolved discussions (waiting on @irahopkinson and @JohnThomson)

___
*[`extensions/hello-someone/hello-someone.js` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3wOe968vSZIQcI5jV:-NSICKiV6g9g91gws3UK:b-himjza) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L37)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yes there is a difference. I'm fine with it being an arrow function for testing.
</blockquote></details>

Ah interesting. After a good bit of google searching, I found the difference [from here](https://stackoverflow.com/questions/54884489/difference-between-arrow-function-vs-normal-function-inside-interface):
```typescript
interface myInterface {
    foo1(args: string): void;
    foo2: (args: string) => void;
}
```

And an example [object function](https://www.w3schools.com/js/js_object_methods.asp):
```typescript
const person = {
  firstName: "John",
  lastName: "Doe",
  id: 5566,
  fullName() {
    return this.firstName + " " + this.lastName;
  }
};
```

I have done some updating to add more variations and such. Learned a lot here. Thanks!
___
*[`extensions/hello-someone/hello-someone.js` line 22 at r2](https://reviewable.io/reviews/paranext/paranext-core/122#-NSDXZuSE5--5wuxmhqi:-NSIYiAaDWghALAzkqMQ:bm6dx47) ([raw file](https://github.com/paranext/paranext-core/blob/ed80cbdd808c01e97ab9708221fefeb068b0ff89/extensions/hello-someone/hello-someone.js#L22)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This wasn't an arrow function before and you can have async methods in objects. It isn't obvious to me that this needs to be an arrow function (nor the 2 below either). From looking through the code briefly it looks like the method is always called off the object and not passed around anywhere. Also they are no longer using `this` either so I think they can all be object methods. Is that right?

It's fine if this is for test purposes. But having at least one arrow function and one object method might test more. What do you think?
</blockquote></details>

Wow, I didn't realize you could attach functions to objects like this! Learned lots from this! See below for my comments about it.
___
*[`src/shared/services/DataProviderService.ts` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3yG6pAzACyzIe50Zz:-NSI_7hV6XefI4R9Kjhg:b-i4ry1r) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/services/DataProviderService.ts#L39)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

If `papi` starts by awaiting to initialize the network, can't everything after that assume it's ready?
</blockquote></details>

It could, but `papi` is an exported object that is always synchronously defined; it doesn't wait for the network to initialize. Each service on it must be ready on its own. I think putting initialize conditions individually into each service also helps with initialization order (if one service depends on another, it can await the other service here). We also do not use `papi` in our core code generally but rather get references to the services directly because of potential dependency cycle issues.
___
*[`src/shared/services/DataProviderService.ts` line 85 at r2](https://reviewable.io/reviews/paranext/paranext-core/122#-NSDwstwElVly11gSFtf:-NSI_oKl618CiebYYF1u:bfn9au4) ([raw file](https://github.com/paranext/paranext-core/blob/ed80cbdd808c01e97ab9708221fefeb068b0ff89/src/shared/services/DataProviderService.ts#L85)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is a good improvement to start with a defined object. We should always aim to do that in general otherwise our code is littered with checks for undefined. In which case this comment seems unnecessary but perhaps that is not our default in general?
</blockquote></details>

Indeed that is not our default. We discussed in the code style conversation today that it is valid for an object to be `undefined` if it isn't populated until a later time. This is just a very special case where `undefined` is an update that we would need to give to the callback.
___
*[`src/shared/util/Util.ts` line 46 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3Qa0a6GjCgqlfomoX:-NSIcA8c8MdKFEkbHl1E:bt6h7vw) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/util/Util.ts#L46)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

An issue sounds good, go ahead and make one.
</blockquote></details>

#134 thanks!


<!-- Sent from Reviewable.io -->

2023-04-06 00:10 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 14 unresolved discussions (waiting on @JohnThomson and @tjcouch-sil)

___
*[`src/shared/services/DataProviderService.ts` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3yG6pAzACyzIe50Zz:-NSIsLND9azRuvyfWbQ4:b-qs1mlm) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/services/DataProviderService.ts#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It could, but `papi` is an exported object that is always synchronously defined; it doesn't wait for the network to initialize. Each service on it must be ready on its own. I think putting initialize conditions individually into each service also helps with initialization order (if one service depends on another, it can await the other service here). We also do not use `papi` in our core code generally but rather get references to the services directly because of potential dependency cycle issues.
</blockquote></details>

I didn't completely understand all you are saying here but I want to and this is now out of scope for this PR. Resolving.


<!-- Sent from Reviewable.io -->

2023-04-06 01:33 UTC, irahopkinson requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 14 unresolved discussions (waiting on @JohnThomson and @tjcouch-sil)

___
*[`src/shared/services/DataProviderService.ts` line 76 at r3](https://reviewable.io/reviews/paranext/paranext-core/122#-NSJBYcJE93GrgJkQAxH:-NSJBYcKCACCEQUlu1KQ:b-71lq2n) ([raw file](https://github.com/paranext/paranext-core/blob/7ba24753fad42231d69f6748dcd4e8a0a48c0db9/src/shared/services/DataProviderService.ts#L76)):*
> ```XML
> 
>     // Default options
>     const subscriberOptions: DataProviderSubscriberOptions = {
> ```

Did you miss staging the updates to this type?


<!-- Sent from Reviewable.io -->

2023-04-06 02:41 UTC, irahopkinson reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 12 unresolved discussions (waiting on @JohnThomson)

___
*[`src/shared/services/DataProviderService.ts` line 76 at r3](https://reviewable.io/reviews/paranext/paranext-core/122#-NSJBYcJE93GrgJkQAxH:-NSJRAWyD7BqiYfYCcE1:b-q59rpr) ([raw file](https://github.com/paranext/paranext-core/blob/7ba24753fad42231d69f6748dcd4e8a0a48c0db9/src/shared/services/DataProviderService.ts#L76)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Did you miss staging the updates to this type?
</blockquote></details>

Done now.


<!-- Sent from Reviewable.io -->

2023-04-06 13:30 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 12 unresolved discussions (waiting on @irahopkinson and @JohnThomson)

___
*[`extensions/hello-someone/hello-someone.js` line 112 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS34Gmk1lF4O8XVPJ_v:-NSIvIdT4MCG_fGZ4epe:b6ud3ce) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L112)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Err... we created that type so it's easy for us to change it to follow our guidelines in that type declaration. However here, I'm particularly interested in making the tenary operator more readable 2 lines below. It's made difficult by its inline use. Can you do something about that?
</blockquote></details>

We discussed and decided to add `success` as a valid boolean in the style guide.
___
*[`src/shared/models/IDataProvider.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS3t2RU8zpZObNTCj7S:-NSIyOA99p1W67cqem4J:b-ipmk2v) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/models/IDataProvider.ts#L12)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Thanks for the rename and updated description. Good improvement. However I think the word `Equal` is what makes it difficult. What about `receiveAllUpdates`? It might also help to specify what happens when it's `false` - will I receive updates only based on my selector or none at all?

In terms of name guidelines, adding `will` or `can` would suffice, i.e. `willGetDataImmediately` and `willReceiveAllUpdates`.
</blockquote></details>

Discussed. Will add options to naming exceptions. Will rename options to `whichUpdates` and `retrieveDataImmediately`.


<!-- Sent from Reviewable.io -->

2023-04-06 19:53 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: 20 of 33 files reviewed, 12 unresolved discussions (waiting on @irahopkinson and @JohnThomson)

___
*[`extensions/hello-someone/hello-someone.js` line 124 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7-vM402B92EeoqQbV:-NSLppvM59zxtlsgUwoH:b-jupe8l) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L124)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Regarding "I think there should be some way to request notification when any greeting changes, but get a message that just has the data about the one person whose greeting changed.", you can provide the subscribe option `receiveEqualUpdates`, and your callback will be run on any updates even if your data didn't change :)

I don't understand the complex relationship example, so I would love to hear more about this! Part of me wonders if the selector events concept I have been considering would solve the issues about different kinds of events going out. Part of me wonders if we need something deeper. Would be good to brainstorm about your concerns together!
</blockquote></details>

I think maybe the following issues address these concerns as we discussed: #109, #135, #136. I don't think I fully understand the use case for sending events yet, so I think it would be good to discuss that more sometime (maybe for another issue?).


<!-- Sent from Reviewable.io -->

2023-04-06 21:23 UTC, irahopkinson requested changes
> Reviewed 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 16 unresolved discussions (waiting on @JohnThomson and @tjcouch-sil)

___
*[`tsconfig.json` line 15 at r5](https://reviewable.io/reviews/paranext/paranext-core/122#-NSNPY9t0ue0xQ-PVNnz:-NSNPY9t0ue0xQ-PVNo-:b-w7fgg2) ([raw file](https://github.com/paranext/paranext-core/blob/513f9b5d258a560176dafc53a97365c1575e42cc/tsconfig.json#L15)):*
> ```jsonc
>       "@client/*": ["./client/*"],
>       "@extension-host/*": ["./extension-host/*"],
>       "@extensions/*": ["../extensions/*"],
> ```

Doesn't this addition mean we also need additions in `.erb\configs\webpack.config.base.ts` so we don't exclude the wrong things?
___
*[`extensions/hello-world/hello-world.js` line 180 at r3](https://reviewable.io/reviews/paranext/paranext-core/122#-NSNQEPi-VKetvWYOcBK:-NSNQEPi-VKetvWYOcBL:bc88uq3) ([raw file](https://github.com/paranext/paranext-core/blob/7ba24753fad42231d69f6748dcd4e8a0a48c0db9/extensions/hello-world/hello-world.js#L180)):*
> ```JavaScript
>           });
> 
>           //# sourceURL=hello-world-webview.js
> ```

Why the deletion on the file extension? I was presumming you have some source that isn't committed and this comment notes that somewhat.
___
*[`src/renderer/testing/TestButtonsPanel.tsx` line 211 at r5](https://reviewable.io/reviews/paranext/paranext-core/122#-NSNQvTG5K4-3CN90Sdy:-NSNQvTG5K4-3CN90Sdz:b-oef2pv) ([raw file](https://github.com/paranext/paranext-core/blob/513f9b5d258a560176dafc53a97365c1575e42cc/src/renderer/testing/TestButtonsPanel.tsx#L211)):*
> ```XML
>       // @ts-ignore ts(2339)
>       .testRandomMethod('from test buttons panel')
>       .then((result: string) => {
> ```

Can this function be async so we can await here or does that not work well with React?
___
*[`src/renderer/testing/TestQuickVerseHeresyPanel.tsx` line 1 at r5](https://reviewable.io/reviews/paranext/paranext-core/122#-NSNRcXw1-_iUPPZscTJ:-NSNRcXw1-_iUPPZscTK:b6ti60d) ([raw file](https://github.com/paranext/paranext-core/blob/513f9b5d258a560176dafc53a97365c1575e42cc/src/renderer/testing/TestQuickVerseHeresyPanel.tsx#L1)):*
> ```XML
> import './TestButtonsPanel.css';
> ```

Can the quick verse section be removed from above the test buttons now that we have this panel?


<!-- Sent from Reviewable.io -->

2023-04-10 13:45 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: 28 of 33 files reviewed, 16 unresolved discussions (waiting on @irahopkinson and @JohnThomson)

___
*[`tsconfig.json` line 15 at r5](https://reviewable.io/reviews/paranext/paranext-core/122#-NSNPY9t0ue0xQ-PVNnz:-NSNbwjMBvM6osMVqn8l:b-hkwxdd) ([raw file](https://github.com/paranext/paranext-core/blob/513f9b5d258a560176dafc53a97365c1575e42cc/tsconfig.json#L15)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Doesn't this addition mean we also need additions in `.erb\configs\webpack.config.base.ts` so we don't exclude the wrong things?
</blockquote></details>

I'm not sure I'm following. The extensions folder should theoretically never be bundled in with any process bundles; I'm just using the folder for types. Do you want me to add exclusion rules for them?
___
*[`extensions/hello-world/hello-world.js` line 180 at r3](https://reviewable.io/reviews/paranext/paranext-core/122#-NSNQEPi-VKetvWYOcBK:-NSNc_xxDluKbOfoe6CN:b2h0kfl) ([raw file](https://github.com/paranext/paranext-core/blob/7ba24753fad42231d69f6748dcd4e8a0a48c0db9/extensions/hello-world/hello-world.js#L180)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Why the deletion on the file extension? I was presumming you have some source that isn't committed and this comment notes that somewhat.
</blockquote></details>

Oops! I must have accidentally deleted it. Thanks for catching that!
___
*[`src/renderer/testing/TestButtonsPanel.tsx` line 211 at r5](https://reviewable.io/reviews/paranext/paranext-core/122#-NSNQvTG5K4-3CN90Sdy:-NSfChb8AKoV8IleBXm4:b-51ejwv) ([raw file](https://github.com/paranext/paranext-core/blob/513f9b5d258a560176dafc53a97365c1575e42cc/src/renderer/testing/TestButtonsPanel.tsx#L211)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Can this function be async so we can await here or does that not work well with React?
</blockquote></details>

It's fine to use with React. I'm just lazy with test code.
___
*[`src/renderer/testing/TestQuickVerseHeresyPanel.tsx` line 1 at r5](https://reviewable.io/reviews/paranext/paranext-core/122#-NSNRcXw1-_iUPPZscTJ:-NSfHKQG3kWsc3q9pQGJ:b-x5jv5l) ([raw file](https://github.com/paranext/paranext-core/blob/513f9b5d258a560176dafc53a97365c1575e42cc/src/renderer/testing/TestQuickVerseHeresyPanel.tsx#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Can the quick verse section be removed from above the test buttons now that we have this panel?
</blockquote></details>

It could be, but I left this in to demonstrate the difference between using `useDataProvider` primarily and `useData` primarily. I also left it in because it demonstrates that we can get updates to data changes between panels :)


<!-- Sent from Reviewable.io -->

2023-04-10 16:04 UTC, lyonsil requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: 28 of 33 files reviewed, 17 unresolved discussions (waiting on @irahopkinson, @JohnThomson, and @tjcouch-sil)

___
*[`extensions/hello-world/hello-world.js` line 198 at r6](https://reviewable.io/reviews/paranext/paranext-core/122#-NSfs5vY7As4jI25lgPX:-NSfs5vY7As4jI25lgPY:bz35mp8) ([raw file](https://github.com/paranext/paranext-core/blob/3bd919f77c52e365d0bde7640534a7cc0e883555/extensions/hello-world/hello-world.js#L198)):*
> ```JavaScript
>   const unsubGreetings = await greetingsDataProvider.subscribe(
>     'Bill',
>     (billGreeting) => logger.log(`Bill's greeting: ${billGreeting}`),
> ```

Is this a case where `logger.log` should be converted to `logger.info`?  In general in other languages I always try to use `logger.<level>("message")`, like `logger.debug`, 'logger.info`, 'logger.warn`, etc.  I see several other cases where `logger.log` is used in other files, too.


<!-- Sent from Reviewable.io -->

2023-04-10 17:11 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: 28 of 33 files reviewed, 8 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/hello-someone/hello-someone.js` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS6zAj8DoWUbywVLHgK:-NSfuuOw8uBRkI_43R0s:b-rcipg8) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L59)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do you consider it to be a problem that an extension defines both a data provider and a web view that ingests that provider? I think it might make sense to separate them in many cases, but I don't think it is quite necessary that they would have to be separated.

Side note: this PR does demonstrate an extension (`quick-verse.js`) providing data and another extension (`hello-world.js` and the renderer itself). :)
</blockquote></details>

It makes some sense that a DP that is just a demo would have a client-type UI as well. I think it partly surprised me because I had the impression that different degrees and possibly mechanisms of sandboxing were involved. I think I also had a vague idea that data providers might run in Node whereas UI has to run in an actual browser (or embedded browser control). If none of those are issues, all that is left is whether combining them makes a good demo. As long you're sure the UI demo isn't depending on capabilities that are only available because it's in the same code chunk, I don't object if you want to keep them together.
___
*[`extensions/hello-someone/hello-someone.js` line 124 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7-vM402B92EeoqQbV:-NSfwNl6-0IHHhlQiIr4:bwpvniv) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L124)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think maybe the following issues address these concerns as we discussed: #109, #135, #136. I don't think I fully understand the use case for sending events yet, so I think it would be good to discuss that more sometime (maybe for another issue?).
</blockquote></details>

I think we talked about this. The idea that a subscriber gets notified of ALL changes and re-submits the query to see whether anything changed is certainly sufficient to ensure the UI updates as needed, but I'm a little worried about performance if the client doesn't ever get any help to know whether something it cares about changed. But it probably makes sense to start with this approach and later, if we need some optimization to avoid resubmitting too many queries on things that didn't change, we can consider it then.
___
*[`src/renderer/hooks/papi-hooks/useData.ts` line 56 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7H4W0D1_3LejJnAm5:-NSg0uq2Es_2U-bDB4fA:b-o1v4w2) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/renderer/hooks/papi-hooks/useData.ts#L56)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is a tricky situation. We want to call the `useDataProvider` hook to get `dataProvider` and `isDisposed` if `dataType` is a string, but we just want to get the `dataProvider` and `isDisposed` from `dataType` if it is already a `useDataProvider`. However, we always have to call the same number of hooks no matter what code path we follow, so we have to make `dataProvider` and `isDisposed` able to be changed based on `dataType`. But then if we leave them to be changeable, TypeScript gets upset that they might be undefined in the arrow functions below because TypeScript thinks they can be `undefined`, and they are no longer in the same context so their type narrowing that we did by defining them in both the `if` and the `else` depending on what `dataType` is goes away. But we know that no other code has touched those variables, so they aren't `undefined`. So my solution was to make temporary `let` variables for them then make them `consts` when they were both defined.

I did think of a tweak to make this a little less weird and be less dependent on the implementation of the `useDataProvider` hook, so I'll do that now.
</blockquote></details>

I think I got confused by the names. dataType suggests something like an object class more than something that is either a data provider or an ID for one. How about calling it dataProviderSource, then the special case is something like gotDataProviderById = isString(dataProvider).
But also consider pushing the logic down into useDataProvider. What if THAT had a special case for an argument that is already [data provider, isDisposed], and just returned it immediately? It would certainly simplify this code, if it didn't complicate the code there too much.
BTW why do you pass around a separate indication of whether the DP is disposed? Is it not possible to ask the DP itself rather than maintaining a separate record that could get forgotten or out of date? If it's so thoroughly disposed of that you can't invoke one of its methods to check whether it is disposed, it might at least be worth a class to wrap the DP itself and its disposed state. But either way there is a concern: how does everyone who cares find out that a DP has been disposed?
___
*[`src/shared/services/DataProviderService.ts` line 153 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7_sXfEINsy5nMFZjJ:-NSfydwx1NPkn-LzLSiH:b-7c595g) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/services/DataProviderService.ts#L153)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Are you essentially suggesting I go ahead and put in a cache that holds responses for different selectors? I suppose I could do that, but I think it might be best to wait on that. It seems a bit complex to figure out exactly how to bust the cache. I will put a `TODO` in.
</blockquote></details>

No, that wasn't my point.
I'm imagining a client doing something like this:
const [greeting, setGreeting] = useState("");
useEffect(async () =>
  dp.subscribe("greeting", (newGreeting) => setGreeting(newGreeting);
  const result = await (dp.get("greeting");
  setGreeting(result);
}, []);

<div>{greeting}</div>

I probably don't have that exactly right, but if it's close, the sad thing is that the client code and the subscription initialization code are both having to do the same get...the client to get the initial value, and the subscribe code to establish dataPrevious.
What if subscribe returned the same result as get? Then the get that the subscribe code does to establish dataPrevious would also serve to give the client the initial value...which BTW also helps ensure that there are no possible race conditions between getting the initial value and setting up the subscription.
Another variation would be that subscribe always invokes the callback with the initial value it gets for dataPrevious, so the subscriber doesn't have to do anything but subscribe. (I think that might be what useData already does? If so, it may be helpful to provide some clarifying comments: when would a client just do a get, and would it ever make sense to do a get at all if there is a need to subscribe?)
Or maybe I'm totally confused. This PR is too big to keep entirely in my head.


<!-- Sent from Reviewable.io -->

2023-04-10 22:20 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: 23 of 33 files reviewed, 8 unresolved discussions (waiting on @irahopkinson, @JohnThomson, and @lyonsil)

___
*[`extensions/hello-someone/hello-someone.js` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS6zAj8DoWUbywVLHgK:-NSgO3GvAb5RLc72DSAc:b99o5zj) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L59)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It makes some sense that a DP that is just a demo would have a client-type UI as well. I think it partly surprised me because I had the impression that different degrees and possibly mechanisms of sandboxing were involved. I think I also had a vague idea that data providers might run in Node whereas UI has to run in an actual browser (or embedded browser control). If none of those are issues, all that is left is whether combining them makes a good demo. As long you're sure the UI demo isn't depending on capabilities that are only available because it's in the same code chunk, I don't object if you want to keep them together.
</blockquote></details>

This code is tricky to read. Essentially, the node extension has to provide an HTML page that the renderer then displays in an `iframe`. So this HTML page here will be sent to the frontend and will run there with some sandboxing. This demonstrates that providers and UI can be run from different places because the UI code here could theoretically be provided by any extension and is not tied down to this node code.

Hopefully, when I implement [packing on extensions](https://github.com/paranext/paranext-extension-template/issues/1), it will be much easier to tell what's going on as the HTML page will be able to be in a different file and just pulled in here instead of being all in the same file.
___
*[`extensions/hello-world/hello-world.js` line 198 at r6](https://reviewable.io/reviews/paranext/paranext-core/122#-NSfs5vY7As4jI25lgPX:-NSgOzPD5REWe-32KiLP:b7hbfiz) ([raw file](https://github.com/paranext/paranext-core/blob/3bd919f77c52e365d0bde7640534a7cc0e883555/extensions/hello-world/hello-world.js#L198)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Is this a case where `logger.log` should be converted to `logger.info`?  In general in other languages I always try to use `logger.<level>("message")`, like `logger.debug`, 'logger.info`, 'logger.warn`, etc.  I see several other cases where `logger.log` is used in other files, too.
</blockquote></details>

Yep! I plan to fix all of these when I merge in from main. Ira has a comment on here somewhere that I am leaving open to remind myself to do a search in files for `logger.log` :)
___
*[`src/renderer/hooks/papi-hooks/useData.ts` line 56 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7H4W0D1_3LejJnAm5:-NShAyodAYRTzE4NTUWS:bw3l91s) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/renderer/hooks/papi-hooks/useData.ts#L56)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think I got confused by the names. dataType suggests something like an object class more than something that is either a data provider or an ID for one. How about calling it dataProviderSource, then the special case is something like gotDataProviderById = isString(dataProvider).
But also consider pushing the logic down into useDataProvider. What if THAT had a special case for an argument that is already [data provider, isDisposed], and just returned it immediately? It would certainly simplify this code, if it didn't complicate the code there too much.
BTW why do you pass around a separate indication of whether the DP is disposed? Is it not possible to ask the DP itself rather than maintaining a separate record that could get forgotten or out of date? If it's so thoroughly disposed of that you can't invoke one of its methods to check whether it is disposed, it might at least be worth a class to wrap the DP itself and its disposed state. But either way there is a concern: how does everyone who cares find out that a DP has been disposed?
</blockquote></details>

I refactored so `useDataProvider` contains the complexity of accepting [data provider, is Disposed]. It is somewhat cleaner! We can't just return from `useDataProvider` if what's passed in is the return of that hook because that would change the number of hooks we're running depending on the code path.

Right now, one reason for why isDisposed is a separate item is that, otherwise, each developer would have to implement their own `useState` and `useEvent` when they want to listen to the data provider disposal. The `isDisposed` variable returned is "reactive" without the user having to do anything to make it so. It is arguable we could just split that part out into a separate hook!

But the bigger issue is that we are currently returning `DataProviderInfo`-type objects that contain the data provider and an accompanying dispose event from the data provider service. People suggested we not mutate network objects (like data providers) passed into the `papi` originally, but I think I have used this `Info` api enough at this point that I'm ready to simplify it to returning the (mutated) data provider itself instead of its "info", which is very unintuitive and cumbersome in most use cases so far. As such, there is an issue for removing the `Info` api pattern #125
___
*[`src/shared/services/DataProviderService.ts` line 153 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS7_sXfEINsy5nMFZjJ:-NSgEqoeE_l-tetGFesv:b-wmfnho) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/src/shared/services/DataProviderService.ts#L153)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

No, that wasn't my point.
I'm imagining a client doing something like this:
const [greeting, setGreeting] = useState("");
useEffect(async () =>
  dp.subscribe("greeting", (newGreeting) => setGreeting(newGreeting);
  const result = await (dp.get("greeting");
  setGreeting(result);
}, []);

<div>{greeting}</div>

I probably don't have that exactly right, but if it's close, the sad thing is that the client code and the subscription initialization code are both having to do the same get...the client to get the initial value, and the subscribe code to establish dataPrevious.
What if subscribe returned the same result as get? Then the get that the subscribe code does to establish dataPrevious would also serve to give the client the initial value...which BTW also helps ensure that there are no possible race conditions between getting the initial value and setting up the subscription.
Another variation would be that subscribe always invokes the callback with the initial value it gets for dataPrevious, so the subscriber doesn't have to do anything but subscribe. (I think that might be what useData already does? If so, it may be helpful to provide some clarifying comments: when would a client just do a get, and would it ever make sense to do a get at all if there is a need to subscribe?)
Or maybe I'm totally confused. This PR is too big to keep entirely in my head.
</blockquote></details>

Ah I see. Thank you for clarifying. Yes, this is a big and confusing PR! I appreciate your patience and determination :)

`createDataProviderSubscriber` creates a subscriber function that uses `retrieveDataImmediately` (previously named `getDataImmediately`, but that was deemed confusing to be a boolean and not a function), provided by the user who is subscribing, to do what you are suggesting already: it runs a `get` immediately when you subscribe and runs your callback with the result so people don't have to subscribe and then run a `get` as well. It  [...]

2023-04-10 23:28 UTC, irahopkinson reviewed
> Reviewed 4 of 5 files at r6, 3 of 5 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson, @lyonsil, and @tjcouch-sil)

___
*[`tsconfig.json` line 15 at r5](https://reviewable.io/reviews/paranext/paranext-core/122#-NSNPY9t0ue0xQ-PVNnz:-NShPPhYDI8RGzovHKQ6:bqiglaq) ([raw file](https://github.com/paranext/paranext-core/blob/513f9b5d258a560176dafc53a97365c1575e42cc/tsconfig.json#L15)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm not sure I'm following. The extensions folder should theoretically never be bundled in with any process bundles; I'm just using the folder for types. Do you want me to add exclusion rules for them?
</blockquote></details>

All good, thanks for the clarification.
___
*[`src/renderer/hooks/papi-hooks/useDataProvider.ts` line 31 at r8](https://reviewable.io/reviews/paranext/paranext-core/122#-NShQzdd3S-tbC9Et7ao:-NShQzdd3S-tbC9Et7ap:b-dp8yle) ([raw file](https://github.com/paranext/paranext-core/blob/217488fc53425cab5aa32677e26cb6c9499bc616/src/renderer/hooks/papi-hooks/useDataProvider.ts#L31)):*
> ```XML
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> function useDataProvider<T extends IDataProvider<any, any, any>>(
>   dataProviderSource: string | [T | undefined, boolean] | undefined,
> ```

This appears to be duplicated below?



_Code quote:_
```XML
function useDataProvider<T extends IDataProvider<any, any, any>>(
  dataProviderSource: string | [T | undefined, boolean] | undefined,
): [T | undefined, boolean];
```
___
*[`src/renderer/testing/TestQuickVerseHeresyPanel.tsx` line 1 at r5](https://reviewable.io/reviews/paranext/paranext-core/122#-NSNRcXw1-_iUPPZscTJ:-NShSoATB07yHwCWC-_H:brxp9sq) ([raw file](https://github.com/paranext/paranext-core/blob/513f9b5d258a560176dafc53a97365c1575e42cc/src/renderer/testing/TestQuickVerseHeresyPanel.tsx#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It could be, but I left this in to demonstrate the difference between using `useDataProvider` primarily and `useData` primarily. I also left it in because it demonstrates that we can get updates to data changes between panels :)
</blockquote></details>

Sounds good.


<!-- Sent from Reviewable.io -->

2023-04-11 13:09 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson, @JohnThomson, and @lyonsil)

___
*[`src/renderer/hooks/papi-hooks/useDataProvider.ts` line 31 at r8](https://reviewable.io/reviews/paranext/paranext-core/122#-NShQzdd3S-tbC9Et7ao:-NSkPb-tDmjXrvxh0OY7:bej8pge) ([raw file](https://github.com/paranext/paranext-core/blob/217488fc53425cab5aa32677e26cb6c9499bc616/src/renderer/hooks/papi-hooks/useDataProvider.ts#L31)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This appears to be duplicated below?
</blockquote></details>

Indeed, it is unfortunate that this has to be the case, but [only the declared overload signatures are usable (as opposed to the implementation signature)](https://www.typescriptlang.org/docs/handbook/2/functions.html#overload-signatures-and-the-implementation-signature). I want to be able to pass in a variable that is either a string or the return from this hook, so I had to make an overload signature that is the same as the implementation signature. Thanks for checking!


<!-- Sent from Reviewable.io -->

2023-04-11 18:58 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: 24 of 33 files reviewed, 5 unresolved discussions (waiting on @irahopkinson, @lyonsil, and @tjcouch-sil)

___
*[`src/renderer/hooks/papi-hooks/useData.ts` line 11 at r9](https://reviewable.io/reviews/paranext/paranext-core/122#-NSlfP6B8Ekq4EpNK63_:-NSlfP6B8Ekq4EpNK63a:b2w13xg) ([raw file](https://github.com/paranext/paranext-core/blob/09748ec73dbd17283333cc1166e0aed9c0581ead/src/renderer/hooks/papi-hooks/useData.ts#L11)):*
> ```XML
> /**
>  * Subscribes to run a callback on a data provider's data with specified selector
>  * @param dataProviderSource string data type to get data provider for OR dataProvider (result of useDataProvider if you
> ```

Consider spelling out
@param dataProviderSource (first overload) ...
@param dataProvider (second overload)...

If the compiler/doc generator/whatever is using these @param things will let you.
___
*[`src/renderer/hooks/papi-hooks/useDataProvider.ts` line 36 at r8](https://reviewable.io/reviews/paranext/paranext-core/122#-NSl4a224gfsL993v2EW:-NSl_hs91C0UXaRfZcQC:bae1j60) ([raw file](https://github.com/paranext/paranext-core/blob/217488fc53425cab5aa32677e26cb6c9499bc616/src/renderer/hooks/papi-hooks/useDataProvider.ts#L36)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You have good points. I will refactor `useDataProvider` to stop providing `isDisposed`.

Regarding passing in a string or a DP, I'm trying to provide an easy way to avoid having one component getting the data provider multiple times. See `useDataProvider` and `useData` in `TestQuickVerseHeresypanel.tsx` for an example.
</blockquote></details>

Hmm, I wonder what dataProviderSource will do if asked repeatedly for the same DP. Is it going to make another instance, or quickly look up the same one? If it will efficiently provide the same one, ideally without another render, I would wonder whether the overload that takes the existing DP was premature optimization.
Still it's done now and the result is not bad, except perhaps in the couple of places where we have the three definitions of the function.
I think I would be inclined to make it look MORE like two overloads and an implementation.  Something like,

Get the specified data provider (returns undefined in the initial render while it is being created, and again in an additional render after it has been disposed)
...first overload...

Return the same Data Provider passed in (this overload makes it easier for some clients to follow the rules of hooks)
...second overload...

Implementation of the two overloads:
...the implementation...

But it's also OK as is...this is just an idea you can use if you think it helps. (The approach has some appeal for useData, too, but there it would be harder to do it without repeating a lot.)


<!-- Sent from Reviewable.io -->

2023-04-11 19:59 UTC, irahopkinson reviewed
> Reviewed 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-04-11 22:21 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: 22 of 34 files reviewed, 3 unresolved discussions (waiting on @irahopkinson, @JohnThomson, @lyonsil, and @param)

___
*[`src/renderer/hooks/papi-hooks/useData.ts` line 11 at r9](https://reviewable.io/reviews/paranext/paranext-core/122#-NSlfP6B8Ekq4EpNK63_:-NSlrNeLEodgPMhcNrtn:b-ydonir) ([raw file](https://github.com/paranext/paranext-core/blob/09748ec73dbd17283333cc1166e0aed9c0581ead/src/renderer/hooks/papi-hooks/useData.ts#L11)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Consider spelling out
@param dataProviderSource (first overload) ...
@param dataProvider (second overload)...

If the compiler/doc generator/whatever is using these @param things will let you.
</blockquote></details>

Done. Good idea.
___
*[`src/renderer/hooks/papi-hooks/useDataProvider.ts` line 36 at r8](https://reviewable.io/reviews/paranext/paranext-core/122#-NSl4a224gfsL993v2EW:-NSmLC5g6DbuM6w4N4CA:b-bxzut0) ([raw file](https://github.com/paranext/paranext-core/blob/217488fc53425cab5aa32677e26cb6c9499bc616/src/renderer/hooks/papi-hooks/useDataProvider.ts#L36)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Hmm, I wonder what dataProviderSource will do if asked repeatedly for the same DP. Is it going to make another instance, or quickly look up the same one? If it will efficiently provide the same one, ideally without another render, I would wonder whether the overload that takes the existing DP was premature optimization.
Still it's done now and the result is not bad, except perhaps in the couple of places where we have the three definitions of the function.
I think I would be inclined to make it look MORE like two overloads and an implementation.  Something like,

Get the specified data provider (returns undefined in the initial render while it is being created, and again in an additional render after it has been disposed)
...first overload...

Return the same Data Provider passed in (this overload makes it easier for some clients to follow the rules of hooks)
...second overload...

Implementation of the two overloads:
...the implementation...

But it's also OK as is...this is just an idea you can use if you think it helps. (The approach has some appeal for useData, too, but there it would be harder to do it without repeating a lot.)
</blockquote></details>

I adjusted the JSDocs to properly give full information for the different overloads of these hooks.

Your comment also made me realize I wasn't memoizing `NetworkObjectService.get` at all, which needs to happen so we don't create multiple of the same network object. As such, I made that adjustment as well. Thanks!


<!-- Sent from Reviewable.io -->

2023-04-12 21:49 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: 3 of 56 files reviewed, 3 unresolved discussions (waiting on @irahopkinson, @JohnThomson, @lyonsil, and @param)

___
*[`extensions/hello-someone/hello-someone.js` line 46 at r1](https://reviewable.io/reviews/paranext/paranext-core/122#-NS2orzZDBn63m_yz4JB:-NSrRQM1DGnTqnt9uqBF:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/1fd1c95ff8c95f8e4711fac3ff1f4f54dd3e90dc/extensions/hello-someone/hello-someone.js#L46)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Good call. Please leave this comment here so I remember to do this after merging, but I think it may be best to do all the reviewing we want before I merge and have to reformat everything.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-12 22:01 UTC, lyonsil approved these changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: 3 of 56 files reviewed, 3 unresolved discussions (waiting on @irahopkinson, @JohnThomson, and @param)



<!-- Sent from Reviewable.io -->

2023-04-12 22:45 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r9, 38 of 46 files at r11, 6 of 8 files at r12, 5 of 5 files at r13, 4 of 4 files at r14, all commit messages.
> Dismissed @JohnThomson from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122#-:-NSrczGQ6LLNCpDpLCjx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjcouch-sil)

___
*[`src/renderer/components/papi-components/text-field.component.tsx` line 47 at r14](https://reviewable.io/reviews/paranext/paranext-core/122#-NSrUgg74LPDg5TaVbG4:-NSrUgg74LPDg5TaVbG5:b-ed5dcu) ([raw file](https://github.com/paranext/paranext-core/blob/4bb2809e0f0062248113ff5d521eca3c4d228139/src/renderer/components/papi-components/text-field.component.tsx#L47)):*
> ```XML
>   className?: string;
>   /**
>    * Starting value for the text field if it is not controlled
> ```

I want to register my objection to adding unrelated (out of scope) items to any PR let alone an already large PR.

This is a non-blocking comment and I'm reviewing them because this PR is overdue for merging, but I felt I need to mention this.


<!-- Sent from Reviewable.io -->

2023-04-13 13:14 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjcouch-sil)

___
*[`src/renderer/components/papi-components/text-field.component.tsx` line 47 at r14](https://reviewable.io/reviews/paranext/paranext-core/122#-NSrUgg74LPDg5TaVbG4:-NSukCa106i7NwjkotQb:b-gijdzz) ([raw file](https://github.com/paranext/paranext-core/blob/4bb2809e0f0062248113ff5d521eca3c4d228139/src/renderer/components/papi-components/text-field.component.tsx#L47)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I want to register my objection to adding unrelated (out of scope) items to any PR let alone an already large PR.

This is a non-blocking comment and I'm reviewing them because this PR is overdue for merging, but I felt I need to mention this.
</blockquote></details>

I think it is a good idea to keep unrelated stuff out of the pr. I wasn't really thinking too deeply about how related the component stuff was. I put a text field in for testing, and I realized immediately that it was not controllable. As such, I went and fixed it and used it. But I suppose it makes sense to just keep using a normal input field for the PR and change it in a follow-up. Will keep this in mind for the future. Thanks!


<!-- Sent from Reviewable.io -->

2023-04-13 13:14 UTC, merged