Send/receive events and add unit tests (#58)
paranext/paranext-core pull request #124
Opened 2023-04-03 21:09 UTC by lyonsil

2023-04-05 04:39 UTC, irahopkinson reviewed
I started reviewing this and then realized that the base branch had already been merged (and deleted) and so I thought the diff would be wrong but for some reason **Reviewable** is still showing the correct diff to the orignal base that is now gone. Well done **Reviewable*! :clap: 

> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124#-:-NSE7Ua53ss53gsU_2L9:b8aatc5)* status: all files reviewed, 12 unresolved discussions (waiting on @lyonsil)

___
*[`.vscode/extensions.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE2pXgAwYyNHpIYNi8:-NSE2pXgAwYyNHpIYNi9:be95wk3) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/.vscode/extensions.json#L9)):*
> ```JSON
>     "mrmlnc.vscode-json5",
>     "streetsidesoftware.code-spell-checker",
>     "formulahendry.dotnet-test-explorer"
> ```

nit: prefer alphabetical order where possible to help with finding items.
___
*[`.vscode/extensions.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE39GN54wdZtJu96ng:-NSE39GN54wdZtJu96nh:b-4cai91) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/.vscode/extensions.json#L9)):*
> ```JSON
>     "mrmlnc.vscode-json5",
>     "streetsidesoftware.code-spell-checker",
>     "formulahendry.dotnet-test-explorer"
> ```

Thanks for adding this to the list. I already had it installed so can recommend it also.
___
*[`.vscode/settings.json` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE2bfTDObs2Vq_sWrS:-NSE2bfTDObs2Vq_sWrT:be95wk3) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/.vscode/settings.json#L2)):*
> ```JSON
> {
>   "dotnet-test-explorer.testProjectPath": "c-sharp-tests/c-sharp-tests.csproj",
> ```

nit: prefer alphabetical order where possible to help with finding items.
___
*[`c-sharp/AssemblyInfo.cs` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE47DX3MkhAYVocE-P:-NSE47DX3MkhAYVocE-Q:b2yi3u0) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/AssemblyInfo.cs#L3)):*
> ```Smalltalk
> using System.Runtime.CompilerServices;
> 
> [assembly: InternalsVisibleTo("c-sharp-tests")]
> ```

I'm guessing the tests can't live in `c-sharp/tests`?
___
*[`c-sharp/README.md` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE4tCM74jOdZzB2nI0:-NSE4tCM74jOdZzB2nI1:bjl0m3g) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/README.md#L1)):*
> ```Markdown
> # Helpful Tips
> ```

Thanks for adding this README. Nice job and the links make it easy too.
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEHObm1nshNzFlx8TI:-NSEHObm1nshNzFlx8TJ:b96xrkm) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L86)):*
> ```Smalltalk
> 
>         // Find the right message type to deserialize
>         var messageType = ReadValue<MessageType>(ref readerClone, "type");
> ```

I'm not sure I agree with changing to use `var` here since it isn't obvious it will return an `Enum`, thoughts?
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 93 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEImkICrNqUkI-GraO:-NSEImkICrNqUkI-GraP:b-k8u1wy) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L93)):*
> ```Smalltalk
>         if (messageDataType == typeof(MessageEvent))
>         {
>             readerClone = reader; // Ordering of items in JSON isn't guaranteed
> ```

nit: comments on their own line, see our [guide](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#commenting-conventions). Here and all over the place.
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 102 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEJuoz3uz5MvdnVWO_:-NSEJuoz3uz5MvdnVWOa:b-vurtmk) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L102)):*
> ```Smalltalk
> 
>         var msg = (Message)
>             JsonSerializer.Deserialize(ref reader, messageDataType!, s_recursiveSafeOptions)!;
> ```

Can you still assert `messageDataType` is not null with the addition of L95-96? Above we throw if the `TryGetValue` fails but not here.
___
*[`c-sharp/Messages/EventType.cs` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEQVTCE6jgvybdN--C:-NSEQVTCE6jgvybdN--D:b-2hfvod) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/Messages/EventType.cs#L7)):*
> ```Smalltalk
> public sealed class EventType : EnumType
> {
>     public static readonly Enum<EventType> ClientConnect = new("network:onDidClientConnect");
> ```

These 3 look like they are linking to TS items. If that's so can you add comments with where they came from?
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 327 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEYsUr0Lu8XzCqQHIv:-NSEYsUr0Lu8XzCqQHIw:b-upfuz5) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageTransports/PapiClient.cs#L327)):*
> ```Smalltalk
>                         _ = Task.Run(() =>
>                         {
>                             HandleMessage(message);
> ```

Thanks for breaking this up in to more manageble and readable methods.
___
*[`c-sharp-tests/c-sharp-tests.csproj` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEBIwsDgOpOK2Vw_D0:-NSEBIwsDgOpOK2Vw_D1:b-u30kfp) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp-tests/c-sharp-tests.csproj#L1)):*
> ```XML
> <Project Sdk="Microsoft.NET.Sdk">
> ```

Thanks for adding the tests. We should add them to GHA in `.github\workflows\test.yml` so they run on each PR. Are you comfortable to do that? Either you or I could do that in a follow-up PR but it would be cool to see them on this PR.
___
*[`c-sharp-tests/c-sharp-tests.csproj` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEh5-97SSmoRhol7VS:-NSEh5-97SSmoRhol7VT:bv2mtpf) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp-tests/c-sharp-tests.csproj#L15)):*
> ```XML
>   <ItemGroup>
>     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
>     <PackageReference Include="xunit" Version="2.4.2" />
> ```

Any reason for preference of `xunit` over `nunit`?
___
*[`c-sharp-tests/JsonUtils/MessageConverter.cs` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEZpw6BbQcvJ3Atk3w:-NSEZpw6BbQcvJ3Atk3x:bp9p5x8) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp-tests/JsonUtils/MessageConverter.cs#L7)):*
> ```Smalltalk
> namespace TestParanextDataProvider.MessageHandlers;
> 
> public class MessageConverterTest
> ```

I'd feel happier if the file was named the same as this class. A couple of times during review I've opened this file and been confused that it didn't match what I was seeing in Reviewable since this test file is named the same as the class file it's testing.

nit: I'd name this class in plural, i.e. `MessageConverterTests`.
___
*[`c-sharp-tests/JsonUtils/MessageConverter.cs` line 49 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEarKi8Tr2nDXsestl:-NSEarKi8Tr2nDXsestm:bbljw1m) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp-tests/JsonUtils/ [...]

2023-04-05 13:22 UTC, FoolRunning requested changes
> Reviewed 24 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: all files reviewed, 23 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`c-sharp/AssemblyInfo.cs` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBd-7PEwJmocrwSPoT:-NSBd-7PEwJmocrwSPoU:bf3cbje) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/AssemblyInfo.cs#L3)):*
> ```Smalltalk
> using System.Runtime.CompilerServices;
> 
> [assembly: InternalsVisibleTo("c-sharp-tests")]
> ```

That reminds me that we at some point, not part of this PR, need to create the assembly info correctly with the correct copyright, etc.
___
*[`c-sharp/AssemblyInfo.cs` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE47DX3MkhAYVocE-P:-NSGUDGZDdQVU81GYhQG:bsewl0u) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/AssemblyInfo.cs#L3)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I'm guessing the tests can't live in `c-sharp/tests`?
</blockquote></details>

Ideally not since it makes it more complicated to create a release build without the test code included in the built DLL.
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBxO8dE5wmQ1jUAyoY:-NSBxO8dE5wmQ1jUAyoZ:b-h9yvcm) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L51)):*
> ```Smalltalk
>         {
>             var baseType = obj!.GetType().BaseType;
>             while (baseType != null)
> ```

What is the purpose of these loops? It appears to just look at the base types of each object looking for a non-abstract base type, but in the possibilities list above you already ensure that the types in the list are not abstract. Is the problem that there are some non-abstract classes that are used as a base type?
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEHObm1nshNzFlx8TI:-NSGULqF0TRjN67lAsTQ:b9v4p18) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L86)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I'm not sure I agree with changing to use `var` here since it isn't obvious it will return an `Enum`, thoughts?
</blockquote></details>

Per [our guidelines](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#implicitly-typed-local-variables), ``var`` should only be used if it's obvious. Here it is not, so ``var`` should not be used.
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 98 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBz0906cs9s7Svd1iD:-NSBz0906cs9s7Svd1iE:b-f57ts5) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L98)):*
> ```Smalltalk
>                 messageDataType = eventMessageDataType;
> 
>             readerClone = reader; // We'll need it again below
> ```

I think it's dangerous to not keep the cloning of the state near where the reading happens (i.e. down where ``GetEventData`` is called). The cloning needs to happen before any call to ``ReadValue``. It might be best to instead have the cloning happen inside of ``ReadValue`` so callers don't have to worry about it.
___
*[`c-sharp/MessageHandlers/MessageHandlerEvent.cs` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCLhs6ECPVfKe-ltPL:-NSCLhs6ECPVfKe-ltPM:b-zf6evk) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerEvent.cs#L22)):*
> ```Smalltalk
>     private readonly ConcurrentDictionary<Enum<EventType>, PapiEventHandler> _handlers = new();
> 
>     public void RegisterEventHandler(Enum<EventType> eventType, PapiEventHandler handler)
> ```

I'm not convinced that we should allow more than one handler for a specific event type. Only allowing one would greatly simplify things, I think.
___
*[`c-sharp/MessageHandlers/MessageHandlerEvent.cs` line 70 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSC-2_r1sC4wkif24dZ:-NSC-2_r1sC4wkif24d_:bk41m4g) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerEvent.cs#L70)):*
> ```Smalltalk
>         List<Message> messages = new();
>         MessageEvent messageEvent = (MessageEvent)message;
>         if (_handlers.TryGetValue(messageEvent.EventType, out var handlersForEventType))
> ```

Without locking here, you can get into the situation where a Register or Unregister is half-run (i.e. between the ``TryGetValue`` and the setting of the new delegate). It won't necessarily cause problems, but it would still be best if a lock was consistently used (and it changed to be a normal dictionary). It could also keep potential problems happening in the future if more code is added to Register/Unregister.
The lock only needs to cover the ``TryGetValue`` call so it shouldn't cause any problems (although it will probably make the code a little awkward).
___
*[`c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs` line 63 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCN58GBbje1X0_NDV-:-NSCN58GBbje1X0_NDV0:b-at8aky) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs#L63)):*
> ```Smalltalk
>             );
>         }
>         return messageList;
> ```

If we decide to keep multiple message handlers (I'm hoping not), this should be changed to ``yield return`` calls instead of creating a new list all the time containing one item.
___
*[`c-sharp/Messages/MessageEvent.cs` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCNt_87mXHMaD_VfS0:-NSCNt_87mXHMaD_VfS1:b16if4) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/Messages/MessageEvent.cs#L16)):*
> ```Smalltalk
>     {
>         // Default for new events that don't have a custom class
>         EventContentsType = typeof(System.Text.Json.JsonElement);
> ```

``using``s should be used instead of using fully qualified names.
___
*[`c-sharp/Messages/MessageEventClientConnect.cs` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCNbPU0D5IWSijKjuF:-NSCNbPU0D5IWSijKjuG:b16if4) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/Messages/MessageEventClientConnect.cs#L10)):*
> ```Smalltalk
>     /// </summary>
>     private MessageEventClientConnect()
>         : base(Messages.EventType.ClientConnect) { }
> ```

``using``s should be used instead of using fully qualified names.
___
*[`c-sharp/Messages/MessageEventClientConnect.cs` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSGVhzZ6dGsT5LcZRq_:-NSGVhzZ6dGsT5LcZRqa:b16if4) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/Messages/MessageEventClientConnect.cs#L13)):*
> ```Smalltalk
> 
>     public MessageEventClientConnect(MessageEventClientConnectContents eventContents)
>         : base(Messages.EventType.ClientConnect, eventContents) { }
> ```

``using``s should be used instead of using fully qualified names.
___
*[`c-sharp/Messages/MessageEventClientDisconnect.cs` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCNiYkEbbpsTugSRX9:-NSCNiYkEbbpsTugSRXA:b16if4) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c [...]

2023-04-05 13:27 UTC, FoolRunning reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: all files reviewed, 23 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`c-sharp/AssemblyInfo.cs` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE47DX3MkhAYVocE-P:-NSGaO6Y3GI94Ihfp1Oy:b-z0jtre) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/AssemblyInfo.cs#L3)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Ideally not since it makes it more complicated to create a release build without the test code included in the built DLL.
</blockquote></details>

Ignore my previous comment. I read it wrong.


<!-- Sent from Reviewable.io -->

2023-04-05 16:04 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: 28 of 29 files reviewed, 20 unresolved discussions (waiting on @FoolRunning, @irahopkinson, and @tjcouch-sil)

___
*[`.vscode/extensions.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE2pXgAwYyNHpIYNi8:-NSGqDA19VWM-8d4TJrc:b-yyd6fx) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/.vscode/extensions.json#L9)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

nit: prefer alphabetical order where possible to help with finding items.
</blockquote></details>

Done - yes, good idea.
___
*[`.vscode/settings.json` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE2bfTDObs2Vq_sWrS:-NSGq5xu3HUHYQaTaCHz:bnlpofb) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/.vscode/settings.json#L2)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

nit: prefer alphabetical order where possible to help with finding items.
</blockquote></details>

Isn't it already in alphabetical order here?
___
*[`c-sharp/AssemblyInfo.cs` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBd-7PEwJmocrwSPoT:-NSGsE7R5PLNdRd6tgvO:b-rdeubv) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/AssemblyInfo.cs#L3)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

That reminds me that we at some point, not part of this PR, need to create the assembly info correctly with the correct copyright, etc.
</blockquote></details>

Do you want to create an issue in the backlog with the details of what you think should be done?
___
*[`c-sharp/AssemblyInfo.cs` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE47DX3MkhAYVocE-P:-NSGqovy5MR-Uefk-XMp:b-rcved9) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/AssemblyInfo.cs#L3)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Ignore my previous comment. I read it wrong.
</blockquote></details>

In my previous experience, it seemed better to put unit tests in a separate assembly than putting them in the same assembly.  There is some [discussion about it here](https://stackoverflow.com/questions/347156/do-you-put-unit-tests-in-same-project-or-another-project) that highlight some of the same reasons I was thinking about.  Having said that, [there is an answer](https://stackoverflow.com/a/56646051) lower down that covers some ways to combine them together if the group prefers that approach.  It will make the project more complex, but perhaps that is better than 2 projects.  I'm open for discussion on this point for sure.
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBxO8dE5wmQ1jUAyoY:-NSGsM2D5uxnP3Ga1kb6:b2ny210) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L51)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

What is the purpose of these loops? It appears to just look at the base types of each object looking for a non-abstract base type, but in the possibilities list above you already ensure that the types in the list are not abstract. Is the problem that there are some non-abstract classes that are used as a base type?
</blockquote></details>

The original lookup that generates `possiblities` goes arbitrarily deep in the class hierarchy.  There will be immediate children and multiple levels down.  For example, `Message` will have `MessageEvent` and `MessageEventClientConnect` generated as possibilities.  I only want `MessageEvent` when I'm looking for "direct" message types.  However, once I start looking at `MessageEvent` I'm going to run into `MessageEventGeneric` while walking up the inheritance hierarchy from `MessageEventClientconnect`, and that is an abstract type.  The types returned all have to be constructed later, so I can't take in abstract classes.

The whole point of using reflection here is to avoid having to have people remember to add classes to the right dictionaries whenever a new message or event is added later.  If people follow the `README.md` directions or just follow the existing pattern in the code, this will just work for them.
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEHObm1nshNzFlx8TI:-NSGtUyG3DR7REx9wJZ9:b-j2dbuc) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L86)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Per [our guidelines](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#implicitly-typed-local-variables), ``var`` should only be used if it's obvious. Here it is not, so ``var`` should not be used.
</blockquote></details>

Done - I thought it was obvious enough, but that's probably because I wrote it! :grin: 
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 93 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEImkICrNqUkI-GraO:-NSGuBfQBpO7FfIRr5OP:b-cwarru) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L93)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

nit: comments on their own line, see our [guide](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#commenting-conventions). Here and all over the place.
</blockquote></details>

Done - I was following the pattern already established in other parts of this file.
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 98 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBz0906cs9s7Svd1iD:-NSGyLjD7O5DlZRIrmN4:b-unge2m) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L98)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I think it's dangerous to not keep the cloning of the state near where the reading happens (i.e. down where ``GetEventData`` is called). The cloning needs to happen before any call to ``ReadValue``. It might be best to instead have the cloning happen inside of ``ReadValue`` so callers don't have to worry about it.
</blockquote></details>

Done - that is a good suggestion!
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 102 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEJuoz3uz5MvdnVWO_:-NSGzEv74-pi6JZOnIb_:b-g9zjis) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L102)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Can you still assert `messageDataType` is not null with the addition of L95-96? Above we throw if the `TryGetValue` fails but not here.
</blockquote></details>

I don't see how `messageDataType` could be null here.  We threw above if `s_messageTypeMap` didn't have a mapping to the right message type.  If the mapping exists, then the value from the dictionary will not be null.  The only way that variable could be null is if the dictionary didn't have any value, but we already threw if that was the case.

Am I missing something that you see?
___
*[`c-sharp/MessageHandlers/MessageHandlerEvent.cs` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCLhs6ECPVfKe-ltPL:-NSH-1 [...]

2023-04-05 18:12 UTC, FoolRunning reviewed
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: all files reviewed, 17 unresolved discussions (waiting on @irahopkinson, @lyonsil, and @tjcouch-sil)

___
*[`c-sharp/AssemblyInfo.cs` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBd-7PEwJmocrwSPoT:-NSHVRMo8RfffhtpNVpq:bqwyebr) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/AssemblyInfo.cs#L3)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Do you want to create an issue in the backlog with the details of what you think should be done?
</blockquote></details>

I've created an issue (#133)
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBxO8dE5wmQ1jUAyoY:-NSHVfDjE1dsOL1sR1dR:b-dbsfx9) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L51)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

The original lookup that generates `possiblities` goes arbitrarily deep in the class hierarchy.  There will be immediate children and multiple levels down.  For example, `Message` will have `MessageEvent` and `MessageEventClientConnect` generated as possibilities.  I only want `MessageEvent` when I'm looking for "direct" message types.  However, once I start looking at `MessageEvent` I'm going to run into `MessageEventGeneric` while walking up the inheritance hierarchy from `MessageEventClientconnect`, and that is an abstract type.  The types returned all have to be constructed later, so I can't take in abstract classes.

The whole point of using reflection here is to avoid having to have people remember to add classes to the right dictionaries whenever a new message or event is added later.  If people follow the `README.md` directions or just follow the existing pattern in the code, this will just work for them.
</blockquote></details>

I see, now. It's because ``MessageEvent`` is still considered a ``Message`` object, so you need to make sure it derives from the correct type so it can be included in the correct ``Dictionary``. That might deserve a comment somewhere in this method.
Or, maybe it should be done differently through interfaces? (i.e. have message instances and message events derive from completely different interfaces instead of relying on the base class?)
Any thoughts?
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEHObm1nshNzFlx8TI:-NSHW_gICLHx8pqFQ1PP:bqy2poo) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L86)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Done - I thought it was obvious enough, but that's probably because I wrote it! :grin: 
</blockquote></details>

Yeah, according to the coding standards, basically you would only be able to use ``var`` if a direct assignment or a cast was on that line. Every other time, the type can't be inferred without knowing what a method returns. Personally, I try to never use ``var``, but that's just me. 😉
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 118 at r3](https://reviewable.io/reviews/paranext/paranext-core/124#-NSHXnAh3SpRb4K2s86s:-NSHXnAh3SpRb4K2s86t:bxf40ui) ([raw file](https://github.com/paranext/paranext-core/blob/b481041ac7ffd1e7f50f99012ab8a58df881a440/c-sharp/JsonUtils/MessageConverter.cs#L118)):*
> ```Smalltalk
>     /// </summary>
>     private static Enum<T> ReadValue<T>(Utf8JsonReader reader, string property)
>         where T : class, EnumType
> ```

I originally wrote this method similar to what you have now, but I wasn't sure what happened if the method got inlined. I didn't find any answer to the question, and since the code depends on getting a copy of the reader, I didn't want to take any chances. Do you know if the reader is still guaranteed to be copied (via a struct copy from the caller) even if the ``ReadValue`` method gets inlined?
___
*[`c-sharp/MessageHandlers/MessageHandlerEvent.cs` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCLhs6ECPVfKe-ltPL:-NSHYo1OEXyAMr4Pn9Ve:b-88eqvu) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerEvent.cs#L22)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I think forcing a single handler per event will force tighter coupling of other code later or at least will just push the multiplexing further out to be repeated.  Events are one-way notifications as I understand them.  If two different components need to be notified of something (e.g., a remote network object was created or destroyed, a user clicked on some button, etc.), then we need to provide some way for them both to learn about it later.  If we start using events where we intended a request/response, that is a bug on the sender side, I would argue.

I am probably also thinking about events as I think about events in C#, Java, and other languages/frameworks where they are intended to be multicast, one way channels of information flow.  If we don't intend that to be the definition here, then we probably need to start writing some architectural documentation that defines what we mean by key terms like "event" since it diverges from other commonly understood meanings of the same term.
</blockquote></details>

I agree that over the PAPI, we'd want more than one registration to be possible, but since the event registration is only C#-facing and the C# code is basically acting only as a data provider, I think it would be a bad design if we had more than one handler inside the C# that handled a given event from the PAPI.

It's possible I missed something, though.
___
*[`c-sharp/MessageHandlers/MessageHandlerEvent.cs` line 70 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSC-2_r1sC4wkif24dZ:-NSHZfmF-3esKC_uaZj3:b-rqf2yu) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerEvent.cs#L70)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

The proposed change doesn't do anything about the race condition you mention above because sometimes the Register/Unregister call will happen before the event is fired, and sometimes the Register/Unregister call will happen after the event is fired.  The point of the lock is to avoid losing an event handler registration/unregistration since those are multi-step operations.  Adding the lock to execution gives a false impression of doing something useful.  If ordering between registration/unregistration and execution is needed, the owner of the PapiClient object has to enforce that.
</blockquote></details>

What I was trying to say, is that without the lock, some other thread could be running a register call and it could be inside the lock, but in between the two calls to the Dictionary and then this code here runs. Right now, the way the code currently is, I don't think that's a problem, but in the future, if something else was done in the lock to the Dictionary values (as an extreme example, maybe a new registration required all values in the Dictionary to be removed before the new ones were added back in), then this code here could get the Dictionary while in that in-between state since it's not inside a lock. Yes, the dictionary itself will be perfectly fine, but the code here will not run correctly because the information in the Dictionary was in the process of being changed.
Thus, I think it would be best if the lock was put around this call - which then makes it not need to be a *concurrent* dictionary.

If that's still not clear, feel [...]

2023-04-05 18:48 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: 27 of 29 files reviewed, 16 unresolved discussions (waiting on @FoolRunning, @irahopkinson, and @tjcouch-sil)

___
*[`c-sharp-tests/JsonUtils/MessageConverter.cs` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEZpw6BbQcvJ3Atk3w:-NSHjnrU7UPqCj96CBva:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp-tests/JsonUtils/MessageConverter.cs#L7)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Sure - In C++ I found it super helpful to keep unit tests that match the production code in identically named files in a parallel structure.  That way it was clear where to look if we wanted to run code that was intended for specific production code.  If we're careful with test class names (e.g., just append `Tests` at the end) it isn't really that different.

I'll make this adjustment.
</blockquote></details>

Done
___
*[`c-sharp-tests/JsonUtils/MessageConverter.cs` line 49 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEarKi8Tr2nDXsestl:-NSHjpqF392vpgsDooNk:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp-tests/JsonUtils/MessageConverter.cs#L49)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Never seen those best practices before, but this all makes sense.  I'll make the adjustments.
</blockquote></details>

Done
___
*[`c-sharp-tests/MessageHandlers/MessageHandlerEvent.cs` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE_YJA12n2g4WWGdDl:-NSHjStf82qhRRTSQ-T-:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp-tests/MessageHandlers/MessageHandlerEvent.cs#L6)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Sure, same as earlier comments - I'll make the change.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-04-05 18:59 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: 27 of 29 files reviewed, 16 unresolved discussions (waiting on @FoolRunning, @irahopkinson, and @tjcouch-sil)

___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBxO8dE5wmQ1jUAyoY:-NSHk4FmDoCgOrxtZ5SL:bs0xi5n) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L51)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I see, now. It's because ``MessageEvent`` is still considered a ``Message`` object, so you need to make sure it derives from the correct type so it can be included in the correct ``Dictionary``. That might deserve a comment somewhere in this method.
Or, maybe it should be done differently through interfaces? (i.e. have message instances and message events derive from completely different interfaces instead of relying on the base class?)
Any thoughts?
</blockquote></details>

Because of the tie-ins with JSON deserialization and because C# doesn't allow inheriting from multiple classes, I'm not sure of a clearly better approach.  If we go with purely interfaces and not inheritance that is going to introduce code duplication between the message types.  Also technically these events are messages in that all message share the same low-level properties.  So events ought to implement `IMessage`, and we'd be back in the same boat.

I haven't thought of a better way to do what I've got here.  I don't think this is bad per se, and if you follow the pattern you don't have to dig into it and understand the details.  But yes, there is some complexity here.  I will try to add better comments unless we come up with a different approach altogether.


<!-- Sent from Reviewable.io -->

2023-04-05 21:11 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: 27 of 29 files reviewed, 16 unresolved discussions (waiting on @FoolRunning, @irahopkinson, and @tjcouch-sil)

___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 118 at r3](https://reviewable.io/reviews/paranext/paranext-core/124#-NSHXnAh3SpRb4K2s86s:-NSHrVpg6lQba1pXjojA:b-73i8lw) ([raw file](https://github.com/paranext/paranext-core/blob/b481041ac7ffd1e7f50f99012ab8a58df881a440/c-sharp/JsonUtils/MessageConverter.cs#L118)):*
From the [C# language reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#passing-structure-type-variables-by-reference):
> When you pass a structure-type variable to a method as an argument or return a structure-type value from a method, the whole instance of a structure type is copied.

There is nothing in the language reference about inlining breaking this behavior.  Other searches in StackOverflow suggest that inlining is not possible when struct arguments are part of the signature.  The discussions are several years old, but still, if the language spec says they get copied I would trust that without second guessing.
___
*[`c-sharp/MessageHandlers/MessageHandlerEvent.cs` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCLhs6ECPVfKe-ltPL:-NSHwa379gsoXHZO2aOZ:bbe9r0e) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerEvent.cs#L22)):*
> I think it would be a bad design if we had more than one handler inside the C# that handled a given event from the PAPI.

To me, it seems too early to make that declaration.  You've thought about this more than me, but I've found it's better to not make too many assumptions early in a project about how all the code will work exactly.  The normal use case very well might be a single subscriber.  The high level idea of a one way information stream doesn't naturally say "this should only go to 1 receiver," though, even just within C#.
___
*[`c-sharp/MessageHandlers/MessageHandlerEvent.cs` line 70 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSC-2_r1sC4wkif24dZ:-NSI0GUy8pqrJ6OGbFI2:b-sb1765) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerEvent.cs#L70)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

What I was trying to say, is that without the lock, some other thread could be running a register call and it could be inside the lock, but in between the two calls to the Dictionary and then this code here runs. Right now, the way the code currently is, I don't think that's a problem, but in the future, if something else was done in the lock to the Dictionary values (as an extreme example, maybe a new registration required all values in the Dictionary to be removed before the new ones were added back in), then this code here could get the Dictionary while in that in-between state since it's not inside a lock. Yes, the dictionary itself will be perfectly fine, but the code here will not run correctly because the information in the Dictionary was in the process of being changed.
Thus, I think it would be best if the lock was put around this call - which then makes it not need to be a *concurrent* dictionary.

If that's still not clear, feel free to talk on Discord.
</blockquote></details>

I think I understand what you're saying.  I do think the code works fine as-is, as you say, but it does add potential fragility for future maintainers.  We probably don't need the perf benefits of avoiding an uncontested lock which I expect to be the normal case, so it isn't that big of a deal.


<!-- Sent from Reviewable.io -->

2023-04-05 22:50 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: 23 of 29 files reviewed, 16 unresolved discussions (waiting on @FoolRunning, @irahopkinson, and @tjcouch-sil)

___
*[`c-sharp/MessageHandlers/MessageHandlerEvent.cs` line 70 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSC-2_r1sC4wkif24dZ:-NSIarjzBhdqI1dOn2RZ:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerEvent.cs#L70)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I think I understand what you're saying.  I do think the code works fine as-is, as you say, but it does add potential fragility for future maintainers.  We probably don't need the perf benefits of avoiding an uncontested lock which I expect to be the normal case, so it isn't that big of a deal.
</blockquote></details>

Done
___
*[`c-sharp-tests/c-sharp-tests.csproj` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEh5-97SSmoRhol7VS:-NSIax1I3obpH2sTAcAV:b-q9qmaw) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp-tests/c-sharp-tests.csproj#L15)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I did some reading, and xunit seemed to be a slightly better choice from what I could tell as long as we didn't have any other reason to steer us one way or another.  I don't feel strongly about it and am happy to change if we want to use nunit instead.
</blockquote></details>

Switched to `nunit` to be more in line with other SIL projects.  The degree to which `xunit` is arguably better is probably negated and more by not being standard.


<!-- Sent from Reviewable.io -->

2023-04-05 23:48 UTC, irahopkinson requested changes
Looking good, just need valid json and I'm happy.

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124#-:-NSInIwm4lalGUFNpkFd:bgma1v7)* status: all files reviewed, 11 unresolved discussions (waiting on @FoolRunning and @lyonsil)

___
*[`.vscode/extensions.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE2pXgAwYyNHpIYNi8:-NSIbcn34iao-p1XujYy:b4veaew) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/.vscode/extensions.json#L9)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Done - yes, good idea.
</blockquote></details>

Great. It's now missing an ending comma. Saving in VS Code would auto format it to remove the last dangling comma as well to make it valid JSON.
___
*[`.vscode/settings.json` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE2bfTDObs2Vq_sWrS:-NSIc8S8CHNlVT7FQ5Yg:bcvoq1o) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/.vscode/settings.json#L2)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Isn't it already in alphabetical order here?
</blockquote></details>

haha, yes, sorry,  'd' does come before 'e'.
___
*[`c-sharp/AssemblyInfo.cs` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE47DX3MkhAYVocE-P:-NSIcWOu5RXYMEbT2Ukp:b-a1j2s7) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/AssemblyInfo.cs#L3)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

In my previous experience, it seemed better to put unit tests in a separate assembly than putting them in the same assembly.  There is some [discussion about it here](https://stackoverflow.com/questions/347156/do-you-put-unit-tests-in-same-project-or-another-project) that highlight some of the same reasons I was thinking about.  Having said that, [there is an answer](https://stackoverflow.com/a/56646051) lower down that covers some ways to combine them together if the group prefers that approach.  It will make the project more complex, but perhaps that is better than 2 projects.  I'm open for discussion on this point for sure.
</blockquote></details>

We definitely don't want to complicate the setup. I was just trying to avoid having another folder in our repo root. Moving the existing `c-sharp` to `c-sharp/src` and `c-sharp-tests` to `c-sharp/tests` would do that but my aversion to too much in the root might just be me. Unless others think so too we can leave it as is for this PR.
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 102 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEJuoz3uz5MvdnVWO_:-NSIez3jAPBbiSX_GEwU:b-x9344v) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L102)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I don't see how `messageDataType` could be null here.  We threw above if `s_messageTypeMap` didn't have a mapping to the right message type.  If the mapping exists, then the value from the dictionary will not be null.  The only way that variable could be null is if the dictionary didn't have any value, but we already threw if that was the case.

Am I missing something that you see?
</blockquote></details>

Doesn't `out Type?` on L92 indicate that `eventMessageDataType` could be _undefined_? Oh wait, but then the `TryGetValue` would return false and we wouldn't assign it. Sorry, my mistake.
___
*[`c-sharp/Messages/EventType.cs` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEQVTCE6jgvybdN--C:-NSIgG2T8W98e_YgIAVn:b-hgaojp) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/Messages/EventType.cs#L7)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

That probably requires some input from @tjcouch-sil .  Event types are scattered around in the TS code form what I could tell unlike message types.  If we agree on where events should live in TS code I can certainly add comments/pointers here.
</blockquote></details>

Gotcha, out of scope for this PR.
___
*[`c-sharp-tests/JsonUtils/MessageConverter.cs` line 49 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEarKi8Tr2nDXsestl:-NSIhxdL1XVUv9j-sG9s:b-zhn10x) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp-tests/JsonUtils/MessageConverter.cs#L49)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Done
</blockquote></details>

Nice job on the change and thanks for the link. I've added it to our [guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide#c-specific-guidelines).


<!-- Sent from Reviewable.io -->

2023-04-06 14:01 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: 28 of 30 files reviewed, 10 unresolved discussions (waiting on @FoolRunning and @irahopkinson)

___
*[`.vscode/extensions.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE2pXgAwYyNHpIYNi8:-NSLplznDG9lpGlmLuOW:b5sajpb) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/.vscode/extensions.json#L9)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Great. It's now missing an ending comma. Saving in VS Code would auto format it to remove the last dangling comma as well to make it valid JSON.
</blockquote></details>

oops - fixed now
___
*[`c-sharp/AssemblyInfo.cs` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE47DX3MkhAYVocE-P:-NSLqN296T3inDB0uA__:b-hw1hp1) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/AssemblyInfo.cs#L3)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

We definitely don't want to complicate the setup. I was just trying to avoid having another folder in our repo root. Moving the existing `c-sharp` to `c-sharp/src` and `c-sharp-tests` to `c-sharp/tests` would do that but my aversion to too much in the root might just be me. Unless others think so too we can leave it as is for this PR.
</blockquote></details>

I think the idea of `c-sharp/src` and `c-sharp/tests` being separate is a good one.  It's not a big deal, but it is a little cleaner.

This might be a nice follow up PR as it will have so many moves and small text adjustments just for the renaming.
___
*[`c-sharp-tests/c-sharp-tests.csproj` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSEBIwsDgOpOK2Vw_D0:-NSLr4ytE_ZyxvQGIZDv:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp-tests/c-sharp-tests.csproj#L1)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I will work on this.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-04-06 15:41 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: 21 of 30 files reviewed, 10 unresolved discussions (waiting on @FoolRunning, @irahopkinson, and @lyonsil)

___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBxO8dE5wmQ1jUAyoY:-NSMCa3X-nF7LypaLls9:b8fnvj) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L51)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Because of the tie-ins with JSON deserialization and because C# doesn't allow inheriting from multiple classes, I'm not sure of a clearly better approach.  If we go with purely interfaces and not inheritance that is going to introduce code duplication between the message types.  Also technically these events are messages in that all message share the same low-level properties.  So events ought to implement `IMessage`, and we'd be back in the same boat.

I haven't thought of a better way to do what I've got here.  I don't think this is bad per se, and if you follow the pattern you don't have to dig into it and understand the details.  But yes, there is some complexity here.  I will try to add better comments unless we come up with a different approach altogether.
</blockquote></details>

After some more thought I still couldn't come up with a better idea, so I added some detailed comments in this file to help future readers.  If you have a better idea after some thought let me know.
___
*[`c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs` line 63 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCN58GBbje1X0_NDV-:-NSMD5k05rtIY0WCs1Oa:b9z8zwt) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs#L63)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

If we only need a single handler, would it make more sense to just change the interface from `IEnumerable<Message>?` to just `Message?`?  That is how it was before this PR.
</blockquote></details>

I changed the `IMessageHandler` interface to drop nullability and changed all the implementing classes to use `yield` as you suggest.  I also changed the consuming classes to remove the null checks.  It did simplify the code in most places which was nice.


<!-- Sent from Reviewable.io -->

2023-04-06 17:37 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: 20 of 30 files reviewed, 9 unresolved discussions (waiting on @FoolRunning, @irahopkinson, and @lyonsil)

___
*[`c-sharp/AssemblyInfo.cs` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSE47DX3MkhAYVocE-P:-NSMcrGl5WhYFiqn1PSI:b-56e2ql) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/AssemblyInfo.cs#L3)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I think the idea of `c-sharp/src` and `c-sharp/tests` being separate is a good one.  It's not a big deal, but it is a little cleaner.

This might be a nice follow up PR as it will have so many moves and small text adjustments just for the renaming.
</blockquote></details>

Created https://github.com/paranext/paranext-core/issues/138 to track this as a separate issue.


<!-- Sent from Reviewable.io -->

2023-04-06 18:02 UTC, lyonsil reviewed
@FoolRunning I dug more into the .NET websocket implementation based on your previous comments/questions.  There isn't a problem sending and receiving at the same time as I said ought to be true for reasonable network socket implementations.  However, there is a problem with 2+ threads sending at the same time which is disappointing.  (It would also be a problem to have 2+ threads receiving at the same time, but our code doesn't do that.)  To avoid expanding this PR beyond the intention of event handling, I opened https://github.com/paranext/paranext-core/issues/137 as a follow up to deal with the problem of multiple senders.  We shouldn't have problems with this right away, but we should get back to it sooner rather than later.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124#-:-NSMePHN6DgnevyG3bkW:b6op20b)* status: 20 of 30 files reviewed, 9 unresolved discussions (waiting on @FoolRunning, @irahopkinson, and @lyonsil)



<!-- Sent from Reviewable.io -->

2023-04-06 20:44 UTC, irahopkinson approved these changes
I really like the removal of nullable. Although I wouldn't have know to suggest that, I do like the results in the simpler code.

Yeh, for C# GHA tests. :clap: 

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124#-:-NSNI1mJ7YCnvWU1LWO0:bnkjyxe)* status: all files reviewed, 9 unresolved discussions (waiting on @FoolRunning and @lyonsil)

___
*[`.github/workflows/test.yml` line 54 at r7](https://reviewable.io/reviews/paranext/paranext-core/124#-NSNHDfM818eu700WcUF:-NSNHDfM818eu700WcUG:b-f8dxh0) ([raw file](https://github.com/paranext/paranext-core/blob/7b93cfbe4f6630a6c308f2fa720f34d6f7c5486b/.github/workflows/test.yml#L54)):*
> ```YAML
>         run: npm run build:data-release
> 
>       - name: run dotnet unit tests
> ```

nit: I would put these after the format check since they will get bigger and bigger but the check won't likely take much more time - that way we would fail earlier.

So good to see these tests running in GHA, thanks.


<!-- Sent from Reviewable.io -->

2023-04-10 13:45 UTC, FoolRunning approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/124)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSBxO8dE5wmQ1jUAyoY:-NSfMIvP8oqCqcj2ykJo:byx6ckw) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/JsonUtils/MessageConverter.cs#L51)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

After some more thought I still couldn't come up with a better idea, so I added some detailed comments in this file to help future readers.  If you have a better idea after some thought let me know.
</blockquote></details>

I was meaning having interfaces in addition to the existing base classes where the interfaces would only be on the outer-most classes in the hierarchy. Either way, I think it's fine for now. We can always change it later since it's just an implementation detail of the C#.
___
*[`c-sharp/JsonUtils/MessageConverter.cs` line 118 at r3](https://reviewable.io/reviews/paranext/paranext-core/124#-NSHXnAh3SpRb4K2s86s:-NSfMok_6OuRXdo7zvTh:bt5cgqp) ([raw file](https://github.com/paranext/paranext-core/blob/b481041ac7ffd1e7f50f99012ab8a58df881a440/c-sharp/JsonUtils/MessageConverter.cs#L118)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

From the [C# language reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#passing-structure-type-variables-by-reference):
> When you pass a structure-type variable to a method as an argument or return a structure-type value from a method, the whole instance of a structure type is copied.

There is nothing in the language reference about inlining breaking this behavior.  Other searches in StackOverflow suggest that inlining is not possible when struct arguments are part of the signature.  The discussions are several years old, but still, if the language spec says they get copied I would trust that without second guessing.

</blockquote></details>

Good enough for me
___
*[`c-sharp/MessageHandlers/MessageHandlerEvent.cs` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCLhs6ECPVfKe-ltPL:-NSfN62CB113INx_qB84:b2pat84) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerEvent.cs#L22)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

> I think it would be a bad design if we had more than one handler inside the C# that handled a given event from the PAPI.

To me, it seems too early to make that declaration.  You've thought about this more than me, but I've found it's better to not make too many assumptions early in a project about how all the code will work exactly.  The normal use case very well might be a single subscriber.  The high level idea of a one way information stream doesn't naturally say "this should only go to 1 receiver," though, even just within C#.
</blockquote></details>

Yeah, that is a good point. Let's just leave it for now. I'm not thrilled with the complications it introduces to the code, but it's fine for now.
___
*[`c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs` line 63 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCN58GBbje1X0_NDV-:-NSfOyPyESSqFHx-fIMT:b9ndxh7) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs#L63)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I changed the `IMessageHandler` interface to drop nullability and changed all the implementing classes to use `yield` as you suggest.  I also changed the consuming classes to remove the null checks.  It did simplify the code in most places which was nice.
</blockquote></details>

I like these changes. Thanks for doing that.
___
*[`c-sharp/Messages/MessageEvent.cs` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCNt_87mXHMaD_VfS0:-NSfO7fPDihpuUX_zs0R:by7yvcn) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/Messages/MessageEvent.cs#L16)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Normally I agree with you.  For JSON in particular there is a nasty collision between `Newtonsoft.Json` and `Text.Json`.  They share nearly identical types, and I lost 30-60 minutes in this code trying to debug a problem that was caused because VS decided I meant Newtonsoft Json here instead of System.Text.Json.  I was trying to be SUPER explicit about which type I meant to avoid weird shenanigans.
</blockquote></details>

Ah. I didn't think about that.
___
*[`c-sharp/Messages/MessageEventClientConnect.cs` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSCNbPU0D5IWSijKjuF:-NSfOBGm1Q1LXzfUslkn:b-4lntql) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/Messages/MessageEventClientConnect.cs#L10)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

The code fails to compile with [error CS0120](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0120) if you don't prepend this with `Messages`.  It thinks I'm talking about the property exposed in `MessageEvent.cs` named `EventType` instead of the class `Messages.EventType`.  I didn't provide the full typename of `Paranext.DataProvider.Messages.EventType` because the first two parts weren't needed, only the `Messages` portion to distinguish between the two.
</blockquote></details>

Ah. I didn't think about that.
___
*[`c-sharp/Messages/MessageEventClientConnect.cs` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/124#-NSGVhzZ6dGsT5LcZRq_:-NSfOGg_0iEGfmhkJ3Iz:by7yvcn) ([raw file](https://github.com/paranext/paranext-core/blob/964d69c72f1ba126ffedfcead391ae9dae9b3591/c-sharp/Messages/MessageEventClientConnect.cs#L13)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

The code fails to compile with [error CS0120](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0120) if you don't prepend this with `Messages`.  It thinks I'm talking about the property exposed in `MessageEvent.cs` named `EventType` instead of the class `Messages.EventType`.  I didn't provide the full typename of `Paranext.DataProvider.Messages.EventType` because the first two parts weren't needed, only the `Messages` portion to distinguish between the two.
</blockquote></details>

Ah. I didn't think about that.


<!-- Sent from Reviewable.io -->

2023-04-10 14:07 UTC, merged