Select Scripture when you click a check result
paranext/paranext-core pull request #1345
Opened 2024-11-25 18:20 UTC by tjcouch-sil

- Added `WebViewController`s for Scripture editors
  - One method `selectRange` that you pass USJ or USFM range specification, and it will select that location in the Scripture
- Converted Scripture editor `WebViewProvider` to `WebViewFactory`
- Set up check results list to call that web view controller on the editor from which it was opened

Known issues:
- Location offsets don't get converted quite properly from USFM to USJ
- Selection is really faint and hard to see. Also you can't really click into the editor without changing the selection

2024-11-25 19:31 UTC, lyonsil requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1345)* status: all files reviewed, 8 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 218 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZfx94A2iU-eASawBi:-OCZfx94A2iU-eASawBj:b-i2mw5d) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L218)):*
> ```XML
>           if (!selectedRow || !editorWebViewController) return;
> 
>           logger.info(JSON.stringify(selectedRow));
> ```

I'm guessing this was accidentally left in from debugging. This should probably at least move to `logger.debug` and add some more context if we're going to leave it in.
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 237 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZgRrB43-Am2BLhEI_:-OCZgRrCDuveAxx2MtpH:bnxn84n) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L237)):*
> ```XML
>                   offset: startOffset,
>                 };
>             let end: ScriptureLocation = { ...start, offset: start.offset ?? 0 };
> ```

 @irahopkinson We probably need some clarification on the right way to specify a `SelectionRange` if the end isn't known/specified. It would be nice if the default was to automatically select to the end of verse, but either way I can see us potentially ending up with something unexpected/not useful if offsets are identical in the start and end of the range selection.
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 105 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZlLH3-wgB8JvZUGOk:-OCZlLH3-wgB8JvZUGOl:b-inqnt3) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L105)):*
> ```XML
>       switch (method) {
>         case 'selectRange':
>           logger.info(`selectRange targetScrRef ${serialize(targetScrRef)} ${serialize(range)}`);
> ```

Another case that should be `logger.debug`?
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZlTSs2vYWoRLvXA_m:-OCZlTSt3bEAr3Vw-NsI:bp78wd2) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L108)):*
> ```XML
> 
>           if (compareScrRefs(scrRef, targetScrRef) !== 0) {
>             // Need to update scr ref. Give it some time before setting the range
> ```

What does `give it some time` mean here exactly? Should we be awaiting something?
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZm_Pj6baGljLU6F0i:-OCZm_Pk9YgkW_oIYkp8:b-jxegex) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L2)):*
> ```XML
> declare module 'platform-scripture-editor' {
>   import type { SelectionRange } from 'shared-react/annotation/selection.model';
> ```

Looks like `ts` is unhappy about these new type references for some reaosn
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZmn_y80LA797SblTE:-OCZmn_y80LA797SblTF:b-hw6efv) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L19)):*
> ```XML
> 
>   /**
>    * Position in Scripture. See {@link CheckLocation} for more information as this is mostly a
> ```

I'm wondering if we need to have a cleanup ticket where we settle on exactly where we use `ScriptureReference` and where we use `VerseRef`. They seem redundant, and I know we've used `VerseRef` back and forth with the .NET process, so I'm not sure what the cross-process concern is exactly.
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZn7uH1AI-0iLIqrhb:-OCZn7uH1AI-0iLIqrhc:b5xj91o) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L25)):*
> ```XML
>    * Also added `bookNum` and `chapterNum` to the `jsonPath` result
>    */
>   export type ScriptureLocation =
> ```

I wonder if we ought to define a type like this in `platform-scripture` and have checks use it instead of defining a separate type.
___
*[`extensions/src/platform-scripture-editor/src/main.ts` line 175 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZjwvh5O9xTHo9de4g:-OCZjwvh5O9xTHo9de4h:b-euxpkb) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/main.ts#L175)):*
> ```XML
>       async selectRange(range) {
>         try {
>           logger.info(
> ```

Similar to my other comment, I'm guessing we don't want to leave this as-is in production code. Maybe change to `logger.debug`?


<!-- Sent from Reviewable.io -->

2024-11-26 17:23 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1345)* status: 2 of 6 files reviewed, 8 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 218 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZfx94A2iU-eASawBi:-OCdQ3m9APSZTKL1ubsS:bgrujwg) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L218)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm guessing this was accidentally left in from debugging. This should probably at least move to `logger.debug` and add some more context if we're going to leave it in.
</blockquote></details>

Removed - thanks!
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 237 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZgRrB43-Am2BLhEI_:-OCdQEBH10OulhtKrl49:buthzwf) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L237)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

@irahopkinson We probably need some clarification on the right way to specify a `SelectionRange` if the end isn't known/specified. It would be nice if the default was to automatically select to the end of verse, but either way I can see us potentially ending up with something unexpected/not useful if offsets are identical in the start and end of the range selection.
</blockquote></details>

FYI I believe the built-in browser range always has a start and end. They have the same node and offset if there is nothing selected. Feels a bit less ambiguous to me.

Side note, the browser selection has anchor and focus instead of start and end so it is directional. Interesting

[Selection - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Selection)
[Range - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Range)
___
*[`extensions/src/platform-scripture-editor/src/main.ts` line 175 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZjwvh5O9xTHo9de4g:-OCdRmdp576u5lY1HDgS:bcr5s2o) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/main.ts#L175)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Similar to my other comment, I'm guessing we don't want to leave this as-is in production code. Maybe change to `logger.debug`?
</blockquote></details>

Got it, thanks!
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 105 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZlLH3-wgB8JvZUGOk:-OCdS-oM1ktgpr-s8aBz:bcr5s2o) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L105)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Another case that should be `logger.debug`?
</blockquote></details>

Got it, thanks!
___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZlTSs2vYWoRLvXA_m:-OCdSN1G711x8PrSnYvk:b-d8cy94) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L108)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

What does `give it some time` mean here exactly? Should we be awaiting something?
</blockquote></details>

Updated! Hopefully that clarifies things :)
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZm_Pj6baGljLU6F0i:-OCdSu_JBBZdis5Q0_rF:bv96yyt) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L2)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Looks like `ts` is unhappy about these new type references for some reaosn
</blockquote></details>

Yep, fixed. Thanks!
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZmn_y80LA797SblTE:-OCdSzrT4oKIw-iODUie:bbpoe87) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L19)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm wondering if we need to have a cleanup ticket where we settle on exactly where we use `ScriptureReference` and where we use `VerseRef`. They seem redundant, and I know we've used `VerseRef` back and forth with the .NET process, so I'm not sure what the cross-process concern is exactly.
</blockquote></details>

`VerseRef` is a class, and classes don't rehydrate into classes across processes but just stay as an object that has whatever the class's `toJSON` returns. We could possibly craft into our `serialize` and `deserialize` a way to rehydrate specific hard-coded classes like `VerseRef`; I made an issue about that somewhere a long time ago.

`ScriptureReference` is a simple object with the three specific properties. No fanciness needed. I *think* I remember that C#'s `VerseRef` can deserialize `ScriptureReference`s, but I dunno about serializing into `ScriptureReference`s; I just don't remember if we write those properties or not.

Anyway, probably wouldn't hurt to make an issue for considering how to clean these up.
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZn7uH1AI-0iLIqrhb:-OCdUF-p8C0LTYLEnboQ:bovvkz8) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L25)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I wonder if we ought to define a type like this in `platform-scripture` and have checks use it instead of defining a separate type.
</blockquote></details>

I would be interested in that! I figured maybe we could reconsider all the checks types at once sometime in a follow-up issue for fixing the offsets and such. Does that seem reasonable, or do you want to do something sooner?

Maybe we could add it to this issue https://github.com/paranext/paranext-core/issues/1215 ?


<!-- Sent from Reviewable.io -->

2024-11-26 17:52 UTC, lyonsil reviewed
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1345)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZlTSs2vYWoRLvXA_m:-OCdZieGBmww-LxNbxST:b-af183f) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L108)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Updated! Hopefully that clarifies things :)
</blockquote></details>

Yep, thanks!
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZmn_y80LA797SblTE:-OCd_1zABpg7x8Me6auT:b-275xom) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

`VerseRef` is a class, and classes don't rehydrate into classes across processes but just stay as an object that has whatever the class's `toJSON` returns. We could possibly craft into our `serialize` and `deserialize` a way to rehydrate specific hard-coded classes like `VerseRef`; I made an issue about that somewhere a long time ago.

`ScriptureReference` is a simple object with the three specific properties. No fanciness needed. I *think* I remember that C#'s `VerseRef` can deserialize `ScriptureReference`s, but I dunno about serializing into `ScriptureReference`s; I just don't remember if we write those properties or not.

Anyway, probably wouldn't hurt to make an issue for considering how to clean these up.
</blockquote></details>

Interestingly I realized yesterday afternoon that the rehydration problem with `VerseRef` is what is causing https://github.com/paranext/paranext-core/issues/1171. I should have a change to `deserialize` coming up shortly for that purpose.

Having said this, it still seems error prone to have two types that mean basically the same thing but aren't the same. When should we use `VerseRef` and when should we use `ScriptureReference`? It seems like we're going to end up with a mishmash in the end. It's our own constructed version of `undefined` and `null`.
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZn7uH1AI-0iLIqrhb:-OCdaJGK7lHuZI6g3q3Y:boocih4) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L25)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I would be interested in that! I figured maybe we could reconsider all the checks types at once sometime in a follow-up issue for fixing the offsets and such. Does that seem reasonable, or do you want to do something sooner?

Maybe we could add it to this issue https://github.com/paranext/paranext-core/issues/1215 ?
</blockquote></details>

I updated the description of that issue to include looking at similar types.


<!-- Sent from Reviewable.io -->

2024-11-26 17:54 UTC, lyonsil approved these changes
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1345)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 237 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZgRrB43-Am2BLhEI_:-OCdasLGBCT1OcxXwbyd:bf6awmb) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L237)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

FYI I believe the built-in browser range always has a start and end. They have the same node and offset if there is nothing selected. Feels a bit less ambiguous to me.

Side note, the browser selection has anchor and focus instead of start and end so it is directional. Interesting

[Selection - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Selection)
[Range - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Range)
</blockquote></details>

It would be nice to get @irahopkinson 's thoughts here before merging if possible.


<!-- Sent from Reviewable.io -->

2024-11-26 18:15 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1345)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1345#-OCZmn_y80LA797SblTE:-OCdfCvUB6J1aNCNfDmq:b-kwb8sm) ([raw file](https://github.com/paranext/paranext-core/blob/1454d82c1a49b907ee013bf4a5500dbd009993af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L19)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Interestingly I realized yesterday afternoon that the rehydration problem with `VerseRef` is what is causing https://github.com/paranext/paranext-core/issues/1171. I should have a change to `deserialize` coming up shortly for that purpose.

Having said this, it still seems error prone to have two types that mean basically the same thing but aren't the same. When should we use `VerseRef` and when should we use `ScriptureReference`? It seems like we're going to end up with a mishmash in the end. It's our own constructed version of `undefined` and `null`.
</blockquote></details>

Interesting!

Here's the issue I was talking about - apparently not about classes in general but about one specific class that doesn't even exist yet XD https://github.com/paranext/paranext-core/issues/56

Yes, agreed; we already have the angst between these two types. It would be nice to have it tightened up.


<!-- Sent from Reviewable.io -->

2024-11-26 22:19 UTC, lyonsil approved these changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1345)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-26 22:19 UTC, merged