Revise Settings Dialog with New UX Design
paranext/paranext-core pull request #1354
Opened 2024-11-26 21:58 UTC by jolierabideau

Problems still to fix:
- If I open the settings dialog, leave the settings dialog open, quit the app, and then `npm start` ... The projects don't load in the ComboBox. With DEV_NOISY=true, it will show only the Hello World projects. With DEV_NOISY=false it will show "No options"
- With DEV_NOISY=true, the project interfaces are not being filtered correctly. The hello world project settings group shows even when you select a non-hello world project.

-----

This PR satisfies #1213 

I implemented sidebar hierarchy and styled the search bar based on [Ian's filtering settings Figma](https://www.figma.com/design/zJWrApZ8AyPGxNHdndbkTz/Settings-Dialog-%23434?node-id=762-3221&node-type=canvas&t=M1qTpsYTitrJFoGm-0). All of one extension's setting groups are on the same page in shadcn `Card`s based on the [Combined Settings - v0](https://b_tyfkysg0kgm.v0.build/). 

![Screenshot 2024-11-26 at 2 54 45 PM](https://github.com/user-attachments/assets/5ff1f11a-4124-4666-b7ec-f1b7d8cc5011)

I added support for receiving a project id and only showing settings for that project.

![Screenshot 2024-11-26 at 11 53 18 AM](https://github.com/user-attachments/assets/99e68a0f-a750-461c-9e3e-e464e74165e7)

Other misc changes:
- Updated localized strings
- Created a `SettingsSidebarContentSearch` component, that is similar to the `TabNavigationContentSearch` component we were using previously, except it uses a Shadcn `Sidebar` for navigation, and has updated styling. I did not remove the previous component in case that tab navigation is useful somewhere else.
- Created the `SettingsSidebar` component with extension list and project `ComboBox`.
- Added a second className prop to `ComboBox` - I needed to add a style to the `Popover` inside of the `ComboBox`, but the className only applied to the trigger, so I added a `popoverClassName` and `buttonClassName`. And updated the uses.
- I added a className prop to the `SearchBar` 
- I added a basic Sidebar Example to the preview
- I removed the second settings tab, so there is only one tab rendering settings with an optional projectId passed in.
- Per the confusion around setting language, I removed the word "User" in these settings components, I replaced it with "Other", which should probably change but I couldn't decide what else to call them. 
- Changed the `CheckBox` to `Switch` in settings

2024-12-02 18:29 UTC, lyonsil requested changes
Lots of good work here! I have several questions to make sure I'm following everything properly. Also, I'm not at all familiar with what we're doing with Tailwind styling, so I can't comment on anything there. If that needs a closer look, please ask someone who is familiar with it.

> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354#-:-OD7cHgy7N88SLWxEfqW:byl952u)* status: all files reviewed, 15 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar.component.tsx` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7IuW03cKLdpKMd2ie:-OD7IuW03cKLdpKMd2if:bx79tsl) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar.component.tsx#L20)):*
> ```XML
> };
> 
> export type ProjectOptions = { projectId: string; projectName: string };
> ```

There aren't really any "options" here. I would like something like `ProjectInfo` would make more sense, but it's not a huge deal.
___
*[`lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar.component.tsx` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7FuuH-nA02EvfnnO9:-OD7FuuH-nA02EvfnnOA:b-ytvmq1) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar.component.tsx#L45)):*
> ```XML
> 
>   /** Placeholder for the button */
>   buttonPlaceholder: string;
> ```

What's the point of a placeholder here? I would think we'd either put a button in or not have a placeholder.
___
*[`lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar.component.tsx` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7Jccv-uv-5UKFSb7z:-OD7Jccv-uv-5UKFSb8-:b-u4zjty) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar.component.tsx#L99)):*
> ```XML
>                       { 'tw-bg-white tw-text-gray-900 tw-shadow-sm': getIsActive(label) },
>                     )}
>                     onClick={() => handleSelectItem(label, undefined)}
> ```

You could change `handleSelectItem(label, undefined)` to just `handleSelectItem(label)` here since the second argument is optional.
___
*[`lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar-content-search.component.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7FK-F9j1KuH7Tz0rF:-OD7FK-GCws2KUat7u3h:bmwseyd) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar-content-search.component.tsx#L12)):*
> ```XML
> 
>     /** Text direction ltr or rtl */
>     direction?: 'ltr' | 'rtl';
> ```

Why do we need to explicitly call this out here as an input parameter? I would have expected this to be derived from either the current UI locale or the language(s) represented in the search string.
___
*[`src/renderer/services/web-view.service-host.ts` line 1439 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7Z4L9-db5k78RicBm:-OD7Z4LAEXU9GOZVl8JX:b-hnigjo) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/src/renderer/services/web-view.service-host.ts#L1439)):*
> ```XML
>       type: 'float',
>       position: 'center',
>       floatSize: { height: 575, width: 950 },
> ```

Where are we getting the size constants?
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sheet.tsx` line 0 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7MVmd3iXxBYJXo8h8:-OD7MVmd3iXxBYJXo8h9:b3tzoa4) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sheet.tsx#L0)):*
I don't do a lot of UI programming, but I'm not sure what a `Sheet` is intended to be along with all the things we're providing for it. I don't see any documentation below, so I'm guessing this is something like a spreadsheet. But then I start wondering what the different is between a sheet, a table, and a grid unless sheets have formulas which I don't see below. I think some guidance docs would be nice to add for people who want to use sheets.
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 21 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7Ni-145HLzb7JLB-i:-OD7Ni-145HLzb7JLB-j:byrfmb4) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L21)):*
> ```XML
> 
> const SIDEBAR_COOKIE_NAME = 'sidebar:state';
> const SIDEBAR_COOKIE_MAX_AGE = 60 * 60 * 24 * 7;
> ```

What happens a week after the max age is set? Does some setting disappear or reset to a default value? I think we've just been saving things directly to `localStorage` instead of using cookies. @tjcouch-sil do you see concerns with mixing in cookies with our UI?

Where does the cookie get read? I only see us writing it, not reading it.

If we do need cookies for some reason, I guess I would expect them to never expire (or set an expiration to something like 2^31 which would have the same effect).
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 98 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7TmNX7BqsdMD1WdCG:-OD7TmNX7BqsdMD1WdCH:b-rtjigh) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L98)):*
> ```XML
>     React.useEffect(() => {
>       const handleKeyDown = (event: KeyboardEvent) => {
>         if (event.key === SIDEBAR_KEYBOARD_SHORTCUT && (event.metaKey || event.ctrlKey)) {
> ```

Was this specified by UX? Just thinking about if we are trying to create equivalent shortcut keys for PT9 and/or if we should be writing down shortcut keys anywhere that we are using for different things to avoid collisions.
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 152 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7VOAl9okpgsV-qcCn:-OD7VOAl9okpgsV-qcCo:b-fc2m19) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L152)):*
> ```XML
>   },
> );
> SidebarProvider.displayName = 'SidebarProvider';
> ```

Does this actually get displayed somewhere? If not, what's the point of it? The same goes for cases below where you set the `displayName` property.
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 279 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7WB2I1lBP5OS0ajfG:-OD7WB2I1lBP5OS0ajfH:buxnsc9) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L279)):*
> ```XML
>     >
>       <PanelLeft />
>       <span className="tw-sr-only">Toggle Sidebar</span>
> ```

Does this need to be localized? I don't see where it gets drawn.
___
*[`lib/platform-bible-react/src/components/hooks/use-mobile.tsx` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7LMZz8-qc2upopjym:-OD7LMZz8-qc2upopjyn:b-btihu6) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/hooks/use-mobile.tsx#L3)):*
> ```XML
> import * as React from 'react';
> 
> const MOBILE_ [...]

2024-12-02 19:26 UTC, jolierabideau reviewed
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354#-:-OD7pcfH-ECrF056v8_o:b-9qdoz3)* status: all files reviewed, 12 unresolved discussions (waiting on @lyonsil and @tj)

___
*[`lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar-content-search.component.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7FK-F9j1KuH7Tz0rF:-OD7gWI3EO7L8tH4tpVf:bhwjter) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar-content-search.component.tsx#L12)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Why do we need to explicitly call this out here as an input parameter? I would have expected this to be derived from either the current UI locale or the language(s) represented in the search string.
</blockquote></details>

I copied the `TabNavigationContentSearch` component to start this one, previously I added `direction` to the `TabNavigationContentSearch` component because I used it directly in the preview, and there we pass the selected direction into the components. Since this component isn't in the preview, I can remove it. 
___
*[`lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar.component.tsx` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7FuuH-nA02EvfnnO9:-OD7iK4g-2-kAxVTohk2:bpgknpg) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/advanced/settings-components/settings-sidebar.component.tsx#L45)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

What's the point of a placeholder here? I would think we'd either put a button in or not have a placeholder.
</blockquote></details>

It should be `buttonPlaceholderText`, I am passing a localized string into this prop.
___
*[`lib/platform-bible-react/src/components/basics/search-bar.component.tsx` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7L53uE0_BAzKea86X:-OD7irmE96sgnRPyYArl:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/basics/search-bar.component.tsx#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

All properties should probably have some JSDOC description
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/hooks/use-mobile.tsx` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7LMZz8-qc2upopjym:-OD7ius85pjlFQIQxoaC:b-cc7tsd) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/hooks/use-mobile.tsx#L3)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Where did this constant come from?
</blockquote></details>

When you use the `npx` script to add a Shadcn component, it adds the other component/hook dependencies that it needs. This was one of them. It is used in `shadcn-ui/sidebar.tsx`. This constant came from Shadcn.
___
*[`lib/platform-bible-react/src/components/hooks/use-mobile.tsx` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7LTi--deY9FBTrz-7:-OD7jhS_9XHOK4Oj0T4Z:bkhvev8) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/hooks/use-mobile.tsx#L5)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It would be good to add a return type and a JSDOC-style description to this function. I'm not sure what "mobile" is intended to mean in this context. In the absence of context I would assume it means "running on a smartphone" which I doubt is the intent since we're not targeting smartphone OSes.
</blockquote></details>

You are right, I don't see us using this. It is only used in `shadcn-ui/sidebar.tsx`, and I didn't export it so it can't be accessed outside of PBR. I can remove the use of this hook in `shadcn-ui/sidebar.tsx` and delete the file? 
___
*[`lib/platform-bible-react/src/components/hooks/use-mobile.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7LzE96cNJVBeTNK0I:-OD7l7aO1L34mum8Wc1m:b-dxl180) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/hooks/use-mobile.tsx#L9)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Just curious, what is `mql` in this context? I think I've only ever seen "QL" at the end of an abbreviation when it stands for "query language", but I'm pretty sure that's not the intent here.
</blockquote></details>

Looks like it stands for `MediaQueryList`. https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sheet.tsx` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7MVmd3iXxBYJXo8h8:-OD7lQTg5r2t7L6KxKfk:bbl9c9j) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sheet.tsx#L)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I don't do a lot of UI programming, but I'm not sure what a `Sheet` is intended to be along with all the things we're providing for it. I don't see any documentation below, so I'm guessing this is something like a spreadsheet. But then I start wondering what the different is between a sheet, a table, and a grid unless sheets have formulas which I don't see below. I think some guidance docs would be nice to add for people who want to use sheets.
</blockquote></details>

This is another of the components that the script added as a dependency for `Sidebar`. Shadcn `Sheet` extends the Radix `Dialog` component. The `Sidebar` actually just renders a `Sheet`. I also did not export this component so it cannot be accessed outside of PBR.  
https://ui.shadcn.com/docs/components/sheet
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 21 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7Ni-145HLzb7JLB-i:-OD7mLVWDG3sVUtvDmDD:bi9qv66) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L21)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

What happens a week after the max age is set? Does some setting disappear or reset to a default value? I think we've just been saving things directly to `localStorage` instead of using cookies. @tjcouch-sil do you see concerns with mixing in cookies with our UI?

Where does the cookie get read? I only see us writing it, not reading it.

If we do need cookies for some reason, I guess I would expect them to never expire (or set an expiration to something like 2^31 which would have the same effect).
</blockquote></details>

I am not sure what happens with these cookies. This is more of the code that was generated from Shadcn. I can work on removing this, and seeing if that changes the functionality of the `Sidebar`.
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 98 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7TmNX7BqsdMD1WdCG:-OD7mutx54vUrkvQutNM:b-ia8i04) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L98)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Was this specified by UX? [...]

2024-12-04 15:08 UTC, lyonsil requested changes
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354)* status: all files reviewed, 7 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/basics/search-bar.component.tsx` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7L53uE0_BAzKea86X:-ODHAPuOBSHzSo0hxqb2:b-ondr4b) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/basics/search-bar.component.tsx#L6)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I was talking about `className` since all the other properties of `SearchBarProps` have descriptions. It is good for the types to have docs, too.
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 21 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7Ni-145HLzb7JLB-i:-ODHAgCJB65GmGPrxhii:b-lio93y) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L21)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I am not sure what happens with these cookies. This is more of the code that was generated from Shadcn. I can work on removing this, and seeing if that changes the functionality of the `Sidebar`.
</blockquote></details>

Thanks! I was a bit confused about introducing concepts we haven't been using for any reason.
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 152 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7VOAl9okpgsV-qcCn:-ODHBO684jBB2IKVpxPm:byr8o27) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L152)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

All of the Shadcn-generated components have this. From the little research I did, it appears that React sometimes does not do a good job of inferring the displayName when you use functional components, so setting it explicitly is supposed to help it appear correctly in debugging tools and error messages.
</blockquote></details>

Thanks for digging into this!
___
*[`src/renderer/services/web-view.service-host.ts` line 1439 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7Z4L9-db5k78RicBm:-ODHCT2m6l1MgqZ3r2K4:b7ggriy) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/src/renderer/services/web-view.service-host.ts#L1439)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I meant to change this. I took this from UX's Figma, as I was testing I wanted to render the tab larger. I am not sure what I should change it to?
</blockquote></details>

This is probably a good question for UX.
___
*[`lib/platform-bible-react/src/index.ts` line 46 at r2](https://reviewable.io/reviews/paranext/paranext-core/1354#-ODHCFA34BL5bs5Ten16:-ODHCFA34BL5bs5Ten17:bu73445) ([raw file](https://github.com/paranext/paranext-core/blob/b2b6c78469b5918adda50df30ef3230757a3ff18/lib/platform-bible-react/src/index.ts#L46)):*
> ```XML
>   default as SettingsSidebar,
>   type SettingsSidebarProps,
>   type ProjectInfo as ProjectOptions,
> ```

This might have been done by VSCode. I'm assuming the intent it not to rename this type on the export.


<!-- Sent from Reviewable.io -->

2024-12-04 17:23 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354)* status: 30 of 39 files reviewed, 5 unresolved discussions (waiting on @lyonsil)

___
*[`lib/platform-bible-react/src/index.ts` line 46 at r2](https://reviewable.io/reviews/paranext/paranext-core/1354#-ODHCFA34BL5bs5Ten16:-ODHgdaH5DscvecRFpvR:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/b2b6c78469b5918adda50df30ef3230757a3ff18/lib/platform-bible-react/src/index.ts#L46)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This might have been done by VSCode. I'm assuming the intent it not to rename this type on the export.
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/basics/search-bar.component.tsx` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7L53uE0_BAzKea86X:-ODHehI-1XSDvQl9DSLj:bc6a2vh) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/basics/search-bar.component.tsx#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Sorry, I was talking about `className` since all the other properties of `SearchBarProps` have descriptions. It is good for the types to have docs, too.
</blockquote></details>

Oops! Fixed
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 98 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7TmNX7BqsdMD1WdCG:-ODHeoX06n5MKldhl-ZH:b25mfhy) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L98)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

That's a good thought. I can talk with UX about this.
</blockquote></details>

I have made a note to talk with Sebastian about this in our next components meeting! 
___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 279 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7WB2I1lBP5OS0ajfG:-ODHf36R2660XnOV1-0U:bz4eorl) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L279)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I would say yes, I didn't use the `SidebarTrigger` so I didn't notice this.
</blockquote></details>

This component uses the `sr-only` className, which means this is hidden visually without hiding it from screen readers. I am not sure how best to localize this string, besides adding a prop that we pass into the Shadcn sidebar?  I am curious if I could bring this up with Sebastian as well since there are a few Shadcn components that have text like this, and then come up with an issue to fix all of them with what we decide?
___
*[`src/renderer/services/web-view.service-host.ts` line 1439 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7Z4L9-db5k78RicBm:-ODHgYPuBBxTBk-D8TJW:b-9tnuh3) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/src/renderer/services/web-view.service-host.ts#L1439)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This is probably a good question for UX.
</blockquote></details>

Posted in the UX channel, so hopefully I will have an answer soon


<!-- Sent from Reviewable.io -->

2024-12-04 18:27 UTC, lyonsil approved these changes
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354)* status: all files reviewed, 2 unresolved discussions

___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 279 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7WB2I1lBP5OS0ajfG:-ODHv8zP4Ule907qoaod:b8jzkn4) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L279)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

This component uses the `sr-only` className, which means this is hidden visually without hiding it from screen readers. I am not sure how best to localize this string, besides adding a prop that we pass into the Shadcn sidebar?  I am curious if I could bring this up with Sebastian as well since there are a few Shadcn components that have text like this, and then come up with an issue to fix all of them with what we decide?
</blockquote></details>

Sure, that makes sense. Resolving this for now.


<!-- Sent from Reviewable.io -->

2024-12-04 22:10 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx` line 98 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7TmNX7BqsdMD1WdCG:-ODIfbqE4IBnYnokfXIQ:b-sm1e0q) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/lib/platform-bible-react/src/components/shadcn-ui/sidebar.tsx#L98)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I have made a note to talk with Sebastian about this in our next components meeting!
</blockquote></details>

Commented this part out pending the discussion with Sebastian
___
*[`src/renderer/services/web-view.service-host.ts` line 1439 at r1](https://reviewable.io/reviews/paranext/paranext-core/1354#-OD7Z4L9-db5k78RicBm:-ODIgL0s0fMWTiA7b9NB:b9dd3fz) ([raw file](https://github.com/paranext/paranext-core/blob/5f8e1c85744a7cf36a536d459b465a653e585757/src/renderer/services/web-view.service-host.ts#L1439)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Posted in the UX channel, so hopefully I will have an answer soon
</blockquote></details>

It seems they do not have an answer yet on which constants to use here. I rounded to the nearest hundred, and peeked at the widths and heights of other floating tabs. The configure checks and inventories web views render at w: 700 and h: 800, so it doesn't seem like it is too much larger than others. Do you think we could go ahead and merge?


<!-- Sent from Reviewable.io -->

2024-12-05 00:08 UTC, tjcouch-sil requested changes
Thanks for the adjustments! Sorry I wasn't super clear on how to deprecate before. It's a new thing I just started doing a bit ago, and I haven't yet written about it in the style guide. I added some clarifications :)

> Reviewed 2 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354#-:-ODJ873p-7LEnLy4xiIp:b-v6cod5)* status: 33 of 39 files reviewed, 5 unresolved discussions (waiting on @jolierabideau and @lyonsil)

___
*[`src/renderer/services/web-view.service-host.ts` line 1424 at r4](https://reviewable.io/reviews/paranext/paranext-core/1354#-ODJ7dA_-h7AcY6L6WFN:-ODJ7dA_-h7AcY6L6WFO:b-uxlqs9) ([raw file](https://github.com/paranext/paranext-core/blob/dbc5f02273efb15a00da8e8db0003b2e41dcd196/src/renderer/services/web-view.service-host.ts#L1424)):*
> ```XML
> };
> 
> async function openSettingsTab(webViewId: WebViewId): Promise<Layout | undefined> {
> ```

Currently, `platform.openProjectSettings` and `platform.openUserSettings` are silently broken. because they are no longer used.

To deprecate a feature, it still needs to be used so the feature still works for those who haven't yet upgraded to the newer thing. So in this case, you'd want to keep those two commands in the `commandHandlers` object but just have them both run `openSettingsTab` just like the `platform.openSettings` command currently does.
___
*[`lib/platform-bible-react/src/components/basics/combo-box.component.tsx` line 97 at r4](https://reviewable.io/reviews/paranext/paranext-core/1354#-ODJ6ZmKEZo_V2q_k5HO:-ODJ6ZmL4bNjzNBYV6b5:by63dry) ([raw file](https://github.com/paranext/paranext-core/blob/dbc5f02273efb15a00da8e8db0003b2e41dcd196/lib/platform-bible-react/src/components/basics/combo-box.component.tsx#L97)):*
> ```XML
>           aria-expanded={open}
>           id={id}
>           className={cn('tw-w-[200px] tw-justify-between', buttonClassName)}
> ```

Currently, `className` is silently broken. because it is no longer used.

To deprecate a feature, it still needs to be used so the feature still works for those who haven't yet upgraded to the newer thing. So in this case, you'd want to use the `className` prop like you used to use it while also making `buttonClassName` work. I'd suggest something like the following:

```ts
className={cn('tw-w-[200px] tw-justify-between', buttonClassName ?? className)}
```
___
*[`lib/papi-dts/papi.d.ts` line 2902 at r4](https://reviewable.io/reviews/paranext/paranext-core/1354#-ODJ67XW82zqqN0WmeQl:-ODJ67XXCUCy4sSpAb5s:b-prhk54) ([raw file](https://github.com/paranext/paranext-core/blob/9e0e5bdfa48fcc4ff6ff9693e8418edba251495d/lib/papi-dts/papi.d.ts#L2902)):*
> ```XML
>     'platform.restart': () => Promise<void>;
>     'platform.openProjectSettings': (webViewId: string) => Promise<void>;
>     'platform.openUserSettings': () => Promise<void>;
> ```

Perfect job on the deprecation of the project settings command! We also need the `openUserSettings` command to stick around, too, though :) sorry for the unclear direction before!


<!-- Sent from Reviewable.io -->

2024-12-05 16:10 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354)* status: 30 of 39 files reviewed, 5 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`lib/papi-dts/papi.d.ts` line 2902 at r4](https://reviewable.io/reviews/paranext/paranext-core/1354#-ODJ67XW82zqqN0WmeQl:-ODMYxOn2PXQfmzvSFBM:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/9e0e5bdfa48fcc4ff6ff9693e8418edba251495d/lib/papi-dts/papi.d.ts#L2902)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Perfect job on the deprecation of the project settings command! We also need the `openUserSettings` command to stick around, too, though :) sorry for the unclear direction before!
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/basics/combo-box.component.tsx` line 97 at r4](https://reviewable.io/reviews/paranext/paranext-core/1354#-ODJ6ZmKEZo_V2q_k5HO:-ODMZDl5EMpwXqXnSw0T:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/dbc5f02273efb15a00da8e8db0003b2e41dcd196/lib/platform-bible-react/src/components/basics/combo-box.component.tsx#L97)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Currently, `className` is silently broken. because it is no longer used.

To deprecate a feature, it still needs to be used so the feature still works for those who haven't yet upgraded to the newer thing. So in this case, you'd want to use the `className` prop like you used to use it while also making `buttonClassName` work. I'd suggest something like the following:

```ts
className={cn('tw-w-[200px] tw-justify-between', buttonClassName ?? className)}
```
</blockquote></details>

Done.
___
*[`src/renderer/services/web-view.service-host.ts` line 1424 at r4](https://reviewable.io/reviews/paranext/paranext-core/1354#-ODJ7dA_-h7AcY6L6WFN:-ODMZQh0En5z4hU6k19B:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/dbc5f02273efb15a00da8e8db0003b2e41dcd196/src/renderer/services/web-view.service-host.ts#L1424)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Currently, `platform.openProjectSettings` and `platform.openUserSettings` are silently broken. because they are no longer used.

To deprecate a feature, it still needs to be used so the feature still works for those who haven't yet upgraded to the newer thing. So in this case, you'd want to keep those two commands in the `commandHandlers` object but just have them both run `openSettingsTab` just like the `platform.openSettings` command currently does.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-05 17:41 UTC, tjcouch-sil reviewed
Thanks for the fixes! Looks great :)

> Reviewed 3 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354#-:-ODMuJQv6pS8C4ATgRYq:b-t3h4rs)* status: 33 of 39 files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`lib/papi-dts/papi.d.ts` line 2902 at r4](https://reviewable.io/reviews/paranext/paranext-core/1354#-ODJ67XW82zqqN0WmeQl:-ODMtublEUXhv4gko2Sd:b-snbm3v) ([raw file](https://github.com/paranext/paranext-core/blob/9e0e5bdfa48fcc4ff6ff9693e8418edba251495d/lib/papi-dts/papi.d.ts#L2902)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like maybe this needs to be updated with `npm run build:types` - the pre-commit script no longer runs this for you as of maybe last week. The build server will run it and will fail the build check if it detects `papi.d.ts` changes, though. I have already received failures multiple times because I forgot to run `npm run build:types` :joy:


<!-- Sent from Reviewable.io -->

2024-12-05 17:47 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354)* status: 27 of 39 files reviewed, 2 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`lib/papi-dts/papi.d.ts` line 2902 at r4](https://reviewable.io/reviews/paranext/paranext-core/1354#-ODJ67XW82zqqN0WmeQl:-ODMv_Q69OoqgMLMR65o:b-y9b95b) ([raw file](https://github.com/paranext/paranext-core/blob/9e0e5bdfa48fcc4ff6ff9693e8418edba251495d/lib/papi-dts/papi.d.ts#L2902)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like maybe this needs to be updated with `npm run build:types` - the pre-commit script no longer runs this for you as of maybe last week. The build server will run it and will fail the build check if it detects `papi.d.ts` changes, though. I have already received failures multiple times because I forgot to run `npm run build:types` :joy:
</blockquote></details>

Yes it did! Sorry, thanks for catching that! Hopefully all is good now.


<!-- Sent from Reviewable.io -->

2024-12-05 23:10 UTC, merchako commented
This PR #1354 partial satisfies UX designs to improve Settings

New mockups in response to PR #1354 for clarity and improvement: 
* Design page [PR#1354 Feedback combined](https://www.figma.com/design/zJWrApZ8AyPGxNHdndbkTz/Settings-Dialog-%23434?node-id=1094-838) (Figma)

which combines
* https://www.figma.com/design/zJWrApZ8AyPGxNHdndbkTz/Settings-Dialog-%23434?node-id=1056-899 and
* https://www.figma.com/design/zJWrApZ8AyPGxNHdndbkTz/Settings-Dialog-%23434?node-id=968-369

These **do not block the PR**.

@ianhewubs @jolierabideau @Sebastian-ubs

2024-12-10 19:36 UTC, lyonsil reviewed
> Reviewed 1 of 6 files at r4, 1 of 8 files at r5, 4 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354)* status: 32 of 39 files reviewed, all discussions resolved (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2024-12-10 19:38 UTC, lyonsil reviewed
> Reviewed 4 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-10 19:39 UTC, lyonsil approved these changes
> Reviewed 1 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-10 19:42 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1354#-:-ODm58QH6TKjwk9Tm3rv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-10 19:43 UTC, merged