Add OpenRPC documentation to JSON RPC methods
paranext/paranext-core pull request #1375
Opened 2024-12-09 20:28 UTC by lyonsil

This does not cover providing documentation for all of the JSON RPC methods. It adds the framework for documentation and a fraction of the documentation itself to demonstrate.

I originally looked more deeply into automatically converting JSDOC-style documentation into OpenRPC documentation and C# XML documentation into OpenRPC documentation. Unfortunately it's not straightforward, and for JSDOC-style comments in particular what source code parser (e.g., tokenizer, etc.) to use is not obvious. It seems that if we had wanted to start with OpenRPC documentation it would have been easier to generate boilerplates in other languages easily, but we're not working in that direction.

To view the live documentation, you can open the platform and use the [OpenRPC Playground application](https://playground.open-rpc.org/?transport=websocket&schemaUrl=ws%3A%2F%2Flocalhost%3A8876%0A&uiSchema[appBar][ui:splitView]=false&uiSchema[appBar][ui:input]=false&uiSchema[appBar][ui:examplesDropdown]=false&uiSchema[appBar][ui:transports]=false&uiSchema[appBar][ui:darkMode]=true&uiSchema[appBar][ui:title]=PAPI) to get a very Swagger-like experience. Even better, you can view events coming over the websocket to see what gets sent whenever we do something in the platform.

If we think this is a good foundation, then follow up work will be needed to populate the rest of the network objects, data providers, and commands with documentation. We could also think about making some small updates to the OpenRPC Playground application itself as it has a few bugs and isn't actively maintained.

I don't have a way to open the OpenRPC playground from within P.B right now. I don't think it will work as an extension within the platform because we block application connections back to our websocket port, but we could add something to open a web browser on the OS.

The main negatives I see to this approach are:
- Creating OpenRPC documentation from what we currently have is not fully automatable, but when AI assistance going through them manually isn't too bad at least for simple to moderately complex types. Doing it totally manually would be a pain. Doing it for very complex types will probably also be a pain.
- I don't have helper utils yet in C# to express the OpenRPC documentation sent back to the main process, so some work will be needed there.
- The amount of effort needed to finish this off might not be worth the effort at least right now. It totally depends on how many people will want to interact with Platform.Bible over the websocket vs through the TypeScript PAPI interface.
- OpenRPC isn't widely adopted, so tooling support is limited. JSON RPC is used a lot, but there isn't a real, widely adopted standard for documenting methods over JSON RPC.

Having said this, I think we might want to keep this functionality around even if just for us. It is pretty interesting to be able to send commands on demand and see events come through live.

2024-12-10 03:39 UTC, irahopkinson requested changes
Wow thanks for figuring this out. However, I couldn't actually get a dialog to show without an error, but fun to try externally in the playground.

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1375#-:-ODiakCbDsUKnq9oSHBL:b-82l766)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`src/main/services/project-lookup.service-host.ts` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODiTgzv81f_MWCrE0TC:-ODiTgzv81f_MWCrE0TD:blu1b87) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/main/services/project-lookup.service-host.ts#L34)):*
> ```XML
>           summary: 'Provide metadata for all projects that have PDP factories',
>           description:
>             'Note: If there are multiple PDPs available whose metadata matches the conditions provided by the parameters, their project metadata will all be combined, so all available `projectInterface`s provided by the PDP Factory with the matching id (or all PDP Factories if no id is specified) for the project will be returned.',
> ```

NIT this is super nit-y but "ID" should always be caps in prose (despite us using "id" in code). Here and elsewhere.
___
*[`src/main/services/rpc-websocket-listener.ts` line 203 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODiWDwOCiRxpB4tVkfJ:-ODiWDwOCiRxpB4tVkfK:b-pmbzbw) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/main/services/rpc-websocket-listener.ts#L203)):*
> ```XML
>       if (details.methodDocs) {
>         const newDocs = { name: methodName, ...details.methodDocs.method };
>         newDocs.name = methodName;
> ```

This line seems redundant given the line above? If the spread is overwriting it then just put the spread first (it is usually safer to put more specific assignments after the spread anyway even if there isn't a current overwrite).
___
*[`package.json` line 247 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODiQLKPDD0QCNGk1OaW:-ODiQLKPDD0QCNGk1OaX:b-4ts699) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/package.json#L247)):*
> ```JSON
>   "workspaces": ["lib/*", "extensions", "extensions/src/*"],
>   "volta": {
>     "node": "22.12.0"
> ```

BTW what required moving up to this version of node? Was it OpenRPC?


<!-- Sent from Reviewable.io -->

2024-12-10 17:28 UTC, lyonsil reviewed
I can look through this with you as it should run properly. My best guess is that you aren't changing the message IDs that are always defaulted to 0. This is (in my view) a flaw with the playground as every time you say you want to run a new method it should populate the ID with a random value (strings and numbers are both fine). JSON RPC stacks don't like reusing message IDs on the same connection, and sometimes 0 is special and not a great choice, either. There are a few things I would ideally like to adjust in playground, but I don't think that's a priority at the moment.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1375#-:-ODlP_QQEp6QUc2kzp89:b8dz0zq)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[`package.json` line 247 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODiQLKPDD0QCNGk1OaW:-ODlQSaE2AV8N1P9qMyG:byqzxhy) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/package.json#L247)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW what required moving up to this version of node? Was it OpenRPC?
</blockquote></details>

Ah - that came up as part of my work on this but wasn't caused by OpenRPC. Version 20 of node has a particular bug I discovered that manifests itself on Linux on faster/newer hardware. I found it because I upgraded my dev box. The result is that if I set a breakpoint anywhere in a Node process and try to start Platform in the debugger, it immediately crashes. TJ and I spent some time trying to debug and figure out what is going on, and the clearest result is that v22 LTS fixes the bug. FWIW, v18 also works, but going forward seems better than going backward.

I can back this out and just use v22 on my machine if we don't want to move off of v20 to stay aligned with Electron.
___
*[`src/main/services/project-lookup.service-host.ts` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODiTgzv81f_MWCrE0TC:-ODlZ8a46hsIujRzlpMP:bx8s3gp) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/main/services/project-lookup.service-host.ts#L34)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

NIT this is super nit-y but "ID" should always be caps in prose (despite us using "id" in code). Here and elsewhere.
</blockquote></details>

This is a raw copy of some of the existing JSDOC-style comments. I can update the text in both places to use `ID` instead of `id`.
___
*[`src/main/services/rpc-websocket-listener.ts` line 203 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODiWDwOCiRxpB4tVkfJ:-ODlSXI9-LKtE0QIo8S7:b-6kjd68) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/main/services/rpc-websocket-listener.ts#L203)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This line seems redundant given the line above? If the spread is overwriting it then just put the spread first (it is usually safer to put more specific assignments after the spread anyway even if there isn't a current overwrite).
</blockquote></details>

I can add a comment about this. It looks redundant but actually isn't. Here's why.
- I want `name` to be first in the documentation. Although JS objects are kind of just key-value stores, when JS is stringified to JSON, the order that properties are created in JS defines the order that the properties are serialized. Since I want `name` to be first in the JSON, I have to defined it first in JS.
- I am copying all the properties of `details.methodDocs.method` into the docs because I need everything else. However, it is possible that `method` ends up with a name included. If it is, then it overwrites the name I assigned.
- Since the name I set might be overwritten, then rewriting it on the line after I set it initially enforces that the name is what I want it to be.

Having said all this, I could just delete any existing `name` property on `details.methodDocs.method` before copying into `newDocs`. That has other potential weirdness (e.g., what if someone froze the doc object so I can't change it?) but would not look like a duplicate line of code.


<!-- Sent from Reviewable.io -->

2024-12-10 19:21 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1375#-:-ODm0Fgh-p7MN93h7GuB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`package.json` line 247 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODiQLKPDD0QCNGk1OaW:-ODlySQnB2k7oJ7v93Jl:b-y04itg) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/package.json#L247)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ah - that came up as part of my work on this but wasn't caused by OpenRPC. Version 20 of node has a particular bug I discovered that manifests itself on Linux on faster/newer hardware. I found it because I upgraded my dev box. The result is that if I set a breakpoint anywhere in a Node process and try to start Platform in the debugger, it immediately crashes. TJ and I spent some time trying to debug and figure out what is going on, and the clearest result is that v22 LTS fixes the bug. FWIW, v18 also works, but going forward seems better than going backward.

I can back this out and just use v22 on my machine if we don't want to move off of v20 to stay aligned with Electron.
</blockquote></details>

Good to know about that issue on Linux - that sounds like that was a real pain to sort out. Yeah, we can't go back to node v18 because of Electron but we can likely go up without too many issues. Our Electron is currently on v32 and v34 will be stable in mid-Jan so we can move to that then but it looks like its node version will still be v20. Electron v35 looks like it will be on node v22 but that probably won't be out until March. I think as long as we don't find any issues with node v22 we should be fine for now.


<!-- Sent from Reviewable.io -->

2024-12-10 21:12 UTC, tjcouch-sil requested changes
> Reviewed 16 of 25 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1375)* status: 24 of 26 files reviewed, 5 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`src/shared/models/openrpc.model.ts` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmOodaBtnVhHwK9K9w:-ODmOodaBtnVhHwK9K9x:b2s2ria) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/shared/models/openrpc.model.ts#L6)):*
> ```XML
> 
> // TODO
> // https://playground.open-rpc.org/?transport=websocket&schemaUrl=ws%3A%2F%2Flocalhost%3A8876%0A&uiSchema[appBar][ui:splitView]=false&uiSchema[appBar][ui:input]=false&uiSchema[appBar][ui:examplesDropdown]=false&uiSchema[appBar][ui:transports]=false&uiSchema[appBar][ui:darkMode]=true&uiSchema[appBar][ui:title]=PAPI
> ```

What is this?
___
*[`src/shared/models/openrpc.model.ts` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmOtXw-BJEWOEbn0Km:-ODmOtXxBkppqKVUm-b-:b7ku53y) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/shared/models/openrpc.model.ts#L13)):*
> ```XML
>  * Describes APIs available to call using JSON-RPC 2.0
>  *
>  * See https://github.com/open-rpc/meta-schema/releases - Release 1.14.2 aligns with OpenRPC 1.2.6.
> ```

Could we use its package instead of including the types manually? https://www.npmjs.com/package/@open-rpc/meta-schema/v/1.14.2
___
*[`src/shared/data/rpc.model.ts` line 216 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmO-2G81I5gO_ROvVD:-ODmO-2G81I5gO_ROvVE:b-wr8g54) ([raw file](https://github.com/paranext/paranext-core/blob/28fdd2214bf40142faf5632c54c1d7f2d7995b97/src/shared/data/rpc.model.ts#L216)):*
> ```XML
> 
> /** Get all methods that are currently registered on the network. */
> export const GET_METHODS = 'network:getMethods';
> ```

I think we should leave `network:getMethods` in addition to adding `rpc.discover` to avoid conforming our own things to something required by a tool we use. Maybe `network:getMethods` would be the unchanging, autodoc-independent version that always works no matter what auto-doc tool we use.

If you disagree, I'd think it would still be wise at least to deprecate `network:getMethods` instead of removing it. What do you think?
___
*[`package.json` line 0 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmDha6CzPITCidYINH:-ODmDha6CzPITCidYINI:beqrx0q) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/package.json#L0)):*
I'm surprised to see there aren't any packages added here. Are there types for openrpc stuff?

(Oh - see later comment about https://www.npmjs.com/package/@open-rpc/meta-schema/v/1.14.2)
___
*[`src/renderer/services/dialog.service-host.ts` line 276 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmNph12dDwc89tSaUJ:-ODmNph12dDwc89tSaUK:b-ahfpbp) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/renderer/services/dialog.service-host.ts#L276)):*
> ```XML
>               schema: {
>                 type: 'object',
>                 properties: {
> ```

Looks like this one and the next set of properties are missing things in `ModifierProject` https://github.com/paranext/paranext-core/blob/main/lib/platform-bible-utils/src/settings.model.ts#L86


<!-- Sent from Reviewable.io -->

2024-12-10 21:50 UTC, irahopkinson approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1375)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2024-12-10 22:29 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1375)* status: all files reviewed, 5 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/renderer/services/dialog.service-host.ts` line 276 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmNph12dDwc89tSaUJ:-ODmg2Pn7TbVytMhqFT8:biyyxmj) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/renderer/services/dialog.service-host.ts#L276)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this one and the next set of properties are missing things in `ModifierProject` https://github.com/paranext/paranext-core/blob/main/lib/platform-bible-utils/src/settings.model.ts#L86
</blockquote></details>

Good catch - I can update those.
___
*[`src/shared/data/rpc.model.ts` line 216 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmO-2G81I5gO_ROvVD:-ODm_7EH9EQ6jbsx4n30:b-hlhaxx) ([raw file](https://github.com/paranext/paranext-core/blob/28fdd2214bf40142faf5632c54c1d7f2d7995b97/src/shared/data/rpc.model.ts#L216)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think we should leave `network:getMethods` in addition to adding `rpc.discover` to avoid conforming our own things to something required by a tool we use. Maybe `network:getMethods` would be the unchanging, autodoc-independent version that always works no matter what auto-doc tool we use.

If you disagree, I'd think it would still be wise at least to deprecate `network:getMethods` instead of removing it. What do you think?
</blockquote></details>

`network:getMethods` was only a constant in the model file prior to this. It was a placeholder for something like `rpc.discover` that never got implemented in prior PRs due to time constraints. There was no implementation in the code before this PR. There is nothing to deprecate.

We can always go back and add something like `network:getMethods` if we want to. I just don't know what would use it. I'd say let's wait to implement something like that until we have a need.
___
*[`src/shared/models/openrpc.model.ts` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmOodaBtnVhHwK9K9w:-ODma49h8Y9MD59sBuIq:bmez0j3) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/shared/models/openrpc.model.ts#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

This is the URL I would want to use when opening the browser to automatically load our APIs into the OpenRPC Playground. I don't have a good place to put this for now, but the URL was kind of a pain to put together, so I didn't want to lose it.

When this PR gets merged I can start by putting it it in the wiki. Maybe it would be nice to put in a menu item with `DEV_NOISY`, too, assuming we have a way to open a browser in the OS in a platform agnostic way. I just didn't know where to use the URL for now. Sorry that the comment was pretty brief
___
*[`src/shared/models/openrpc.model.ts` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmOtXw-BJEWOEbn0Km:-ODma_K1BuS721StxHRi:bk1t6u0) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/shared/models/openrpc.model.ts#L13)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Could we use its package instead of including the types manually? https://www.npmjs.com/package/@open-rpc/meta-schema/v/1.14.2
</blockquote></details>

To be honest I didn't see that package. We could switch to that, but I know at least one thing I'd want to change is how references are set. I set the types to only allow references within the JSON document itself (i.e., `#/components/SOMETHING`) because I discovered that if you put references to public schemas (e.g., `https://somewhere/something.json`), then Playground won't render properly because the JSON schema parser they are using won't load in the external references. That means I'd still not be able to use their types as-is without opening up schema references to something that breaks the Playground UI.

I think if the types in that package were something not completely auto-generated in a simple way I would be more excited about them. When I see types like this, I don't get excited. There are lots of defined types like this in that package.
```ts
export type InfoObjectProperties = string;
export type InfoObjectDescription = string;
export type InfoObjectTermsOfService = string;
export type InfoObjectVersion = string;
export type ContactObjectName = string;
export type ContactObjectEmail = string;
export type ContactObjectUrl = string;
export type SpecificationExtension = any;
```

Interestingly, the auto-generator they are using didn't even link up their types internally (notice the `any`s):
```ts
export interface SchemaComponents { [key: string]: any; }
export interface LinkComponents { [key: string]: any; }
export interface ErrorComponents { [key: string]: any; }
export interface ExampleComponents { [key: string]: any; }
export interface ExamplePairingComponents { [key: string]: any; }
export interface ContentDescriptorComponents { [key: string]: any; }
export interface TagComponents { [key: string]: any; }

export interface Components {
  schemas?: SchemaComponents;
  links?: LinkComponents;
  errors?: ErrorComponents;
  examples?: ExampleComponents;
  examplePairings?: ExamplePairingComponents;
  contentDescriptors?: ContentDescriptorComponents;
  tags?: TagComponents;
  [k: string]: any;
}
```

The types in this file provide more realistic restrictions/guidance:
```ts
export type Components = {
  schemas?: { [key: string]: Schema };
  contentDescriptors?: { [key: string]: ContentDescriptor };
  examples?: { [key: string]: Example };
  links?: { [key: string]: Link };
  errors?: { [key: string]: Error };
  tags?: { [key: string]: Tag };
};
```

Also, if we pull in their types, they redefine what is in a JSON schema where we are using types from the `json-schema` package.

I think I'd rather just leave this as-is since using their types doesn't really add anything but they take away some of the value of using types.


<!-- Sent from Reviewable.io -->

2024-12-11 00:11 UTC, irahopkinson approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1375)* status: all files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2024-12-11 01:37 UTC, tjcouch-sil approved these changes
WOWOWOW this is super exciting! :) Looking forward to having this in. Especially if you think it's ready enough to put in the menu item thing I suggested, this is gonna be AWESOME! I have a handful of thoughts for you to consider

> Reviewed 9 of 25 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1375#-:-ODnLcgY5OCUrGwGo8qr:bdiu4l5)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`src/shared/data/rpc.model.ts` line 216 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmO-2G81I5gO_ROvVD:-ODnKVyU-TcotJP2BcYi:bzsf03) ([raw file](https://github.com/paranext/paranext-core/blob/28fdd2214bf40142faf5632c54c1d7f2d7995b97/src/shared/data/rpc.model.ts#L216)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

`network:getMethods` was only a constant in the model file prior to this. It was a placeholder for something like `rpc.discover` that never got implemented in prior PRs due to time constraints. There was no implementation in the code before this PR. There is nothing to deprecate.

We can always go back and add something like `network:getMethods` if we want to. I just don't know what would use it. I'd say let's wait to implement something like that until we have a need.
</blockquote></details>

Oh haha oops. That's funny; I was thinking we didn't have anything like this up to this point, so I was surprised to see it. But I just assumed it was implemented. Anyway thanks for the explanation :) agreed we don't want to make things that aren't needed
___
*[`src/shared/models/openrpc.model.ts` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmOodaBtnVhHwK9K9w:-ODnKpEb798ok4JFhuzT:bwumf1q) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/shared/models/openrpc.model.ts#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This is the URL I would want to use when opening the browser to automatically load our APIs into the OpenRPC Playground. I don't have a good place to put this for now, but the URL was kind of a pain to put together, so I didn't want to lose it.

When this PR gets merged I can start by putting it it in the wiki. Maybe it would be nice to put in a menu item with `DEV_NOISY`, too, assuming we have a way to open a browser in the OS in a platform agnostic way. I just didn't know where to use the URL for now. Sorry that the comment was pretty brief
</blockquote></details>

Thanks for building that link :) looks like it took a while to make! I have some suggestions for you to consider:
1. Make a built-in hard-coded menu item in `platform-bible-menu.commands.ts` like `platform.visitSupportPage` that opens this link in a new browser
2. Add an explanation of what this link is in here so we at least have some context for it. The description-less TODO makes me nervous haha
___
*[`src/shared/models/openrpc.model.ts` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODmOtXw-BJEWOEbn0Km:-ODnHfbX230vdtglx1nU:botiz57) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/shared/models/openrpc.model.ts#L13)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

To be honest I didn't see that package. We could switch to that, but I know at least one thing I'd want to change is how references are set. I set the types to only allow references within the JSON document itself (i.e., `#/components/SOMETHING`) because I discovered that if you put references to public schemas (e.g., `https://somewhere/something.json`), then Playground won't render properly because the JSON schema parser they are using won't load in the external references. That means I'd still not be able to use their types as-is without opening up schema references to something that breaks the Playground UI.

I think if the types in that package were something not completely auto-generated in a simple way I would be more excited about them. When I see types like this, I don't get excited. There are lots of defined types like this in that package.
```ts
export type InfoObjectProperties = string;
export type InfoObjectDescription = string;
export type InfoObjectTermsOfService = string;
export type InfoObjectVersion = string;
export type ContactObjectName = string;
export type ContactObjectEmail = string;
export type ContactObjectUrl = string;
export type SpecificationExtension = any;
```

Interestingly, the auto-generator they are using didn't even link up their types internally (notice the `any`s):
```ts
export interface SchemaComponents { [key: string]: any; }
export interface LinkComponents { [key: string]: any; }
export interface ErrorComponents { [key: string]: any; }
export interface ExampleComponents { [key: string]: any; }
export interface ExamplePairingComponents { [key: string]: any; }
export interface ContentDescriptorComponents { [key: string]: any; }
export interface TagComponents { [key: string]: any; }

export interface Components {
  schemas?: SchemaComponents;
  links?: LinkComponents;
  errors?: ErrorComponents;
  examples?: ExampleComponents;
  examplePairings?: ExamplePairingComponents;
  contentDescriptors?: ContentDescriptorComponents;
  tags?: TagComponents;
  [k: string]: any;
}
```

The types in this file provide more realistic restrictions/guidance:
```ts
export type Components = {
  schemas?: { [key: string]: Schema };
  contentDescriptors?: { [key: string]: ContentDescriptor };
  examples?: { [key: string]: Example };
  links?: { [key: string]: Link };
  errors?: { [key: string]: Error };
  tags?: { [key: string]: Tag };
};
```

Also, if we pull in their types, they redefine what is in a JSON schema where we are using types from the `json-schema` package.

I think I'd rather just leave this as-is since using their types doesn't really add anything but they take away some of the value of using types.
</blockquote></details>

Interesting! Good to know. Would be nice to have a note in the code here to explain why we're not using the package that comes directly from the link you specified here as a reminder for the future :) but I'll unblock
___
*[`src/shared/models/rpc.interface.ts` line 81 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODnI57J8AbPH554InH9:-ODnI57J8AbPH554InHA:b-87mb0i) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/shared/models/rpc.interface.ts#L81)):*
> ```XML
>     methodName: string,
>     method: InternalRequestHandler,
>     methodDocs?: SingleMethodDocumentation,
> ```

I think it would be good to put `SingleMethodDocumentation` (and possibly other types in that file like ones that are used inside this type) in `@papi/core` since it's exposed and probably will be commonly used. Seems like something people very well might want to separate from putting an in-line object in their registration calls, so having the type available would be helpful.
___
*[`src/shared/services/network-object.service.ts` line 423 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODnIZ3F2zWn6LUo_cDV:-ODnIZ3F2zWn6LUo_cDW:brlx4ka) ([raw file](https://github.com/paranext/paranext-core/blob/af13f4332544d0632fe6b676fefa712325b07f78/src/shared/services/network-object.service.ts#L423)):*
> ```XML
>   objectType: string = 'object',
>   objectAttributes: { [property: string]: unknown } | undefined = undefined,
>   objectDocumentation: NetworkObjectDocumentation = {},
> ```

I also think `NetworkObjectDocumentation` and possibly some related types should go on `@papi/core`
___
*[`src/shared/services/network-object.service.ts` line 470 at r1](https://reviewable.io/reviews/paranext/paranext-core/1375#-ODnJEGq2AuqYrreIcfL:-ODnJEGq2AuqYrreIcfM:bxhl7em) ([raw file](https://gith [...]

2024-12-11 19:06 UTC, merged