Update Get Resources web-view UI to Phase 1 UX design
paranext/paranext-core pull request #1399
Opened 2024-12-17 17:00 UTC by rolfheij-sil

![image](https://github.com/user-attachments/assets/d9997d34-64ba-4c6c-8503-bb665b771bee)

Design spec found [here](https://www.figma.com/design/2p7VtjVtRzp5e8zWi5ZCSy/Get-resources-(%2Bhome%2C-send%2Freceive)?node-id=1505-32804&p=f&t=bnLiAzuHTcJX9E8R-0)

2024-12-18 19:30 UTC, lyonsil requested changes
Looks pretty good overall. I have a couple of blocking considerations and a few other questions.

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399#-:-OEQDhpm-kwZY609Y_8R:b-tod765)* status: all files reviewed, 5 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-home/src/home.web-view.tsx` line 0 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQ77P1E583EI5XWhwM:-OEQ77P1E583EI5XWhwN:bkpijx2) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/extensions/src/platform-home/src/home.web-view.tsx#L0)):*
This looks identical to `get-resources.web-view.tsx`.  Even if there are just one or two lines of difference, why aren't we refactoring to provide a single component that both of these web views use? I guess I'm wondering, like in my previous comment, why we are even creating separate extensions if we're just duplicating code.
___
*[`extensions/src/platform-home/contributions/localizedStrings.json` line 0 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQ5ptFA93o1JLFeiAY:-OEQ5ptFA93o1JLFeiAZ:bs1buba) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/extensions/src/platform-home/contributions/localizedStrings.json#L0)):*
It doesn't make a lot of sense to me that we're creating multiple extensions with identical localizations that are all being used to implement the same UI. Since these are all bundled extensions anyway, why did we split these up into separate extensions? If we really do want them to be separate extensions, then we really ought to just enforce a dependency between the extensions and make sure we load them in the right order. Then we don't have to worry about whether the localized strings we need exist.

What might even be simpler than enforcing a dependency between extensions would be to put these in core's localized strings file.

Bottom line, defining the same localized strings in multiple extensions is a recipe for problems later. Some strings will inevitably be updated in one but not the other, and then the indeterminate loading order of the extensions will result in inconsistent localized strings being shown.
___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 189 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQAGylEPz5s8KxBDp9:-OEQAGylEPz5s8KxBDpA:b-mcljvn) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L189)):*
> ```XML
> }: FilterableResourceListProps) {
>   const actionText: string = localizedStrings['%resources_action%'];
>   const anyText: string = localizedStrings['%resources_any%'];
> ```

Perhaps the reason we're duplicating the definition of these localized strings is that anything that uses these components needs the strings to be defined. Is that right? If so, let's move these strings into the base platform's localized strings. Otherwise anytime a new extension is added that uses this component we'll have to create yet another copy.
___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 379 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQBc9ND-EjdPozJA27:-OEQBc9ND-EjdPozJA28:bjfjyhv) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L379)):*
> ```XML
>               />
> 
>               <Filter
> ```

Just a question about this - I would have guessed that a filter for selecting languages would use the new language picker control, not a generic filter. The language picker should handle things like providing the correct label to display for a resource's language matching the UI language. (e.g., if the UI language is Spanish, I think it would say "Inglés" for English resources) We don't really want to be defining language names ourselves if the language picker is already going to handle that using SLDR or something like that.

Was this part of phase 1? Maybe this comes in a later phase. Just checking.
___
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.component.tsx` line 56 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQ8aeeBGAESB7HZWJ5:-OEQ8aeeBGAESB7HZWJ6:b-ypfd8) ([raw file](https://github.com/paranext/paranext-core/blob/7de6701806e71793f43688a622fc4e4604be9bf0/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.component.tsx#L56)):*
> ```XML
> 
>   const getPlaceholderText = () => {
>     if (selected.length === 1)
> ```

Just curious - why was this removed?


<!-- Sent from Reviewable.io -->

2024-12-19 08:36 UTC, Sebastian-ubs reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil and @rolfheij-sil)

___
*[`extensions/src/platform-home/src/home.web-view.tsx` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQ77P1E583EI5XWhwM:-OET0TKb5qTpeYnbb5Tb:bmwniqx) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/extensions/src/platform-home/src/home.web-view.tsx#L)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This looks identical to `get-resources.web-view.tsx`.  Even if there are just one or two lines of difference, why aren't we refactoring to provide a single component that both of these web views use? I guess I'm wondering, like in my previous comment, why we are even creating separate extensions if we're just duplicating code.
</blockquote></details>

I think putting it into platform-bible-react makes sense for 2 reasons:
1. the close proximity to Home. Not sure however if the remaining differences are worth re-using the whole ui or only parts.
2. having whole uis in pbr allows for quicker ui changes and reuse of parts later, as well as possibility to immediately test it with the color theme and alignment
___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 379 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQBc9ND-EjdPozJA27:-OET-feT14v3o0sN_FB-:b-m8upfr) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L379)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Just a question about this - I would have guessed that a filter for selecting languages would use the new language picker control, not a generic filter. The language picker should handle things like providing the correct label to display for a resource's language matching the UI language. (e.g., if the UI language is Spanish, I think it would say "Inglés" for English resources) We don't really want to be defining language names ourselves if the language picker is already going to handle that using SLDR or something like that.

Was this part of phase 1? Maybe this comes in a later phase. Just checking.
</blockquote></details>

No these are different use cases. Probably the way to get the language names can later be shared, but the controls themselves are different:
- ui language picker is a single select component without filtering
- resource language filter is a multi select component with filtering and sorting the selected to the top
___
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.component.tsx` line 56 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQ8aeeBGAESB7HZWJ5:-OET-HPsED5MoEJbpzhI:b-gjyewm) ([raw file](https://github.com/paranext/paranext-core/blob/7de6701806e71793f43688a622fc4e4604be9bf0/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.component.tsx#L56)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Just curious - why was this removed?
</blockquote></details>

This was removed as per the new design
___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 362 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OET2F7l-0mHXnjaxfSq:-OET2F7l-0mHXnjaxfSr:b-t4leij) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L362)):*
> ```XML
>                       placeholder={filterInputText}
>                     />
>                     <Search className="tw-absolute tw-right-3 tw-top-1/2 tw-h-4 tw-w-4 tw--translate-y-1/2 tw-transform tw-text-muted-foreground" />
> ```

The search icon is on the wrong side (and will not change in rtl, but this is discussed elsewhere). Would using the searchBar component work instead?
This is not blocking - we could change this later.


<!-- Sent from Reviewable.io -->

2024-12-19 08:46 UTC, Sebastian-ubs requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil and @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 379 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQBc9ND-EjdPozJA27:-OET36AM2nJXCAYenxBA:bbe16sp) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L379)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

No these are different use cases. Probably the way to get the language names can later be shared, but the controls themselves are different:
- ui language picker is a single select component without filtering
- resource language filter is a multi select component with filtering and sorting the selected to the top
</blockquote></details>

After testing:
1) Good that you added a realistic amount of languages already to the preview app. I recognized, that the language filter popover needs >1 second to open and also a little more than the usual time to close. I guess this is due to the large number of languages (dom nodes) in the popover. We may want to file a separate issue to look into improving this (e.g. not adding+removing it from the dom, but only hiding it).

2) The starred items seem not to match with the initial selection right now, this should be fixed.
![image.png](https://files.reviewableusercontent.io/images/reviewable/141921979/V3gqyY5Vl-qwG7-g_vWsgh1b/image.png)


<!-- Sent from Reviewable.io -->

2024-12-19 09:10 UTC, Sebastian-ubs requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil and @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 379 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQBc9ND-EjdPozJA27:-OET7QP_2FreMkoaiZ4u:bxe55lg) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L379)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

After testing:
1) Good that you added a realistic amount of languages already to the preview app. I recognized, that the language filter popover needs >1 second to open and also a little more than the usual time to close. I guess this is due to the large number of languages (dom nodes) in the popover. We may want to file a separate issue to look into improving this (e.g. not adding+removing it from the dom, but only hiding it).

2) The starred items seem not to match with the initial selection right now, this should be fixed.
![image.png](https://files.reviewableusercontent.io/images/reviewable/141921979/V3gqyY5Vl-qwG7-g_vWsgh1b/image.png)
</blockquote></details>

Found additional bugs:

3. Selected items are not consistently sorted to the top. Also the rest is not alphabetically sorted.
Sorting should be: starred items A-z (independent of their selection), selected (non-starred) items A-z, other (non-starred, non-selected) A-z
English language names are fine for now. This is what we get from DBL and this is what PT9 shows. We may improve this in the future.

![image.png](https://files.reviewableusercontent.io/images/reviewable/141921979/EjRIwuX7AUR9RRTpntoubsek/image.png)

4. Unexpectedly, filtering the language seems to include text this is not shown or does a non-strict search on the language name and acronym. Also compared to PT9, this is showing too much.

![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/141921979/uTrzD-ceXJlkI-MH8ZyL-MsD/image.png)
![image copy 2.png](https://files.reviewableusercontent.io/images/reviewable/141921979/SjN-LlptXaLTvI3TTX8OV7f8/image.png)


<!-- Sent from Reviewable.io -->

2024-12-19 15:13 UTC, Sebastian-ubs requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: 13 of 20 files reviewed, 5 unresolved discussions (waiting on @lyonsil and @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 362 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OET2F7l-0mHXnjaxfSq:-OEUS5Ww5FPlxYCp4z-U:b7i266d) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L362)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Yep, using the search bar is a good idea. I think I got the current search input from the Book Chapter selector. I didn't know about the searchbar :sweat_smile:
</blockquote></details>

just be aware, that the search bar is currently a bit broken ^^ 
(but I guess we want to fix that soon anyhow)
https://github.com/paranext/paranext-core/issues/1405
___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 379 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQBc9ND-EjdPozJA27:-OEUSWht40AQGLEQCXpl:b120ayy) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L379)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

1. Good idea. I think there's multiple places in our code that could be optimized for performance. There might already be an issue for that somewhere, and if not we should open one.
2. Yep, good catch. Will investigate.
3. I believe the sorting happens in the way you describe. The screenshot you added also shows this sorting behavior, right?
4. This behavior is defined by a search algorithm somewhere very deep down in the code. The`MultiSelectComboBox`uses the shadcn `Command`, which uses [this component](https://cmdk.paco.me/), which has this [sorting logic](https://github.com/pacocoursey/cmdk/blob/9827edf89fc663e24188f9d715a0dca01a736d6d/cmdk/src/index.tsx#L432). I suggest we do not change it.
</blockquote></details>

1. I will add one to epic 117
2. -
3. Sorry, yes the screenshot kind of shows sorting for starred and selected items correctly. I however also had a non-starred item appear in the middle of stars at some point. Also the list of unselected languages starts with a language with N, but should be with a language with A
4. Sad to hear this is deep inside the provided code. From a user perspective I think we want to change this. Is it filtering based on some other properties of the object that you pass in, or only based on the strings that show up in the combobox popover but "fuzzy"?


<!-- Sent from Reviewable.io -->

2024-12-19 15:15 UTC, Sebastian-ubs requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: 13 of 20 files reviewed, 5 unresolved discussions (waiting on @lyonsil and @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 379 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQBc9ND-EjdPozJA27:-OEUTxwh-GJhijiNvIOn:b-o4072g) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L379)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

1. I will add one to epic 117
2. -
3. Sorry, yes the screenshot kind of shows sorting for starred and selected items correctly. I however also had a non-starred item appear in the middle of stars at some point. Also the list of unselected languages starts with a language with N, but should be with a language with A
4. Sad to hear this is deep inside the provided code. From a user perspective I think we want to change this. Is it filtering based on some other properties of the object that you pass in, or only based on the strings that show up in the combobox popover but "fuzzy"?
</blockquote></details>

thinking about 3, maybe we need a divider between any of these, but this seems to be minor improvements that can come later. Sorting alphabetically however is needed to not get lost.


<!-- Sent from Reviewable.io -->

2024-12-19 15:21 UTC, lyonsil requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: all files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil and @Sebastian-ubs)

___
*[`extensions/src/platform-home/contributions/localizedStrings.json` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQ5ptFA93o1JLFeiAY:-OEUTJfD0j0EkOoL9fz1:beampcm) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/extensions/src/platform-home/contributions/localizedStrings.json#L)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Yeah, good catch. Initally `Get Resources` was in `platform-bible-internal-extensions` and `Home` was supposed to be bundled, so that's why they're separate extensions. Now that they're both bundled we can probably merge them into a single extension. I'll probably do that in a different PR though, is that okay?
</blockquote></details>

Since we don't have a way for libraries to contribute localization files, then I think any localization strings used by the react lib and utilities lib should be included in the platform. Please move them out of the extensions and into the main localization file for the platform.
___
*[`extensions/src/platform-home/src/home.web-view.tsx` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQ77P1E583EI5XWhwM:-OEUTkuJ4RYsaGK-D_uj:b-tnbbqv) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/extensions/src/platform-home/src/home.web-view.tsx#L)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

@lyonsil Yes, this branch does not have a proper implementation of the `Home` design as proposed by UX yet. I just plugged in a copy of the Get Resources web view as a placeholder for now, since their designs are very similar. I'm working on implementing the `Home` design on a separate branch

@Sebastian-ubs Thinking about it, if `Get Resources` and `Home` do not turn out as similar as you were hoping, we can always split up `FilterableResourceList` in to smaller components. For example, yesterday Alex told me that the `Home` design will not have the Type and Language filter.
</blockquote></details>

Ok - If we think these will end up diverging I'm OK with them being duplicates for now. It would be good to combine them into a single control, though, if they end up being identical or nearly identical.
___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 189 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQAGylEPz5s8KxBDp9:-OEUUByM-zOBOFHuDBK5:b-l5ffmz) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L189)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Good catch. I guess there's two options: Move the localized strings to base, or merge the extensions. I'm not sure what the best approach is, especially because the `Home` design is still evolving, so I don't know how similar/different `Get Resources` and `Home` will end up in the long run
</blockquote></details>

I'll resolve this comment and leave the other one open related to this topic. Since we don't have a way to add localization strings from libraries, we can move these to the main platform's localization file.
___
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.component.tsx` line 56 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQ8aeeBGAESB7HZWJ5:-OEUU3-DDQu56efo5WyT:b-wsvasg) ([raw file](https://github.com/paranext/paranext-core/blob/7de6701806e71793f43688a622fc4e4604be9bf0/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.component.tsx#L56)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Initially the multi-selects related to the filters were designed to always have at least one option selected. However, this meant that showing resources in all languages would require the user to manually select all languages in the filter. So the component was redesigned so that selecting 0 items is interpreted as 'any items', effectively showing all items
</blockquote></details>

Thanks for the explanation!


<!-- Sent from Reviewable.io -->

2024-12-19 16:52 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: all files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil and @Sebastian-ubs)

___
*[`extensions/src/platform-home/src/home.web-view.tsx` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQ77P1E583EI5XWhwM:-OEUpJBs3txJn5r32NBh:bszwfvv) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/extensions/src/platform-home/src/home.web-view.tsx#L)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ok - If we think these will end up diverging I'm OK with them being duplicates for now. It would be good to combine them into a single control, though, if they end up being identical or nearly identical.
</blockquote></details>

I should have said "a single component" in my previous comment.


<!-- Sent from Reviewable.io -->

2024-12-19 17:05 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: all files reviewed, 2 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 379 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQBc9ND-EjdPozJA27:-OEUqWtE0USbhU5ls7pN:b3zgg0l) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L379)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

thinking about 3, maybe we need a divider between any of these, but this seems to be minor improvements that can come later. Sorting alphabetically however is needed to not get lost.
</blockquote></details>

3. I'm trying to replicate the behavior you mention, but I can't. I don't ever see unstarred things in between the starred items, and everything sorts correctly A-z. If you can still replicate this, let me know and we can hop on a call and I can take a look with you.
4. I don't know if we can control it through props. Maybe we could add a separate issue for this, since it's more about customizing the `Command` component than having anything to do with `Get Resources`


<!-- Sent from Reviewable.io -->

2024-12-19 17:27 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: all files reviewed, 2 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 379 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQBc9ND-EjdPozJA27:-OEUwLJy3jPYgmStgDYk:bq8vzdt) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L379)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

3. I'm trying to replicate the behavior you mention, but I can't. I don't ever see unstarred things in between the starred items, and everything sorts correctly A-z. If you can still replicate this, let me know and we can hop on a call and I can take a look with you.
4. I don't know if we can control it through props. Maybe we could add a separate issue for this, since it's more about customizing the `Command` component than having anything to do with `Get Resources`
</blockquote></details>

Note: Issues 3 and 4 seem to be related.
@Sebastian-ubs and I have found that the sorting logic when performing a search on the dropdown is controlled by a custom search algorithm in one of the underlying components on the Multi Select. This leads  to very unpredictable sorting results. A separate issue will be opened to investigate this.

![image.png](https://files.reviewableusercontent.io/images/reviewable/108285668/7fT5YE4lc5a2uOfXa50vTBcP/image.png)


<!-- Sent from Reviewable.io -->

2024-12-20 09:31 UTC, Sebastian-ubs reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx` line 379 at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQBc9ND-EjdPozJA27:-OEYONWbDAusUzI5VVma:b-4zhh21) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/lib/platform-bible-react/src/components/advanced/filterable-resource-list/filterable-resource-list.component.tsx#L379)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Note: Issues 3 and 4 seem to be related.
@Sebastian-ubs and I have found that the sorting logic when performing a search on the dropdown is controlled by a custom search algorithm in one of the underlying components on the Multi Select. This leads  to very unpredictable sorting results. A separate issue will be opened to investigate this.

![image.png](https://files.reviewableusercontent.io/images/reviewable/108285668/7fT5YE4lc5a2uOfXa50vTBcP/image.png)
</blockquote></details>

I've created https://github.com/paranext/paranext-core/issues/1410 and https://github.com/paranext/paranext-core/issues/1411. As the bug about starred item selection was fixed, I am resolving this.


<!-- Sent from Reviewable.io -->

2024-12-20 09:37 UTC, Sebastian-ubs commented
please still fix the issue of the wrong filed used for filtering the type popover
![image](https://github.com/user-attachments/assets/58678ac3-6968-4e34-be35-2281a14bde1a)

2024-12-20 14:03 UTC, Sebastian-ubs approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399#-:-OEZMcJxCWU9sPgDUiaB:bnfp4nl)* status: 9 of 21 files reviewed, 1 unresolved discussion (waiting on @lyonsil and @rolfheij-sil)



<!-- Sent from Reviewable.io -->

2024-12-20 14:11 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399)* status: 9 of 21 files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`extensions/src/platform-home/contributions/localizedStrings.json` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/1399#-OEQ5ptFA93o1JLFeiAY:-OEZPEY26TBm8NLzYgZu:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/b233fc2125dca698114829534a8327f44773e5ff/extensions/src/platform-home/contributions/localizedStrings.json#L)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Since we don't have a way for libraries to contribute localization files, then I think any localization strings used by the react lib and utilities lib should be included in the platform. Please move them out of the extensions and into the main localization file for the platform.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-07 16:50 UTC, lyonsil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 9 files at r3, 3 of 3 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1399#-:-OG0f4kl2DHpwJQA5O9v:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-07 16:50 UTC, merged