Fix race condition with registering webview postMessage calls over RPC
paranext/paranext-core pull request #1406
Opened 2024-12-18 16:29 UTC by lyonsil

2025-01-03 23:26 UTC, tjcouch-sil requested changes
Awesome! Good sleuthing, and nice job with the fix! Very elegant. Thanks for the hard work on it. Handful of comments.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1406#-:-OFiUNjZ3ji0RJ_7rMVL:btqxvvp)* status: all files reviewed, 6 unresolved discussions (waiting on @lyonsil)

___
*[`src/renderer/components/web-view.component.tsx` line 72 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiHyOR5s_UVfhJYKI-:-OFiHyOR5s_UVfhJYKI0:b-fo6esz) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/src/renderer/components/web-view.component.tsx#L72)):*
> ```XML
> 
>   const postMessageCallback = useCallback(
>     ([webViewNonce, message, targetOrigin]: Parameters<WebViewMessageRequestHandler>) => {
> ```

FYI if you want to get rid of the array and use the parameters directly, you can do this:

```typescript
type StuffType = (first: number, second: number, third: string) => void;
function DoStuff(...[first, second, third]: Parameters<StuffType>) {
    console.log(first, second, third);
}
```

Not necessary; just in case you were thinking about it.
___
*[`src/renderer/components/web-view.component.tsx` line 93 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiOGQJ6tVpWzB-7U73:-OFiOGQJ6tVpWzB-7U74:bgpjzpa) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/src/renderer/components/web-view.component.tsx#L93)):*
> ```XML
>   type UnsubscriberContainer = { unsub: UnsubscriberAsync | undefined };
> 
>   useEffect(() => {
> ```

`registrationPromises` needs to be cleaned up for this web view when the web view is unmounted, right? Can you add a new `useEffect` with no dependencies that basically just runs `registrationPromises.cleanupPromiseChain` in its deconstructor? Or maybe there's a timing issue with this `useEffect` that warrants further consideration.

It seems `cleanupPromiseChain` doesn't work if new promises get added after it is run. It seems this `useEffect` probably has the ability to add promises after unmount, so this is a timing problem. Can `cleanupPromiseChain` be refactored so that, if it determines in the `finally` that it is not the current promise, it can be set up to listen to whatever the new promise is and try cleaning up after that one?
___
*[`src/renderer/components/web-view.component.tsx` line 94 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiKlyD--85IIAcqJKE:-OFiKlyD--85IIAcqJKF:bda79kt) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/src/renderer/components/web-view.component.tsx#L94)):*
> ```XML
> 
>   useEffect(() => {
>     let isMounted = true;
> ```

Since this `useEffect` has stuff in its dependency array, the component will not necessarily be unmounted when its destructor runs. It will mean the current values are outdated and may mean the component is unmounted. Please rename this variable to avoid the confusion. I usually name variables similar to this one`isCurrent` or something like that. Though this variable means something slightly different - something like "is this request handler current or already registered and needs to be unregistered immediately". Maybe I'd recommend `isThisRequestHandlerCurrentOrAlreadyRegisteredAndNeedsToBeUnregisteredImmediately`. Really channel our inner Java gurus.
___
*[`src/renderer/components/web-view.component.tsx` line 150 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiLWAMB42cUdHWYw66:-OFiLWAMB42cUdHWYw67:b-p58e6p) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/src/renderer/components/web-view.component.tsx#L150)):*
> ```XML
>     return () => {
>       registrationPromises.addPromise(id, async () => {
>         isMounted = false;
> ```

I had trouble parsing through all the `isMounted`, `unsubContainer.unsub`, and promise stuff here and got it only after a while of concentrated effort. It would be helpful to have a few comments talking through the intentions behind these lines (mostly thinking about 141-151).

For example, it took a long time to figure out that it is appropriate that this line `isMounted = false` should indeed be in this async function and not outside it.
___
*[`lib/platform-bible-utils/src/promise-chaining-map.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFhtG1K1YieDhFxBhVZ:-OFhtG1K1YieDhFxBhV_:b7cxr2n) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/lib/platform-bible-utils/src/promise-chaining-map.ts#L26)):*
> ```XML
>    * Creates a new PromiseChainingMap
>    *
>    * @param logger Object with a `warn` method that will be called when a promise rejects
> ```

Would be nice to mention that this is `console` by default if you make other changes in utils, but maybe not worth it otherwise haha
___
*[`lib/platform-bible-utils/src/promise-chaining-map.ts` line 40 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiBFCv9cVpWCmOpP8F:-OFiBFCw0Iq6RXdseTP8:bsztvb7) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/lib/platform-bible-utils/src/promise-chaining-map.ts#L40)):*
> ```XML
>    * @param promiseFunction Function that returns a promise to add to the chain
>    */
>   addPromise(key: TKey, promiseFunction: () => Promise<unknown>): void {
> ```

I pictured this method by its name as receiving a `Promise`, not a promise function. Should this be renamed to something more like `runAsyncFunction` or `addPromiseFunction` or something? Or maybe just reformat to receive a `Promise`?
___
*[`lib/platform-bible-utils/src/promise-chaining-map.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiBid58VsJu9_FykzK:-OFiBid58VsJu9_FykzL:bed34bq) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/lib/platform-bible-utils/src/promise-chaining-map.ts#L42)):*
> ```XML
>   addPromise(key: TKey, promiseFunction: () => Promise<unknown>): void {
>     const currentPromise = this.map.get(key);
>     this.map.set(key, currentPromise ? currentPromise.then(promiseFunction) : promiseFunction());
> ```

Might it be worth adding a `.catch` on this `.then` that logs a warning with the error? Or maybe add a new parameter of error handler and just log warning by default? Adding an error handler parameter would allow people to decide whether they want to continue the promise chain or throw out of it if there's a problem.
___
*[`lib/platform-bible-utils/src/promise-chaining-map.ts` line 63 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiEBkJ4JBgFupQw5S0:-OFiEBkJ4JBgFupQw5S1:bpns9uh) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/lib/platform-bible-utils/src/promise-chaining-map.ts#L63)):*
> ```XML
>    * @param key Unique key to identify a distinct promise chain
>    */
>   private cleanupPromiseChain(key: TKey): void {
> ```

Maybe worth adding a new parameter of error handler here too? And log by default like it is now


<!-- Sent from Reviewable.io -->

2025-01-06 17:30 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1406)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`lib/platform-bible-utils/src/promise-chaining-map.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFhtG1K1YieDhFxBhVZ:-OFwSXjZ5JkxdVVJxAp9:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/lib/platform-bible-utils/src/promise-chaining-map.ts#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Would be nice to mention that this is `console` by default if you make other changes in utils, but maybe not worth it otherwise haha
</blockquote></details>

Done
___
*[`lib/platform-bible-utils/src/promise-chaining-map.ts` line 40 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiBFCv9cVpWCmOpP8F:-OFwSd960dbEiZNFBpSh:btnz4t6) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/lib/platform-bible-utils/src/promise-chaining-map.ts#L40)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I pictured this method by its name as receiving a `Promise`, not a promise function. Should this be renamed to something more like `runAsyncFunction` or `addPromiseFunction` or something? Or maybe just reformat to receive a `Promise`?
</blockquote></details>

Renamed to `addPromiseFunction`.
___
*[`lib/platform-bible-utils/src/promise-chaining-map.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiBid58VsJu9_FykzK:-OFwT6RBCwfBBR1HMvWC:bkwmair) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/lib/platform-bible-utils/src/promise-chaining-map.ts#L42)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Might it be worth adding a `.catch` on this `.then` that logs a warning with the error? Or maybe add a new parameter of error handler and just log warning by default? Adding an error handler parameter would allow people to decide whether they want to continue the promise chain or throw out of it if there's a problem.
</blockquote></details>

Error handling is done within `cleanupPromiseChain()` on the next line. I think starting with a simple implementation that matches the current use case is enough. If something more complex is helpful/useful later, we can always add the functionality at that time and set defaults to match the current behavior.
___
*[`lib/platform-bible-utils/src/promise-chaining-map.ts` line 63 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiEBkJ4JBgFupQw5S0:-OFwUOze6uCX10lA9mw5:bta4unu) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/lib/platform-bible-utils/src/promise-chaining-map.ts#L63)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Maybe worth adding a new parameter of error handler here too? And log by default like it is now
</blockquote></details>

Same comment as above - Let's start with the simple case and add complexity as it is needed later (if it ever arises).
___
*[`src/renderer/components/web-view.component.tsx` line 93 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiOGQJ6tVpWzB-7U73:-OFwX0TvCjD51d7irsik:b-6qugri) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/src/renderer/components/web-view.component.tsx#L93)):*
> `registrationPromises` needs to be cleaned up for this web view when the web view is unmounted, right?

Cleanup of the map should live solely within the map. That's why `cleanupPromiseChain` is private. Nothing outside of the map should be calling `cleanupPromiseChain`. I don't know what timing issue you're talking about.

> It seems `cleanupPromiseChain` doesn't work if new promises get added after it is run.

Can you be more specific about what you don't think is working? From my testing this works as I would expect (i.e., all registrations and unregistrations happen sequentially between different components with the same ID. There is no timing problem from what I've seen.
___
*[`src/renderer/components/web-view.component.tsx` line 94 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiKlyD--85IIAcqJKE:-OFwZSLfEGnHd5Zv9FTH:bua5pwn) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/src/renderer/components/web-view.component.tsx#L94)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since this `useEffect` has stuff in its dependency array, the component will not necessarily be unmounted when its destructor runs. It will mean the current values are outdated and may mean the component is unmounted. Please rename this variable to avoid the confusion. I usually name variables similar to this one`isCurrent` or something like that. Though this variable means something slightly different - something like "is this request handler current or already registered and needs to be unregistered immediately". Maybe I'd recommend `isThisRequestHandlerCurrentOrAlreadyRegisteredAndNeedsToBeUnregisteredImmediately`. Really channel our inner Java gurus.
</blockquote></details>

I flipped the meaning and renamed to `cleanupHasRun`. 
___
*[`src/renderer/components/web-view.component.tsx` line 150 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiLWAMB42cUdHWYw66:-OFw_rsA4MCl_pIrk8vH:b-s7ck0x) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/src/renderer/components/web-view.component.tsx#L150)):*
> I had trouble parsing through all the ...  stuff here and got it only after a while of concentrated effort.

This describes my normal experience with most React-related code. I added more comments, but I'm not confident it will change the experience for others.


<!-- Sent from Reviewable.io -->

2025-01-06 18:22 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks for the adjustments and clarifications!

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1406#-:-OFwqfACAXQpKC5lpw5V:b-nai1b3)* status: all files reviewed, 1 unresolved discussion

___
*[`lib/platform-bible-utils/src/promise-chaining-map.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiBid58VsJu9_FykzK:-OFwpZ3hE3inMMp6wyZ3:b-449568) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/lib/platform-bible-utils/src/promise-chaining-map.ts#L42)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Error handling is done within `cleanupPromiseChain()` on the next line. I think starting with a simple implementation that matches the current use case is enough. If something more complex is helpful/useful later, we can always add the functionality at that time and set defaults to match the current behavior.
</blockquote></details>

Oh, I totally misread this. I didn't realize `cleanupPromiseChain` is done here, so I didn't realize everything was automatically cleaned up. Sorry about that.
___
*[`src/renderer/components/web-view.component.tsx` line 93 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiOGQJ6tVpWzB-7U73:-OFwqGHWCJKwGGDjSPH7:b-zb2a58) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/src/renderer/components/web-view.component.tsx#L93)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

> `registrationPromises` needs to be cleaned up for this web view when the web view is unmounted, right?

Cleanup of the map should live solely within the map. That's why `cleanupPromiseChain` is private. Nothing outside of the map should be calling `cleanupPromiseChain`. I don't know what timing issue you're talking about.

> It seems `cleanupPromiseChain` doesn't work if new promises get added after it is run.

Can you be more specific about what you don't think is working? From my testing this works as I would expect (i.e., all registrations and unregistrations happen sequentially between different components with the same ID. There is no timing problem from what I've seen.
</blockquote></details>

Resolved by clearing up my misunderstanding about `cleanupPromiseChain`


<!-- Sent from Reviewable.io -->

2025-01-06 19:17 UTC, tjcouch-sil requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1406)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/renderer/components/web-view.component.tsx` line 94 at r1](https://reviewable.io/reviews/paranext/paranext-core/1406#-OFiKlyD--85IIAcqJKE:-OFx26ZS8ShhcdHiXPh3:bybjmjx) ([raw file](https://github.com/paranext/paranext-core/blob/1c0be3ea74561c6d59a8cd24d86af46cb93d9555/src/renderer/components/web-view.component.tsx#L94)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I flipped the meaning and renamed to `cleanupHasRun`.
</blockquote></details>

Thanks! Sorry for the delay


<!-- Sent from Reviewable.io -->

2025-01-06 19:17 UTC, tjcouch-sil approved these changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-06 19:19 UTC, merged