Update Home web-view UI to Phase 1 UX design
paranext/paranext-core pull request #1414
Opened 2024-12-23 17:48 UTC by rolfheij-sil

2025-01-09 12:03 UTC, Sebastian-ubs commented
Hi @rolfheij-sil,

thank you for implementing this.
I am testing with latest commit a88a60c6841e6265a8bf3d9d0225df30680972ee

**Issues I found / expect for Home:**
(unfortunately I was not able to get any new resources, so I could not check these)
1. Will Home refresh immediately when new resources are installed?
Otherwise I guess we would need some refresh button in Home or a close button in Get Resources that would trigger the refresh.
2. The "Clear search" button clears the table filtering, but leaves the filter text inside the search box
3. Short name seems not to be matched by search. "NIV84" does not show up when filtering for "niv".
4. Language name seems not to be matched by search. Searching for "Ancient" does not show an entry that states "Ancient Greek" as language

|||
|-|-|
|![grafik](https://github.com/user-attachments/assets/c43ba292-b4ca-4fa4-896c-39271dc9fbfa)|![grafik](https://github.com/user-attachments/assets/c103ac97-4364-48a0-85de-679840fb6b2e)|


**Issues I found in Get Resources:**
1. loading spinner overlaps table header
![Screenshot 2025-01-09 112658](https://github.com/user-attachments/assets/97c6bfe7-fe63-41da-aca2-775aad683119)
2. When clicking "Get", I was unable to download any resource (even not those dated 20xx), but all only show the endless loading spinner 😕
On the console I got the following error:
    > 11:31:04 JSON-RPC Request error (-32000): Object reference not set to an instance of an object. [at transport C:\code\COPY-paranext-core\.erb\dll\main.bundle.dev.js:4207:15]
    
    Not sure if this is related.
3. While filtered for "gre" there are 2 or even 3 entries with the same short and full name "Pulu Yemonga Ungu Kondemo" and their "Get" button is not clickable.
On the console I see some  `REST GetStreaming result` followed by
    > Warning: Encountered two children with the same key, `ubuNTPulu Yemonga Ungu Kondemo`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

2025-01-09 12:05 UTC, Sebastian-ubs commented
The ubuNT somehow seems to sneek in also when not expected
![grafik](https://github.com/user-attachments/assets/b274ba8c-8ff8-4f4f-9610-74e5ff3ecb52)

2025-01-09 12:09 UTC, Sebastian-ubs commented
Also launching Get Resources with the currently installed languages pre-selected seems not to work
![grafik](https://github.com/user-attachments/assets/cd1abad4-6d40-4dcc-8f65-676da0f79826)

2025-01-10 12:16 UTC, Sebastian-ubs commented
As requested I have added separate issues for the problems I found with Get Resources:
- [PT-1667 Unable to install any resource with GetResources in Platform.Bible](https://paratextstudio.atlassian.net/browse/PT-1667)
- [PT-1668 Get Resources / Table component: Loading spinner overlaps table header](https://paratextstudio.atlassian.net/browse/PT-1668)
- commented in [PT-1585 Get Resources: Follow up](https://paratextstudio.atlassian.net/browse/PT-1585) that the issue with duplicate short names already effects the ui before "Get" can even be clicked

In case any of the mentioned issues in Home will not be addressed in this PR and you want me to file a separate issue, please let me know.

2025-01-24 08:48 UTC, Sebastian-ubs commented
Hi Rolf, please let me know when you have a state I could/should look at and try.

2025-01-28 13:39 UTC, rolfheij-sil reviewed
Thanks for checking Sebastian!
I know we already discussed most of these issues, but for posterity:

Home:
1. No, not currently. I don't know if there's an easy way to do this. Let's pick it up in Phase 2.
2. Interesting. That seems to be a design flaw in the SearchBar. The state of the search input is managed inside the component, and we can't directly manipulate it from the outside. The only way to change it is by typing in the search field, or clicking the X. We should probably open a ticket for this.
3. Fixed
4. Fixed

Get Resources:
1. Strange. Why are there two spinners? Do you still see this behavior?
2. That shouldn't happen... If you still get this error, best to create a bug report for it.
3. I can't reproduce this unfortunately. Can you?
4. I can't reproduce this either, but it seems like it's the result of a situation where you had items with duplicate keys in your list

> Reviewed 71 of 97 files at r1, 6 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414#-:-OHh5_ak0jqIB-VKBAqn:b-jenaqy)* status: 0 of 99 files reviewed, 4 unresolved discussions

___
*[`extensions/src/platform-manage-resources/src/types/platform-manage-resources.d.ts` line 30 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh7Rt96onNlampsj9e:-OHh7Rt96onNlampsj9f:bnyub5w) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/extensions/src/platform-manage-resources/src/types/platform-manage-resources.d.ts#L30)):*
> ```XML
>      * @returns True if any credentials are configured, false if not.
>      */
>     isGetDblResourcesAvailable: (uid: string) => Promise<boolean>;
> ```

The `uid` parameter is a dummy argument. See my reviewable note on `DBLDouwnloadeDataProvider.cs`
___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 66 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh6rqy6JZd8ogQ01Rc:-OHh6rqy6JZd8ogQ01Rd:b5deetj) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/extensions/src/platform-manage-resources/src/home.web-view.tsx#L66)):*
> ```XML
> // This type is copied from paratext-bible-send-receive.d.ts
> // Is there a better way to access this type?
> type EditedStatus = undefined | '' | 'edited' | 'new' | 'unregistered';
> ```

This type is copied from `paratext-bible-send-receive.d.ts`. Is there a better way to access this type?
___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 108 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh7Kfm1rV4BLQ9qt7P:-OHh7Kfn57DVASDIHwpF:b-uede1k) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/extensions/src/platform-manage-resources/src/home.web-view.tsx#L108)):*
> ```XML
>       if (dblResourcesProvider) {
>         setShowGetResourceButton(
>           await dblResourcesProvider.isGetDblResourcesAvailable('Why do we need a parameter here?'),
> ```

See my reviewable note on `DBLDouwnloadeDataProvider.cs`
___
*[`c-sharp/Projects/DigitalBibleLibrary/DblDownloadableDataProvider.cs` line 79 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh6GLzAuQ7bt9Xgl-n:-OHh6GLzAuQ7bt9Xgl-o:b-9i07un) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/c-sharp/Projects/DigitalBibleLibrary/DblDownloadableDataProvider.cs#L79)):*
> ```Smalltalk
>     /// True if any credentials are configured, false if not.
>     /// </returns>
>     private bool IsGetDblResourcesAvailable(string _unused)
> ```

Ideally `_unused` shouldn't be here, but the function does not work when I define it 0 parameters.

@lyonsil Do you know what might be the matter here?


<!-- Sent from Reviewable.io -->

2025-01-28 16:39 UTC, Sebastian-ubs reviewed
Thank you Rolf, I have just pulled latest updates from your branch and checked:

Regarding Home
1+2: WAITING FOR YOU: will you file an issue for it?
3+4: FIXED: can confirm to be fixed

Regarding Get Resources
1. EXISTING: it's a z-index problem of spinner vs table header &rarr; see PT-1668 Get Resources / Table component: Loading spinner overlaps table header
![image.png](https://files.reviewableusercontent.io/images/reviewable/141921979/SLBjSyrpL8YpQvOO7IZjwj6A/image.png)
2. PARTIALLY: is PT-1667 "Unable to install any resource with GetResources in Platform.Bible", which is fixed by removing the "Get Resources" button in Platform - still the menu entry exists, which is good for testing, but bad for the final product, so this should go away.
- Reg. the menu entry for home: Will check with the UX team if we like to rename home or also link it from different menu entries like "Open [...]"
3. QUESTION: seems to be fixed. However ubuNT now is completely gone. Is this expected?
4. WAITING FOR YOU: still exists: GetResources is not launched with my installed resources selected as initial filter
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/141921979/TEISbwCX0GWgE_rFqpacTHgV/image.png)
5. NEW: @ianhewubs mentioned that "DBL resource" is not a valid type
![image copy 2.png](https://files.reviewableusercontent.io/images/reviewable/141921979/5b5MYBoPDw02V1v50M4fPk1u/image.png)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414#-:-OHhiWv_6zVNUZIl7sX8:b-zac9h1)* status: 0 of 106 files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil)



<!-- Sent from Reviewable.io -->

2025-01-29 22:01 UTC, lyonsil requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414)* status: 0 of 106 files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil)

___
*[`c-sharp/Projects/DigitalBibleLibrary/DblDownloadableDataProvider.cs` line 79 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh6GLzAuQ7bt9Xgl-n:-OHo3FPLA5x33Qdr_Z3O:b-6uhl06) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/c-sharp/Projects/DigitalBibleLibrary/DblDownloadableDataProvider.cs#L79)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Ideally `_unused` shouldn't be here, but the function does not work when I define it 0 parameters.

@lyonsil Do you know what might be the matter here?
</blockquote></details>

In `platform-manage-resources.d.ts` I see this:
```ts
    /**
     * Detects if credentials for the DBL have been configured or not. Does not check if they are
     * valid or not.
     *
     * @returns True if any credentials are configured, false if not.
     */
    isGetDblResourcesAvailable: (uid: string) => Promise<boolean>;
```

And in `home.web-view.tsx` I see this:
```ts
          await dblResourcesProvider.isGetDblResourcesAvailable('Why do we need a parameter here?'),
```

The DTS file is what forces the parameter to exist in the webview. Because you pass along a parameter in the webview, there is a parameter the C# JSONRPC library notices. I believe the JSONRPC library will only call functions if the names and number of parameters match (unless some of the parameters are optional). If you remove the parameter from the DTS file and TSX file, then I think you can (and will have to) remove the parameter in the CS file.


<!-- Sent from Reviewable.io -->

2025-01-29 22:02 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414)* status: 0 of 106 files reviewed, 5 unresolved discussions (waiting on @rolfheij-sil)

___
*[`c-sharp/Projects/DigitalBibleLibrary/DblDownloadableDataProvider.cs` line 81 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHo4W4yBdo4Pg8IonGG:-OHo4W4yBdo4Pg8IonGH:b-332ahi) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/c-sharp/Projects/DigitalBibleLibrary/DblDownloadableDataProvider.cs#L81)):*
> ```Smalltalk
>     private bool IsGetDblResourcesAvailable(string _unused)
>     {
>         return DblResourcePasswordProvider.IsPassWordAvailable();
> ```

Minor nit - normally "password" is considered a single word, so the W doesn't need to be capitalized.


<!-- Sent from Reviewable.io -->

2025-01-29 23:29 UTC, tjcouch-sil requested changes
Note: Didn't have time to finish up the review before taking off. Posted what I had, and I will return to this tomorrow! :)

Unfortunately, because of templates and updating from templates and such, we cannot simply rename extension folders. You have a few options:

1. Leave the extension name. Simple and easy, but obviously you don't accomplish the name change
2. Rename the extension in the manifest and such but leave the folder name. Advantage of seeing the proper extension name in the app but still keep file history. Actually I'm not 100% sure types would work if you did this. Would be worth testing if you want to do this
3. Update the extension from the templates to get its files up-to-date with the template. Then move the whole extension folder somewhere else. Commit the deletion of all the files. The run `npm create-extension` with the new folder name. Then move all the files from the old (moved) extension folder into the new extension folder. Commit. This has the benefit of fully changing everything, but you lose history on all the extension files.

You're free to choose whichever you want. However, I'd suggest it might be nice to put everything in `platform-home` instead of moving to a new folder `platform-manage-resources`. This way, it's easy to see where the home page comes from, and it's very likely we will keep the home page very long-term but quite likely the way we get and manage "resources" may change over time (particularly the underlying hookups more than the UI). But it's not really a clear thing and as such is kinda a toss-up. But leaving everything in `platform-home` would remove the trouble of having to create a new extension and such.

![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/EFCv_-xv7X60R05WvfHCRRgG/image.png)

> Reviewed 47 of 97 files at r1, 2 of 12 files at r2, 1 of 9 files at r4, 2 of 4 files at r5, 1 of 1 files at r6, 1 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414#-:-OHnn5LX5HJD_IFpwxre:bens8kj)* status: 54 of 106 files reviewed, 7 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 66 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh6rqy6JZd8ogQ01Rc:-OHoDzwm6_WgBiz5anAH:b-nbhkvy) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/extensions/src/platform-manage-resources/src/home.web-view.tsx#L66)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

This type is copied from `paratext-bible-send-receive.d.ts`. Is there a better way to access this type?
</blockquote></details>

I guess you could put this type in this extension's type declarations and pull it in where you need it in the S/R extension...?
___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 108 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh7Kfm1rV4BLQ9qt7P:-OHoEW0e--4bpezQ9cxf:b-149ecl) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/extensions/src/platform-manage-resources/src/home.web-view.tsx#L108)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

See my reviewable note on `DBLDouwnloadeDataProvider.cs`
</blockquote></details>

Is "Douwnloade" how you spell it in Dutch? ;)
___
*[`-- commits` line 173 at r7](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHnpc7W2XIn-t0jgE76:-OHnpc7W2XIn-t0jgE77:b-796dp5):*
This is very long history. Do you know if you are able to squash all these commits together without any adverse effects? Or at least most of them (maybe excluding the rename step to keep the file rename intact)?

Note you should not squash updates from templates, so you will need to be very careful with the history if you end up doing option 3 I presented in the main conversation.
___
*[`c-sharp/Projects/DigitalBibleLibrary/DblResourcePasswordProvider.cs` line 18 at r7](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHns80_EOTHxXUpEPqA:-OHns80_EOTHxXUpEPqB:b-aa8y7h) ([raw file](https://github.com/paranext/paranext-core/blob/00acdf0f7b1d65445ae5c70eedf8eafad02f7415/c-sharp/Projects/DigitalBibleLibrary/DblResourcePasswordProvider.cs#L18)):*
> ```Smalltalk
>     public static bool IsPassWordAvailable()
>     {
>         if (RegistrationInfo.DefaultUser.IsValid)
> ```

Shouldn't this guard clause be flipped to match the logic of `GetPassword`?

So it would be "if you don't have a valid registration, you're definitely not accessing DBL. If you do have a valid registration, let's see if you have the password"


<!-- Sent from Reviewable.io -->

2025-01-30 18:20 UTC, rolfheij-sil reviewed
Thanks. I knew renaming was a big no-no, so I thought I hadn't done that. Appears that I did, though.
I've renamed the extension back to`platform-get-resources`.

Note that I haven't fixed the issues related to checking if the component is mounted after running async code

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414#-:-OHsH_rs53l4w9LyMQbt:bc4kjfs)* status: 63 of 106 files reviewed, 8 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`-- commits` line 173 at r7](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHnpc7W2XIn-t0jgE76:-OHsKTzP8jafV7lU3wnh:byc3xvj):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is very long history. Do you know if you are able to squash all these commits together without any adverse effects? Or at least most of them (maybe excluding the rename step to keep the file rename intact)?

Note you should not squash updates from templates, so you will need to be very careful with the history if you end up doing option 3 I presented in the main conversation.
</blockquote></details>

Yep, I'll try to squash 'em
___
*[`c-sharp/Projects/DigitalBibleLibrary/DblDownloadableDataProvider.cs` line 79 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh6GLzAuQ7bt9Xgl-n:-OHsKaCP5pq-1wzle3t1:b7rq2fd) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/c-sharp/Projects/DigitalBibleLibrary/DblDownloadableDataProvider.cs#L79)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

In `platform-manage-resources.d.ts` I see this:
```ts
    /**
     * Detects if credentials for the DBL have been configured or not. Does not check if they are
     * valid or not.
     *
     * @returns True if any credentials are configured, false if not.
     */
    isGetDblResourcesAvailable: (uid: string) => Promise<boolean>;
```

And in `home.web-view.tsx` I see this:
```ts
          await dblResourcesProvider.isGetDblResourcesAvailable('Why do we need a parameter here?'),
```

The DTS file is what forces the parameter to exist in the webview. Because you pass along a parameter in the webview, there is a parameter the C# JSONRPC library notices. I believe the JSONRPC library will only call functions if the names and number of parameters match (unless some of the parameters are optional). If you remove the parameter from the DTS file and TSX file, then I think you can (and will have to) remove the parameter in the CS file.
</blockquote></details>

Works with 0 parameters now. Thanks for the help.
___
*[`c-sharp/Projects/DigitalBibleLibrary/DblDownloadableDataProvider.cs` line 81 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHo4W4yBdo4Pg8IonGG:-OHsKkXS3eq7Cc95B58j:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/c-sharp/Projects/DigitalBibleLibrary/DblDownloadableDataProvider.cs#L81)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Minor nit - normally "password" is considered a single word, so the W doesn't need to be capitalized.
</blockquote></details>

Done.
___
*[`c-sharp/Projects/DigitalBibleLibrary/DblResourcePasswordProvider.cs` line 18 at r7](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHns80_EOTHxXUpEPqA:-OHsLdwq5JC1ptZsBUWA:b-8sik3p) ([raw file](https://github.com/paranext/paranext-core/blob/00acdf0f7b1d65445ae5c70eedf8eafad02f7415/c-sharp/Projects/DigitalBibleLibrary/DblResourcePasswordProvider.cs#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Shouldn't this guard clause be flipped to match the logic of `GetPassword`?

So it would be "if you don't have a valid registration, you're definitely not accessing DBL. If you do have a valid registration, let's see if you have the password"
</blockquote></details>

Done, agreed.
___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 66 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh6rqy6JZd8ogQ01Rc:-OHsMI-i81IJS2kW3w0l:b-e0xvq9) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/extensions/src/platform-manage-resources/src/home.web-view.tsx#L66)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I guess you could put this type in this extension's type declarations and pull it in where you need it in the S/R extension...?
</blockquote></details>

Done. I haven't updated the S/R extension yet. It's on my to-do list
___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 108 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh7Kfm1rV4BLQ9qt7P:-OHsMUdHDT1pwulk_6OH:b-zhvsbd) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/extensions/src/platform-manage-resources/src/home.web-view.tsx#L108)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is "Douwnloade" how you spell it in Dutch? ;)
</blockquote></details>

Nope, I just can't type.
Download is just Download in Dutch. 90% of words added to the Dutch language over the past years are just English words :joy:  
It gets interesting with verbs. 'To update' is a verb in Dutch now, and its conjugations are atrocious.
'The updated files' -> 'De geüpdatete bestanden'
___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 218 at r7](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHsEpDE-Tr-Ql0cuO-x:-OHsNfoU20RyiyVwRWoS:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/00acdf0f7b1d65445ae5c70eedf8eafad02f7415/extensions/src/platform-manage-resources/src/home.web-view.tsx#L218)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Can this and the following `useEffect` be simplified into a `useMemo`?
</blockquote></details>

Done
___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 282 at r7](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHsG8ZZ3WxTXy4WLYvG:-OHsONyj05KIhIBkAIH-:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/00acdf0f7b1d65445ae5c70eedf8eafad02f7415/extensions/src/platform-manage-resources/src/home.web-view.tsx#L282)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Could you combine this `useMemo` and `textFilteredProjects`'s `useMemo` so you only have one `useMemo`? I see `textFilteredProjects` is only used in here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-31 10:20 UTC, Sebastian-ubs reviewed
The issues I reported have been fixed or filed as different issue.
A new thing I was recognizing while looking the the browser console: after "home" is loaded, the console shows the following error 3 times:
> renderer.js:2 Uncaught (in promise) Error: getMetadataForProject wait for PDPF with platformScripture.USJ_Chapter threw! Timeout reached when waiting for wait-for-net-obj with details {"objectType":"pdpFactory","attributes":{"projectInterfaces":["platformScripture.USJ_Chapter"]}} to settle
    at Object.getMetadataForProject (renderer.js:2:500034)
    at async Ot (renderer.js:2:505547)
    at async renderer.js:75:290915

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414#-:-OHvr0NtEkFrMItc1TC4:bfzb3gs)* status: 56 of 147 files reviewed, 7 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2025-01-31 10:37 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414)* status: 56 of 147 files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

___
*[`lib/platform-bible-react/dist/index.d.ts` line 1802 at r7](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHsJ3P_7JYDlX4JdREe:-OHvos9zDrEhIBNI7Hy2:bmfxgaw) ([raw file](https://github.com/paranext/paranext-core/blob/065092dd6a85aeeb99f0cb8c53ebdddeb019b1c5/lib/platform-bible-react/dist/index.d.ts#L1802)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Though it's exceptionally unlikely anyone was using this component, this is a breaking change. Probably worth mentioning in the PR description (probably at the top so it's easy to find)

In the same vein, would be good to mention the big-picture restructure you're doing in this PR at the top of the description as well :)
</blockquote></details>

Done :)
___
*[`lib/platform-bible-react/src/components/advanced/filter.component.tsx` line 11 at r7](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHsJSuS9oyo160SFpXc:-OHvnk0mARt-k-GwTZW7:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/00acdf0f7b1d65445ae5c70eedf8eafad02f7415/lib/platform-bible-react/src/components/advanced/filter.component.tsx#L11)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Would be nice to have a description explaining what this is and does. Also how it differs from the `MultiSelectComboBox` (probably best to include a link to it like `{@link MultiSelectComboBox}`)

And description of the new prop in `FilterProps`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-31 10:39 UTC, rolfheij-sil reviewed
> Reviewed 11 of 138 files at r1, 7 of 10 files at r4, 7 of 11 files at r7, 13 of 120 files at r8, 1 of 1 files at r9, 77 of 105 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414)* status: 56 of 147 files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2025-01-31 10:41 UTC, rolfheij-sil reviewed
Thanks for reporting Sebastian, I will look into it.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414#-:-OHvwcAv-RC80BXPl0lx:b-ytbnm5)* status: 56 of 147 files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2025-01-31 14:38 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414)* status: 56 of 147 files reviewed, 6 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 143 at r7](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHsDPbQCLPT0CwAl7iB:-OHwmwzw0EdMjaNkjFi0:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/00acdf0f7b1d65445ae5c70eedf8eafad02f7415/extensions/src/platform-manage-resources/src/home.web-view.tsx#L143)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this is setting state after `await`, so React will get upset if it's after unmount.
</blockquote></details>

Done.
___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 173 at r7](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHsDp3W9x5hVS1QjRkf:-OHwmxrK2O2yq4EgmQvR:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/00acdf0f7b1d65445ae5c70eedf8eafad02f7415/extensions/src/platform-manage-resources/src/home.web-view.tsx#L173)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

These also need `isMounted.current` :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-31 14:41 UTC, rolfheij-sil reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414)* status: 56 of 147 files reviewed, 6 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2025-01-31 15:23 UTC, tjcouch-sil submitted a review, later dismissed
Looks great! Thanks for the improvements :)

> Reviewed 12 of 120 files at r8, 1 of 1 files at r9, 77 of 105 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414#-:-OHwxEcyAclQ3YsT3A2U:bkkqzm8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 66 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh6rqy6JZd8ogQ01Rc:-OHwtRul5Rk8TlBR-hYk:bdovrez) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/extensions/src/platform-manage-resources/src/home.web-view.tsx#L66)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Done. I haven't updated the S/R extension yet. It's on my to-do list
</blockquote></details>

Sounds great!
___
*[`extensions/src/platform-manage-resources/src/home.web-view.tsx` line 108 at r3](https://reviewable.io/reviews/paranext/paranext-core/1414#-OHh7Kfm1rV4BLQ9qt7P:-OHwtV6L7FdqM9r-2gyA:bomsdb6) ([raw file](https://github.com/paranext/paranext-core/blob/5fcacc4da77fedec0be34ecd6949c12ec578cb78/extensions/src/platform-manage-resources/src/home.web-view.tsx#L108)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Nope, I just can't type.
Download is just Download in Dutch. 90% of words added to the Dutch language over the past years are just English words :joy:  
It gets interesting with verbs. 'To update' is a verb in Dutch now, and its conjugations are atrocious.
'The updated files' -> 'De geüpdatete bestanden'
</blockquote></details>

:joy: :100: 


<!-- Sent from Reviewable.io -->

2025-01-31 16:38 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 72 of 100 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414#-:-OHxDacL-O75TJOQyg_r:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-31 16:47 UTC, lyonsil reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> I just had the one blocking issue which has been resolved. If somehow I'm still blocking I don't know why/how. Maybe this will fix it?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1414#-:-OHxFXGD5tTDdCjXaqPe:b-wdx7bm)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-31 16:51 UTC, merged

2025-01-31 17:35 UTC, Sebastian-ubs commented
awesome!