Update the network object service to modify the objects passed in
paranext/paranext-core pull request #156
Opened 2023-04-21 20:12 UTC by lyonsil

2023-04-24 14:55 UTC, tjcouch-sil requested changes
This is great work!! Thanks for all the hard work on this. I'm really looking forward to having these major improvements to network objects and data providers. I added a couple blocking comments as well as many optional comments. Please consider and make adjustments or let me know your thoughts and don't adjust :) I hope this is helpful!

> Reviewed 9 of 12 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/156#-:-NTnkPWu30fGHi7OxJCl:b-c3ymks)* status: all files reviewed, 17 unresolved discussions (waiting on @lyonsil)

___
*[`src/extension-host/extension-host.ts` line 64 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTnYwx_A69srBqHr9w3:-NTnYwx_A69srBqHr9w4:b-nd0j3q) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/extension-host/extension-host.ts#L64)):*
> ```XML
> 
> (async () => {
>   const testEHInfo = await networkObjectService.set('test-extension-host', {
> ```

Remove "info" from name
___
*[`src/extension-host/extension-host.ts` line 84 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTnZ0BqE8H3DayaYFWe:-NTnZ0BqE8H3DayaYFWf:b-nd0j3q) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/extension-host/extension-host.ts#L84)):*
> ```XML
> 
> setTimeout(async () => {
>   let testMainInfo = await networkObjectService.get<{
> ```

Remove "info" from name
___
*[`src/renderer/hooks/papi-hooks/use-data-provider.hook.ts` line 54 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTnZz_u3BOrDD4zE1kI:-NTnZz_u3BOrDD4zE1kJ:b1uuc6m) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/renderer/hooks/papi-hooks/use-data-provider.hook.ts#L54)):*
> ```XML
> ): T | undefined;
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> function useDataProvider<T extends IDataProvider<any, any, any>>(
> ```

It seems this function returns DataProviderInfo<any, any, any> now. Please change this in all the function signatures and comments about signatures.
___
*[`src/renderer/hooks/papi-hooks/use-data-provider.hook.ts` line 90 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTn_Adn9SDir8QNwcZ7:-NTn_Adn9SDir8QNwcZ8:b6uofqp) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/renderer/hooks/papi-hooks/use-data-provider.hook.ts#L90)):*
> ```XML
>   return dataProviderInfo && !isDisposed
>     ? // Type assert here - the user of this hook must make sure to provide the correct type
>       (dataProviderInfo as unknown as T)
> ```

Unless there is no other way to accomplish the typing we want without type asserting to `unknown`, we should avoid it as it entirely removes all write-time type safety from TypeScript (asserting directly without `unknown` makes sure the types are "compatible"). It seems we can avoid `unknown` here by removing the assertion here on line 90 and mentioning that `dataProviderInfo` can alternatively be `undefined` as soon as we retrieve it from `dataProviderService.get`, adding the assertion (and the explanatory comment) up on line 69:

```typescript
dataProviderSource ? dataProviderService.get(dataProviderSource) as Promise<T | undefined> : undefined;
```

That way, we do the type assert that we know should be happening as soon as we can. Previously, type asserting up on line 69 was not easy/possible (don't remember which) because the actual object with type `T` was wrapped in another object. However, now that we have the object itself, we can type assert to let TypeScript know asap that we know the resolved value from `dataProviderService.get` is either `T` or `undefined`.
___
*[`src/shared/models/network-object-info.model.ts` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTnfBLF7YXsfvOTzhOD:-NTnfBLF7YXsfvOTzhOE:b-f69gel) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L6)):*
> ```XML
> 
> /**
>  * An object of this type is returned from NetworkObjectService.get.
> ```

I think it would be useful to include a description comment of what this type is supposed to represent, not just where it is used. Something similar to `This object is retrievable by any process using NetworkObjectService.get, and any process can call its methods`.
___
*[`src/shared/models/network-object-info.model.ts` line 14 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTnfO254bOntES2YDlr:-NTnfO254bOntES2YDls:bt6mt71) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L14)):*
> ```XML
> 
> /**
>  * An object of this type is returned from NetworkObjectService.set.
> ```

I think it would be useful to include a description comment of what this type is supposed to represent, not just where it is used. Something similar to `This object is set up by NetworkObjectService.set to be retrievable by any process using NetworkObjectService.get, and any process can call its methods. However, only the code that calls `NetworkObjectService.set` can call its `dispose` method.
___
*[`src/shared/models/network-object-info.model.ts` line 24 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTne6gE2AEglbtWH2gP:-NTne6gE2AEglbtWH2gQ:b-xidl3o) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L24)):*
> ```XML
> /**
>  * An object of this type is passed into NetworkObjectService.set. Its properties related to
>  * disposal will be changed.
> ```

It seems helpful to be more specific here - maybe mention particularly that `dispose` will be layered over so it is still called.
___
*[`src/shared/models/network-object-info.model.ts` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTndr7N4MpONw-D7jvq:-NTndr7N4MpONw-D7jvr:b-8bf3sw) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L30)):*
> ```XML
>  * functions' arguments and returns must be serializable in order to be called across processes.
>  */
> export type NetworkableObject<T> = Partial<DisposableNetworkObject<T>> & {
> ```

I think it would be useful to include a description comment of what this type is supposed to represent, not just where it is used. Something similar to `Object that is able to be shared on the network` from the old comments.
___
*[`src/shared/models/network-object-info.model.ts` line 31 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTneHaN-18ke79VL2xb:-NTneHaN-18ke79VL2xc:b6hth7s) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L31)):*
> ```XML
>  */
> export type NetworkableObject<T> = Partial<DisposableNetworkObject<T>> & {
>   onDidDispose: never;
> ```

Maybe consider making a JSDoc here that mentions `onDidDispose` is created as part of making a NetworkObject and therefore it is not allowed to exist on a `NetworkableObject` so people know what's going on here a bit better.
___
*[`src/shared/models/network-object-info.model.ts` line 47 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTndZ6m1i4Ss1jATseV:-NTndZ6m1i4Ss1jATseW:bu7uzzp) ([raw file](https://github.com/paranext/paranext-core/blob/61b0143b0fcfaf7d53b4ab757f7a811bfb8313bf/src/shared/models/network-object-info.model.ts#L47)):*
> ```XML
>  * If a network object with the provided id exists remotely but has not been set up
>  * to be used on this process, this function is run in NetworkObjectService.get, and the returned object is used as a base on which to set up a
>  * NetworkObject for use on this process. This is useful  [...]

2023-04-24 18:33 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/156)* status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/extension-host/extension-host.ts` line 64 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTnYwx_A69srBqHr9w3:-NTnm_-rAYHv2XBDzYur:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/extension-host/extension-host.ts#L64)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Remove "info" from name
</blockquote></details>

done
___
*[`src/extension-host/extension-host.ts` line 84 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTnZ0BqE8H3DayaYFWe:-NTnmaWh7lIE5bHNj4gz:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/extension-host/extension-host.ts#L84)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Remove "info" from name
</blockquote></details>

done
___
*[`src/shared/models/network-object-info.model.ts` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTnfBLF7YXsfvOTzhOD:-NTo0G6g7bVSNVTClrRL:b-gn66nw) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it would be useful to include a description comment of what this type is supposed to represent, not just where it is used. Something similar to `This object is retrievable by any process using NetworkObjectService.get, and any process can call its methods`.
</blockquote></details>

I'm trying to determine a single place to put a more complete description of how network objects work and avoid splitting the docs in many places or duplicating content.  See what you think of this next set of changes.
___
*[`src/shared/models/network-object-info.model.ts` line 14 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTnfO254bOntES2YDlr:-NTo0oP6-o4zDOrAjh6w:b-gn66nw) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L14)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it would be useful to include a description comment of what this type is supposed to represent, not just where it is used. Something similar to `This object is set up by NetworkObjectService.set to be retrievable by any process using NetworkObjectService.get, and any process can call its methods. However, only the code that calls `NetworkObjectService.set` can call its `dispose` method.
</blockquote></details>

I'm trying to determine a single place to put a more complete description of how network objects work and avoid splitting the docs in many places or duplicating content.  See what you think of this next set of changes.
___
*[`src/shared/models/network-object-info.model.ts` line 24 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTne6gE2AEglbtWH2gP:-NToDdAF3zYab3D-MukN:b-gn66nw) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L24)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It seems helpful to be more specific here - maybe mention particularly that `dispose` will be layered over so it is still called.
</blockquote></details>

I'm trying to determine a single place to put a more complete description of how network objects work and avoid splitting the docs in many places or duplicating content.  See what you think of this next set of changes.
___
*[`src/shared/models/network-object-info.model.ts` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTndr7N4MpONw-D7jvq:-NToDoSK5E3ZqDb_dWh2:b-gn66nw) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L30)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it would be useful to include a description comment of what this type is supposed to represent, not just where it is used. Something similar to `Object that is able to be shared on the network` from the old comments.
</blockquote></details>

I'm trying to determine a single place to put a more complete description of how network objects work and avoid splitting the docs in many places or duplicating content.  See what you think of this next set of changes.
___
*[`src/shared/models/network-object-info.model.ts` line 31 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTneHaN-18ke79VL2xb:-NToJDTS1CzwoGyrjSKH:b-gn66nw) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L31)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Maybe consider making a JSDoc here that mentions `onDidDispose` is created as part of making a NetworkObject and therefore it is not allowed to exist on a `NetworkableObject` so people know what's going on here a bit better.
</blockquote></details>

I'm trying to determine a single place to put a more complete description of how network objects work and avoid splitting the docs in many places or duplicating content.  See what you think of this next set of changes.
___
*[`src/shared/models/network-object-info.model.ts` line 47 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTndZ6m1i4Ss1jATseV:-NToJOis2RQzL3dd4F9m:b-gn66nw) ([raw file](https://github.com/paranext/paranext-core/blob/61b0143b0fcfaf7d53b4ab757f7a811bfb8313bf/src/shared/models/network-object-info.model.ts#L47)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I also think it is useful to mention that this is especially useful for network events. Do you think it is not valuable to mention this?
</blockquote></details>

I'm trying to determine a single place to put a more complete description of how network objects work and avoid splitting the docs in many places or duplicating content.  See what you think of this next set of changes.
___
*[`src/shared/models/network-object-info.model.ts` line 48 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTncQvcDPYlgADaF4hS:-NToOILQCcse7vrc9HcP:b-15a8i5) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L48)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I could be missing something, but isn't it still useful to mark this as `T extends NetworkableObject`? Maybe `T extends NetworkableObject<unknown>` or `T extends NetworkableObject<Record<string, unknown/any>>`? Hard to tell from Reviewable what would be best or if I am missing something.
</blockquote></details>

It used to be `T extends NetworkableObject`, but `NetworkableObject` was an empty interface, so that didn't provide much meaning.  I think I removed it early on for that reason.  I am adding it back now since `NetworkableObject` has something inside of it.
___
*[`src/shared/models/network-object-info.model.ts` line 51 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTndLsf86cx5pHtwqkz:-NToJi2V0arKwEHMsgyq:bwhco35) ([raw file](https://github.com/paranext/paranext-core/blob/61b0143b0fcfaf7d53b4ab757f7a811bfb8313bf/src/shared/models/network-object-info.model.ts#L51)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think the comments removed from this function are important for explaining what's going on with the container thing, par [...]

2023-04-25 14:28 UTC, tjcouch-sil reviewed
The comment rework looks great! Thanks for the hard work on it :) Just a couple more little things

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/156#-:-NTsmR1sD7tDmcI4CNzZ:b5oodbk)* status: all files reviewed, 6 unresolved discussions (waiting on @lyonsil)

___
*[`src/shared/models/network-object-info.model.ts` line 47 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTndZ6m1i4Ss1jATseV:-NTsntL53SxEAzaIK278:b5jmqpx) ([raw file](https://github.com/paranext/paranext-core/blob/61b0143b0fcfaf7d53b4ab757f7a811bfb8313bf/src/shared/models/network-object-info.model.ts#L47)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I'm trying to determine a single place to put a more complete description of how network objects work and avoid splitting the docs in many places or duplicating content.  See what you think of this next set of changes.
</blockquote></details>

I think this event remark may not have gotten coverage in the comment rework. See below in `networkObjectService.get`'s comment - I think it may fit well in there? Or maybe it makes sense to put it here to carry it with this type. Dunno; feel free to put it wherever seems best to you.
___
*[`src/shared/models/network-object-info.model.ts` line 48 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTncQvcDPYlgADaF4hS:-NTso7SW3gNSAnQ8QPrx:b-yrvu05) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L48)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

It used to be `T extends NetworkableObject`, but `NetworkableObject` was an empty interface, so that didn't provide much meaning.  I think I removed it early on for that reason.  I am adding it back now since `NetworkableObject` has something inside of it.
</blockquote></details>

I don't see these changes yet; assuming there are type changes to come. Thanks!
___
*[`src/shared/services/data-provider.service.ts` line 37 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTngCiX4lf8RmQbywlk:-NTsndGg5iqdetvrVw-a:b-so5qh4) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/services/data-provider.service.ts#L37)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Yeah I missed some references, and I agree consistency is important here.  I moved to "name" from "type" because the values passed in aren't really types in the sense of TYPEscript.  They are names of objects that return data, and that data can have different types.  Also more than one data source could return the same data type.  If we have an actual type named `usfm` we could name the data source `usfm`,  but we could also have a source named `paratext` and another named `some-other-usfm-source` that both return `usfm` data.

If we want to go with the network object terminology, we could call these IDs instead of names.  I'd be fine with that, too.  It took me a little while to realize that "type" didn't really mean "type" which is why I changed it.  Perhaps we can talk with others at stand up to settle on the terminology?  If the group says "type" is best, then I'll switch it back to how it was.
</blockquote></details>

I think you have a great point! I think going with `id` or `dataProviderName` or something along those lines makes sense. Thanks for your insightful feedback and for being thoughtful about how to improve it!
___
*[`src/shared/services/network-object.service.ts` line 280 at r4](https://reviewable.io/reviews/paranext/paranext-core/156#-NTsjzCO3EVPMX4yrH4k:-NTsjzCO3EVPMX4yrH4l:b4nhuo9) ([raw file](https://github.com/paranext/paranext-core/blob/6e25a9246b902181cc396f40365466f802a33c1d/src/shared/services/network-object.service.ts#L280)):*
> ```XML
>  * @param createLocalObjectToProxy Function that creates an object that the network object proxy
>  * will be based upon. The object this function creates cannot have an `onDidDispose` property
>  * defined because we will ignore it and overwrite it while setting up the proxy.
> ```

We are not ignoring the `onDidDispose` here, right? `overrideOnDidDispose` throws an error if the networkable object has it.

Also, I think the comment I asked to be included about that this `LocalObjectToProxyCreator` is especially useful for creating events on network objects didn't get re-introduced.  Think it might be best to go here with these new comment reworks?
___
*[`src/shared/services/network-object.service.ts` line 320 at r4](https://reviewable.io/reviews/paranext/paranext-core/156#-NTskjgUCzcPD1TJsgL8:-NTskjgUCzcPD1TJsgL9:b-o09lvv) ([raw file](https://github.com/paranext/paranext-core/blob/6e25a9246b902181cc396f40365466f802a33c1d/src/shared/services/network-object.service.ts#L320)):*
> ```XML
>     // Setup onDidDispose so that services will know when the proxy is dead
>     const eventEmitter = new PapiEventEmitter<void>();
>     overrideOnDidDispose(baseObject, remoteProxy.proxy, eventEmitter.event);
> ```

Seeing that we have to put two different objects in here makes me wonder if the `undefined` check and `set` cache busting we did on the data provider proxy might be worth doing on the remote object proxy as well. I wonder if that will fix this problem (and would probably help prevent bugs in the future). Think we could at least put a `TODO:` in the remote object proxy to remind ourselves to add the cache busting in the future? Unless you want to do it now; that's fine for me :) just don't want to keep holding this up forever
___
*[`src/shared/services/network-object.service.ts` line 342 at r4](https://reviewable.io/reviews/paranext/paranext-core/156#-NTsluPq0hzmNNd9il6y:-NTsluPr-qXgXlmMgE9R:bml5n6m) ([raw file](https://github.com/paranext/paranext-core/blob/6e25a9246b902181cc396f40365466f802a33c1d/src/shared/services/network-object.service.ts#L342)):*
> ```XML
>  * @param id ID of the object to share on the network. All processes must use this ID to look it up.
>  * @param objectToShare The object to set up as a network object. It will have an event named
>  * `onDidDispose` added to its properties. If the object already contained a `dispose` function, a
> ```

May also be worth mentioning here that if `objectToShare` has `onDidDispose`, it will throw an error.


<!-- Sent from Reviewable.io -->

2023-04-25 16:22 UTC, lyonsil reviewed
Thanks for your helpful comments and hands on working with me on this.  This *should* cover everything (or at least very close to everything) we talked about and you commented on.  Maybe one very small thing left.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/156#-:-NTtD-OA6goZFI78qEJV:b-1trmss)* status: 6 of 17 files reviewed, 3 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`src/renderer/hooks/papi-hooks/use-data-provider.hook.ts` line 54 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTnZz_u3BOrDD4zE1kI:-NTt3ENNCaX4QA1dKipL:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/renderer/hooks/papi-hooks/use-data-provider.hook.ts#L54)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It seems this function returns DataProviderInfo<any, any, any> now. Please change this in all the function signatures and comments about signatures.
</blockquote></details>

done
___
*[`src/renderer/hooks/papi-hooks/use-data-provider.hook.ts` line 90 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTn_Adn9SDir8QNwcZ7:-NTt3RfS8HGjlrYgRFwQ:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/renderer/hooks/papi-hooks/use-data-provider.hook.ts#L90)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Unless there is no other way to accomplish the typing we want without type asserting to `unknown`, we should avoid it as it entirely removes all write-time type safety from TypeScript (asserting directly without `unknown` makes sure the types are "compatible"). It seems we can avoid `unknown` here by removing the assertion here on line 90 and mentioning that `dataProviderInfo` can alternatively be `undefined` as soon as we retrieve it from `dataProviderService.get`, adding the assertion (and the explanatory comment) up on line 69:

```typescript
dataProviderSource ? dataProviderService.get(dataProviderSource) as Promise<T | undefined> : undefined;
```

That way, we do the type assert that we know should be happening as soon as we can. Previously, type asserting up on line 69 was not easy/possible (don't remember which) because the actual object with type `T` was wrapped in another object. However, now that we have the object itself, we can type assert to let TypeScript know asap that we know the resolved value from `dataProviderService.get` is either `T` or `undefined`.
</blockquote></details>

done
___
*[`src/shared/models/network-object-info.model.ts` line 47 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTndZ6m1i4Ss1jATseV:-NTt9S_8-pVbHa4hbZsZ:b-w9s96f) ([raw file](https://github.com/paranext/paranext-core/blob/61b0143b0fcfaf7d53b4ab757f7a811bfb8313bf/src/shared/models/network-object-info.model.ts#L47)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think this event remark may not have gotten coverage in the comment rework. See below in `networkObjectService.get`'s comment - I think it may fit well in there? Or maybe it makes sense to put it here to carry it with this type. Dunno; feel free to put it wherever seems best to you.
</blockquote></details>

Can you restate the comment enhancement you'd like to see?  I'm not quite following your original comment now, and it might be due to the changes that already went in.
___
*[`src/shared/models/network-object-info.model.ts` line 48 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTncQvcDPYlgADaF4hS:-NTt3fr-4yTkm87cp4hd:bb3fcy1) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L48)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I don't see these changes yet; assuming there are type changes to come. Thanks!
</blockquote></details>

done - sorry about that
___
*[`src/shared/services/data-provider.service.ts` line 37 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTngCiX4lf8RmQbywlk:-NTtB5xe0WPplcoRkYBi:b-sqjvbm) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/services/data-provider.service.ts#L37)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think you have a great point! I think going with `id` or `dataProviderName` or something along those lines makes sense. Thanks for your insightful feedback and for being thoughtful about how to improve it!
</blockquote></details>

I started going down the path of using`id`, but that got a little confusing because of `getDataProviderObjectId`.  Rather than having a `data provider ID` that is used to generate a `data provider object ID` leading to the question "Which kind of ID am I looking at?", I went forward with "name".  So a data provider name is used to generate a data provider object ID which is used to create and register the network object.
___
*[`src/shared/services/network-object.service.ts` line 280 at r4](https://reviewable.io/reviews/paranext/paranext-core/156#-NTsjzCO3EVPMX4yrH4k:-NTt47y32K5pwoHG2w1x:b9mq2g6) ([raw file](https://github.com/paranext/paranext-core/blob/6e25a9246b902181cc396f40365466f802a33c1d/src/shared/services/network-object.service.ts#L280)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We are not ignoring the `onDidDispose` here, right? `overrideOnDidDispose` throws an error if the networkable object has it.

Also, I think the comment I asked to be included about that this `LocalObjectToProxyCreator` is especially useful for creating events on network objects didn't get re-introduced.  Think it might be best to go here with these new comment reworks?
</blockquote></details>

fixed - also, `onDidDispose` being disallowed is enforced now by tsc, not just at runtime.  It's hard to see exactly which previous comment you were referencing, but I think what is there now covers everything we discussed.  If not, please flag it again in the latest code.
___
*[`src/shared/services/network-object.service.ts` line 320 at r4](https://reviewable.io/reviews/paranext/paranext-core/156#-NTskjgUCzcPD1TJsgL8:-NTt6Nkl1AFR7IGjiq_R:b-rjh37o) ([raw file](https://github.com/paranext/paranext-core/blob/6e25a9246b902181cc396f40365466f802a33c1d/src/shared/services/network-object.service.ts#L320)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Seeing that we have to put two different objects in here makes me wonder if the `undefined` check and `set` cache busting we did on the data provider proxy might be worth doing on the remote object proxy as well. I wonder if that will fix this problem (and would probably help prevent bugs in the future). Think we could at least put a `TODO:` in the remote object proxy to remind ourselves to add the cache busting in the future? Unless you want to do it now; that's fine for me :) just don't want to keep holding this up forever
</blockquote></details>

I added the cache buster as it could help avoid future strange bugs.  It doesn't get rid of the possibility of hitting this bug again, but I changed the `get` proxy logic to avoid it instead of passing two objects to `overrideOnDidDispose` to lessen potential problems.
___
*[`src/shared/services/network-object.service.ts` line 342 at r4](https://reviewable.io/reviews/paranext/paranext-core/156#-NTsluPq0hzmNNd9il6y:-NTt9IhO5auGayyhRugM:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/6e25a9246b902181cc396f40365466f802a33c1d/src/shared/services/network-object.service.ts#L342)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

May also be worth mentioning here that if `objectToShare` has `onDidDispose`, it will throw an error.
< [...]

2023-04-25 19:06 UTC, tjcouch-sil requested changes
Very close!! Thank you for the hard work!

> Reviewed 10 of 11 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/156#-:-NTtn_nV7qeY7iHYJ1T0:b-vse87v)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`src/renderer/hooks/papi-hooks/use-data-provider.hook.ts` line 91 at r6](https://reviewable.io/reviews/paranext/paranext-core/156#-NTtfTtx93FCvzcI8983:-NTtfTtx93FCvzcI8984:b-o0t1gz) ([raw file](https://github.com/paranext/paranext-core/blob/d08d8cd7875280f9bbde88d570ac3476b0172b6f/src/renderer/hooks/papi-hooks/use-data-provider.hook.ts#L91)):*
> ```XML
>   // If we had to get a data provider, return it if it is not disposed
>   return dataProviderInfo && !isDisposed
>     ? // Type assert here - the user of this hook must make sure to provide the correct type
> ```

Please move this type assertion comment up above where the assertion is now
___
*[`src/shared/models/disposal-interface.ts` line 1 at r6](https://reviewable.io/reviews/paranext/paranext-core/156#-NTtfqmY-lk1OIAVeS-r:-NTtfqmY-lk1OIAVeS-s:b8461at) ([raw file](https://github.com/paranext/paranext-core/blob/d08d8cd7875280f9bbde88d570ac3476b0172b6f/src/shared/models/disposal-interface.ts#L1)):*
> ```XML
> import { PapiEvent } from '@shared/models/papi-event.model';
> ```

This file name does not follow our naming conventions. Consider `disposal-interface.model.ts` or something. Maybe consult Ira :)
___
*[`src/shared/models/network-object-info.model.ts` line 47 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTndZ6m1i4Ss1jATseV:-NTtgFB93swMGfm2bvk_:b98imp2) ([raw file](https://github.com/paranext/paranext-core/blob/61b0143b0fcfaf7d53b4ab757f7a811bfb8313bf/src/shared/models/network-object-info.model.ts#L47)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Can you restate the comment enhancement you'd like to see?  I'm not quite following your original comment now, and it might be due to the changes that already went in.
</blockquote></details>

I will do that in the `networkobjectService.get` area :)
___
*[`src/shared/models/network-object-info.model.ts` line 48 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTncQvcDPYlgADaF4hS:-NTtgKLi0F-7OMDut3Z_:b3tww5b) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/models/network-object-info.model.ts#L48)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

done - sorry about that
</blockquote></details>

No problem!! Just wanted to be sure to follow up on this
___
*[`src/shared/services/data-provider.service.ts` line 37 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTngCiX4lf8RmQbywlk:-NTtgerY2etVwTHAweeZ:bi0agof) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/services/data-provider.service.ts#L37)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I started going down the path of using`id`, but that got a little confusing because of `getDataProviderObjectId`.  Rather than having a `data provider ID` that is used to generate a `data provider object ID` leading to the question "Which kind of ID am I looking at?", I went forward with "name".  So a data provider name is used to generate a data provider object ID which is used to create and register the network object.
</blockquote></details>

Gotcha. Thanks for looking into it. Would you mind either updating the places where `dataType` is used elsewhere or filing a new issue to change the names please? Just want to be consistent. So in `useDataProvider` and `useData`, for example, we need to change the parameter name from `dataType` to `providerName`. (`dataType` is an overloaded parameter name in those two files in particular, so the actual function code shouldn't change.)
___
*[`src/shared/services/data-provider.service.ts` line 321 at r6](https://reviewable.io/reviews/paranext/paranext-core/156#-NTthB1HAMk4aSZxan0y:-NTthB1HAMk4aSZxan0z:b-33e2pk) ([raw file](https://github.com/paranext/paranext-core/blob/d08d8cd7875280f9bbde88d570ac3476b0172b6f/src/shared/services/data-provider.service.ts#L321)):*
> ```XML
>  */
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> async function get<T extends IDataProvider<any, any, any> & Record<string, unknown>>(
> ```

Do we need to add `Record` here? Why? It is expected that extensions that define data providers will also define a data provider type that people can use to call custom methods on those data providers. I believe adding `Record` here pretty much prevents us from enforcing write-time types.

Maybe the problem is that `onDidDispose` isn't on the type returned. So maybe we need to change `T extends IDataProvider` to `T extends DataProviderInfo`? And then the return type can be `Promise<T | undefined>`?
___
*[`src/shared/services/network-object.service.ts` line 280 at r4](https://reviewable.io/reviews/paranext/paranext-core/156#-NTsjzCO3EVPMX4yrH4k:-NTtiT0C2npXxwttMVoF:by4uyg1) ([raw file](https://github.com/paranext/paranext-core/blob/6e25a9246b902181cc396f40365466f802a33c1d/src/shared/services/network-object.service.ts#L280)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

fixed - also, `onDidDispose` being disallowed is enforced now by tsc, not just at runtime.  It's hard to see exactly which previous comment you were referencing, but I think what is there now covers everything we discussed.  If not, please flag it again in the latest code.
</blockquote></details>

I'm talking about mentioning that `createLocalObjectToProxy` is particularly useful for creating network events on a network object. Before the changes in this PR, the `LocalObjectToProxyCreator` type had the following in its comment to indicate the reason we have this:

`This is useful for setting up network events on a network object.`

You are welcome to word this any way you choose if it does seem valuable to you.
___
*[`src/shared/services/network-object.service.ts` line 358 at r6](https://reviewable.io/reviews/paranext/paranext-core/156#-NTtk9uZ53LZtGnvB8_W:-NTtk9uZ53LZtGnvB8_X:b-667ccg) ([raw file](https://github.com/paranext/paranext-core/blob/d08d8cd7875280f9bbde88d570ac3476b0172b6f/src/shared/services/network-object.service.ts#L358)):*
> ```XML
>  * @returns INetworkObjectDisposer wrapping the object to share
>  */
> const set = async <T extends object>(
> ```

Can we change this to `<T extends NetworkableObject>` and make `objectToShare` just `T`?

Also, I think we do not need `as unknown` at the bottom of this function, but I may be missing something. Does TypeScript produce an error if you remove it?


<!-- Sent from Reviewable.io -->

2023-04-25 21:59 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/156)* status: 9 of 17 files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/renderer/hooks/papi-hooks/use-data-provider.hook.ts` line 91 at r6](https://reviewable.io/reviews/paranext/paranext-core/156#-NTtfTtx93FCvzcI8983:-NTtpb2XCePm12Q9_Yf-:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/d08d8cd7875280f9bbde88d570ac3476b0172b6f/src/renderer/hooks/papi-hooks/use-data-provider.hook.ts#L91)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please move this type assertion comment up above where the assertion is now
</blockquote></details>

done
___
*[`src/shared/models/network-object-info.model.ts` line 47 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTndZ6m1i4Ss1jATseV:-NTuFndQA47Nreh2UARt:b-1yvy5c) ([raw file](https://github.com/paranext/paranext-core/blob/61b0143b0fcfaf7d53b4ab757f7a811bfb8313bf/src/shared/models/network-object-info.model.ts#L47)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I will do that in the `networkobjectService.get` area :)
</blockquote></details>

I think this is done
___
*[`src/shared/services/data-provider.service.ts` line 37 at r2](https://reviewable.io/reviews/paranext/paranext-core/156#-NTngCiX4lf8RmQbywlk:-NTuL9hoByFZrEgbLuAn:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/21b94438abaad1b4efb6ff46cf3feb797e797abb/src/shared/services/data-provider.service.ts#L37)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Gotcha. Thanks for looking into it. Would you mind either updating the places where `dataType` is used elsewhere or filing a new issue to change the names please? Just want to be consistent. So in `useDataProvider` and `useData`, for example, we need to change the parameter name from `dataType` to `providerName`. (`dataType` is an overloaded parameter name in those two files in particular, so the actual function code shouldn't change.)
</blockquote></details>

done
___
*[`src/shared/services/data-provider.service.ts` line 321 at r6](https://reviewable.io/reviews/paranext/paranext-core/156#-NTthB1HAMk4aSZxan0y:-NTuFsQ-BYykC-cKmM9o:b-ars5hs) ([raw file](https://github.com/paranext/paranext-core/blob/d08d8cd7875280f9bbde88d570ac3476b0172b6f/src/shared/services/data-provider.service.ts#L321)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do we need to add `Record` here? Why? It is expected that extensions that define data providers will also define a data provider type that people can use to call custom methods on those data providers. I believe adding `Record` here pretty much prevents us from enforcing write-time types.

Maybe the problem is that `onDidDispose` isn't on the type returned. So maybe we need to change `T extends IDataProvider` to `T extends DataProviderInfo`? And then the return type can be `Promise<T | undefined>`?
</blockquote></details>

done - we worked through removing `Record<string, unknown>` everywhere together
___
*[`src/shared/services/network-object.service.ts` line 280 at r4](https://reviewable.io/reviews/paranext/paranext-core/156#-NTsjzCO3EVPMX4yrH4k:-NTuGOpO57pns_ps_goB:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/6e25a9246b902181cc396f40365466f802a33c1d/src/shared/services/network-object.service.ts#L280)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm talking about mentioning that `createLocalObjectToProxy` is particularly useful for creating network events on a network object. Before the changes in this PR, the `LocalObjectToProxyCreator` type had the following in its comment to indicate the reason we have this:

`This is useful for setting up network events on a network object.`

You are welcome to word this any way you choose if it does seem valuable to you.
</blockquote></details>

done
___
*[`src/shared/services/network-object.service.ts` line 358 at r6](https://reviewable.io/reviews/paranext/paranext-core/156#-NTtk9uZ53LZtGnvB8_W:-NTuGTHH0p663uzUm8QN:bhxj3tl) ([raw file](https://github.com/paranext/paranext-core/blob/d08d8cd7875280f9bbde88d570ac3476b0172b6f/src/shared/services/network-object.service.ts#L358)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Can we change this to `<T extends NetworkableObject>` and make `objectToShare` just `T`?

Also, I think we do not need `as unknown` at the bottom of this function, but I may be missing something. Does TypeScript produce an error if you remove it?
</blockquote></details>

done - we worked this out together as there were complications with the `Record<string, unknown>` references
___
*[`src/shared/models/disposal-interface.ts` line 1 at r6](https://reviewable.io/reviews/paranext/paranext-core/156#-NTtfqmY-lk1OIAVeS-r:-NTuFhRRDoCxyOzT0zeh:b-hff6wv) ([raw file](https://github.com/paranext/paranext-core/blob/d08d8cd7875280f9bbde88d570ac3476b0172b6f/src/shared/models/disposal-interface.ts#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This file name does not follow our naming conventions. Consider `disposal-interface.model.ts` or something. Maybe consult Ira :)
</blockquote></details>

renamed


<!-- Sent from Reviewable.io -->

2023-04-25 22:08 UTC, merged