Added proper icon files
paranext/paranext-core pull request #17
Opened 2023-02-01 22:57 UTC by tjcouch-sil

- Renamed pt-react.png to icon.png so electron-builder will hopefully pick it up for all platforms
- Added other icon files in a new assets-excluded folder whose contents are not included in the electron-builder package (so we can put whatever we want in there)

2023-02-01 23:02 UTC, irahopkinson approved these changes
👍 LGTM

2023-02-02 13:43 UTC, FoolRunning commented
Why are there so many versions of the same icon? The .ico file should contain all the sizes and we should probably stick to using .svg files everywhere else (since that is what UX will likely want since they want a scalable UI).

2023-02-02 13:47 UTC, FoolRunning requested changes

2023-02-02 13:47 UTC, FoolRunning commented on src/main/main.ts
> +    icon: getAssetPath('icon.png'),
Github needs a comment in a code file for me to request changes, so here it is.

2023-02-02 15:04 UTC, FoolRunning approved these changes

2023-02-02 15:09 UTC, merged