Allow webviews to load static assets from extensions
paranext/paranext-core pull request #182
Opened 2023-05-10 22:08 UTC by lyonsil

2023-05-10 22:14 UTC, lyonsil reviewed
It is perhaps worth calling out that the hook added for getting extension assets isn't strictly needed.  I started with that approach, but it required allowing `data:` as a source in the security policy which might not be ideal.  More importantly, though, is that if the hook was the only way to get data it was going to be clunky to reference assets wherever needed.  Having a URL is much cleaner, so the custom `paranextension://` protocol is the expected way this will be used 95% of the time or more.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182#-:-NV6hw1T5kb0v5pAEp80:bpgb3ll)* status: 0 of 13 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-11 04:42 UTC, irahopkinson requested changes
Looking good. Love the clever protocol ellision.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182#-:-NV85GCQB4oZ8LJCbGDo:b-n8pt2e)* status: all files reviewed, 12 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/lib/quick-verse/assets/letter-q.png` line 0 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7lWm10fztgUDpiwkB:-NV7lWm10fztgUDpiwkC:blrlb9x) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/extensions/lib/quick-verse/assets/letter-q.png#L0)):*
Do we own this asset or does it have an appropraite license?
___
*[`src/main/main.ts` line 127 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV81lptCIg39epQKyoL:-NV81lptCIg39epQKyoM:bqxqrzd) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/main/main.ts#L127)):*
> ```XML
> 
>   // Set our custom protocol handler to load assets from extensions
>   extensionAssetProtocolService.initialize();
> ```

This doesn't seem to belong here since we want to separate electron and other node stuff. Can you explain why it needs to be in `createWindow` of electron?
___
*[`src/main/main.ts` line 234 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV81FiZCgQ2HVVqvsQa:-NV81Fi_CgA-VQY-3sgT:b-brba3h) ([raw file](https://github.com/paranext/paranext-core/blob/09acc4b2e0c07ab4e627bc4c1c057713e1c471aa/src/main/main.ts#L234)):*
> ```XML
> 
> (async () => {
>   await networkService.initialize();
> ```

By removing this you can't guarantee that the network service will have initialized by the time the remaining code needs to run. You either have to put them all in the same `(async () => { ... })()` block or put this line back in. Putting it back in is probably the easiest and won't take any more time if it has initialized.
___
*[`src/renderer/index.ejs` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV83tY9C0ScbTLGnE88:-NV83tY9C0ScbTLGnE89:b-zdn2ya) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/renderer/index.ejs#L13)):*
> ```EJS
>       script-src allows them to use script tags and in-line attribute scripts
>         'self' so scripts can be loaded from us
>         'paranextension:' so scripts can be loaded from installed extensions
> ```

nit: strictly this isn't in single quotes (same as `https:` isn't). Here and below.
___
*[`src/renderer/testing/test-quick-verse-heresy-panel.component.tsx` line 46 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7qHY6-6BxNh9yZsl7:-NV7qHY6-6BxNh9yZsl8:b-w2zwmk) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/renderer/testing/test-quick-verse-heresy-panel.component.tsx#L46)):*
> ```XML
>           }}
>         />
>         <p />
> ```

This looks like it got missed in clean-up and needs to be removed.
___
*[`src/shared/services/extension-asset-protocol.service.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7t0xxBxo3VRJkcNEY:-NV7t0xxBxo3VRJkcNEZ:b-83btg3) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/services/extension-asset-protocol.service.ts#L1)):*
> ```XML
> import { protocol } from 'electron';
> ```

I'm wondering if this really belongs in `shared` since it's importing stuff from `electron`? Perhaps it should go in `main/services` since it's only called from `main.ts`?
___
*[`src/shared/services/extension-asset-protocol.service.ts` line 38 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7thYF73QWfyYKQ7dV:-NV7thYF73QWfyYKQ7dW:b-cpk92p) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/services/extension-asset-protocol.service.ts#L38)):*
> ```XML
> 
> /** Lookup the MIME type to pass back to the renderer */
> function getMimeTimeForFileName(fileName: string): string {
> ```

Is that a typo? Should be `getMimeTypeForFileName`?
___
*[`src/shared/services/extension-asset-protocol.service.ts` line 38 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7uK5m3_pse8JTykDZ:-NV7uK5m3_pse8JTykD_:blbi10p) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/services/extension-asset-protocol.service.ts#L38)):*
> ```XML
> 
> /** Lookup the MIME type to pass back to the renderer */
> function getMimeTimeForFileName(fileName: string): string {
> ```

nit: `fileName` is a compound word and is therefore easier to read as `filename`.
___
*[`src/shared/services/extension-asset-protocol.service.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7ufluEz1JiNfQc0ZG:-NV7ufluEz1JiNfQc0ZH:bvyz235) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/services/extension-asset-protocol.service.ts#L42)):*
> ```XML
>   if (dotIndex > 0) {
>     const fileType: string = fileName.substring(dotIndex);
>     if (fileType in knownMimeTypes) return knownMimeTypes[fileType as keyof typeof knownMimeTypes];
> ```

Checking the file extension doesn't actually check that the file contents are the given mime type. That is probably a security concern that we should probably care about here?
___
*[`src/shared/services/extension-asset-protocol.service.ts` line 76 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7yA0fE8kQfagOIjBO:-NV7yA0fE8kQfagOIjBP:b81i0eg) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/services/extension-asset-protocol.service.ts#L76)):*
> ```XML
> 
>       // "paranextension://" is 17 characters long
>       const uri: string = request.url.substring(17);
> ```

Do we need to check that the URL actually does start with that protocol? If not how do we know that it does?

A simple `request.url.startsWith('paranextension://')` would do.
___
*[`src/shared/services/extension-asset-protocol.service.ts` line 87 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7zRUK1kN8wCc56Lrv:-NV7zRUK1kN8wCc56Lrw:b35uttl) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/services/extension-asset-protocol.service.ts#L87)):*
> ```XML
>       let extension = uri.substring(0, slash);
>       let asset = uri.substring(slash + 1);
>       if (!extension || extension.length === 0 || !asset || asset.length === 0) {
> ```

Are you sure the length checks are needed here? My understanding is that `if (!value)` will check for _undefined_, _null_ and empty string.
___
*[`src/shared/utils/http-status-codes.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7rTua9gOgNz9IFZgm:-NV7rTua9gOgNz9IFZgn:b-b3b7t) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/utils/http-status-codes.ts#L1)):*
> ```XML
> // From https://github.com/prettymuchbryce/http-status-codes/blob/master/src/status-codes.ts
> ```

I see you have grabbed one file out of an existing npm package. Is that to save space, i.e this file is ~20KB whereas the package is about 10x that? Or some other reason?


<!-- Sent from Reviewable.io -->

2023-05-11 21:16 UTC, tjcouch-sil reviewed
> Reviewed 7 of 13 files at r1, 1 of 5 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: 9 of 13 files reviewed, 9 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/lib/quick-verse/assets/letter-q.png` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7lWm10fztgUDpiwkB:-NVAIiNU4PuTWvPm-dF_:byco555) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/extensions/lib/quick-verse/assets/letter-q.png#L)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

The file came from here: https://www.veryicon.com/icons/emoticon/creative-gradient-alphanumeric-icon-cool/letter-q-6.html

On the page it says "License: Free for personal and commercial purpose."  I purposefully looked around to find something that had a license like that.  I'm happy to switch with something else if we have a preferred source for things like this.  It's not meant for long-term use.
</blockquote></details>

I think we should attribute it in the code somewhere. Could we maybe put it in an `attribution.txt` file or something in this folder?
___
*[`src/extension-host/services/asset-retrieval.service.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NVAtT9S5HtJAgjYxG7z:-NVAtT9S5HtJAgjYxG8-:bzgtdrm) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/extension-host/services/asset-retrieval.service.ts#L5)):*
> ```XML
> import path from 'path';
> 
> export default async function getAsset(extensionName: string, assetName: string): Promise<Buffer> {
> ```

I believe the `getExtensionAsset` command should change to a request and be set up in this service in a similar fashion to `addWebView` in `web-view.service.ts`. This service would move to `@shared` for now. I recommend this change because it would combine all the code related to this service into one file.

This would require using `isExtensionHost` to either send the request or actually perform the request when you call this function. I know we have discussed not liking this strategy, but I believe it is worth combining in this manner until we split the code into abstract classes and implementing classes and such as we discussed around #63, during which we could fix this code.

If you don't want to refactor like this, maybe it would be good to add a comment mentioning the link between these two places so that, when we do #63, we can integrate the code into the one service.
___
*[`src/main/main.ts` line 127 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV81lptCIg39epQKyoL:-NVAv9uLDRPC_5vri39I:bz0uv1t) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/main/main.ts#L127)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Moved to `main/services`.
</blockquote></details>

I agree that we should put this service in `main/services` - thanks for moving it :) FYI I believe all the protocol stuff is electron-specific. VSCode has a function you run to get the proper asset url for a webview asset. On desktop in electron, I believe they use an electron protocol similar to this ("vscode-resource"). On web, if I remember correctly, they route it to their own cdn.
___
*[`src/main/main.ts` line 234 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV81FiZCgQ2HVVqvsQa:-NVAwzqF4pdqFbFt0tDj:b-i8atn6) ([raw file](https://github.com/paranext/paranext-core/blob/09acc4b2e0c07ab4e627bc4c1c057713e1c471aa/src/main/main.ts#L234)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Reworked `main.ts` and added comments about where additional synchronization could happen to eliminate some startup race conditions.
</blockquote></details>

I think it is better to start everything in parallel rather than to start everything sequentially. I think it makes most sense to start the window asap (first priority) to give user feedback and to start other things all at once to get the system up and running as soon as we can. If there's any process that needs to wait on another process, I would think it would be best to have it poll for a bit while starting rather than not launching until something else is done. That way, at least theoretically the computer's resources can be used as much as possible to help us start quickly. We already have websocket connection polling (trying to connect to the server's websocket and waiting a bit if it fails) on the JavaScript client side. I suggest we make an issue to add websocket connection polling on the C# side as well instead of baking in a startup order. That way, the processes start asap. They will also be able to wait on each other to do things (like addWebView for example. Though it is a very temporary api, it does illustrate a dependency problem) when #51 is finished. I'd like to hear your thoughts on this topic.
___
*[`src/main/main.ts` line 234 at r3](https://reviewable.io/reviews/paranext/paranext-core/182#-NVBJyCYDV7Mg7mpOnQD:-NVBJyCZ1JvYUMeFLXN4:b1ms3we) ([raw file](https://github.com/paranext/paranext-core/blob/f1a4722993834a8e634c38e7b817e1c93619c504/src/main/main.ts#L234)):*
> ```XML
>   });
> 
>   // #endregion
> ```

Why did you remove these regions? I think this `// #endregion` doesn't have a `// #region` to go with it anymore, but I could be missing something
___
*[`src/main/services/extension-asset-protocol.service.ts` line 76 at r3](https://reviewable.io/reviews/paranext/paranext-core/182#-NVBeTHkBCwmb3wufPDP:-NVBeTHkBCwmb3wufPDQ:bqqp2ct) ([raw file](https://github.com/paranext/paranext-core/blob/f1a4722993834a8e634c38e7b817e1c93619c504/src/main/services/extension-asset-protocol.service.ts#L76)):*
> ```XML
> 
>       // "paranextension://" is 17 characters long
>       const uri: string = request.url.substring(17);
> ```

Maybe consider making `paranextension` a const and making a const length as well so we don't have to bake in a magic number?


<!-- Sent from Reviewable.io -->

2023-05-11 23:00 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: 8 of 14 files reviewed, 8 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/lib/quick-verse/assets/letter-q.png` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7lWm10fztgUDpiwkB:-NVBypUaBtenVlY9pW_G:b-6ryjaq) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/extensions/lib/quick-verse/assets/letter-q.png#L)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think we should attribute it in the code somewhere. Could we maybe put it in an `attribution.txt` file or something in this folder?
</blockquote></details>

Good point.  Added `ATTRIBUTION.md` to the directory.  I just looked at reusing one of the existing icons, but they all are white or mostly white, and the background of that window is white, so they wouldn't show up.  If it's preferred I can probably edit one of our icons to not be white and use that.
___
*[`src/main/main.ts` line 127 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV81lptCIg39epQKyoL:-NVBzEi1A1doS-oid3GL:b-8wpxdb) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/main/main.ts#L127)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I agree that we should put this service in `main/services` - thanks for moving it :) FYI I believe all the protocol stuff is electron-specific. VSCode has a function you run to get the proper asset url for a webview asset. On desktop in electron, I believe they use an electron protocol similar to this ("vscode-resource"). On web, if I remember correctly, they route it to their own cdn.
</blockquote></details>

I just tried registering the protocol handler outside of `createWindow` in `main.ts`, and it shows this error:
```
(node:32169) UnhandledPromiseRejectionWarning: TypeError: electron_1.protocol.registerBufferProtocol is not a function
    at /home/lyonsm/paranext-core/src/main/services/extension-asset-protocol.service.ts:71:14
    at Object.initialize (/home/lyonsm/paranext-core/src/main/services/extension-asset-protocol.service.ts:119:5)
    at main (/home/lyonsm/paranext-core/src/main/main.ts:98:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/lyonsm/paranext-core/src/main/main.ts:310:3
(Use `electron --trace-warnings ...` to show where the warning was created)
```

I'm going to leave the registration call where it is given that it doesn't seem to work anywhere else.
___
*[`src/main/main.ts` line 234 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV81FiZCgQ2HVVqvsQa:-NVC0Kne7AlPE32_mymo:b-6a0lr5) ([raw file](https://github.com/paranext/paranext-core/blob/09acc4b2e0c07ab4e627bc4c1c057713e1c471aa/src/main/main.ts#L234)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it is better to start everything in parallel rather than to start everything sequentially. I think it makes most sense to start the window asap (first priority) to give user feedback and to start other things all at once to get the system up and running as soon as we can. If there's any process that needs to wait on another process, I would think it would be best to have it poll for a bit while starting rather than not launching until something else is done. That way, at least theoretically the computer's resources can be used as much as possible to help us start quickly. We already have websocket connection polling (trying to connect to the server's websocket and waiting a bit if it fails) on the JavaScript client side. I suggest we make an issue to add websocket connection polling on the C# side as well instead of baking in a startup order. That way, the processes start asap. They will also be able to wait on each other to do things (like addWebView for example. Though it is a very temporary api, it does illustrate a dependency problem) when #51 is finished. I'd like to hear your thoughts on this topic.
</blockquote></details>

I think we agreed in our discussion to focus on correctness and stability in startup for now, so I won't make any adjustments.  Having said that, I threw in a `console.time` at the start of the file and `console.timeEnd` at the beginning of the `Start the renderer` region.  On my dev box, this all takes about 0.1 milliseconds, so I don't think we're hurting start up time with this rearranging.  Other things I marked as TODO would have more of an impact, and we might not want to do them.
___
*[`src/main/main.ts` line 234 at r3](https://reviewable.io/reviews/paranext/paranext-core/182#-NVBJyCYDV7Mg7mpOnQD:-NVBzpW4255dJSqt_BeL:bq6ov52) ([raw file](https://github.com/paranext/paranext-core/blob/f1a4722993834a8e634c38e7b817e1c93619c504/src/main/main.ts#L234)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why did you remove these regions? I think this `// #endregion` doesn't have a `// #region` to go with it anymore, but I could be missing something
</blockquote></details>

I just checked, and the opening `// #region` comment is on line 51.


<!-- Sent from Reviewable.io -->

2023-05-12 02:39 UTC, irahopkinson reviewed
> Reviewed 4 of 5 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`src/main/main.ts` line 234 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV81FiZCgQ2HVVqvsQa:-NVCYbfsEMrpfziveLC9:b-jhpcvm) ([raw file](https://github.com/paranext/paranext-core/blob/09acc4b2e0c07ab4e627bc4c1c057713e1c471aa/src/main/main.ts#L234)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I think we agreed in our discussion to focus on correctness and stability in startup for now, so I won't make any adjustments.  Having said that, I threw in a `console.time` at the start of the file and `console.timeEnd` at the beginning of the `Start the renderer` region.  On my dev box, this all takes about 0.1 milliseconds, so I don't think we're hurting start up time with this rearranging.  Other things I marked as TODO would have more of an impact, and we might not want to do them.
</blockquote></details>

Thanks for checking into the timing - looks good.
___
*[`src/main/main.ts` line 277 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NVCZ0R50C8jxsWQ8_02:-NVCZ0R50C8jxsWQ8_03:b-mtu1hq) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/main/main.ts#L277)):*
> ```XML
> // #region network object test
> 
> (async () => {
> ```

Pretty sure we can take this content out of the self calling **async** arrow function now that `main` is **async** or does that change the order of things in an unhelpful way?
___
*[`src/main/main.ts` line 27 at r3](https://reviewable.io/reviews/paranext/paranext-core/182#-NVCY7Kq73FAnO3RNIG5:-NVCY7Kq73FAnO3RNIG6:b16wzln) ([raw file](https://github.com/paranext/paranext-core/blob/f1a4722993834a8e634c38e7b817e1c93619c504/src/main/main.ts#L27)):*
> ```XML
> import { wait } from '@shared/utils/util';
> 
> async function main() {
> ```

I like this re-organization on `main` - a big step in the right direction.
___
*[`src/renderer/testing/test-quick-verse-heresy-panel.component.tsx` line 46 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7qHY6-6BxNh9yZsl7:-NVCo1XyEiXUPAxxNMhi:bkzpgm5) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/renderer/testing/test-quick-verse-heresy-panel.component.tsx#L46)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I put it there on purpose.  I can remove it if desired.
</blockquote></details>

Sorry, I thought this was a closing tag without an opening tag. I now see that it is a self-closing tag.
___
*[`src/shared/services/extension-asset-protocol.service.ts` line 38 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7uK5m3_pse8JTykDZ:-NVCTRpK7KwmmIcb-Up8:b-gd5139) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/services/extension-asset-protocol.service.ts#L38)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I don't think everyone would agree with that.
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/f/file-name

I generally find `fileName` easier to read.  I'm probably influenced by starting my career where it was considered 2 words in general.

</blockquote></details>

Fair enough. I am a little surprised MS sees it still as 2 words though.
___
*[`src/shared/services/extension-asset-protocol.service.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7ufluEz1JiNfQc0ZG:-NVCUCyB6WsaV6h9HM1n:b-shwolg) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/services/extension-asset-protocol.service.ts#L42)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I agree that a file extension doesn't imply what the actual contents are.  Having said that, I think this approach is a good one for a few reasons:
1) In my limited testing, it actually didn't matter what MIME type I listed for the renderer to show the appropriate content (at least for images).  What it DID help with, though, is debugging.  Chromium's dev tools try to render content based on the MIME type when you're digging into the details, and it's much nicer to see renderer data than raw binary.
2) This will only ever serve up files that are provided by the extensions themselves. I believe users will have to trust the content provided by extensions.  As such, if someone wants to distribute malicious content in an extension that someone else trusts, we're probably in trouble anyway.
3) If the renderer uses a MIME type to make security decisions, it's broken anyway.  Any limited validation a host might do might not catch all security issues (e.g., anti-virus software isn't fool proof), and code that parses potentially malicious data needs to be tested well.
</blockquote></details>

Yes, 2 is sufficient on its own for me.
___
*[`src/shared/services/extension-asset-protocol.service.ts` line 76 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7yA0fE8kQfagOIjBO:-NVCVRTT6oMO-qKvfLbk:bthbgwz) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/services/extension-asset-protocol.service.ts#L76)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

This is removing `paranextension://` from the front of the given URL which the protocol handler needs to have already verified starts with it to know to pass the URL to this code.  It's not checking the prefix.
</blockquote></details>

Yes, I realised what this was doing already - I was asking if we needed to add a check for protocol before this line. However, it makes sense that the protocol handler would be checking this - thanks for explaining.


<!-- Sent from Reviewable.io -->

2023-05-12 14:29 UTC, tjcouch-sil requested changes
Thanks for all the hard work! I'm really excited that you're bringing this feature!! This is awesome. A few things to consider for hardening and a couple blocking things. Thank you!

> Reviewed 2 of 13 files at r1, 3 of 5 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182#-:-NVFMM8gCTYDHsuVMN0E:b-7t3qkc)* status: all files reviewed, 6 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/lib/quick-verse/assets/letter-q.png` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7lWm10fztgUDpiwkB:-NVFGC_U9QuFvlL91-8L:bag1l0c) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/extensions/lib/quick-verse/assets/letter-q.png#L)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Good point.  Added `ATTRIBUTION.md` to the directory.  I just looked at reusing one of the existing icons, but they all are white or mostly white, and the background of that window is white, so they wouldn't show up.  If it's preferred I can probably edit one of our icons to not be white and use that.
</blockquote></details>

This is fine :) thank you!
___
*[`src/extension-host/services/asset-retrieval.service.ts` line 6 at r4](https://reviewable.io/reviews/paranext/paranext-core/182#-NVFHicJ8kh63M4fEjfP:-NVFHicJ8kh63M4fEjfQ:b5ymj07) ([raw file](https://github.com/paranext/paranext-core/blob/8b81db916c05bb67e12b6d502b308393d9a68f73/src/extension-host/services/asset-retrieval.service.ts#L6)):*
> ```XML
> 
> export default async function getAsset(extensionName: string, assetName: string): Promise<Buffer> {
>   const pathToAsset = buildExtensionPathFromName(extensionName, path.join('assets', assetName));
> ```

I'm beginning to think it may not be wise to restrict this protocol only to the `assets` folder. When people make websites, I believe they usually link to their styles and code from some other folder like `src` and their images and such from `assets`, `media`, etc. I think it would feel strange to make people put some of their code in one folder and some of their code in another folder like `src` vs `assets`. I don't think we're really buying anything meaningful by restricting to `assets`, right?

Additionally, I think the way Vite works, it would be hard to transpile things in a static folder like `assets`. That's a secondary item, though, since I don't think we need to cater to the build tooling for how we design.
___
*[`src/main/main.ts` line 234 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV81FiZCgQ2HVVqvsQa:-NVFGfxSDE9A-v8Loz_X:b-xvrd1) ([raw file](https://github.com/paranext/paranext-core/blob/09acc4b2e0c07ab4e627bc4c1c057713e1c471aa/src/main/main.ts#L234)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Thanks for checking into the timing - looks good.
</blockquote></details>

Agreed. Would you mind making an issue about optimizing startup for much later when we're actually hardening? Dunno if the MVP milestone has been created yet... 
___
*[`src/main/main.ts` line 234 at r3](https://reviewable.io/reviews/paranext/paranext-core/182#-NVBJyCYDV7Mg7mpOnQD:-NVFGb0L3idpDKf7BG_7:bl1ovhv) ([raw file](https://github.com/paranext/paranext-core/blob/f1a4722993834a8e634c38e7b817e1c93619c504/src/main/main.ts#L234)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I just checked, and the opening `// #region` comment is on line 51.
</blockquote></details>

Ah sorry. Thank you!
___
*[`src/renderer/index.ejs` line 13 at r4](https://reviewable.io/reviews/paranext/paranext-core/182#-NVFJfdjDRlgybYHuqQL:-NVFJfdjDRlgybYHuqQM:blr8gis) ([raw file](https://github.com/paranext/paranext-core/blob/8b81db916c05bb67e12b6d502b308393d9a68f73/src/renderer/index.ejs#L13)):*
> ```EJS
>       script-src allows them to use script tags and in-line attribute scripts
>         'self' so scripts can be loaded from us
>         paranextension: so scripts can be loaded from installed extensions
> ```

I added to #89 mentioning that we should evaluate this addition to the CSP at some point. I don't have any reason in mind right now why this would be inappropriate, but it would be worth considering.
___
*[`src/renderer/testing/test-quick-verse-heresy-panel.component.tsx` line 39 at r4](https://reviewable.io/reviews/paranext/paranext-core/182#-NVFLXWCATLAxF5VXABA:-NVFLXWD2lSBUfFflFMZ:bvla1zt) ([raw file](https://github.com/paranext/paranext-core/blob/8b81db916c05bb67e12b6d502b308393d9a68f73/src/renderer/testing/test-quick-verse-heresy-panel.component.tsx#L39)):*
> ```XML
>       <div className="hello">
>         <img
>           src="paranextension://quick-verse/letter-q.png"
> ```

Is there anywhere in an extension webview that you are using `paranextension:`? If not, maybe you could add a call in an existing webview or convert this panel into an extension webview in `quick-verse`? Katherine can probably help with doing that if you want to do that, but no pressure at all. Just want it to be exercised within an extension webview somehow if that sounds good.
___
*[`src/shared/utils/http-status-codes.ts` line 1 at r4](https://reviewable.io/reviews/paranext/paranext-core/182#-NVFKRhF4rbJBcL5Z3RR:-NVFKRhG8dTHx0uIMXu9:by6zlti) ([raw file](https://github.com/paranext/paranext-core/blob/8b81db916c05bb67e12b6d502b308393d9a68f73/src/shared/utils/http-status-codes.ts#L1)):*
> ```XML
> // From https://github.com/prettymuchbryce/http-status-codes/blob/master/src/status-codes.ts
> ```

Could we instead install this package as a dependency? I could be missing something, but it seems unhelpful to copy the file in (webpack "tree shakes" unused dependencies out even within a single module file, so installing the whole package would not increase the production bundle size to my understanding).

Particularly, I think about some future time where we will likely be scraping our npm packages to grab their licenses and aggregate them into a licensing display of some sort. Copying this file instead of installing the npm package breaks this future hope a bit.


<!-- Sent from Reviewable.io -->

2023-05-12 15:05 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: 8 of 16 files reviewed, 3 unresolved discussions (waiting on @irahopkinson, @lyonsil, and @tjcouch-sil)

___
*[`src/extension-host/services/asset-retrieval.service.ts` line 6 at r4](https://reviewable.io/reviews/paranext/paranext-core/182#-NVFHicJ8kh63M4fEjfP:-NVFPkXjC_a2SvQ8p8ai:b1zty9z) ([raw file](https://github.com/paranext/paranext-core/blob/8b81db916c05bb67e12b6d502b308393d9a68f73/src/extension-host/services/asset-retrieval.service.ts#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm beginning to think it may not be wise to restrict this protocol only to the `assets` folder. When people make websites, I believe they usually link to their styles and code from some other folder like `src` and their images and such from `assets`, `media`, etc. I think it would feel strange to make people put some of their code in one folder and some of their code in another folder like `src` vs `assets`. I don't think we're really buying anything meaningful by restricting to `assets`, right?

Additionally, I think the way Vite works, it would be hard to transpile things in a static folder like `assets`. That's a secondary item, though, since I don't think we need to cater to the build tooling for how we design.
</blockquote></details>

It does give something that might be considered helpful as things are now.  That is, on the backend extensions can read from anywhere they want in their extension installation directory, but we have some code in place to prevent extensions from reading code from each other's installation directories.  This new protocol doesn't prevent cross-extension reading of data, but if we leave it as-is it gives extension authors a way to have a separate "public" area from the rest of their installation directory.  That is, the `asset` subdirectory is public, but the rest is private to their extension back end code.
___
*[`src/main/main.ts` line 234 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV81FiZCgQ2HVVqvsQa:-NVFS6U2CCTBY96W1ax3:b-3j6d2z) ([raw file](https://github.com/paranext/paranext-core/blob/09acc4b2e0c07ab4e627bc4c1c057713e1c471aa/src/main/main.ts#L234)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Agreed. Would you mind making an issue about optimizing startup for much later when we're actually hardening? Dunno if the MVP milestone has been created yet... 
</blockquote></details>

https://github.com/paranext/paranext-core/issues/184
___
*[`src/main/main.ts` line 277 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NVCZ0R50C8jxsWQ8_02:-NVFHgKz3e5p1Rkg_C55:bcx8m4g) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/main/main.ts#L277)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Pretty sure we can take this content out of the self calling **async** arrow function now that `main` is **async** or does that change the order of things in an unhelpful way?
</blockquote></details>

You're right.  Removing the unneeded `async`.
___
*[`src/shared/utils/http-status-codes.ts` line 1 at r4](https://reviewable.io/reviews/paranext/paranext-core/182#-NVFKRhF4rbJBcL5Z3RR:-NVFTNoTB_wfy47y3fOo:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/8b81db916c05bb67e12b6d502b308393d9a68f73/src/shared/utils/http-status-codes.ts#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Could we instead install this package as a dependency? I could be missing something, but it seems unhelpful to copy the file in (webpack "tree shakes" unused dependencies out even within a single module file, so installing the whole package would not increase the production bundle size to my understanding).

Particularly, I think about some future time where we will likely be scraping our npm packages to grab their licenses and aggregate them into a licensing display of some sort. Copying this file instead of installing the npm package breaks this future hope a bit.
</blockquote></details>

Done
___
*[`src/main/services/extension-asset-protocol.service.ts` line 76 at r3](https://reviewable.io/reviews/paranext/paranext-core/182#-NVBeTHkBCwmb3wufPDP:-NVFP-Ld-anRqlgkVZEc:bq2x5pc) ([raw file](https://github.com/paranext/paranext-core/blob/f1a4722993834a8e634c38e7b817e1c93619c504/src/main/services/extension-asset-protocol.service.ts#L76)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Maybe consider making `paranextension` a const and making a const length as well so we don't have to bake in a magic number?
</blockquote></details>

Good idea - done
___
*[`src/shared/services/extension-asset-protocol.service.ts` line 76 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NV7yA0fE8kQfagOIjBO:-NVFMHa8AJD-QabEUqWY:bj6hnaq) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/shared/services/extension-asset-protocol.service.ts#L76)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yes, I realised what this was doing already - I was asking if we needed to add a check for protocol before this line. However, it makes sense that the protocol handler would be checking this - thanks for explaining.
</blockquote></details>

Sorry, I don't think I read your comment closely enough.  For some reason I only saw your `A simple ...` sentence the first time through.  But yes, if we ever got a URL passed in that didn't start with our protocol, electron itself is broken and there are bigger problems.


<!-- Sent from Reviewable.io -->

2023-05-12 16:37 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: 8 of 18 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/renderer/testing/test-quick-verse-heresy-panel.component.tsx` line 39 at r4](https://reviewable.io/reviews/paranext/paranext-core/182#-NVFLXWCATLAxF5VXABA:-NVFblCY7fR107iVJQkF:bifz21y) ([raw file](https://github.com/paranext/paranext-core/blob/8b81db916c05bb67e12b6d502b308393d9a68f73/src/renderer/testing/test-quick-verse-heresy-panel.component.tsx#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is there anywhere in an extension webview that you are using `paranextension:`? If not, maybe you could add a call in an existing webview or convert this panel into an extension webview in `quick-verse`? Katherine can probably help with doing that if you want to do that, but no pressure at all. Just want it to be exercised within an extension webview somehow if that sounds good.
</blockquote></details>

Good call - I added the "Q" to "Hello World."  It didn't work at first because there is a separate content security policy that applies to webviews, and I needed to add the protocol to that CSP, too, in addition to the top-level one.


<!-- Sent from Reviewable.io -->

2023-05-12 18:56 UTC, tjcouch-sil reviewed
> Reviewed 9 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @lyonsil)

___
*[`src/extension-host/services/asset-retrieval.service.ts` line 6 at r4](https://reviewable.io/reviews/paranext/paranext-core/182#-NVFHicJ8kh63M4fEjfP:-NVGJHHvCXnAeQO6tCO6:b-ggp9zr) ([raw file](https://github.com/paranext/paranext-core/blob/8b81db916c05bb67e12b6d502b308393d9a68f73/src/extension-host/services/asset-retrieval.service.ts#L6)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

It does give something that might be considered helpful as things are now.  That is, on the backend extensions can read from anywhere they want in their extension installation directory, but we have some code in place to prevent extensions from reading code from each other's installation directories.  This new protocol doesn't prevent cross-extension reading of data, but if we leave it as-is it gives extension authors a way to have a separate "public" area from the rest of their installation directory.  That is, the `asset` subdirectory is public, but the rest is private to their extension back end code.
</blockquote></details>

This does seem worth preserving, so we discussed having the caller add `assets` to their path or it throws. That way, in the future, we can add extension-scoped file access with backwards compatibility if we decide to do so.


<!-- Sent from Reviewable.io -->

2023-05-12 21:06 UTC, irahopkinson reviewed
> Reviewed 7 of 10 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`src/extension-host/services/asset-retrieval.service.ts` line 6 at r6](https://reviewable.io/reviews/paranext/paranext-core/182#-NVGjPt25PfG-_5p4tUn:-NVGjPt25PfG-_5p4tUo:bl1uiqm) ([raw file](https://github.com/paranext/paranext-core/blob/2ddf4daffe3a65a88f31effbf2d13545b4ffe219/src/extension-host/services/asset-retrieval.service.ts#L6)):*
> ```XML
> export default async function getAsset(extensionName: string, assetName: string): Promise<Buffer> {
>   const prefix = assetName.substring(0, 7).replace('\\', '/');
>   if (prefix !== 'assets/') throw Error('Requests are limited to files in the "assets" directory');
> ```

How about making this a **const** and using its length above to get rid of the magic number?



_Code quote:_
```XML
'assets/'
```
___
*[`cspell.json` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NVGlVvhAiYBz2EVhG7j:-NVGlVvhAiYBz2EVhG7k:b-44bb5t) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/cspell.json#L33)):*
> ```JSON
>     "Papis",
>     "paranext",
>     "paranextension",
> ```

This is no longer needed since its name has changed, so remove or change to the new name.


<!-- Sent from Reviewable.io -->

2023-05-12 21:28 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[`src/extension-host/services/asset-retrieval.service.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NVAtT9S5HtJAgjYxG7z:-NVGrEbi2lcDjQMJBwad:bly1hjn) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/src/extension-host/services/asset-retrieval.service.ts#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe the `getExtensionAsset` command should change to a request and be set up in this service in a similar fashion to `addWebView` in `web-view.service.ts`. This service would move to `@shared` for now. I recommend this change because it would combine all the code related to this service into one file.

This would require using `isExtensionHost` to either send the request or actually perform the request when you call this function. I know we have discussed not liking this strategy, but I believe it is worth combining in this manner until we split the code into abstract classes and implementing classes and such as we discussed around #63, during which we could fix this code.

If you don't want to refactor like this, maybe it would be good to add a comment mentioning the link between these two places so that, when we do #63, we can integrate the code into the one service.
</blockquote></details>

This should be resolved now.
___
*[`cspell.json` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NVGlVvhAiYBz2EVhG7j:-NVGqxI53KgRCGe_KCwy:b-zenupp) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/cspell.json#L33)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is no longer needed since its name has changed, so remove or change to the new name.
</blockquote></details>

I believe I removed "paranextension" at the same time I changed the protocol string.  Do you still see it?


<!-- Sent from Reviewable.io -->

2023-05-12 21:35 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: 15 of 19 files reviewed, 1 unresolved discussion (waiting on @github-code-scanning[bot] and @irahopkinson)

___
*[`src/extension-host/services/asset-retrieval.service.ts` line 5 at r6](https://reviewable.io/reviews/paranext/paranext-core/182#gh-1192774948:-NVGsvs4D9LPXYBUq0Ym:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2ddf4daffe3a65a88f31effbf2d13545b4ffe219/src/extension-host/services/asset-retrieval.service.ts#L5)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Incomplete string escaping or encoding

This replaces only the first occurrence of '\\'.

[Show more details](https://github.com/paranext/paranext-core/security/code-scanning/3)
</blockquote></details>

Done.
___
*[`src/extension-host/services/asset-retrieval.service.ts` line 6 at r6](https://reviewable.io/reviews/paranext/paranext-core/182#-NVGjPt25PfG-_5p4tUn:-NVGswl9Ajy4k7jcg0LS:b-aqbpn3) ([raw file](https://github.com/paranext/paranext-core/blob/2ddf4daffe3a65a88f31effbf2d13545b4ffe219/src/extension-host/services/asset-retrieval.service.ts#L6)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

How about making this a **const** and using its length above to get rid of the magic number?
</blockquote></details>

rewrote this


<!-- Sent from Reviewable.io -->

2023-05-12 21:35 UTC, lyonsil reviewed
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: 15 of 19 files reviewed, all discussions resolved (waiting on @irahopkinson)



<!-- Sent from Reviewable.io -->

2023-05-12 22:56 UTC, irahopkinson reviewed
> Reviewed 2 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/extension-host/extension-host.ts` line 56 at r6](https://reviewable.io/reviews/paranext/paranext-core/182#-NVH6lEK6P0mDaUPzaBC:-NVH6lEK6P0mDaUPzaBD:b-qdgxlh) ([raw file](https://github.com/paranext/paranext-core/blob/2ddf4daffe3a65a88f31effbf2d13545b4ffe219/src/extension-host/extension-host.ts#L56)):*
> ```XML
> 
> // Need to wait a bit to initialize extensions in production because the extension host launches faster than the renderer.
> // TODO: Fix this so we can await renderer connecting event or something
> ```

Good job - great to see this gone!
___
*[`src/extension-host/extension-host.ts` line 43 at r8](https://reviewable.io/reviews/paranext/paranext-core/182#-NVH5us10g3XeAHn9CQp:-NVH5us23s8juU5Afhbr:b-579crh) ([raw file](https://github.com/paranext/paranext-core/blob/cae3a1dd6247edad3fcfd105edc6bf93dd532c2d/src/extension-host/extension-host.ts#L43)):*
> ```XML
>     // Set up network commands
>     Object.entries(commandHandlers).forEach(async ([commandName, handler]) => {
>       await papi.commands.registerCommand(commandName, handler).promise;
> ```

FYI: the commands won't necessarily all be registered before the next line `extensionAssetService.initialize()` since this is `await` inside an arrow function (in which case you probably don't need to `await` here). If the intention was to register each command before the service init then this won't do it.
___
*[`src/shared/services/extension-asset.service.ts` line 7 at r8](https://reviewable.io/reviews/paranext/paranext-core/182#-NVH8VhI9dLMU4jdTbtM:-NVH8VhI9dLMU4jdTbtN:b-5a4a01) ([raw file](https://github.com/paranext/paranext-core/blob/cae3a1dd6247edad3fcfd105edc6bf93dd532c2d/src/shared/services/extension-asset.service.ts#L7)):*
> ```XML
> import { assert } from 'console';
> 
> let getAsset: typeof GetAsset;
> ```

Since I needed to check what was happening here I wouldn't change the casing to `GetAsset` since that makes it already look like a type (and the import does also but is actually importing a function despite adding the `type` keyword). How about `let getAssetFunction: typeof getAsset;` (and just import the function normally)? I'm probably missing something here since I'm not sure why you do the dynamic import later when the function has already been imported above.



_Code quote:_
```XML
GetAsset
```
___
*[`cspell.json` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/182#-NVGlVvhAiYBz2EVhG7j:-NVHABqv2o_kRhoUaBfO:bndpwwa) ([raw file](https://github.com/paranext/paranext-core/blob/701ceedf7667dc21abcb78c4360755e3d1544a47/cspell.json#L33)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I believe I removed "paranextension" at the same time I changed the protocol string.  Do you still see it?
</blockquote></details>

Is good now.


<!-- Sent from Reviewable.io -->

2023-05-12 23:04 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/shared/services/extension-asset.service.ts` line 7 at r8](https://reviewable.io/reviews/paranext/paranext-core/182#-NVH8VhI9dLMU4jdTbtM:-NVHBnJjD2K-WVG-9P0s:b-7iz56e) ([raw file](https://github.com/paranext/paranext-core/blob/cae3a1dd6247edad3fcfd105edc6bf93dd532c2d/src/shared/services/extension-asset.service.ts#L7)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Since I needed to check what was happening here I wouldn't change the casing to `GetAsset` since that makes it already look like a type (and the import does also but is actually importing a function despite adding the `type` keyword). How about `let getAssetFunction: typeof getAsset;` (and just import the function normally)? I'm probably missing something here since I'm not sure why you do the dynamic import later when the function has already been imported above.
</blockquote></details>

Ok, I take it back about `import type` since that always gets erased at runtime (which explains the dynmaic import) but I'd still make it `import type getAsset from '@extension-host/services/asset-retrieval.service';`


<!-- Sent from Reviewable.io -->

2023-05-13 02:33 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

___
*[`src/extension-host/extension-host.ts` line 43 at r8](https://reviewable.io/reviews/paranext/paranext-core/182#-NVH5us10g3XeAHn9CQp:-NVHuC4g7fgMmb4sMQMv:bqrhhoq) ([raw file](https://github.com/paranext/paranext-core/blob/cae3a1dd6247edad3fcfd105edc6bf93dd532c2d/src/extension-host/extension-host.ts#L43)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

FYI: the commands won't necessarily all be registered before the next line `extensionAssetService.initialize()` since this is `await` inside an arrow function (in which case you probably don't need to `await` here). If the intention was to register each command before the service init then this won't do it.
</blockquote></details>

Yes, I see now that forEach doesn't do what I believed.  Updated.
___
*[`src/shared/services/extension-asset.service.ts` line 7 at r8](https://reviewable.io/reviews/paranext/paranext-core/182#-NVH8VhI9dLMU4jdTbtM:-NVHtF7t85UhTi9oz89-:b-92zfsi) ([raw file](https://github.com/paranext/paranext-core/blob/cae3a1dd6247edad3fcfd105edc6bf93dd532c2d/src/shared/services/extension-asset.service.ts#L7)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Ok, I take it back about `import type` since that always gets erased at runtime (which explains the dynmaic import) but I'd still make it `import type getAsset from '@extension-host/services/asset-retrieval.service';`
</blockquote></details>

I would very much like to leave this as-is for now.  This file was written working directly with TJ, and it's a pattern I'd like to explore changing more significantly in the future rather than tweaking it more now.


<!-- Sent from Reviewable.io -->

2023-05-13 04:33 UTC, irahopkinson approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

___
*[`src/shared/services/extension-asset.service.ts` line 7 at r8](https://reviewable.io/reviews/paranext/paranext-core/182#-NVH8VhI9dLMU4jdTbtM:-NVINCw28xJ2HQY9Snln:b-i7gt9u) ([raw file](https://github.com/paranext/paranext-core/blob/cae3a1dd6247edad3fcfd105edc6bf93dd532c2d/src/shared/services/extension-asset.service.ts#L7)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I would very much like to leave this as-is for now.  This file was written working directly with TJ, and it's a pattern I'd like to explore changing more significantly in the future rather than tweaking it more now.
</blockquote></details>

Sure, this was non-blocking.


<!-- Sent from Reviewable.io -->

2023-05-13 04:45 UTC, irahopkinson approved these changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

___
*[`src/shared/services/extension-asset.service.ts` line 7 at r8](https://reviewable.io/reviews/paranext/paranext-core/182#-NVH8VhI9dLMU4jdTbtM:-NVIPKnl3Y2YDp4XBm7N:b-q83z6x) ([raw file](https://github.com/paranext/paranext-core/blob/cae3a1dd6247edad3fcfd105edc6bf93dd532c2d/src/shared/services/extension-asset.service.ts#L7)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Sure, this was non-blocking.
</blockquote></details>

A clean-up could be to create `export type GetAsset = typeof getAsset;` in `extension-host/services/asset-retrieval.service.ts`, then you wouldn't need to do the `typeof` here which is what I found confusing.


<!-- Sent from Reviewable.io -->

2023-05-15 15:25 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thank you for all the hard work! I know this will be a GREAT addition to Paranext!

> Reviewed 1 of 10 files at r5, 2 of 6 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182#-:-NVV04BW-MQEyPwlbalM:bqprlf2)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/extension-host/extension-host.ts` line 41 at r9](https://reviewable.io/reviews/paranext/paranext-core/182#-NVV-AFgCRT0TrNQVYVZ:-NVV-AFgCRT0TrNQVYV_:b-ahvpbb) ([raw file](https://github.com/paranext/paranext-core/blob/3cda453b14325c9770c110c98ff86ed397841803/src/extension-host/extension-host.ts#L41)):*
> ```XML
>   .initialize()
>   .then(async () => {
>     // Set up network commands
> ```

If you do any more work on this PR, I recommend changing this comment back to "Set up test handlers" because this code probably shouldn't stay here long-term. It's just testing sending and receiving commands from many different places. Not a big deal, though.


<!-- Sent from Reviewable.io -->

2023-05-15 18:12 UTC, tjcouch-sil approved these changes
> Reviewed 9 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2023-05-15 18:12 UTC, tjcouch-sil approved these changes
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/182)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2023-05-15 19:23 UTC, merged