Add Data Type functions to Data Provider API
paranext/paranext-core pull request #206
Opened 2023-05-25 22:38 UTC by tjcouch-sil

Added data types to data provider api. Before, data providers had `get`, `set`, `notifyUpdate`, and `subscribe` to serve and control updates to one data type. Now, data providers expose multiple sets of functions, one per data type they serve. Essentially, the functions do the same thing, but they are scoped with one extra distinction from just a selector (the data type). For example, the Sneeze Board could have Sneezes and Users, so it would have two sets of functions:
  - `getSneeze`, `setSneeze`, `notifyUpdateSneeze`, and `subscribeSneeze`
  - `getUser`, `setUser`, `notifyUpdateUser`, and `subscribeUser`

`set` and `notifyUpdate` methods now have more complex return types. They can return '*' to update all data types related to this data provider, a string of one data type name to update that data type, an array of data type names to update those data types, truthy (other than string or array) to update just the specific data type for this method (e.g. returning true from `setSneeze` would update all `Sneeze` subscribers only), or falsy to update nothing.
Now, instead of just using `useData` hook, you use `useData.<data_type>` like `useData.Verse`. To specify types, you can get the data types from the provider and index into the proper type like `useData.Verse<QuickVerseDataTypes['Verse']>`

2023-05-26 10:18 UTC, rolfheij-sil submitted a review, later dismissed
![image.png](https://files.reviewableusercontent.io/images/reviewable/108285668/lCbIJPvr4APCoEdqteAF2CJm/image.png)
Awesome work. I don't think I have enough TS knowledge to actually review this, but I did have a bunch of questions

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206#-:-NWMYppB7UAIUM1pxVw5:b-c40qcu)* status: all files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMP7TaBRQ1YAmfzsQ8:-NWMP7TaBRQ1YAmfzsQ9:b485lrr) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/hello-someone/hello-someone.ts#L37)):*
> ```XML
>     this.people[name.toLowerCase()]!.greeting = greeting;
>     // Update greetings and all because all needs to know about all changes to people
>     return ['Greeting', 'All'];
> ```

setGreeting should return a promise, but to me it looks like it's returning an array of strings. Can you help me understand what's going on here?
___
*[`extensions/lib/hello-world/hello-world.ts` line 55 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMSBU8C-6R_ziUr7Zt:-NWMSBU9CORda_zmdTQR:b905wf8) ([raw file](https://github.com/paranext/paranext-core/blob/bc370840b6d54bec954f567ae561ee96942e7f0b/extensions/lib/hello-world/hello-world.ts#L55)):*
> ```XML
>   if (greetingsDataProvider) {
>     // Test subscribing to a data provider
>     const unsubGreetings = await greetingsDataProvider.subscribe('Bill', (billGreeting: string) =>
> ```

Why was the type defintion removed?
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 47 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMTBtlE9GSnCV7Qpyg:-NWMTBtlE9GSnCV7Qpyh:b-3b5ju4) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/hello-world/hello-world.web-view.tsx#L47)):*
> ```XML
>   const [name, setName] = useState('Bill');
> 
>   const [personGreeting] = useData.Greeting<GreetingsDataTypes['Greeting']>(
> ```

I know it doesn't make sense, but what would happen if you would do something like
`useData.Greeting<GreetingsDataTypes['Age']>`?
___
*[`src/renderer/hooks/papi-hooks/use-data.hook.ts` line 161 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMY4qy1XEHLgiw4dbm:-NWMY4qy1XEHLgiw4dbn:bhsdoez) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/renderer/hooks/papi-hooks/use-data.hook.ts#L161)):*
> ```XML
>  * @param defaultValue the initial value to return while first awaiting the data
>  *
>  *    WARNING: MUST BE STABLE - const or wrapped in useState, useMemo, etc. The reference must not be updated every render
> ```

Is there a way to enforce this?
___
*[`src/renderer/hooks/papi-hooks/use-data.hook.ts` line 194 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMXyS92_M9ThYSSag-:-NWMXyS92_M9ThYSSag0:b-7xanwj) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/renderer/hooks/papi-hooks/use-data.hook.ts#L194)):*
> ```XML
>   },
>   set() {
>     // Doing this makes no sense
> ```

Then why do you declare/expose it?
___
*[`src/shared/models/data-provider-engine.model.ts` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMYEh6D3b21Cn0bl0P:-NWMYEh6D3b21Cn0bl0Q:bwcwmoy) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/shared/models/data-provider-engine.model.ts#L17)):*
> ```XML
>  * behavior, you should return this parameter directly or `true` if this parameter is undefined.
>  *
>  * WARNING: Never run this in the `get<data_type>` method! It will create a destructive infinite loop.
> ```

I see a bunch of these warning comments throughout the code. Is there an other (better?) way of instructing/forcing users to use this code in a proper way, other than these comments?


<!-- Sent from Reviewable.io -->

2023-05-26 14:25 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206)* status: 12 of 17 files reviewed, 6 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMP7TaBRQ1YAmfzsQ8:-NWN9xoV7WpD3fOfxo2b:burdx01) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/hello-someone/hello-someone.ts#L37)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

setGreeting should return a promise, but to me it looks like it's returning an array of strings. Can you help me understand what's going on here?
</blockquote></details>

When you mark a function `async`, it automatically wrap the return in a promise :)
___
*[`extensions/lib/hello-world/hello-world.ts` line 55 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMSBU8C-6R_ziUr7Zt:-NWNA8RZ7b1b8DfAceNP:btzbxg7) ([raw file](https://github.com/paranext/paranext-core/blob/bc370840b6d54bec954f567ae561ee96942e7f0b/extensions/lib/hello-world/hello-world.ts#L55)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Why was the type defintion removed?
</blockquote></details>

It has inferred types now. `billGreeting` is now `string | undefined`, so I figured I'd just take it out since it's kinda ugly.
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 47 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMTBtlE9GSnCV7Qpyg:-NWNAkSQEdvvcNlPYt0A:b-ore1d5) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/hello-world/hello-world.web-view.tsx#L47)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I know it doesn't make sense, but what would happen if you would do something like
`useData.Greeting<GreetingsDataTypes['Age']>`?

</blockquote></details>

I think it would mess up the data types for you. Unfortunately, this is the best I could figure out how to do. I tried very hard to make it so you could just put the data provider type or even data types, but everything I tried resulted in losing type support.

I did actually figure out a different solution that gives a biiiit more type support, so I'm doing that instead.
___
*[`src/renderer/hooks/papi-hooks/use-data.hook.ts` line 161 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMY4qy1XEHLgiw4dbm:-NWNR32n7elBGu7zUfX6:b5zkbha) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/renderer/hooks/papi-hooks/use-data.hook.ts#L161)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Is there a way to enforce this?
</blockquote></details>

I don't believe so - I believe it's up to the developer. React does some weird stuff that aren't really "typed".
___
*[`src/renderer/hooks/papi-hooks/use-data.hook.ts` line 194 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMXyS92_M9ThYSSag-:-NWNRK5KDt-8QVLYBZA1:br5xm8e) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/renderer/hooks/papi-hooks/use-data.hook.ts#L194)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Then why do you declare/expose it?
</blockquote></details>

Because the default `set` for a proxy is to just set the prop on the object. So here I'm removing users' ability to change the object. :)
___
*[`src/shared/models/data-provider-engine.model.ts` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMYEh6D3b21Cn0bl0P:-NWNRbiE7fy95912wvql:bylaozq) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/shared/models/data-provider-engine.model.ts#L17)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I see a bunch of these warning comments throughout the code. Is there an other (better?) way of instructing/forcing users to use this code in a proper way, other than these comments?
</blockquote></details>

Not to my understanding. If anyone else has ideas, I'm certainly open to them.


<!-- Sent from Reviewable.io -->

2023-05-26 14:55 UTC, rolfheij-sil submitted a review, later dismissed
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-05-26 19:44 UTC, lyonsil reviewed
I have a mix of design level and code level questions/thoughts, and it's hard to tease them apart completely.  For example:
- What other approaches were considered besides looking for `get`, `set`, and `subscribe` as "magic words" in function names?  I'm definitely concerned about someone creating a function not intended to be consumed by a data provider that starts with one of those words and not understanding why their data provider engine won't register properly.  I wonder what other avenues you started going down and realized were bad ideas for some reason.
- These changes provide nice granularity but add extra complexity.  Did we look at simplifying any existing design, like having `TSelector` always be `string` or `TGetData` and `TSetData` always being the same type?  Those might be bad examples, but overall it would be nice to not make an already somewhat complex part of the code more complicated if we can simply some parts at the same time.  From your comments perhaps even TypeScript couldn't keep up with some of the types in the new model.
- In a couple of places I see `*` as a magic value, and in a couple of other places I see `all` as a magic value.  I believe they are provided in different places as part of different types, but they are close enough in meaning that I wonder if people will be confused by similar, but different magic values.

I wonder if it would be helpful to have a short guide on how people are intended to create and consume data providers if these changes are merged as-is.  Or maybe just a meeting to explain the various types, how they relate to each other, and what types  are used for different purposes would help.  (If you meet to discuss when I'm gone, please record it.)  I think our sample extension provide some details, but there are nuances I don't understand like:
- What is the real "minimal set" of things a data provider author needs to do?
- I see some functions can, but don't have to be written by data providers since the framework will do it for them.  What is the full set of optional functions?  When/why would a data provider override default behavior?
- There are some warnings along the lines of "don't call `get` here or this will blow up."  What are all the concerns/caveats that we know of in the current design?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206#-:-NWOMM5T04Mju4bZjwq0:b-p9qqvp)* status: 15 of 17 files reviewed, 8 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-05-26 21:25 UTC, tjcouch-sil reviewed
In response to your design/code stuff:
1. There wasn't much else considered other than these magic words. There were a handful of other approaches we considered using magic words, but this one seemed cleanest and easiest to understand. The main other approach we have considered is allowing them to provide some kind of object that they can put function names in to describe different parts of the functionality. But that feels really annoying because then you have to update stuff in multiple places. I certainly appreciate that these magic words could be confusing. I will change `internalSet` to `#setInternal` (a private method that I don't think will be picked up by papi) to see if that makes anything clearer. What do you think of just making the difference private vs public functions? Alternately, would changing the magic words make it better in your mind? Like prefixing everything with `dp` like `dpSet<data_type>` or something? Do you have any other suggestions for any of this topic?
2. `TSelector`, `TGetData`, and `TSetData` are very intentionally how they are. I think people should be able to set up data providers with whatever selectors they want. For example, our Scripture provider probably would want in some cases to have a ScrRef object as a selector. Also, I originally had `TSetData` and `TGetData` as the same `TData`, but that failed almost immediately. I expect there are few cases where they will actually be the same. However, people who want to simplify things can - `DataProviderDataTypes` defaults subsequent generics to their prior generic. So you could do `DataProviderDataTypes<string>`, and all three would be string. Any suggestions for improvement on this topic?
3. Seems like a reasonable idea. I'll look into it! Originally I used `'all'` in both cases but realized that would overlap with a possible data type, so I changed it in the place where that would be important but not in the other place that uses it.

Yes, I agree that a data provider API guide is in order. Thanks for the feedback!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206#-:-NWOu6z29CpXOWahkmjL:b6dih00)* status: 15 of 17 files reviewed, 8 unresolved discussions (waiting on @lyonsil and @rolfheij-sil)

___
*[`src/renderer/hooks/papi-hooks/use-data.hook.ts` line 179 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNaXPB9rH_EqGw_ZMB:-NWOsodHBT1VEURiJxva:b-2f6zrq) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/renderer/hooks/papi-hooks/use-data.hook.ts#L179)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Interesting use of a proxy here.  Do we need to be concerned about data providers going away?  Like if someone disables an extension that had a data provider does the cache here need to be purged?
</blockquote></details>

If I understand you correctly, there is no need to delete the proxy functions if data providers are disposed - these functions aren't tied to any data provider in particular. You pass the data provider into the hook function.
___
*[`src/shared/models/data-provider-engine.model.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNcPTuCd7WY6FjdNSV:-NWOtObID5xKRcbgRXwk:b-93el2p) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/shared/models/data-provider-engine.model.ts#L19)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I think I need to chew on this one for a while, but at first glace it's confusing to me to have a function that is intended to update data take in "instructions" and also return "instructions".  I would think an "update" function that takes in instructions either returns nothing or returns something about the update operation itself (succeeded/failed, list of clients to update, etc.).  A function that takes instructions and returns instructions seems more like a configuration-type operation, not a data update operation.
</blockquote></details>

Is it better to just go ahead and use the input parameter and then run the data provider's notifyUpdate afterward just to kinda "let them know"? That way, they wouldn't ever be able to mess with the return from a notify update like if they wanted to make it so it updates all data types if you run `notifyUpdateAll()` or something. Seems like the signature is confusing indeed, but I dunno what else to do.


<!-- Sent from Reviewable.io -->

2023-05-26 22:13 UTC, lyonsil reviewed
1. In other languages, a pattern I would expect to follow for what we're doing is that I would register an instance of a class that implements an interface provided by the framework.  The framework might say, "Here's IDataProvider that we defined, go create an object that implements it and pass that object into `RegisterDataProvider()`."  The approach we're taking with network objects and data providers where we mutate objects and create proxies works, but it feels very bespoke.  With data providers it's even more so because of the magic words.  That might just be my lack of experience in TS/JS, so I can't push on this too hard with high confidence.  However, the more bespoke something is, the higher the bar is for extension developers to build something.

I realize there are many cases where modules in TS/JS are preferred over classes.  I'm not saying classes are necessarily the right answer here.  However, I think there is something to be said for interfaces.  When I'm building something that needs to be standardized in some way because someone else is going to call my code, I want to have a very clear picture of how they are going to call my code.  Interfaces are very well known ideas in many languages that serve this purpose.  Magic words combined with reflection works, but taking that approach essentially requires developers to read and understand what they need to do in depth.  They can't reuse as much of what they've learned previously.

(As an aside, with network objects I think the mutation + proxies makes more sense because we really want to reflect every property out to users.  With data providers, there is a lot more structure and expectations about what the engine provides in terms of properties, so repeating the same approach isn't as natural to me.)

All this being said, if we stick with this approach, I would vote for `dpGet` over just `get` because `get` and `set` are so commonly used in function names it will be easy for developers to make a mistake.

A guide will probably be needed if the pattern isn't a common one that developers will be used to using.  If an API is obvious enough at first glance, the need for a guide is probably lower.

2. I was picking on those 3 data types mostly because they get passed around a lot, so if they could be simplified it might simplify a lot of other interfaces.  I'm not saying there is anything wrong with them per se.  My main point is that the data provider model is kind of complicated.  11 export types, most of which rely on each other, and a few other things are in that model file.  I am just trying to see if we can make the model simpler in some way.

3. `all` vs `*` usage isn't a huge thing, but going back to the point above, I think we should try to simplify this if we can.  This was just a small case I noticed.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206#-:-NWP-5FqCjtk8EgfB45b:b5btfk3)* status: 15 of 17 files reviewed, 7 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-05-26 22:36 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206)* status: 15 of 17 files reviewed, 7 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`src/shared/models/data-provider-engine.model.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNcPTuCd7WY6FjdNSV:-NWP7ioA88me6315EkTt:b-lkqeji) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/shared/models/data-provider-engine.model.ts#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is it better to just go ahead and use the input parameter and then run the data provider's notifyUpdate afterward just to kinda "let them know"? That way, they wouldn't ever be able to mess with the return from a notify update like if they wanted to make it so it updates all data types if you run `notifyUpdateAll()` or something. Seems like the signature is confusing indeed, but I dunno what else to do.
</blockquote></details>

After thinking about this one for a while and looking at the code, I'm still a little perplexed about this function.  I don't quite follow (line 356 of `data-provider.service.ts`) what this means:
```
        let dpeNotifyUpdateResult: DataProviderUpdateInstructions<TDataTypes> | undefined = args[0] === undefined ? true : args[0];
```

How are the results of an update operation typed as instructions for the update operation that are already done?  It's circular reasoning.  I must be missing something here because I'm sure that's not what you mean.  The caller would have known the parameters they passed in, so they don't need them returned back.  Also we're not chaining together calls on the instructions like you would in a builder pattern in Java.


<!-- Sent from Reviewable.io -->

2023-05-29 03:38 UTC, irahopkinson requested changes
I would agree with @lyonsil comments on design. However, if the current design is better than what we already have I would be ok merging this design as long as it doesn't make it harder to implement a better design. If we did merge this PR it wouldn't complete issue #109 until the design concerns where addressed.

> Reviewed 12 of 17 files at r1, 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206#-:-NW_ZNFP-p1DHjtspvOZ:b-ctaxez)* status: all files reviewed, 11 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 20 at r4](https://reviewable.io/reviews/paranext/paranext-core/206#-NWZ_Q2LEkaKw_pEODZe:-NWZ_Q2LEkaKw_pEODZf:b-pdtxmf) ([raw file](https://github.com/paranext/paranext-core/blob/7a30556b3e45058f21a3e9619ae6fdea68f1f39f/extensions/lib/hello-someone/hello-someone.ts#L20)):*
> ```XML
>     bill: { greeting: 'Hi, my name is Bill!', age: 43 },
>     kathy: { greeting: 'Hello. My name is Kathy.', age: 35 },
>   } as AllGreetingsData,
> ```

This is overcoming the type system. If someone changes `people` and it doesn't conform to the `AllGreetingsData` type then nothing will complain since the type is asserted `as AllGreetingsData` even if it is not. You could type the whole engine object but if you just want to type the `people` property then a simple solution is to create `people` first with its type declared and then simply include it in the engine, i.e.
```typescript
const people: AllGreetingsData = {
  bill: { greeting: 'Hi, my name is Bill!', age: 43 },
  kathy: { greeting: 'Hello. My name is Kathy.', age: 35 },
};
 
// ...
const greetingsDataProviderEngine = {
  people,

  // ...
};

```
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 32 at r4](https://reviewable.io/reviews/paranext/paranext-core/206#-NWZjRRy1kRe_f4G3Y6j:-NWZjRRz3t0IK9NwBCes:bo1dorc) ([raw file](https://github.com/paranext/paranext-core/blob/7a30556b3e45058f21a3e9619ae6fdea68f1f39f/extensions/lib/hello-someone/hello-someone.ts#L32)):*
> ```XML
>     this.ensurePersonExists(name);
>     // If there is no change in the greeting, don't update
>     if (greeting === this.people[name.toLowerCase()]!.greeting) return false;
> ```

You can get ride of the 4x non-null assertions (and therefore not need to disable eslint) if you remove the unnecessary `undefined` from the `AllGreetingsData` declaration, i.e.:
```typescript
export type AllGreetingsData = {
  [name: string]: Person;
};
```
___
*[`extensions/lib/hello-someone/hello-someone.d.ts` line 1 at r4](https://reviewable.io/reviews/paranext/paranext-core/206#-NWZV0I-BgCrutQlGzDg:-NWZV0I-BgCrutQlGzDh:bjaw9om) ([raw file](https://github.com/paranext/paranext-core/blob/7a30556b3e45058f21a3e9619ae6fdea68f1f39f/extensions/lib/hello-someone/hello-someone.d.ts#L1)):*
> ```XML
> import type IDataProvider from 'shared/models/data-provider.interface';
> ```

BTW I'm not sure why this file exists. Wouldn't it be better to just declare these in usual code and have the `.d.ts` files generated? Perhaps vite doesn't do that yet for WebViews and this is to be done in another issue?
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 47 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMTBtlE9GSnCV7Qpyg:-NWZo0nGEqARIKg9Jbr7:b-e9qt8k) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/hello-world/hello-world.web-view.tsx#L47)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it would mess up the data types for you. Unfortunately, this is the best I could figure out how to do. I tried very hard to make it so you could just put the data provider type or even data types, but everything I tried resulted in losing type support.

I did actually figure out a different solution that gives a biiiit more type support, so I'm doing that instead.
</blockquote></details>

It would make more sense to me as programmer to need to do `useData<'Greeting'>.Greeting<GreetingsDataTypes>(`, is that a possible way to handle it or is that more complicated (or less) to implement (and keep type support)?

I haven't thought too deeply about the types since they are already pretty complex and so this suggestion just might not be possible.
___
*[`src/shared/models/data-provider-engine.model.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNcPTuCd7WY6FjdNSV:-NW_FrhxBbL6pjK72Gsu:b-6x82vv) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/shared/models/data-provider-engine.model.ts#L19)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

After thinking about this one for a while and looking at the code, I'm still a little perplexed about this function.  I don't quite follow (line 356 of `data-provider.service.ts`) what this means:
```
        let dpeNotifyUpdateResult: DataProviderUpdateInstructions<TDataTypes> | undefined = args[0] === undefined ? true : args[0];
```

How are the results of an update operation typed as instructions for the update operation that are already done?  It's circular reasoning.  I must be missing something here because I'm sure that's not what you mean.  The caller would have known the parameters they passed in, so they don't need them returned back.  Also we're not chaining together calls on the instructions like you would in a builder pattern in Java.
</blockquote></details>

I was confused by "_instructions_" too. Would it help if we renamed `DataProviderUpdateInstructions` to something like `DataProviderUpdateSettings`?
___
*[`src/shared/utils/util.ts` line 170 at r4](https://reviewable.io/reviews/paranext/paranext-core/206#-NWZN0M-Ef-ikDju8xXC:-NWZN0M-Ef-ikDju8xXD:bmziudt) ([raw file](https://github.com/paranext/paranext-core/blob/7a30556b3e45058f21a3e9619ae6fdea68f1f39f/src/shared/utils/util.ts#L170)):*
> ```XML
> // We want to use any so it can be an object, number, string, etc. Just can't be null or undefined
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> export function getAllObjectFunctionNames(obj: NonNullable<any>) {
> ```

BTW I can't remember if we settled on using `lodash` (or some other library) since it's already included in our bundle anyway, but I think this function does the same thing https://lodash.com/docs/4.17.15#functionsIn or https://lodash.com/docs/4.17.15#functions and are well tested.


<!-- Sent from Reviewable.io -->

2023-06-01 18:08 UTC, tjcouch-sil reviewed
After lots of discussion (notes below), we came down on some decisions (bold) regarding the following issues:

- Recommended pattern - object vs class
  - **object for starting, getting hang of api, class for advanced usage like multiple of the same data provider**
    - Objects have slightly better intellisense - you can see a list of all the functions you need to implement. Classes can extend a notifyUpdate class. You can make multiple objects of one class. Classes don't have to specify their extra properties/methods exactly. Classes have private methods. Classes have full support on decorators.
- Accidental creation of papi functions
  - One get and one set? Like `get(dataType: string, selector: TDataTypes[DataType]['selector']): TDataTypes[DataType]['getData']`
    - Sadly the other parameters' types don't narrow when you narrow the data type parameter
  - Prefix on get/set?
  - Create new function like SetVerse?
  - Have capital SetVerse/GetVerse be the function that is layered over?
  - Don't layer over - require anything that wants to update outside a set function to use notifyUpdate
  - __ignoredMethods prop on data provider?
  - Ignore methods that don't have pairs
  - **@ignore decorator**
    - Can import from papi. Only really works on classes, but we can work around for objects. Seems like it makes sense to have functions enabled by default as you are creating a data provider
  - @set('Verse') decorator? Might require knowing functions on remote. Unless we used some kind of special function names that weren't the actual function names or required the functions be the right name for the decorator to work. Won't have accidental functions being enabled, but it's a lot of extra work
- Let people run get/set with whatever arguments they want?
  - Subscribe/hook builders
    - subscribe builder - provide options
    - useData builder - provide default value, options
    - Unwieldy, very unrecognizable pattern
  - Move all the parameters up and let rest parameters be the set/get args
    - subscribe - callback, options, then args
    - useData - data provider name, default value, options, then args
    - Would never be able to add arguments without breaking change
  - **Leave it to one selector. People can make a specifically typed array to imitate multiple parameters**
    - Make example Verses that has array of refs

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206#-:-NWs3SnCBtozzRMCeNcs:b-n4bryy)* status: 8 of 19 files reviewed, 9 unresolved discussions (waiting on @irahopkinson, @lyonsil, and @rolfheij-sil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 14 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNS-mV6T3eI9z0yZMY:-NWPCF928ICiGuM_KZBz:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/hello-someone/hello-someone.ts#L14)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Would it be simpler to have a `getPerson()` method that creates the person if needed and then returns it? As in:
```
  getPerson(name: string) {
    const lowerCaseName: string = name.toLowerCase();
    if (!this.people[lowerCaseName]) this.people[lowerCaseName] = {};
    return this.people[lowerCaseName];
  },
```

Then, for instance, `getAge()` could change to the following with no non-null assertions.  It would get rid of a lot of `toLowerCase()` calls, too.
```
  async getAge(name: string) {
    return getPerson(name).age;
  },
```
</blockquote></details>

Done
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNTJDz80t0RIEPOXqd:-NWPCOKB8FPfst31HMK6:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/hello-someone/hello-someone.ts#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Since this is an example, it might be nice to add JSDoc comments explaining what the return type means.  Same with later functions.
</blockquote></details>

Done
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 20 at r4](https://reviewable.io/reviews/paranext/paranext-core/206#-NWZ_Q2LEkaKw_pEODZe:-NWhX1ggCbi0XdM1vmhH:b98lpt7) ([raw file](https://github.com/paranext/paranext-core/blob/7a30556b3e45058f21a3e9619ae6fdea68f1f39f/extensions/lib/hello-someone/hello-someone.ts#L20)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is overcoming the type system. If someone changes `people` and it doesn't conform to the `AllGreetingsData` type then nothing will complain since the type is asserted `as AllGreetingsData` even if it is not. You could type the whole engine object but if you just want to type the `people` property then a simple solution is to create `people` first with its type declared and then simply include it in the engine, i.e.
```typescript
const people: AllGreetingsData = {
  bill: { greeting: 'Hi, my name is Bill!', age: 43 },
  kathy: { greeting: 'Hello. My name is Kathy.', age: 35 },
};
 
// ...
const greetingsDataProviderEngine = {
  people,

  // ...
};

```
</blockquote></details>

Type assertion (without `as unknown` in the middle) does check to make sure the types are compatible, meaning you can use the object as the type. However, it does not check tightly to make sure every member is strictly the exact object literal type. So, as it is now, you can add unknown properties to the people, but you cannot specify a known prop with the wrong type. I am doing some rework, though, so this will be changed to have stronger typing.
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 32 at r4](https://reviewable.io/reviews/paranext/paranext-core/206#-NWZjRRy1kRe_f4G3Y6j:-NWm6aBS0zyYVwlQWjvv:bh5bqg8) ([raw file](https://github.com/paranext/paranext-core/blob/7a30556b3e45058f21a3e9619ae6fdea68f1f39f/extensions/lib/hello-someone/hello-someone.ts#L32)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

You can get ride of the 4x non-null assertions (and therefore not need to disable eslint) if you remove the unnecessary `undefined` from the `AllGreetingsData` declaration, i.e.:
```typescript
export type AllGreetingsData = {
  [name: string]: Person;
};
```
</blockquote></details>

I got rid of the assertions another way. It seems like a meaningful difference in the data that some people do not exist. Though I suppose I could alternatively refactor so the difference is not meaningful... Does it seem to reduce complexity enough? I prefer to leave it.
___
*[`extensions/lib/hello-someone/hello-someone.d.ts` line 1 at r4](https://reviewable.io/reviews/paranext/paranext-core/206#-NWZV0I-BgCrutQlGzDg:-NWm7Rhe-Qi33lICvA7F:b-v6ibfq) ([raw file](https://github.com/paranext/paranext-core/blob/7a30556b3e45058f21a3e9619ae6fdea68f1f39f/extensions/lib/hello-someone/hello-someone.d.ts#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I'm not sure why this file exists. Wouldn't it be better to just declare these in usual code and have the `.d.ts` files generated? Perhaps vite doesn't do that yet for WebViews and this is to be done in another issue?
</blockquote></details>

Yes, it would be better to generate these type files - there is a `TODO` in `quick-verse.d.ts` about that. However, I have not set it up. I imagine that would be part of #69
___
*[`extensions/lib/hello-world/hello-world.ts` line 55 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMSBU8C-6R_ziUr7Zt:-NWPCVjt69UxdhW7mXBT:bjhxfxu) ([raw file](https://github.com/paranext/paranext-core/blob/bc370840b6d54bec954f567ae561ee96942e7f0b/extensions/lib/hello-world/hello-world.ts#L55)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I think it is a little c [...]

2023-06-02 01:17 UTC, irahopkinson requested changes
> Reviewed 9 of 11 files at r5, 7 of 8 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206)* status: all files reviewed, 10 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 32 at r4](https://reviewable.io/reviews/paranext/paranext-core/206#-NWZjRRy1kRe_f4G3Y6j:-NWtPw9X64zs7HPB7itc:bgj1yey) ([raw file](https://github.com/paranext/paranext-core/blob/7a30556b3e45058f21a3e9619ae6fdea68f1f39f/extensions/lib/hello-someone/hello-someone.ts#L32)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I got rid of the assertions another way. It seems like a meaningful difference in the data that some people do not exist. Though I suppose I could alternatively refactor so the difference is not meaningful... Does it seem to reduce complexity enough? I prefer to leave it.
</blockquote></details>

I think the distinction is unhelpful. If a person doesn't exist, don't add them as `undefined` - just don't add them. However, what you have now is better and probably not worth spending more time on.
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 27 at r5](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtMJ-d0CUyw5w66vfj:-NWtMJ-d0CUyw5w66vfk:bc8i8mq) ([raw file](https://github.com/paranext/paranext-core/blob/b9dc03085268e4c915e22322aea8d2b050cba6f4/extensions/lib/hello-someone/hello-someone.ts#L27)):*
> ```XML
>  *  - Greeting: a person's greeting
>  *  - Age: a person's age
>  *  - All: information about all the people associated with this engine
> ```

This JDSoc was very helpful to quickly see what is intended - thanks for adding them all.

Perhaps renaming `All` to `People` would make things clearer (then `AllGreetingsData` would change to `PeopleData` and make that clearer too).
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 52 at r5](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtP-ZT0ia4Gu3vSJHc:-NWtP-ZT0ia4Gu3vSJHd:b-rly17t) ([raw file](https://github.com/paranext/paranext-core/blob/b9dc03085268e4c915e22322aea8d2b050cba6f4/extensions/lib/hello-someone/hello-someone.ts#L52)):*
> ```XML
>    * Get a person by name. By default, creates that person if they don't exist yet
>    * @param name name of person
>    * @param createIfDoesNotExist whether to create the person if they doesn't exist. Defaults to true
> ```

sp: they `don't` exist.
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 192 at r5](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtRRMa27gLdfoeTktQ:-NWtRRMa27gLdfoeTktR:b-4kk32i) ([raw file](https://github.com/paranext/paranext-core/blob/b9dc03085268e4c915e22322aea8d2b050cba6f4/extensions/lib/hello-someone/hello-someone.ts#L192)):*
> ```XML
>     const person = this.getPerson(name, false);
>     if (person) {
>       logger.log(`RIP ${name}, who died tragically young at age ${person.age}. ;(`);
> ```

Use `logger.info` instead.



_Code quote:_
```XML
logger.log
```
___
*[`extensions/lib/quick-verse/quick-verse.ts` line 52 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNWBGxDZJhlOfBXbrZ:-NWtTTX313efLOxCx5Zf:b-ma4ejy) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/quick-verse/quick-verse.ts#L52)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I added an `@return`, but I think we don't need an explicit return type for these methods as the interface this class implements informs Intellisense of the method signatures. Let me know your thoughts.
</blockquote></details>

I'll add this to our style discussion. Explicit return types have saved me a few times when it inferred what I wasn't expecting. Plus it makes code review easier because review tools don't allow you to hover and see the type like in VS Code.
___
*[`extensions/lib/quick-verse/quick-verse.ts` line 50 at r7](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtaB29EXLlWhFRJ7QB:-NWtaB29EXLlWhFRJ7QC:b-de972l) ([raw file](https://github.com/paranext/paranext-core/blob/a270062dc6c9f97004414415a31aeb695be3e6aa/extensions/lib/quick-verse/quick-verse.ts#L50)):*
> ```XML
>  *    - You must specify parameter and return types. They are not inferred
>  *
>  * can create extra properties/methods without having to specify them in this type and private
> ```

Is this sentence in the right place? It seems disconnected from where it should be.
___
*[`src/shared/services/data-provider.service.ts` line 55 at r6](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtcXh8EQGxCnTN76FM:-NWtcXh8EQGxCnTN76FN:b6imt9p) ([raw file](https://github.com/paranext/paranext-core/blob/815d634d06d6bb5fd22a1a0998587824c68172bd/src/shared/services/data-provider.service.ts#L55)):*
> ```XML
> /**
>  * Abstract class that provides a placeholder `notifyUpdate` so data provider engine classes don't
>  * have to write their own if they want to use `notifyUpdate` if they don't want to.
> ```

This sentence is awkward and could use some revision.
___
*[`src/shared/services/data-provider.service.ts` line 293 at r6](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtcv43ALzA4VzK1NKg:-NWtcv43ALzA4VzK1NKh:b36fitt) ([raw file](https://github.com/paranext/paranext-core/blob/815d634d06d6bb5fd22a1a0998587824c68172bd/src/shared/services/data-provider.service.ts#L293)):*
> ```XML
> function mapUpdateInstructionsToUpdateEvent<TDataTypes extends DataProviderDataTypes>(
>   updateInstructions: DataProviderUpdateInstructions<TDataTypes> | undefined,
>   dataType: DataTypeNames<TDataTypes> | null,
> ```

Why `null` here instead of `undefined`? `undefined` would better indicate it doesn't have a data type IMHO.


<!-- Sent from Reviewable.io -->

2023-06-02 04:11 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206)* status: all files reviewed, 11 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`src/shared/models/data-provider-engine.model.ts` line 53 at r7](https://reviewable.io/reviews/paranext/paranext-core/206#-NWuGucjDbrtN-gn7H5v:-NWuGucjDbrtN-gn7H5w:b-cviep6) ([raw file](https://github.com/paranext/paranext-core/blob/a270062dc6c9f97004414415a31aeb695be3e6aa/src/shared/models/data-provider-engine.model.ts#L53)):*
> ```XML
>  * @see HasNotifyUpdate for more information on using this type.
>  */
> export type HasNotifyUpdate<TDataTypes extends DataProviderDataTypes> = {
> ```

This looks too much like a boolean name. How about something like `WithNotifyUpdate`?



_Code quote:_
```XML
HasNotifyUpdate
```


<!-- Sent from Reviewable.io -->

2023-06-02 17:00 UTC, tjcouch-sil reviewed
We are asking the extension team to test out this API and determine what is good and bad about it, what is difficult to understand, etc.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206#-:-NWwy_Rr7gbsMxiQwv5_:b77zlms)* status: 8 of 19 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @rolfheij-sil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 32 at r4](https://reviewable.io/reviews/paranext/paranext-core/206#-NWZjRRy1kRe_f4G3Y6j:-NWwO4Q37s3oOZpPRsMF:b-75dbhl) ([raw file](https://github.com/paranext/paranext-core/blob/7a30556b3e45058f21a3e9619ae6fdea68f1f39f/extensions/lib/hello-someone/hello-someone.ts#L32)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I think the distinction is unhelpful. If a person doesn't exist, don't add them as `undefined` - just don't add them. However, what you have now is better and probably not worth spending more time on.
</blockquote></details>

I am not adding them as `undefined`. I believe index signatures like this define the data type for any string key, so that would mean I would have to guarantee there is a person at any string index. Since that is not the case, however, I added `undefined` to indicate not every string has a person.

If I remove `undefined` from the index signature and I try to get a person, TypeScript thinks that person is definitely defined:
![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/toLHY_8dYskDZvrCKrM_xJhJ/image.png)
However, since that person is not necessarily defined, I decided to add `undefined`. A clearer and more accurate type would be to make the index optional so it implicitly adds `undefined`, but optional index signatures seem to be unsupported in TypeScript for some reason. Hence the manually specified `undefined`.
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 27 at r5](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtMJ-d0CUyw5w66vfj:-NWwgKU30nY7TgwQQbRa:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/b9dc03085268e4c915e22322aea8d2b050cba6f4/extensions/lib/hello-someone/hello-someone.ts#L27)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This JDSoc was very helpful to quickly see what is intended - thanks for adding them all.

Perhaps renaming `All` to `People` would make things clearer (then `AllGreetingsData` would change to `PeopleData` and make that clearer too).
</blockquote></details>

Done
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 192 at r5](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtRRMa27gLdfoeTktQ:-NWwPj2kChO_Ujxkyq0K:bnpf5f7) ([raw file](https://github.com/paranext/paranext-core/blob/b9dc03085268e4c915e22322aea8d2b050cba6f4/extensions/lib/hello-someone/hello-someone.ts#L192)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Use `logger.info` instead.
</blockquote></details>

Oops! Maybe we should rip this out of the type and/or shim it out or something so people don't use it haha would you be interested in pursuing such an idea? Or making an issue for it?
___
*[`extensions/lib/quick-verse/quick-verse.ts` line 50 at r7](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtaB29EXLlWhFRJ7QB:-NWwPuXoEY9PrFfJrGMA:b-ffit3s) ([raw file](https://github.com/paranext/paranext-core/blob/a270062dc6c9f97004414415a31aeb695be3e6aa/extensions/lib/quick-verse/quick-verse.ts#L50)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Is this sentence in the right place? It seems disconnected from where it should be.
</blockquote></details>

Oops! Haha I forgot to remove this once I reformatted this comment. Thanks!
___
*[`src/shared/models/data-provider-engine.model.ts` line 53 at r7](https://reviewable.io/reviews/paranext/paranext-core/206#-NWuGucjDbrtN-gn7H5v:-NWwQixq37mf9zkoS4rW:b-opshx) ([raw file](https://github.com/paranext/paranext-core/blob/a270062dc6c9f97004414415a31aeb695be3e6aa/src/shared/models/data-provider-engine.model.ts#L53)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This looks too much like a boolean name. How about something like `WithNotifyUpdate`?
</blockquote></details>

Sure! Done
___
*[`src/shared/services/data-provider.service.ts` line 55 at r6](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtcXh8EQGxCnTN76FM:-NWwSs8a4lIjf701631B:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/815d634d06d6bb5fd22a1a0998587824c68172bd/src/shared/services/data-provider.service.ts#L55)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This sentence is awkward and could use some revision.
</blockquote></details>

Done.
___
*[`src/shared/services/data-provider.service.ts` line 293 at r6](https://reviewable.io/reviews/paranext/paranext-core/206#-NWtcv43ALzA4VzK1NKg:-NWwQqaiCFmEcK7qa2Yh:b-dsle7c) ([raw file](https://github.com/paranext/paranext-core/blob/815d634d06d6bb5fd22a1a0998587824c68172bd/src/shared/services/data-provider.service.ts#L293)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Why `null` here instead of `undefined`? `undefined` would better indicate it doesn't have a data type IMHO.
</blockquote></details>

I wanted to clarify specifically that we consciously and intentionally set it to nothing, and I thought we decided we would use null in those cases. However, I guess maybe we didn't decide that - the style google doc says we prefer undefined with no caveats. I suppose `undefined` would work just fine, but I want to match specifically to whatever our 'nothing' is because empty string is a data type even though it is falsy. It will just look a bit weirder to `=== undefined`, but I'll go ahead and change it. Let me know your thoughts :)


<!-- Sent from Reviewable.io -->

2023-06-06 00:22 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 16 of 16 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206#-:-NXD4LW99Fj0abG7wnqV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 32 at r4](https://reviewable.io/reviews/paranext/paranext-core/206#-NWZjRRy1kRe_f4G3Y6j:-NXD4CWA3BAVAGgtk-Gp:bpkrn2t) ([raw file](https://github.com/paranext/paranext-core/blob/7a30556b3e45058f21a3e9619ae6fdea68f1f39f/extensions/lib/hello-someone/hello-someone.ts#L32)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I am not adding them as `undefined`. I believe index signatures like this define the data type for any string key, so that would mean I would have to guarantee there is a person at any string index. Since that is not the case, however, I added `undefined` to indicate not every string has a person.

If I remove `undefined` from the index signature and I try to get a person, TypeScript thinks that person is definitely defined:
![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/toLHY_8dYskDZvrCKrM_xJhJ/image.png)
However, since that person is not necessarily defined, I decided to add `undefined`. A clearer and more accurate type would be to make the index optional so it implicitly adds `undefined`, but optional index signatures seem to be unsupported in TypeScript for some reason. Hence the manually specified `undefined`.
</blockquote></details>

Yes, you are right.
___
*[`extensions/lib/hello-someone/hello-someone.web-view.ejs` line 37 at r8](https://reviewable.io/reviews/paranext/paranext-core/206#-NXCnqoCA101a-8wFkFR:-NXCnqoCA101a-8wFkFS:b-h2mm9h) ([raw file](https://github.com/paranext/paranext-core/blob/94ac0271f8c4d404d780d06c10507260bd9a9fbe/extensions/lib/hello-someone/hello-someone.web-view.ejs#L37)):*
> ```EJS
>       }
> 
>       const dataProviderPromise = papi.dataProvider.get('hello-someone\.people');
> ```

BTW I'm surprised to see the `\` added before the period. Did the period need to be escaped?
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 67 at r8](https://reviewable.io/reviews/paranext/paranext-core/206#-NXCoHr9DzNkYsXAuPxl:-NXCoHr9DzNkYsXAuPxm:bo201nc) ([raw file](https://github.com/paranext/paranext-core/blob/94ac0271f8c4d404d780d06c10507260bd9a9fbe/extensions/lib/hello-world/hello-world.web-view.tsx#L67)):*
> ```XML
>   const [psalm1] = useData.Chapter<QuickVerseDataTypes, 'Chapter'>(
>     'quick-verse.quick-verse',
>     ['Psalm', 1],
> ```

Nice demo of this. Thanks for adding it.


<!-- Sent from Reviewable.io -->

2023-06-08 19:54 UTC, lyonsil approved these changes
Thanks for really digging into my points, considering possible changes, and making updates.  Clearly you put a lot of effort into this, and I appreciate it!

I think getting user feedback, even if the sample size is small for now, is a good next step.  Although there are some variations here from what I could call "typical patterns" in other languages, I can understand how/why we might vary in TS/JS.  Let's roll with this and see what feedback is.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r3, 1 of 11 files at r5, 1 of 8 files at r6, 16 of 16 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206#-:-NXRYxYu1r6lZzjNqyc3:b-pc73o0)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/lib/hello-world/hello-world.ts` line 55 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWMSBU8C-6R_ziUr7Zt:-NXR3zkSBQHnDMb94rq9:b-rwvgod) ([raw file](https://github.com/paranext/paranext-core/blob/bc370840b6d54bec954f567ae561ee96942e7f0b/extensions/lib/hello-world/hello-world.ts#L55)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I prefer to leave it out as it isn't part of this extension. It could go either way, though. I guess I'll put it back in actually. Maybe a topic for style guide discussions...?
</blockquote></details>

This probably is a good style guide discussion topic.  @irahopkinson FYI
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 67 at r8](https://reviewable.io/reviews/paranext/paranext-core/206#-NXCoHr9DzNkYsXAuPxl:-NXR4aEd7Htbw3_twEEU:b-pbdqzg) ([raw file](https://github.com/paranext/paranext-core/blob/94ac0271f8c4d404d780d06c10507260bd9a9fbe/extensions/lib/hello-world/hello-world.web-view.tsx#L67)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nice demo of this. Thanks for adding it.
</blockquote></details>

Agreed!
___
*[`extensions/lib/quick-verse/quick-verse.ts` line 85 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNWS2N8JI7lWYdWXrS:-NXR5hOYAA7rjnw9BDQX:bkl854p) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/quick-verse/quick-verse.ts#L85)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Added description but no return type - inferred. Let me know your thoughts.
</blockquote></details>

Looks like there is a return type now.  I'm assuming this evolved over time.
___
*[`extensions/lib/quick-verse/quick-verse.ts` line 97 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNWZdZ4ogcbza0vxTd:-NXR6Bnw1CioQ9KwgL9B:bkl854p) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/quick-verse/quick-verse.ts#L97)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Added description but no return type - inferred. Let me know your thoughts.
</blockquote></details>

Looks like there is a return type now.  I'm assuming this evolved over time.
___
*[`extensions/lib/quick-verse/quick-verse.ts` line 143 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNXt8R3ST8-5aVp43n:-NXR6LQm1LaFrzaI0x8F:bkl854p) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/quick-verse/quick-verse.ts#L143)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Added description but no return type - inferred. Let me know your thoughts.
</blockquote></details>

Looks like there is a return type now.  I'm assuming this evolved over time.
___
*[`src/shared/models/data-provider-engine.model.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNcPTuCd7WY6FjdNSV:-NXRUlX2-LPvSkbZK__c:b-az4y5t) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/src/shared/models/data-provider-engine.model.ts#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Yes, the way I wrote `notifyUpdate`s was confusing. I will refactor. Hopefully we can revisit after the refactor.

Essentially, the way I wrote it, you could run a `notifyUpdate<data_type>` without creating the function yourself, and it would infer a data type to update based on which one you ran. But you can override them and provide your own functionality. So your override takes in whatever the inferred value is from the built-in version, then you return whatever update instructions you actually want to run. Confusing.

Notes from conversation about the design:

- notifyUpdate
  - Many or one?
    - Many
      - Parallelism
      - Automatically infer which data types to update
    - **One**
      - Can do anything many can do except automatically infer
      - Easier to reason about?
        - Wouldn't get to bake in changes to updates by data type (would have to build your own notifyUpdateVerse or something that runs notifyUpdate internally. Though is that really any different...? Might also be simpler tbh)
    - Combined
      - notifyUpdate<data_type> infers which type to update, no params
        - dev can override to update multiple types, but nothing passed in
      - notifyUpdate defaults to updating all, can specify an input otherwise
        - dev can override, but it just reports the update (runs after update finished)
      - naming collision - empty string data type name
  - Pass-through or run after?
    - **Run after** - just too confusing and not adding much
</blockquote></details>

Thanks for the hard work here.  This makes a lot more sense to me.


<!-- Sent from Reviewable.io -->

2023-06-09 16:00 UTC, katherinejensen00 commented
I just finished updating the Sneezeboard data engine to match these changes. I really like this second way. I think it makes the data types much more intuitive and the code more readable. The process felt more natural and naming variables was a lot easier as I didn't need to think of a word that could be a sneeze or a user. Understanding the context token and some other changes to activate was probably the hardest part, but the examples helped and I was able to figure it out. The documentation and examples are helpful and I was able to get through the process without asking questions.

2023-06-13 20:15 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/lib/hello-someone/hello-someone.web-view.ejs` line 37 at r8](https://reviewable.io/reviews/paranext/paranext-core/206#-NXCnqoCA101a-8wFkFR:-NXqNE8u9Wlk2ciypTo-:b-pb1bps) ([raw file](https://github.com/paranext/paranext-core/blob/94ac0271f8c4d404d780d06c10507260bd9a9fbe/extensions/lib/hello-someone/hello-someone.web-view.ejs#L37)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I'm surprised to see the `\` added before the period. Did the period need to be escaped?
</blockquote></details>

Oops! Dunno how that got there or how I didn't notice haha fixed.
___
*[`extensions/lib/quick-verse/quick-verse.ts` line 143 at r1](https://reviewable.io/reviews/paranext/paranext-core/206#-NWNXt8R3ST8-5aVp43n:-NXqO8MUDj_ZzJ-TftU7:b-dpt00g) ([raw file](https://github.com/paranext/paranext-core/blob/ea48b7554112f3699b47c12503d6126ebf7fcb19/extensions/lib/quick-verse/quick-verse.ts#L143)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Looks like there is a return type now.  I'm assuming this evolved over time.
</blockquote></details>

Oh, I thought you meant in all these that you wanted an explicit return type in the function signature like `async getHeresy(verseRef: string): Promise<string> { ... }`


<!-- Sent from Reviewable.io -->

2023-06-13 23:36 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks for all your great work on this.

> Reviewed 1 of 1 files at r9, 9 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/206#-:-NXr5_Qt25nsM8OWNzGI:bqqllgc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-06-13 23:36 UTC, merged