Create WebViewProvider API, allowing webviews to persist across refreshes
paranext/paranext-core pull request #225
Opened 2023-06-07 23:33 UTC by tjcouch-sil

- Reworked loading and saving tabs so every tab is responsible for its own serialization and deserialization
- Split tab ids into id and tabType
- Tightened up layout-related types for better TypeScript support
- Moved saving and loading layout to web view service
- Created web view provider service that handles web view providers specifically. Each provider is distinct from other providers by having a unique webViewType, which is how the contents of webviews is determined
  - This service is a weird split off from web view service, so I made it internal and not affect extension developers. Seems like a helpful distinction, though. Would love input on any thoughts regarding reworking it. Maybe make a singleton class in web view service? Dunno; not sure it's even worth it right now. Might be best to make an issue if it even warrants it
- Reworked `addWebView` so you provide just a `webViewType`, layout info, and some options. Then the appropriate WebViewProvider takes care of actually making the web view
- `onDidAddWebView` event no longer carries `content` or `styles` so there's not so much unnecessary talk all over the network over webviews
- Added a button on the (newly renamed) People webview that opens a new People webview :)
![image](https://github.com/paranext/paranext-core/assets/104016682/9d6913d4-2638-4368-827d-c0071a3885f6)

2023-06-07 23:34 UTC, tjcouch-sil reviewed
Oops - this is supposed to be a draft PR. Sorry! Thanks for previewing and giving feedback :)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/225#-:-NXNCM2g-AZ1ZY9Z09_a:b-yhj0pd)* status: 0 of 25 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-08 00:00 UTC, irahopkinson commented
There is a **Convert to draft** link button top-right in the reviewers section of the side-bar - hard to spot though.





<!-- Sent from Reviewable.io -->

2023-06-08 05:08 UTC, irahopkinson requested changes
I've run out of time to look at everything today but I'll publish what I have so far. Do note there are some tests failing which is why the GitHub checks aren't happy yet.

> Reviewed 15 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/225#-:-NXOOPUWCIMU9btKJa4X:b-6mhsdt)* status: 15 of 25 files reviewed, 8 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/lib/hello-world/hello-world.ts` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/225#-NXNpqET3tZxiiqGwd89:-NXNpqET3tZxiiqGwd8A:b562vxq) ([raw file](https://github.com/paranext/paranext-core/blob/67e7809691db3b2ed9dc0963390f5bdd92ef7565/extensions/lib/hello-world/hello-world.ts#L43)):*
> ```XML
> const reactWebViewType = 'hello-world.react';
> 
> const reactWebViewProvider: IWebViewProvider = {
> ```

BTW this is the 3rd copy of this code. What about supplying a `webViewProviderFactory` function or is this likely to be different for other WebViews?
___
*[`extensions/lib/hello-world/hello-world.ts` line 93 at r1](https://reviewable.io/reviews/paranext/paranext-core/225#-NXNrdHlDOiHRSePhOM4:-NXNrdHlDOiHRSePhOM5:b-68ynia) ([raw file](https://github.com/paranext/paranext-core/blob/67e7809691db3b2ed9dc0963390f5bdd92ef7565/extensions/lib/hello-world/hello-world.ts#L93)):*
> ```XML
>   // anywhere; it just has to match `webViewType`. See `hello-someone.ts` for an example of keeping
>   // an existing webview that was specifically created by `hello-someone`.
>   papi.webViews.addWebView(htmlWebViewType, undefined, { existingId: '*' });
> ```

BTW how about making this the default `options` in `addWebView`, then this call (and the one below) would simplify nicely. A unique WebView is likely the default, right?



_Code quote:_
```XML
{ existingId: '*' }
```
___
*[`src/shared/data/web-view.model.ts` line 158 at r1](https://reviewable.io/reviews/paranext/paranext-core/225#-NXO2zdH-ZC34uMe8Ap_:-NXO2zdH-ZC34uMe8Apa:bsufqs2) ([raw file](https://github.com/paranext/paranext-core/blob/67e7809691db3b2ed9dc0963390f5bdd92ef7565/src/shared/data/web-view.model.ts#L158)):*
> ```XML
> export type AddWebViewOptions = {
>   /**
>    * If provided, requests from the web view provider an existing existing WebView with this id
> ```

This sentence needs some revising to clarify meaning.
___
*[`src/shared/models/web-view-provider.model.ts` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/225#-NXO5MI42bLfxLxVCkaO:-NXO5MI42bLfxLxVCkaP:b-o0780u) ([raw file](https://github.com/paranext/paranext-core/blob/67e7809691db3b2ed9dc0963390f5bdd92ef7565/src/shared/models/web-view-provider.model.ts#L22)):*
> ```XML
>   getWebView(
>     serializedWebView: WebViewDefinitionSerialized,
>     addWebViewOptions: AddWebViewOptions,
> ```

BTW it appears this argument is optional (at least in `hello-someone.ts` and `hello-world.ts`)?
___
*[`src/shared/models/web-view-provider.model.ts` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/225#-NXO96x24cPvgfJx4DQj:-NXO96x24cPvgfJx4DQk:behy0ba) ([raw file](https://github.com/paranext/paranext-core/blob/67e7809691db3b2ed9dc0963390f5bdd92ef7565/src/shared/models/web-view-provider.model.ts#L31)):*
> ```XML
>     CanHaveOnDidDispose<IWebViewProvider> {}
> 
> // What the papi returns on register. Basically a layer over DisposableNetworkObject
> ```

Err... how can it be called `DisposableWebViewProvider` when it omits `dispose`?
___
*[`src/shared/services/web-view-provider.service.ts` line 49 at r1](https://reviewable.io/reviews/paranext/paranext-core/225#-NXOETBf3UeqFUI0E5f-:-NXOETBf3UeqFUI0E5f0:bylm496) ([raw file](https://github.com/paranext/paranext-core/blob/67e7809691db3b2ed9dc0963390f5bdd92ef7565/src/shared/services/web-view-provider.service.ts#L49)):*
> ```XML
>  * it unless something else in the existing process is subscribed to it.
>  */
> function hasKnown(webViewType: string): boolean {
> ```

BTW I haven't figured out yet why you choose a standard function or an arrow function. Above you have 2 arrow functions - one tiny and one longer. Here it's also tiny but a function. What's the criteria you use for choosing between them?
___
*[`src/shared/services/web-view-provider.service.ts` line 78 at r1](https://reviewable.io/reviews/paranext/paranext-core/225#-NXOJiCZ5pczb4ycRDIC:-NXOJiCZ5pczb4ycRDID:bhj0rpt) ([raw file](https://github.com/paranext/paranext-core/blob/67e7809691db3b2ed9dc0963390f5bdd92ef7565/src/shared/services/web-view-provider.service.ts#L78)):*
> ```XML
> 
>   // Set up the WebView provider to be a network object so other processes can use it
>   const disposableWebViewProvider = (await networkObjectService.set(
> ```

BTW you don't need to us `as` here but instead:
```
  const disposableWebViewProvider: DisposableWebViewProvider = await networkObjectService.set(
    webViewProviderObjectId,
    webViewProvider,
  );
```
Perhaps this amounts to the same thing but is slightly cleaner without extra brackets.
___
*[`src/shared/services/web-view.service.ts` line 123 at r1](https://reviewable.io/reviews/paranext/paranext-core/225#-NXONXCoBKMm2_4UyLlF:-NXONXCoBKMm2_4UyLlG:b-aozxej) ([raw file](https://github.com/paranext/paranext-core/blob/67e7809691db3b2ed9dc0963390f5bdd92ef7565/src/shared/services/web-view.service.ts#L123)):*
> ```XML
>   const webViewDefinitionCloned: Omit<WebViewDefinition, 'content'> &
>     Partial<Pick<WebViewDefinition, 'content'>> &
>     Partial<Pick<WebViewDefinitionReact, 'styles'>> = { ...webViewDefinition };
> ```

BTW the spread opertator won't do a deep clone but I guess that's all you need here, right?


<!-- Sent from Reviewable.io -->

2023-06-09 04:35 UTC, irahopkinson reviewed
> Reviewed 10 of 25 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/225)* status: all files reviewed, 35 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/renderer/components/web-view.component.tsx` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSJqNE6lHKxHazFblq:-NXSJqNE6lHKxHazFblr:bvqpd9s) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/web-view.component.tsx#L57)):*
> ```XML
> }
> 
> export default function loadWebViewPanel(savedTabInfo: SavedTabInfo): TabInfo {
> ```

This is really loading a WebView tab. Panel has a different meaning in `rc-dock` so this could be confusing to use `panel` here. How about `loadWebViewTab`?

Same for `saveWebViewPanel` below.



_Code quote:_
```XML
loadWebViewPanel
```
___
*[`src/renderer/components/web-view.component.tsx` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSTvZ-6rexpitURA_l:-NXSTvZ-6rexpitURA_m:b5a0dr6) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/web-view.component.tsx#L57)):*
> ```XML
> }
> 
> export default function loadWebViewPanel(savedTabInfo: SavedTabInfo): TabInfo {
> ```

BTW I'm not sure if this should remain the default export. I don't have a strong opinion but my instinct is to remove the default now we have other valid exports and we load all 3 in the only place we import them. This is our next item to discuss for styles but this seems a clearer example than some of the other edge cases we need to discuss. Feel free to leave it as is if you feel differently.



_Code quote:_
```XML
default
```
___
*[`src/renderer/components/web-view.component.tsx` line 71 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSOJuPB97a3keb6ysK:-NXSOJuPB97a3keb6ysL:b-bfwiu0) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/web-view.component.tsx#L71)):*
> ```XML
>     // deserialize the web view. It will asynchronously go get the content and re-run this function
>     if (!data.content && data.content !== '')
>       (async () => {
> ```

The anonymous self-calling function seems a little funky here. How about a named async function that we pass in `data` to it but don't await when we call it here? E.g. `if (!data.content && data.content !== '') getWebViewContent(data);`
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 62 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSn2Y47_7UMPiN3KZE:-NXSn2Y47_7UMPiN3KZF:b65idn7) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.tsx#L62)):*
> ```XML
> 
> const tabLoaderMap = new Map<TabType, TabLoader>([
>   [TAB_TYPE_ABOUT, loadAboutPanel],
> ```

I think these should all be renamed `load<feature>Tab`.
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 76 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSp4qJ6R9ySH4lwG-5:-NXSp4qJ6R9ySH4lwG-6:b-55yqz9) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.tsx#L76)):*
> ```XML
> function loadSavedTabInfo(tabInfo: SavedTabInfo): TabInfo {
>   const tabLoader = tabLoaderMap.get(tabInfo.tabType);
>   if (!tabLoader) return createErrorTab(`No tab loader for tabType '${tabInfo.tabType}'`);
> ```

BTW this should be renamed to match the new pattern of `loadErrorTab`.
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 87 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSoP1d7kQBxtRkybFu:-NXSoP1d7kQBxtRkybFv:b-dbywwm) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.tsx#L87)):*
> ```XML
> }
> 
> type RCDockTabInfo = TabData & Omit<TabInfo, 'title'> & { tabInfoTitle: string };
> ```

BTW types should probably be grouped together at the top of the file after imports and before consts. It makes it easier to find and keep them organised and to refactor them into `.model.ts` files if they are needed elsewhere.
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 103 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSqLau0yOwZLLVVfPE:-NXSqLau0yOwZLLVVfPF:bhctao9) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.tsx#L103)):*
> ```XML
>   return {
>     ...tabInfo,
>     tabInfoTitle: tabInfo.title,
> ```

BTW would it be better to already have it saved this way inside `tabInfo` so there is no special case here for `title` and would also simplify things in the `saveTab` function?
___
*[`src/renderer/components/docking/paranext-dock-layout.component.test.ts` line 77 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSwmV09us-_ybnrCvo:-NXSwmV09us-_ybnrCvp:bazvrva) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.test.ts#L77)):*
> ```XML
> 
>       expect(() => loadTab(savedTabInfoNone)).toThrow();
>       expect(() => loadTab(savedTabInfoNoId)).toThrow();
> ```

These 2 added expects don't add anything to the tests other than more running time. Revert the changes other than the `as`. If you want to check that no `tabType` causes a throw then add a new `it` block and define an `id` so it gets through the first throw check that this `it` block tests.
___
*[`src/renderer/components/docking/paranext-dock-layout.component.test.ts` line 87 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXT-cXJ6N9uDS_Wc86c:-NXT-cXJ6N9uDS_Wc86d:b-g8uh1q) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.test.ts#L87)):*
> ```XML
>       const event: AddWebViewEvent = { webView: {} as WebViewProps, layout: { type: 'tab' } };
> 
>       expect(() => addWebViewToDock(event, dockLayout)).toThrow();
> ```

In my VSCode this line is complaining that "Expected 3 arguments, but got 2".
___
*[`src/renderer/components/docking/paranext-dock-layout.component.test.ts` line 95 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXT0CUf65qMOO04Ami9:-NXT0CUf65qMOO04AmiA:b-djsdfh) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.test.ts#L95)):*
> ```XML
>       const dockLayout = instance(mockDockLayout);
>       const event: AddWebViewEvent = {
>         webView: { id: 'myId', webViewType: 'test', content: '' },
> ```

`content` is not defined in `AddWebViewEvent` - you can probably just remove it.
___
*[`src/renderer/components/docking/paranext-dock-layout.component.test.ts` line 99 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXT-o-g6FbwvadhjmHU:-NXT-o-g6FbwvadhjmHV:b-g8uh1q) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.test.ts#L99)):*
> ```XML
>       };
> 
>       expect(() => addWebViewToDock(event, dockLayout)).toThrow();
> ```

In my VSCode this line is complaining that "Expected 3 arguments, but got 2".
___
*[`src/renderer/components/docking/paranext-dock-layout.component.test.ts` line 111 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXT02am7mes-u_HNGxo:-NXT02am7mes-u_HNGxp:b-djsdfh) ([raw file](https://github.com/paranext/paranext [...]

2023-06-12 23:27 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/225)* status: all files reviewed, 27 unresolved discussions (waiting on @irahopkinson)

___
*[`extensions/lib/hello-world/hello-world.ts` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/225#-NXNpqET3tZxiiqGwd89:-NXWjaDe7MJDNKdImbUu:bnfr81k) ([raw file](https://github.com/paranext/paranext-core/blob/67e7809691db3b2ed9dc0963390f5bdd92ef7565/extensions/lib/hello-world/hello-world.ts#L43)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW this is the 3rd copy of this code. What about supplying a `webViewProviderFactory` function or is this likely to be different for other WebViews?
</blockquote></details>

How the code is right now, I think it might be a bit valuable - we may get a few lines back. However, I think introducing state will almost certainly cause every one of these to be very different. As such, I think I'd like to leave it.
___
*[`extensions/lib/hello-world/hello-world.ts` line 93 at r1](https://reviewable.io/reviews/paranext/paranext-core/225#-NXNrdHlDOiHRSePhOM4:-NXWjluG9vOthcn0weDj:b-i5yenq) ([raw file](https://github.com/paranext/paranext-core/blob/67e7809691db3b2ed9dc0963390f5bdd92ef7565/extensions/lib/hello-world/hello-world.ts#L93)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW how about making this the default `options` in `addWebView`, then this call (and the one below) would simplify nicely. A unique WebView is likely the default, right?
</blockquote></details>

It makes most sense to me when thinking about how this function will be used in the future to leave the default to be creating a new one (among our current options). Most of the time, people aren't going to make an ever-existing webview that shows solely because their extension is running. Actually, I don't know when that would be something someone would want to do. I imagine that, most of the time, it would be something like someone goes to a menu and presses a button to open the Interlinear for a project for example. That would not just look for any existing interlinear but would rather look for a specific one tied to the project or open a new one. Since we don't have project-specific anything right now, I figure the best default is to leave it to create a new one.

If we made `{ existingId: '*' }` the default, that would mean that, unless someone specifies otherwise, running `addWebView` will always use *any* web view that is already showing if one is showing (whether it was created in this same context or another context). I don't imagine that would be super common. I mostly added it to make doing what we're doing now easier.
___
*[`src/renderer/components/web-view.component.tsx` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSJqNE6lHKxHazFblq:-NXWl2AX4cF74lKaXMPL:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/web-view.component.tsx#L57)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is really loading a WebView tab. Panel has a different meaning in `rc-dock` so this could be confusing to use `panel` here. How about `loadWebViewTab`?

Same for `saveWebViewPanel` below.
</blockquote></details>

Done.
___
*[`src/renderer/components/web-view.component.tsx` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSTvZ-6rexpitURA_l:-NXWl3Xy8-_HG63KSy53:b-3df9bt) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/web-view.component.tsx#L57)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I'm not sure if this should remain the default export. I don't have a strong opinion but my instinct is to remove the default now we have other valid exports and we load all 3 in the only place we import them. This is our next item to discuss for styles but this seems a clearer example than some of the other edge cases we need to discuss. Feel free to leave it as is if you feel differently.
</blockquote></details>

Good thought. I agree. Done. I will make the component itself the default since that's what the file is named.
___
*[`src/renderer/components/web-view.component.tsx` line 71 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSOJuPB97a3keb6ysK:-NXkW0ig0-YxU2umF6PU:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/web-view.component.tsx#L71)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

The anonymous self-calling function seems a little funky here. How about a named async function that we pass in `data` to it but don't await when we call it here? E.g. `if (!data.content && data.content !== '') getWebViewContent(data);`
</blockquote></details>

Done.
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 76 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSp4qJ6R9ySH4lwG-5:-NXkW6PE5YD4GuiOFd1R:b-hvfl54) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.tsx#L76)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW this should be renamed to match the new pattern of `loadErrorTab`.
</blockquote></details>

I disagree in this case. `createErrorTab` doesn't do the same thing as the others. It isn't loading anything; it's creating a new tab with a specific error message. Let me know your thoughts. Thanks!
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 87 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSoP1d7kQBxtRkybFu:-NXkWQEb7ZvtpOPFlxrm:bjhtt7x) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.tsx#L87)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW types should probably be grouped together at the top of the file after imports and before consts. It makes it easier to find and keep them organised and to refactor them into `.model.ts` files if they are needed elsewhere.
</blockquote></details>

Agreed. I just didn't get around to that yet. Thanks for pointing it out - helps me to remember! :)
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 103 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSqLau0yOwZLLVVfPE:-NXkk3o07HG9Aov7A13e:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.tsx#L103)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW would it be better to already have it saved this way inside `tabInfo` so there is no special case here for `title` and would also simplify things in the `saveTab` function?
</blockquote></details>

Done.
___
*[`src/renderer/components/docking/paranext-dock-layout.component.test.ts` line 77 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSwmV09us-_ybnrCvo:-NXkksq86QOWzBzr_xk8:b-dczr9d) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/docking/paranext-dock-layout.component.test.ts#L77)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

These 2 added expects don't add anything to the tests other than more running time. Revert the changes other than the `as`. If you want to check that no `tabType` causes a throw then add a  [...]

2023-06-13 01:03 UTC, irahopkinson submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks for all your hard work on this.

> Reviewed 18 of 18 files at r3, 9 of 9 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/225#-:-NXmGm_vBZ7gUg0zcw2g:b-ki56nc)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/renderer/components/web-view.component.tsx` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-core/225#-NXSTvZ-6rexpitURA_l:-NXm4CnJBkjoX4wPu8Ve:b-wotgqu) ([raw file](https://github.com/paranext/paranext-core/blob/fe9ec11c187af13a3c430e1e93e29e09bab4d049/src/renderer/components/web-view.component.tsx#L57)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Good thought. I agree. Done. I will make the component itself the default since that's what the file is named.
</blockquote></details>

Even better. Thanks for doing it for the other built-in tabs also.
___
*[`src/renderer/components/web-view.component.tsx` line 59 at r5](https://reviewable.io/reviews/paranext/paranext-core/225#-NXmEamx88fTTalmIl0c:-NXmEamx88fTTalmIl0d:bqocgwd) ([raw file](https://github.com/paranext/paranext-core/blob/2a4e79a957da9d4f2205c49e45c9c5360a35b0a0/src/renderer/components/web-view.component.tsx#L59)):*
> ```XML
> 
> /**
>  * Tell the web view service to deserialize the web view with the provided serialized definition
> ```

BTW use 'load' and 'save' rather than 'deserialize' and 'serialize' here?


<!-- Sent from Reviewable.io -->

2023-06-13 03:16 UTC, irahopkinson approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-06-13 03:16 UTC, merged