Added websocket communication between main and renderer, improved build process and dev experience
paranext/paranext-core pull request #24
Opened 2023-02-10 02:13 UTC by tjcouch-sil

- Added `NetworkService.ts` which handles high-level network stuff like requests
- Added `ConnectionService.ts` which manages the network connections at a high level (could probably be merged with `NetworkService.ts`
- Added `ClientNetworkConnector.ts` and `ServerNetworkConnector.ts` which handle the websocket implementation of connections. They conform to `INetworkConnector`, and they are returned from the same `NetworkConnectorFactory.ts` function based on which process you are in. Hopefully, these files are the only things that would change if we were to change ipc implementations (they actually started with electron ipc, then we switched to websocket ipc because electron ipc wasn't much faster and would make communication with other clients more complex than we want right now).
- Added `CommandService.ts` which handles commands and their registrations
- Added `papi.ts` which compiles all the things we want on the papi (right now, just has `CommandService.ts`. Maybe will put `PapiUtil.ts` on it too)
- Added some test electron ipc handlers
- Added some test commands
- Added network testing buttons to `App.tsx`
- Added useful hooks and `Util.ts` from POC
- Added path aliases for more uniform imports
- Fixed path aliases not working on main process in development (ERB issue)
- Fixed husky spamming the console horribly (ERB issue)
- Excluded main files from renderer bundle and renderer files from main bundle so you don't get node-exclusive code (like `ws` library) in browser which fails to webpack
- Added eslint/prettier formatting rules from the POC
- Gitignored vscode workspace files
- Bumped nvmrc
- Bumped electron and electron-builder versions
- Added `src/shared` to directories that electronmon watches
- Added helpful npm scripts
- Removed ERB example code
- Misc formatting of ERB files

2023-02-13 06:39 UTC, irahopkinson requested changes
Wow, you have been busy, thanks for all this good work.

I haven't gone through all the files yet, but thought I would send in what I have done so far.

We haven't done this together before so I'm not sure what level you want me to pitch the review at. It would be helpful to have you walk through your PR together. Could we do that tomorrow?

2023-02-13 06:39 UTC, irahopkinson commented on src/renderer/App.tsx
> +        <button
Remove this button. We no longer need it and it causes an error anyway.

2023-02-13 06:39 UTC, irahopkinson commented on tsconfig.json
> +      "@renderer/*": ["./renderer/*"],
nit: The above 3 seem redundant when you can just use `@renderer/util` for example. Consider removing them.

2023-02-13 06:39 UTC, irahopkinson commented on tsconfig.json
> +      "@mainServices/*": ["./main/services/*"]
nit: This seems redundant when you can just use `@main/sevices`. Consider removing it.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/Util.ts
> +export function newGuid(): string {
This doesn't appear to be used so it can be removed. If its still needed consider using https://www.npmjs.com/package/uuid which includes parsing and validation.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/Util.ts
> +export function isValidValue(val: unknown): val is NonNullable<unknown> {
This doesn't appear to be used so it can be removed.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/Util.ts
> +export function debounce<T extends (...args: unknown[]) => void>(
This doesn't appear to be used so it can be removed.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/Util.ts
> +export function groupBy<K, V>(
This doesn't appear to be used so it can be removed.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/Util.ts
> +export const htmlEncode = (str: string): string =>
This doesn't appear to be used so it can be removed.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/Util.ts
> +export const voidElements: string[] = [
This doesn't appear to be used so it can be removed.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/PapiUtil.ts
> +export type UnsubPromise<T = unknown> = {
This doesn't appear to be used and can be removed.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/PapiUtil.ts
> +export const aggregateUnsubscribers = (
This doesn't appear to be used and can be removed.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/PapiUtil.ts
> +  initialized: boolean,
nit: its clearer to prefix boolean names with `is` or `has`, eg `isInitialized`

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/PapiUtil.ts
> +        const unregistered = backupUnregisterFn
This is an unsafe logical coerce of `backupUnregisterFn`, better to declare what you are actually checking, eg `const unregistered = backupUnregisterFn != null`, this will check for _null_ and _undefined_.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/util/PapiUtil.ts
> +        const unregistered = backupUnregisterFn
nit: its clearer to prefix boolean names with `is` or `has`, eg `isUnregistered`

2023-02-13 06:39 UTC, irahopkinson commented on .eslintrc.js
> +    'no-console': 'off',
nit: I would argue that we want this on. General messages should go to the logger (not the console). Debugging can go to the console but should be removed before PR. If there is another exception we can disbale the rule for that line.

2023-02-13 06:39 UTC, irahopkinson commented on package.json
> +    "build:native-modules": "cd ./release/app && npm install",
Do we still need this?

2023-02-13 06:39 UTC, irahopkinson commented on package.json
>    "prettier": {
We don't need this and `.prettierrc`. Pick one and merge to the other.

2023-02-13 06:39 UTC, irahopkinson commented on package.json
> +    "start:main": "cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only -r tsconfig-paths/register .",
Do we still need this?

2023-02-13 06:39 UTC, irahopkinson commented on src/__tests__/App.test.tsx
> +    act(() => {
Pretty sure you don't need `act` here now that you are mocking other items.

2023-02-13 06:39 UTC, irahopkinson commented on src/renderer/hooks/usePrevious.ts
> +export default <T>(value: T) => {
This doesn't appear to be used anywhere and can be removed.

2023-02-13 06:39 UTC, irahopkinson commented on src/renderer/hooks/useStyle.ts
> +export default (promiseFactoryCallback: () => Promise<string | undefined>) => {
This doesn't appear to be used anywhere and can be removed.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +  connected = false;
These 2 properties form at least a tristate variable (possibly quadstate). I.e. they both can't actually be true but there is no interlock on that. Would it be better to have a single `connectionStatus` enum with states of _Connecting_, _Connected_, _Disconnecting_, _Disconnected_?

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/data/NetworkConnectorTypes.ts
> +  InitClient = 'initClient',
nit: I'm thinking these enum values should use something other than camelCase (that we use for vars etc), how about kebab-case?

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (!clientSocket)
Lets be more explicit about what we are checking, e.g. `if (clientSocket == null)` which will check both _null_ and _undefined_.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (!this.websocketServer)
Lets be more explicit about what we are checking, e.g. `if (this.websocketServer == null)` which will check both _null_ and _undefined_.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (!this.connected || !this.websocketServer)
Lets be more explicit about what we are checking, e.g. `if (!this.connected || this.websocketServer == null)` which will check both _null_ and _undefined_.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    // eslint-disable-next-line no-restricted-syntax
Do we have a good reason for why this rule is on in the first place. `for of` is very useful. Can we allow it but exclude other restricted syntax?

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (callbacks) callbacks.forEach((callback) => callback(data, clientId));
This can be simplified to `callbacks?.forEach((callback) => callback(data, clientId));`.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (!callbacks) return false; // Did not find any callbacks for the message type
Again use `if (callbacks == null) return false;`

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (!callbacks) {
Again use `if (callbacks == null) {`

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    console.log(`this:${this}, this.nextClientId: ${this.nextClientId}`);
Remove this if it is debug info. Otherwise use the electron logger.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    websocket.addEventListener('error', console.error);
How about using the electron logger?

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    const connectorInfo = { clientId };
Specify the type for type safety, e.g. `const connectorInfo: NetworkConnectorInfo = { clientId };`. We should probably add the lint rule to enforce this.

2023-02-13 06:39 UTC, irahopkinson commented on src/shared/data/InternalConnectionTypes.ts
> +  clientId: number;
I'm wondering if `clientId` should have its own non-primative type, e.g. `clientId: ClientId;`?

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    /* websocket.off('error', console.error);
Either remove this commented section or include a comment to explain why its being kept.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +  connect = async (
nit: this public method (and also part of the interface) is buried amongst private methods. It should probably live above all private messages (along with other interface implmenting methods). We should be able to find these at the top without having to scoll far to find them. We can add lint rules to enforce this. Thoughts?

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (this.connectPromise) return this.connectPromise;
Again check explicitly `if (this.connectPromise != null) return this.connectPromise;`

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    this.websocketServer = new WebSocketServer({ port: 8876 });
This magic port number should at least be `const` or `readonly` property. It probably really needs to be imported from a shared `constants.ts` file.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +      if (!liveRequest)
Again use  `if (liveRequest == null)`.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (!this.requestRouter)
Use a more explicit check.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +      if (!this.localRequestHandler)
Use a more explicit check.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (this.websocketServer) {
Use a more explicit check.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (this.unsubscribeHandleRequestMessage)
Use a more explicit check.

2023-02-13 06:39 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    if (!liveRequest)
Use a more explicit check.

2023-02-13 14:23 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +  connected = false;
Good idea! Updated in `INetworkConnector.ts`, `ServerNetworkConnector.ts`, `ClientNetworkConnector.ts`, and `ConnectionService.ts`

2023-02-13 14:25 UTC, tjcouch-sil commented on .eslintrc.js
> +    'no-console': 'off',
I agree that we should turn this on once we have logging :) do we have logging yet? Maybe we could make a card for logging and do that sometime soon? Would it be ok if we left this off till then?

2023-02-13 14:30 UTC, tjcouch-sil commented on package.json
> +    "build:native-modules": "cd ./release/app && npm install",
I suppose we don't need it right now, but I left it in because maybe we would need it sometime in the future. Tim calls me out on YAGNI, too :D I will take it out.

2023-02-13 14:31 UTC, tjcouch-sil commented on package.json
> +    "start:main": "cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only -r tsconfig-paths/register .",
Yep! This enables path aliases in the main process in development. Read more at https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3404#issuecomment-1422898254 :)

2023-02-13 14:56 UTC, tjcouch-sil commented on src/__tests__/App.test.tsx
> +    act(() => {
Removed!

2023-02-13 16:23 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +    if (!this.websocketServer)
It seems this is a debated practice in the JavaScript world. After Ira and I discussed, we decided to allow truthy/falsy checks like these in most cases. Please see the Code Style guide for more information: https://github.com/paranext/paranext/wiki/Code-Style-Guide

2023-02-13 16:45 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +    // eslint-disable-next-line no-restricted-syntax
We added a section in https://github.com/paranext/paranext/wiki/Code-Style-Guide discussing the situation.

2023-02-13 17:14 UTC, tjcouch-sil commented on package.json
>    "prettier": {
Merged! Thanks!

2023-02-13 17:17 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +    if (callbacks) callbacks.forEach((callback) => callback(data, clientId));
I got used to the C# version, where you can't do the in-line null check on the left side of an expression, but I can change it here :) thanks!

2023-02-13 17:22 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +    const connectorInfo = { clientId };
If `connectorInfo` leaves out required fields from `NetworkConnectorInfo`, it will show an error when using `connectorInfo` in a place where it should be `NetworkConnectorInfo` like as follows (I added `stuff: string` to `NetworkConnectorInfo` to demonstrate):
![image](https://user-images.githubusercontent.com/104016682/218527379-68d3d2a0-3758-408d-b0c5-c535d78449c9.png)

Because this works, I am a bit hesitant to set a rule that would require specifying type in all cases. Do you know which lint rule enforces this? It would be good to get into some details and figure out if we can enable it in a nuanced way so we don't always have to type stuff. I certainly am open to discussing arguments for always typing, though! And it does seem very reasonable to add the type here, so I will do that. Thanks for the catch!

2023-02-13 17:26 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +    /* websocket.off('error', console.error);
Oh, actually this code is supposed to be there. At first, I had all of these arrow functions as normal class functions that wouldn't automatically bind `this`. Then I realized I needed to bind the functions, so I did that and added `removeAllListeners`. But then I decided to change them to arrow functions and specify which ones to remove. I think specifying which ones to remove is my preference because that is the interface the built-in `WebSocket` class uses (it does not have `removeAllListeners`), and it's nice to be consistent. Definitely open to discussing. Going to push changes here but leave this comment in case you would like to discuss or push back on my changes. Thanks for the catch!

2023-02-13 17:27 UTC, irahopkinson commented on .eslintrc.js
> +    'no-console': 'off',
Yep, we have `electron-log` installed. So far its only used for the `AppUpdater` in `main.ts` and I think it only transports to file so far.

2023-02-13 18:22 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    const connectorInfo = { clientId };
I agree we don't want to require specifying types in all cases. Looks like we already have https://typescript-eslint.io/rules/no-inferrable-types/ on through `erb`. I couldn't find anything else more nuance. Should we add something to the https://github.com/paranext/paranext/wiki/Code-Style-Guide for when we should include type declarations?

2023-02-13 19:08 UTC, tjcouch-sil commented on .eslintrc.js
> +    'no-console': 'off',
Do you think we could create a card to make a logging service and adjust the `console.` calls as needed? Or do you think we ought to do this now with my changes? Seems like a separate topic in my mind.

2023-02-13 19:09 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +    const connectorInfo = { clientId };
https://github.com/paranext/paranext/wiki/Code-Style-Guide added. Seem like a good write-up? Or shall we adjust?

2023-02-13 19:10 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +  connect = async (
I wrote it in functionality order-ish, but it's probably a good idea to make a better ordering system. Added https://github.com/paranext/paranext/wiki/Code-Style-Guide very primitive. Please feel free to suggest changes or additions!

2023-02-13 19:11 UTC, irahopkinson commented on .eslintrc.js
> +    'no-console': 'off',
Yep, make a card. Thats why this was a `nit` - meant to be a non-blocking comment.

2023-02-13 19:14 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    const connectorInfo = { clientId };
Looks good.

2023-02-13 19:17 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +    console.log(`this:${this}, this.nextClientId: ${this.nextClientId}`);
Removed! Good catch :)

2023-02-13 19:19 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +    websocket.addEventListener('error', console.error);
Agreed! Added in #25

2023-02-13 19:20 UTC, tjcouch-sil commented on .eslintrc.js
> +    'no-console': 'off',
Aah gotcha. I misunderstood nit, then. I will update the description in the Code Review guide to note that sometimes nits are future actions to be taken! :) Thanks! #25

2023-02-13 19:25 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +  connect = async (
Hmm one thing I realize we don't have an order for is types/interfaces/classes that are local to one file (not exported). So like some internal type that is used only within one file like a component's props or something (not a great example since that could definitely be helpful to have outside the file as well, but that's just one example). I think it would be good in this case to keep it in the most natural order again because of execution order. Since those types/interfaces/classes are not hoisted, it would be good to have them higher (I know TypeScript does just fine with types/interfaces anywhere, but it seems nice to have parallelism between local variables and types and such). What do you think?

2023-02-13 19:28 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +    this.websocketServer = new WebSocketServer({ port: 8876 });
I figured it was very likely we would rewrite how this works fairly significantly at some point, so I didn't really think about a solution. But at least a temporary solution is better than none :) thanks for the idea! What do you think about a `const` in `NetworkConnectorTypes.ts` for now?

2023-02-13 19:42 UTC, tjcouch-sil commented on src/renderer/App.tsx
> +        <button
Actually, it exercises throwing an error in a requestHandler on a different process (the server throws an error inside its request handler when the client sends this message, and it receives an exception back). Seems like an important functionality to exercise. I will remove "Edge" from the button label. Is that all right for you?

2023-02-13 19:42 UTC, tjcouch-sil commented on src/renderer/hooks/usePrevious.ts
> +export default <T>(value: T) => {
Done

2023-02-13 19:43 UTC, tjcouch-sil commented on src/renderer/hooks/useStyle.ts
> +export default (promiseFactoryCallback: () => Promise<string | undefined>) => {
Done

2023-02-13 19:45 UTC, tjcouch-sil commented on src/shared/data/InternalConnectionTypes.ts
> +  clientId: number;
Are you thinking do this so we can have more information attached to the clientId in the future because the server might need to treat different connections differently? Seems reasonable, but what do you think about just having that kind of thing on `NetworkConnectorInfo`? Or are there other reasons to make ClientId its own non-primitive type?

2023-02-13 19:51 UTC, tjcouch-sil commented on src/shared/util/PapiUtil.ts
> +export type UnsubPromise<T = unknown> = {
One reason it might be valuable to leave this here is that this `PapiUtil.ts` seems likely to be exposed on PAPI soon. If we keep this and `aggregateUnsubscribers`, that would be nice for devs who see the `Async` type/method and want to use similar things to them but want it to be synchronous unsubscribing. As such, maybe this doesn't quite fall under YAGNI because it keeps the utilities for the synchronous and asynchronous unsubscribers the same. What do you think?

2023-02-13 19:51 UTC, tjcouch-sil commented on src/shared/util/PapiUtil.ts
> +export const aggregateUnsubscribers = (
See comment above

2023-02-13 19:52 UTC, tjcouch-sil commented on src/shared/util/PapiUtil.ts
> +  initialized: boolean,
Done here and on the member variables in `NetworkService` and `CommandService`

2023-02-13 19:54 UTC, tjcouch-sil commented on src/shared/data/NetworkConnectorTypes.ts
> +  InitClient = 'initClient',
Since we have already started doing this in the TypeScript and C#, it seems inertia is for camelCasing. Do you have thoughts on in what way changing to a different case could be valuable? I'm not sure I see yet why we would need to change, but I'm open to the idea!

2023-02-13 19:56 UTC, tjcouch-sil commented on src/shared/util/PapiUtil.ts
> +        const unregistered = backupUnregisterFn
Good call :) done

2023-02-13 19:59 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +  connect = async (
For class ordering we can use https://typescript-eslint.io/rules/member-ordering/ - the default ordering may be sufficient. Last time I looked at this it didn't include getters and setters (we had to do this manually) so I'm happy to see this now is included.

For module ordering I think currently it doesn't even allow 'use' before 'declare' which TS can totally cope with. I prefer exports at the top - not sure why that messes up execution order since exports aren't normally executed?

2023-02-13 20:02 UTC, tjcouch-sil commented on src/shared/util/PapiUtil.ts
> +        const unregistered = backupUnregisterFn
Added a code style section https://github.com/paranext/paranext/wiki/Code-Style-Guide

2023-02-13 20:08 UTC, tjcouch-sil commented on src/shared/util/Util.ts
> +export function newGuid(): string {
I will remove this for now, but I plan to use guids shortly in `scaffold-code-extension-host`. I would argue that, at least for now, our purposes do not require a complex guid library. This solution is very small and fulfils our minimal needs. Later, we could add in the library and use it here to preserve apis. Do you have a particular leaning toward `uuid` in the short term? Thanks!

2023-02-13 20:09 UTC, tjcouch-sil commented on src/shared/util/Util.ts
> +export function isValidValue(val: unknown): val is NonNullable<unknown> {
Done

2023-02-13 20:09 UTC, tjcouch-sil commented on src/shared/util/Util.ts
> +export function debounce<T extends (...args: unknown[]) => void>(
Done

2023-02-13 20:10 UTC, tjcouch-sil commented on src/shared/util/Util.ts
> +export function groupBy<K, V>(
Done

2023-02-13 20:12 UTC, tjcouch-sil commented on tsconfig.json
> +      "@renderer/*": ["./renderer/*"],
Removed

2023-02-13 20:13 UTC, tjcouch-sil commented on tsconfig.json
> +      "@mainServices/*": ["./main/services/*"]
Removed

2023-02-13 20:25 UTC, irahopkinson commented on src/renderer/App.tsx
> +        <button
Yep.

2023-02-13 20:28 UTC, irahopkinson commented on src/shared/util/Util.ts
> +export function newGuid(): string {
No. We can move to the uuid lib if we need it. If you are going to use `newGuid` in your next PR then just leave it in here. Justification of immediate intended use is good enough.

2023-02-13 20:28 UTC, irahopkinson commented on src/shared/util/PapiUtil.ts
> +export type UnsubPromise<T = unknown> = {
Yep, sounds good.

2023-02-13 20:29 UTC, irahopkinson commented on src/shared/util/PapiUtil.ts
> +export const aggregateUnsubscribers = (
Yep, keep it.

2023-02-13 20:38 UTC, irahopkinson commented on src/shared/data/NetworkConnectorTypes.ts
> +  InitClient = 'initClient',
Only that it would more readily distinguish data from var names. In a similar way we use CAPS_SNAKE_CASE for consts, etc. Changing it now is easy but not so easy when its persisted in data. This is also a `nit` so your choice.

2023-02-13 20:39 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +  connect = async (
Created a new card #26 to deal with this in the future. For module ordering, I am particularly concerned about stuff like we see in `CommandService` where I had to make `registerCommandUnsafe` to use in `initialize` and `registerCommand` to use after `initialize` because trying to use `registerCommand` in `initialize` gave this rule error https://typescript-eslint.io/rules/no-use-before-define/

2023-02-13 20:45 UTC, tjcouch-sil commented on src/shared/util/Util.ts
> +export function newGuid(): string {
Put back in. Thank you for your thoughts!

2023-02-13 20:46 UTC, irahopkinson commented on src/shared/data/InternalConnectionTypes.ts
> +  clientId: number;
I was thinking for type safety to distinguish from any other var that is also a number but not actually a valid `clientId`. So `NetworkConnectorInfo` has a `ClientId` and `InternalRequest` has it also for `senderId` and `requestId` since one can be assigned and compared with the others (but not some other random `number` var). I'm not sure if this just makes life harder without much benefit but it seemed like a good idea at the time I wrote the comment.

2023-02-13 20:46 UTC, tjcouch-sil commented on src/shared/data/NetworkConnectorTypes.ts
> +  InitClient = 'initClient',
Changed. Thanks!

2023-02-13 20:47 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +    /* websocket.off('error', console.error);
Ok, the changes are in. Please resolve or let me know your thoughts. Thanks!

2023-02-13 20:49 UTC, tjcouch-sil commented on src/shared/data/NetworkConnectorTypes.ts
> +  InitClient = 'initClient',
Changed. Thanks!

2023-02-13 20:52 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +    this.websocketServer = new WebSocketServer({ port: 8876 });
Yep, its going to much easier to move later if we need to.

2023-02-13 20:58 UTC, tjcouch-sil commented on src/shared/data/InternalConnectionTypes.ts
> +  clientId: number;
Gotcha! I think that may be worth considering further at some point. However, it seems we don't gain a lot from it at the moment, and it's an implementation detail (except to executables that want to get in on the PAPI) for now. I lean toward leaving it out for now if that's all right...

2023-02-13 22:32 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +  connect = async (
We finished our discussion and added module style info to https://github.com/paranext/paranext/wiki/Code-Style-Guide

2023-02-13 22:38 UTC, tjcouch-sil commented on src/shared/data/InternalConnectionTypes.ts
> +  clientId: number;
We discussed and decided we will skip for now because it may involve freezing ClientId objects and added complexity that is not necessary at this time.

2023-02-14 00:21 UTC, irahopkinson requested changes
Ok, finished going through all the files now. It was good to work through issues form the first half of the review with you, thanks for that.

Just some similar issues plus potentially using a different `await/catch` pattern.

2023-02-14 00:21 UTC, irahopkinson commented on src/renderer/services/ClientNetworkConnector.ts
> +    if (callbacks) callbacks.forEach((callback) => callback(data));
Can simplify to `callbacks?.forEach((callback) => callback(data));`

2023-02-14 00:21 UTC, irahopkinson commented on src/renderer/services/ClientNetworkConnector.ts
> +    incoming: boolean,
style: use `isIncoming`

2023-02-14 00:21 UTC, irahopkinson commented on src/shared/services/CommandService.ts
> +/* const commandUnsubscribers = new Map<string, Unsubscriber>(); */
Why is this commented, will it be used soon? If not, remove it.

2023-02-14 00:21 UTC, irahopkinson commented on src/shared/services/CommandService.ts
> +/* const registerCommandsUnsafe = (
Why is this commented, will it be used soon? If not, remove it.

2023-02-14 00:21 UTC, irahopkinson commented on src/shared/services/CommandService.ts
> +/* const sendEpmRequest = async <TParam extends Array<unknown>, TReturn>(
Why is this commented, will it be used soon? If not, remove it.

2023-02-14 00:21 UTC, irahopkinson commented on src/shared/services/CommandService.ts
> +/* const registerCommands = async (...commands: CommandRegistration[]) => {
Why is this commented, will it be used soon? If not, remove it.

2023-02-14 00:21 UTC, irahopkinson commented on src/shared/services/CommandService.ts
> +/* const unregisterCommands = async (...commands: string[]) => {
Why is this commented, will it be used soon? If not, remove it.

2023-02-14 00:21 UTC, irahopkinson commented on src/shared/services/CommandService.ts
> +/* export const unregisterCommand = async (commandName: string) => {
Why is this commented, will it be used soon? If not, remove it.

2023-02-14 00:21 UTC, irahopkinson commented on src/shared/services/ConnectionService.ts
> +  NetworkConnectorFactory.createNetworkConnector()
I wonder if the `const nC = await NetworkConnectorFactory.createNetworkConnector().catch(...);` pattern would be cleaner here? Is that familiar to you? This would give a more straightforward flow to the code without extra indenting.

2023-02-14 00:21 UTC, irahopkinson commented on src/shared/services/NetworkService.ts
> +/* const requestRaw = async <TParam, TReturn>(
Why is this commented, will this be used soon? If not, remove it.

2023-02-14 14:09 UTC, tjcouch-sil commented on src/renderer/services/ClientNetworkConnector.ts
> +    if (callbacks) callbacks.forEach((callback) => callback(data));
Done

2023-02-14 14:10 UTC, tjcouch-sil commented on src/renderer/services/ClientNetworkConnector.ts
> +    incoming: boolean,
Done

2023-02-14 14:11 UTC, tjcouch-sil commented on src/shared/services/CommandService.ts
> +/* const commandUnsubscribers = new Map<string, Unsubscriber>(); */
Nope - just forgot to clean out the old implementations from the POC. Removed

2023-02-14 14:11 UTC, tjcouch-sil commented on src/shared/services/CommandService.ts
> +/* const registerCommandsUnsafe = (
Removed

2023-02-14 14:12 UTC, tjcouch-sil commented on src/shared/services/CommandService.ts
> +/* const sendEpmRequest = async <TParam extends Array<unknown>, TReturn>(
Removed

2023-02-14 14:12 UTC, tjcouch-sil commented on src/shared/services/CommandService.ts
> +/* const registerCommands = async (...commands: CommandRegistration[]) => {
Removed

2023-02-14 14:12 UTC, tjcouch-sil commented on src/shared/services/CommandService.ts
> +/* const unregisterCommands = async (...commands: string[]) => {
Removed

2023-02-14 14:12 UTC, tjcouch-sil commented on src/shared/services/CommandService.ts
> +/* export const unregisterCommand = async (commandName: string) => {
Removed

2023-02-14 14:15 UTC, tjcouch-sil commented on src/shared/services/NetworkService.ts
> +/* const requestRaw = async <TParam, TReturn>(
Removed

2023-02-14 14:49 UTC, tjcouch-sil commented on src/shared/services/ConnectionService.ts
> +  NetworkConnectorFactory.createNetworkConnector()
I refactored the code to use async/await and try/catch. Let me know if you have any comments! For some reason, when I was writing this code, I didn't think about that I could still use async with creating a promise to manually resolve later. But then I did it in another place later. 🤷 Thanks!

2023-02-14 15:40 UTC, irahopkinson commented on src/shared/services/ConnectionService.ts
> +  NetworkConnectorFactory.createNetworkConnector()
That wasn't the pattern I was indicating but is close enough and much improved readability. The pattern I showed above would acheive the same thing but without the `try` so is even cleaner for a single call like this.

2023-02-14 15:48 UTC, irahopkinson submitted a review, later dismissed
👍 LGTM, thanks for this.

2023-02-14 17:48 UTC, irahopkinson approved these changes
LGTM, good suggestion from Tim.

2023-02-14 19:26 UTC, merged