Added Scripture reference selection control to the main toolbar
paranext/paranext-core pull request #266
Opened 2023-06-26 19:22 UTC by tombogle

2023-06-26 19:23 UTC, tombogle commented
(For now), should the reference selector appear on the toolbar a) unconditionally, b) conditionally, or c) by means of "children"?

2023-06-26 23:26 UTC, tjcouch-sil commented
> (For now), should the reference selector appear on the toolbar a) unconditionally, b) conditionally, or c) by means of "children"?

My first thought is by 'children' so we can use the toolbar in the top bar with the ScrRef and use it without in the window bars. But that's just a first thought without really considering much how it would impact the code.

2023-07-27 17:38 UTC, tombogle commented on lib/papi-components/src/toolbar.component.tsx
> +                  width: '80%',
I think what we *really* want here is a way to auto-size this so that the columns fit. I couldn't figure out how to do that, since the columns are arranged with "flex" and they don't seem to care about running out of horizontal space and breaking into a second row. Maybe flex layout is the wrong thing.

2023-07-27 17:38 UTC, tombogle commented on src/renderer/components/platform-bible-toolbar.tsx
> +  // eslint-disable-next-line no-console
Once this is working correctly, I think we can just remove this console.log. I had put it in to try to figure out where the reference was getting lost.

2023-08-03 16:37 UTC, tjcouch-sil requested changes
Thanks for the hard work on this!! Looking forward to having it in.

> Reviewed 9 of 24 files at r2, 1 of 9 files at r4, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266#-:-NawFc_G4wmhnIWSCgyu:b-xzi9hn)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @jolierabideau and @tombogle)

___
*[`lib/papi-components/src/toolbar.component.tsx` line 106 at r3](https://reviewable.io/reviews/paranext/paranext-core/266#gh-1276612799:-NawEcsU8fqGpZRJQplI:b-hxj67n) ([raw file](https://github.com/paranext/paranext-core/blob/886b439fe2cfd71fe218bc7b92d09e26cdf46403/lib/papi-components/src/toolbar.component.tsx#L106)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I think what we *really* want here is a way to auto-size this so that the columns fit. I couldn't figure out how to do that, since the columns are arranged with "flex" and they don't seem to care about running out of horizontal space and breaking into a second row. Maybe flex layout is the wrong thing.
</blockquote></details>

Maybe we can pair on this together sometime. We generally want to avoid adding `style` in React [as advised by the React team](https://react.dev/reference/react-dom/components/common#applying-css-styles:~:text=We%20recommend%20only%20using%20the%20style%20attribute%20when%20your%20styles%20depend%20on%20JavaScript%20variables.)
___
*[`src/renderer/components/platform-bible-menu.commands.tsx` line 31 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-NawE9gAECYoL6HdjpAD:-NawE9gAECYoL6HdjpAE:bsn0jyx) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/components/platform-bible-menu.commands.tsx#L31)):*
> ```XML
>       break;
>     case 'platform.restartExtensionHost':
>       commandService.sendCommand(command.command);
> ```

We should probably change this to the default. Then we can get rid of the current default and `platform.quit`


<!-- Sent from Reviewable.io -->

2023-08-03 18:27 UTC, jolierabideau requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266)* status: 0 of 24 files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil and @tombogle)

___
*[`lib/papi-components/src/toolbar.component.tsx` line 106 at r3](https://reviewable.io/reviews/paranext/paranext-core/266#gh-1276612799:-Nawc-d87yN4US-CPy_K:b-cmd2dz) ([raw file](https://github.com/paranext/paranext-core/blob/886b439fe2cfd71fe218bc7b92d09e26cdf46403/lib/papi-components/src/toolbar.component.tsx#L106)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Maybe we can pair on this together sometime. We generally want to avoid adding `style` in React [as advised by the React team](https://react.dev/reference/react-dom/components/common#applying-css-styles:~:text=We%20recommend%20only%20using%20the%20style%20attribute%20when%20your%20styles%20depend%20on%20JavaScript%20variables.)
</blockquote></details>

Pairing might be helpful, I have not been able to figure out how to use css to style the paper element of the drawer. Is using `style` acceptable if we need to pass the toolbar height, or should that be done differently as well?
___
*[`src/renderer/components/platform-bible-menu.commands.tsx` line 31 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-NawE9gAECYoL6HdjpAD:-NawcuXs3zgynXdChLNB:bh9d6cs) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/components/platform-bible-menu.commands.tsx#L31)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We should probably change this to the default. Then we can get rid of the current default and `platform.quit`
</blockquote></details>

Working
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 13 at r3](https://reviewable.io/reviews/paranext/paranext-core/266#gh-1276614290:-Nawd1n644j6s8ENJa7l:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/886b439fe2cfd71fe218bc7b92d09e26cdf46403/src/renderer/components/platform-bible-toolbar.tsx#L13)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Once this is working correctly, I think we can just remove this console.log. I had put it in to try to figure out where the reference was getting lost.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-03 19:07 UTC, irahopkinson commented
*[`lib/papi-components/src/toolbar.component.tsx` line 106 at r3](https://reviewable.io/reviews/paranext/paranext-core/266#gh-1276612799:-NawmTPhCoN3pk08x67o:b-lm0a9m) ([raw file](https://github.com/paranext/paranext-core/blob/886b439fe2cfd71fe218bc7b92d09e26cdf46403/lib/papi-components/src/toolbar.component.tsx#L106)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Pairing might be helpful, I have not been able to figure out how to use css to style the paper element of the drawer. Is using `style` acceptable if we need to pass the toolbar height, or should that be done differently as well?
</blockquote></details>

BTW there is a fix on the `main` branch for the column height to auto-size that you could grab (sorry I only did that for the actual menu and didn't think about its story).


<!-- Sent from Reviewable.io -->

2023-08-03 20:57 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266)* status: 0 of 24 files reviewed, 2 unresolved discussions (waiting on @irahopkinson, @tjcouch-sil, and @tombogle)

___
*[`lib/papi-components/src/toolbar.component.tsx` line 106 at r3](https://reviewable.io/reviews/paranext/paranext-core/266#gh-1276612799:-Nax9M9CE1VQAOhfi7Gq:b-aj5784) ([raw file](https://github.com/paranext/paranext-core/blob/886b439fe2cfd71fe218bc7b92d09e26cdf46403/lib/papi-components/src/toolbar.component.tsx#L106)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW there is a fix on the `main` branch for the column height to auto-size that you could grab (sorry I only did that for the actual menu and didn't think about its story).
</blockquote></details>

The `height: 'fit-content'` in line 130 is auto-sizing the column height of the menu. Is that the fix you are referring to from [this commit](https://github.com/paranext/paranext-core/commit/1e745305767f02160b131f4b521153e4b9746d60)?


<!-- Sent from Reviewable.io -->

2023-08-03 22:23 UTC, irahopkinson commented
*[`lib/papi-components/src/toolbar.component.tsx` line 106 at r3](https://reviewable.io/reviews/paranext/paranext-core/266#gh-1276612799:-NaxU6GXD__2Yyzg8-he:b-olnixv) ([raw file](https://github.com/paranext/paranext-core/blob/886b439fe2cfd71fe218bc7b92d09e26cdf46403/lib/papi-components/src/toolbar.component.tsx#L106)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

The `height: 'fit-content'` in line 130 is auto-sizing the column height of the menu. Is that the fix you are referring to from [this commit](https://github.com/paranext/paranext-core/commit/1e745305767f02160b131f4b521153e4b9746d60)?
</blockquote></details>

Yes (although in that commit it's not on L130 ).


<!-- Sent from Reviewable.io -->

2023-08-04 15:04 UTC, rolfheij-sil requested changes
Cool stuff. Great work.

> Reviewed 9 of 24 files at r2, 1 of 9 files at r4, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266#-:-Nb040M97ZFMW-vGAb2U:brvfuty)* status: 0 of 24 files reviewed, 12 unresolved discussions (waiting on @jolierabideau, @rolfheij-sil, @tjcouch-sil, and @tombogle)

___
*[`lib/papi-components/src/index.ts` line 13 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-ygZR4QC5Z9vMF8OS:-Nb-ygZR4QC5Z9vMF8OT:b-9fmyl7) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/index.ts#L13)):*
> ```XML
> export { default as MenuItem } from './menu-item.component';
> export { default as Table } from './table.component';
> export type { MenuColumn, GridMenuProps } from './grid-menu.component';
> ```

Should the items in this files be ordered alphabetically? Right now these items are inserted in between the Table component and the Table types, which doesn't seem right
___
*[`lib/papi-components/src/menu-item.component.tsx` line 4 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-nUH352yLjvirjAuE:-Nb-nUH352yLjvirjAuF:b83ei65) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/menu-item.component.tsx#L4)):*
> ```XML
> import './menu-item.component.css';
> import { PropsWithChildren } from 'react';
> import { Command } from 'toolbar.component';
> ```

There's a circular dependecy here. `toolbar`includes `grid-menu` includes `menu-item` includes `toolbar`
I don't think that's a good idea
___
*[`lib/papi-components/src/toolbar.component.tsx` line 61 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-xPKL3Q_XwDVmFfT9:-Nb-xPKL3Q_XwDVmFfTA:bvkurjk) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/toolbar.component.tsx#L61)):*
> ```XML
>     if (isMenuOpen) setMenuOpen(false);
>     setHasShiftModifier(false);
>   }, [isMenuOpen, setMenuOpen]);
> ```

The setter never change right? So does it make sense to include it in this list of dependencies?
___
*[`lib/papi-components/src/toolbar.component.tsx` line 72 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-wNsb5-NUxg3Vb3EO:-Nb-wNsb5-NUxg3Vb3EP:blfmbs0) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/toolbar.component.tsx#L72)):*
> ```XML
>       });
>     },
>     [setMenuOpen, setHasShiftModifier],
> ```

These setters never change right? So does it make sense to include them in this list of dependencies?
___
*[`lib/papi-components/src/toolbar.component.tsx` line 76 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-wztoEr5MOdTi8JEo:-Nb-wztoEr5MOdTi8JEp:b-fq65yq) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/toolbar.component.tsx#L76)):*
> ```XML
> 
>   // This ref will always be defined
>   // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
> ```

This eslint instruction doesn't seem to be relevant here, right?
___
*[`lib/papi-components/src/toolbar.component.tsx` line 77 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-wwm5DCmOLA8osfgx:-Nb-wwm5DCmOLA8osfgy:bixq7ny) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/toolbar.component.tsx#L77)):*
> ```XML
>   // This ref will always be defined
>   // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>   const containerRef = useRef<HTMLDivElement>(null);
> ```

This refs seems to be the only one that is used. Can we delete the other two?
___
*[`src/renderer/app.component.tsx` line 18 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-XdQ24r5tUYR0JTAb:-Nb-XdQ24r5tUYR0JTAc:bc6k4wi) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/app.component.tsx#L18)):*
> ```XML
>   return (
>     <TestContext.Provider value="test">
>       <PlatformBibleToolbar referenceChanged={handleReferenceChanged} scrRef={scrRef} />
> ```

I guess you could inline this function?
`referenceChanged={(newScrRef) => {setScrRef(newScrRef);}}`
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 10 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-Zk_59HvMxnXpVaSb:-Nb-Zk_59HvMxnXpVaSc:b-ukq0le) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/components/platform-bible-toolbar.tsx#L10)):*
> ```XML
>   referenceChanged: (scrRef: ScriptureReference) => void;
> }) {
>   const { referenceChanged } = props;
> ```

This can be a single line, I think
`const { referenceChanged, scrRef } = props;`

Or you could use `props.scrRef` and `props.referenceChanged` below. That way you wouldn't even need this line.
I'm not sure what the preferred/recommended way is though, or if it's a matter of personal preference.
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 14 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb03Bel0PTixDLDTd51:-Nb03Bel0PTixDLDTd52:bknmzh) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/components/platform-bible-toolbar.tsx#L14)):*
> ```XML
> 
>   return (
>     <Toolbar className="toolbar" dataHandler={HandleMenuData} commandHandler={HandleMenuCommand}>
> ```

The HandleMenuData function expects 1 boolean argument, right? Shouldn't it be included here?
___
*[`src/stories/toolbar.stories.tsx` line 10 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-z-Ig-R_xocDGIIcd:-Nb-z-Ig-R_xocDGIIce:b1bj1sj) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/stories/toolbar.stories.tsx#L10)):*
> ```XML
>   tags: ['autodocs'],
>   argTypes: {
>     menu: { control: 'text' },
> ```

The `menu` prop expects an object, right? Not a string?


<!-- Sent from Reviewable.io -->

2023-08-04 17:11 UTC, jolierabideau commented
@irahopkinson For the `handleMenuClose` and `handleMenuButtonClick`, is there a specific reason why we include the setter as a dependency? Rolf pointed out that those shouldn't change, but wanted to ask since these were semi-recent changes you made. [Link to file in on main](https://github.com/paranext/paranext-core/blob/main/src/renderer/components/platform-bible-toolbar.tsx).

2023-08-04 17:12 UTC, jolierabideau requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266)* status: 0 of 24 files reviewed, 11 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`lib/papi-components/src/index.ts` line 13 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-ygZR4QC5Z9vMF8OS:-Nb0O8DK4h47JAIH5o0U:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/index.ts#L13)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Should the items in this files be ordered alphabetically? Right now these items are inserted in between the Table component and the Table types, which doesn't seem right
</blockquote></details>

Done
___
*[`lib/papi-components/src/menu-item.component.tsx` line 4 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-nUH352yLjvirjAuE:-Nb0MRbe2SPK4Fd6ZJtX:bb7rkpz) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/menu-item.component.tsx#L4)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

There's a circular dependecy here. `toolbar`includes `grid-menu` includes `menu-item` includes `toolbar`
I don't think that's a good idea
</blockquote></details>

Done  TJ and I just found and finished working on this!
___
*[`lib/papi-components/src/toolbar.component.tsx` line 61 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-xPKL3Q_XwDVmFfT9:-Nb0PDMt2x2uaz5M6Rp3:b-nux6ii) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/toolbar.component.tsx#L61)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

The setter never change right? So does it make sense to include it in this list of dependencies?
</blockquote></details>

Working  This change was made by Ira. I agree that they shouldn't change, and TS doesn't throw an error when I remove it from the dependency list.
___
*[`lib/papi-components/src/toolbar.component.tsx` line 72 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-wNsb5-NUxg3Vb3EO:-Nb0PeUL5LmGKTzEvZHv:b-nux6ii) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/toolbar.component.tsx#L72)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

These setters never change right? So does it make sense to include them in this list of dependencies?
</blockquote></details>

Working  This change was made by Ira. I agree that they shouldn't change, and TS doesn't throw an error when I remove it from the dependency list.
___
*[`lib/papi-components/src/toolbar.component.tsx` line 76 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-wztoEr5MOdTi8JEo:-Nb0NJEp3V-NqIY5yRJr:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/toolbar.component.tsx#L76)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

This eslint instruction doesn't seem to be relevant here, right?
</blockquote></details>

Done
___
*[`lib/papi-components/src/toolbar.component.tsx` line 77 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-wwm5DCmOLA8osfgx:-Nb0PlGK2eU574w_zf6f:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/toolbar.component.tsx#L77)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

This refs seems to be the only one that is used. Can we delete the other two?
</blockquote></details>

Done
___
*[`src/renderer/app.component.tsx` line 18 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-XdQ24r5tUYR0JTAb:-Nb0PpnJAicTp7aSzAzE:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/app.component.tsx#L18)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I guess you could inline this function?
`referenceChanged={(newScrRef) => {setScrRef(newScrRef);}}`
</blockquote></details>

Done
___
*[`src/renderer/components/platform-bible-menu.commands.tsx` line 31 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-NawE9gAECYoL6HdjpAD:-Nb0Ng7a-eGNoukiazA0:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/components/platform-bible-menu.commands.tsx#L31)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Working
</blockquote></details>

Done.
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 10 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-Zk_59HvMxnXpVaSb:-Nb0QXs5ARcFh-DYafcP:banjx40) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/components/platform-bible-toolbar.tsx#L10)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

This can be a single line, I think
`const { referenceChanged, scrRef } = props;`

Or you could use `props.scrRef` and `props.referenceChanged` below. That way you wouldn't even need this line.
I'm not sure what the preferred/recommended way is though, or if it's a matter of personal preference.
</blockquote></details>

Done  changed to the single line way you described. While talking with TJ we solved an error where TS wanted destructuring props in the component. So I think that way would be recommended.
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 14 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb03Bel0PTixDLDTd51:-Nb0SBGY34PqXNu8zpKu:b-2pcb98) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/components/platform-bible-toolbar.tsx#L14)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

The HandleMenuData function expects 1 boolean argument, right? Shouldn't it be included here?
</blockquote></details>

From what I can understand, we don't need to pass the arguments until we are using the function. Here I am just sending the function to the component. The `HandleMenuCommand` function also expects an argument and both work as expected.
___
*[`src/stories/toolbar.stories.tsx` line 10 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-z-Ig-R_xocDGIIcd:-Nb0SWi2-pu1Cs_oJPL3:bl0rlks) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/stories/toolbar.stories.tsx#L10)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

The `menu` prop expects an object, right? Not a string?
</blockquote></details>

Done  changed this to object, I am still working on getting the drawer to display correctly.


<!-- Sent from Reviewable.io -->

2023-08-04 17:23 UTC, tjcouch-sil requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266)* status: 0 of 25 files reviewed, 11 unresolved discussions (waiting on @jolierabideau, @rolfheij-sil, and @tombogle)

___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 14 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb0ZpENDi_jy07hYbPx:-Nb0ZpENDi_jy07hYbPy:bogk1m1) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/components/platform-bible-toolbar.tsx#L14)):*
> ```XML
> 
>   return (
>     <Toolbar className="toolbar" dataHandler={HandleMenuData} commandHandler={HandleMenuCommand}>
> ```

Please make normal function names (not React function components though) lowerCamelCase (lower-case first letter) :) thanks!


<!-- Sent from Reviewable.io -->

2023-08-04 17:42 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266)* status: 0 of 25 files reviewed, 11 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 14 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb0ZpENDi_jy07hYbPx:-Nb0bE3s1LabhOBPc_uD:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/src/renderer/components/platform-bible-toolbar.tsx#L14)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please make normal function names (not React function components though) lowerCamelCase (lower-case first letter) :) thanks!
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-07 04:28 UTC, irahopkinson reviewed
Strictly, Rolf is correct and they shouldn't change. However, I think I added them because the linter complained without them, and the linter doesn't know that they won't change. Given that they don't change means it doesn't hurt to include them since that would never trigger a change event. But if you remove them and the linter is happy,  go for it.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266#-:-NbDETJY0pDGIiDJDSHm:b-qecf54)* status: 0 of 25 files reviewed, 10 unresolved discussions (waiting on @jolierabideau, @rolfheij-sil, and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-08-07 08:59 UTC, rolfheij-sil requested changes
> Reviewed 7 of 14 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266)* status: 0 of 25 files reviewed, 4 unresolved discussions (waiting on @jolierabideau, @rolfheij-sil, @tjcouch-sil, and @tombogle)

___
*[`lib/papi-components/src/index.ts` line 13 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-ygZR4QC5Z9vMF8OS:-NbEBvxR8h9EZ5p9XYbp:b1jqtjk) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/index.ts#L13)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks! There's a small error: `default as Table` is now exported as a `type`, but it's a component.
This line should be restored: `export { default as Table } from './table.component';` 
And `default as Table` should be removed from the table types export
___
*[`lib/papi-components/src/menu-item.component.tsx` line 4 at r5](https://reviewable.io/reviews/paranext/paranext-core/266#-Nb-nUH352yLjvirjAuE:-NbECGbK6Bb47RuFGFxB:b-83sjoh) ([raw file](https://github.com/paranext/paranext-core/blob/e5c8ecb203e80ba4fadb41eb369489ced5d40bc2/lib/papi-components/src/menu-item.component.tsx#L4)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Done  TJ and I just found and finished working on this!
</blockquote></details>

Nice!


<!-- Sent from Reviewable.io -->

2023-08-07 13:42 UTC, rolfheij-sil approved these changes
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266)* status: 0 of 25 files reviewed, all discussions resolved (waiting on @jolierabideau, @rolfheij-sil, and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-08-07 17:38 UTC, jolierabideau approved these changes
> Reviewed 7 of 24 files at r2, 1 of 14 files at r5, 5 of 14 files at r6, 4 of 8 files at r7, 3 of 7 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-07 17:56 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/266#-:-NbG8D1ZBeAfROnl5-QZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-07 17:56 UTC, merged