Create C# client for handling requests for existing Paratext data. (#7, #16).
paranext/paranext-core pull request #28
Opened 2023-02-15 17:01 UTC by FoolRunning

Currently only a dummy request is registered (**addOne**), but it proves out the concepts.

2023-02-15 22:48 UTC, tjcouch-sil requested changes
Just a few things to discuss. Thanks for all the hard work! Looks great!

Also, does the code currently include the ability to make requests from the C# side? I suppose there's no guarantee this will need to happen, but I figure it probably will at some point (like needing to get the current scroll group or scripture reference or something, dunno). Think that's something to consider adding (making a card to do later is great)?

2023-02-15 22:48 UTC, tjcouch-sil commented on .vscode/launch.json
> +      "name": ".NET Core Attach",
Does this attach VSCode to an existing ParanextDataProvider.exe? If you use `.NET Core Launch`, does it handle breakpoints and such just fine without needing to do this one separately? Feel free to resolve if these things are the case. Just pondering a bit if we need these `attach` configurations like the `Electron: Renderer` one, but I suppose they could be helpful in some cases :)

2023-02-15 22:48 UTC, tjcouch-sil commented on .vscode/tasks.json
> +    "tasks": [
What is the difference between these tasks and the npm `build:data` scripts you added for dotnet commands? I see these tasks have a couple extra args - are they important in one context but not in the other? I think it might be to our benefit to use npm scripts to run these dotnet commands and then this `tasks.json` would just run those npm scripts instead of calling dotnet independently (actually, I think VSCode might automatically detect the `build` scripts and make tasks for them). That way, the build machines and anyone who wants to code on this repo without VSCode can run the exact same dotnet commands via npm scripts without having to replicate these args and such in other places. And then we have less upkeep when we want to change args for these commands.

2023-02-15 22:48 UTC, tjcouch-sil commented on c-sharp/Data/MessageConverter.cs
> +            throw new JsonException($"Unexpected token {reader.TokenType} (expected PropertyName)");
I think I may have read this wrong initially and am no longer so sure, but I just want to check as I have not done anything with .NET's json implementation before: does this indicate that ReadProperty requires the json to be in a specific order? Like in its use above in `Read`, does `messageType` have to be the first property in the object? If so, I imagine we should probably discuss that and options for how to address this special requirement as I don't believe JSON is naturally ordered.

2023-02-15 22:48 UTC, tjcouch-sil commented on c-sharp/Data/NetworkConnectorTypes.cs
> +    public NetworkConnectorInfo? ConnectorInfo { get; set; }
InitClient.connectorInfo is required on the TS side. Do we have a way to make this required here? Maybe in the default constructor it can be initialized to something similar to `CONNECTOR_INFO_DISCONNECTED`, which is in `InternalConnectionTypes.ts` and is used in `ClientNetworkConnector.ts`?

2023-02-15 22:48 UTC, tjcouch-sil commented on c-sharp/Utils/JsonUtils.cs
> +            IgnoreReadOnlyProperties = false, // Need message type to be serialized
After seeing this line, I read through `NetworkConnectorTypes.cs` and came up with  a couple of questions:
1. Are `const`s ignored or included? I see `NetworkConnectorInfo` has a `const` for the unset clientId. Wondering if that is accidentally copied.
2. I noticed that none of the `Type` properties are marked `readonly` or `const`. Are they considered to be `readonly` because they are properties whose `abstract` property only has `get`? They're also not static - are they instantiated on the object every time you create an object?

2023-02-15 22:48 UTC, tjcouch-sil commented on package.json
> +    "postinstall": "ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && npm run build:data && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config
I am beginning to think we may want to leave building the dotnet code out of postinstall since postinstall relates to installing node dependencies and won't affect how the dotnet code works. Originally, I thought it would be nice to simplify the steps to get started coding, but it seems it may add to the time it takes to install packages unnecessarily. What do you think about removing `npm run build:data` from the `postinstall` here and adding a step in the readme in getting started developing that says you must run `npm run build:data` after the step that says to run `npm install`?

2023-02-16 02:06 UTC, irahopkinson requested changes
This is looking good. I just have few minor questions.

2023-02-16 02:06 UTC, irahopkinson commented on .vscode/launch.json
> +      "program": "${workspaceFolder}/c-sharp/bin/Debug/net7.0/ParanextDataProvider.exe",
This will only work on Windows. Is that ok for now? We could just label it, e.g. `.NET Core Launch (Windows)`.

Same for **processName** below.

2023-02-16 02:06 UTC, irahopkinson commented on .vscode/tasks.json
> +            "label": "build",
We are likely to have a bunch of tasks. Perhaps we should namespace these as a dotnet/.NET build. Same for the other 2 below.

2023-02-16 02:06 UTC, irahopkinson commented on c-sharp/Web/PapiClient.cs
> +using System.Reflection.Metadata;
This looks like its unused, if so remove it.

2023-02-16 02:06 UTC, irahopkinson commented on c-sharp/Web/PapiClient.cs
> +    /// <param name="doStuff">Method that is called when the request is recieved from the server</param>
sp: received

2023-02-16 02:06 UTC, irahopkinson commented on c-sharp/Web/PapiClient.cs
> +            message.Write(buffer, 0, result .Count);
I'm not familair with this notation `result .Count`, i.e. with a space before the period. What does this do or is it meant to be `result.Count`?

2023-02-16 02:06 UTC, irahopkinson commented on c-sharp/Web/PapiClient.cs
> +            message.Write(buffer, 0, result .Count);
I asked ChatGPT, you can even do `result . Count`, i.e. a space before and after the period, and all three will do the same thing.

2023-02-16 03:01 UTC, irahopkinson commented on package.json
> +    "postinstall": "ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && npm run build:data && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config
Actually this currently takes almost no time (in case that helps in the choice).

2023-02-16 14:56 UTC, tjcouch-sil commented on .vscode/launch.json
> +      "program": "${workspaceFolder}/c-sharp/bin/Debug/net7.0/ParanextDataProvider.exe",
Maybe we could configure some dotnet command to run the ParanextDataProvider.exe? I don't really know how the "Play" button works in VS, but I feel like it probably works cross-platform. I wonder if we could figure out a way to configure the project so we could run the platform-specific build :)

2023-02-16 21:03 UTC, irahopkinson commented on .vscode/launch.json
> +      "program": "${workspaceFolder}/c-sharp/bin/Debug/net7.0/ParanextDataProvider.exe",
VSCode has [platform specific properties](https://code.visualstudio.com/docs/editor/debugging#_platformspecific-properties) to deal with this. Looks easy enough.

2023-02-22 16:09 UTC, FoolRunning commented on .vscode/launch.json
> +      "name": ".NET Core Attach",
They were both auto-generated when I added the project inside VSCode. I've never used the "attach" one, but I expect it would be useful when the C# client is automatically started instead of having to start it manually. When that functionality is added, we'll probably have to look at these configurations again.

2023-02-22 16:11 UTC, FoolRunning commented on .vscode/tasks.json
> +    "tasks": [
This file was auto-generated when I added the project in VSCode. I wasn't sure what it was for so I just left it. I would be happy to delete it.

2023-02-22 16:12 UTC, FoolRunning commented on .vscode/tasks.json
> +            "label": "build",
This file was auto-generated when I added the project in VSCode. I wasn't sure what it was for so I just left it. If there is a better way of doing things, I'm all for it.

2023-02-22 16:15 UTC, FoolRunning commented on c-sharp/Data/MessageConverter.cs
> +            throw new JsonException($"Unexpected token {reader.TokenType} (expected PropertyName)");
Yes, I'm fairly certain that the JsonReader reads things in order and it's not a robust solution - just how it seems to work in the example I found. I'll change this as it's not a good long-term solution.

2023-02-22 16:16 UTC, FoolRunning commented on c-sharp/Data/NetworkConnectorTypes.cs
> +    public NetworkConnectorInfo? ConnectorInfo { get; set; }
Makes sense. I'll make this not-nullable.

2023-02-22 16:25 UTC, FoolRunning commented on c-sharp/Utils/JsonUtils.cs
> +            IgnoreReadOnlyProperties = false, // Need message type to be serialized
1. Constants should be ignored - this property only affects properties.
2. Yes, they are read-only by the fact they do not have setters. They shouldn't be instantiated for each creation of an object. The code is the equivalent of 
``` c#
public Enum<MessageType> Type
{
    get { return MessageType.Request; }
}
```
so it's not allocating new memory for each instance or even each call since it's returning a readonly static field.

2023-02-22 16:26 UTC, FoolRunning commented on c-sharp/Web/PapiClient.cs
> +using System.Reflection.Metadata;
Done

2023-02-22 16:27 UTC, FoolRunning commented on c-sharp/Web/PapiClient.cs
> +            message.Write(buffer, 0, result .Count);
Whitespace is not significant to most of C# code - it's just a typo. Fixed.

2023-02-22 16:34 UTC, FoolRunning commented on package.json
> +    "postinstall": "ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && npm run build:data && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config
I know it looks like I added this, but it really was just changing the old scripts to use the new C# code. See [this change](https://github.com/paranext/paranext-core/commit/cf952b6d12f5ee6c31a003585cbc3dc6a2cfc5c3#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) where the scripts were removed - causing it to look like they were added here. I just replaced ``run build:edge`` with ``run build:data`` (i.e. edge -> data) in all scripts.

2023-02-22 17:11 UTC, FoolRunning commented on .vscode/launch.json
> +      "program": "${workspaceFolder}/c-sharp/bin/Debug/net7.0/ParanextDataProvider.exe",
Done

2023-02-22 18:14 UTC, FoolRunning commented on c-sharp/Web/PapiClient.cs
> +    /// <param name="doStuff">Method that is called when the request is recieved from the server</param>
Fixed

2023-02-22 18:38 UTC, FoolRunning commented on c-sharp/Data/MessageConverter.cs
> +            throw new JsonException($"Unexpected token {reader.TokenType} (expected PropertyName)");
I've changed it

2023-02-22 18:56 UTC, tjcouch-sil commented on .vscode/tasks.json
> +    "tasks": [
Ah gotcha! Yeah, I think it might be best to remove this file as VSCode should automatically detect our npm build scripts as tasks.

2023-02-22 18:56 UTC, tjcouch-sil commented on c-sharp/Data/MessageConverter.cs
> +    private static Enum<TReturn> ReadProperty<TReturn>(ref Utf8JsonReader reader) where TReturn : class, EnumType
Looks like this `ReadProperty` method specifically reads `type`, which made it hard for me to understand without reading the code. Do you think you could rename it and reword the comment describing it to clarify the purpose of the method?

2023-02-22 18:56 UTC, tjcouch-sil commented on c-sharp/Data/MessageConverter.cs
> +            throw new JsonException($"Unexpected token {reader.TokenType} (expected PropertyName)");
Great! Thanks!

2023-02-22 18:58 UTC, tjcouch-sil commented on c-sharp/Utils/JsonUtils.cs
> +            IgnoreReadOnlyProperties = false, // Need message type to be serialized
Ok perfect! Thank you!

2023-02-22 18:58 UTC, tjcouch-sil commented on c-sharp/Data/NetworkConnectorTypes.cs
> +    public NetworkConnectorInfo? ConnectorInfo { get; set; }
Looks great. Thank you!

2023-02-22 19:01 UTC, tjcouch-sil commented on package.json
> +    "postinstall": "ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && npm run build:data && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config
Right; didn't mean to indicate you added it. I was just processing through a thought I had since I put it in originally with the edge stuff. Since a lot of people probably won't be messing with the C# much, I imagine it might be best to take this out of `postinstall` and put it in the readme to run it instead. If we think it would be a positive change to make this not run every time you run `npm install` (which I think is the case), I can adjust it on this PR if you want...?

2023-02-22 19:09 UTC, FoolRunning commented on c-sharp/Data/MessageConverter.cs
> +    private static Enum<TReturn> ReadProperty<TReturn>(ref Utf8JsonReader reader) where TReturn : class, EnumType
Good catch. It was originally going to handle two different properties, but there only ended up being one that needed to be read and I guess I didn't completely change everything back correctly.

2023-02-22 19:11 UTC, FoolRunning commented on .vscode/tasks.json
> +    "tasks": [
Deleted.

2023-02-22 19:13 UTC, FoolRunning commented on package.json
> +    "postinstall": "ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && npm run build:data && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config
I'll just change it. I don't think it's that much to ask to run ``build:data`` explicitly.

2023-02-22 19:14 UTC, tjcouch-sil requested changes
Thanks for the great updates! Just a few things. Please let me know if you would like me to do the npm script stuff. I'll see what I can do if so!

2023-02-22 19:21 UTC, FoolRunning commented
@tjcouch-sil, I'm not sure what you mean by the "npm script stuff". I made the changes I think you meant in your comments. Maybe I misunderstood something.

2023-02-22 20:30 UTC, irahopkinson commented on .vscode/launch.json
> +      "program": "${workspaceFolder}/c-sharp/bin/Debug/net7.0/ParanextDataProvider.exe",
Please do the same for **processName** in **.NET Core Attach**.

2023-02-22 20:44 UTC, irahopkinson approved these changes
👍 LGTM, once TJ is happy.

2023-02-22 20:50 UTC, FoolRunning commented on .vscode/launch.json
> +      "program": "${workspaceFolder}/c-sharp/bin/Debug/net7.0/ParanextDataProvider.exe",
Done

2023-02-22 20:57 UTC, tjcouch-sil commented on c-sharp/Data/MessageConverter.cs
> +    private static Enum<TReturn> ReadProperty<TReturn>(ref Utf8JsonReader reader) where TReturn : class, EnumType
Great :) Thanks!

2023-02-22 21:40 UTC, tjcouch-sil approved these changes
Looks good! Created #35 .

2023-02-22 21:42 UTC, merged