Added extension host process that launches from main process
paranext/paranext-core pull request #29
Opened 2023-02-15 19:54 UTC by tjcouch-sil

- Added extension host process that launches from main process. Has some test command handlers
  - Watchers automatically restart it with `nodemon`
  - Extension host has its own webpack configuration and exports to its own js bundle
  - When launched through VS Code, breakpoints hit on both main and extension host
  - When launched outside of VS Code, extension host console logs and errors are logged with `{eh}` prefix and `{/eh}` postfix
- Added localStorage polyfill on the Node processes. Goes to `%appdata%/paranext-core`
- Added `src/client` folder for shared modules between the renderer and the extension host
- Added `src/node` folder for shared modules between main and extension host
- Added retrying websocket connection on clients
- Removed request registrations on client disconnect
- Split out WebSocket in `ClientNetworkConnector.ts` into `WebSocketFactory.ts` that loads browser WebSocket in renderer and `ws`'s WebSocket in Node (extension host)
- Various fixes

2023-03-07 04:09 UTC, irahopkinson requested changes
Thanks for all your good work on this. I've done a first pass over this to keep it moving forward.

2023-03-07 04:09 UTC, irahopkinson commented on .vscode/launch.json
> +      "autoAttachChildProcesses": true
I can't find in the [official VSCode docs](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes) what `autoAttachChildProcesses` does. A quick search indicates this _used_ to be an option. It can probably be removed since I don't think it does anything anymore. Here and below.

2023-03-07 04:09 UTC, irahopkinson commented on src/shared/services/NetworkService.ts
> +  console.log(
Use `logger`.

2023-03-07 04:09 UTC, irahopkinson commented on src/shared/services/CommandService.ts
> +          console.log(
Use `logger`.

2023-03-07 04:09 UTC, irahopkinson commented on src/renderer/App.tsx
> +            console.log(
Use `logger` and also 3 other places below.

2023-03-07 04:09 UTC, irahopkinson commented on src/node/util/util.ts
> +  return `${
Should probably use `path.join()` here so it uses the right forward or back slash for the OS.

2023-03-07 04:09 UTC, irahopkinson commented on src/client/services/ClientNetworkConnector.ts
> +          console.warn(
Use `logger`.

2023-03-07 04:09 UTC, irahopkinson commented on src/client/services/IWebSocket.ts
> +export type IWebSocket = WebSocket;
👍I like that you have shimmed this - good job.

2023-03-07 04:09 UTC, irahopkinson commented on src/extension-host/extension-host.ts
> +console.log('Hello from the extension host!');
Use `logger`. Replace 8 times in this file including in comments.

2023-03-07 04:09 UTC, irahopkinson commented on src/main/main.ts
> +console.log(localStorage.getItem('stuff'));
Use `logger`. Replace 6 times in this file.

2023-03-07 04:09 UTC, irahopkinson commented on src/client/services/WebSocketFactory.ts
> + * Creates a ServerNetworkConnector or a ClientNetworkConnector depending on if we're in main or renderer
This comment (and the one for `createWebSocket`) is either incorrect or the file should be moved to the `shared` folder. Given that `createWebSocket` is only called from `ClientNetworkConnector.ts` then its likely in the right place but both comments need updating.

2023-03-07 04:09 UTC, irahopkinson commented on src/main/main.ts
> +    return undefined;
What does this do for us?

2023-03-07 04:09 UTC, irahopkinson commented on src/main/main.ts
> +  return undefined;
Also not sure what this is doing for us here?

2023-03-07 04:09 UTC, irahopkinson commented on src/main/main.ts
> +// #region Extension Host
How about the contents of this section go in a `ExtensionHost.initialize` method defined elsewhere that can be called from here?

2023-03-07 04:09 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +type WebSocketClient = Omit<InitClient, 'type' | 'senderId'> & {
`Omit<InitClient, 'type' | 'senderId'> &` doesn't appear to add anything to the `WebSocketClient` type (at least according to VSCode). Is it still needed?

2023-03-07 04:09 UTC, irahopkinson commented on src/shared/services/NetworkConnectorFactory.ts
>  export const createNetworkConnector = async (): Promise<INetworkConnector> => {
This is only called from `ConnectionService.ts` which I undestand is client only. Why not import it normally and call it directly there rather than use this factory with dynamic imports?

2023-03-07 04:09 UTC, irahopkinson commented on src/main/main.ts
> +  ? fork(
Have you tested a production build?

2023-03-07 04:09 UTC, irahopkinson commented on src/extension-host/extension-host.ts
> +  .catch((e) => console.error(e));
This can be simplified to `.catch(logger.error);`.

2023-03-07 17:32 UTC, tjcouch-sil commented on .vscode/launch.json
> +      "autoAttachChildProcesses": true
Seems fine to remove it! Removed. I also tweaked a couple things to make hot reloading on the C# client work as well as making the VSCode .NET Core Launch work again as it was broken.

2023-03-07 17:41 UTC, tjcouch-sil commented on src/shared/services/NetworkService.ts
> +  console.log(
I changed all uses of `console` to `logger` and enabled the `no-console` rule. :)

2023-03-07 17:41 UTC, tjcouch-sil commented on src/shared/services/CommandService.ts
> +          console.log(
Done

2023-03-07 17:41 UTC, tjcouch-sil commented on src/renderer/App.tsx
> +            console.log(
Done

2023-03-07 17:47 UTC, tjcouch-sil commented on src/node/util/util.ts
> +  return `${
Good call. Done

2023-03-07 17:47 UTC, tjcouch-sil commented on src/client/services/ClientNetworkConnector.ts
> +          console.warn(
Done

2023-03-07 17:48 UTC, tjcouch-sil commented on src/client/services/IWebSocket.ts
> +export type IWebSocket = WebSocket;
Thanks!

2023-03-07 17:48 UTC, tjcouch-sil commented on src/extension-host/extension-host.ts
> +console.log('Hello from the extension host!');
Done

2023-03-07 17:50 UTC, tjcouch-sil commented on src/main/main.ts
> +console.log(localStorage.getItem('stuff'));
Done

2023-03-07 17:52 UTC, tjcouch-sil commented on src/client/services/WebSocketFactory.ts
> + * Creates a ServerNetworkConnector or a ClientNetworkConnector depending on if we're in main or renderer
Good catch. Done

2023-03-07 17:56 UTC, tjcouch-sil commented on src/main/main.ts
> +    return undefined;
There's a nice `promise/always-return` rule that enforces returning in all promise chains so you never get lost with an unresolved promise https://github.com/eslint-community/eslint-plugin-promise/blob/main/docs/rules/always-return.md I didn't used to do this, but it seems very reasonable to me. This way, no promise is ever not resolved or rejected. People can `.then` or `await` any existing promise without changing it. Without this rule, it might be harder to tell bugs from promises not resolving.

Feel free to offer your thoughts :)

2023-03-07 17:56 UTC, tjcouch-sil commented on src/main/main.ts
> +  return undefined;
See above

2023-03-07 17:58 UTC, tjcouch-sil commented on src/main/main.ts
> +// #region Extension Host
Oh no! I should have put that code into this PR, but I put it into [this one](https://github.com/paranext/paranext-core/blob/30-load-extensions/src/main/main.ts) not thinking about it. Is it ok if we wait and get it into that PR? That PR is just waiting on this PR, which is waiting on Tim's docking framework PR.

2023-03-07 18:00 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
> +type WebSocketClient = Omit<InitClient, 'type' | 'senderId'> & {
It should be adding `connectorInfo` and `clientGuid`, right?
https://github.com/paranext/paranext-core/blob/scaffold-core-extension-host/src/shared/data/NetworkConnectorTypes.ts#L33-L39

2023-03-07 18:06 UTC, tjcouch-sil commented on src/shared/services/NetworkConnectorFactory.ts
>  export const createNetworkConnector = async (): Promise<INetworkConnector> => {
`ConnectionService.ts` is used in both client and server. This `NetworkConnectorFactory` is the splitting point where the client gets different code than the server does. I have webpack rules set up so that the clients exclude code from the server, and the server excludes code from the client. That way, we don't have to bundle extra code, and we can avoid polyfills for a bunch of node stuff that we don't need to polyfill. I have also been considering using https://webpack.js.org/plugins/normal-module-replacement-plugin/ , but I'm not sure if that would work flexibly enough for our needs. Would need to reflect on it more. I created #63 for it.

2023-03-07 18:07 UTC, tjcouch-sil commented on src/extension-host/extension-host.ts
> +  .catch((e) => console.error(e));
Done

2023-03-07 18:07 UTC, tjcouch-sil commented on src/main/main.ts
> +  ? fork(
Yes. It works properly :)

2023-03-08 04:00 UTC, irahopkinson requested changes
I see you have auto-merge enabled. When I end up approving this PR it could merge before #43.

2023-03-08 04:00 UTC, irahopkinson commented on .vscode/launch.json
> +      "name": "Debug .NET Core",
Does this actually allow debugging? It looks like it just builds the executable.

2023-03-08 04:00 UTC, irahopkinson commented on .vscode/launch.json
> +        "program": "${workspaceFolder}/c-sharp/bin/Debug/net7.0/win-x64/ParanextDataProvider.exe"
If you had to change this for Windows then its likely Linux and MacOS need updating also.

2023-03-08 04:00 UTC, irahopkinson commented on src/main/main.ts
> +// #region Extension Host
Yep

2023-03-08 04:00 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
> +type WebSocketClient = Omit<InitClient, 'type' | 'senderId'> & {
Yes, sorry I must have been looking at the wrong thing yesterday. Now that I'm looking today the type has all four properties as expected.

2023-03-08 04:00 UTC, irahopkinson commented on src/shared/services/NetworkConnectorFactory.ts
>  export const createNetworkConnector = async (): Promise<INetworkConnector> => {
Ok

2023-03-08 04:00 UTC, irahopkinson commented on src/main/main.ts
> +logger.log(localStorage.getItem('stuff'));
Is this still needed? If its only confirming that localStorage is working then remove it.

2023-03-08 04:00 UTC, irahopkinson commented on src/main/main.ts
> +    return undefined;
The rule points to this [article](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html) at the top, which reminds me why we should use async/await rather than promises directly (`.then`). Since we are likely to still have the occasional use of `.then` then this rule should be on. Thanks for doing that.

2023-03-08 14:13 UTC, tjcouch-sil commented on src/main/main.ts
> +logger.log(localStorage.getItem('stuff'));
Good catch! Removed

2023-03-08 14:23 UTC, tjcouch-sil commented on .vscode/launch.json
> +        "program": "${workspaceFolder}/c-sharp/bin/Debug/net7.0/win-x64/ParanextDataProvider.exe"
Indeed. However, I do not know how to run or test them. I did some research and made some changes. I hope they work.

2023-03-08 14:24 UTC, tjcouch-sil commented on .vscode/launch.json
> +      "name": "Debug .NET Core",
Yep, it runs and allows debugging. I guess it's VSCode magic with the `coreclr` and `launch` things. I believe Tim autogenerated these commands when he added the C# client.

2023-03-08 21:55 UTC, irahopkinson approved these changes
👍 LGTM

2023-03-08 21:55 UTC, irahopkinson commented on .vscode/launch.json
> +        "program": "${workspaceFolder}/c-sharp/bin/Debug/net7.0/win-x64/ParanextDataProvider.exe"
LGTM

2023-03-08 22:20 UTC, merged