Run the dotnet Data Provider from electron
paranext/paranext-core pull request #36
Opened 2023-02-22 21:44 UTC by irahopkinson

- console messages are passed through to the electron console
- add GHA dotnet build
- also `npx update-browserslist-db@latest`
- note: in dev, close the app (before ctrl + c) so that the dotnet process is killed

2023-02-22 22:10 UTC, tjcouch-sil requested changes
Thanks for the hard work on this! I love the idea of splitting the code to run the dotnet project out into its own service. Just a few thoughts and questions for you :)

2023-02-22 22:10 UTC, tjcouch-sil commented on src/main/services/dotnet-data-provider.service.ts
> +  let command = 'dotnet';
Do you think it might be worth making an `npm run start:data` script that does this and running it in development? Like I'm running the extension host in development [here](https://github.com/paranext/paranext-core/blob/30-load-extensions/src/main/main.ts#L269). Or I could modify it in my PR - either way :)

2023-02-22 22:10 UTC, tjcouch-sil commented on src/main/main.ts
> +import dotnetDataProvider from './services/dotnet-data-provider.service';
Can we make this an aliased path like `@mail/services/...`? I suggest we recommend using aliased paths where possible in our code style guide so we have more uniform import statements for webpack magic's sake. What do you think?

2023-02-22 22:10 UTC, tjcouch-sil commented on package.json
> +    "build:data-release:windows": "dotnet publish c-sharp/ParanextDataProvider.csproj -p:PublishProfile=FolderProfile -r win-x64 -o ./c-sharp/bin/Release/net7.0/publish/win-x64/",
Oh I didn't notice before that we lost the [publish profile from the edge project](c-sharp/Properties/PublishProfiles/FolderProfile.pubxml). Think we can remove `-p:PublishProfile=FolderProfile` on all these `build:data` scripts since we no longer need it? Sorry to bother - I can take it out with my PR if you want!

2023-02-22 22:10 UTC, tjcouch-sil commented on src/main/main.ts
> +  dotnetDataProvider.start();
Since the C# provider isn't tied to any window in particular (theoretically maybe we could have multiple windows spawned from electron in the future, though I don't know that we should because that would tie us down to electron more), it may be best to start this outside of the context of creating a window. That way, we will start it with the main process and keep just the one while the main process is alive. We also don't have to wait for `app.whenReady` if we start this outside of the `createWindow` function :)

2023-02-22 22:10 UTC, FoolRunning requested changes

2023-02-22 22:10 UTC, FoolRunning commented on src/main/services/dotnet-data-provider.service.ts
> +    if (dotnet.kill()) {
Assuming this is a process kill - this is actually a very bad idea. Killing a process outright has the same problems as killing a thread. For example, the process might be in the middle of writing a file asynchronously. Ideally, the process should be closed cleanly by sending a close request via the PAPI and waiting for a while - only killing if the process seems to be hung.

It's possible we may want to just leave this as-is for now, but it's definitely not a good long-term solution.

2023-02-22 22:10 UTC, FoolRunning commented on src/main/services/dotnet-data-provider.service.ts
> +    if (dotnet.kill()) {
FWIW, the process should cleanly close if it gets a request to close the socket.

2023-02-22 23:37 UTC, irahopkinson commented on src/main/services/dotnet-data-provider.service.ts
> +  let command = 'dotnet';
Done.

2023-02-22 23:37 UTC, irahopkinson commented on src/main/main.ts
> +import dotnetDataProvider from './services/dotnet-data-provider.service';
Done.

2023-02-22 23:37 UTC, irahopkinson commented on package.json
> +    "build:data-release:windows": "dotnet publish c-sharp/ParanextDataProvider.csproj -p:PublishProfile=FolderProfile -r win-x64 -o ./c-sharp/bin/Release/net7.0/publish/win-x64/",
Done.

2023-02-22 23:38 UTC, irahopkinson commented on src/main/main.ts
> +  dotnetDataProvider.start();
The reason I did it this way was because at this stage we only have one window and I couldn't find a more reliable event. E.g. for event `before-quit` or `will-quit` it [notes that](https://www.electronjs.org/docs/latest/api/app#event-before-quit) "_on Windows, this event will not be emitted if the app is closed due to a shutdown/restart of the system or a user logout_". If you think that is acceptable I can move the calls outside the window system. Also I wasn't sure when the ws would be open so that .NET doesn't quit but I thought it would be up by the time we open a window. I expect we will move all this around as we go forward.

2023-02-22 23:38 UTC, irahopkinson commented on src/main/services/dotnet-data-provider.service.ts
> +    if (dotnet.kill()) {
I was expecting we would eventually have a better way of closing it down earlier in the quit process. This is meant to be the kill at the end if nothing else has done it cleanly. I've re-labelled it to make it clearer. I'm thinking that a clean shutdown is not really in scope for [Hello World for Electron C# Cross Platform](https://github.com/paranext/paranext-core/issues/8) which is mainly about the build, but I agree we need to do it.

@tjcouch-sil any thoughts on how we would close the ws from this service?

2023-02-22 23:47 UTC, tjcouch-sil commented on src/main/services/dotnet-data-provider.service.ts
> +  let command = 'dotnet';
Awesome! Thanks :)

2023-02-23 00:02 UTC, tjcouch-sil commented on src/main/main.ts
> +  dotnetDataProvider.start();
Not sure I understand the concern - is the dotnet process not shutting down when the electron process does? Does it automatically stop when you kill the node process? I believe the extension host process does (I just run `spawn` right in the `main.ts` code not in a function or anything), so I just assumed it would in this case... But I suppose I don't necessarily know that the extension host process does either... Hard to tell with node processes since a bunch of apps use node haha

Regarding start timing, I have been just adding timeouts where needed to make sure things initialize after one another properly. I think we will be able to fix this once we have the ability to fire and subscribe to events.

2023-02-23 00:06 UTC, tjcouch-sil commented on src/main/services/dotnet-data-provider.service.ts
> +    if (dotnet.kill()) {
I don't think there is a good way yet; we don't even have a system so the server knows what kind of connection each connection is, so I don't think we would be able to tell which socket is the C# socket. Maybe we don't need that, though; maybe we just need to close all the connections at once...? But then I suppose we might run into trouble if we close sockets and end the processes before they're all finished saving and such. Maybe we need to send requests to each connection telling it to wrap up its activities and shut itself down. I should probably reflect on this and add something at some point. Seems out of scope of this PR.

2023-02-23 00:09 UTC, tjcouch-sil commented on src/main/main.ts
> +import dotnetDataProvider from './services/dotnet-data-provider.service';
Great. Thank you! Added to the style guide

2023-02-23 00:31 UTC, irahopkinson commented on src/main/main.ts
> +  dotnetDataProvider.start();
At lunch I realized I could start it after the `NetworkService.initialize()` and that the `window-all-closed` event will catch all Windows (and Linux) quit events and the `will-quit` event will cover Linux and MacOS. I've made that change now.

Pretty sure if we start processes we will need to clean them up ourselves. Do you think they will shutdown when the electron process is shut?

2023-02-23 16:47 UTC, tjcouch-sil commented on src/main/main.ts
> +  dotnetDataProvider.start();
It appears that, [according to Node docs](https://nodejs.org/docs/latest-v18.x/api/child_process.html#optionsdetached), on Windows, the child processes close, but they may or may not with certainty on other platforms.

What if we just tell the child processes to close when our Node process closes? This is apparently a somewhat complex task, but we can probably use one of the following libraries:

https://www.npmjs.com/package/node-cleanup - very old but seemingly quite flexible/powerful. Seems like it may run async closing code on `process.exit()`, but it seems unclear
https://www.npmjs.com/package/exit-hook - newer, maintained library that has an asynchronous closing code api but does not successfully await async closing code when using `process.exit()`. It has a `gracefulExit()` function to use instead

It seems fine to make a card to do this.

2023-02-23 20:10 UTC, irahopkinson commented on src/main/main.ts
> +  dotnetDataProvider.start();
Yeah, go ahead an make an issue card.

2023-02-23 22:24 UTC, tjcouch-sil commented on src/main/main.ts
> +  dotnetDataProvider.start();
Created issue #37

2023-02-23 22:25 UTC, tjcouch-sil commented on src/main/services/dotnet-data-provider.service.ts
> +    if (dotnet.kill()) {
Created issue #37 . I recommend we deal with it at some point in the future unrelated to this PR.

2023-02-23 22:27 UTC, tjcouch-sil commented on src/main/main.ts
> +  dotnetDataProvider.start();
Could you update your PR description reflecting the changes please? Thank you for the hard work! Looks good! Please feel free to resolve this conversation when you make the update.

2023-02-27 15:25 UTC, FoolRunning approved these changes

2023-02-27 15:45 UTC, tjcouch-sil approved these changes

2023-02-27 15:45 UTC, merged