60 resource viewer v2
paranext/paranext-core pull request #380
Opened 2023-08-15 15:04 UTC by katherinejensen00

Here is the code for a super basic resource viewer using Tom Hindle's editor that he started. Note, the reference control will be hooked up to the resource viewer in another task and is just there for now as a reference ;).

2023-08-15 16:59 UTC, tjcouch-sil requested changes
Thanks for the hard work on this!! So close!

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/380#-:-Nbu7glLAnh7H6LPN1ss:boos4uy)* status: all files reviewed, 10 unresolved discussions (waiting on @katherinejensen00)

___
*[`.vscode/settings.json` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu3oD0BEsF6GAFWTfj:-Nbu3oD12Z0Ec1IzLp17:b2j6fvg) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/.vscode/settings.json#L66)):*
> ```JSON
>     }
>   ],
>   "cSpell.words": ["usfm"]
> ```

We already have a cspell configuration in `paranext-core/cspell.json` that is picking up usfm. Is yours not respecting this file? Do you have some overrides in your VSCode settings that prevent you from using this file?
___
*[`extensions/src/resource-viewer/resource-viewer.ts` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu5z19AJhJ-DbUe0Th:-Nbu5z19AJhJ-DbUe0Ti:b-d4ub1k) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/extensions/src/resource-viewer/resource-viewer.ts#L17)):*
> ```XML
> 
> const unsubscribers: UnsubscriberAsync[] = [];
> class ResourceDataProviderEngine
> ```

Is this used? Can you remove it?
___
*[`extensions/src/resource-viewer/resource-viewer.ts` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu62SU8bqg28exMsBU:-Nbu62SU8bqg28exMsBV:b-d4ub1k) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/extensions/src/resource-viewer/resource-viewer.ts#L130)):*
> ```XML
> 
>   const unsubPromises = [
>     papi.commands.registerCommand('resourceViewer.getUsfm', () => {
> ```

Is this used? Can you remove it?
___
*[`extensions/src/resource-viewer/resource-viewer.ts` line 141 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu64S709ywCesE9YeD:-Nbu64S8EV84yH9T-1GV:b-2pdnfo) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/extensions/src/resource-viewer/resource-viewer.ts#L141)):*
> ```XML
>   papi.webViews.getWebView(resourceWebViewType, undefined, { existingId: '?' });
> 
>   if (resourceDataProvider) {
> ```

This seems to be unnecessary test code - can we remove it?
___
*[`extensions/src/resource-viewer/resource-viewer.ts` line 161 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu5EDBEU-ZlQxAaSdB:-Nbu5EDBEU-ZlQxAaSdC:b-jcgu6e) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/extensions/src/resource-viewer/resource-viewer.ts#L161)):*
> ```XML
>   );
>   logger.info('The Resource Viewer is finished activating!');
>   return combinedUnsubscriber;
> ```

The way to register unsubscribers has changed. Please refer to https://discord.com/channels/1064938364597436416/1136698231250755664 for how to update :) thanks!
___
*[`extensions/src/resource-viewer/resource-viewer.d.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu6GYY4phJ9ixD0a7D:-Nbu6GYY4phJ9ixD0a7E:b-d4ub1k) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/extensions/src/resource-viewer/resource-viewer.d.ts#L7)):*
> ```XML
> 
> // TODO: Should this eventually be turned into ScrText or should it utilize ScrText?
> export type ResourceDataTypes = {
> ```

Is this used? Can you remove it?
___
*[`extensions/src/resource-viewer/resource-viewer.d.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu6Hku-w-ByP9msIgR:-Nbu6Hku-w-ByP9msIgS:b-d4ub1k) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/extensions/src/resource-viewer/resource-viewer.d.ts#L28)):*
> ```XML
>  *  number type is sneezeId and will update an existing sneeze
>  */
> export type ResourceDataProvider = IDataProvider<ResourceDataTypes>;
> ```

Is this used? Can you remove it?
___
*[`extensions/src/resource-viewer/resource-viewer.d.ts` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu6IeWB9c9nkMZSaXg:-Nbu6IeWB9c9nkMZSaXh:bf9rr8) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/extensions/src/resource-viewer/resource-viewer.d.ts#L31)):*
> ```XML
> 
> declare module 'papi-commands' {
>   export interface CommandHandlers {
> ```

Are these used? Can you remove them?
___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 122 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu6Mgx7HKftqM0_AjZ:-Nbu6Mgx7HKftqM0_Aj_:b-62fxey) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L122)):*
> ```XML
> 
> /**
>  * Scripture text panel that inserts the chapter string into innerHTML or a contentEditable div.
> ```

This comment appears to be incorrect (I think it was incorrect in the POC as well... Oops. Sorry)
___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu6Tpr2xdxhOrSYryY:-Nbu6Tpr2xdxhOrSYryZ:b-g20yhw) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L130)):*
> ```XML
>     // eslint-disable-next-line jsx-a11y/no-static-element-interactions
>     <div className="text-panel">
>       <RefSelector
> ```

If you move this RefSelector into `ResourceViewer`, add a `useState` for its `scrRef`, and use that state in the `useData.ChapterUsx` hook, you'll have the scrRef hooked up to the usx editor :)
___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 159 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu7aIi3bylLH_9uTaE:-Nbu7aIi3bylLH_9uTaF:b8jzo8t) ([raw file](https://github.com/paranext/paranext-core/blob/89fdfc623cd5f2e1836a13915e8765f7877c56a0/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L159)):*
> ```XML
>     'usfm',
>     useMemo(() => new VerseRef('GEN', '1', '1', ScrVers.English), []),
>     'Loading Psalm 1...',
> ```

This loading statement might be a bit too specific :)


<!-- Sent from Reviewable.io -->

2023-08-21 16:07 UTC, katherinejensen00 reviewed
Thanks for all of your help, TJ!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/380#-:-NcNqUaIDgxIcYxUIPsJ:b-zg7eeu)* status: all files reviewed, 9 unresolved discussions (waiting on @tjcouch-sil)

___
*[`.vscode/settings.json` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu3oD0BEsF6GAFWTfj:-NcNqGB2-epjR7iQ0eRP:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7fcce4378b68e9693538d3526105940e27d5fe49/.vscode/settings.json#L66)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We already have a cspell configuration in `paranext-core/cspell.json` that is picking up usfm. Is yours not respecting this file? Do you have some overrides in your VSCode settings that prevent you from using this file?
</blockquote></details>

Done.
___
*[`extensions/src/resource-viewer/resource-viewer.ts` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu5z19AJhJ-DbUe0Th:-NcNqHxJ2BFZ1CzOGCZY:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7fcce4378b68e9693538d3526105940e27d5fe49/extensions/src/resource-viewer/resource-viewer.ts#L17)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is this used? Can you remove it?
</blockquote></details>

Done.
___
*[`extensions/src/resource-viewer/resource-viewer.ts` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu62SU8bqg28exMsBU:-NcNqIPy5MGeT6Ocs2AY:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7fcce4378b68e9693538d3526105940e27d5fe49/extensions/src/resource-viewer/resource-viewer.ts#L130)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is this used? Can you remove it?
</blockquote></details>

Done.
___
*[`extensions/src/resource-viewer/resource-viewer.ts` line 141 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu64S709ywCesE9YeD:-NcNqIydDD_oZjhlSL9z:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7fcce4378b68e9693538d3526105940e27d5fe49/extensions/src/resource-viewer/resource-viewer.ts#L141)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This seems to be unnecessary test code - can we remove it?
</blockquote></details>

Done.
___
*[`extensions/src/resource-viewer/resource-viewer.ts` line 161 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu5EDBEU-ZlQxAaSdB:-NcNqJbm3msc3i3m1jS3:bxv7e1d) ([raw file](https://github.com/paranext/paranext-core/blob/7fcce4378b68e9693538d3526105940e27d5fe49/extensions/src/resource-viewer/resource-viewer.ts#L161)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The way to register unsubscribers has changed. Please refer to https://discord.com/channels/1064938364597436416/1136698231250755664 for how to update :) thanks!
</blockquote></details>

This ended up not being needed, so I just removed it.
___
*[`extensions/src/resource-viewer/resource-viewer.d.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu6GYY4phJ9ixD0a7D:-NcNqQGi3aZLA6t1Vq1p:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7fcce4378b68e9693538d3526105940e27d5fe49/extensions/src/resource-viewer/resource-viewer.d.ts#L7)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is this used? Can you remove it?
</blockquote></details>

Done.
___
*[`extensions/src/resource-viewer/resource-viewer.d.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu6Hku-w-ByP9msIgR:-NcNqR-rARP_Hf8dz1My:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7fcce4378b68e9693538d3526105940e27d5fe49/extensions/src/resource-viewer/resource-viewer.d.ts#L28)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is this used? Can you remove it?
</blockquote></details>

Done.
___
*[`extensions/src/resource-viewer/resource-viewer.d.ts` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu6IeWB9c9nkMZSaXg:-NcNqRFUDLsq35rOQKNt:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7fcce4378b68e9693538d3526105940e27d5fe49/extensions/src/resource-viewer/resource-viewer.d.ts#L31)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Are these used? Can you remove them?
</blockquote></details>

Done.
___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 122 at r1](https://reviewable.io/reviews/paranext/paranext-core/380#-Nbu6Mgx7HKftqM0_AjZ:-NcNqSAC7vxmJj-9pEIk:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7fcce4378b68e9693538d3526105940e27d5fe49/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L122)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This comment appears to be incorrect (I think it was incorrect in the POC as well... Oops. Sorry)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-21 16:15 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks for the hard work!

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/380#-:-NcNsDuMAZP5AIxTyJJV:bh33jmx)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-08-21 16:15 UTC, tjcouch-sil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/380)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-21 19:32 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/380#-:-NcO_MF58H5C8XxQlZIE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-21 19:32 UTC, merged

2023-08-21 22:39 UTC, irahopkinson reviewed
> Reviewed 6 of 11 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/380)* status: all files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`extensions/src/resource-viewer/package.json` line 13 at r3](https://reviewable.io/reviews/paranext/paranext-core/380#-NcPBady7ifJq0YLZtwN:-NcPBady7ifJq0YLZtwO:bic7qpa) ([raw file](https://github.com/paranext/paranext-core/blob/0bfdb7afe6868af2cce087bd070e6094536f334e/extensions/src/resource-viewer/package.json#L13)):*
> ```JSON
>   "license": "MIT",
>   "devDependencies": {
>     "usxeditor": "^0.0.9-alpha"
> ```

This is definitely not a `devDependency` since you use the package in production code. Change this to `dependencies`.


<!-- Sent from Reviewable.io -->

2023-08-22 13:46 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/380)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/src/resource-viewer/package.json` line 13 at r3](https://reviewable.io/reviews/paranext/paranext-core/380#-NcPBady7ifJq0YLZtwN:-NcSUSWP3hIos92Yc90C:b3svxjv) ([raw file](https://github.com/paranext/paranext-core/blob/0bfdb7afe6868af2cce087bd070e6094536f334e/extensions/src/resource-viewer/package.json#L13)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is definitely not a `devDependency` since you use the package in production code. Change this to `dependencies`.
</blockquote></details>

Since it is bundled into the extension main code, I would say it is a `devDependency`. It is not necessary for npm to install it when you're using the pre-built extension code.


<!-- Sent from Reviewable.io -->

2023-08-22 19:54 UTC, irahopkinson commented
*[`extensions/src/resource-viewer/package.json` line 13 at r3](https://reviewable.io/reviews/paranext/paranext-core/380#-NcPBady7ifJq0YLZtwN:-NcTm97N49CuOD8pBNyC:b-oh6dw3) ([raw file](https://github.com/paranext/paranext-core/blob/0bfdb7afe6868af2cce087bd070e6094536f334e/extensions/src/resource-viewer/package.json#L13)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Let's wait for Ira.
</blockquote></details>

According to [the npm definition](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file) and since it's used in production it belongs in `dependencies` (it should only go in `devDependencies` if it is required only in your development phase). @tjcouch-sil is correct but only relative to the main app, however the local `package.json` file should always describe things for itself not how they are for a consumer.


<!-- Sent from Reviewable.io -->

2023-08-23 19:11 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/380)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/src/resource-viewer/package.json` line 13 at r3](https://reviewable.io/reviews/paranext/paranext-core/380#-NcPBady7ifJq0YLZtwN:-NcYgKLC1y-DLXE0h8Uk:b-peff9r) ([raw file](https://github.com/paranext/paranext-core/blob/0bfdb7afe6868af2cce087bd070e6094536f334e/extensions/src/resource-viewer/package.json#L13)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

According to [the npm definition](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file) and since it's used in production it belongs in `dependencies` (it should only go in `devDependencies` if it is required only in your development phase). @tjcouch-sil is correct but only relative to the main app, however the local `package.json` file should always describe things for itself not how they are for a consumer.
</blockquote></details>

I disagree that the npm definition indicates this should be a dependency because we are only depending on the `usxeditor` package existing in our environment in local development. I believe [the difference in the way npm treats the two](https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencie) backs up my position. A `dependency` is installed when you install a package through `npm` as a dependency (or dev dependency) of your project, whereas a `devDependency` is not installed when you install a package through `npm` as a dependency (or dev dependency) of your project. If I install a library as a dependency of my app, I don't want to install that package's `devDependencies` because I am just using the final built files of that library. However, I do want to install that package's `dependencies` because the nature of `dependencies` is that they must exist in order for the library to work.

In my perspective, putting a package in `dependencies` is essentially equivalent to marking that package as `external` in webpack. [ERB](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/8d3efc1426e91bae90e85b829ca338b14f61be03/.erb/configs/webpack.config.base.ts#L11) sort-of makes this connection explicit by pulling `dependencies` from one of its `package.json` files and marking them external programmatically. However, I concede that they only did that with the `package.json` relating to [native modules](https://electron-react-boilerplate.js.org/docs/native-modules), so they're not hard on this issue (probably because this topic is not well understood and is debated widely). My perspective is that `dependencies` approximately equals `external` because marking something `external` means webpack will leave the `import` statements so node actually looks for that module and actually imports it instead of bundling it into your code, thereby making it a literal dependency in your production code.

We are distributing bundled extension code that has no dependencies other than those marked `external` in our webpack config. Let's pretend extensions were all on npm. If someone installed our extension as a library, they would have our built code. The only things they would want to install are the `dependencies` of our project because those are needed to run our code. `devDependencies` (like `usxeditor`) are already bundled into the extension bundle, so we don't want to install `devDependencies` again.

The difference is if you need it in production vs local development, so we can think about what code is being run. If we're developing locally, we're running webpack and bundling a bunch of dependencies together to make the main file that gets run. Hence we mark many things like webpack and `usxeditor` as `devDependencies`. If it's already built for production, we don't need those `devDependencies` because Platform.Bible is running the main file that's already built and ready to go.

The difference between dependencies and devDependencies in terms of bundled libraries appears to be debated fairly widely across the internet. A quick Google search proves this to be true - there are many people making very confident assertions that they are right on both sides as usual in the web dev world ;) I came down on the side that I did because it follows the way npm actually uses `dependencies` and `devDependencies`; there seem to be incongruences in the meanings of `dependencies` and `devDependencies` in my mind otherwise; and it seems there is not much consensus in the web dev world to the contrary.

The following comment from some random guy seems to represent my position well: https://github.com/webpack/webpack/issues/520#issuecomment-331689542


<!-- Sent from Reviewable.io -->

2023-08-24 22:11 UTC, irahopkinson commented
Thanks @tjcouch-sil for that great explaination so lets go with that.

In your first link it talked about [bundledDependencies](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bundleddependencies) which I don' think I knew about before. I'm wondering if we should investigate using that to make situations like this clearer?

2023-08-25 14:10 UTC, tjcouch-sil reviewed
Good question; I'm not really exactly sure what `bundledDependencies` does, but it seems unrelated to webpack-related bundling. Sounds like maybe npm will bundle those `dependencies` into the final deliverable, which is different than webpack bundling, which embeds the dependency code into your built files.

We should probably put something about how we use `dependencies` vs `devDependencies` somewhere in our documentation - does the style guide seem like a good place for it? I kinda feel like maybe a different place would be more suitable. Maybe we could add a quick description line in the style guide and link to a separate wiki page explaining more in-depth?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/380#-:-Nch0Rim6_xO6uyQZIFV:bm93998)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)



<!-- Sent from Reviewable.io -->

2023-08-27 21:13 UTC, irahopkinson commented
Would the [template README](https://github.com/paranext/paranext-extension-template/blob/main/README.md) be the right place? Otherwise go with your idea.





<!-- Sent from Reviewable.io -->

2023-08-28 14:21 UTC, tjcouch-sil reviewed
I'd prefer to put it somewhere that is more scoped to our code.  Since this is more of a preference than a semantically meaningful difference specifically for extensions because of the way we load them, I'd say it doesn't fit too well in the template README. I added a bullet to the [style guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide#typescript-specific-guidelines) at the bottom of the list "Specify bundled dependencies in `devDependencies`". Let me know what you think. I'm open to moving it somewhere else if you have other thoughts :)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/380#-:-NcwVdvg8ZFeKLKr8PlR:b-xyx8bo)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)



<!-- Sent from Reviewable.io -->

2023-08-28 19:37 UTC, irahopkinson commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks for capturing that.





<!-- Sent from Reviewable.io -->