Moved app dir to home/.platform.bible and restructured some files in there, named UnsubscriberAsyncLists
paranext/paranext-core pull request #384
Opened 2023-08-16 22:53 UTC by tjcouch-sil

2023-08-16 23:33 UTC, irahopkinson requested changes
Thanks for the excellent PR description. I presume that is just a typo having an extra dot in each path for item 2 Unzipped extensions?

Just one other question.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/384#-:-Nc-bJ7R2w0SzzfiOXQk:b-o2gjc6)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`.eslintrc.js` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/384#-Nc-dV3y-BjG9IRjvWbX:-Nc-dV3y-BjG9IRjvWbY:bxhwtli) ([raw file](https://github.com/paranext/paranext-core/blob/bb3eef8fc124cd62b3b08aa5104ac4d0f6f9c46c/.eslintrc.js#L44)):*
> ```JavaScript
>       'error',
>       {
>         allow: ['arrowFunctions', 'functions', 'methods'],
> ```

I don't understand why you are allowing these 3 when this error can be properly overcome by simply adding a comment in an empty function such as:
```js
function foo() {
    // do nothing.
}
```
Which shows that it is intentionally empty. For your use case here I would be ok with `allow: ['constructors'],` since they can often be expected to be empty, but even then you can add the comment.
___
*[`src/extension-host/extension-types/unsubscriber-async-list.ts` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/384#-Nc-a3HA-Q9Jwib1tLrW:-Nc-a3HA-Q9Jwib1tLrX:b5svz2i) ([raw file](https://github.com/paranext/paranext-core/blob/bb3eef8fc124cd62b3b08aa5104ac4d0f6f9c46c/src/extension-host/extension-types/unsubscriber-async-list.ts#L34)):*
> ```XML
>     return results.every((unsubscriberSucceeded, index) => {
>       if (!unsubscriberSucceeded)
>         logger.error(`UnsubscriberAsyncList ${this.name}: Unsubscriber at index ${index} failed!`);
> ```

FYI I was just starting to look at what it would take to do this. I was about to make a new branch and saw your commit and that you have already done it. Awesome!


<!-- Sent from Reviewable.io -->

2023-08-17 14:06 UTC, tjcouch-sil reviewed
Yep, that was a typo. Thanks!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/384#-:-Nc2nk2-4wlvf2XsgKnJ:b-l5uim2)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`.eslintrc.js` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/384#-Nc-dV3y-BjG9IRjvWbX:-Nc2nmEP3VUZUI6t3ZkB:bo3k2vc) ([raw file](https://github.com/paranext/paranext-core/blob/bb3eef8fc124cd62b3b08aa5104ac4d0f6f9c46c/.eslintrc.js#L44)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I don't understand why you are allowing these 3 when this error can be properly overcome by simply adding a comment in an empty function such as:
```js
function foo() {
    // do nothing.
}
```
Which shows that it is intentionally empty. For your use case here I would be ok with `allow: ['constructors'],` since they can often be expected to be empty, but even then you can add the comment.
</blockquote></details>

I just copied this configuration from what we are currently extending which is [airbnb's rules](https://github.com/airbnb/javascript/blob/46ae3e225673b6bbd52a49f78b9474cd282b8e4f/packages/eslint-config-airbnb-base/rules/best-practices.js#L95C6-L95C6), so this is what it has been this whole time. If we want to change it, I'd suggest we have a style discussion.

The reason I removed the non-typescript one and added this one is that typescript adds parameter properties, and the typescript version of the rule supports empty constructors with parameter properties.
___
*[`src/extension-host/extension-types/unsubscriber-async-list.ts` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/384#-Nc-a3HA-Q9Jwib1tLrW:-Nc2oSmN0U7ZRutd-Unn:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/bb3eef8fc124cd62b3b08aa5104ac4d0f6f9c46c/src/extension-host/extension-types/unsubscriber-async-list.ts#L34)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

FYI I was just starting to look at what it would take to do this. I was about to make a new branch and saw your commit and that you have already done it. Awesome!
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2023-08-17 14:14 UTC, lyonsil approved these changes
One small comment.  Otherwise looks great!

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/384#-:-Nc2qCe-Ekj3sokHlPxl:b-lvz70t)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`.eslintrc.js` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/384#-Nc-dV3y-BjG9IRjvWbX:-Nc2meTjCaUjv4GcwsNX:bwsga9j) ([raw file](https://github.com/paranext/paranext-core/blob/bb3eef8fc124cd62b3b08aa5104ac4d0f6f9c46c/.eslintrc.js#L44)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I don't understand why you are allowing these 3 when this error can be properly overcome by simply adding a comment in an empty function such as:
```js
function foo() {
    // do nothing.
}
```
Which shows that it is intentionally empty. For your use case here I would be ok with `allow: ['constructors'],` since they can often be expected to be empty, but even then you can add the comment.
</blockquote></details>

FWIW, I'm OK with empty function bodies in general.
___
*[`src/extension-host/services/extension.service.ts` line 93 at r1](https://reviewable.io/reviews/paranext/paranext-core/384#-Nc2oLky2xiOOem5-EAp:-Nc2oLky2xiOOem5-EAq:bgesa2u) ([raw file](https://github.com/paranext/paranext-core/blob/bb3eef8fc124cd62b3b08aa5104ac4d0f6f9c46c/src/extension-host/services/extension.service.ts#L93)):*
> ```XML
> 
> /** This is the location where we will store decompressed extension ZIP files */
> const userUnzippedExtensionsCacheUri: string = joinUriPaths('cache://extensions');
> ```

I think we can drop the call to `joinUriPaths` here and just assign the string to the `const` variable.


<!-- Sent from Reviewable.io -->

2023-08-17 14:15 UTC, lyonsil approved these changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/384)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-08-17 18:35 UTC, lyonsil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/384#-:-Nc3liBh1rQbvt1OpjfR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)



<!-- Sent from Reviewable.io -->

2023-08-17 20:04 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/384#-:-Nc45AEl-gCThu-SHMY4:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`.eslintrc.js` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/384#-Nc-dV3y-BjG9IRjvWbX:-Nc44fGlCHvlQlfRNOHD:bbgfsij) ([raw file](https://github.com/paranext/paranext-core/blob/bb3eef8fc124cd62b3b08aa5104ac4d0f6f9c46c/.eslintrc.js#L44)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

FWIW, I'm OK with empty function bodies in general.
</blockquote></details>

Sorry, didn't realise it was just a switch to the TS version of the rule. I'm fine with that.


<!-- Sent from Reviewable.io -->

2023-08-17 20:04 UTC, merged

2023-08-17 22:06 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/384)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`.eslintrc.js` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/384#-Nc-dV3y-BjG9IRjvWbX:-Nc4XAmG6CTkPeRRZXJg:b9n5i05) ([raw file](https://github.com/paranext/paranext-core/blob/bb3eef8fc124cd62b3b08aa5104ac4d0f6f9c46c/.eslintrc.js#L44)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Sorry, didn't realise it was just a switch to the TS version of the rule. I'm fine with that.
</blockquote></details>

No prob :) understandable. It looks confusing.


<!-- Sent from Reviewable.io -->