Add Project Data Provider Factories and associated types
paranext/paranext-core pull request #389
Opened 2023-08-18 22:15 UTC by lyonsil

2023-08-22 15:38 UTC, tjcouch-sil requested changes
Wow!! Great stuff! So excited to see projects are happening!! Thanks for the hard work on this.

> Reviewed 4 of 10 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/389#-:-NcStJO_-aEiQczg5Uzy:b-sumbm2)* status: all files reviewed, 13 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/src/hello-someone/hello-someone.ts` line 318 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSpM8S1Bq5ruuvxEsM:-NcSpM8S1Bq5ruuvxEsN:bw27hrl) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/extensions/src/hello-someone/hello-someone.ts#L318)):*
> ```XML
>       'abc',
>     );
>   if (customProjectDataProvider.dispose)
> ```

Should a PDP's `dispose` ever exist for someone who didn't create it? I think not since it's basically a data provider.
___
*[`extensions/src/hello-world/hello-world.d.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSZ60C5BBB9OXC0oBk:-NcSZ60C5BBB9OXC0oBl:b-rwkfm6) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/extensions/src/hello-world/hello-world.d.ts#L23)):*
> ```XML
> 
> declare module 'papi-project-data-types' {
>   export type MyProjectDataType = MandatoryProjectDataType & {
> ```

Since this type is created from `hello-world`, I think it would be best to keep it in that module. Maybe could you move it up into the `hello-world` module and then put an import line in this module instead? Like:

```typescript
declare module 'papi-project-data-types' {
  import { MyProjectDataType } from 'hello-world';
}
```
___
*[`src/declarations/papi-project-data-types.ts` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSZdF8EYHnwkJhsVRB:-NcSZdF8EYHnwkJhsVRC:b-7kpvt8) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/declarations/papi-project-data-types.ts#L1)):*
> ```XML
> declare module 'papi-project-data-types' {
> ```

Hot off the presses from Rolf and me (the commit went in yesterday afternoon) is that `papi-commands.ts` is now `papi-shared-types.ts` and should contain all our shared data types for ease of access for people. Do you think that's a good idea? We do lose some separation... If you agree with that decision, would you mind moving these things into that file and module? Let me know if you think we should do differently. :) Thanks! Sorry for the annoying timing.
___
*[`src/declarations/papi-project-data-types.ts` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSahqh7CZb8yVXlvxs:-NcSahqi55uotLlB7MGf:b-oaln85) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/declarations/papi-project-data-types.ts#L7)):*
> ```XML
> 
>   /** This is not yet a complete list of the data types available from Paratext projects. */
>   export type ParatextStandardProjectDataTypes = MandatoryProjectDataType & {
> ```

I think especially related to the suggestion above about moving all modules' shared types to one combined module, I'd think we should move these ProjectDataTypes out of this module. I dunno exactly where... Maybe just into one of the other `model` files? I can't think of a case where core would make its own ProjectDataTypes long-term, so maybe we can mark those TODO to be deleted when we clean up this test code or something.
___
*[`src/declarations/papi-project-data-types.ts` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSswKG40ehIOOOhfyG:-NcSswKG40ehIOOOhfyH:b-fkwqrt) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/declarations/papi-project-data-types.ts#L20)):*
> ```XML
>   /**
>    * Data types for each project data provider supported by PAPI. Extensions can add more data types
>    * with corresponding project data provider IDs by adding details to their `d.ts` file.
> ```

Can we call out that these must extend `MandatoryProjectDataTypes` to make sure people notice?
___
*[`src/declarations/papi-project-data-types.ts` line 25 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSt8ZZ3hfLDTMdzVRa:-NcSt8ZZ3hfLDTMdzVRb:b55z17r) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/declarations/papi-project-data-types.ts#L25)):*
> ```XML
>    * ```typescript
>    * declare module 'papi-project-data-types' {
>    *   export type MyProjectDataTypes = MandatoryProjectDataTypes & {
> ```

In a similar line to a couple other comments, could we move this example `MyProjectDataTypes` out to its own module and import it into `papi-project-data-types` here so we aren't cluttering the module?
___
*[`src/main/services/project-data-provider-factory.service.ts` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSptDIEeWXnDKhONBZ:-NcSptDIEeWXnDKhONB_:b-hrixp7) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/main/services/project-data-provider-factory.service.ts#L1)):*
> ```XML
> import {
> ```

I got confused when I saw that this was a "service". This is essentially just moving the creation of a test PDPF out of main and into its own file, right? Could we think of another name for it since it's not really serving functionality or adding new features to the PAPI in the same way that other services are? Maybe `notes-only-project-data-provider-factory.model.ts` or something? I dunno; it's kinda in a weird place in that it isn't really like any other files we have so far in my mind. I guess it is a service in some sense. Let me know your thoughts :)
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSbG-Y7raC-3nEi6nB:-NcSbG-Y7raC-3nEi6nC:b-14k94m) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/models/project-data-provider-engine.model.ts#L9)):*
> ```XML
>  * to the set of project types available in Paratext.
>  */
> export type ProjectTypes = keyof ProjectDataTypes;
> ```

I think that, since this type is just a modulation on `ProjectDataTypes`, it probably belongs in the `papi-project-data-types` (or `papi-shared-types` if you move stuff) module to go along with `ProjectDataTypes` if that's ok! Let me know if you have thoughts otherwise.
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 12 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcScGX61KVQWA3Y1Z4y:-NcScGX61KVQWA3Y1Z4z:besdztx) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/models/project-data-provider-engine.model.ts#L12)):*
> ```XML
> 
> // This enforces all the keys match ProjectDataTypes
> type IDataProviderEngineGeneric<T extends ProjectDataTypes> = {
> ```

If you put `T extends ProjectDataTypes & MandatoryProjectDataType`, does that prevent people from using their `ProjectDataTypes` if they don't extend `MandatoryProjectDataType`? Might be good to do that if so. And on `IDataProviderEngineGeneric` below.
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSbjWP-k84Ax6ZhDDa:-NcSbjWP-k84Ax6ZhDDb:b-gnlbzd) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/models/project-data-provider-engine.model.ts#L20)):*
> ```XML
> 
> // This enforces all the keys match ProjectDataTypes
> type IDataProviderGeneric<T extends ProjectDataTypes> = {
> ```

Should this be named `IProjectDataProviderGeneric` since it is constrained to `ProjectDataTypes`?
___
*[`src/shared/services/project-data-provider.service.ts` line 61 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSeKTo9CeKP49EssoW:-NcSeKTo9CeKP49 [...]

2023-08-24 23:23 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/389)* status: 10 of 19 files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/hello-someone/hello-someone.ts` line 318 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSpM8S1Bq5ruuvxEsM:-NccdmN-E3QVIdzojWJ5:b91pcrp) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/extensions/src/hello-someone/hello-someone.ts#L318)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should a PDP's `dispose` ever exist for someone who didn't create it? I think not since it's basically a data provider.
</blockquote></details>

Yes, you are right.  There is some type confusion going on here as the `networkObjectService.get` call doesn't actually give back an object with `dispose` on it.  I updated the type definition for PDPs to omit the `dispose` method so it doesn't show up in Intellisense.
___
*[`extensions/src/hello-world/hello-world.d.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSZ60C5BBB9OXC0oBk:-Ncda1j25Ds194qYUj9T:b-hcsy50) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/extensions/src/hello-world/hello-world.d.ts#L23)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since this type is created from `hello-world`, I think it would be best to keep it in that module. Maybe could you move it up into the `hello-world` module and then put an import line in this module instead? Like:

```typescript
declare module 'papi-project-data-types' {
  import { MyProjectDataType } from 'hello-world';
}
```
</blockquote></details>

I tried doing this, but it results in the following error: `Imports are not permitted in module augmentations. Consider moving them to the enclosing external module.ts(2667)`.  I also can't import the type in the same file where it is also declared in another module.

Looks like this has to be defined in the same module unless we move it completely into another file which seems unnecessarily complicated for extension developers.
___
*[`src/main/services/project-data-provider-factory.service.ts` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSptDIEeWXnDKhONBZ:-NccmYXB1QQkaJaSCmWd:b-sshsff) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/main/services/project-data-provider-factory.service.ts#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I got confused when I saw that this was a "service". This is essentially just moving the creation of a test PDPF out of main and into its own file, right? Could we think of another name for it since it's not really serving functionality or adding new features to the PAPI in the same way that other services are? Maybe `notes-only-project-data-provider-factory.model.ts` or something? I dunno; it's kinda in a weird place in that it isn't really like any other files we have so far in my mind. I guess it is a service in some sense. Let me know your thoughts :)
</blockquote></details>

I'm assuming this is where we would initialize/start all PDPFs that are not written in C# and are part of the core platform.  The "notes only" PDPF is kind of a test, but really I see it more of a placeholder for real PDPFs than a test to be completely deleted and nothing put in its place.  I couldn't think of a better name than the "PDPF service" for a thing like this.  Also, we REALLY want to make sure it only runs from one designated process, and main make more sense to me than the extension host.

If you have a different location or name that makes more sense, I'm open to suggestions.
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSbG-Y7raC-3nEi6nB:-Nccoi-C-rcLIFuHtQW1:bv8eg6k) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/models/project-data-provider-engine.model.ts#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think that, since this type is just a modulation on `ProjectDataTypes`, it probably belongs in the `papi-project-data-types` (or `papi-shared-types` if you move stuff) module to go along with `ProjectDataTypes` if that's ok! Let me know if you have thoughts otherwise.
</blockquote></details>

If we move then, then I think we'd want to move `IDataProviderEngineGeneric`, `ProjectDataProviderEngineTypes`, `IProjectDataProviderGeneric`, and `ProjectDataProvider`.  All 5 of theses belong together IMO.  Would you like them all to move or none of them?
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 12 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcScGX61KVQWA3Y1Z4y:-Ncco4pn-vgQYXfPUoN-:b-7vak5r) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/models/project-data-provider-engine.model.ts#L12)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

If you put `T extends ProjectDataTypes & MandatoryProjectDataType`, does that prevent people from using their `ProjectDataTypes` if they don't extend `MandatoryProjectDataType`? Might be good to do that if so. And on `IDataProviderEngineGeneric` below.
</blockquote></details>

That doesn't work.  It causes a type error.  I tried several things originally to pull `MandatoryProjectDataType` into the requirements for type definitions, and I couldn't find a way to do it with types alone.  I have a runtime check (which is better than nothing) instead.
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSbjWP-k84Ax6ZhDDa:-NccpPdc0DxHU7jGzONF:bzg1ihb) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/models/project-data-provider-engine.model.ts#L20)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should this be named `IProjectDataProviderGeneric` since it is constrained to `ProjectDataTypes`?
</blockquote></details>

I'll rename this and the non-generic one to be a little clearer.
___
*[`src/shared/services/project-data-provider.service.ts` line 61 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSeKTo9CeKP49EssoW:-NccqfER9opifDSDh6zb:b-ayywze) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/services/project-data-provider.service.ts#L61)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Awesome! Super happy that we can leverage the data provider service like this. One question, though: since we're using the same `registerEngine` function that's publicly available, we could hit name conflicts with extensions' data providers. Can we maybe rename this `registerEngine` (maybe to something that indicates it is private to within the core) and change the suffix that gets added or something to differentiate using it internally vs externally? And then we would make a new version of `registerEngine` that layers over this one and adds the suffix we currently use and is the new function exposed on the data provider papi service.
</blockquote></details>

How could we hit name conflicts if the name is a nonce?  I purposefully designed this so PDPs have random names so we don't have conflicts.  Continuing to layer over APIs with more functions doesn't really add any value, I don't think.

In general I don't like that prefix/suffix naming approach when adding services.  It's mostly because it makes the code much harder to deal with when interacting with other programming languages.  We're effecti [...]

2023-08-25 17:15 UTC, tjcouch-sil requested changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/389)* status: all files reviewed, 6 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/src/hello-world/hello-world.d.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSZ60C5BBB9OXC0oBk:-Nch8eeV9ZJ5mfEkeFG2:bsip34y) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/extensions/src/hello-world/hello-world.d.ts#L23)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I tried doing this, but it results in the following error: `Imports are not permitted in module augmentations. Consider moving them to the enclosing external module.ts(2667)`.  I also can't import the type in the same file where it is also declared in another module.

Looks like this has to be defined in the same module unless we move it completely into another file which seems unnecessarily complicated for extension developers.
</blockquote></details>

How are you getting this error? I can't seem to get it when I try adding this import for `CommandHandlers` to try it out on my machine either in VSCode or when I run `npx tsc`. Maybe we can look together for a bit.
___
*[`src/declarations/papi-shared-types.ts` line 82 at r3](https://reviewable.io/reviews/paranext/paranext-core/389#-Nch8xP6DMtgua6T9nHY:-Nch8xP6DMtgua6T9nHZ:b-750nsy) ([raw file](https://github.com/paranext/paranext-core/blob/a19a8bf75522366dde90f542b221f54c0442f15a/src/declarations/papi-shared-types.ts#L82)):*
> ```XML
>     ParatextStandardProjectDataTypes,
>     NotesOnlyProjectDataTypes,
>   } from 'papi-shared-types-dependencies';
> ```

Please consider moving this up to the top of the module where the `ScriptureReference` is being imported :)
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSbG-Y7raC-3nEi6nB:-Nch9IYzDycl-JzB2m1n:b-rwv0n9) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/models/project-data-provider-engine.model.ts#L9)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If we move then, then I think we'd want to move `IDataProviderEngineGeneric`, `ProjectDataProviderEngineTypes`, `IProjectDataProviderGeneric`, and `ProjectDataProvider`.  All 5 of theses belong together IMO.  Would you like them all to move or none of them?
</blockquote></details>

I'd still prefer just the one because it matches what we do with the other shared types. `ProjectTypes` and `ProjectDataTypes` in my mind are similarly useful and are more globally useful than being related particularly to PDPEs, so I'd think `ProjectTypes` belongs with the interface it's modulating. Maybe we ought to discuss further on a call.
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 25 at r3](https://reviewable.io/reviews/paranext/paranext-core/389#-NchAy3l4CNHuN2yLzIG:-NchAy3l4CNHuN2yLzIH:bxsie1s) ([raw file](https://github.com/paranext/paranext-core/blob/a19a8bf75522366dde90f542b221f54c0442f15a/src/shared/models/project-data-provider-engine.model.ts#L25)):*
> ```XML
> 
> /** All possible types for ProjectDataProviders: IDataProvider<ProjectDataType> */
> export type ProjectDataProvider = Omit<IProjectDataProviderGeneric<ProjectDataTypes>, 'dispose'>;
> ```

Actually I think this is an oversight on my part when I reworked the data provider types a bit. Would you mind putting this on `IDataProvider` please? Neither one is supposed to have `dispose`, so putting it on `IDataProvider` would solve both problems at once :) but I understand if you want me to do that separately or something.
___
*[`src/shared/services/project-data-provider.service.ts` line 61 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSeKTo9CeKP49EssoW:-NchBVkd1nvtziaavRqK:buxnm8c) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/services/project-data-provider.service.ts#L61)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

How could we hit name conflicts if the name is a nonce?  I purposefully designed this so PDPs have random names so we don't have conflicts.  Continuing to layer over APIs with more functions doesn't really add any value, I don't think.

In general I don't like that prefix/suffix naming approach when adding services.  It's mostly because it makes the code much harder to deal with when interacting with other programming languages.  We're effectively parsing a big string into a JSON object, then taking fields out of the JSON object and parsing them again.  Let's parse once and be done with it.  If we need more fields on the JSON object, I think they should be top-level fields.  But again, since the name of the PDP object is random, it shouldn't matter here.
</blockquote></details>

I agree that there should be better ways to indicate information about a network object than prefix and/or suffix information. Prefixes and suffixes are a short-term solution to a larger issue (as we discussed a while ago with [project design stuff](https://docs.google.com/document/d/1K-lNUzzThDvDrNrnU2UXXHny30SgjhIxfkC-Xc1fk5o/edit#heading=h.wuvpr98m91q0)).

For the short-term, it seems helpful to have the different types of network objects have different prefixes or suffixes. This is due to my thought that the short-term solution to keeping lists of the different kinds of network objects will probably need to differentiate them depend on prefixes and suffixes, unfortunately.

As such, I'd like to keep PDPs separated from DPs. So this is less about literal name conflicts and more about different types of network objects. Sorry I didn't keep that clear in my head and in my explanation before.

If you'd prefer to leave it for now (or even just add a prefix/suffix on the id right here and call it a day), I understand. It will likely have to change somewhat when we implement the short-term network object tracking solution, but that is a different issue. Just let me know your preference; not a big deal either way.
___
*[`src/shared/services/project-data-provider.service.ts` line 99 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSk1wDCqI72VuLQcmC:-NchejnXC-ex86DW9jrj:bt1dy8z) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/services/project-data-provider.service.ts#L99)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Assuming people want to use Intellisense, then we probably want to leave these parameters as-is, don't we?  Then people can get values out of metadata and make sure a project type matches something they expect and can go from there.  Maybe storage type is extraneous to them, but they can just pass the storage type along from the metadata object.
</blockquote></details>

I believe the solutions I proposed would allow people to use Intellisense to the extent to which they are able. They have to know at compile time which kind of projectType they're dealing with, so they will have to specify that in some way concretely. Then the object they get has the types and such they want. If they simply pull values out of metadata for the project, they won't be able to tell what data types are on the PDP. It is an unfortunate problem but one I don't think we are able to avoid.

I thought we would be able to do more originally, but I was glossing over this issue. Sorry to mislead you on that hope.
___
*[`src/shared/services/project-data-provider.service.ts` line 108 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSnNhp9hfJojlHMRcD:-NchfYm5DSsuVmjvRWgQ:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/services/projec [...]

2023-08-25 19:27 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/389)* status: 14 of 21 files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/hello-world/hello-world.d.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSZ60C5BBB9OXC0oBk:-Nci98VEAuqHY_htEtae:b-l04ita) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/extensions/src/hello-world/hello-world.d.ts#L23)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

How are you getting this error? I can't seem to get it when I try adding this import for `CommandHandlers` to try it out on my machine either in VSCode or when I run `npx tsc`. Maybe we can look together for a bit.
</blockquote></details>

Resolved per our discussion
___
*[`src/declarations/papi-shared-types.ts` line 82 at r3](https://reviewable.io/reviews/paranext/paranext-core/389#-Nch8xP6DMtgua6T9nHY:-NchkIsX1kSsxvh7SrOW:bap7wft) ([raw file](https://github.com/paranext/paranext-core/blob/a19a8bf75522366dde90f542b221f54c0442f15a/src/declarations/papi-shared-types.ts#L82)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please consider moving this up to the top of the module where the `ScriptureReference` is being imported :)
</blockquote></details>

Refactored per our discussion
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSbG-Y7raC-3nEi6nB:-Nci1sMvCjoSNvjLMFeM:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/models/project-data-provider-engine.model.ts#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'd still prefer just the one because it matches what we do with the other shared types. `ProjectTypes` and `ProjectDataTypes` in my mind are similarly useful and are more globally useful than being related particularly to PDPEs, so I'd think `ProjectTypes` belongs with the interface it's modulating. Maybe we ought to discuss further on a call.
</blockquote></details>

Done.
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 25 at r3](https://reviewable.io/reviews/paranext/paranext-core/389#-NchAy3l4CNHuN2yLzIG:-NchkLkQBjQI6omDAhlf:blsr546) ([raw file](https://github.com/paranext/paranext-core/blob/a19a8bf75522366dde90f542b221f54c0442f15a/src/shared/models/project-data-provider-engine.model.ts#L25)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Actually I think this is an oversight on my part when I reworked the data provider types a bit. Would you mind putting this on `IDataProvider` please? Neither one is supposed to have `dispose`, so putting it on `IDataProvider` would solve both problems at once :) but I understand if you want me to do that separately or something.
</blockquote></details>

Done - this was moved down to networkObjectService since that's where it came from.
___
*[`src/shared/services/project-data-provider.service.ts` line 61 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSeKTo9CeKP49EssoW:-Nchl6nTAwKA2hXsfoBy:b-oyq08p) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/services/project-data-provider.service.ts#L61)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I agree that there should be better ways to indicate information about a network object than prefix and/or suffix information. Prefixes and suffixes are a short-term solution to a larger issue (as we discussed a while ago with [project design stuff](https://docs.google.com/document/d/1K-lNUzzThDvDrNrnU2UXXHny30SgjhIxfkC-Xc1fk5o/edit#heading=h.wuvpr98m91q0)).

For the short-term, it seems helpful to have the different types of network objects have different prefixes or suffixes. This is due to my thought that the short-term solution to keeping lists of the different kinds of network objects will probably need to differentiate them depend on prefixes and suffixes, unfortunately.

As such, I'd like to keep PDPs separated from DPs. So this is less about literal name conflicts and more about different types of network objects. Sorry I didn't keep that clear in my head and in my explanation before.

If you'd prefer to leave it for now (or even just add a prefix/suffix on the id right here and call it a day), I understand. It will likely have to change somewhat when we implement the short-term network object tracking solution, but that is a different issue. Just let me know your preference; not a big deal either way.
</blockquote></details>

Ok - I added `-pdp` to the end of the randomly generated name.
___
*[`src/shared/services/project-data-provider.service.ts` line 99 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSk1wDCqI72VuLQcmC:-NchlLuODyiCjUDrr2HE:bprf9ga) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/services/project-data-provider.service.ts#L99)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe the solutions I proposed would allow people to use Intellisense to the extent to which they are able. They have to know at compile time which kind of projectType they're dealing with, so they will have to specify that in some way concretely. Then the object they get has the types and such they want. If they simply pull values out of metadata for the project, they won't be able to tell what data types are on the PDP. It is an unfortunate problem but one I don't think we are able to avoid.

I thought we would be able to do more originally, but I was glossing over this issue. Sorry to mislead you on that hope.
</blockquote></details>

Added a TODO to fix this when https://github.com/paranext/paranext-core/issues/357 is resolved.


<!-- Sent from Reviewable.io -->

2023-08-25 19:30 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thank you for the hard work! This is awesome!

> Reviewed 7 of 7 files at r4, all commit messages.
> Dismissed @tjcouch-sil from a discussion.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/389#-:-NciA6pXASOpQ4NcDIuG:b-rykzh1)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`extensions/src/hello-world/hello-world.d.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSZ60C5BBB9OXC0oBk:-Nci9YN434O1nZErVQ4f:bhim0uf) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/extensions/src/hello-world/hello-world.d.ts#L23)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Resolved per our discussion
</blockquote></details>

Had troubles with the way node parses modules when they do and don't have top-level imports and exports, so we decided to undo this and just let `papi-shared-types` be polluted. Not a huge deal, and the inconsistencies would be confusing for extension developers.
___
*[`src/shared/services/project-data-provider.service.ts` line 61 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSeKTo9CeKP49EssoW:-Nci9wvt0wVtBo-NKDcQ:b-3t1yr9) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/services/project-data-provider.service.ts#L61)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ok - I added `-pdp` to the end of the randomly generated name.
</blockquote></details>

We discussed that we might not actually need to differentiate pdps since PDPFs will give the ids.
___
*[`src/shared/services/project-data-provider.service.ts` line 99 at r2](https://reviewable.io/reviews/paranext/paranext-core/389#-NcSk1wDCqI72VuLQcmC:-Nci9TDq93f_fZUaLLX7:btryz0c) ([raw file](https://github.com/paranext/paranext-core/blob/004a2ef0fc225b76e255a0320efc7577c6aee0e1/src/shared/services/project-data-provider.service.ts#L99)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe the solutions I proposed would allow people to use Intellisense to the extent to which they are able. They have to know at compile time which kind of projectType they're dealing with, so they will have to specify that in some way concretely. Then the object they get has the types and such they want. If they simply pull values out of metadata for the project, they won't be able to tell what data types are on the PDP. It is an unfortunate problem but one I don't think we are able to avoid.

I thought we would be able to do more originally, but I was glossing over this issue. Sorry to mislead you on that hope.
</blockquote></details>

Discussed that we will make this change in #357


<!-- Sent from Reviewable.io -->

2023-08-25 19:30 UTC, tjcouch-sil approved these changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/389)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-25 19:46 UTC, merged

2023-08-27 22:26 UTC, irahopkinson commented
*[`src/shared/services/project-data-provider.service.ts` line 46 at r5](https://reviewable.io/reviews/paranext/paranext-core/389#-Nct5OOl-w0G7d4JfIbj:-Nct5OOl-w0G7d4JfIbk:b1hqzsy) ([raw file](https://github.com/paranext/paranext-core/blob/84bde924209f8d698ace1720eefcf9cec731f77a/src/shared/services/project-data-provider.service.ts#L46)):*
> ```XML
>         ),
>       );
>       if (!pdpId) throw new Error(`Could get register project data provider for ${projectId} `);
> ```

BTW is this error message missing the word 'not' or am I missing something?


<!-- Sent from Reviewable.io -->

2023-08-27 22:36 UTC, irahopkinson commented
*[`src/shared/services/project-data-provider.service.ts` line 120 at r5](https://reviewable.io/reviews/paranext/paranext-core/389#-Nct7vNH8n1ftO6Q1Bvc:-Nct7vNH8n1ftO6Q1Bvd:bbls9rc) ([raw file](https://github.com/paranext/paranext-core/blob/84bde924209f8d698ace1720eefcf9cec731f77a/src/shared/services/project-data-provider.service.ts#L120)):*
> ```XML
> export interface PapiBackendProjectDataProviderService {
>   registerProjectDataProviderEngineFactory: typeof registerProjectDataProviderEngineFactory;
>   getProjectDataProvider: typeof getProjectDataProvider;
> ```

BTW This interface could extend from the frontend one so we don't have to declare this twice



_Code quote:_
```XML
getProjectDataProvider: typeof getProjectDataProvider;
```


<!-- Sent from Reviewable.io -->