Add C# project data support
paranext/paranext-core pull request #427
Opened 2023-09-18 17:42 UTC by lyonsil

2023-09-18 17:47 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: 0 of 29 files reviewed, 1 unresolved discussion

___
*[`src/main/main.ts` line 326 at r1](https://reviewable.io/reviews/paranext/paranext-core/427#-NedOX4p8AAqML4Sf3PJ:-NedOX4p8AAqML4Sf3PK:b-4430w7) ([raw file](https://github.com/paranext/paranext-core/blob/8841c4557cb7132f8057eed34e09206ae58b1c33/src/main/main.ts#L326)):*
> ```XML
>   setTimeout(async () => {
>     const paratextPdp = await getProjectDataProvider(
>       '499234e1-9965-452b-8175-138330893b6a',
> ```

This is a test project I got from Tim.  I'm not sure if we should add this project as part of setting up a dev environment or just cut this code altogether.  Thoughts?


<!-- Sent from Reviewable.io -->

2023-09-19 22:21 UTC, tjcouch-sil requested changes
> Reviewed 15 of 29 files at r1, 11 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: 25 of 29 files reviewed, 12 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/NetworkObjects/DataProvider.cs` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/427#-NeiJ8-r5SW7JyNl9-6O:-NeiJ8-r5SW7JyNl9-6P:b-lpa5fy) ([raw file](https://github.com/paranext/paranext-core/blob/5709ed37f2802a2b6e3e802882f2e4a418a91f6e/c-sharp/NetworkObjects/DataProvider.cs#L34)):*
> ```Smalltalk
>             : base(papiClient)
>         {
>             // "-data" is the suffix used by PAPI for data provider names
> ```

Is there any particular reason to remove this comment? Seems like a helpful explanation of what's happening here.
___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NeimxEm8oBaU8OILd7T:b-j93u5t) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
> ```Smalltalk
>     // Inside of each project's "shortName_ID" directory, these are the subdirectories and files
>     private const string PROJECT_PARATEXT_SUBDIRECTORY = "project";
>     private const string PROJECT_EXTENSIONS_SUBDIRECTORY = "extensions";
> ```

I don't believe we want to have a separate `extensions` subdirectory for the data that extensions use. Rather, I believe all data related to the project goes in the single `project` subdirectory (inside the top project directory). Each PSI gets to determine where it puts extension data within its `project` subdirectory. So one PSI (according to one `storageType`) might put all its extension data in its `<name>_<id>/project/extensions` folder while another PSI might intermingle some things like `<name>_<id>/project/biblicalTermsRenderings.json` and put everything else in the extensions folder or something.

@FoolRunning do you have thoughts? I don't want Matt to have to rework this before being sure.
___
*[`c-sharp/Projects/LocalProjects.cs` line 82 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeiX8_X6Bk5sgnGSzFL:-NeiX8_Y80ZGZMiy85wu:bw5y2g) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L82)):*
> ```Smalltalk
>     public static void SaveProjectMetadata(ProjectMetadata metadata, bool overwrite = false)
>     {
>         var projectDir = Path.Join(s_projectRootFolder, $"{metadata.Name}_${metadata.ID}");
> ```

Is the `$` inside the string supposed to be there? Seems it is a literal dollar sign in the string. I believe the dir names are supposed to be just <name>_<id>, but I could be missing something!

I also see this template (with the literal dollar sign) on line 112. It might be best to combine these into a separate function that generates the dir name.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeizA8b9B1XQw2pr-DS:-NeizA8b9B1XQw2pr-DT:bay4fi9) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L39)):*
> ```Smalltalk
>         try
>         {
>             details = LocalProjects.GetProjectDetails(Guid.Parse(projectID));
> ```

I'm not familiar with this `Guid` library. Are there any conditions under which `Guid.Parse` would fail? I do not know if project ids are standardized enough to parse as guids if there are any particular requirements. @FoolRunning do you know if project ids are required to be standardized in any way?
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-Nej-JQT7JOEfFufGwZE:-Nej-JQT7JOEfFufGwZF:b-fob64i) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L57)):*
> ```Smalltalk
> 
>         // Once the PDP has been registered, return the name of it so callers can get it
>         newPdp.RegisterDataProvider().Wait();
> ```

Was synchronously waiting preferred here for some reason over asynchronous? Can we make this method asynchronous instead of synchronous with a wait?
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 92 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejLLfkCM-aV17mk5aC:-NejLLflAdidlW1FKKd6:b-8r9dzy) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L92)):*
> ```Smalltalk
>             Book
>                 => string.IsNullOrEmpty(error)
>                     ? ResponseToRequest.Failed(error)
> ```

This reads unnaturally to me. I would expect the presence of an error string to indicate a failure, not the other way around. Is there any way to rename some things or refactor a bit to make things make more natural sense?
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 44 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejPV0514Bv9xHMI0R5:-NejPV0514Bv9xHMI0R6:b3wc5py) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ProjectDataProvider.cs#L44)):*
> ```Smalltalk
>     }
> 
>     protected override ResponseToRequest HandleRequest(string functionName, JsonArray args)
> ```

Should this be asynchronous to be more flexible with various implementations? Actually, this prompts me to wonder if a lot of stuff in this PR should be asynchronous as we would do for the JavaScript side. I imagine these abstract classes may be exposed to C# extensions to use.
___
*[`c-sharp/Projects/ProjectStorageType.cs` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejTInA4dI143wTTmdb:-NejTInA4dI143wTTmdc:bbrnpl3) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ProjectStorageType.cs#L7)):*
> ```Smalltalk
> /// This is not related to the format of the data itself but the way it is stored
> /// </summary>
> public enum ProjectStorageType
> ```

I wonder if we will need to make this some kind of flexible enum that can be extended by C#-based extensions. Maybe it's worth creating another issue on this since this PR is big and works right now?
___
*[`c-sharp/Projects/ProjectType.cs` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejTVtq-BCvoRNA5JIi:-NejTVtq-BCvoRNA5JIj:bgig4b3) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ProjectType.cs#L6)):*
> ```Smalltalk
> /// Format of main (Project Data Provider, not extension) data in a project
> /// </summary>
> internal static class ProjectType
> ```

Why is this a class instead of an enum like `ProjectStorageType`?

As with `ProjectStorageType`, I wonder if we will need to make this some kind of flexible enum that can be extended by C#-based extensions. Maybe it's worth creating another issue on this since this PR is big and works right now?
___
*[`c-sharp/Projects/RawDirectoryProjectStreamManager.cs` line 67 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejUKVbDrG5GrrNhPa8:-NejUKVbDrG5GrrNhPa9:b-xufl3d) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/RawDirectoryProjectStreamManager.cs#L67)):*
> ```Smalltalk
>     }
> 
>     public Stream? GetDataStream(string streamName, bool createIfNotExists = false)
> ```

I think I'm reading that we are giving PSIs direct access to `<name>_<id>`, not just `<name>_<id>/project` folder, which we are not supposed to do. If so, we should probably restrict them or put some TODOs around to indicate where this access needs to be restr [...]

2023-09-19 22:23 UTC, tjcouch-sil reviewed
Wow!! Thanks for all the hard work on this! Super excited for all the hard work you put into this. Thank you!

> Reviewed 3 of 29 files at r1, 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427#-:-NejXSm6DrGGhUbwApCH:b-1shk6a)* status: all files reviewed, 12 unresolved discussions (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2023-09-20 16:05 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 11 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/NetworkObjects/DataProvider.cs` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/427#-NeiJ8-r5SW7JyNl9-6O:-Nen18wO7K0sQ5jcOMlM:b-yjjsok) ([raw file](https://github.com/paranext/paranext-core/blob/5709ed37f2802a2b6e3e802882f2e4a418a91f6e/c-sharp/NetworkObjects/DataProvider.cs#L34)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is there any particular reason to remove this comment? Seems like a helpful explanation of what's happening here.
</blockquote></details>

Ah, I will put it back.  I had removed it in an earlier revision because I was changing it to only end in "-pdp" for project data providers.  Then I discovered through testing that PDPs end with "-pdp-data", so I removed my other changes but didn't put this comment back.
___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NenK58w8z_jCWdxCoG_:bbztglz) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I don't believe we want to have a separate `extensions` subdirectory for the data that extensions use. Rather, I believe all data related to the project goes in the single `project` subdirectory (inside the top project directory). Each PSI gets to determine where it puts extension data within its `project` subdirectory. So one PSI (according to one `storageType`) might put all its extension data in its `<name>_<id>/project/extensions` folder while another PSI might intermingle some things like `<name>_<id>/project/biblicalTermsRenderings.json` and put everything else in the extensions folder or something.

@FoolRunning do you have thoughts? I don't want Matt to have to rework this before being sure.
</blockquote></details>

Copying my comments from `RawDirectoryProjectStreamManager`:

If something else (Paratext, Clear, etc.) might need tight ownership over everything in the `project` subdirectory, then where are PSIs supposed to store extension data?  I guess we could force it to go own level down further (e.g., `<name>_<id>/project/real_project_data` and `<name>_<id>/project/extension_data`), but why?  What are you worried about PSIs doing?
___
*[`c-sharp/Projects/LocalProjects.cs` line 82 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeiX8_X6Bk5sgnGSzFL:-Nen2nfo3LWK6RDGN11x:bn7mn7s) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L82)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is the `$` inside the string supposed to be there? Seems it is a literal dollar sign in the string. I believe the dir names are supposed to be just <name>_<id>, but I could be missing something!

I also see this template (with the literal dollar sign) on line 112. It might be best to combine these into a separate function that generates the dir name.
</blockquote></details>

You're right, those were mistakes.  Thanks for pointing them out.  Obviously this is part of the code that hasn't been tested yet.  Project creation and writing hasn't really been tested well yet.  I was putting some simple ideas in place for now.

Sure, I can add a one liner method for this.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeizA8b9B1XQw2pr-DS:-Nen4SWc6EOiCJe3494X:b-ar4icq) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm not familiar with this `Guid` library. Are there any conditions under which `Guid.Parse` would fail? I do not know if project ids are standardized enough to parse as guids if there are any particular requirements. @FoolRunning do you know if project ids are required to be standardized in any way?
</blockquote></details>

If I GUID isn't a GUID, then Guid.Parse will fail. :smile:

For example:
```c#
	public static void Main()
	{
		Guid.Parse("This is not a GUID");
	}
```

Produces this:
```
Run-time exception (line 7): Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
```

More details are in the [.NET documentation for the method](https://learn.microsoft.com/en-us/dotnet/api/system.guid.parse?view=net-7.0).  It actually can parse GUIDs in a few other formats, too, but I don't think we will use any of those.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-Nej-JQT7JOEfFufGwZE:-Nen5p8c2ti5NjVbiRL-:bk1dke1) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L57)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Was synchronously waiting preferred here for some reason over asynchronous? Can we make this method asynchronous instead of synchronous with a wait?
</blockquote></details>

It would be significantly disruptive to convert this method to async because of all the places that get touched.  If you change this to `async`, you probably change a bunch of other interfaces and methods at the same time.  Nearly every method becomes `async`.  I started down that path a week or two ago and backed out.

At this point in the code, using `async` doesn't buy us a lot in practice.  The really important place to use `async` is inside of the message transport (i.e., `PapiClient.cs`).  We don't want to block handling an incoming message because we are already handling another one in front of it.  Once the tasks for incoming messages have been scheduled (see `HandleIncomingMessages()` in `PapiClient.cs`), they are able to run on different threads in the thread pool.  (The documented description of `Task.Run()` is `Queues the specified work to run on the ThreadPool and returns a task or [Task<TResult>](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1?view=net-7.0) handle for that work.`.)

In JavaScript/TypeScript, the runtime engine really has a single thread, so `async` is needed for [cooperative multitasking](https://en.wikipedia.org/wiki/Cooperative_multitasking).  In .NET, the runtime uses true [multithreading](https://en.wikipedia.org/wiki/Multithreading_(computer_architecture).  .NET `Task` objects make the situation fuzzier because it adds the ability for programs to use cooperative multitasking and multithreading both at the same time.

Technically it would slightly more performant to do everything `async` so that fewer threads and context switches would be needed, but from previous testing I've already seen that the existing architecture can handle more than a thousand requests per second, and that's way faster than we need.  Also, writing the `async` code is more tedious, so I didn't really think spending the time on it was important vs. all the other stuff we have to get done for the project.  Basically I'm prioritizing easier code to write/understand over a small and I think unneeded performance benefit.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 92 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejLLfkCM-aV17mk5aC:-NenCZvQ61PlQRov0ZEU:b-w2j1mp) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L92)):*
<details><summary><i>Previously, tjc [...]

2023-09-20 22:00 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: 23 of 29 files reviewed, 10 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`src/shared/services/project-data-provider.service.ts` line 113 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejV4n1ABgP8jIqfP9A:-NeoaoUJAwGjR_zylNVi:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/src/shared/services/project-data-provider.service.ts#L113)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Sorry, I don't fully understand what you're suggesting.  I'll follow up with you separately.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-09-21 15:49 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: 22 of 30 files reviewed, 9 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/Projects/ProjectStorageType.cs` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejTInA4dI143wTTmdb:-NesNB2j5M5pAmZevZG4:b-9u801q) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ProjectStorageType.cs#L7)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Paratext already has a more flexible enum type we use in another place.  I didn't use it here because I wanted tight control over how each enum value is converted to JSON.

I will just convert this to a string like it is for `ProjectType` to make C#-based extensions easier to work with.
</blockquote></details>

This has been converted to a string type with several built-in values.


<!-- Sent from Reviewable.io -->

2023-09-21 20:02 UTC, FoolRunning requested changes
> Reviewed 16 of 29 files at r1, 3 of 12 files at r2, 8 of 8 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 17 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`c-sharp/JsonUtils/ProjectMetadataConverter.cs` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/427#-NeddKXJ4r5Y4PmYssKf:-NeddKXJ4r5Y4PmYssKg:b-kv7hje) ([raw file](https://github.com/paranext/paranext-core/blob/8841c4557cb7132f8057eed34e09206ae58b1c33/c-sharp/JsonUtils/ProjectMetadataConverter.cs#L50)):*
> ```Smalltalk
>         }
> 
>         public static string ToJsonString(this ProjectMetadata projectMetadata)
> ```

Why is this not just a method on **ProjectMetadata**?
___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-Net56sc4rIXi7bKgxwj:bjasc97) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Copying my comments from `RawDirectoryProjectStreamManager`:

If something else (Paratext, Clear, etc.) might need tight ownership over everything in the `project` subdirectory, then where are PSIs supposed to store extension data?  I guess we could force it to go own level down further (e.g., `<name>_<id>/project/real_project_data` and `<name>_<id>/project/extension_data`), but why?  What are you worried about PSIs doing?
</blockquote></details>

Interesting question. I would think it would be best left up to the PSI (extension data is also going to go through the PSI as I recall). However, I would expect best-practices to be to have the PSI create a sub-directory for each extension so extensions can't modify the data of other extensions.
___
*[`c-sharp/Projects/LocalProjects.cs` line 15 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-Net7Uew9j5p7c91et6M:-Net7Uew9j5p7c91et6N:b-ujk1s2) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/LocalProjects.cs#L15)):*
> ```Smalltalk
> {
>     private static readonly ConcurrentDictionary<Guid, ProjectDetails> s_projectDetailsMap = new();
>     private static readonly ConcurrentDictionary<Guid, ScrText> s_paratextProjectMap = new();
> ```

I would think this map should not exist. The projects should be put into the **ScrTextCollection** so the rest of ParatextData can find them.
___
*[`c-sharp/Projects/LocalProjects.cs` line 127 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-Net6ogk1Hrlej632uP2:-Net6ogk1Hrlej632uP3:b-25i7mt) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/LocalProjects.cs#L127)):*
> ```Smalltalk
>         ProjectName projectName =
>             new(Path.Join(projectDetails.Directory, PROJECT_PARATEXT_SUBDIRECTORY));
>         // TODO: Figure out a way to get a proper Paratext user
> ```

You could have asked me. :stuck_out_tongue_winking_eye: 
**RegistrationInfo.DefaultUser** should be what you want.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeizA8b9B1XQw2pr-DS:-Net8wvj2E2dJXl9ZrjN:b-o2x8f2) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L39)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If I GUID isn't a GUID, then Guid.Parse will fail. :smile:

For example:
```c#
	public static void Main()
	{
		Guid.Parse("This is not a GUID");
	}
```

Produces this:
```
Run-time exception (line 7): Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
```

More details are in the [.NET documentation for the method](https://learn.microsoft.com/en-us/dotnet/api/system.guid.parse?view=net-7.0).  It actually can parse GUIDs in a few other formats, too, but I don't think we will use any of those.
</blockquote></details>

A project Guid in Paratext is not a standard GUID. It is actually the hash of the first commit to the Mercurial repository. That is why **ScrText.Guid** is a **HexId** type. I would expect this to cause problems with this code.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 100 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetAqDz5f52szDTyprJ:-NetAqE-C2XexKsQKeZw:bb4s58q) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L100)):*
> ```Smalltalk
>             Verse
>                 => string.IsNullOrEmpty(error)
>                     ? ResponseToRequest.Succeeded(scrText.GetVerseText(verseRef))
> ```

I'm not sure how much we care at the moment, but this is not the correct implementation for getting the USFM of a single verse. It should be **ScrText.Parser.GetVerseUsfmText**. The call you have here will skip over non-verse text (e.g. footnotes, section heads, etc.).
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 172 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetG_op2WtPOM0C5VOa:-NetG_op2WtPOM0C5VOb:b8asrbw) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L172)):*
> ```Smalltalk
>         using TextWriter textWriter = new StreamWriter(dataStream, Encoding.UTF8);
>         textWriter.Write(data);
>         textWriter.Flush();
> ```

It's probably fine for now, but long-term the writing of any project data should be inside a write lock.
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 29 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetDRWDE0eyovZEV5AD:-NetDRWDE0eyovZEV5AE:bp3m9cp) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L29)):*
> ```Smalltalk
>     protected Dictionary<string, Func<string, ResponseToRequest>> Getters { get; } = new();
>     protected Dictionary<string, Func<string, string, ResponseToRequest>> Setters { get; } = new();
>     protected Dictionary<string, Func<string, ResponseToRequest>> Subscribers { get; } = new();
> ```

I thought the whole point of the design of data providers in Platform.Bible was that we wouldn't need to do things like this. Why are methods like the generic **HandleRequest** below necessary? Did that nice-ness never make it to the C# side of things?
___
*[`c-sharp/Projects/ProjectStorageInterpreter.cs` line 21 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetHF_uELcGNSqPHW1G:-NetHF_uELcGNSqPHW1H:b-n2t80n) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectStorageInterpreter.cs#L21)):*
> ```Smalltalk
>     )
>         // TODO: Register one network object per (storage type, project type) pair or come up with a better approach
>         : base($"platform.{storageType}-{projectTypes[0]}-psi", papiClient)
> ```

Probably not worth changing, but I would expect the C# code in Platform.Bible to only ever support one PSI implementation and one PDP implementation - the ones related to the existing Paratext project structure. I would expect everything else to not be written in C#.
___
*[`c-sharp/Projects/ProjectType.cs` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejTVtq-BCvoRNA5JIi:-NetI1m28382vdDxa0fa:b-brlt5j) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ProjectType.cs#L6)):*
> ... by C#-based extensions

Why would a C# extension need any code in this ex [...]

2023-09-21 21:47 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 17 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/JsonUtils/ProjectMetadataConverter.cs` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/427#-NeddKXJ4r5Y4PmYssKf:-NetXiU28Iqevg3stlvN:b-jbj2ow) ([raw file](https://github.com/paranext/paranext-core/blob/8841c4557cb7132f8057eed34e09206ae58b1c33/c-sharp/JsonUtils/ProjectMetadataConverter.cs#L50)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Why is this not just a method on **ProjectMetadata**?
</blockquote></details>

It could be, but I have been generally trying to keep JSON serialization code until `JsonUtils`.  I don't have a strong opinion on this.  I was trying to follow the general pattern that was already there, and it was kind of nice to have the main class just focus on the data fields and keep serialization/deserialization concerns separate.  If you thing they ought to be combined I can do that.
___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NetZuRt7XP1j32TW9qb:bqz35bi) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
> I would expect best-practices to be to have the PSI create a sub-directory for each extension so extensions can't modify the data of other extensions.

That's basically what I'm doing in this PR, but I'm putting it under `<name>_<id>/extensions/<extension_name>`, not `<name>_<id>/project/extensions/<extension_name>`.  Is that fine, or does everything, including extension data, need to live under `project`?  If it all does need to live under `project`, would Paratext be unhappy about extra subdirectories in a project directory that it didn't manage?  If so, I'd need to push things down a level (e.g., `<name>_<id>/project/project_data` and `<name>_<id>/project/extension_data`).
___
*[`c-sharp/Projects/LocalProjects.cs` line 15 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-Net7Uew9j5p7c91et6M:-NetYF6S0Z1-PK8j1Rw1:b-uocwsl) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/LocalProjects.cs#L15)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I would think this map should not exist. The projects should be put into the **ScrTextCollection** so the rest of ParatextData can find them.
</blockquote></details>

What would the rest of ParatextData do with them?  I'm definitely not saying you're wrong.  Just trying to understand this further.

I see there are a bunch of properties in `ScrTextCollection`that might not make sense on a machine without Paratext on it (e.g., a Linux host).  For example, there are a bunch of `*SettingsDirectory` values that are set.  Do you feel good about `ScrTextCollection` working as-is on machines without Paratext installed?
___
*[`c-sharp/Projects/LocalProjects.cs` line 127 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-Net6ogk1Hrlej632uP2:-Net_mjvAto1fCW3DKG6:b-k6pyoc) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/LocalProjects.cs#L127)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

You could have asked me. :stuck_out_tongue_winking_eye: 
**RegistrationInfo.DefaultUser** should be what you want.
</blockquote></details>

Thanks!  I'll make this change.

I don't think you were available when I was writing that particular line, so I put in a placeholder and a TODO.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeizA8b9B1XQw2pr-DS:-Net_zhS5-7cudnnD2MX:bty5nuu) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L39)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

A project Guid in Paratext is not a standard GUID. It is actually the hash of the first commit to the Mercurial repository. That is why **ScrText.Guid** is a **HexId** type. I would expect this to cause problems with this code.
</blockquote></details>

Regardless of how the bytes are conjured up, can a `HexId` be represented as a `GUID`?  If not we definitely should not call it a GUID since a GUID is a well known, specific type that has a normal formatting referenced in the code.  If it can be represented as a GUID internally but just has a different string form, then what string form would it be in so that we can parse it properly?
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 100 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetAqDz5f52szDTyprJ:-Netbase7LW8XKFyCOGr:b-fuuu1g) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L100)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I'm not sure how much we care at the moment, but this is not the correct implementation for getting the USFM of a single verse. It should be **ScrText.Parser.GetVerseUsfmText**. The call you have here will skip over non-verse text (e.g. footnotes, section heads, etc.).
</blockquote></details>

Thanks - I'll make the adjustments.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 172 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetG_op2WtPOM0C5VOa:-NetbhvkDUWvcLvejiCj:bttv0z4) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L172)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

It's probably fine for now, but long-term the writing of any project data should be inside a write lock.
</blockquote></details>

I can make the change here.  I assume you're talking about a general write lock, not the specific Paratext class, right?  This is just for extension data, so I wouldn't expect to use a Paratext lock in particular here.
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 29 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetDRWDE0eyovZEV5AD:-NetfxlyEtvsfVNJQBkf:b-gjkcmy) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L29)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I thought the whole point of the design of data providers in Platform.Bible was that we wouldn't need to do things like this. Why are methods like the generic **HandleRequest** below necessary? Did that nice-ness never make it to the C# side of things?
</blockquote></details>

We receive a message over the network with a name of some function to run and optionally some arguments to pass to the functions.  We *could* spend time doing some reflection gymnastics to locate methods and serialize to the right types, but that seems like it would take a lot more time and be more fragile than adding some switch statements or functions in maps to lookup.  In most cases this is taken care of by a single switch statement and some abstract methods that something can implement so they never see it, but for project data providers we don't know what all the functions will be up front.

I guess I don't know what "nice-ness" you mean exactly, but I'm assuming you're talking about the reflection approach.  If you mean something else, then I guess I need to hear more about what you're talking about.
___
*[`c-sharp/Projects/ProjectType.cs` line 6 at r2](https:/ [...]

2023-09-21 23:06 UTC, tjcouch-sil requested changes
> Reviewed 6 of 8 files at r3, 2 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 15 unresolved discussions (waiting on @FoolRunning and @lyonsil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NetqrIdE8Ry3OhX1wPi:bhs8fza) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

> I would expect best-practices to be to have the PSI create a sub-directory for each extension so extensions can't modify the data of other extensions.

That's basically what I'm doing in this PR, but I'm putting it under `<name>_<id>/extensions/<extension_name>`, not `<name>_<id>/project/extensions/<extension_name>`.  Is that fine, or does everything, including extension data, need to live under `project`?  If it all does need to live under `project`, would Paratext be unhappy about extra subdirectories in a project directory that it didn't manage?  If so, I'd need to push things down a level (e.g., `<name>_<id>/project/project_data` and `<name>_<id>/project/extension_data`).
</blockquote></details>

When Tim and I designed this, I suggested we make the `<name>_<id>` folder basically equal to the project folder in Paratext. However, that makes it so the metadata is harder to find unless we put it in the project folder (which shouldn't happen because that folder's contents are controlled by the PSI). We decided the PSI gets access to one folder, the `<name>_<id>/project` folder, and it gets to do whatever it wants in there. Clean, straight-forward, easy project folder access rules. We left the implementation details up to each PSI.

For the Paratext PSI, you could just consider the `<name>_<id>/project` folder basically equal to the Paratext project folder. There's a bunch of data in there that is core data in PT9 but is extension data in PB, so there is quite a bit of extension data mixed in with the core project data. If I understand correctly, PT9 plugins are generally recommended to put their data in some subfolder, so maybe new extension data could go in there. I think I prefer this way a bit since it matches well to how PT9 already does things and doesn't add extra subdirectories.

Or you could alternatively consider the `<name>_<id>/project/project_data` folder (or whatever you want to call it) basically equal to the Paratext project folder and put new extension data in `<name>_<id>/project/extension_data` like you mentioned.

The big idea is that the PSI is the only one who gets access to that folder, and it gets to do what it wants inside that one folder. We don't know what people will want to do with their data. It seems unhelpful to me to enforce a delineation in the file system that they might not want. I guess you could argue that they could just not put anything in the extension directory. But we have to give the PSI special access to these two folders, and now we are dictating that the effective project data can possibly be in two folders instead of all being in one.

This led me to consider again whether delineating between core project data and extension data was unnecessary. However, I think it still makes sense in that the project type determines a set of data relevant to the project data provider, then other data is considered extension data.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeizA8b9B1XQw2pr-DS:-NesNI865M9fuctAVJNp:b16y3i0) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L39)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Regardless of how the bytes are conjured up, can a `HexId` be represented as a `GUID`?  If not we definitely should not call it a GUID since a GUID is a well known, specific type that has a normal formatting referenced in the code.  If it can be represented as a GUID internally but just has a different string form, then what string form would it be in so that we can parse it properly?
</blockquote></details>

I may be looking in the wrong place, but I can only find strings without hyphens in the `Guid` property in `Settings.xml` for a number of projects I am seeing. I also found some that don't have a `Guid`... And one that has `TMSId` (whatever that means) with hyphens. And I found at least on some ERs that there isn't anything that looks similar to a guid anywhere in the `Settings.xml`... I'm confused. I am not familiar with constraints on project IDs. I expect that we do not need to parse the project IDs, but Tim can answer that better than me.

If we can't always find a guid-like thing for each project, what are we going to do when we can't find one??
___
*[`c-sharp/Projects/ProjectStorageInterpreter.cs` line 21 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetHF_uELcGNSqPHW1G:-NetzDS0CBGW_wU1nmbs:b-qhs5is) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectStorageInterpreter.cs#L21)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Probably not worth changing, but I would expect the C# code in Platform.Bible to only ever support one PSI implementation and one PDP implementation - the ones related to the existing Paratext project structure. I would expect everything else to not be written in C#.
</blockquote></details>

I could see us writing a PT9 format PSI and a Paratext.Bible format where we make the updates to data formats like splitting notes by book and such maybe... Though maybe that's unnecessary and we would just want to do the import/export step every time!


<!-- Sent from Reviewable.io -->

2023-09-22 14:19 UTC, FoolRunning requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 12 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`c-sharp/JsonUtils/ProjectMetadataConverter.cs` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/427#-NeddKXJ4r5Y4PmYssKf:-NexEuVc-oDTHCuVtaPp:b7wwl2q) ([raw file](https://github.com/paranext/paranext-core/blob/8841c4557cb7132f8057eed34e09206ae58b1c33/c-sharp/JsonUtils/ProjectMetadataConverter.cs#L50)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It could be, but I have been generally trying to keep JSON serialization code until `JsonUtils`.  I don't have a strong opinion on this.  I was trying to follow the general pattern that was already there, and it was kind of nice to have the main class just focus on the data fields and keep serialization/deserialization concerns separate.  If you thing they ought to be combined I can do that.
</blockquote></details>

I personally don't like extension methods on a class like this. I also don't like using extension methods when you could just add the method to the class in the first place. 
I'm fine with discussing this, but, personally, I feel it should either be moved to some static utils class or moved to **ProjectMetadata**.
___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-Nex82u_ERPhM9jYRKNZ:butxau9) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

When Tim and I designed this, I suggested we make the `<name>_<id>` folder basically equal to the project folder in Paratext. However, that makes it so the metadata is harder to find unless we put it in the project folder (which shouldn't happen because that folder's contents are controlled by the PSI). We decided the PSI gets access to one folder, the `<name>_<id>/project` folder, and it gets to do whatever it wants in there. Clean, straight-forward, easy project folder access rules. We left the implementation details up to each PSI.

For the Paratext PSI, you could just consider the `<name>_<id>/project` folder basically equal to the Paratext project folder. There's a bunch of data in there that is core data in PT9 but is extension data in PB, so there is quite a bit of extension data mixed in with the core project data. If I understand correctly, PT9 plugins are generally recommended to put their data in some subfolder, so maybe new extension data could go in there. I think I prefer this way a bit since it matches well to how PT9 already does things and doesn't add extra subdirectories.

Or you could alternatively consider the `<name>_<id>/project/project_data` folder (or whatever you want to call it) basically equal to the Paratext project folder and put new extension data in `<name>_<id>/project/extension_data` like you mentioned.

The big idea is that the PSI is the only one who gets access to that folder, and it gets to do what it wants inside that one folder. We don't know what people will want to do with their data. It seems unhelpful to me to enforce a delineation in the file system that they might not want. I guess you could argue that they could just not put anything in the extension directory. But we have to give the PSI special access to these two folders, and now we are dictating that the effective project data can possibly be in two folders instead of all being in one.

This led me to consider again whether delineating between core project data and extension data was unnecessary. However, I think it still makes sense in that the project type determines a set of data relevant to the project data provider, then other data is considered extension data.
</blockquote></details>

Also, for the purposes of Send/Receive (which I realize we're not going to worry about for a while), everything related to the project needs to be contained in a single directory (think of the project as a mini code repository). This includes any extension data related to the project.
___
*[`c-sharp/Projects/LocalProjects.cs` line 15 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-Net7Uew9j5p7c91et6M:-Nex4Jyi95H65TsM9vLG:bw9gqzw) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/LocalProjects.cs#L15)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

What would the rest of ParatextData do with them?  I'm definitely not saying you're wrong.  Just trying to understand this further.

I see there are a bunch of properties in `ScrTextCollection`that might not make sense on a machine without Paratext on it (e.g., a Linux host).  For example, there are a bunch of `*SettingsDirectory` values that are set.  Do you feel good about `ScrTextCollection` working as-is on machines without Paratext installed?
</blockquote></details>

**ScrTextCollection** needs to work for some parts of ParatextData to function properly - see uses of **ScrTextCollection** inside ParatextData. If any part of ParatextData needs a **ScrText**, it gets it via the **ScrTextCollection**. Even the **SettingsDirectory** needs to be set so that some needed files can be found. **ParatextData.Initialize** (called from **ParatextGlobals**) initializes the **ScrTextCollection** for Platform.Bible.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeizA8b9B1XQw2pr-DS:-Nex9Dj38mVMFzaS_bU7:b5qv8d9) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I may be looking in the wrong place, but I can only find strings without hyphens in the `Guid` property in `Settings.xml` for a number of projects I am seeing. I also found some that don't have a `Guid`... And one that has `TMSId` (whatever that means) with hyphens. And I found at least on some ERs that there isn't anything that looks similar to a guid anywhere in the `Settings.xml`... I'm confused. I am not familiar with constraints on project IDs. I expect that we do not need to parse the project IDs, but Tim can answer that better than me.

If we can't always find a guid-like thing for each project, what are we going to do when we can't find one??
</blockquote></details>

I'm not sure what projects you're looking at, but the Guid property in the Settings.xml files should look like ```<Guid>45eff14875b6fc356a3cadb5306d40c279deec25</Guid>``` It's basically a hexidecimal string. 
Yes, it's not technically a GUID and calling it a GUID is historical (way before my time). Maybe it was a GUID at one point.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 172 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetG_op2WtPOM0C5VOa:-NexAPYh3mhEVYSktf0E:b8hduxs) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L172)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I can make the change here.  I assume you're talking about a general write lock, not the specific Paratext class, right?  This is just for extension data, so I wouldn't expect to use a Paratext lock in particular here.
</blockquote></details>

I was meaning the Paratext write lock. During a S/R, the entire project is locked. Ideally, for this reason, it would be best to use the Paratext write locking in the C# code since the C# code has all the S/R code in it (unless we end up writing our own S/R system for Platform.Bible from scratch). We will prob [...]

2023-09-22 14:47 UTC, tjcouch-sil requested changes
> Reviewed 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 10 unresolved discussions (waiting on @FoolRunning and @lyonsil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NexG6W98vXjnCa4pe5C:b-qzcvvo) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Also, for the purposes of Send/Receive (which I realize we're not going to worry about for a while), everything related to the project needs to be contained in a single directory (think of the project as a mini code repository). This includes any extension data related to the project.
</blockquote></details>

Also note we decided the DPP would give us the project metadata (particularly relevant are storageType and projectType), so S/R would theoretically need to know each project's metadata.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeizA8b9B1XQw2pr-DS:-NexI5Yc0rK1IMm8l5Q5:bp0ihu6) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L39)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I'm not sure what projects you're looking at, but the Guid property in the Settings.xml files should look like ```<Guid>45eff14875b6fc356a3cadb5306d40c279deec25</Guid>``` It's basically a hexidecimal string. 
Yes, it's not technically a GUID and calling it a GUID is historical (way before my time). Maybe it was a GUID at one point.
</blockquote></details>

Sounds like we need to avoid parsing the project ID as a guid, then, unfortunately.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-Nej-JQT7JOEfFufGwZE:-NexC8qv473Lpa-laa1U:boa2wd) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L57)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It would be significantly disruptive to convert this method to async because of all the places that get touched.  If you change this to `async`, you probably change a bunch of other interfaces and methods at the same time.  Nearly every method becomes `async`.  I started down that path a week or two ago and backed out.

At this point in the code, using `async` doesn't buy us a lot in practice.  The really important place to use `async` is inside of the message transport (i.e., `PapiClient.cs`).  We don't want to block handling an incoming message because we are already handling another one in front of it.  Once the tasks for incoming messages have been scheduled (see `HandleIncomingMessages()` in `PapiClient.cs`), they are able to run on different threads in the thread pool.  (The documented description of `Task.Run()` is `Queues the specified work to run on the ThreadPool and returns a task or [Task<TResult>](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1?view=net-7.0) handle for that work.`.)

In JavaScript/TypeScript, the runtime engine really has a single thread, so `async` is needed for [cooperative multitasking](https://en.wikipedia.org/wiki/Cooperative_multitasking).  In .NET, the runtime uses true [multithreading](https://en.wikipedia.org/wiki/Multithreading_(computer_architecture).  .NET `Task` objects make the situation fuzzier because it adds the ability for programs to use cooperative multitasking and multithreading both at the same time.

Technically it would slightly more performant to do everything `async` so that fewer threads and context switches would be needed, but from previous testing I've already seen that the existing architecture can handle more than a thousand requests per second, and that's way faster than we need.  Also, writing the `async` code is more tedious, so I didn't really think spending the time on it was important vs. all the other stuff we have to get done for the project.  Basically I'm prioritizing easier code to write/understand over a small and I think unneeded performance benefit.
</blockquote></details>

Ah right, I forgot C# has actual multithreading haha thanks for the reminder. That definitely changes things. I do wonder about C# code calling other C# code and getting blocked, but maybe we don't care. I dunno. I wouldn't be concerned if this didn't affect extension api. However, it feels weird and incongruous to me to expose a nearly 100% async extension api in JS but expose a mostly synchronous extension api in C#. What are your thoughts on this discrepancy? @FoolRunning any thoughts?

If this conversation lasts longer than other conversations here, we can just leave it for sure. Don't want to hold up the work for this.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 161 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NexEvJk5yBIGLXMcDVf:-NexEvJk5yBIGLXMcDVg:brs6fa1) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L161)):*
> ```Smalltalk
>     public override ResponseToRequest SetExtensionData(ProjectDataScope scope, string data)
>     {
>         if (scope.ExtensionName == null)
> ```

Should these two null checks go in or be added to `GetExtensionStream`? Just a quick thought; feel free to change or ignore without a comment.
___
*[`c-sharp/Projects/ProjectType.cs` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejTVtq-BCvoRNA5JIi:-NexJe-t8vit47JrQLTV:b-h89ho4) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ProjectType.cs#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I've been in discussions (along with TJ and I thought you, too) where C#-based extensions (i.e., some sort of plug-ins we would need to load) have been kicked around as a possibility.  I don't think it's a plan of record yet.
</blockquote></details>

When I said "flexible enums", I was thinking about `papi-shared-types` and how extensions can add to our interfaces with their extension apis. Maybe we don't really care enough in C#. 

I think we probably should have a conversation about C#-based extensions as it sounds like we have been thinking two different things about them.
___
*[`c-sharp/Projects/RawDirectoryProjectStreamManager.cs` line 67 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejUKVbDrG5GrrNhPa8:-NexKKqMBV7HjQ1qfAlH:b-uggw92) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/RawDirectoryProjectStreamManager.cs#L67)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If something else (Paratext, Clear, etc.) might need tight ownership over everything in the `project` subdirectory, then where are PSIs supposed to store extension data?  I guess we could force it to go own level down further (e.g., `<name>_<id>/project/real_project_data` and `<name>_<id>/project/extension_data`), but why?  What are you worried about PSIs doing?
</blockquote></details>

This goes along with the conversation we're having above. The design was that we would have read/write exclusivity on the `<name>_<id>` folder except the `<name>_<id>/project` folder, and the PSI gets free reign in the `project` subfolder. PSIs can do whatever they want inside that `project` folder. So yes, the idea is to force it to go down one level further.

If we did every [...]

2023-09-22 15:56 UTC, FoolRunning reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 10 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-Nej-JQT7JOEfFufGwZE:-NexZsUj6WYET_rjVc6u:bmzfyyq) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L57)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ah right, I forgot C# has actual multithreading haha thanks for the reminder. That definitely changes things. I do wonder about C# code calling other C# code and getting blocked, but maybe we don't care. I dunno. I wouldn't be concerned if this didn't affect extension api. However, it feels weird and incongruous to me to expose a nearly 100% async extension api in JS but expose a mostly synchronous extension api in C#. What are your thoughts on this discrepancy? @FoolRunning any thoughts?

If this conversation lasts longer than other conversations here, we can just leave it for sure. Don't want to hold up the work for this.
</blockquote></details>

As Matt stated, since the message transport and handling are async, I think that means that multiple requests can be handled at once already. Each request is (possibly) handled on a separate thread and assuming the JS code is awaiting, then it shouldn't matter how long the C# code takes to process that message (within reason, probably). So, I think having these methods be synchronous is perfectly fine.


<!-- Sent from Reviewable.io -->

2023-09-22 20:18 UTC, tjcouch-sil requested changes
> Reviewed 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 13 unresolved discussions (waiting on @FoolRunning and @lyonsil)

___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 29 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyPn7f-ZdeQCzoOeKA:-NeyPn7f-ZdeQCzoOeKB:b-kdxjrr) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L29)):*
> ```Smalltalk
>     protected Dictionary<string, Func<string, ResponseToRequest>> Getters { get; } = new();
>     protected Dictionary<string, Func<string, string, ResponseToRequest>> Setters { get; } = new();
>     protected Dictionary<string, Func<string, ResponseToRequest>> Subscribers { get; } = new();
> ```

I think we could probably derive `Subscribers` based on the setters and getters. It should just be a method that runs `PapiClient.RegisterEventHandler` for the event associated with that data type, right? So I don't think DataProvider inheritors would necessarily need to create their own subscribe methods.

A simpler approach could be to assume the data type exists on this data provider when you try to subscribe and not worry about coordinating between setters/getters and subscribers ;)

An even simpler approach would be to forget C#-side subscribers for now and put a TODO and a new issue :)
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 50 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyPQo_89VrLp6S1vAR:-NeyPQo_89VrLp6S1vAS:b-6fpkyi) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L50)):*
> ```Smalltalk
>     }
> 
>     protected override ResponseToRequest HandleRequest(string functionName, JsonArray args)
> ```

I'm now realizing I think this implementation of `HandleRequest` should probably be moved up to `DataProvider.cs` since this is more of a core functionality of data providers rather than specific to project data providers. Then people could overwrite it and put whatever extra functions they want then call `base.HandleRequest(...)` otherwise. It is certainly arguable that this is just one way to implement getters and setters, but I think this is probably more user-friendly than making people write their own `HandleRequest` from scratch.
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 61 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyVsfx3zcugWvtC95k:-NeyVsfx3zcugWvtC95l:bclg8za) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L61)):*
> ```Smalltalk
> 
>             if (functionName.StartsWith("set"))
>                 return Setters[functionName](args[0]!.ToJsonString(), args[1]!.ToJsonString());
> ```

I could be missing something, but I don't think I see `SendDataUpdateEvent` getting run anywhere with these setters. Think here would be a good place to run it? Like on the TS side, you could take the return from the setter and send that out. Or document carefully and make sure you explicitly warn people that they need to send that event themselves on every set function in their data providers. (I noticed this because it seems `ParatextProjectDataProvider.cs` doesn't send out events, so you could do it automatically here similar to TS or do it manually in each setter.)

I suppose another option would be to push this off to #362.


<!-- Sent from Reviewable.io -->

2023-09-22 20:41 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: 26 of 30 files reviewed, 13 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/JsonUtils/ProjectMetadataConverter.cs` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/427#-NeddKXJ4r5Y4PmYssKf:-NexeUzLAyFrCA6QLPCM:bcvg4zq) ([raw file](https://github.com/paranext/paranext-core/blob/8841c4557cb7132f8057eed34e09206ae58b1c33/c-sharp/JsonUtils/ProjectMetadataConverter.cs#L50)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I personally don't like extension methods on a class like this. I also don't like using extension methods when you could just add the method to the class in the first place. 
I'm fine with discussing this, but, personally, I feel it should either be moved to some static utils class or moved to **ProjectMetadata**.
</blockquote></details>

Ok - changed the extension method to a static util class method.
___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NeyWhVC61zbew6CqS2J:b-n9qq2k) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Also note we decided the DPP would give us the project metadata (particularly relevant are storageType and projectType), so S/R would theoretically need to know each project's metadata.
</blockquote></details>

At this point, the structure for paratext projects is:
```
<user_home_dir>/.platform.bible/projects/<name>_<id>/project/...
    > meta.json (file for all project and project storage types)
    > paratext (dir for paratext project types)
    > extensions/<extension_name> (dirs for paratext project types, and others presumably could follow the same pattern)
```

So everything will live under the `project` folder except the `meta.json` file.  I don't know what else might live alongside `meta.json` eventually, but there is a place for it now.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 100 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetAqDz5f52szDTyprJ:-Ney6yczAJQLOKyGjVV0:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L100)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Thanks - I'll make the adjustments.
</blockquote></details>

Done
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 161 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NexEvJk5yBIGLXMcDVf:-NeyXoe90xokPvsG9Rmd:bq5gqoo) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L161)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should these two null checks go in or be added to `GetExtensionStream`? Just a quick thought; feel free to change or ignore without a comment.
</blockquote></details>

I didn't do that because that doesn't have a `ResponseToReqyest` return value.
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 29 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyPn7f-ZdeQCzoOeKA:-NeyYA5s5r_q5OfH4JvE:bhf59qt) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L29)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think we could probably derive `Subscribers` based on the setters and getters. It should just be a method that runs `PapiClient.RegisterEventHandler` for the event associated with that data type, right? So I don't think DataProvider inheritors would necessarily need to create their own subscribe methods.

A simpler approach could be to assume the data type exists on this data provider when you try to subscribe and not worry about coordinating between setters/getters and subscribers ;)

An even simpler approach would be to forget C#-side subscribers for now and put a TODO and a new issue :)
</blockquote></details>

These 3 collections are just there to look up what methods to run when a function call comes in.  Nothing actually forces an implementer to add anything to them.  I can have a getter without a setter or both without a subscriber.  So the "even simpler approach" is effectively in place with this PR.  

Because subscribers might want to filter their notifications based on the design, I'm not sure if this can be simplified as you suggest.  If it can, we can always add that later, and it would only cause a minimal change to this code.  I think we can leave this as-is for now and cross the bridge of what to do about subscribers if/when it becomes important.
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 50 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyPQo_89VrLp6S1vAR:-NeyZRbU8juQHP31WhCm:b-53iy84) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L50)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm now realizing I think this implementation of `HandleRequest` should probably be moved up to `DataProvider.cs` since this is more of a core functionality of data providers rather than specific to project data providers. Then people could overwrite it and put whatever extra functions they want then call `base.HandleRequest(...)` otherwise. It is certainly arguable that this is just one way to implement getters and setters, but I think this is probably more user-friendly than making people write their own `HandleRequest` from scratch.
</blockquote></details>

I guess I disagree with you on this.  For simple data providers, this function can be implemented as a very straightforward switch statement (see `TimeDataProvider.cs` as an example).  Making people call base classes when their code doesn't handle something means they have to really understand the base case, too.
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 61 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyVsfx3zcugWvtC95k:-NeyaslI7xvMHhMqNFc9:b602c5t) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L61)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I could be missing something, but I don't think I see `SendDataUpdateEvent` getting run anywhere with these setters. Think here would be a good place to run it? Like on the TS side, you could take the return from the setter and send that out. Or document carefully and make sure you explicitly warn people that they need to send that event themselves on every set function in their data providers. (I noticed this because it seems `ParatextProjectDataProvider.cs` doesn't send out events, so you could do it automatically here similar to TS or do it manually in each setter.)

I suppose another option would be to push this off to #362.
</blockquote></details>

How do you know what the data scope is at this level?  I think the setter is what has that knowledge.  It's probably fair that the setters I have aren't calling that event either, but I don't know what we want to put there anyway.
___
*[`c-sharp/Projects/ProjectStorageInterpreter.cs` line 21 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetHF_uELcGNSqPHW1G:-NeyVCRA6TZ-CQPsuE5J:bua9qjy) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectStorageInterpreter.cs#L21)):*
<details><summary><i>Previous [...]

2023-09-22 20:43 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: 26 of 30 files reviewed, 13 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NeycExRA6RR1ZXJ0xRw:b-d016ql) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

At this point, the structure for paratext projects is:
```
<user_home_dir>/.platform.bible/projects/<name>_<id>/project/...
    > meta.json (file for all project and project storage types)
    > paratext (dir for paratext project types)
    > extensions/<extension_name> (dirs for paratext project types, and others presumably could follow the same pattern)
```

So everything will live under the `project` folder except the `meta.json` file.  I don't know what else might live alongside `meta.json` eventually, but there is a place for it now.
</blockquote></details>

Whoops, `meta.json` is on the same level as `project`.  Apologies for my last comments.  The other two are subdirectories of `project`.


<!-- Sent from Reviewable.io -->

2023-09-22 21:12 UTC, FoolRunning requested changes
> Reviewed 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 11 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`c-sharp/JsonUtils/ProjectMetadataConverter.cs` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/427#-NeddKXJ4r5Y4PmYssKf:-NeyfilPEkIYJg5wn7YA:b-n5bry1) ([raw file](https://github.com/paranext/paranext-core/blob/8841c4557cb7132f8057eed34e09206ae58b1c33/c-sharp/JsonUtils/ProjectMetadataConverter.cs#L50)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ok - changed the extension method to a static util class method.
</blockquote></details>

I'm personally not happy with this as a "fix", but I don't think it's worth holding the PR up for this.
___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NeygJIoBEj7daFQn0tI:bpj648d) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Whoops, `meta.json` is on the same level as `project`.  Apologies for my last comments.  The other two are subdirectories of `project`.
</blockquote></details>

Assuming you meant to show it as:
```
<user_home_dir>/.platform.bible/projects/<name>_<id>/...
    > meta.json (file for all project and project storage types)
    > project/...
        > paratext (dir for paratext project types)
        > extensions/<extension_name> (dirs for paratext project types, and others presumably could follow the same pattern)
```
Then I think that's fine.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeizA8b9B1XQw2pr-DS:-NeyheiEAO97yszhUc-T:bbmztt9) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Sounds like we need to avoid parsing the project ID as a guid, then, unfortunately.
</blockquote></details>

Note that we can use the **HexId** class inside this code (it's in ParatextData).
___
*[`c-sharp/Projects/RawDirectoryProjectStreamManager.cs` line 18 at r7](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyiCNaA048Gs25aWuY:-NeyiCNaA048Gs25aWuZ:bl3vmx0) ([raw file](https://github.com/paranext/paranext-core/blob/a0f4d2e4a2b5e1747122c2cc92ed65148db05fb3/c-sharp/Projects/RawDirectoryProjectStreamManager.cs#L18)):*
> ```Smalltalk
>     {
>         _projectDetails = projectDetails;
>         _writableRootDir = Path.Join(projectDetails.Directory, "project");
> ```

This seems wrong to me. I would expect **projectDetails.Directory** to have the "project" directory already, or "project" should be "paratext" (i.e. **LocalProject.PARATEXT_DATA_SUBDIRECTORY**) per your description above.


<!-- Sent from Reviewable.io -->

2023-09-22 21:13 UTC, tjcouch-sil reviewed
> Reviewed 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 10 unresolved discussions (waiting on @FoolRunning and @lyonsil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-Neyfr7BCzEw9pP0U3jO:b8y0h9n) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Whoops, `meta.json` is on the same level as `project`.  Apologies for my last comments.  The other two are subdirectories of `project`.
</blockquote></details>

Looks good. Thank you! I wonder if, in the future (no need to beat the dead horse here imo), it would make sense to share Paratext 9's plugin data folder (if that's a thing; I think I remember it being mentioned) with PB extensions. That's something I'd prefer Tim to think about, though, since I really don't know enough to be able to decide. Could be that we just bake in specific PB extensions to grab stuff out of the PT9 plugin folder as needed similar to how we'll probably do BT renderings.
___
*[`c-sharp/Projects/ProjectType.cs` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejTVtq-BCvoRNA5JIi:-Neyht5z0XLyMxyR9PBJ:b-xcny9h) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ProjectType.cs#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

> I was thinking about `papi-shared-types` and how extensions can add to our interfaces with their extension apis
Our C# code as of this moment only provides data, not consumes it.  We don't have a way to request a network object in C#, actually.  (I punted on this until we rework the network messages because it's going to be messy to do it in C# with the messages as they are now.)

Given that we only publish and don't produce, I don't think coming up with a similar approach as what we have in TypeScript makes sense here.  A publisher can just write a class the publishes the expected types with the expected function names.  "Expected" will presumably be defined in TypeScript which C# can't access anyway.

> I think we probably should have a conversation about C#-based extensions as it sounds like we have been thinking two different things about them.
This probably wouldn't hurt, but I'm going to consider it outside the scope of this PR unless you think it really needs to block it.  We haven't really put a lot of thought into how we might load in other C# add-ons, and a lot of places will need to be touched if/when that happens.
</blockquote></details>

I absolutely agree that the discussion about C# extensions is beyond the scope of this PR and issue :)
___
*[`c-sharp/Projects/RawDirectoryProjectStreamManager.cs` line 67 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NejUKVbDrG5GrrNhPa8:-NeyiwW7EzU7-t3vHvUX:byqzz02) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/RawDirectoryProjectStreamManager.cs#L67)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I moved things down a level, so everything is in the `project` directory now.  Paratext projects will have a `paratext` subdirectory that the `ScrText` object owns.
</blockquote></details>

Perfect. Thank you!
___
*[`c-sharp/Projects/RawDirectoryProjectStreamManager.cs` line 18 at r7](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyiBhV-ot5RZIp8ZWa:-NeyiBhV-ot5RZIp8ZWb:b-zexf3j) ([raw file](https://github.com/paranext/paranext-core/blob/a0f4d2e4a2b5e1747122c2cc92ed65148db05fb3/c-sharp/Projects/RawDirectoryProjectStreamManager.cs#L18)):*
> ```Smalltalk
>     {
>         _projectDetails = projectDetails;
>         _writableRootDir = Path.Join(projectDetails.Directory, "project");
> ```

Can `"project"` here be replaced with `LocalProjects.PROJECT_SUBDIRECTORY` (or wherever you'd want to make this string a public const)? Not a big deal; it can certainly wait (maybe with an issue created so we don't lose track of it) if there end up being no further code changes.


<!-- Sent from Reviewable.io -->

2023-09-25 00:33 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 8 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NezTYsEEchAI0f_2ex-:bvnqyas) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
> Assuming you meant to show it as:

Yes, that is what I meant.  Sorry for the mix-up.

> would make sense to share Paratext 9's plugin data folder

In my mind, when we have a PSI that is sharing project data owned by someone else, all that data belongs in the designated subfolder (i.e., `paratext` in this case).  The PSI really shouldn't be touching the directory contents owned by Paratext or any other application.
___
*[`c-sharp/Projects/LocalProjects.cs` line 15 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-Net7Uew9j5p7c91et6M:-NezXRXDBYRuey2rLt5i:b-6x3pgz) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/LocalProjects.cs#L15)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

**ScrTextCollection** needs to work for some parts of ParatextData to function properly - see uses of **ScrTextCollection** inside ParatextData. If any part of ParatextData needs a **ScrText**, it gets it via the **ScrTextCollection**. Even the **SettingsDirectory** needs to be set so that some needed files can be found. **ParatextData.Initialize** (called from **ParatextGlobals**) initializes the **ScrTextCollection** for Platform.Bible.
</blockquote></details>

Done - using `ScrTextCollection` now.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeizA8b9B1XQw2pr-DS:-NezdPNL94IRBeow8S8f:b-5wrxfw) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L39)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Note that we can use the **HexId** class inside this code (it's in ParatextData).
</blockquote></details>

I removed all use of `Guid` and switched to make the IDs strings.  I don't want to lock in that all projects must have `HexId` project IDs for when we start to have non-Paratext projects, but this doesn't preclude use of `HexId` values, either.  I did add a restriction that the string IDs have to be case insensitive so that we don't trip over capital letters vs lower case.

I don't mind that these aren't GUIDs, but I would like to stick with the term "GUID" to only apply when something aligns with the [generally understood definition of the term](https://en.wikipedia.org/wiki/Universally_unique_identifier).
___
*[`c-sharp/Projects/RawDirectoryProjectStreamManager.cs` line 18 at r7](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyiCNaA048Gs25aWuY:-NezU9_o8Er59g4EA9Mq:bqoces8) ([raw file](https://github.com/paranext/paranext-core/blob/a0f4d2e4a2b5e1747122c2cc92ed65148db05fb3/c-sharp/Projects/RawDirectoryProjectStreamManager.cs#L18)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

This seems wrong to me. I would expect **projectDetails.Directory** to have the "project" directory already, or "project" should be "paratext" (i.e. **LocalProject.PARATEXT_DATA_SUBDIRECTORY**) per your description above.
</blockquote></details>

I am renaming `ProjectDetails.Directory` to `ProjectDetails.HomeDirectory` to try to help distinguish.  Having a subdirectory named `project` inside of a directory that contains data for a project makes naming tricky.  I'm hoping the concept of a "project home directory" helps this make more sense.

For purposes of this particular class, I still like the name `_writableRootDir` as this class isn't permitting writing to anything at a higher level, but it is permitted to write at a lower level.  In that case of Paratext projects, I wouldn't expect the PSI to be accessing anything in the `paratext` subdirectory as the `ScrText` object owns that directory.  For Paratext projects, this class is probably only going to be used for accessing the `extensions` directory underneath `<project home dir>/project`.  I suppose it's possible that we end up with a need to write directly into the `paratext` subdirectory, and this would allow it if that happens, but I hope that isn't the case.
___
*[`c-sharp/Projects/RawDirectoryProjectStreamManager.cs` line 18 at r7](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyiBhV-ot5RZIp8ZWa:-NezVGIf0pwh92FCVYHn:bz4ysun) ([raw file](https://github.com/paranext/paranext-core/blob/a0f4d2e4a2b5e1747122c2cc92ed65148db05fb3/c-sharp/Projects/RawDirectoryProjectStreamManager.cs#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Can `"project"` here be replaced with `LocalProjects.PROJECT_SUBDIRECTORY` (or wherever you'd want to make this string a public const)? Not a big deal; it can certainly wait (maybe with an issue created so we don't lose track of it) if there end up being no further code changes.
</blockquote></details>

This class isn't intending to be dependent on `LocalProjects` or vice versa, so I would prefer not to do that.  I also don't think creating a ticket to decide where the string "project" should live is a great use of tickets, either.  If/when we need to refactor this code it can be dealt with as appropriate.


<!-- Sent from Reviewable.io -->

2023-09-25 13:48 UTC, FoolRunning reviewed
> Reviewed 12 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-09-25 17:17 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 4 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 172 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetG_op2WtPOM0C5VOa:-NfCKloQ4eAuy7ew2WCT:b-6xskcw) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L172)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I was meaning the Paratext write lock. During a S/R, the entire project is locked. Ideally, for this reason, it would be best to use the Paratext write locking in the C# code since the C# code has all the S/R code in it (unless we end up writing our own S/R system for Platform.Bible from scratch). We will probably eventually also need a write lock for Platform.Bible, but I feel that both write lock systems probably aren't really needed until we start implementing S/R.
</blockquote></details>

Moved this into a Paratext write lock
___
*[`c-sharp/Projects/RawDirectoryProjectStreamManager.cs` line 74 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NetJQwiDJcDuwbCOPg5:-NfCKqEGEjNccJq8zxiW:b-53a2mg) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/RawDirectoryProjectStreamManager.cs#L74)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Anything owned by the project (including extension data) should probably go through the FileManager. The **FileManager** keeps track of file changes and fires events accordingly. However, it seems like the even is only used in Paratext right now, so maybe it's not as important as I first thought. On the other hand, it is also nice to have all project file access go through a common abstracted file system in case we need to change something in the future.
</blockquote></details>

I'm going to punt on this for now since it doesn't seem to add anything, and if we need to make adjustments to how we handle extension data file handling it's easier to not have to worry about touching Paratext.Data classes.


<!-- Sent from Reviewable.io -->

2023-09-25 17:37 UTC, FoolRunning approved these changes
> Reviewed 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-09-25 17:37 UTC, FoolRunning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427#-:-NfCPdhP4haPmLLTAiHH:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-09-25 17:38 UTC, FoolRunning submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-09-25 18:44 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: 32 of 33 files reviewed, 3 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`src/main/main.ts` line 326 at r1](https://reviewable.io/reviews/paranext/paranext-core/427#-NedOX4p8AAqML4Sf3PJ:-NfCdsedCGQ4LRaL1yKY:bdiae0v) ([raw file](https://github.com/paranext/paranext-core/blob/8841c4557cb7132f8057eed34e09206ae58b1c33/src/main/main.ts#L326)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'd recommend copying the WEB into the `~/.platform.bible/projects` folder. You could do it so you don't need to tweak the usfm data provider - you'd have to create a `meta.json` programmatically instead of just copying the modified WEB stuff from the assets (including a `meta.json` you put in there). Either way.
</blockquote></details>

Since the `.platform.bible`directory isn't part of the repo and we don't have a clear way for how to populate data in that place by default for devs, I just commented out this code for now and added instructions for how to test in the short term.  I'm sure we'll want to adjust this later, and I thought this would be enough breadcrumbs for the time being.


<!-- Sent from Reviewable.io -->

2023-09-25 18:57 UTC, FoolRunning approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-09-25 19:43 UTC, tjcouch-sil requested changes
> Reviewed 8 of 12 files at r8, 8 of 9 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NfCfOA-DsDqGTEbE1Xq:bsucl02) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
I think I didn't explain well enough. Paratext 9 has a subfolder inside each project folder that PT9 plugins are recommended to put their project-related data in.

I'm suggesting we make it so the PSI puts extension project data in the same project subfolder as PT9 did. We are essentially using PT9's project file structure for everything else, so it seems to make sense to do the same for the extension (aka plugin) data too. For example, one day, we will change things so project notes are split up differently than how they are now in the PT9 file structure. That new split-up will be part of a new PB-style file structure. But we are just using the file structure of PT9 right now.

I think we also benefit from this strategy by removing the need for subfolders of the `project` folder. The `project` folder is now a PT9-file-structure project folder.

I asked Tim his thoughts, and he said it made sense so Paratext 9 plugins could still find their data. He said the following about the plugin project data folders:

> Projects have a **pluginData** folder which contains folders for the plugins. Unfortunately, because of the way plugin unique identifiers were defined in Paratext, it usually looks double-nested (e.g. Transcelerator's directory is `{project}\pluginData\Transcelerator\Transcelerator`).

I think making this change would be a benefit to us, but it doesn't matter enough to change this PR in my opinion unless you really want to do it now. I'd say let's make an issue unless you want to go ahead and do it now.
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 29 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyPn7f-ZdeQCzoOeKA:-NfCm0BGDo4pnVhbNmgP:bwjeqhg) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L29)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

These 3 collections are just there to look up what methods to run when a function call comes in.  Nothing actually forces an implementer to add anything to them.  I can have a getter without a setter or both without a subscriber.  So the "even simpler approach" is effectively in place with this PR.  

Because subscribers might want to filter their notifications based on the design, I'm not sure if this can be simplified as you suggest.  If it can, we can always add that later, and it would only cause a minimal change to this code.  I think we can leave this as-is for now and cross the bridge of what to do about subscribers if/when it becomes important.
</blockquote></details>

New issue for this and related things #438
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 61 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyVsfx3zcugWvtC95k:-NfCqnvq-8iCnVvpdG_3:bis14hh) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L61)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

How do you know what the data scope is at this level?  I think the setter is what has that knowledge.  It's probably fair that the setters I have aren't calling that event either, but I don't know what we want to put there anyway.
</blockquote></details>

I believe we discussed that you will update documentation to emphasize that the `SendDataUpdateEvent` must be called in `Set` methods in order for updates to be pushed out and will update the corresponding `Set` methods in `ParatextProjectDataProvider.cs`, right? Otherwise, I don't think the data will get pushed to subscribers.
___
*[`c-sharp/Projects/RawDirectoryProjectStreamManager.cs` line 18 at r7](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyiBhV-ot5RZIp8ZWa:-NfCnWVc11BZ_IKRhA85:b-lez3vt) ([raw file](https://github.com/paranext/paranext-core/blob/a0f4d2e4a2b5e1747122c2cc92ed65148db05fb3/c-sharp/Projects/RawDirectoryProjectStreamManager.cs#L18)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This class isn't intending to be dependent on `LocalProjects` or vice versa, so I would prefer not to do that.  I also don't think creating a ticket to decide where the string "project" should live is a great use of tickets, either.  If/when we need to refactor this code it can be dealt with as appropriate.
</blockquote></details>

Is there any situation in which the "project" subfolder would change in one of these two places but not in the other? In my mind, they seem like they are the same thing, so I want them to come from the same const and not be two independent strings. Otherwise, if we ever changed the subfolder, we would have to find both places to change it. I don't understand why not use a const in both places - maybe it can come from a more neutral file so these two files don't have dependency on each other since that is a concern (I am interested in understanding why it is a concern). Or if a neutral third file doesn't work for some reason, what about at least making a comment in both places that mention they are linked? Does that solve your concerns?
___
*[`src/main/main.ts` line 326 at r1](https://reviewable.io/reviews/paranext/paranext-core/427#-NedOX4p8AAqML4Sf3PJ:-NfCpi8DDgOolASxbt3J:bwacmt5) ([raw file](https://github.com/paranext/paranext-core/blob/8841c4557cb7132f8057eed34e09206ae58b1c33/src/main/main.ts#L326)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Since the `.platform.bible`directory isn't part of the repo and we don't have a clear way for how to populate data in that place by default for devs, I just commented out this code for now and added instructions for how to test in the short term.  I'm sure we'll want to adjust this later, and I thought this would be enough breadcrumbs for the time being.
</blockquote></details>

Issue #440
___
*[`src/shared/models/project-data-provider.model.ts` line 6 at r10](https://reviewable.io/reviews/paranext/paranext-core/427#-NfCpubWAavVmOIeHFGv:-NfCpubWAavVmOIeHFGw:bi64rv3) ([raw file](https://github.com/paranext/paranext-core/blob/d1549149d12af2fd27e8689a15b382e72b4873bc/src/shared/models/project-data-provider.model.ts#L6)):*
> ```XML
> export type ExtensionDataScope = {
>   extensionName: string;
>   dataQualifier: string;
> ```

I am rather confused by these property names, though I think I can piece together that they are the extension calling for data and what kind of data it's asking for (not the same as a selector, which confused me at first). Would you mind adding comments explaining what they are?


<!-- Sent from Reviewable.io -->

2023-09-25 21:47 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: 28 of 33 files reviewed, 2 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 26 at r2](https://reviewable.io/reviews/paranext/paranext-core/427#-NeimxEm8oBaU8OILd7S:-NfCte8RBmRW7az8O99o:b-3j6ayf) ([raw file](https://github.com/paranext/paranext-core/blob/c9c4cb3d985d428f7e36b36ae03e0308efb34060/c-sharp/Projects/LocalProjects.cs#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think I didn't explain well enough. Paratext 9 has a subfolder inside each project folder that PT9 plugins are recommended to put their project-related data in.

I'm suggesting we make it so the PSI puts extension project data in the same project subfolder as PT9 did. We are essentially using PT9's project file structure for everything else, so it seems to make sense to do the same for the extension (aka plugin) data too. For example, one day, we will change things so project notes are split up differently than how they are now in the PT9 file structure. That new split-up will be part of a new PB-style file structure. But we are just using the file structure of PT9 right now.

I think we also benefit from this strategy by removing the need for subfolders of the `project` folder. The `project` folder is now a PT9-file-structure project folder.

I asked Tim his thoughts, and he said it made sense so Paratext 9 plugins could still find their data. He said the following about the plugin project data folders:

> Projects have a **pluginData** folder which contains folders for the plugins. Unfortunately, because of the way plugin unique identifiers were defined in Paratext, it usually looks double-nested (e.g. Transcelerator's directory is `{project}\pluginData\Transcelerator\Transcelerator`).

I think making this change would be a benefit to us, but it doesn't matter enough to change this PR in my opinion unless you really want to do it now. I'd say let's make an issue unless you want to go ahead and do it now.
</blockquote></details>

https://github.com/paranext/paranext-core/issues/441
___
*[`c-sharp/Projects/ProjectDataProvider.cs` line 61 at r5](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyVsfx3zcugWvtC95k:-NfDFCao55lu0msvKcht:b-hx4cjx) ([raw file](https://github.com/paranext/paranext-core/blob/03f7853f1ec4fe590a8a555638b96dea5d871e43/c-sharp/Projects/ProjectDataProvider.cs#L61)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe we discussed that you will update documentation to emphasize that the `SendDataUpdateEvent` must be called in `Set` methods in order for updates to be pushed out and will update the corresponding `Set` methods in `ParatextProjectDataProvider.cs`, right? Otherwise, I don't think the data will get pushed to subscribers.
</blockquote></details>

Just pushed a commit that sends out the data update events for project data updates.
___
*[`c-sharp/Projects/RawDirectoryProjectStreamManager.cs` line 18 at r7](https://reviewable.io/reviews/paranext/paranext-core/427#-NeyiBhV-ot5RZIp8ZWa:-NfDFVWf5Oo5x4koMS3f:b-y4kgou) ([raw file](https://github.com/paranext/paranext-core/blob/a0f4d2e4a2b5e1747122c2cc92ed65148db05fb3/c-sharp/Projects/RawDirectoryProjectStreamManager.cs#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is there any situation in which the "project" subfolder would change in one of these two places but not in the other? In my mind, they seem like they are the same thing, so I want them to come from the same const and not be two independent strings. Otherwise, if we ever changed the subfolder, we would have to find both places to change it. I don't understand why not use a const in both places - maybe it can come from a more neutral file so these two files don't have dependency on each other since that is a concern (I am interested in understanding why it is a concern). Or if a neutral third file doesn't work for some reason, what about at least making a comment in both places that mention they are linked? Does that solve your concerns?
</blockquote></details>

My concern is that I don't want to imply a dependency of one on the other for such a trivial thing, and what/how/where projects live in the file system has been in a flux a bit during this PR.  It seems plausible to me that this whole section of code could be revamped as we make more decisions, and in my mind it's more important for relationships between these classes to be clear than make sure the word "project" isn't used twice.
___
*[`src/shared/models/project-data-provider.model.ts` line 6 at r10](https://reviewable.io/reviews/paranext/paranext-core/427#-NfCpubWAavVmOIeHFGv:-NfDIrUBAHZhS4-e0YnP:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/d1549149d12af2fd27e8689a15b382e72b4873bc/src/shared/models/project-data-provider.model.ts#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I am rather confused by these property names, though I think I can piece together that they are the extension calling for data and what kind of data it's asking for (not the same as a selector, which confused me at first). Would you mind adding comments explaining what they are?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-25 22:03 UTC, tjcouch-sil requested changes
> Reviewed 3 of 4 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: 32 of 33 files reviewed, 2 unresolved discussions (waiting on @FoolRunning and @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 136 at r11](https://reviewable.io/reviews/paranext/paranext-core/427#-NfDIi1xBJTLrqnV6U0f:-NfDIi1xBJTLrqnV6U0g:bpcft0a) ([raw file](https://github.com/paranext/paranext-core/blob/2e5ef088e02b45971e300c11a43ed9a33e9c6be6/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L136)):*
> ```Smalltalk
>                     }
>                 );
>                 return ResponseToRequest.Succeeded($"chapter:{verseRef}");
> ```

I believe the event contents must be the data type in string format. So in this case, it would be `"Chapter"`, I think. Or I guess `scope.DataType.ToUpperInvariant()` might work more generically.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 187 at r12](https://reviewable.io/reviews/paranext/paranext-core/427#-NfDK_L0B833xYps5APv:-NfDK_L0B833xYps5APw:be6ed5h) ([raw file](https://github.com/paranext/paranext-core/blob/4ac49469b647395eed1f75d116f543d8b195824f/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L187)):*
> ```Smalltalk
>                 }
>             );
>             return ResponseToRequest.Succeeded($"extensions:{scope.ExtensionName}");
> ```

I think this needs to be `ExtensionData` for it to work with subscriptions as they stand right now.

I could see this causing catastrophic performance issues when every extension project data provider grabs its data when just one kind of extension data got updated. Maybe we need to consider tweaking the design of the subscriptions and events for PSI/PDPs... Maybe we could somehow support sending out the whole extension data scope object. Probably worth making a separate issue.
___
*[`src/shared/models/project-data-provider.model.ts` line 6 at r10](https://reviewable.io/reviews/paranext/paranext-core/427#-NfCpubWAavVmOIeHFGv:-NfDLNdd17YmxVnmAoU1:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/d1549149d12af2fd27e8689a15b382e72b4873bc/src/shared/models/project-data-provider.model.ts#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2023-09-25 22:03 UTC, tjcouch-sil reviewed
> Reviewed 1 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2023-09-25 22:11 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 136 at r11](https://reviewable.io/reviews/paranext/paranext-core/427#-NfDIi1xBJTLrqnV6U0f:-NfDNSUV1oIGU5R7DrWr:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2e5ef088e02b45971e300c11a43ed9a33e9c6be6/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L136)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe the event contents must be the data type in string format. So in this case, it would be `"Chapter"`, I think. Or I guess `scope.DataType.ToUpperInvariant()` might work more generically.
</blockquote></details>

Done.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 187 at r12](https://reviewable.io/reviews/paranext/paranext-core/427#-NfDK_L0B833xYps5APv:-NfDNv-B3GxsIVHoGdR3:b-y8qjdr) ([raw file](https://github.com/paranext/paranext-core/blob/4ac49469b647395eed1f75d116f543d8b195824f/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L187)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think this needs to be `ExtensionData` for it to work with subscriptions as they stand right now.

I could see this causing catastrophic performance issues when every extension project data provider grabs its data when just one kind of extension data got updated. Maybe we need to consider tweaking the design of the subscriptions and events for PSI/PDPs... Maybe we could somehow support sending out the whole extension data scope object. Probably worth making a separate issue.
</blockquote></details>

The event has been updated.

I'm having a hard time thinking of a user story for a potential performance problem.  I think we have to wait to see how it really shakes out and then open tickets if there actually turn out to be problems.  If you have a user story in mind with what we have now, though, please open the ticket or let me know what you have in mind and I can open it.


<!-- Sent from Reviewable.io -->

2023-09-26 16:35 UTC, tjcouch-sil requested changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 136 at r11](https://reviewable.io/reviews/paranext/paranext-core/427#-NfDIi1xBJTLrqnV6U0f:-NfGqi_3C-QZVYK0a-7E:b-bv81tm) ([raw file](https://github.com/paranext/paranext-core/blob/2e5ef088e02b45971e300c11a43ed9a33e9c6be6/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L136)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually now that I look at the code, I believe the string in the event must be `"[\"Chapter\"]"` (not the `Chapter` constant which is all caps, but the raw string "Chapter" to match the data type. These are case-sensitive at the moment because of how the subscribe code works). Looks like the string must be a json-ified array whose contents are one string that is the name of the data type. I think that may have been a hold-over from when I was playing with the design for these update events and looking into a couple different possibilities for how to encode the needed information:

https://github.com/paranext/paranext-core/blob/361-csharp-load-projects/src/shared/services/data-provider.service.ts#L132-L137
![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/w6RlZJsMvi0nWk5g2VOWv7Xg/image.png)

Note that there cannot be any verse information or anything else in the string. It must be exactly the data type with the exact capitalization expected when using the `set___` function (so in this case `setChapter` would mean the data type is `"Chapter"`).

I'd say we're in need of a rework issue on these subscriptions. Maybe we can rework the event to pass out a JSON object containing this update information. Then we could be a bit freer to add more information to it as needed like with specific kinds of `ExtensionData`. Then we could figure out some way to get it all working together (not sure of all the details right now). If you think it might be better for this to be case-insensitive, that's also a conversation we could have around that issue (I don't want to worry about it right now haha).

Maybe a user story could be "As an extension developer, I want to be able to receive updates on my project-specific extension data when my data is updated by others without receiving updates on my data when any extension's project-specific extension data is updated by anyone so I am not unnecessarily processing data."

Created #443
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 187 at r12](https://reviewable.io/reviews/paranext/paranext-core/427#-NfDK_L0B833xYps5APv:-NfHH98yB9zepOy5Ri3m:bpt679m) ([raw file](https://github.com/paranext/paranext-core/blob/4ac49469b647395eed1f75d116f543d8b195824f/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L187)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

The event has been updated.

I'm having a hard time thinking of a user story for a potential performance problem.  I think we have to wait to see how it really shakes out and then open tickets if there actually turn out to be problems.  If you have a user story in mind with what we have now, though, please open the ticket or let me know what you have in mind and I can open it.
</blockquote></details>

Unfortunately, along the same lines as the comment I made above, I believe the string in the event must be `"[\"ExtensionData\"]"` without any additional information. Created #443


<!-- Sent from Reviewable.io -->

2023-09-26 17:06 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> woooo! So excited!! Thanks for all the hard work!

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/427#-:-NfHS87T5Fp8LI_pZ0oC:b-i38pe4)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-26 17:19 UTC, merged