Run basic checks stub
paranext/paranext-core pull request #468
Opened 2023-09-27 14:33 UTC by jolierabideau

- `ChapterRangeSelection` created in PAPI Components- used in many places in Paratext and could be useful to extensions. 
- Exposed `getChaptersForBook` from PAPI Scripture utils
- `BasicChecks` component maps checks to Checkboxes
- `BookSelection` component offers two radio groups: selecting chapter range for the current book, or choosing new books to check.
- `RunBasicChecksTab` to display everything and collect data from each of the components for posting.

I commented out the other floating tabs while I was developing, but should we leave the project dialogs and extension toggle commented out so that we don't overwhelm the screen on first load?

![Screenshot 2023-09-27 at 11 23 28 AM](https://github.com/paranext/paranext-core/assets/135999578/403ccca0-6e5f-4c0a-9b37-ff3c4e29d48b)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-core/468)

2023-09-28 17:05 UTC, katherinejensen00 requested changes
I can't remember for sure, but I think there was talk of potentially removing the project dropdown as that was mainly there in P9 because of a bad state you could get into. I think we are hoping to avoid that bad state in Paratext.Bible, but I am not totally sure. Either way, UX is redesigning this anyway so it probably isn't worth changing now as it will probably be changed in that design if a change is needed.

Thank you Jolie and Tom for your great work on this! It looks amazing and I know that was a struggle. I have a few minor questions and notes, but it is basically done. The components you created as part of this task will be really helpful.

> Reviewed 2 of 6 files at r1, 1 of 2 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/468#-:-NfRgvV616Sy3J5nfgu2:bl243qd)* status: all files reviewed, 5 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/papi-components/dist/index.d.ts` line 38 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRhhST5IuLCHItoBZ_:-NfRhhSU13Nxfp-ZngV_:bmmxrkh) ([raw file](https://github.com/paranext/paranext-core/blob/e0775baa71224fad84ebdc09baabe627fd3dbc58/lib/papi-components/dist/index.d.ts#L38)):*
> ```XML
> export declare function Button({ id, isDisabled, className, onClick, onContextMenu, children, }: ButtonProps): import("react/jsx-runtime").JSX.Element;
> export declare enum LabelPosition {
> 	After = "after",
> ```

I am probably missing something (like this was just moved somewhere else), but why was this deleted?
___
*[`lib/papi-components/src/chapter-range-selection.component.tsx` line 5 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRiN-N2tzcnHcaZ7Rk:-NfRiN-N2tzcnHcaZ7Rl:b-jvri4h) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/chapter-range-selection.component.tsx#L5)):*
> ```XML
> import ComboBox, { ComboBoxLabelOption } from './combo-box.component';
> 
> export type ChapterRangeSelectionProps = {
> ```

I think this is going to be a really helpful component to have. Thanks for creating it!
___
*[`src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx` line 7 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRj1S51hvi2Th2ddvg:-NfRj1S51hvi2Th2ddvh:b8rth74) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx#L7)):*
> ```XML
> import './book-selection.component.scss';
> 
> type BookSelectionProps = {
> ```

Thanks for creating this! We know this will come up a lot :)
___
*[`src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx` line 113 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRjOnyB5ya01EdCaqZ:-NfRjOnyB5ya01EdCaq_:b-kpyj9m) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx#L113)):*
> ```XML
>         options={projectNameOptions}
>       />
>       {/* Should always be two columns? */}
> ```

Great question for UX. I wonder if this could eventually change based on the size of the window. I think what you have is great for now though and should not change as part of this case. It might be nice to throw this question in to the UX case for designing the Run Checks dialog
___
*[`src/renderer/testing/test-layout.data.ts` line 5 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRjlfqEGvgZ90kCgXu:-NfRjlfqEGvgZ90kCgXv:b-tdnyag) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/testing/test-layout.data.ts#L5)):*
> ```XML
> import { TAB_TYPE_ABOUT } from '@renderer/testing/about-panel.component';
> import { TAB_TYPE_BUTTONS } from '@renderer/testing/test-buttons-panel.component';
> // import { TAB_TYPE_QUICK_VERSE_HERESY } from '@renderer/testing/test-quick-verse-heresy-panel.component';
> ```

Should these stay commented out, or did you just do that temporarily?


<!-- Sent from Reviewable.io -->

2023-09-28 17:14 UTC, tjcouch-sil requested changes
Thanks for all the hard work on this! Looking good!

> Reviewed 2 of 6 files at r1, 1 of 2 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/468#-:-NfRmEV2DKPZAJoxcYGs:bu4rqhm)* status: all files reviewed, 21 unresolved discussions (waiting on @jolierabideau and @katherinejensen00)

___
*[`lib/papi-components/dist/index.d.ts` line 38 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRhhST5IuLCHItoBZ_:-NfRlyaM4bLx3W_WnpHY:b-hbhrqu) ([raw file](https://github.com/paranext/paranext-core/blob/e0775baa71224fad84ebdc09baabe627fd3dbc58/lib/papi-components/dist/index.d.ts#L38)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

I am probably missing something (like this was just moved somewhere else), but why was this deleted?
</blockquote></details>

This is an autogenerated file, and it was just moved down further. I was confused at first too haha
___
*[`lib/papi-components/src/chapter-range-selection.component.tsx` line 8 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRlUpr4ECZNQvElYLu:-NfRlUpr4ECZNQvElYLv:bkght4x) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/chapter-range-selection.component.tsx#L8)):*
> ```XML
>   startChapter: number;
>   endChapter: number;
>   onChangeStartChapter: (_event: SyntheticEvent<Element, Event>, value: unknown) => void;
> ```

Making these `value` parameters typed would be very helpful. I think they are just `number` type.

Do you need the underscore on `_event`? I recommend removing it if not.
___
*[`lib/papi-components/src/chapter-range-selection.component.tsx` line 18 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRbZlQ821HKas-T_Tf:-NfRbZlQ821HKas-T_Tg:byrwody) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/chapter-range-selection.component.tsx#L18)):*
> ```XML
> }
> 
> export default function ChapterRangeSelection({
> ```

I suggest renaming this to `ChapterRangeSelector` to indicate its role is to allow people to select books. It kinda reads to me like it is just a display of a chapter range selection as is.
___
*[`lib/papi-components/src/chapter-range-selection.component.tsx` line 27 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRkwlP-G_HyVEkDWb1:-NfRkwlP-G_HyVEkDWb2:bp2hvfr) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/chapter-range-selection.component.tsx#L27)):*
> ```XML
> }: ChapterRangeSelectionProps) {
>   let chapterNumberOptions: ChapterNumberOption[];
>   const numberArray = Array.from({ length: chapterCount }, (_, index) => index + 1);
> ```

It is probably best to wrap this in a useMemo so you aren't creating a new array every render.
___
*[`lib/papi-components/src/chapter-range-selection.component.tsx` line 29 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRkANa7ovjuP3X1ZLU:-NfRkANbE0M3O8EnfNup:bdgpkc6) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/chapter-range-selection.component.tsx#L29)):*
> ```XML
>   const numberArray = Array.from({ length: chapterCount }, (_, index) => index + 1);
> 
>   const getChapterNumberOptions = () => {
> ```

Have you tried just using the `numberArray` as the options? I think the combo box might support a number array, but you would have to change `combo-box.component.tsx`'s `ComboBoxOption` type to include `number` because TypeScript doesn't realize it can support it:

```typescript
export type ComboBoxOption = string | number | ComboBoxLabelOption;
```

That would simplify this code a lot. You wouldn't need the `let` or this function. You wouldn't need `currentStartChapter` or `currentEndChapter` :)
___
*[`lib/papi-components/src/index.ts` line 12 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRW7MxE475_NAOStBG:-NfRW7MxE475_NAOStBH:b-8lbzqp) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/index.ts#L12)):*
> ```XML
> export { default as RefSelector } from './ref-selector.component';
> export type { ScrRefSelectorProps } from './ref-selector.component';
> export { getChaptersForBook } from './scripture/scripture-util';
> ```

I wonder if we should create a subpath export that exports all of the scripture utils we have. Not right now. Would probably make things more organized. #240
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 63 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRWfG21cia_CcoF8AK:-NfRWfG21cia_CcoF8AL:b-mb7qg) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/docking/paranext-dock-layout.component.tsx#L63)):*
> ```XML
>   TAB_TYPE_RUN_BASIC_CHECKS,
>   loadRunBasicChecksTab,
> } from '../run-basic-checks-dialog/run-basic-checks-tab.component';
> ```

This needs to be an `@aliased/...` path
___
*[`src/renderer/components/run-basic-checks-dialog/basic-checks.component.tsx` line 68 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRWySu8t15c27EPSXB:-NfRWySu8t15c27EPSXC:b35prat) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/basic-checks.component.tsx#L68)):*
> ```XML
> 
> type BasicCheckProps = {
>   handleSelectChecks: (checkName: string) => void;
> ```

Should this be `handleSelectCheck` since it handles one check at a time?
___
*[`src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx` line 7 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRb91U9ZnGkDBfPtxg:-NfRb91VBozfXvgJ-r84:bxz5u9t) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx#L7)):*
> ```XML
> import './book-selection.component.scss';
> 
> type BookSelectionProps = {
> ```

I wonder if it would be helpful to union with the Chapter change props. Like

```typescript
type BookSelectionProps = ChapterRangeSelectionProps & {
  ...
}
```

Are you using all the chapter selection props here? Are you intending to have all of them and to pass them all down? Union would probably be a good fit if so such that you don't have to copy prop types around.
___
*[`src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx` line 9 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRgjqKEKiqBdlNA0w8:-NfRgjqKEKiqBdlNA0w9:br1888o) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx#L9)):*
> ```XML
> type BookSelectionProps = {
>   useCurrentBook: boolean;
>   toggleCurrentBook: () => void;
> ```

Could you add an argument to this function which is a boolean of the new value to make the job easier for parent components?
___
*[`src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx` line 12 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRXmG3C6VWG26miDPM:-NfRXmG3C6VWG26miDPN:b47yvft) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx#L12)):*
> ```XML
>   currentBookNumber: number;
>   selectedBooks: number[];
>   handleSelectBooks: (bookNumber: number) => void;
> ```

Should this be `handleSelectBook`?
___
*[`src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx` line 20 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRXtrAAfBxbcrnq7A9:-NfRXtrAAfBxbcrn [...]

2023-09-28 17:17 UTC, katherinejensen00 reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/468)* status: all files reviewed, 20 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/papi-components/dist/index.d.ts` line 38 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRhhST5IuLCHItoBZ_:-NfRmd-L6tQ71T-mx8Kh:bdjrg1z) ([raw file](https://github.com/paranext/paranext-core/blob/e0775baa71224fad84ebdc09baabe627fd3dbc58/lib/papi-components/dist/index.d.ts#L38)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is an autogenerated file, and it was just moved down further. I was confused at first too haha
</blockquote></details>

That makes sense. Thanks!


<!-- Sent from Reviewable.io -->

2023-09-29 21:06 UTC, jolierabideau reviewed
There was talk about removing the project dropdown, I left a comment about that being changed eventually. I can take it out if that is preferred! That would remove the need to fetchProjects() in this tab. Thanks for your reviews! 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/468#-:-NfRw0LZ6mn389_M28NS:bdb4wla)* status: all files reviewed, 15 unresolved discussions (waiting on @katherinejensen00 and @tjcouch-sil)

___
*[`lib/papi-components/src/chapter-range-selection.component.tsx` line 8 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRlUpr4ECZNQvElYLu:-NfWkN7UE43jGA4HpIgh:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/chapter-range-selection.component.tsx#L8)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Making these `value` parameters typed would be very helpful. I think they are just `number` type.

Do you need the underscore on `_event`? I recommend removing it if not.
</blockquote></details>

Done
___
*[`lib/papi-components/src/chapter-range-selection.component.tsx` line 18 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRbZlQ821HKas-T_Tf:-NfSDgwn1HCuRLZCixNt:b-qjsx3m) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/chapter-range-selection.component.tsx#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I suggest renaming this to `ChapterRangeSelector` to indicate its role is to allow people to select books. It kinda reads to me like it is just a display of a chapter range selection as is.
</blockquote></details>

Done That makes sense!
___
*[`lib/papi-components/src/chapter-range-selection.component.tsx` line 27 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRkwlP-G_HyVEkDWb1:-NfSknQq1HV7xFwpMZPz:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/chapter-range-selection.component.tsx#L27)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It is probably best to wrap this in a useMemo so you aren't creating a new array every render.
</blockquote></details>

Done.
___
*[`lib/papi-components/src/chapter-range-selection.component.tsx` line 29 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRkANa7ovjuP3X1ZLU:-NfSEkGC6Q5fTXTYXV1z:bpegmr8) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/chapter-range-selection.component.tsx#L29)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Have you tried just using the `numberArray` as the options? I think the combo box might support a number array, but you would have to change `combo-box.component.tsx`'s `ComboBoxOption` type to include `number` because TypeScript doesn't realize it can support it:

```typescript
export type ComboBoxOption = string | number | ComboBoxLabelOption;
```

That would simplify this code a lot. You wouldn't need the `let` or this function. You wouldn't need `currentStartChapter` or `currentEndChapter` :)
</blockquote></details>

This makes a lot more sense! I switched it to number[] but I am troubleshooting the autocomplete warning "MUI: The `getOptionLabel` method of Autocomplete returned number (31) instead of a string for 31." 
___
*[`lib/papi-components/src/index.ts` line 12 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRW7MxE475_NAOStBG:-NfSEzbcDAvd7FpDJDB_:b-96bc1b) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/index.ts#L12)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I wonder if we should create a subpath export that exports all of the scripture utils we have. Not right now. Would probably make things more organized. #240
</blockquote></details>

I did wonder if these utils should be exported and if there was a better way to do it. So is this fine for now? Or would you like me to go ahead and add them all individually until we get to this subpath issue?
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 63 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRWfG21cia_CcoF8AK:-NfSFc9a89Pz1y0ePyRr:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/docking/paranext-dock-layout.component.tsx#L63)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This needs to be an `@aliased/...` path
</blockquote></details>

Done.
___
*[`src/renderer/components/run-basic-checks-dialog/basic-checks.component.tsx` line 68 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRWySu8t15c27EPSXB:-NfSFkIf-kPNZs5ntSc3:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/basic-checks.component.tsx#L68)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should this be `handleSelectCheck` since it handles one check at a time?
</blockquote></details>

Done.
___
*[`src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx` line 7 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRb91U9ZnGkDBfPtxg:-NfSLgISEabmX9Rno3yC:bn51ti6) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx#L7)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I wonder if it would be helpful to union with the Chapter change props. Like

```typescript
type BookSelectionProps = ChapterRangeSelectionProps & {
  ...
}
```

Are you using all the chapter selection props here? Are you intending to have all of them and to pass them all down? Union would probably be a good fit if so such that you don't have to copy prop types around.
</blockquote></details>

I am using startChapter, endChapter, and chapterCount. So I omitted the onChangeStart and onChangeEnd. 
___
*[`src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx` line 9 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRgjqKEKiqBdlNA0w8:-NfXROlp2nxdpg76tfqR:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Could you add an argument to this function which is a boolean of the new value to make the job easier for parent components?
</blockquote></details>

Done
___
*[`src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx` line 12 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRXmG3C6VWG26miDPM:-NfShjIyELnnkiDx6j9b:b-a59cdv) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx#L12)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should this be `handleSelectBook`?
</blockquote></details>

It was stubbed to only select one book, but really users will be able to select multiple so I turned that into an array of numbers. 
___
*[`src/renderer/components/run-basic-checks-dialog/book-selection.component.tsx` line 21 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRZl1RDBs-pQNIKMMZ:-NfSkQhN0IksD4u0gI2v:b-896fix) ([raw file](https://github.com/para [...]

2023-10-02 16:04 UTC, katherinejensen00 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/468#-:-Nfl7S1x3McJGFkUEaMF:bnfp4nl)* status: all files reviewed, 13 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx` line 113 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRjOnyB5ya01EdCaqZ:-Nfl7ALLCEfGOzY6CUSr:bh95uwn) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx#L113)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I attempted to switch to one when the window wasn't wide enough for two. But it became difficult with so many unknowns for width of tab and how much space each section should take up. I can add it to the UX case!
</blockquote></details>

Great, thanks, Jolie!
___
*[`src/renderer/testing/test-layout.data.ts` line 5 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRjlfqEGvgZ90kCgXu:-Nfl7HngDDt__Fh0akD9:bg7hssi) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/src/renderer/testing/test-layout.data.ts#L5)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I did do that while I was developing. But, now that we have so many floating tabs I am wondering if it makes sense to leave some of them commented out? I could leave Quick Verse and then we wouldn't have to clear out of all the tabs on a fresh start.
</blockquote></details>

That makes sense. Thanks for explaining that!


<!-- Sent from Reviewable.io -->

2023-10-02 22:08 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> just one question (potentially with action or potentially not) and two tiny things to ignore for now unless you end up making other changes. Thanks for all the hard work! Great stuff! If you don't need to make any changes, feel free to resolve my comments and get this in.

> Reviewed 14 of 15 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/468#-:-NfmQCaC4olK7Z6b-Wgi:b-syxn0l)* status: all files reviewed, 3 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/papi-components/src/index.ts` line 12 at r5](https://reviewable.io/reviews/paranext/paranext-core/468#-NfRW7MxE475_NAOStBG:-NflvBwv5FDEFMLzDwsB:b88pca9) ([raw file](https://github.com/paranext/paranext-core/blob/e7034aca432a36cc2dffb8ccd83bb24cecd82879/lib/papi-components/src/index.ts#L12)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I did wonder if these utils should be exported and if there was a better way to do it. So is this fine for now? Or would you like me to go ahead and add them all individually until we get to this subpath issue?
</blockquote></details>

Yep, just fine for now. I just put this here to have a link to it for later. I put the status of this discussion as "Informing" (the i in a circle) to indicate there's no action for now :) thanks for checking!
___
*[`src/renderer/components/run-basic-checks-dialog/book-selector.component.tsx` line 7 at r6](https://reviewable.io/reviews/paranext/paranext-core/468#-NfmP9Ft4-8NQisIvw80:-NfmP9Ft4-8NQisIvw81:b-1w6awt) ([raw file](https://github.com/paranext/paranext-core/blob/73e3bf9d5549b7beb12ecc925c5d586c9aecf49a/src/renderer/components/run-basic-checks-dialog/book-selector.component.tsx#L7)):*
> ```XML
> import './book-selector.component.scss';
> 
> type BookSelectionProps = Omit<
> ```

No big deal, but this is still named `Selection`. No need to change this now unless you end up making other changes.
___
*[`src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx` line 38 at r6](https://reviewable.io/reviews/paranext/paranext-core/468#-Nflwxfd3mW0YmKqwnaR:-Nflwxfd3mW0YmKqwnaS:b1n52qq) ([raw file](https://github.com/paranext/paranext-core/blob/73e3bf9d5549b7beb12ecc925c5d586c9aecf49a/src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx#L38)):*
> ```XML
>   const [useCurrentBook, setUseCurrentBook] = useState<boolean>(true);
> 
>   const handleSelectBooks = (bookNumbers: number[]) => {
> ```

Previously, this handled deselecting books, but it doesn't seem to now. Is it still intended to do so, or not anymore? If not right now, feel free to resolve this comment. If so, maybe the argument `bookNumbers` can be an object whose keys are books and values are true or false? Just a suggestion! :) Do what makes sense to you!
___
*[`lib/papi-components/src/chapter-range-selector.component.tsx` line 33 at r6](https://reviewable.io/reviews/paranext/paranext-core/468#-NfluHxr-Yr_oxpKqtxG:-NfluHxr-Yr_oxpKqtxH:b-z2tog4) ([raw file](https://github.com/paranext/paranext-core/blob/73e3bf9d5549b7beb12ecc925c5d586c9aecf49a/lib/papi-components/src/chapter-range-selector.component.tsx#L33)):*
> ```XML
>         disabled={isDisabled}
>         control={
>           <ComboBox
> ```

`ComboBox has a generic type. In order to avoid type asserting in `onChange`, you should be able to change this line to `<ComboBox<number>` (and line 50). Not a big deal this time; no need to change unless you're already making other changes


<!-- Sent from Reviewable.io -->

2023-10-03 12:22 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/468)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx` line 38 at r6](https://reviewable.io/reviews/paranext/paranext-core/468#-Nflwxfd3mW0YmKqwnaR:-NfpTilS8yKr_LMyLDyK:btljdcw) ([raw file](https://github.com/paranext/paranext-core/blob/73e3bf9d5549b7beb12ecc925c5d586c9aecf49a/src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx#L38)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Previously, this handled deselecting books, but it doesn't seem to now. Is it still intended to do so, or not anymore? If not right now, feel free to resolve this comment. If so, maybe the argument `bookNumbers` can be an object whose keys are books and values are true or false? Just a suggestion! :) Do what makes sense to you!
</blockquote></details>

I believe it does deselect books with line 52.


<!-- Sent from Reviewable.io -->

2023-10-03 12:23 UTC, merged