Add electron-edge-js and C# project, update Electron to 22.0.3 and Node to 16.17.1
paranext/paranext-core pull request #5
Opened 2023-01-24 23:34 UTC by tjcouch-sil

- Added nice eslint rules I developed from the [React POC](https://github.com/tjcouch-sil/paranext-poc) (we can always discuss code style preferences)
- Added path aliases from the React POC for nice imports
- Bumped nvmrc to 16.17.1
- Bumped Electron to 22.0.3
- Added electron-edge-js as a [native dependency](https://electron-react-boilerplate.js.org/docs/adding-dependencies/#module-structure)
- Added `EdgeLibrary.csproj` (mostly from the [edge POC](https://github.com/tjcouch-sil/paranext-electron-edge-poc)) as a starting point for calling C# functions
- Hooked up a Test Edge button that sends a message from the renderer to the main process, invokes an edge function, and returns a string that prints in the DevTools console

2023-01-25 04:01 UTC, irahopkinson requested changes
Thanks for all your work on this.

There are some files that were specifically removed from the boilerplate which I've added comments. You can't comment non-text files so also remove the 4x electron `assets/icon.*` files.

And I have one question about `require` in a TS file.

2023-01-25 04:01 UTC, irahopkinson commented on .github/FUNDING.yml
> +# These are supported funding model platforms
Remove this file, we don't need it.

2023-01-25 04:01 UTC, irahopkinson commented on .github/ISSUE_TEMPLATE/1-Bug_report.md
> +---
Remove this file, we don't need it.

2023-01-25 04:01 UTC, irahopkinson commented on .github/ISSUE_TEMPLATE/2-Question.md
> +---
Remove this file, we don't need it.

2023-01-25 04:01 UTC, irahopkinson commented on .github/ISSUE_TEMPLATE/3-Feature_request.md
> +---
Remove this file, we don't need it.

2023-01-25 04:01 UTC, irahopkinson commented on .github/config.yml
> +requiredHeaders:
Remove this file, we don't need it.

2023-01-25 04:01 UTC, irahopkinson commented on .github/stale.yml
> +# Number of days of inactivity before an issue becomes stale
Remove this file, we don't need it.

2023-01-25 04:01 UTC, irahopkinson commented on .prettierrc
> +	"endOfLine": "auto"
EOL should be LF (unix style) to align with what we need for git to work across platforms.

2023-01-25 04:01 UTC, irahopkinson commented on src/main/main.ts
> +const edge = require('electron-edge-js');
Does this need to be `require`d rather than `import`ed? Linters don't like it, and I vaguely remember some packaging issues or something in the past.

2023-01-25 14:56 UTC, tjcouch-sil commented on .github/FUNDING.yml
> +# These are supported funding model platforms
Removed. Thanks!

2023-01-25 14:56 UTC, tjcouch-sil commented on .github/ISSUE_TEMPLATE/1-Bug_report.md
> +---
Removed. Thanks!

2023-01-25 14:56 UTC, tjcouch-sil commented on .github/ISSUE_TEMPLATE/3-Feature_request.md
> +---
Removed. Thanks!

2023-01-25 14:56 UTC, tjcouch-sil commented on .github/config.yml
> +requiredHeaders:
Removed. Thanks!

2023-01-25 14:56 UTC, tjcouch-sil commented on .github/stale.yml
> +# Number of days of inactivity before an issue becomes stale
Removed. Thanks!

2023-01-25 14:56 UTC, tjcouch-sil commented on .prettierrc
> +	"endOfLine": "auto"
Fixed. Thanks!

2023-01-25 15:34 UTC, tjcouch-sil commented on src/main/main.ts
> +const edge = require('electron-edge-js');
Edge needs some environment variables before import/require. `EDGE_USE_CORECLR` is easy to set in `package.json` in scripts, but `EDGE_APP_ROOT` points to the build location of the C# project, which I suppose may be different in different contexts. Would it be different if we were developing vs in packaged production? If not, maybe we can figure out putting `EDGE_USE_CORECLR` somewhere else. The reason I set environment variables here and then `require`d edge instead of importing at the top is that it did the same in the [quick start example](https://github.com/agracio/electron-edge-js-quick-start/blob/master/renderer.js#L12), and I couldn't think of a better way for now since I don't really know what the project will look like packaged up and cross-platform and such. Are we going to use different build folders for different distributions? Will the folder be different between development and packaged? How do we address this issue in such a way that we can simply import edge at the top and the `EDGE_APP_ROOT` environment variable is set correctly? If you have thoughts, please share! Otherwise I will look at the mac deployment and see if that sheds any light. Thanks!

2023-01-25 15:43 UTC, tjcouch-sil commented on src/main/main.ts
> +const edge = require('electron-edge-js');
According to the macos build job, the failure was in `npm install`:

```
Package mono-2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `mono-2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mono-2' found
...
gyp: Call to 'pkg-config mono-2 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
...
An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/runner/work/paranext-core/paranext-core/release/app/node_modules/electron-edge-js'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild"
```

ERB is set up so that native module dependencies are 

Looks like there are a number of dependencies that we will need to install in order to build electron-edge-js on the various platforms:

https://github.com/agracio/edge-js#building-on-windows
https://github.com/agracio/edge-js#building-on-osx
https://github.com/agracio/edge-js#building-on-linux

Alternatively, we could investigate using the prebuilt versions of the electron-edge-js package included in its package. We would want to figure out how to prevent `.erb/scripts/electron-rebuild.js` from firing `electron-rebuild` on `electron-edge-js`. However, I suspect this could hinder our cross-platform capabilities or future-proofing capabilities. I don't know, though, so maybe it's worth giving a shot! I will investigate. After all, it is rather annoying that people have to download all these dependencies to make `electron-edge-js` build on their machine. :/

2023-02-01 22:13 UTC, tjcouch-sil commented
Abandoning. See https://github.com/paranext/paranext-core/issues/1

2023-02-01 22:13 UTC, closed without merging