Added dialog service for retrieving info from users. Select Project Dialog. `useDialogCallback` hook
paranext/paranext-core pull request #553
Opened 2023-10-13 23:03 UTC by tjcouch-sil

Resolves #388

2023-10-16 00:50 UTC, irahopkinson reviewed
Thanks for all your good work on this.

It still feels like we are inappropriately using tab panel floats for dialogs. One of the issues with using floats is it puts an unnecessary burden on the window docking system (saving layouts and positions) for something that is inherently outside the docking system. Is there some reason we don't just use [MUI Dialogs](https://mui.com/material-ui/react-dialog/) that are designed for purpose (including already modal)? Or are we just trying to get past Tech Demo without doing that work? 

> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/553#-:-NgpnyFF8Ai3MsAet1BZ:bj9cyzp)* status: all files reviewed, 24 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/hello-someone/hello-someone.ts` line 319 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpK6OD8E5YNPFNrsZi:-NgpK6OD8E5YNPFNrsZj:bj2xfgp) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/extensions/src/hello-someone/hello-someone.ts#L319)):*
> ```XML
>     papi.webViews.onDidAddWebView((addWebViewEvent) => {
>       if (addWebViewEvent.webView.webViewType === peopleWebViewType)
>         logger.log(
> ```

Nit: use `info`.



_Code quote:_
```XML
.log(
```
___
*[`extensions/src/hello-world/web-views/hello-world.web-view.tsx` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpNBO33pIQeiyFe8hF:-NgpNBO33pIQeiyFe8hG:b-9iqy2p) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/extensions/src/hello-world/web-views/hello-world.web-view.tsx#L90)):*
> ```XML
>       title: 'Select Hello World Project',
>     }).current,
>     'None' as string,
> ```

Nit: I'm pretty sure this doesn't need to be here since a literal string is a string.



_Code quote:_
```XML
 as string
```
___
*[`src/extension-host/extension-host.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpOqWy-T-D07fTDc5r:-NgpOqWy-T-D07fTDc5s:b-5x2a8g) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/extension-host/extension-host.ts#L12)):*
> ```XML
> import { getErrorMessage } from '@shared/utils/util';
> import { CommandNames } from 'papi-shared-types';
> import { startProjectLookupService } from '@extension-host/services/project-lookup.service.host';
> ```

This doesn't follow our filename convention. What are you trying to convey with this filename? What is a 'host' file type mean?
___
*[`src/extension-host/services/papi-backend.service.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpPCX29TS_8ipd-f2F:-NgpPCX55QunTUQySdoc:bfzx5m7) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/extension-host/services/papi-backend.service.ts#L26)):*
> ```XML
>   ExtensionStorageService,
> } from '@extension-host/services/extension-storage.service';
> import { ProjectLookupServiceType } from '@shared/services/project-lookup.service.model';
> ```

This doesn't follow our filename convention. What are you trying to convey with this filename? Would `project-lookup-service.model` work?
___
*[`src/extension-host/services/papi-backend.service.ts` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpPUxTEipoLArjkRYE:-NgpPUxTEipoLArjkRYF:b386q1h) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/extension-host/services/papi-backend.service.ts#L29)):*
> ```XML
> import projectLookupService from '@shared/services/project-lookup.service';
> import dialogService from '@shared/services/dialog.service';
> import { DialogService } from '@shared/services/dialog.service.model';
> ```

This doesn't follow our filename convention. What are you trying to convey with this filename? Would `dialog-service.model` work?
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpV0tWA6V6Lyse_hAk:-NgpV0tWA6V6Lyse_hAl:b-s9dl7s) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/dialog-base.data.ts#L13)):*
> ```XML
>   Component?: (props: DialogProps) => ReactElement;
>   /**
>    * The default icon for this dialog. This may be overridden by the `DialogOptions.title`
> ```

Copy and paster error? Change to `DialogOptions.iconUrl`.



_Code quote:_
```XML
DialogOptions.title
```
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpcR9S8qLly-fVDpqe:-NgpcR9S8qLly-fVDpqf:blwshrg) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/dialog-base.data.ts#L29)):*
> ```XML
>   minWidth?: number;
>   /** The minimum height to which the dialog can be set */
>   minHeight?: number;
> ```

BTW I'm wondering if this is such a good idea to put dialog sizing in the hands of the extension developer. Dialog sizing is really more a function of the design system and the viewport size. Minimums might be a good guide but maybe not specifying the initial size? Thoughts? Perhaps this is just an interim setting?



_Code quote:_
```XML
  /** The width and height at which the dialog will be loaded */
  initialSize: FloatSize;
  /** The minimum width to which the dialog can be set */
  minWidth?: number;
  /** The minimum height to which the dialog can be set */
  minHeight?: number;
```
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 54 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpdxvbDcQaml78rEOM:-Ngpdxvc-MZFqDFayWaH:bb7phvt) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/dialog-base.data.ts#L54)):*
> ```XML
>   submitDialog(data: TData): void;
>   /**
>    * Rejects the dialog request with hte specified message
> ```

typo



_Code quote:_
```XML
hte
```
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 112 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpfQox4nTNHUASLKuQ:-NgpfQox4nTNHUASLKuR:b-ep7kvg) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/dialog-base.data.ts#L112)):*
> ```XML
> }
> 
> export function hookUpDialogService({
> ```

BTW since this function is exported it should probably have a JSDoc.
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngpi7z2Ew0GEyWFps1l:-Ngpi7z2Ew0GEyWFps1m:b-bpui2w) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L13)):*
> ```XML
> type SelectProjectDialogProps = DialogProps<string>;
> 
> const SELECT_PROJECT_DIALOG_TYPE = 'platform.selectProject';
> ```

BTW I wondering if we exported this from a `*.model.ts` file it could be included in papi and we wouldn't need to have the other 2 magic strings floating around.
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpiumKAMr5YX7403CF:-NgpiumKAMr5YX7403CG:bilvvdr) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L18)):*
> ```XML
>   const [projects, isLoadingProjects] = usePromise(
>     projectLookupService.getMetadataForAllProjects,
>     useMemo(() => [], []),
> ```

BTW er, what does this empty memo do for us? Is this some React trick?
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/ [...]

2023-10-16 18:27 UTC, lyonsil requested changes
> Reviewed 32 of 39 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/553)* status: all files reviewed, 34 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/src/hello-world/web-views/hello-world.web-view.tsx` line 90 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtX9pO844__WNGvOUf:-NgtX9pO844__WNGvOUg:b-1zkpqn) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/extensions/src/hello-world/web-views/hello-world.web-view.tsx#L90)):*
> ```XML
>   const [project, selectProject] = useDialogCallback(
>     'platform.selectProject',
>     useRef({
> ```

Can we come up with a way for this hook to work without requiring the caller to remember to call `useRef`?  This design I assume means if someone forgets then the renderer will spin re-rendering.  It feels fragile.
___
*[`src/extension-host/extension-host.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpOqWy-T-D07fTDc5r:-NgtXkjT5mr9ZtQeyJnn:b-j4ztk0) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/extension-host/extension-host.ts#L12)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This doesn't follow our filename convention. What are you trying to convey with this filename? What is a 'host' file type mean?
</blockquote></details>

@irahopkinson - TJ and I were talking about this sort of naming.  In the newer design we talked about, we're separating the "server" code that is only meant to run in a specific process from the "client" code that is meant to run in any process that wants to use the "server."  We talked about naming that "server" code with `host`.  Do you have a different idea for naming?
___
*[`src/extension-host/services/papi-backend.service.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpPCX29TS_8ipd-f2F:-NgtYAFH2y9tG-n7BmIc:bvod7ns) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/extension-host/services/papi-backend.service.ts#L26)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This doesn't follow our filename convention. What are you trying to convey with this filename? Would `project-lookup-service.model` work?
</blockquote></details>

@irahopkinson - TJ and I were talking about this sort of naming.  In the newer design we talked about, we're separating the "server" code that is only meant to run in a specific process from the "client" code that is meant to run in any process that wants to use the "server."  I think it's worthwhile to talk about updating our naming guidelines to clarify exactly what we want to name these different files.
___
*[`src/renderer/index.tsx` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtY_ge9wlYrrw2LdwW:-NgtY_ge9wlYrrw2LdwX:bv4umex) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/index.tsx#L19)):*
> ```XML
> webViewProviderService.initialize();
> webViewService.initialize();
> startDialogService();
> ```

Don't we need to await all of these calls?  I know you're just following the pattern be adding another line that doesn't await, but it seems like we need to await these calls.  For example, if the network service doesn't finish initializing before we run other services that use it, I'm not sure how well we will recover.
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 27 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtZ3gY1b7Viijo4KkH:-NgtZ3gY1b7Viijo4KkI:baeatsw) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/components/dialogs/dialog-base.data.ts#L27)):*
> ```XML
>   initialSize: FloatSize;
>   /** The minimum width to which the dialog can be set */
>   minWidth?: number;
> ```

I assume we're talking about units in terms of pixels and not points or picas or something else, but it would be good to call this out in the comment.  Same below.
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 104 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtZwHJ74YBhOd0zUH5:-NgtZwHJ74YBhOd0zUH6:b-klwtxs) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/components/dialogs/dialog-base.data.ts#L104)):*
> ```XML
> 
> /**
>  * Reject a dialog request. Synchronously rejects, then asynchronously closes the dialog
> ```

What if the async closing of the dialog fails?  With this pattern the error is lost.  Why not make the call async?
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpiumKAMr5YX7403CF:-NgtaC-g1BvSxdtHMkLO:b-a1tt0l) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L18)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW er, what does this empty memo do for us? Is this some React trick?
</blockquote></details>

And can we just have a default value for that argument instead of making callers use this syntax?
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngpm3Zn97rS2n7i8Gzp:-NgtakBd4cVAjLS_fquk:b-n83ooo) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L37)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I think this should just be camelCase since it's an object in place of a class instance rather than a genuine `const` value (such as `SELECT_PROJECT_DIALOG_TYPE`), i.e. change to `selectProjectDialog`.
</blockquote></details>

My current understanding is that we should only use `UPPER_SNAKE_CASE` for constant strings, numbers, and booleans.  Where are we on that?
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 239 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngtbbla6ry6YOOrw9NY:-Ngtbbla6ry6YOOrw9NZ:b-idm5uo) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/components/docking/paranext-dock-layout.component.tsx#L239)):*
> ```XML
>   switch (layout.position) {
>     case 'center':
>       left = layoutSize.width / 2 - width / 2;
> ```

What if the dialog is larger than the layout?  Could a dialog's top bar be offscreen and unselectable?  Do we need to make sure that `left` and `top` have a minimum of 0?
___
*[`src/renderer/hooks/papi-hooks/use-dialog-callback.hook.ts` line 65 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtdSDG98RG3VNa9TtX:-NgtdSDG98RG3VNa9TtY:b2f1twp) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/hooks/papi-hooks/use-dialog-callback.hook.ts#L65)):*
> ```XML
>   // type assert to tell TS that undefined will be part of `TResponse` if `defaultResponse` is not
>   // specified but is not otherwise
>   const [response, setResponse] = useState(defaultResponse as TResponse);
> ```

Can the default response ever change?
___
*[`src/renderer/hooks/papi-hooks/use-dialog-callback.hook.ts` line 73 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngtdhp52o3710kn1fBT:-Ngtdhp52o3710kn1fBU:bejo94h) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/hooks/papi-hooks/use-dialog-callback.hook.ts#L73)):*
> ```XML
>       setIsShowingDialog(true);
>       try {
>        [...]

2023-10-16 22:07 UTC, tjcouch-sil reviewed
Using the existing pathways certainly reduces complications. It also theoretically will allow us one day to split P.B into a multi-window application more easily (UX might want dialogs [in their own window like in PT9](https://discord.com/channels/1064938364597436416/1163467866625019934/1163484331663179856), though it seems they will discuss and get back to us). It also gives us a nice pathway to preserving dialogs between refreshes if we ever want to put the effort into making that happen.

Also, MUI dialogs' modality probably would need some work anyway since I imagine they don't have any recommended ways to synchronize modality between multiple windows as we will have one day. Not to say it wouldn't be a head-start; just that it would also need work.

These things being said, it's probably most that I just went with what I perceived to be a low-resistance path. We could always change things in the future. I would not say, though, that I intended to put this in just to get past tech demo.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/553#-:-NgsdhlX50QvhoGf_2dv:b-1dgxwi)* status: 11 of 45 files reviewed, 23 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/src/hello-someone/hello-someone.ts` line 319 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpK6OD8E5YNPFNrsZi:-NgsfTxM1BfLqCcuSUSF:bfq6zgf) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/extensions/src/hello-someone/hello-someone.ts#L319)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nit: use `info`.
</blockquote></details>

Oops! Thanks :)
___
*[`extensions/src/hello-world/web-views/hello-world.web-view.tsx` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpNBO33pIQeiyFe8hF:-NgsfY163PoJcwInnU9k:by5ubzg) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/extensions/src/hello-world/web-views/hello-world.web-view.tsx#L90)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nit: I'm pretty sure this doesn't need to be here since a literal string is a string.
</blockquote></details>

Actually unfortunately `'None'` in this case is interpreted as type `"None"`, not type `string`, probably because it's a hard-baked const string. I had to ponder the differences in the way TypeScript interprets specific strings vs `string` overall. I believe the difference is when TypeScript determines that the variable can change. So `let thing = 'stuff'` is type `string`, but `const thing = 'stuff'` is type `"stuff"`.

So this needs to be type asserted here because of this issue (as mentioned in the JSDoc for `useDialogCallback` [here](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/hooks/papi-hooks/use-dialog-callback.hook.ts#L38)). Basically I'm using the type of this parameter to determine if the returned result type can be undefined or not, and this is the consequence. :p not the greatest thing, but maybe people won't mind it being `undefined` in general and won't run into this much. Just not sure what the best approach was here, so I went with this.
___
*[`extensions/src/hello-world/web-views/hello-world.web-view.tsx` line 90 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtX9pO844__WNGvOUf:-NgtvOuOAlsD2_r6riiX:b-3uo2qg) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/extensions/src/hello-world/web-views/hello-world.web-view.tsx#L90)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Can we come up with a way for this hook to work without requiring the caller to remember to call `useRef`?  This design I assume means if someone forgets then the renderer will spin re-rendering.  It feels fragile.
</blockquote></details>

Yeah, I think I'd like to think of some way to improve this, too... Though I'd prefer to put that feedback in #552 and think about it then (I added it as a new bullet). This is following current patterns of our custom hooks. Maybe we ought to say options should never change unless you unmount and remount a component! But I don't want to do that here in just one place without a big-picture reflection and discussion. Maybe there's a better way, but I can't think of one currently.
___
*[`src/extension-host/extension-host.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpOqWy-T-D07fTDc5r:-Ngsgd3v70NYPQEn7eJV:b-62gwzj) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/extension-host/extension-host.ts#L12)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

@irahopkinson - TJ and I were talking about this sort of naming.  In the newer design we talked about, we're separating the "server" code that is only meant to run in a specific process from the "client" code that is meant to run in any process that wants to use the "server."  We talked about naming that "server" code with `host`.  Do you have a different idea for naming?
</blockquote></details>

This `.service.host` file describes the actual implementation on a process of a service as we deliberated over in #203 long ago. Matt implemented the first service, `project-lookup.service.ts`, with this pattern, then we discussed changing the name to fit our current patterns a bit better.

I suggested this naming scheme to promote file-name-search (Ctrl+P) discoverability:

![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/DA6alsUoi-KwBA7j3BGpa8_c/image.png)

In a call, we decided on `.service-host`, `.service`, and `.service-model` as it is apparently more consistent with [our style guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide).

(Sorry, Matt; I wrote this before you responded. Didn't mean to rewrite what you said)
___
*[`src/extension-host/services/papi-backend.service.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpPCX29TS_8ipd-f2F:-NgtAQYs-dUySnPLkVqW:b-eqoag2) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/extension-host/services/papi-backend.service.ts#L26)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This doesn't follow our filename convention. What are you trying to convey with this filename? Would `project-lookup-service.model` work?
</blockquote></details>

This `.service.model` file describes the shape of a service. Matt implemented the first service from #203, `project-lookup.service.ts`, with this pattern of a separate interface file describing the service, then we discussed changing the name to fit our current patterns a bit better.

I suggested this naming scheme to promote file-name-search (Ctrl+P) discoverability:

![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/DA6alsUoi-KwBA7j3BGpa8_c/image.png)

I'd prefer to keep the name through `.service` intact so it is easy to search on file name and find all three relevant files. Do you have any thoughts?
___
*[`src/extension-host/services/papi-backend.service.ts` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpPUxTEipoLArjkRYE:-NgtAq3R1VcJyaIgudkG:b-q64pkt) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/extension-host/services/papi-backend.service.ts#L29)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This doesn't follow our filename convention. What are you trying to convey with this filename? Would `dialog-service.model` work?
</blockquote></details>

See above.
___
*[`src/renderer/index.tsx` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/5 [...]

2023-10-16 22:08 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/553)* status: 11 of 45 files reviewed, 23 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`src/extension-host/services/papi-backend.service.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpPCX29TS_8ipd-f2F:-NguX0t-5TtJXIyqQ7xG:b-hvuzx5) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/extension-host/services/papi-backend.service.ts#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This `.service.model` file describes the shape of a service. Matt implemented the first service from #203, `project-lookup.service.ts`, with this pattern of a separate interface file describing the service, then we discussed changing the name to fit our current patterns a bit better.

I suggested this naming scheme to promote file-name-search (Ctrl+P) discoverability:

![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/DA6alsUoi-KwBA7j3BGpa8_c/image.png)

I'd prefer to keep the name through `.service` intact so it is easy to search on file name and find all three relevant files. Do you have any thoughts?
</blockquote></details>

Oh, sorry, I forgot to update this discussion. We concluded in making all these `.service-whatever.ts`


<!-- Sent from Reviewable.io -->

2023-10-17 04:12 UTC, irahopkinson requested changes
> Reviewed 7 of 7 files at r2, 32 of 34 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/553)* status: all files reviewed, 12 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpcR9S8qLly-fVDpqe:-NgvWYVw5gbA6Fvqq-MP:bahy06j) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/dialog-base.data.ts#L29)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm not exactly sure what you're asking here, so I will clarify some things in case that helps us to know what we're talking about:

These three are part of the dialog definition, which is determined by the dialog creator and is not changeable when calling dialogs. Each dialog can have different sizes and such, but extension developers can't change the built-in dialog sizes.

However, developers can change these values for their own webviews (and conceivably their own custom dialogs whenever we get that in with #551). Are you suggesting they shouldn't be able to define their own sizes for these? I imagine they should be able to set up their webviews and dialogs to match their content size appropriately, but maybe we could specify absolute minimums that they can't go below. Any thoughts?
</blockquote></details>

What if the viewport is smaller than the `initialSize`? I'll leave off discussing this as probably what I was initially thinking of is out of scope here and fits in #551.
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 119 at r4](https://reviewable.io/reviews/paranext/paranext-core/553#-NgvXbPv0Ue-72OPzB-P:-NgvXbPv0Ue-72OPzB-Q:b-5gvppe) ([raw file](https://github.com/paranext/paranext-core/blob/4853186774e2e86e8a82748ad7d07e5976140d8b/src/renderer/components/dialogs/dialog-base.data.ts#L119)):*
> ```XML
> /**
>  * Set the functionality of submitting and canceling dialogs. This should be called specifically by
>  * `dialog.service.host.ts` immediately on startup and by nothing else. This is only here to
> ```

Change to `service-host` now. There might be a bunch of these renames in comments you should search for.



_Code quote:_
```XML
service.host
```
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngpi7z2Ew0GEyWFps1l:-NgvdJJ546lgXGvSova3:byuqk8y) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L13)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm not a huge fan of this either... I suppose we could change it as suggested, but it breaks from our current pattern with commands and such where we have mapped types that work directly from const strings. I definitely appreciate a desire to change them to use const references, though... But that would require putting them on the actual PAPI, not just on the `papi.d.ts`, and we would have to figure out letting extensions add their own unless we wanted our internal ones using consts on the PAPI and everyone else's using magic strings. Any thoughts? Maybe we could put them on a [`CachedDataProvider`](https://github.com/paranext/paranext-core/issues/498)? Seems like a lot of work for a bunch of strings, but maybe it's worth haha I dunno
</blockquote></details>

Yeah, that larger discussion is out of scope here. But you could remove one magic string by declaring and exporting this in `dialog-definition.model.ts`.
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpiumKAMr5YX7403CF:-NgveFvf4tjySM5oazS7:b-8sxlv4) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Yeah, unfortunately the way I wrote `usePromise`, it re-runs the function every time the default state is changed, so even the default state has to be a stable reference. So wrapping the empty array in a `useMemo` makes it a stable reference. We could actually probably put it in a `useRef`, but it probably isn't particularly impactful. I made an issue #552 to revise these hooks like making the default state not reactive so we don't have to do weirdness like this.

The default if the argument is unspecified is `undefined`. I just didn't want to account for that value in this context, so I made it `[]`.
</blockquote></details>

Ok. Do you get a stable reference if an empty array const is declared outside the funtion definition?
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpkLaE1X6NNAJysCQF:-Ngveof67vUD2AVhV-VP:bedy7b4) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L23)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'd say we should probably make some larger issue around rich text editing. It would have impacts on a lot of things including our Project Notes data api and such. Would be good to nail this down at some point.

Created #557
</blockquote></details>

Err, #557 doesn't seem to cover what I'm getting at since a dialog prompt doesn't need to be editable rich text. If `prompt` was  of type`string | JSX.Element` then we could format the prompt. However, a valid answer to my first question could be "we are keeping it simple as a string for now".
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngpm3Zn97rS2n7i8Gzp:-NgvkbnA1HJVFLHECNpd:b-1r7wrw) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L37)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

If I freeze it, does that make it any better? :) (actually I'm going to go freeze it now because it should be frozen haha oops) In my mind, frozen reference consts seem pretty much equivalent to primitive type consts (and they're both runtime consts unlike in many other languages), but I wasn't really sure what would be best. I believe the naming convention specifications are not specific enough to clearly dictate what to do in this situation, and I believe we are already inconsistent throughout our code base regarding this convention. It's probably [best to consult the team](https://stackoverflow.com/questions/1352875/naming-convention-for-a-variable-that-works-like-a-constant) on this to figure out what will help us best as a whole. Could we add a line to the style discussions about this rather than figuring out here?

Also, interestingly, I think our style guide as it is written right now dictates that we make all constants PascalCase because that's [the C# convention](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names#naming-conventions) and there is nothing stating otherwise. I don't know that we're doing this anywhere on the node side. Oops haha oh well.
</blockquote></details>

Freezing it does it for me.

I'm not seeing what you are seeing in the [Code Style Guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide). The only mention of "the C# convention" is in the [C#-specific Guidelines](https://github.com/paranext/paranext/wiki/Code-Style-Guide#c-specific-guidelines) section which doesn't apply to TS code. However, I do agree [...]

2023-10-17 15:13 UTC, lyonsil requested changes
Lots of good stuff here.  I just have one lingering concern.

> Reviewed 33 of 34 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/553#-:-NgyBbkz9s0SrxGC3-wI:bsgvnsz)* status: all files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/hello-world/web-views/hello-world.web-view.tsx` line 90 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtX9pO844__WNGvOUf:-Ngy49I7BoL3Qsys97nB:b-u9ew2d) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/extensions/src/hello-world/web-views/hello-world.web-view.tsx#L90)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Yeah, I think I'd like to think of some way to improve this, too... Though I'd prefer to put that feedback in #552 and think about it then (I added it as a new bullet). This is following current patterns of our custom hooks. Maybe we ought to say options should never change unless you unmount and remount a component! But I don't want to do that here in just one place without a big-picture reflection and discussion. Maybe there's a better way, but I can't think of one currently.
</blockquote></details>

Ok - I added some thoughts to that ticket.
___
*[`src/renderer/index.tsx` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtY_ge9wlYrrw2LdwW:-Ngy4f3j113fHRjeSYUM:b-yjhg8o) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/index.tsx#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Each service that initializes internally awaits anything that the service depends on. Everything in the React stuff doesn't need the services to start in order to get to first paint, so we don't need to await these services. Most of these services (except the web view provider service; I think I probably just put it here because I had a lot on my mind and wanted to just have it spin up) are initialized here because they set up request handlers on the renderer process that other processes need to use.

We do need to strengthen our initialization sequence and our exception handling throughout the software at some point, but I would consider that to be far outside the scope of this issue.
</blockquote></details>

I don't think it's outside the scope of this issue to add `await` to the front of initializing functions we're adding onto.  As a general practice we ought to be awaiting all `async` functions without good reason.  If you really don't want to await these, can you add an explicit comment saying why we aren't awaiting?
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 104 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtZwHJ74YBhOd0zUH5:-NgyAXLc85KyIC8oHVtR:b-xq575j) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/components/dialogs/dialog-base.data.ts#L104)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I don't know what we would want to do if it failed (which seems rather unlikely and like a larger problem than just this one dialog request), so I figured might as well make the important parts synchronous so the things that need to happen when this is called from React happen and leave out the rest for now. I thought we could make a synchronous call to close the tab if we end up deciding to make synchronous `dockLayout` calls from the web view service available (which I kinda hope we do before long since it seems like it would help with a lot of things).

I'll make an IIFE here so we log more contextual info in case this does ever happen to be a problem. Let me know if you have any thoughts on what else you think we should do if anything.
</blockquote></details>

Thanks, I think that's a reasonable step to take.  I agree this is an unusual and unlikely situation, but those are exactly the kinds of things that require extra logging or other checking because if they happen they will be baffling without extra data.
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngpm3Zn97rS2n7i8Gzp:-Ngy7XmUCXP40yO5RhBw:b-lqdky8) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L37)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Freezing it does it for me.

I'm not seeing what you are seeing in the [Code Style Guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide). The only mention of "the C# convention" is in the [C#-specific Guidelines](https://github.com/paranext/paranext/wiki/Code-Style-Guide#c-specific-guidelines) section which doesn't apply to TS code. However, I do agree that the [TypeScript-specific Guidelines](https://github.com/paranext/paranext/wiki/Code-Style-Guide#typescript-specific-guidelines) are not clear on what to do in this case.
</blockquote></details>

Ok, I'm probably crossing C# patterns here.  Freezing makes sense to me.
___
*[`src/renderer/hooks/papi-hooks/use-dialog-callback.hook.ts` line 87 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtfWUHBydE3mIaxM89:-NgyA69FCEsMuK3udAC3:b-uv4tn) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/hooks/papi-hooks/use-dialog-callback.hook.ts#L87)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The dependency array for `useCallback` is used to create a new callback function, not to run the function itself like in a `useEffect`. Setting a state in a callback that is listening for changes to that state is fine; it will just (appropriately) create a new function with the updated state on the next render. If we had a `useEffect` here, we would either not want to do this or establish some base case like in normal recursion. Preferably avoid doing it somehow :joy:
</blockquote></details>

Thanks for the clarification!
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 239 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngtbbla6ry6YOOrw9NY:-Ngy9H0k8Z4dGcHvYU5W:bv5u7gs) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/components/docking/paranext-dock-layout.component.tsx#L239)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

That would be a wise thing to work out in another issue regarding float size/position limits for all tabs as this is a big conversation. Since before this PR, you have been able to set webviews to whatever size you want, and they can totally block the screen and prevent you from doing anything. There's also some complication regarding what to do if the window is so small that even reasonable tabs and dialogs don't fit.
</blockquote></details>

Sounds good - opened https://github.com/paranext/paranext-core/issues/558 to track going forward.


<!-- Sent from Reviewable.io -->

2023-10-17 16:16 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/553)* status: 40 of 45 files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/src/hello-world/web-views/hello-world.web-view.tsx` line 90 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtX9pO844__WNGvOUf:-NgyM2En-b2-emawvmVN:b1wneoh) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/extensions/src/hello-world/web-views/hello-world.web-view.tsx#L90)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ok - I added some thoughts to that ticket.
</blockquote></details>

Gotcha. Thanks!
___
*[`src/renderer/index.tsx` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtY_ge9wlYrrw2LdwW:-NgyOLSH4qWP-805YDjh:bbtsx0a) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/index.tsx#L19)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I don't think it's outside the scope of this issue to add `await` to the front of initializing functions we're adding onto.  As a general practice we ought to be awaiting all `async` functions without good reason.  If you really don't want to await these, can you add an explicit comment saying why we aren't awaiting?
</blockquote></details>

I'll put an IIFE on each like we agreed on in the other case. Seems like an easy quick fix that we can both be happy with.

I also filed #559
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpcR9S8qLly-fVDpqe:-NgyOEqF3ogOLr_FiVJJ:bhcruwn) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/dialog-base.data.ts#L29)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

What if the viewport is smaller than the `initialSize`? I'll leave off discussing this as probably what I was initially thinking of is out of scope here and fits in #551.
</blockquote></details>

Oh actually Matt brought up the same concern! He filed #558 on it. Thanks!
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 104 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtZwHJ74YBhOd0zUH5:-NgyO1RJ0NR29EKBr5If:b1wneoh) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/components/dialogs/dialog-base.data.ts#L104)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Thanks, I think that's a reasonable step to take.  I agree this is an unusual and unlikely situation, but those are exactly the kinds of things that require extra logging or other checking because if they happen they will be baffling without extra data.
</blockquote></details>

Gotcha. Thanks!
___
*[`src/renderer/components/dialogs/dialog-base.data.ts` line 119 at r4](https://reviewable.io/reviews/paranext/paranext-core/553#-NgvXbPv0Ue-72OPzB-P:-NgyPUM7DPfSwDxUHCSr:boyexb3) ([raw file](https://github.com/paranext/paranext-core/blob/4853186774e2e86e8a82748ad7d07e5976140d8b/src/renderer/components/dialogs/dialog-base.data.ts#L119)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Change to `service-host` now. There might be a bunch of these renames in comments you should search for.
</blockquote></details>

Done. Thanks!
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpiumKAMr5YX7403CF:-NgyNt5W0yfENi6i9FH_:b-pf3bt3) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L18)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Ok. Do you get a stable reference if an empty array const is declared outside the funtion definition?
</blockquote></details>

Yep! I'm just lazy :joy:
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngpm3Zn97rS2n7i8Gzp:-NgyNjBkCP9dAyRSk105:b-ymnajy) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L37)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ok, I'm probably crossing C# patterns here.  Freezing makes sense to me.
</blockquote></details>

Oh yeah, you're right - I thought I remembered we adhered to C# conventions in all cases where we don't state otherwise even in TypeScript code, but I see now it says "C#-specific". Thanks!

Regardless, if we want to have a discussion (not part of this PR) to see what communicates best to our team, that works for me. I wasn't totally sure on this point, and it seems there isn't a particular consensus. Seems it's team-by-team.
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 239 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngtbbla6ry6YOOrw9NY:-NgyNdho1vpo-qAUqrq8:b-1pe5yw) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/components/docking/paranext-dock-layout.component.tsx#L239)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Sounds good - opened https://github.com/paranext/paranext-core/issues/558 to track going forward.
</blockquote></details>

Awesome. Thank you!


<!-- Sent from Reviewable.io -->

2023-10-17 17:25 UTC, lyonsil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/553#-:-Ngyf2MYCnN2D4hZbgqQ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/renderer/index.tsx` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/553#-NgtY_ge9wlYrrw2LdwW:-Ngycz2a08aQ5w3Bz2bI:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/43a6f990f87ec09959fc31470e7073abac598d71/src/renderer/index.tsx#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'll put an IIFE on each like we agreed on in the other case. Seems like an easy quick fix that we can both be happy with.

I also filed #559
</blockquote></details>

Thanks!
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngpm3Zn97rS2n7i8Gzp:-Ngye99RDHWrWK-frMEA:b-xkqs0z) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L37)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oh yeah, you're right - I thought I remembered we adhered to C# conventions in all cases where we don't state otherwise even in TypeScript code, but I see now it says "C#-specific". Thanks!

Regardless, if we want to have a discussion (not part of this PR) to see what communicates best to our team, that works for me. I wasn't totally sure on this point, and it seems there isn't a particular consensus. Seems it's team-by-team.
</blockquote></details>

In C#, generally I only saw `UPPER_SNAKE_CASE` used for compile-time constants.  There isn't an equivalent in TS/JS, but I think a constant that cannot be changed after it is set is probably close.

Agree this doesn't hold up the current PR.


<!-- Sent from Reviewable.io -->

2023-10-17 19:53 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/553)* status: 42 of 45 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-Ngpi7z2Ew0GEyWFps1l:-NgzBYLqBrA8hzgveqrV:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L13)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yeah, that larger discussion is out of scope here. But you could remove one magic string by declaring and exporting this in `dialog-definition.model.ts`.
</blockquote></details>

Done
___
*[`src/renderer/components/dialogs/select-project.dialog.tsx` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/553#-NgpkLaE1X6NNAJysCQF:-NgzB_HtDrMT7jcmjCye:b-iil90z) ([raw file](https://github.com/paranext/paranext-core/blob/116977602423ee2754dbac00fdb9f0b1c7cf6cf8/src/renderer/components/dialogs/select-project.dialog.tsx#L23)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Err, #557 doesn't seem to cover what I'm getting at since a dialog prompt doesn't need to be editable rich text. If `prompt` was  of type`string | JSX.Element` then we could format the prompt. However, a valid answer to my first question could be "we are keeping it simple as a string for now".
</blockquote></details>

I'd like to touch base and get in sync on this, but let's leave it for another time if that's ok - I would indeed like to keep it simple for now.


<!-- Sent from Reviewable.io -->

2023-10-17 20:55 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/553#-:-NgzPuCE358Di2gkCPkC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-17 20:55 UTC, merged