#460 Make the Resource Viewer editable as a proof-of-concept Scripture editor
paranext/paranext-core pull request #556
Opened 2023-10-16 15:16 UTC by FoolRunning

Note that to test this, the WEB project needs to be editable.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-core/556)

2023-10-16 15:49 UTC, tjcouch-sil approved these changes
Awesome!! Thanks! Note: Tim and I discussed that he will look into putting this work in the ParatextPDP as well though that is probably not easily testable for the time being. Will probably need to test in https://github.com/paranext/paranext-core/issues/448 or something

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556#-:-Ngt6mSA1dPSD7FeBckI:b3t0nt1)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-16 16:10 UTC, lyonsil submitted a review, later dismissed
How does one make a project editable?

The USFM data provider is a good place to start.  I wonder if it would be good to apply these changes to `ParatextProjectStorageInterpreter.cs`, `SetProjectData` at the same time.   I expect the USFM data provider to go away not long after the tech demo.  It was just a placeholder to start.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556#-:-Ngt8K-G36NgBG67pUXg:b-169qts)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning)

___
*[`c-sharp/NetworkObjects/UsfmDataProvider.cs` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/556#-NgtEWpaBdZAEK5lIotz:-NgtEWpaBdZAEK5lIou-:bfj4s8g) ([raw file](https://github.com/paranext/paranext-core/blob/d86f4e230cee73aae6640c05d7d2a6ec4409c304/c-sharp/NetworkObjects/UsfmDataProvider.cs#L99)):*
> ```Smalltalk
>     }
> 
>     public ResponseToRequest SetUsx(VerseRef vref, string newUsx)
> ```

I'm sensing the potential benefit of some USX helper classes.  This is more of an FYI for the future than any change that is needed now, but I think it would be nice to have something that understands the inner details of USX separate from the data provider class itself.


<!-- Sent from Reviewable.io -->

2023-10-24 15:32 UTC, tjcouch-sil requested changes
Awesome! Thanks for the hard work getting this updated! Just one thing that is probably a typo.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556#-:-NhXJ6gK48GleyHCQfY7:b-u73mjn)* status: all files reviewed, 2 unresolved discussions (waiting on @FoolRunning)

___
*[`extensions/src/usfm-data-provider/index.d.ts` line 209 at r2](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXIqc85ySB6BQ3B-kZ:-NhXIqc85ySB6BQ3B-k_:bs7dezc) ([raw file](https://github.com/paranext/paranext-core/blob/cd2923b321f6be666160f47f05f4e6b6216573cd/extensions/src/usfm-data-provider/index.d.ts#L209)):*
> ```XML
>      * @returns unsubscriber function (run to unsubscribe from listening for updates)
>      */
>     subscribeVerseUSX(
> ```

I think this should be `subscribeChapterUSX`, right?


<!-- Sent from Reviewable.io -->

2023-10-24 15:45 UTC, lyonsil requested changes
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning)

___
*[`c-sharp/Projects/ProjectStorageInterpreter.cs` line 58 at r2](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXKwDy8H5IizcYt5hX:-NhXKwDz1VTcgN1BOpY_:b-jkwr87) ([raw file](https://github.com/paranext/paranext-core/blob/851ecbcfb0abc73e677bf9ea9aea95ea577a7700/c-sharp/Projects/ProjectStorageInterpreter.cs#L58)):*
> ```Smalltalk
>                 return GetProjectData(dataScope);
>             case "setProjectData":
>                 var setProjectReturn = SetProjectData(dataScope, args[1]!.ToJsonString());
> ```

It looks like you changed all these to pass through JsonNodes instead of strings, but then you just call `ToString()` on the other side.  This also requires pulling in more `using` statements, mixing both `System.Text.Json` and `Newtonsoft.Json` in the same file.  This has caused bugs for us in the past because there are some classes with identical names, creating some ambiguity about what classes you're actually pulling in when working with JSON.  Since you aren't actually using the `JsonNode` properties or functions on the other side, please revert these changes and pass strings instead of the `JsonNode` objects.


<!-- Sent from Reviewable.io -->

2023-10-24 15:53 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556)* status: all files reviewed, 5 unresolved discussions (waiting on @FoolRunning)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXMSTn3QUCH_pUpGmV:-NhXMSTn3QUCH_pUpGmW:b2f0t6) ([raw file](https://github.com/paranext/paranext-core/blob/cd2923b321f6be666160f47f05f4e6b6216573cd/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L1)):*
> ```Smalltalk
> using System.Net.Http.Json;
> ```

Why is this being included?  If we can keep the number of JSON-related imports down, that would be nice.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 276 at r2](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXNPviAYrJ_tBRpJ82:-NhXNPviAYrJ_tBRpJ83:b-tv39bm) ([raw file](https://github.com/paranext/paranext-core/blob/cd2923b321f6be666160f47f05f4e6b6216573cd/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L276)):*
> ```Smalltalk
> 
>     /// <summary>
>     /// Converts usfm to usx, but does not annotate
> ```

What are the implications of "does not annotate"?  Should we file an "Ideas" issue to improve our USX transformations in the future?


<!-- Sent from Reviewable.io -->

2023-10-24 15:53 UTC, lyonsil reviewed
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556)* status: all files reviewed, 5 unresolved discussions (waiting on @FoolRunning)



<!-- Sent from Reviewable.io -->

2023-10-24 18:38 UTC, lyonsil requested changes
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/NetworkObjects/UsfmDataProvider.cs` line 72 at r3](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXxDo-CJzN1i2cmVJ9:-NhXxDo-CJzN1i2cmVJA:b-9lghoq) ([raw file](https://github.com/paranext/paranext-core/blob/d98055c4a8df60fbf430284e970ab1ff5d822d4d/c-sharp/NetworkObjects/UsfmDataProvider.cs#L72)):*
> ```Smalltalk
>     }
> 
>     private ResponseToRequest GetUsx(string args)
> ```

There is already a `GetUsx` below.  To help avoid confusion between identical function names, can we either call this something else or rename the other function?
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXMSTn3QUCH_pUpGmV:-NhXw4UB4pHpSrhYysij:b6yd8xd) ([raw file](https://github.com/paranext/paranext-core/blob/cd2923b321f6be666160f47f05f4e6b6216573cd/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L1)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

See my comment below on why this was deemed necessary.
</blockquote></details>

This is not the same as JsonNode which you reference below.  That's from the System.Text.Json references.  Why System.Net.Http.Json, too?  That's 3 different JSON libraries in one file.  Do you really need System.Net.Http.Json?
___
*[`c-sharp/Projects/ProjectStorageInterpreter.cs` line 58 at r2](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXKwDy8H5IizcYt5hX:-NhXwKvyBUZbmqWrxU35:b-3wa108) ([raw file](https://github.com/paranext/paranext-core/blob/851ecbcfb0abc73e677bf9ea9aea95ea577a7700/c-sharp/Projects/ProjectStorageInterpreter.cs#L58)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

This was done on purpose since the previous ``ToJsonString`` call that was passed to the ``SetProjectData`` method is the thing that escapes all of the USX data (i.e. not a good thing to pass into ``SetProjectData``). I chose to pass in the whole ``JsonNode`` so that the various handlers can determine how the argument should be processed. If I, instead, changed the ``ToJsonString`` to be ``ToString``, this would mean that we'd have to re-parse the JSON string if it was actually a JSON object that was needed in the handler.
</blockquote></details>

It's not a good thing to have both Newtonsoft.Json and System.Text.Json in the same file for reasons I mentioned.  Can you just change the `ToJsonString` calls to `ToString` so we don't have to add the other references by passong JsonNodes?  Also, are you sure that the change to `ToString` from `ToJsonString` didn't effect any of the other, existing functions?


<!-- Sent from Reviewable.io -->

2023-10-24 18:38 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/NetworkObjects/UsfmDataProvider.cs` line 72 at r3](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXxDo-CJzN1i2cmVJ9:-NhXyqjP4_AiFGNpvcM1:b-ds6l8f) ([raw file](https://github.com/paranext/paranext-core/blob/d98055c4a8df60fbf430284e970ab1ff5d822d4d/c-sharp/NetworkObjects/UsfmDataProvider.cs#L72)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

There is already a `GetUsx` below.  To help avoid confusion between identical function names, can we either call this something else or rename the other function?
</blockquote></details>

Same with `SetUsx`.


<!-- Sent from Reviewable.io -->

2023-10-26 13:35 UTC, FoolRunning reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`c-sharp/NetworkObjects/UsfmDataProvider.cs` line 72 at r3](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXxDo-CJzN1i2cmVJ9:-NhgAPW-4w0ED-gcXFEt:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/d98055c4a8df60fbf430284e970ab1ff5d822d4d/c-sharp/NetworkObjects/UsfmDataProvider.cs#L72)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Same with `SetUsx`.
</blockquote></details>

Done
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXMSTn3QUCH_pUpGmV:-Nhg88JJ8K2XnOHWx_uR:bfdygsw) ([raw file](https://github.com/paranext/paranext-core/blob/cd2923b321f6be666160f47f05f4e6b6216573cd/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L1)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This is not the same as JsonNode which you reference below.  That's from the System.Text.Json references.  Why System.Net.Http.Json, too?  That's 3 different JSON libraries in one file.  Do you really need System.Net.Http.Json?
</blockquote></details>

Didn't notice that. Removed.
___
*[`c-sharp/Projects/ProjectStorageInterpreter.cs` line 58 at r2](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXKwDy8H5IizcYt5hX:-Nhg8FR_AM4mE6klSd0H:b-k8xytx) ([raw file](https://github.com/paranext/paranext-core/blob/851ecbcfb0abc73e677bf9ea9aea95ea577a7700/c-sharp/Projects/ProjectStorageInterpreter.cs#L58)):*
> Can you just change the `ToJsonString` calls to `ToString` so we don't have to add the other references by passong JsonNodes?

Fine.

> Also, are you sure that the change to `ToString` from `ToJsonString` didn't effect any of the other, existing functions?

As long as the node is actually a value that is a string, this is best. However, this will fail to work if we ever have a handler that needs a JSON object since I think ``ToString`` will fail for a non-value node.


<!-- Sent from Reviewable.io -->

2023-10-26 14:09 UTC, lyonsil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556#-:-NhgJOHs8MuQ5BXcFPDp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-10-26 17:30 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thank you! Sorry I was holding up the PR - I didn't notice til now

> Reviewed 2 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/556#-:-Nhh1KXu0QkF6H-y-mnW:b-bkbpv6)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`c-sharp/Projects/ProjectStorageInterpreter.cs` line 58 at r2](https://reviewable.io/reviews/paranext/paranext-core/556#-NhXKwDy8H5IizcYt5hX:-Nhh1B8l70uEfuPumW-y:b-r29w0d) ([raw file](https://github.com/paranext/paranext-core/blob/851ecbcfb0abc73e677bf9ea9aea95ea577a7700/c-sharp/Projects/ProjectStorageInterpreter.cs#L58)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

> Can you just change the `ToJsonString` calls to `ToString` so we don't have to add the other references by passong JsonNodes?

Fine.

> Also, are you sure that the change to `ToString` from `ToJsonString` didn't effect any of the other, existing functions?

As long as the node is actually a value that is a string, this is best. However, this will fail to work if we ever have a handler that needs a JSON object since I think ``ToString`` will fail for a non-value node.
</blockquote></details>

That sounds like a problem - I imagine we will want to do JSON when we make the USJ endpoints. But I'd rather get this in and worry about it later honestly :grimacing:


<!-- Sent from Reviewable.io -->

2023-10-26 18:32 UTC, merged