Enable webviews to change their title and icon url
paranext/paranext-core pull request #583
Opened 2023-10-20 17:32 UTC by tjcouch-sil

Refactored how React webviews work a bit so a few `WebViewProps` are now passed in for ease of access:
- useWebViewState
- updateWebViewDefinition
- getWebViewDefinitionUpdatableProperties

Also added `getBookUsx` to the USFM data provider to get data for Ira.

Subscribing to updates to the webview definition was split into #581 since that did not seem particularly valuable at this time.

Resolves #445

2023-10-20 20:33 UTC, lyonsil requested changes
Looks good overall.  Just one thing I see that should probably be addressed.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/583#-:-NhDmcIM2c-lYg2p7dWT:b-cw3in4)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/NetworkObjects/UsfmDataProvider.cs` line 100 at r1](https://reviewable.io/reviews/paranext/paranext-core/583#-NhDZkvt3H13jyrURNzF:-NhDZkvt3H13jyrURNzG:buszjto) ([raw file](https://github.com/paranext/paranext-core/blob/a75aa7bca889fcc803a963ff728550b19d05444a/c-sharp/NetworkObjects/UsfmDataProvider.cs#L100)):*
> ```Smalltalk
>     private string GetUsxForBook(VerseRef vref)
>     {
>         XmlDocument usx = ConvertUsfmToUsx(GetUsfm(vref.BookNum, -1), vref.BookNum);
> ```

Minor nit: It seems like it would be a little cleaner to leave off the `-1` since the intent is that the default argument covers the case of getting a book, not a chapter.
___
*[`c-sharp/NetworkObjects/UsfmDataProvider.cs` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/583#-NhDYX-4AOVuyVvFp0mc:-NhDYX-4AOVuyVvFp0md:b-y5roki) ([raw file](https://github.com/paranext/paranext-core/blob/a75aa7bca889fcc803a963ff728550b19d05444a/c-sharp/NetworkObjects/UsfmDataProvider.cs#L130)):*
> ```Smalltalk
>     /// <param name="chapterNum">The chapter for which to get USFM or -1 for the whole book</param>
>     /// <returns>USFM</returns>
>     private string GetUsfm(int bookNum, int chapterNum = -1)
> ```

It would be a little cleaner to use `int?` defaulted to `null` than `int` defaulted to `-1`.  Then switch your check below about whether the value is set or not.

If you want to keep it as an `int` instead of `int?`, then you probably want to change the check from `chapterNum == -1` to `chaptuerNum >= 0`.  If someone passes a value less than `-1` I'm not sure what is intended to happen.


<!-- Sent from Reviewable.io -->

2023-10-20 21:15 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/583)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`c-sharp/NetworkObjects/UsfmDataProvider.cs` line 100 at r1](https://reviewable.io/reviews/paranext/paranext-core/583#-NhDZkvt3H13jyrURNzF:-NhDvsgy7-r465zBAH1S:boyexb3) ([raw file](https://github.com/paranext/paranext-core/blob/a75aa7bca889fcc803a963ff728550b19d05444a/c-sharp/NetworkObjects/UsfmDataProvider.cs#L100)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Minor nit: It seems like it would be a little cleaner to leave off the `-1` since the intent is that the default argument covers the case of getting a book, not a chapter.
</blockquote></details>

Done. Thanks!
___
*[`c-sharp/NetworkObjects/UsfmDataProvider.cs` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/583#-NhDYX-4AOVuyVvFp0mc:-NhDvto818quJPvwQNld:boyexb3) ([raw file](https://github.com/paranext/paranext-core/blob/a75aa7bca889fcc803a963ff728550b19d05444a/c-sharp/NetworkObjects/UsfmDataProvider.cs#L130)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It would be a little cleaner to use `int?` defaulted to `null` than `int` defaulted to `-1`.  Then switch your check below about whether the value is set or not.

If you want to keep it as an `int` instead of `int?`, then you probably want to change the check from `chapterNum == -1` to `chaptuerNum >= 0`.  If someone passes a value less than `-1` I'm not sure what is intended to happen.
</blockquote></details>

Done. Thanks!


<!-- Sent from Reviewable.io -->

2023-10-20 21:33 UTC, lyonsil requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/583)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`c-sharp/NetworkObjects/UsfmDataProvider.cs` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/583#-NhDYX-4AOVuyVvFp0mc:-NhE-O48CTElKH4yw1sy:bxj0wr5) ([raw file](https://github.com/paranext/paranext-core/blob/a75aa7bca889fcc803a963ff728550b19d05444a/c-sharp/NetworkObjects/UsfmDataProvider.cs#L130)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Done. Thanks!
</blockquote></details>

Thanks - once you update the param comment it should be good to go!


<!-- Sent from Reviewable.io -->

2023-10-23 13:23 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/583)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`c-sharp/NetworkObjects/UsfmDataProvider.cs` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/583#-NhDYX-4AOVuyVvFp0mc:-NhRgxs-4ff8swYSMH6s:b-ngepr8) ([raw file](https://github.com/paranext/paranext-core/blob/a75aa7bca889fcc803a963ff728550b19d05444a/c-sharp/NetworkObjects/UsfmDataProvider.cs#L130)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Thanks - once you update the param comment it should be good to go!
</blockquote></details>

:confounded: done


<!-- Sent from Reviewable.io -->

2023-10-23 13:57 UTC, lyonsil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/583#-:-NhRosKm2ZMFi1SDx3ij:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-23 13:58 UTC, merged