Fix Scripture update events not causing data providers to re-fetch data
paranext/paranext-core pull request #644
Opened 2023-11-15 17:32 UTC by tjcouch-sil

Update events on C# were being double-serialized. As such, subscribers weren't receiving updates. Additionally, not all relevant data types were announced as updated.

Before, the update looked like this:
![image](https://github.com/paranext/paranext-core/assets/104016682/aa7e09be-2779-4a51-9a62-e65a6ecccb55)

Now, the update looks like this:
![image](https://github.com/paranext/paranext-core/assets/104016682/993a10c3-469e-44e2-affb-b23912a5772d)

2023-11-15 18:11 UTC, lyonsil approved these changes
Thanks for fixing this quickly!

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/644#-:-NjJAWth7F8Udi1sr_M1:b-j9iko1)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-15 18:19 UTC, FoolRunning requested changes
I know you hate doing it, but it would be best if tests were written for this.

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/644#-:-NjJCGag2k6TsUKcpt14:bschriv)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-15 21:34 UTC, FoolRunning approved these changes
Since this is for the tech demo, I'm jut going to approve it.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/644#-:-NjJtSgr1sh6BJkfKWMF:b-foos8b)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-15 21:34 UTC, merged

2023-11-16 13:43 UTC, tjcouch-sil commented
Scripture update event PR https://github.com/paranext/paranext-core/pull/646