Load extensions from file, add very primitive webviews
paranext/paranext-core pull request #67
Opened 2023-03-08 23:35 UTC by tjcouch-sil

Resolves #30

2023-03-09 04:21 UTC, irahopkinson requested changes
I'm at the end of my day so I'll publish what I've reviewed so far. Thanks for all your work on this.

2023-03-09 04:21 UTC, irahopkinson commented on .eslintrc.js
> +    'react/jsx-props-no-spreading': 'off',
Hmm, reading the rule it seems a good one to keep on. What is the reasoning for disabling it?

2023-03-09 04:21 UTC, irahopkinson commented on .eslintrc.js
> +    'react/jsx-props-no-spreading': 'off',
Putting these in alphabetically order would make finding them easier.

2023-03-09 04:21 UTC, irahopkinson commented on extensions/hello-someone/hello-someone.js
> +console.log('Hello Someone is importing!');
Use `logger` or remove it. Here and below.

2023-03-09 04:21 UTC, irahopkinson commented on extensions/hello-someone/hello-someone.js
> +console.log('Hello Someone is importing!');
JS files should have `'use strict';` on the first line.

Is there some reason this can't be a TS file?

2023-03-09 04:21 UTC, irahopkinson commented on extensions/hello-someone/hello-someone.js
> +console.log('Hello Someone is importing!');
`extensions` may need their own `.eslintrc.js` file if you want to allow it, since having it set to `warn` will probably still fail in CI builds (as it should).

2023-03-09 04:21 UTC, irahopkinson commented on extensions/hello-someone/manifest.json
> +  "activationEvents": ["onCommand:hello-someone.hello-someone"]
The extension registers 2 commands, should `hello-someone.echo-someone-renderer` be included here?

2023-03-09 14:21 UTC, tjcouch-sil commented on extensions/hello-someone/hello-someone.js
> +console.log('Hello Someone is importing!');
Regarding the logger, I will add the current logger to the `papi`, but I also made #68 for making the logger contextual to an extension.

Regarding `.eslintrc.js`, See reply on the TS comment. :)

2023-03-09 14:22 UTC, tjcouch-sil commented on extensions/hello-someone/hello-someone.js
> +console.log('Hello Someone is importing!');
This can't currently be a TS file because I have not set up webpack, babel, etc on extensions yet. That will be a fair bit of work, so I put it off for now. Extensions will probably need their own whole JS ecosystem and build setup and such.

See https://github.com/paranext/paranext-extension-template/issues/1

2023-03-09 14:25 UTC, tjcouch-sil commented on extensions/hello-someone/manifest.json
> +  "activationEvents": ["onCommand:hello-someone.hello-someone"]
Added

2023-03-09 14:38 UTC, tjcouch-sil commented on extensions/hello-someone/hello-someone.js
> +console.log('Hello Someone is importing!');
Update: I added an `.eslintrc.js` file because `'use strict;'` was giving an error. It appears maybe strict mode is automatically enabled on modules. But I don't understand that situation exactly (might as well be safe rather than sorry) and I think it is a good thing to go ahead and make a separate `.eslintrc.js` file if for no other reason than for practice. Plus, webpack will definitely enable strict mode whenever we get to that point.

For more info:
https://eslint.org/docs/latest/rules/strict
https://stackoverflow.com/questions/49386015/javascript-use-strict-is-unnecessary-inside-of-modules

2023-03-09 14:40 UTC, tjcouch-sil commented on .eslintrc.js
> +    'react/jsx-props-no-spreading': 'off',
Sounds good. Done

2023-03-09 14:57 UTC, tjcouch-sil commented on .eslintrc.js
> +    'react/jsx-props-no-spreading': 'off',
I personally dislike this rule to be honest. If I have an object whose type I know is the `Props` type for a component, I want to be able to spread that object into the component so that I don't have to go to every place where I am programmatically generating that component and add the new prop from the object whose type I already know is the `Props` type for that component. It makes enough sense not to spread props when the object type is not the specific `Props` type for that component (like if you're hand-building a component with a number of variables), but the rule doesn't have an exception case for that. So I just turned it off.

It seems reasonable not to pass unintended props down, of course. However, I think that because TypeScript gives us the power to check types, it is arguably worth leveraging it in this context. The reason they say not to pass props down is for maintainability; I think we have increased maintainability when passing `Props`-type objects into their own component. Again, I'm particularly considering the scenario of passing a `Props`-type object into its respective component, not generally spreading props; I think there is an argument for not spreading props where the types don't match up well. I think the readability argument is also somewhat diminished because of TypeScript and the object being `Props` type as well.

I think it would make sense to re-enable the rule for `html` because of the detail they mention that spreading in HTML elements messes up React warning logs. I'll do that for now.

I have not discussed this perspective with others before; looking forward to hearing your thoughts! Maybe we can discuss, come down on a decision, and write a bit in the style guide if we cannot leverage the rule to enforce whatever decision we make.

For reference, the rule is https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md

2023-03-10 03:45 UTC, irahopkinson requested changes
Its really nice to see all the clean up of things going into better places in this PR , great job along with everything else.

2023-03-10 03:45 UTC, irahopkinson commented on src/node/util/util.ts
> +  const fullUri = uri.includes('://') ? uri : `app://${uri}`;
Should this use the `APP_SCHEME`, i.e. ```const fullUri = uri.includes('://') ? uri : `${APP_SCHEME}://${uri}`;```?

2023-03-10 03:45 UTC, irahopkinson commented on src/extension-host/services/ExtensionService.ts
> +type ExtensionInfo = Readonly<
My learning of TS over the years have said to favor `interface` over `type`, in fact to use `type` only when necessary. Here one of those reasons is its easier to 'inherit' an `interface` and more readable too. You can resolve this if you just want to add this to our code style discussion.

2023-03-10 03:45 UTC, irahopkinson commented on src/extension-host/services/ExtensionService.ts
> +type ExtensionInfo = Readonly<
Read this https://www.typescriptlang.org/play#example/types-vs-interfaces for a better explanation.

2023-03-10 03:45 UTC, irahopkinson commented on src/extension-host/services/ExtensionService.ts
> + * WARNING: This does not shim functionality out of extenions! Do not run this alone. Only run wrapped in activateExtensions()
nit: sp: extensions

2023-03-10 03:45 UTC, irahopkinson commented on src/main/main.ts
> +extensionHostService.start();
Don't we want to do this along with the other services setup above? I.e. only init the extension host after the network is initialized? If there is a good reason for where it is now then feel free to resolve this comment yourself.

2023-03-10 03:45 UTC, irahopkinson commented on src/main/services/dotnet-data-provider.service.ts
> + * TODO: fix this to be a more elegant shutdown
Actually, we still need to be able to hard kill. The plan is to add a `stopDotnetDataProvider` method to stop it cleanly and then only kill it if that fails.

2023-03-10 03:45 UTC, irahopkinson commented on src/main/services/extension-host.service.ts
> +      "Could not connect to extension host's stderr or stdout! You will not see extension host console logs here.",
To be consistent perhaps add '[extension host]' to the beginning of this message.

2023-03-10 03:45 UTC, irahopkinson commented on src/main/services/extension-host.service.ts
> +      "Could not connect to extension host's stderr or stdout! You will not see extension host console logs here.",
BTW when would this actually happen? Did you encounter it?

2023-03-10 03:45 UTC, irahopkinson commented on src/node/services/NodeFileSystemService.ts
> +  const dirents = await fs.promises.readdir(getPathFromUri(uri), {
It's fine to use well known abbrevations like 'dir' in names. A better name might be `dirEntries` and `dirEntry` below in the arrow function.

2023-03-10 03:45 UTC, irahopkinson commented on src/renderer/components/WebView.tsx
> +      contents: React.ReactNode;
Add this to the import rather than rely on the global `React`.

2023-03-10 03:45 UTC, irahopkinson commented on src/renderer/components/WebView.tsx
> +    // TODO: This doesn't work. Probably because the browser considers it to be cross-origin since we are loading from a script. Figure out how to fix this
Is this potentially a killer if we can't find a sutable way around this?

2023-03-10 03:45 UTC, irahopkinson commented on src/renderer/components/WebView.tsx
> +    return () => {
You could make this DRYer by declaring it, calling it and then returning it.

2023-03-10 03:45 UTC, irahopkinson commented on src/renderer/index.tsx
>  NetworkService.initialize();
This is unnecessary since `CommandService.initialize()` immediately calls `NetworkService.initialize();`

2023-03-10 03:45 UTC, irahopkinson commented on src/shared/services/WebViewService.ts
> +      .length === 1;
I'm not sure I get this code. It seems to be saying that a successfull unsubscribe is when there is only 1 item left in the callback array irrespective of how many there were to start with. What am I missing here?

2023-03-10 03:45 UTC, irahopkinson commented on src/shared/services/WebViewService.ts
> +  if (webViewPapi) {
This is not normal flow. Normal flow is check exceptions and throw and normal code after is not indented. This doesn't change its function but is easier to read.

2023-03-10 03:45 UTC, irahopkinson commented on src/shared/services/WebViewService.ts
> +  return Promise.resolve();
It looks like you are intentionally ignoring the promise result from the dynamic import. Can you explain why?

2023-03-10 03:45 UTC, irahopkinson commented on src/shared/services/WebViewService.ts
> +/** Commands that this process will handle if it is the renderer. Registered automatically at initialization */
nit: empty line missing above.

2023-03-10 15:45 UTC, tjcouch-sil commented on src/extension-host/services/ExtensionService.ts
> +type ExtensionInfo = Readonly<
I have come to nearly the opposite conclusion up to this point, actually. I don't mind either one, but, because I can do disparate union types in  I generally prefer `type` and often use it unless I'm dealing with classes or something where you can't use disparate union types (see the playground's linked StackOverflow answer point 4 about classes/interfaces being ['static blueprints'](https://stackoverflow.com/questions/37233735/interfaces-vs-types-in-typescript/52682220#52682220)).

Regarding 'disparate union types', See `PapiUtil.ts`'s `ComplexResponse` type, which unions two types whose `success` boolean is either `true` or `false`, which distinguishes them completely and determines what members that `ComplexResponse` has. Same thing with `Message` in `NetworkConnectorTypes.ts`. Essentially, there are a number of cases in which I find it useful to have a certain property on an object determine what type it is, and TypeScript supports this with `type` but not with `interface` (because it's a static blueprint). For example, I reimplemented `ComplexResponse` with `interface`s here (I called it `Response`, though):
![image](https://user-images.githubusercontent.com/104016682/224359201-16a0afbf-e552-44df-9712-cb796d9baaec.png)

TypeScript throws an error basically saying you can't have completely disparate interface subtypes like this:
![image](https://user-images.githubusercontent.com/104016682/224359272-12067126-12ac-4bb5-bbc3-de640372d38d.png)

As I have come to do more and more generic-style programming, I have appreciated this disparate union type feature of types more and more, so I now use them unless I want to use an interface for some reason. I think there is an additional benefit of not having declaration merging (point 5 in that StackOverflow answer) - in general, this is probably not a good feature in my mind because it seems types should be the same everywhere you use them. However, I think it would be very useful to consider how we might leverage declaration merging for our PAPI, though!

The playground you sent gives a very powerful illustration regarding error messages - it's nice to see the cleaner error messages of `interface`s.

It would be good to discuss this topic further another time. For now, let's put a line in the code style discussion and resolve this if that sounds good to you. Thank you for this! It was good to get refreshed on the differences and preferences.

2023-03-10 15:49 UTC, tjcouch-sil commented on src/node/util/util.ts
> +  const fullUri = uri.includes('://') ? uri : `app://${uri}`;
Yes!! Good catch. Fixed. Thank you! That could have resulted in some problems if we rename the `app` scheme to `user` as I am considering doing :)

2023-03-10 15:49 UTC, tjcouch-sil commented on src/extension-host/services/ExtensionService.ts
> + * WARNING: This does not shim functionality out of extenions! Do not run this alone. Only run wrapped in activateExtensions()
Thank you! I think I wrote all this before we had CSpell. Fixed.

2023-03-10 15:51 UTC, tjcouch-sil commented on src/main/main.ts
> +extensionHostService.start();
I believe this is the right place to have it. Launching everything at the very beginning probably means everything can get started sooner. I added retry initial connection logic for the extension host so it just works whenever the main NetworkService is finished initializing. Maybe we can do the same for the C# client in #52. Does that seem reasonable?

2023-03-10 15:52 UTC, tjcouch-sil commented on src/main/services/dotnet-data-provider.service.ts
> + * TODO: fix this to be a more elegant shutdown
Good point :) fixed.

2023-03-10 16:03 UTC, tjcouch-sil commented on src/main/services/extension-host.service.ts
> +      "Could not connect to extension host's stderr or stdout! You will not see extension host console logs here.",
Added `[extension host]`. Thanks!

Actually, this error has never happened to my memory. But `spawn` with the `stdio` option set like I made it gives a `ChildProcessByStdio<null, internal.Readable, internal.Readable>`, which could fail to create `stderr` or `stdout` (from the JSDoc of `stderr`: "The subprocess.stderr property can be null if the child process could not be successfully spawned."). As such, I put that check in to make sure it gets properly created. I updated the `extensionHost` type to reflect this change. However, I could definitely see an argument that we don't need to ignore `stdin`. But I dunno haha seems like not a big issue to consider at the moment. Maybe one day we will try piping through `stdio` instead of WebSocket.

2023-03-10 16:04 UTC, tjcouch-sil commented on src/node/services/NodeFileSystemService.ts
> +  const dirents = await fs.promises.readdir(getPathFromUri(uri), {
I called it `dirents` because the type is `fs.Dirent[]`, but I certainly see your point. I will change it!

2023-03-10 16:06 UTC, tjcouch-sil commented on src/renderer/components/WebView.tsx
> +      contents: React.ReactNode;
Fixed

2023-03-10 16:11 UTC, tjcouch-sil commented on src/renderer/components/WebView.tsx
> +    // TODO: This doesn't work. Probably because the browser considers it to be cross-origin since we are loading from a script. Figure out how to fix this
To be honest, I don't know exactly. I can kinda see some arguments for the concept that we might not really need `iframe`s in the first place, but I currently feel like there will be benefits regarding locking down internet access (we would be able to specify a different content security policy for the code that is running in iframes). However, we will probably need to make ways to plug into our DOM without `iframe`s anyway like in annotations, so I kinda wonder what difference it would make. Beyond that, I am not even really certain of the implications of not catching these `iframe` exceptions. The things I have run into have not crashed Paranext, but I imagine there are probably ways to do so from an `iframe`. Not sure if being able to catch them would solve the problem. I asked the architecture advisory board to ask around about this, but I have not heard anything back. I feel like I remember you may have asked someone about this too - did you hear anything?

2023-03-10 16:20 UTC, tjcouch-sil commented on src/renderer/components/WebView.tsx
> +    return () => {
Tweaked it a bit. Hopefully this is a bit like what you were looking for, but there are enough differences that it doesn't quite work 1-to-1

2023-03-10 16:22 UTC, tjcouch-sil commented on src/renderer/index.tsx
>  NetworkService.initialize();
`NetworkService` starts the websocket server and client, so I thought it would be best to start it asap. It probably doesn't make much difference, but I think it's worth having that be the first thing that happens. Let me know your thoughts.

2023-03-10 16:26 UTC, tjcouch-sil commented on src/shared/services/WebViewService.ts
> +      .length === 1;
Ah, yes, this is a bit obtuse. `splice` returns an array of whatever it took out from the original array (empty if it took nothing). So I'm checking to make sure `splice` actually removed the event handler. Added a comment to explain:
"Remove the handler from the list of callbacks. Successful if splice successfully removed one element from the array."

2023-03-10 16:27 UTC, tjcouch-sil commented on src/shared/services/WebViewService.ts
> +      .length === 1;
Oh hmm, I did just notice that splicing `-1` removes the element 1 from the end. Oops. Will fix

2023-03-10 16:31 UTC, tjcouch-sil commented on src/shared/services/WebViewService.ts
> +  if (webViewPapi) {
Good catch! Fixed.

2023-03-10 16:37 UTC, tjcouch-sil commented on src/shared/services/WebViewService.ts
> +  return Promise.resolve();
When I don't have `return Promise.resolve()` here, eslint gets me for not consistently returning. In the guard at the top of the function, I return a promise, so eslint gets mad when I don't return a promise in any code paths. So essentially I await the dynamic import if I need to do it, and I use its result appropriately. But I don't need to return anything from this function in general, so I just resolve to nothing when finished.

Maybe it reads a bit better with a comment and `return undefined`. Let me know what you think!

2023-03-10 16:38 UTC, tjcouch-sil commented on src/shared/services/WebViewService.ts
> +/** Commands that this process will handle if it is the renderer. Registered automatically at initialization */
Fixed.

2023-03-10 19:40 UTC, irahopkinson commented on src/main/main.ts
> +extensionHostService.start();
Sounds good, I added a comment in #52.

2023-03-10 19:51 UTC, irahopkinson commented on src/renderer/components/WebView.tsx
> +    // TODO: This doesn't work. Probably because the browser considers it to be cross-origin since we are loading from a script. Figure out how to fix this
I think I said I could ask a paid contractor if you needed. I believe you were pursuing other options first.

2023-03-10 19:57 UTC, irahopkinson commented on src/renderer/components/WebView.tsx
> +    return () => {
That was towards the end of my day yesterday and TBH I didn't notice the differences - that one was a `addEventListener` and the other `removeEventListener` nor the difference in the message. However I really like what you have done with it and that makes those differences more obvoius (despite me missing before). Thanks.

2023-03-10 20:18 UTC, irahopkinson commented on src/shared/services/WebViewService.ts
> +    if (eventHandlerIndex < 0) return false; // Did not find this callback
I think our style guide says comments on their own line - not at the end of a line?

2023-03-10 20:18 UTC, irahopkinson commented on src/extension-host/services/ExtensionService.ts
> +type ExtensionInfo = Readonly<
Sounds good.

2023-03-10 20:21 UTC, irahopkinson requested changes
Nearly there. Since this is such a large PR I would feel better if @FoolRunning reviewed it also but fine if you want to get it in sooner.

2023-03-10 20:46 UTC, tjcouch-sil commented on src/shared/services/WebViewService.ts
> +    if (eventHandlerIndex < 0) return false; // Did not find this callback
I don't believe our code style guide has guidance on where to put comments other than rule-disabling comments. I put a line in the code style guide thread for us to discuss :)

2023-03-11 00:57 UTC, irahopkinson approved these changes

2023-03-11 00:57 UTC, merged

2023-03-13 18:19 UTC, FoolRunning commented on src/extension-host/extension-types/IExtension.ts
> +  deactivate?: UnsubscriberAsync;
Why is there a deactivate in addition to having the unsubscriber? It seems like only one of those should be needed (I would prefer the deactivate event/method).

2023-03-13 18:19 UTC, FoolRunning commented on src/renderer/components/WebView.tsx
> +export function WebView({ contents, hasReact = false }: WebViewProps) {
Since the type of ``contents`` is defined by what ``hasReact`` is set to, doesn't this make the default signature contain a string ``contents``? I would vote to change the default to be ``true`` since I would expect by far the most common thing that extensions will provide would be a react component.

2023-03-13 18:19 UTC, FoolRunning commented on src/renderer/context/papi-context/papi-context.ts
> +/** All React components to be exposed on the papi */
This is not a react component. Yes?

2023-03-13 18:19 UTC, FoolRunning commented on src/shared/data/FileSystemTypes.ts
> + *  - resources:// - goes to the resources directory installed in the app
How does an extension get access to its own data (e.g. it has an icon or even an XML file containing data it needs to load)? I would expect those files to be inside the extension's folder, not in the app or resources folders. Maybe that will be a part of of the PAPI, but isn't implemented yet?

2023-03-13 18:19 UTC, FoolRunning commented on extensions/hello-someone/manifest.json
> +    "onCommand:hello-someone.echo-someone-renderer"
Why are the ``activationEvents`` specified in the manifest? I didn't see any place that this information is used. Is this just for documentation sake or is it going to have some function?

2023-03-13 18:51 UTC, tjcouch-sil commented on src/extension-host/extension-types/IExtension.ts
> +  deactivate?: UnsubscriberAsync;
I was thinking of making a simple api where you return the unsubscriber from `activate`, but then if you needed more complex functionality, you could use `deactivate`. VSCode actually passes in a 'context' object in `activate` that provides a place to set up unsubscribers kinda similarly to what I made in `activate`. I don't think `activate` will return an unsubscriber for long. I can remove it now if you'd prefer! Or make a card for it.

Somewhat related contextual papi cards: #50, #68

2023-03-13 18:52 UTC, tjcouch-sil commented on extensions/hello-someone/manifest.json
> +    "onCommand:hello-someone.echo-someone-renderer"
They are not used yet. They will be used for lazy-loading extensions in #51 :)

2023-03-13 18:53 UTC, tjcouch-sil commented on src/shared/data/FileSystemTypes.ts
> + *  - resources:// - goes to the resources directory installed in the app
Not implemented yet - I was thinking that could go in with #50 and #53 :)

2023-03-13 18:54 UTC, tjcouch-sil commented on src/renderer/context/papi-context/papi-context.ts
> +/** All React components to be exposed on the papi */
Good catch! Fixed in #72

2023-03-13 18:56 UTC, tjcouch-sil commented on src/renderer/components/WebView.tsx
> +export function WebView({ contents, hasReact = false }: WebViewProps) {
Good point! Fixed in #72

2023-03-13 19:24 UTC, FoolRunning commented on src/extension-host/extension-types/IExtension.ts
> +  deactivate?: UnsubscriberAsync;
No, if there's a plan to possibly remove it, then that's fine for now.