Add ways to use WebSocket and XMLHttpRequest in the renderer
paranext/paranext-core pull request #678
Opened 2023-12-12 20:11 UTC by lyonsil

2023-12-12 22:18 UTC, tjcouch-sil requested changes
Exciting!! I like it! A few thoughts for you.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/678#-:-NlV5v0C4C8CDOmZZURl:b-d6alk3)* status: all files reviewed, 6 unresolved discussions (waiting on @lyonsil)

___
*[`src/renderer/index.tsx` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUp6kU7B1B_tFJW_kF:-NlUp6kU7B1B_tFJW_kG:b7blkc6) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L16)):*
> ```XML
> 
> window.onerror = (message, source, lineno, colno, error): void => {
>   logger.error(`An error occurred: ${message}`);
> ```

Does this solve #79? Sounds nice! Could you please add a comment explaining what this code block does (I think I get it, but it would be good to know for sure and would be good for others to know in the future)?

Is there a need for these to be in different log statements, or could they be concatenated in one (with `\n` between if desired)? There's just a lot of extra stuff that gets added to each log line, and I think they might even be asynchronously logged and could get split up by other processes logging stuff in the middle (not sure about that, but it seems possible).
___
*[`src/renderer/index.tsx` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUpQ0L-J0Pt9uqVdd_:-NlUpQ0L-J0Pt9uqVdda:bsz2ov0) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L23)):*
> ```XML
> };
> 
> if (window.process) {
> ```

Could you please add comments explaining what you're doing with this? I'm not really clear on what's going on here. Maybe something particular to electron, but I don't know the difference between this code and the code above. Or can this code go in `main.ts`? It looks like maybe it's `node` code (`process` is a global variable in node but not in browser, `require` is only in node, and electron stuff generally belongs in `node`). Seems like this wouldn't do anything unless `nodeIntegration` was on (not the case for us). But I could be missing something.
___
*[`src/renderer/index.tsx` line 48 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUtYFi-uwcpvA1kVOI:-NlUtYFi-uwcpvA1kVOJ:b-iaavgr) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L48)):*
> ```XML
> 
>     await Promise.allSettled([
>       commandService.initialize(),
> ```

We're losing individualized error logs for each of these services - do you know if initialization/start errors in these services would look relatively identifiable? I dunno if it's really a huge deal, so not blocking. :shrug: 
___
*[`src/renderer/services/renderer-web-socket.service.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUma3_5mt71RD3fYGn:-NlUma3_5mt71RD3fYGo:b88b3lk) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-web-socket.service.ts#L27)):*
> ```XML
>     hostname === '::1' ||
>     hostname.endsWith('.local') ||
>     parseInt(port, 10) === parseInt(`${WEBSOCKET_PORT}`, 10)
> ```

Why restrict the user from accessing `localhost`? Hmm, is that some kind of attack vector even if we only allow it when not set offline? I haven't really considered it; would be glad to hear your thoughts. I understand the desire to avoid letting them hook into the papi itself (things get weird haha Inception, anyone?), but I'm not sure on first hand why not allow `localhost` connections.

For example, if someone is testing their Sneeze Board extension against their local development Sneeze Board Server, they would probably need to use a local connection (with a different port than `WEBSOCKET_PORT` which is probably worth blocking). Or I guess some unimportant Bible Translation tool that has some websocket connection, but that's not worth mentioning when we can discuss the Sneeze Board server. (I don't particularly have one in mind, just by the way)

(Regarding Inception)
![](https://c.tenor.com/EYPJjOVJOHYAAAAC/tenor.gif)
___
*[`src/renderer/services/renderer-web-socket.service.ts` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUnp2-E3tSpFMKRwgc:-NlUnp2-E3tSpFMKRwgd:b-xevsqd) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-web-socket.service.ts#L71)):*
> ```XML
> 
>   constructor(url: string | URL, protocols?: string | string[]) {
>     // TODO: Hook into something that checks for whether the platform is in offline mode
> ```

Absolutely not necessary for this PR, but it could be helpful to go ahead and make some placeholder function in `internet.service.ts` that checks for online or offline now that we have multiple places that need it. Then you can put it here, in the XMLHttpRequest class, and in the `fetch` in that service. Just to be able to keep track a little better for the future.

Feel 100% free to resolve this with no action!
___
*[`src/renderer/services/renderer-xml-http-request.service.ts` line 67 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlV1Ec_AbM0uuZTaqdf:-NlV1Ec_AbM0uuZTaqdg:b-oe52ut) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-xml-http-request.service.ts#L67)):*
> ```XML
>     // If we ever need something better we could use a Proxy or just hold an inner object.
>     // eslint-disable-next-line no-constructor-return
>     return new XMLHttpRequest();
> ```

Since this doesn't actually give us the ability to filter the internet access, I think it would be best to go ahead and make a proxy or inner object so we can drop in the offline check when it is time.


<!-- Sent from Reviewable.io -->

2023-12-12 22:29 UTC, irahopkinson requested changes
Thanks for your work on this.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/678#-:-NlV8TE66m8NG5bhp_oU:b7tt6m2)* status: all files reviewed, 10 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`lib/papi-dts/papi.d.ts` line 4797 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUmPrQ5SWDWrRS4ZCq:-NlUmPrQ5SWDWrRS4ZCr:b520fjg) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/lib/papi-dts/papi.d.ts#L4797)):*
> ```XML
>      * Note that the Node WebSocket implementation is different and not wrapped here.
>      */
>     webSocket: typeof PapiRendererWebSocket;
> ```

Since this is a class (type) I would label it in PascalCase, i.e. `WebSocket`. Same for `XMLHttpRequest` below.
___
*[`src/renderer/index.tsx` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUpQ0L-J0Pt9uqVdd_:-NlV7q4L5NTacrPu9URz:b-qu691f) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L23)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Could you please add comments explaining what you're doing with this? I'm not really clear on what's going on here. Maybe something particular to electron, but I don't know the difference between this code and the code above. Or can this code go in `main.ts`? It looks like maybe it's `node` code (`process` is a global variable in node but not in browser, `require` is only in node, and electron stuff generally belongs in `node`). Seems like this wouldn't do anything unless `nodeIntegration` was on (not the case for us). But I could be missing something.
</blockquote></details>

I think this shouldn't be here as it breaks electron isolation to directly call an electron backend dialog from the renderer. Please remove it or if we really need it call it through the preload.
___
*[`src/renderer/index.tsx` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUky0ICYm9AMUquzVP:-NlUky0ICYm9AMUquzVQ:b-7ctaig) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L45)):*
> ```XML
> 
>     // This needs to run before web views start running and after the network service is running
>     blockWebSocketsToPapiNetwork();
> ```

BTW there is a small window between network init and this being turned off. Even though that may not actaullty be an issue, I wonder if it would be better to default this to off (not allowed) and enable it where needed, as a better pattern?
___
*[`src/renderer/index.tsx` line 47 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUlS77BRUW1WJsycfU:-NlUlS77BRUW1WJsycfV:b-wnw4nr) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L47)):*
> ```XML
>     blockWebSocketsToPapiNetwork();
> 
>     await Promise.allSettled([
> ```

FYI thanks for cleaning up this section of the code.
___
*[`src/renderer/services/renderer-web-socket.service.ts` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUo7K2AvZdnnfrzzPJ:-NlUo7K2AvZdnnfrzzPK:b-nbiynp) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-web-socket.service.ts#L23)):*
> ```XML
>   // Check if the hostname is one of the common localhost values or the port number matches
>   return (
>     hostname === 'localhost' ||
> ```

Add in `hostname.endsWith('.localhost')` since the domain `platform.localhost` is also `localhost`.
___
*[`src/renderer/services/renderer-web-socket.service.ts` line 80 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlV5OYT7UWoJjK2LOd0:-NlV5OYT7UWoJjK2LOd1:b-d8ca8i) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-web-socket.service.ts#L80)):*
> ```XML
>     // If we ever need something better we could use a Proxy or just hold an inner object.
>     // eslint-disable-next-line no-constructor-return
>     return new WebSocket(url, protocols);
> ```

I think this should be `super(url, protocols)`? Same in the other service.



_Code quote:_
```XML
return new WebSocket(url, protocols);
```


<!-- Sent from Reviewable.io -->

2023-12-13 18:31 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/678)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`lib/papi-dts/papi.d.ts` line 4797 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUmPrQ5SWDWrRS4ZCq:-NlZOPKT9hT7aHkcjP5u:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/lib/papi-dts/papi.d.ts#L4797)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Since this is a class (type) I would label it in PascalCase, i.e. `WebSocket`. Same for `XMLHttpRequest` below.
</blockquote></details>

Done
___
*[`src/renderer/index.tsx` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUp6kU7B1B_tFJW_kF:-NlYxsWX0ciF_rP6M-DF:b3sp8kf) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L16)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Does this solve #79? Sounds nice! Could you please add a comment explaining what this code block does (I think I get it, but it would be good to know for sure and would be good for others to know in the future)?

Is there a need for these to be in different log statements, or could they be concatenated in one (with `\n` between if desired)? There's just a lot of extra stuff that gets added to each log line, and I think they might even be asynchronously logged and could get split up by other processes logging stuff in the middle (not sure about that, but it seems possible).
</blockquote></details>

I just took all of this code out.  I have been running into cases (starting before I worked on this ticket) where around the end of start up, the renderer window simply closes without any logging or explanation of what is happening.  I did some looking up of what different people have tried to log when unhandled exceptions/errors occur, and I was just doing copy/paste to try to help track it down.  Of course after adding all the code the window closing stopped.
___
*[`src/renderer/index.tsx` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUpQ0L-J0Pt9uqVdd_:-NlYyqep8c4RtcH6m1XL:bkrpv6e) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L23)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I think this shouldn't be here as it breaks electron isolation to directly call an electron backend dialog from the renderer. Please remove it or if we really need it call it through the preload.
</blockquote></details>

See comment above.  Just trying to track down why the renderer is closing without any explanation.  I'm taking this code out since it's not really part of this ticket.
___
*[`src/renderer/index.tsx` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUky0ICYm9AMUquzVP:-NlYzCzf9YbMUCNPx5uo:b-7d0uyd) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L45)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW there is a small window between network init and this being turned off. Even though that may not actaullty be an issue, I wonder if it would be better to default this to off (not allowed) and enable it where needed, as a better pattern?
</blockquote></details>

In this process, it shouldn't matter that the small window exists.  What I am trying to prevent is extensions connecting back to the PAPI network, and extension code can't run in the renderer (I don't think at least) until the web view service starts up below.  The network service itself needs to create a web socket and connect back to PAPI network, though, so I can't really block it until the network service has its socket.

If there is a way for extension code to run before the services below start, then I agree some change like you're talking about will be needed.
___
*[`src/renderer/index.tsx` line 48 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUtYFi-uwcpvA1kVOI:-NlYzsvI1jlcVbB3ny1X:bqx9osj) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L48)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We're losing individualized error logs for each of these services - do you know if initialization/start errors in these services would look relatively identifiable? I dunno if it's really a huge deal, so not blocking. :shrug:
</blockquote></details>

You're right, this wasn't doing what I wanted it to do.  TS didn't read my mind this time.  I just added a util function that does what I was envisioning.
___
*[`src/renderer/services/renderer-web-socket.service.ts` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUo7K2AvZdnnfrzzPJ:-NlZKKWg17h8ovw3Qaec:b-achn9n) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-web-socket.service.ts#L23)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Add in `hostname.endsWith('.localhost')` since the domain `platform.localhost` is also `localhost`.
</blockquote></details>

Done - thanks
___
*[`src/renderer/services/renderer-web-socket.service.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUma3_5mt71RD3fYGn:-NlZKMfT92TLRPMfT9Bj:b-h1rgqe) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-web-socket.service.ts#L27)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why restrict the user from accessing `localhost`? Hmm, is that some kind of attack vector even if we only allow it when not set offline? I haven't really considered it; would be glad to hear your thoughts. I understand the desire to avoid letting them hook into the papi itself (things get weird haha Inception, anyone?), but I'm not sure on first hand why not allow `localhost` connections.

For example, if someone is testing their Sneeze Board extension against their local development Sneeze Board Server, they would probably need to use a local connection (with a different port than `WEBSOCKET_PORT` which is probably worth blocking). Or I guess some unimportant Bible Translation tool that has some websocket connection, but that's not worth mentioning when we can discuss the Sneeze Board server. (I don't particularly have one in mind, just by the way)

(Regarding Inception)
![](https://c.tenor.com/EYPJjOVJOHYAAAAC/tenor.gif)
</blockquote></details>

If an extension can connect back to the local computer using a websocket, they can join the PAPI network directly.  At that point there is no security, I think.  If we're trying to keep TS/JS extensions in some sort of sandbox, we have to prevent this.  If we're saying that network access == "I don't care, let this extension do anything it wants of any sort", then I can drop this.  I didn't think that's what we were saying, but I might be wrong.

If we're looking to enable local web sockets EXCEPT for the PAPI websocket, I can just block the websocket port.  I'm not super confident about that being a sufficient check, though, as technically port numbers can be specified in octal or hexadecimal form even though I don't think the standard WebSocket class understands those at this point.
___
*[`src/renderer/services/renderer-web-socket.service.ts` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUnp2-E3tSpFMKRwgc:-NlZOaYOCxAKKEsPodLs:b-isnmnf) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/servi [...]

2023-12-13 19:10 UTC, irahopkinson submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/678#-:-NlZ_Ew3CmAmiuYVx-ju:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/renderer/services/renderer-web-socket.service.ts` line 80 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlV5OYT7UWoJjK2LOd0:-NlZZLZjCaTfBKNCsIft:b-jfmrlk) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-web-socket.service.ts#L80)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I can change it, but why?  This is kind of confusing to me because `WebSocket` is both an interface and a `var`.  If I say `super`, that implies to me that I have subclassed a `class` or other object of some kind (i.e., I've inserted it into my object as the prototype).  However, since `interface`s aren't "real" from JS's standpoint, I would assume there is no prototype set automatically other than something generic like Object.  Thus I need to reference a real type to return, and TS is smart enough to know when I say `new WebSocket` it has to reference something that is an object instead of an interface.

Regardless of my word salad above, if I try to use `super(url, protocols)` I see this error:
```
'super' can only be referenced in a derived class.ts(2335)
```

I think that means I need to leave this as-is.
</blockquote></details>

Sorry, you are right, I read your class definition as `extends` but it actually says `implements`.


<!-- Sent from Reviewable.io -->

2023-12-13 22:37 UTC, tjcouch-sil requested changes
Thank you for the updates! Still a few things to discuss. We can have a call if you prefer. Just let me know :)

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/678#-:-Nl_Jpav1YNqF7-1Wa-X:b-j7lyue)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`src/renderer/index.tsx` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUp6kU7B1B_tFJW_kF:-Nl_DHGLEMPrVYoFvTAR:b-ok8vh2) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/index.tsx#L16)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I just took all of this code out.  I have been running into cases (starting before I worked on this ticket) where around the end of start up, the renderer window simply closes without any logging or explanation of what is happening.  I did some looking up of what different people have tried to log when unhandled exceptions/errors occur, and I was just doing copy/paste to try to help track it down.  Of course after adding all the code the window closing stopped.
</blockquote></details>

Bummer :( sorry about that. Hope we get it figured out!
___
*[`src/renderer/services/renderer-web-socket.service.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUma3_5mt71RD3fYGn:-Nl_Dkc0DVQ0JwaoQwxr:b-iulfl) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-web-socket.service.ts#L27)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If an extension can connect back to the local computer using a websocket, they can join the PAPI network directly.  At that point there is no security, I think.  If we're trying to keep TS/JS extensions in some sort of sandbox, we have to prevent this.  If we're saying that network access == "I don't care, let this extension do anything it wants of any sort", then I can drop this.  I didn't think that's what we were saying, but I might be wrong.

If we're looking to enable local web sockets EXCEPT for the PAPI websocket, I can just block the websocket port.  I'm not super confident about that being a sufficient check, though, as technically port numbers can be specified in octal or hexadecimal form even though I don't think the standard WebSocket class understands those at this point.
</blockquote></details>

Currently, my preference would be to block only the PAPI websocket port. Again, I haven't thought this through deeply, but what could an extension do if it connected back through the websocket that it couldn't do already through the PAPI? I guess they could register request handlers, not just command handlers... Not a huge deal probably. It gets kinda weird if they do that, though, so it seems nice to make a simple check to attempt to prevent them from connecting on our port. I'm still thinking it would be good to let them connect to other localhost ports, though, but I still could be missing something. Do you have a particular problem in mind to avoid regarding other local connections?
___
*[`src/renderer/services/renderer-xml-http-request.service.ts` line 67 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlV1Ec_AbM0uuZTaqdf:-Nl_FULo2mY5d4CtqLE_:b-sp8ptq) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-xml-http-request.service.ts#L67)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I can do it, but why?  I thought the online/offline mode was going to be set on start up and unchangeable without closing and reopening P.B.  If that's the case, then I don't know what we would actually do with a filter beyond whatever we will do within the Electron network filter magic we discussed a while back (which would affect things at a lower level than a proxied filter).

Note that the concern with `localhost` doesn't impact `XMLHttpRequest` because you can't use that to join the PAPI network.
</blockquote></details>

My intent with this issue was to allow these internet access routes to go through our code so we can do what we want to restrict/reroute it when offline or when they try to connect to something blacklisted. Right now, since the action of connecting to the internet in this class does not touch our code, we can't blacklist or reroute when we get that code in place without writing additional code in here to allow that to happen, whereas it is already in place in the other JS-based internet-connection places.

If you prefer to make another issue, we can get this code through. On rereading the issue description, I see I did not elaborate as clearly 
as I should have on this point. And as you mention, we may do all this stuff in the electron protocol anyway.
___
*[`src/shared/utils/util.ts` line 208 at r2](https://reviewable.io/reviews/paranext/paranext-core/678#-Nl_HlYq1G-5qcFApigs:-Nl_HlYq1G-5qcFApigt:b-6zymi5) ([raw file](https://github.com/paranext/paranext-core/blob/c7c5e23e17e136cd8659d6fa6558c8af80963137/src/shared/utils/util.ts#L208)):*
> ```XML
> /**
>  * Run an array of promises, and either return an array of the outcomes if they all were fulfilled
>  * or throw if at least one of them was rejected
> ```

Would you mind please clarifying that this throws with an error message including the error message for each rejected promise? I couldn't tell what made this different than [`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) without reading the code.

I also think the return value feels a bit weird since this function feels like `Promise.all`, but I address that in a comment below that is just a suggestion.
___
*[`src/shared/utils/util.ts` line 219 at r2](https://reviewable.io/reviews/paranext/paranext-core/678#-Nl_H55o7ObIZbKfo8L9:-Nl_H55o7ObIZbKfo8LA:b-4mzjcx) ([raw file](https://github.com/paranext/paranext-core/blob/c7c5e23e17e136cd8659d6fa6558c8af80963137/src/shared/utils/util.ts#L219)):*
> ```XML
>   if (rejections.length > 0) {
>     const reasons = rejections.map((rejection, index) => {
>       if (rejection.status !== 'rejected') return "Why doesn't TS know we already checked this?";
> ```

Honestly. This bothers me too 😂
___
*[`src/shared/utils/util.ts` line 220 at r2](https://reviewable.io/reviews/paranext/paranext-core/678#-Nl_HFtT1Kkue7qbSOhY:-Nl_HFtT1Kkue7qbSOhZ:b-qcdav4) ([raw file](https://github.com/paranext/paranext-core/blob/c7c5e23e17e136cd8659d6fa6558c8af80963137/src/shared/utils/util.ts#L220)):*
> ```XML
>     const reasons = rejections.map((rejection, index) => {
>       if (rejection.status !== 'rejected') return "Why doesn't TS know we already checked this?";
>       return `[${index}]: ${rejection.reason}`;
> ```

I think this function may be served well by having the same parameters and return as [`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all). I think the promises should be in the first parameter as an array of promises instead of being spread params to match with `Promise.all`. (I also would vote for an optional second parameter that is a message to include at the start of the thrown error so it's easier for us to identify what code failed, but that's definitely not required.) Right now, I think the return is guaranteed to be successful settled promises, so mapping them out to the actual promise results would probably be a nice quality-of-life improvement in addition to making the function feel more familiar like `Promise.all`. Then you could say in the JSDoc that this is just like `Promise.all` but with the additional error message logging as mentioned in an above comment.

This is just a suggestion to help make this function hopefully feel more natural to a JS dev. I do strongly s [...]

2023-12-14 15:26 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/678)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/renderer/services/renderer-web-socket.service.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUma3_5mt71RD3fYGn:-Nlct1Y45tAUOlV72iF7:b-61bd8w) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-web-socket.service.ts#L27)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Currently, my preference would be to block only the PAPI websocket port. Again, I haven't thought this through deeply, but what could an extension do if it connected back through the websocket that it couldn't do already through the PAPI? I guess they could register request handlers, not just command handlers... Not a huge deal probably. It gets kinda weird if they do that, though, so it seems nice to make a simple check to attempt to prevent them from connecting on our port. I'm still thinking it would be good to let them connect to other localhost ports, though, but I still could be missing something. Do you have a particular problem in mind to avoid regarding other local connections?
</blockquote></details>

Done - I don't have a concrete security attack in mind.
___
*[`src/renderer/services/renderer-xml-http-request.service.ts` line 67 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlV1Ec_AbM0uuZTaqdf:-NlcqOZU39jssnwqFrkV:b-jswxmz) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-xml-http-request.service.ts#L67)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

My intent with this issue was to allow these internet access routes to go through our code so we can do what we want to restrict/reroute it when offline or when they try to connect to something blacklisted. Right now, since the action of connecting to the internet in this class does not touch our code, we can't blacklist or reroute when we get that code in place without writing additional code in here to allow that to happen, whereas it is already in place in the other JS-based internet-connection places.

If you prefer to make another issue, we can get this code through. On rereading the issue description, I see I did not elaborate as clearly 
as I should have on this point. And as you mention, we may do all this stuff in the electron protocol anyway.
</blockquote></details>

Opened #681 for this purpose
___
*[`src/shared/utils/util.ts` line 208 at r2](https://reviewable.io/reviews/paranext/paranext-core/678#-Nl_HlYq1G-5qcFApigs:-NlcmIKh6_lcIxW6vQ-s:b-rc3h6e) ([raw file](https://github.com/paranext/paranext-core/blob/c7c5e23e17e136cd8659d6fa6558c8af80963137/src/shared/utils/util.ts#L208)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Would you mind please clarifying that this throws with an error message including the error message for each rejected promise? I couldn't tell what made this different than [`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) without reading the code.

I also think the return value feels a bit weird since this function feels like `Promise.all`, but I address that in a comment below that is just a suggestion.
</blockquote></details>

I'm moving this into a private helper function and dropping it from `utils`.
___
*[`src/shared/utils/util.ts` line 220 at r2](https://reviewable.io/reviews/paranext/paranext-core/678#-Nl_HFtT1Kkue7qbSOhY:-NlcnjoC2Ekpl0_b1dBq:b-sjpunz) ([raw file](https://github.com/paranext/paranext-core/blob/c7c5e23e17e136cd8659d6fa6558c8af80963137/src/shared/utils/util.ts#L220)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think this function may be served well by having the same parameters and return as [`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all). I think the promises should be in the first parameter as an array of promises instead of being spread params to match with `Promise.all`. (I also would vote for an optional second parameter that is a message to include at the start of the thrown error so it's easier for us to identify what code failed, but that's definitely not required.) Right now, I think the return is guaranteed to be successful settled promises, so mapping them out to the actual promise results would probably be a nice quality-of-life improvement in addition to making the function feel more familiar like `Promise.all`. Then you could say in the JSDoc that this is just like `Promise.all` but with the additional error message logging as mentioned in an above comment.

This is just a suggestion to help make this function hopefully feel more natural to a JS dev. I do strongly suggest doing this since this function should probably go in our shared npm library, but I don't think it's required.
</blockquote></details>

I'm going to move this into a private helper function and drop it from `utils`.  My purpose in creating it was to try and make a function that more naturally followed what I was hoping for and might want to use elsewhere, not to create something for a wider usage outside of our team.  It seems like me putting it here is causing confusion, and I don't think it's a great use of time to fiddle with the types for a function that no one else might ever care about.


<!-- Sent from Reviewable.io -->

2023-12-14 16:00 UTC, tjcouch-sil approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/678)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/renderer/services/renderer-web-socket.service.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlUma3_5mt71RD3fYGn:-Nld2Hfo2ckxZ4muLKhr:byuyeie) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-web-socket.service.ts#L27)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done - I don't have a concrete security attack in mind.
</blockquote></details>

Gotcha. Thanks! Definitely open to further action if we think of something :)
___
*[`src/renderer/services/renderer-xml-http-request.service.ts` line 67 at r1](https://reviewable.io/reviews/paranext/paranext-core/678#-NlV1Ec_AbM0uuZTaqdf:-Nld2RZ82brqwyeSqOIf:b-9755fn) ([raw file](https://github.com/paranext/paranext-core/blob/2dda646eff8de3c72c7b096a51a10e631299936a/src/renderer/services/renderer-xml-http-request.service.ts#L67)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Opened #681 for this purpose
</blockquote></details>

Thank you!
___
*[`src/shared/utils/util.ts` line 220 at r2](https://reviewable.io/reviews/paranext/paranext-core/678#-Nl_HFtT1Kkue7qbSOhY:-Nld2XCD9b7J54BI8akK:b-pb9exw) ([raw file](https://github.com/paranext/paranext-core/blob/c7c5e23e17e136cd8659d6fa6558c8af80963137/src/shared/utils/util.ts#L220)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm going to move this into a private helper function and drop it from `utils`.  My purpose in creating it was to try and make a function that more naturally followed what I was hoping for and might want to use elsewhere, not to create something for a wider usage outside of our team.  It seems like me putting it here is causing confusion, and I don't think it's a great use of time to fiddle with the types for a function that no one else might ever care about.
</blockquote></details>

Gotcha! Sorry for the trouble :p


<!-- Sent from Reviewable.io -->

2023-12-14 16:00 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thank you! Looks good!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/678#-:-Nld2amw9saKcIUgNEJj:by8jgm7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-14 16:11 UTC, merged