Added events and emitters, added useEvent hook, tweaked docking framework css
paranext/paranext-core pull request #72
Opened 2023-03-13 17:43 UTC by tjcouch-sil

- Added `PEvent`, which provide an easy api for subscribing callbacks to some event
- Added `PNetworkEvent`, which is used in `NetworkService` to provide an easy api for subscribing callbacks to an event over the network
  - Do not use `PNetworkEvent` directly. Use `NetworkService.createNetworkEventEmitter` instead
- Added `useEvent` hook for easy subscribing to events in React
- Adjusted css for the docking framework to look a bit cleaner

2023-03-14 14:06 UTC, FoolRunning requested changes

2023-03-14 14:06 UTC, FoolRunning commented on src/shared/data/NetworkConnectorTypes.ts
> +  InternalEvent,
I didn't see any changes on the C# side (see comment at the top of this file). Are you thinking that the C# code won't worry about events?

2023-03-14 14:48 UTC, tjcouch-sil commented on src/shared/data/NetworkConnectorTypes.ts
> +  InternalEvent,
I think the C# should work on events (I made issue #58 for it), but I figured we would continue our pattern of my working on Node stuff and your working on C# stuff where available. However, I now realize that was an assumption I made that we did not discuss. Would be good to discuss how we want to split work up moving forward.

2023-03-14 17:46 UTC, FoolRunning submitted a review, later dismissed

2023-03-14 17:46 UTC, FoolRunning commented
I'd like @irahopkinson to also review this.

2023-03-15 02:53 UTC, irahopkinson requested changes
Nice job cleaning the CSS, etc. I had noticed the floating window had excess grey margin at the top. I guess it bothered you too 😉. Thanks for all this work on events, great job.

2023-03-15 02:53 UTC, irahopkinson commented on src/shared/util/PEvent.ts
> +          if (this.subscriptions.length === 0) this.subscriptions = undefined;
I'm not sure why `subscriptions` can't be initialized to, and here stay as, an empty array? It's simpler to not have to check if a property is defined and I don't see a good reason for it to be undefined.

2023-03-15 02:53 UTC, irahopkinson commented on src/shared/util/PEvent.ts
> +export class PEventEmitter<T> {
nit: I'm wondering about putting `PEvent` and `PNetworkEvent` in a utils folder. This is a model declaration not a utility function so I would put it in a `models` folder. I guess we still need to have that style discussion. Fell free to resolve this yourself.

2023-03-15 02:53 UTC, irahopkinson commented on cspell.json
> +    "maximizable"
nit: alphabetical order (I know you were just moving as is). Resolve this yourself as needed.

2023-03-15 02:53 UTC, irahopkinson commented on src/shared/util/PNetworkEvent.ts
> +  }
This can all be simplified to:
```
  /**
   * Creates a NetworkEventEmitter
   * @param networkSubscriber callback that accepts the event and emits it to other processes
   */
  constructor(
    /** Callback that sends the event to other processes on the network when it is emitted */
    private networkSubscriber: PEventHandler<T>
  ) {
    super();
  }
```

I.e. you can declare and initialize `networkSubscriber` in the constructor argument.

2023-03-15 02:53 UTC, irahopkinson commented on src/shared/util/PNetworkEvent.ts
> +   * @param type unique type that identifies this event. Must be the same across processes
There is no `type` argument. Remove.

2023-03-15 02:53 UTC, irahopkinson commented on src/shared/services/NetworkService.ts
> +export const createNetworkEventEmitter = <T>(
`createNetworkEventEmitterUnsafe` does warn not to use it outside of initialization. Does this need something to make it safe such as `await initialize();` or is it safe some other way that I can't see?

2023-03-15 02:53 UTC, irahopkinson commented on src/client/services/ClientNetworkConnector.ts
> +  ) => void;
DRY: Seems like this should have a locally defined type since its used again in the `connect` method (L111+).

2023-03-15 02:53 UTC, irahopkinson commented on src/client/services/ClientNetworkConnector.ts
> +  ) => void;
Hmm, its also used in 3 other files (total of 6 places), perhaps declare and export it in `INetworkConnector.ts`.

2023-03-15 02:53 UTC, irahopkinson commented on src/main/services/ServerNetworkConnector.ts
>    /**
nit: sp: next line 'websocket'. This is existing so resolve yourself.

2023-03-15 12:51 UTC, tjcouch-sil commented on src/shared/util/PEvent.ts
> +          if (this.subscriptions.length === 0) this.subscriptions = undefined;
The idea here was to make creating an event emitter as light as possible because people might not actually use it. I think it makes sense to leave the array empty, but I will leave lazy loading the array like with the `event` property if that sounds good to you! Made some changes; let me know your thoughts.

2023-03-15 12:51 UTC, tjcouch-sil commented on src/shared/util/PEvent.ts
> +export class PEventEmitter<T> {
I like the idea of putting them somewhere else, but I didn't know what to call the folder. `models` sounds fine for now!

2023-03-15 12:55 UTC, tjcouch-sil commented on cspell.json
> +    "maximizable"
Done :)

2023-03-15 13:00 UTC, tjcouch-sil commented on src/shared/util/PNetworkEvent.ts
> +  }
Ooh good catch! I'm not super used to that syntax, but I like it. I couldn't find an eslint rule for it, though :/ done

2023-03-15 13:01 UTC, tjcouch-sil commented on src/shared/util/PNetworkEvent.ts
> +   * @param type unique type that identifies this event. Must be the same across processes
Done - good catch!

2023-03-15 13:02 UTC, tjcouch-sil commented on src/shared/services/NetworkService.ts
> +export const createNetworkEventEmitter = <T>(
Ah yes, this is rather confusing. I will add comments to clarify. Basically the actual creation of emitters is fine, but the thing that needs to wait for initialization is the code that sends the event on the network. So `createNetworkEventEmitter` runs `createNetworkEventEmitterUnsafe` and passes in `emitEventOnNetwork`, which safely runs `emitEventOnNetworkUnsafe`. :)

2023-03-15 14:43 UTC, tjcouch-sil commented on src/client/services/ClientNetworkConnector.ts
> +  ) => void;
Good idea. Fixed

2023-03-15 14:46 UTC, tjcouch-sil commented on src/main/services/ServerNetworkConnector.ts
>    /**
Fixed

2023-03-15 22:41 UTC, irahopkinson commented on src/shared/models/PNetworkEvent.ts
> +    this.networkSubscriber = networkSubscriber;
This is no longer needed because you have declared the argument to be a class property so its value will be assigned to the value you pass in. That's an important part of the simplicity of declaring properties in the constructor arguments. Remove this line.

2023-03-15 22:41 UTC, irahopkinson commented on src/shared/util/PEvent.ts
> +          if (this.subscriptions.length === 0) this.subscriptions = undefined;
Are you anticipating there will be millions of these empty emitters in existance? Even so they won't take up much room https://stackoverflow.com/a/44222044. Can you explain why you want it super light? Is this premature optimization?

2023-03-15 23:01 UTC, irahopkinson requested changes
Good changes. Nearly there.

2023-03-15 23:01 UTC, irahopkinson commented on src/shared/services/NetworkService.ts
> +    () => removeNetworkEventEmitterInternal(eventType),
Good catch removing it from the list. Resolve this yourself.

2023-03-15 23:01 UTC, irahopkinson commented on src/shared/data/InternalConnectionTypes.ts
nit: I would also say that everything in the `data` folder are also data models (not data itself) and therefore should move to the `models` folder. This doesn't need doing in this PR so feel free to resolve this yourself if you don't do it now.

2023-03-16 15:51 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/72)* status: 0 of 37 files reviewed, 8 unresolved discussions (waiting on @FoolRunning and @irahopkinson)

___
*[`src/shared/data/NetworkConnectorTypes.ts` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/72#-NQcHyXyavs2Ht2RUymk-r1-11:-NQev9aV3m7gPTlFWHhQ:b9he2z8) ([raw file](https://github.com/paranext/paranext-core/blob/1d357f470850706bb9f0459ed58c6592b8511db1/src/shared/data/NetworkConnectorTypes.ts#L11)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think the C# should work on events (I made issue #58 for it), but I figured we would continue our pattern of my working on Node stuff and your working on C# stuff where available. However, I now realize that was an assumption I made that we did not discuss. Would be good to discuss how we want to split work up moving forward.
</blockquote></details>

Tim and I discussed and decided that I would mostly work on node stuff and he would mostly work on C# stuff moving forward. However, he will pick up some Node stuff in order to get acquainted.
___
*[`src/shared/services/NetworkService.ts` line 367 at r3](https://reviewable.io/reviews/paranext/paranext-core/72#-NQcHyXyavs2Ht2RUymo-r3-367:-NQf6R4o3pGHyIvhfCHI:b-7z430k) ([raw file](https://github.com/paranext/paranext-core/blob/818c874cf0732ef30e38188947b2d1cb3c553280/src/shared/services/NetworkService.ts#L367)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Good catch removing it from the list. Resolve this yourself.
</blockquote></details>

Thanks! :)
___
*[`src/shared/models/PNetworkEvent.ts` line 29 at r3](https://reviewable.io/reviews/paranext/paranext-core/72#-NQcHyXyavs2Ht2RUymv-r3-29:-NQf69PFEVBJqVhiiV_l:bbz6kc3) ([raw file](https://github.com/paranext/paranext-core/blob/818c874cf0732ef30e38188947b2d1cb3c553280/src/shared/models/PNetworkEvent.ts#L29)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is no longer needed because you have declared the argument to be a class property so its value will be assigned to the value you pass in. That's an important part of the simplicity of declaring properties in the constructor arguments. Remove this line.
</blockquote></details>

Ah yes, good catch. Done
___
*[`src/shared/util/PEvent.ts` line 67 at r1](https://reviewable.io/reviews/paranext/paranext-core/72#-NQcHyXyavs2Ht2RUymr-r1-67:-NQf4fzz67LpLQTbhrjg:b-ubwejs) ([raw file](https://github.com/paranext/paranext-core/blob/1d357f470850706bb9f0459ed58c6592b8511db1/src/shared/util/PEvent.ts#L67)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Are you anticipating there will be millions of these empty emitters in existance? Even so they won't take up much room https://stackoverflow.com/a/44222044. Can you explain why you want it super light? Is this premature optimization?
</blockquote></details>

VSCode uses a linked list for their subscriptions (they call them listeners because there are some other details on them). Theirs is also [lazy loaded](https://github.com/microsoft/vscode/blob/47f8188659a4336166f31b168d1bd88dfd9c7c9c/src/vs/base/common/event.ts#LL808C6-L808C6). I figured lazy loading an array would be a quick and easy way to get a bit of a similar optimization pattern to what they have (not to say we have to do everything the way they do it especially if we don't want to! Just seemed like a reasonable adjustment here). Though their linked list is not an array and may come with more significant performance implications.

I think there will be many event emitters made all over the PAPI that may or may not ever be used. It all depends on what extensions want to do and which extensions a user has active. Seems like it doesn't hurt to put in two or three lines to lazy load; do you feel there is significant value added from not lazy loading?


<!-- Sent from Reviewable.io -->

2023-03-16 18:44 UTC, irahopkinson approved these changes
> Reviewed 17 of 37 files at r1, 2 of 8 files at r2, 17 of 18 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/72)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning)

___
*[`src/shared/util/PEvent.ts` line 67 at r1](https://reviewable.io/reviews/paranext/paranext-core/72#-NQcHyXyavs2Ht2RUymr-r1-67:-NQfi1Ci3m1S-yoPY5cU:b-wr7csn) ([raw file](https://github.com/paranext/paranext-core/blob/1d357f470850706bb9f0459ed58c6592b8511db1/src/shared/util/PEvent.ts#L67)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

VSCode uses a linked list for their subscriptions (they call them listeners because there are some other details on them). Theirs is also [lazy loaded](https://github.com/microsoft/vscode/blob/47f8188659a4336166f31b168d1bd88dfd9c7c9c/src/vs/base/common/event.ts#LL808C6-L808C6). I figured lazy loading an array would be a quick and easy way to get a bit of a similar optimization pattern to what they have (not to say we have to do everything the way they do it especially if we don't want to! Just seemed like a reasonable adjustment here). Though their linked list is not an array and may come with more significant performance implications.

I think there will be many event emitters made all over the PAPI that may or may not ever be used. It all depends on what extensions want to do and which extensions a user has active. Seems like it doesn't hurt to put in two or three lines to lazy load; do you feel there is significant value added from not lazy loading?
</blockquote></details>

In this particular case no, but in general yes. Lets move this forward.


<!-- Sent from Reviewable.io -->

2023-03-16 18:46 UTC, irahopkinson approved these changes
> Dismissed @FoolRunning from a discussion.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/72)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-03-16 18:47 UTC, merged