Implementation of context menus (#707)
paranext/paranext-core pull request #746
Opened 2024-01-29 22:36 UTC by tombogle

2024-02-22 22:43 UTC, lyonsil reviewed
> Reviewed 5 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746)* status: 0 of 44 files reviewed, 5 unresolved discussions (waiting on @tombogle)

___
*[`tsconfig.json` line 44 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHxTEA9DIVplilID-o:-NrHxTEA9DIVplilID-p:b-93tdad) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/tsconfig.json#L44)):*
> ```jsonc
>     "src",
>     "assets",
>     "lib/platform-bible-react/src/components/button.component.test.tsx",
> ```

Why were these two lines added to the top level `tsconfig.json`?
___
*[`.vscode/settings.json` line 66 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHxlpU5zbsi1ZmF-9d:-NrHxlpU5zbsi1ZmF-9e:b-crdrkr) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/.vscode/settings.json#L66)):*
> ```JSON
>     }
>   ],
>   "cSpell.words": ["unlocalized"]
> ```

I would have expected this to be added to the top level `cspell.json` file instead of VSCode settings.
___
*[`lib/platform-bible-react/tsconfig.json` line 8 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHy2BS2mItZINDD08m:-NrHy2BS2mItZINDD08n:blnqz17) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/lib/platform-bible-react/tsconfig.json#L8)):*
> ```jsonc
>     "target": "ESNext",
>     "module": "ESNext",
>     "typeRoots": ["./node_modules/@types", "../../node_modules/@types"],
> ```

If the react lib is missing some types, I would expect them to be added to the react lib's `package.json` instead of adding the reference to the parent.  Is this a better solution for some reason?
___
*[`lib/platform-bible-utils/tsconfig.json` line 8 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHyeN7BJTs4wxNxDXw:-NrHyeN7BJTs4wxNxDXx:bzb8edw) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/lib/platform-bible-utils/tsconfig.json#L8)):*
> ```jsonc
>     "target": "ESNext",
>     "module": "ESNext",
>     "typeRoots": ["./node_modules/@types", "../../node_modules/@types"],
> ```

Same comment here as the react lib.  Why not install more types here?
___
*[`src/shared/utils/non-validating-document-combiner.ts` line 2 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHz1A89KgqL8NYiM7z:-NrHz1A89KgqL8NYiM8-:b-1w6ol8) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/src/shared/utils/non-validating-document-combiner.ts#L2)):*
> ```XML
> /* There is a copy of this file in
>   lib\platform-bible-react\src\test-utils\non-validating-document-combiner.ts. Changes made here
> ```

@tjcouch-sil Should I just put this class back into the utils lib as part of my "stitch together" issue?


<!-- Sent from Reviewable.io -->

2024-02-23 19:00 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746)* status: 0 of 44 files reviewed, 8 unresolved discussions (waiting on @lyonsil and @tombogle)

___
*[`lib/platform-bible-react/src/index.ts` line 17 at r4](https://reviewable.io/reviews/paranext/paranext-core/746#-NrM8Ksg8Mc6zIC1G0Rv:-NrM8Ksg8Mc6zIC1G0Rw:b-keuakj) ([raw file](https://github.com/paranext/paranext-core/blob/9ea642ade9ba996baf4f223a34213fd040b4ccb0/lib/platform-bible-react/src/index.ts#L17)):*
> ```XML
>   ComboBoxValue,
> } from './components/combo-box.component';
> export { default as TopLevelMenu } from './components/top-level-menu.component';
> ```

Not a blocking change, but these items are in alphabetical order by the source file name
___
*[`lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx` line 145 at r4](https://reviewable.io/reviews/paranext/paranext-core/746#-NrMIMLW2-WiVwddkYlW:-NrMIMLX6yg_Ro0FJSgh:b-85ofxm) ([raw file](https://github.com/paranext/paranext-core/blob/9ea642ade9ba996baf4f223a34213fd040b4ccb0/lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx#L145)):*
> ```XML
>       {/* I can't find anyway to "destructure" items.map. Asked ChatGPT, Google, and co-workers. */}
>       {/* eslint-disable-next-line react/destructuring-assignment */}
>       {items.map((itemInfo, index) => {
> ```

I haven't quite figured out why I get this message sometimes and not others. But is this a place where you could use `forEach()` instead? And does that prevent the error?
___
*[`lib/platform-bible-react/src/components/button.component.test.tsx` line 1 at r4](https://reviewable.io/reviews/paranext/paranext-core/746#-NrM9AEM3qUknai4jhHN:-NrM9AEM3qUknai4jhHO:bkrdrnb) ([raw file](https://github.com/paranext/paranext-core/blob/9ea642ade9ba996baf4f223a34213fd040b4ccb0/lib/platform-bible-react/src/components/button.component.test.tsx#L1)):*
> ```XML
> import { render, fireEvent } from '@testing-library/react';
> ```

It is using `@testing-library/react` and `@testing-library/jest-dom` but I don't think those are installed in the `platform-bible-react` library. Do we need them installed?


<!-- Sent from Reviewable.io -->

2024-02-26 19:56 UTC, irahopkinson reviewed
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746)* status: 1 of 45 files reviewed, 7 unresolved discussions (waiting on @lyonsil and @tombogle)

___
*[`tsconfig.json` line 44 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHxTEA9DIVplilID-o:-NrayJ6t-A0NpD-V4S9e:bpqy5cf) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/tsconfig.json#L44)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I'm guessing they were either added by mistake or added during one of several aborted attempts to get some things working. @tjcouch-sil, do you happen to recall. I'm reverting them unless you can think of a reason why they should be needed.
</blockquote></details>

When you move files around in VS Code it "helpfully" updates `tsconfig.json` for you. I consider it's changes and have so far always reverted them.


<!-- Sent from Reviewable.io -->

2024-02-28 00:27 UTC, tjcouch-sil requested changes
Tom, this is AWESOME! Thanks a ton for the hard work on this. Super excited to have this stuff in.

I am going to make an additional level of comment than I usually do here (the FOLLOW-UP level) since this is a time-sensitive PR. I will use the following categories:

- Blocking (filled circle with white line): please fix or respond with reasons why not asap
- Discussing (open circle) with FOLLOW-UP at top: unless you want to go ahead and discuss something about it now, please make a note of this (maybe copy a link to the discussion into some document for later? Or whatever works for you), resolve it yourself once you have made a note, and continue the discussion after resolving it (so we can determine the right course of action) or fix in an immediate follow-up PR if we agree on what to change. If this weren't a time-sensitive PR, these would probably be blocking
- Discussing (open circle): please consider and either make changes, respond, or just resolve yourself if it is just a note that doesn't seem important to you right now
- Info (i): just FYI. No action needed unless you want to make changes

Thanks!

> Reviewed 23 of 43 files at r2, 1 of 8 files at r4, 6 of 10 files at r5, 4 of 5 files at r6, 6 of 6 files at r7, 9 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746#-:-NrfiGve8CT4d63PPMfE:b-ooqv0p)* status: 40 of 48 files reviewed, 21 unresolved discussions (waiting on @jolierabideau, @lyonsil, and @tombogle)

___
*[`.vscode/launch.json` line 91 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-Nrbh_VHDakVMeFSlEsO:-Nrbh_VHDakVMeFSlEsP:b5qsev1) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/.vscode/launch.json#L91)):*
> ```JSON
>       "type": "node",
>       "request": "launch",
>       "name": "Jest: current file",
> ```

Is this still in use now that we are using the Jest Runner extension? I prefer to keep these minimal if possible to avoid clutter.
___
*[`lib/platform-bible-react/tsconfig.json` line 8 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHy2BS2mItZINDD08m:-NrbhzpF85tbx0Zuu_bW:b3jvem7) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/lib/platform-bible-react/tsconfig.json#L8)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If the react lib is missing some types, I would expect them to be added to the react lib's `package.json` instead of adding the reference to the parent.  Is this a better solution for some reason?
</blockquote></details>

Running `npm i` removes packages that are in common between the current directory's `node_modules` and any below. I believe that, if you don't specify `typeRoots`, TypeScript climbs directories looking for `node_modules/@types` folders by default (I can't remember for sure, but that may have been removed very recently - TS 5.3 or something? Or maybe they changed something else about it. I don't remember).

We needed to remove react from here below because having two copies was causing problems in the jest tests. But we need the types in both places. So this is how we need to do it. Another reason that splitting or using something like nx would be great.
___
*[`lib/platform-bible-react/src/components/context-menu.component.tsx` line 12 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrbjLg66J_m9ByULMs3:-NrbjLg66J_m9ByULMs4:bixfk5x) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/context-menu.component.tsx#L12)):*
> ```XML
> 
> export default function ContextMenu(menuProps: PropsWithChildren<ContextMenuProps>) {
>   const { className, commandHandler, menuDefinition, children } = menuProps;
> ```

Barring any reason you need to use the whole props parameter, props are usually destructured directly in the function's parameter like so:

```typescript
export default function ContextMenu({ className, commandHandler, menuDefinition, children }: PropsWithChildren<ContextMenuProps>) {
```
___
*[`lib/platform-bible-react/src/components/context-menu.component.tsx` line 14 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrfMjBS8kqzxezCuj4w:-NrfMjBS8kqzxezCuj4x:bk11zdg) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/context-menu.component.tsx#L14)):*
> ```XML
>   const { className, commandHandler, menuDefinition, children } = menuProps;
> 
>   const [contextMenu, setContextMenu] = React.useState<
> ```

It is hard to understand what this variable does from the name. I recommend changing the name of this variable to something more descriptive like `[contextMenuPosition, setContextMenuPosition]` or something.
___
*[`lib/platform-bible-react/src/components/context-menu.component.tsx` line 22 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-Nrbk4OED4Ua1Ko5jAv8:-Nrbk4OED4Ua1Ko5jAv9:b-ry2apx) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/context-menu.component.tsx#L22)):*
> ```XML
>   >(undefined);
> 
>   const handleContextMenu = (event: React.MouseEvent) => {
> ```

When passing functions down into child components, it is generally best to wrap the function in `useCallback` to avoid breaking the child component's (potential) memoization by changing the props passed in every render.
___
*[`lib/platform-bible-react/src/components/context-menu.component.tsx` line 37 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrbkGFO8qwWIM_Fu-qE:-NrbkGFP-_-g4MmO2crN:b-ry2apx) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/context-menu.component.tsx#L37)):*
> ```XML
>   };
> 
>   const handleClose = () => {
> ```

When passing functions down into child components, it is generally best to wrap the function in `useCallback` to avoid breaking the child component's (potential) memoization by changing the props passed in every render.
___
*[`lib/platform-bible-react/src/components/context-menu.component.tsx` line 48 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrgsgEF4yf2iVWLvMDj:-NrgsgEF4yf2iVWLvMDk:b-y4e96u) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/context-menu.component.tsx#L48)):*
> ```XML
>       className={`papi-context-menu-target ${className ?? ''}`}
>       onContextMenu={handleContextMenu}
>       style={{ cursor: 'context-menu' }}
> ```

FOLLOW-UP

Please create a class (or add to existing classes) for all styles that are not conditional upon something in the javascript and can be represented as pure CSS. It is more efficient.
___
*[`lib/platform-bible-react/src/components/context-menu.component.tsx` line 50 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrfLjTG6bcY4XZMzt7a:-NrfLjTHDLuuRZ3iK5f0:b-nj9s16) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/context-menu.component.tsx#L50)):*
> ```XML
>       style={{ cursor: 'context-menu' }}
>     >
>       {children}
> ```

FOLLOW-UP

Could you please add information about how to use the children/this component in the JSDoc? I think I'm understanding that this component wraps whatever you want to add a context menu to, but it is unclear without information explaining it.
___
*[`lib/platform-bible-react/src/components/context-menu.component.tsx` line 57 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-Nrgt5aBBKtjSp8wOfwS:-Nrgt5aBBKtjSp8wOfwT:bqoiaa4) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible- [...]

2024-02-28 14:32 UTC, tjcouch-sil reviewed
> Reviewed 3 of 8 files at r10, 8 of 8 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746)* status: 39 of 48 files reviewed, 14 unresolved discussions (waiting on @jolierabideau, @lyonsil, and @tombogle)

___
*[`lib/platform-bible-react/src/index.ts` line 17 at r4](https://reviewable.io/reviews/paranext/paranext-core/746#-NrM8Ksg8Mc6zIC1G0Rv:-Nrk7FD9Cxa3H875cmKh:b-iwhick) ([raw file](https://github.com/paranext/paranext-core/blob/9ea642ade9ba996baf4f223a34213fd040b4ccb0/lib/platform-bible-react/src/index.ts#L17)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

Looks like the context-menu file is not in alphabetical order yet. Agreed that this is not a big deal to block over, but would be nice :)
___
*[`lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx` line 145 at r4](https://reviewable.io/reviews/paranext/paranext-core/746#-NrMIMLW2-WiVwddkYlW:-Nrk5U_67XgvoosaSSMz:b-g4wzgl) ([raw file](https://github.com/paranext/paranext-core/blob/9ea642ade9ba996baf4f223a34213fd040b4ccb0/lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx#L145)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Sorry, I meant I want to figure out how to rework it from the way it's currently written. Sorry for the lack of clarity. I'll open another discussion on it so it is properly showing as a separate topic from Jolie's.
___
*[`lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx` line 156 at r11](https://reviewable.io/reviews/paranext/paranext-core/746#-Nrk5fUvBoIJyhJ7QeKG:-Nrk5fUvBoIJyhJ7QeKH:b-vvtc3w) ([raw file](https://github.com/paranext/paranext-core/blob/2410ec8359a7a8c7d1ab49bb9dedc01f187a4863/lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx#L156)):*
> ```XML
>       {(() => {
>         const elements: ReactNode[] = [];
>         // A little more convoluted, but using foreach instead of map gets around a complaint about
> ```

FOLLOW-UP

I would be interested in taking a look at this to see if we can figure out how to resolve this problem without the IIFE and `forEach` and such. An IIFE embedded in JSX is quite difficult to read and understand.
___
*[`lib/platform-bible-utils/tsconfig.json` line 8 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHyeN7BJTs4wxNxDXw:-Nrk6USwE3pcqxLdsrI1:b8r5g20) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/lib/platform-bible-utils/tsconfig.json#L8)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Same reason. @tjcouch-sil
</blockquote></details>

Might be nice to include the comment here that you put in `lib/platform-bible-react/tsconfig.json` as well :)
___
*[`.vscode/settings.json` line 66 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHxlpU5zbsi1ZmF-9d:-Nrk6kal7SlBKVGLqjo0:be23dab) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/.vscode/settings.json#L66)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Moving it to match your (reasonable) expectations. Does this suggest that I have something misconfigured, or did I just choose the wrong option when asked about what to do with this word?
</blockquote></details>

Hopefully you should see this option. It is the option we prefer :) 
![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/PJ0oftce0XjQkt5fpRwgnGvX/image.png)

I think adding to workspace settings would put it here.
___
*[`lib/platform-bible-react/src/components/button.component.test.tsx` line 1 at r4](https://reviewable.io/reviews/paranext/paranext-core/746#-NrM9AEM3qUknai4jhHN:-Nrk4aFhDWky1KtfJjiJ:b-nah0pr) ([raw file](https://github.com/paranext/paranext-core/blob/9ea642ade9ba996baf4f223a34213fd040b4ccb0/lib/platform-bible-react/src/components/button.component.test.tsx#L1)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I added them and then did an npm i, but that led to several errors when trying to build the react components. Maybe I did something wrong or maybe there is something else that needs to be done to prevent the errors. But if we want these added, I'll need help.
</blockquote></details>

I wonder if this is *another* case of having multiple of the same library in the `node_modules` stack. Maybe running `npm install` up in core root after `npm install` down in the react library folder would fix the errors. But it doesn't really matter much.


<!-- Sent from Reviewable.io -->

2024-02-28 19:54 UTC, tombogle reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746)* status: 39 of 48 files reviewed, 14 unresolved discussions (waiting on @jolierabideau, @lyonsil, and @tjcouch-sil)

___
*[`lib/platform-bible-react/src/index.ts` line 17 at r4](https://reviewable.io/reviews/paranext/paranext-core/746#-NrM8Ksg8Mc6zIC1G0Rv:-Nrl-WVl-ZVsTMeKJD4G:b-886gsx) ([raw file](https://github.com/paranext/paranext-core/blob/9ea642ade9ba996baf4f223a34213fd040b4ccb0/lib/platform-bible-react/src/index.ts#L17)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like the context-menu file is not in alphabetical order yet. Agreed that this is not a big deal to block over, but would be nice :)
</blockquote></details>

Fixed
___
*[`lib/platform-bible-react/src/components/grid-menu.component.tsx` line 45 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-Nrfi0Y8ELVuu3zhd3H2:-Nrl2bvP6bNyjUWhUzus:b-ew4ps2) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/grid-menu.component.tsx#L45)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why is `className` separated from `MenuColumnProps`?

Also can it be specified as optional instead of required but `string | undefined`?
</blockquote></details>

Judging by the comments, I think I can safely say that was the excellent work of ChatGPT.
___
*[`lib/platform-bible-react/src/components/grid-menu.component.tsx` line 95 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrgSLue-bNfgZHMGY2g:-Nrl3f6v8022-8yCcBUP:b-63rh4j) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/grid-menu.component.tsx#L95)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

FOLLOW-UP

It would probably be best to make a guard here so we throw or warn or something if it is not an object instead of just ignoring right now.
</blockquote></details>

@lyonsil kinds of figured we didn't really need this check at all since other stuff would presumably get broken if some other property were added. But if some other non-object property were added, in this case, just ignoring it is the right thing to do since were just trying to get a list of the MenuColumnWithHeader objects. The real thing we want to guard against (but can't) is trying to process some other type of object. That said, I have made the check tighter and improved the comment.
___
*[`lib/platform-bible-react/src/components/grid-menu.component.tsx` line 100 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrghI_n08wHoJZZUXO0:-Nrl6odk68YaQ_KDRMmK:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/grid-menu.component.tsx#L100)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

When passing calculated values down into child components, it is generally best to wrap the value in `useMemo` to avoid breaking the child component's (potential) memoization by changing the props passed in every render.

In this case, you would probably wrap everything from `columnNumbers` down to here in the `useMemo` so everything you need to create `sortedColumns` is inside the `useMemo`.
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx` line 45 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrgqKsI6NDRodNDABl-:-Nrl8uUo97vBG-hpBrKh:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx#L45)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It looks like this is not currently ensuring that a valid parent menu was provided. Could you make a guard and either throw or not have anything in includedGroups if `parentMenuItem.id` doesn't exist? Or put a `TODO:` at the start of this comment?
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx` line 51 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrgrFkZALMslBnjQ8aC:-NrlCi9j0--FtTKnTk77:b-yxv7ge) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx#L51)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

FOLLOW-UP

I don't think this `'menuItem' in group` is checking the same thing as the above one is, right? Above, you checked to make sure `menuItem` was in the array entry's `group` member. However, in here, it seems you're checking to make sure `menuItem` is in the array entry itself. I would expect this always to be false, so I am a bit confused.

Also I think you may be able to combine both the filter statements into one in here. That might be an alternative way to prevent `includedGroups` from having all the possible groups if there isn't a proper `parentMenuItem`
</blockquote></details>

What a great reminder that I need to write tests and add storybook data to test the submenu functionality.
___
*[`lib/platform-bible-react/src/components/button.component.test.tsx` line 1 at r4](https://reviewable.io/reviews/paranext/paranext-core/746#-NrM9AEM3qUknai4jhHN:-Nrl1iFa3D-DEXEFnue7:b2jehsu) ([raw file](https://github.com/paranext/paranext-core/blob/9ea642ade9ba996baf4f223a34213fd040b4ccb0/lib/platform-bible-react/src/components/button.component.test.tsx#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I wonder if this is *another* case of having multiple of the same library in the `node_modules` stack. Maybe running `npm install` up in core root after `npm install` down in the react library folder would fix the errors. But it doesn't really matter much.
</blockquote></details>

Yes, that took care of the problem.


<!-- Sent from Reviewable.io -->

2024-02-28 22:29 UTC, tombogle reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746)* status: 27 of 49 files reviewed, 14 unresolved discussions (waiting on @jolierabideau, @lyonsil, and @tjcouch-sil)

___
*[`lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx` line 51 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrgrFkZALMslBnjQ8aC:-NrlpYH6CEL9wYzskcJX:b-lfwxka) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx#L51)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

What a great reminder that I need to write tests and add storybook data to test the submenu functionality.
</blockquote></details>

Fixed and tested!
___
*[`lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx` line 111 at r9](https://reviewable.io/reviews/paranext/paranext-core/746#-Nrh4qqU0Gy6qSPHqz8H:-NrlNppU8E6Gy3HWJjir:b-1dcph8) ([raw file](https://github.com/paranext/paranext-core/blob/ab13997c124470faa8310b1578211525cbf8084d/lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx#L111)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

typo: "expect" -> except
</blockquote></details>

Corrected


<!-- Sent from Reviewable.io -->

2024-02-28 22:34 UTC, tombogle commented
*[`lib/platform-bible-react/src/components/top-level-menu.component.tsx` line 11 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-Nrh0dwE5SqepjUcd7p0:-Nrlqfv12GWLQd04D1wW:b-ro68q2) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/top-level-menu.component.tsx#L11)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

FOLLOW-UP

It is hard to understand what this component does or when I should use it from this comment. I don't know what this means. How does it differ than GridMenu and ContextMenu? When should I use it? The name seems to me to indicate it is the menu I should use, but the comment here seems to differ.
</blockquote></details>

Is there a way to mark something for "internal" export?


<!-- Sent from Reviewable.io -->

2024-02-28 22:37 UTC, tombogle commented
*[`tsconfig.json` line 44 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHxTEA9DIVplilID-o:-NrlrLv1A0D7Egk8Dk9K:ba3dfob) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/tsconfig.json#L44)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Agreed - I think these are incorrect "helps" from VSCode.
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2024-02-29 06:31 UTC, tombogle reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746)* status: 20 of 50 files reviewed, 12 unresolved discussions (waiting on @jolierabideau, @lyonsil, and @tjcouch-sil)

___
*[`lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx` line 55 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-Nrgs0Dm03hkb1r9PNYf:-NrnSwI4Aq_7TAnt1M3H:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx#L55)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe you need to return JSX here since this is rendering a component in JSX. Unfortunately, you generally shouldn't call a function component or create additional parameters like this. You'll have to pass the props down and add `includedGroups` as another prop.

Something like this:


```tsx
return <GroupedMenuItemList {...props} includedGroups={includedGroups} />
```

I believe this is forbidden syntax that will cause an error to show up from eslint because it is generally not the best design. It is often worth considering and making sure this is the best way to go. But it is useful sometimes, so it may be appropriate to ignore the error.
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx` line 107 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrgwzjN10gWVtravuXm:-NrnWyjeEnlZRdHXUoX2:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/grouped-menu-item-list.component.tsx#L107)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

When passing calculated values down into child components, it is generally best to wrap the value in `useMemo` to avoid breaking the child component's (potential) memoization by changing the props passed in every render.
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/toolbar.component.tsx` line 36 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrgzkorEun6Ss3Nqj1x:-Nrlq47pEActufVFfRH5:b-nqbv7k) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/toolbar.component.tsx#L36)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

FOLLOW-UP

I think, most likely, either this should be removed or `menuProvider` should be removed. I prefer passing in `menu` and `devMenu` (or something along those lines) over passing in a function that returns the menu since that is more declarative react-y. State should generally flow down the component hierarchy instead of being requested from below.
</blockquote></details>

I have removed this comment (and the other commented out stuff earlier in this file) since it is now working using the menuProvider approach. (I was not the original creator of that approach.) But for sure, we can do some follow-up work to change the approach.
___
*[`lib/platform-bible-react/src/components/top-level-menu.component.tsx` line 38 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-Nrh-chS3eikTRoA1DUX:-NrnYpq07amsk56u82di:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/top-level-menu.component.tsx#L38)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

As I mentioned in a previous comment, you need to use JSX syntax when dealing with function components. You need to pass the props in as attributes in the JSX element, and there is no ability to provide multiple different props. You can pass all your props down and add `includedGroups` as another prop.
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/test-utils/non-validating-document-combiner.ts` line 1 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-Nrh14s104CpCJwN4myD:-NrlquHT55J-NKGpfCwp:b-1dcph8) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/test-utils/non-validating-document-combiner.ts#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

typo: `TChanges`
</blockquote></details>

Corrected
___
*[`lib/platform-bible-utils/tsconfig.json` line 8 at r3](https://reviewable.io/reviews/paranext/paranext-core/746#-NrHyeN7BJTs4wxNxDXw:-NrlrD9U8pMXVksEIzaG:b7s3fui) ([raw file](https://github.com/paranext/paranext-core/blob/b5c358099543e22a3f02c2ac908678ee643446ba/lib/platform-bible-utils/tsconfig.json#L8)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Might be nice to include the comment here that you put in `lib/platform-bible-react/tsconfig.json` as well :)
</blockquote></details>

Comment added


<!-- Sent from Reviewable.io -->

2024-02-29 06:45 UTC, tombogle commented
There is still one visual issue I'm trying to figure out: Why doesn't setting inset true leave leading space for menu items that don't have leading icons defined? This needs to be addressed, but it probably shouldn't hold things up.

2024-02-29 18:58 UTC, tombogle commented
*[`lib/platform-bible-react/src/components/grid-menu.component.tsx` line 95 at r7](https://reviewable.io/reviews/paranext/paranext-core/746#-NrgSLue-bNfgZHMGY2g:-NrqCvrQ1tJgvJeZoab2:b-vdcmaz) ([raw file](https://github.com/paranext/paranext-core/blob/dd7b4dd7a045167bf3c5a1409e6004ef482ff53c/lib/platform-bible-react/src/components/grid-menu.component.tsx#L95)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oh, sorry, I didn't mean doing a tighter check; I just meant it would be best to do something if we find messed up data so we know that a non-object got in. A "guard" as I was discussing would be just flipping the `if` and throwing if it hit that if. But if you don't want to throw, might be best to warn:

```typescript
if (<your_condition_is_true>)
  columnNumbers.doStuff(...)
else logger.warn(`Column with column name ${columnName} on menu ${id} is not an object! Ignoring. This may indicate data corruption`);
```

Something along these lines. I don't have the context to know how to identify the menu, so I just grabbed `id` from above. I dunno if that's the right thing to use to identify here. Just would be good to do something so we can follow up on the problem if this happens.
</blockquote></details>

I think the point is that if anything else were added, we wouldn't ultimately want to throw an exception at all. We'd just want to weed it out (as we're doing with the isExtensible flag. The only reason to consider throwing an exception (or warning) would be to trigger a review of the code to make sure it is right. But I think with the new tightened check, it should be extremely unlikely that anything else (i.e., some object that wasn't really a column) would be added to columns that would accidentally slip in. 


<!-- Sent from Reviewable.io -->

2024-03-01 14:28 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> awesome! Just need a discussion resolved by @jolierabideau and a review on the story and test files.

> Reviewed 9 of 11 files at r16, 7 of 7 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746#-:-NruPdbV8-3QGpEhYUeo:buri1wg)* status: 42 of 51 files reviewed, 1 unresolved discussion (waiting on @jolierabideau)



<!-- Sent from Reviewable.io -->

2024-03-01 14:56 UTC, jolierabideau approved these changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746)* status: 42 of 51 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-01 15:05 UTC, jolierabideau approved these changes
Looks great Tom! 

> Reviewed 1 of 43 files at r2, 2 of 8 files at r4, 3 of 12 files at r8, 1 of 2 files at r9, 2 of 11 files at r16.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/746#-:-NruX7CL6IhMlnt6Uk00:b-fln04z)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-01 15:09 UTC, merged