Create menu store service
paranext/paranext-core pull request #747
Opened 2024-01-30 18:28 UTC by rolfheij-sil

2024-01-31 16:19 UTC, tjcouch-sil reviewed
Thanks for the great work on a lot of new stuff! Getting there :)

> Reviewed 5 of 9 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747#-:-NpVJOgjB9fp0xxq9b2-:b-rdvo3o)* status: all files reviewed, 15 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/extension-host/services/menu-store.service-host.ts` line 15 at r4](https://reviewable.io/reviews/paranext/paranext-core/747#-NpR9CnN50uJfPURA9cA:-NpR9CnN50uJfPURA9cB:b-8utsld) ([raw file](https://github.com/paranext/paranext-core/blob/36168ef64bbe9832e678104fe55b037c2fb66f63/src/extension-host/services/menu-store.service-host.ts#L15)):*
> ```XML
> import { deserialize } from 'platform-bible-utils';
> import menuDataObject from '@extension-host/data/menu.data.json';
> import { logger } from './papi-backend.service';
> ```

Path alias please :)
___
*[`src/extension-host/services/menu-store.service-host.ts` line 30 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpRhL_79lEJEypzD9a5:-NpRhL_79lEJEypzD9a6:blkpyqy) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L30)):*
> ```XML
>   }
> 
>   async getMenuData(menuType: string): Promise<MenuContent> {
> ```

I think you also need to be able to return web view menus for specific web views when people ask for them, not just the whole object of all the web view menus. You may need to adjust `loadAllMenuData` to account for this (or however you want to do it). I think it may be best to rework the `DataProviderDataTypes` here to provide one for the main menu and one for web view menus, then you can return the exact data type each one should be. For example, you could create `WebViewMenu: DataProviderDataTypes<string, WebViewMenu, never>` to provide menus for each web view. There are also the two default entries in the menu data, but I don't know that we really need to pass those around right now. Maybe we can implement that later if someone asks for it.
___
*[`src/extension-host/services/menu-store.service-host.ts` line 65 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpV8zbeETSiz-23piLu:-NpV8zbeETSiz-23piLv:b-h6jj2n) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L65)):*
> ```XML
> }
> 
> export function getMenuDataObject(): MenuData {
> ```

Does this need to be used anywhere outside of this file? I think it would probably be best to remove `export` or remove this function entirely if possible. We are providing a way to get to the menu data via the data provider, and I don't currently think it would be a good idea to give another path to it. That way, all access is consistent.
___
*[`src/extension-host/services/menu-store.service-host.ts` line 96 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpV9IXT0ShaB5p0s3eI:-NpV9IXT0ShaB5p0s3eJ:b-fc0op0) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L96)):*
> ```XML
> }
> 
> export const menuStoreService = createSyncProxyForAsyncObject<MenuStoreServiceType>(async () => {
> ```

Does this need to be exported? Probably best to avoid it if possible since I believe everyone should be using the `.service.ts`'s version of this, not this one, so all access is consistent.
___
*[`src/extension-host/services/menu-store.service-host.test.tsx` line 2 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVGVyV82cyJ-p8_i0Z:-NpVGVyV82cyJ-p8_i0_:b-8utsld) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.test.tsx#L2)):*
> ```XML
> import { MenuData } from '@shared/services/menu-store.service-model';
> import { MenuStoreDataProviderEngine } from './menu-store.service-host';
> ```

Path alias please :)
___
*[`src/extension-host/services/menu-store.service-host.test.tsx` line 5 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpV9pHoCrdz2fspsHWY:-NpV9pHoCrdz2fspsHWZ:b-cn8ddg) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.test.tsx#L5)):*
> ```XML
> 
> // Mocks come from menu contribution design proposal document sample JSON contributed from extension called "paratext"
> const MOCK_MENU_DATA_STRING: string = `{
> ```

I imagine you probably can get rid of this now since you aren't using the node file system service anymore.
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 18 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVAEE68Wz26SVfuSFI:-NpVAEE68Wz26SVfuSFJ:b-xy1c2r) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/renderer/components/platform-bible-toolbar.tsx#L18)):*
> ```XML
>   const [mainContent] = useData(menuStoreService.name).MenuData('mainMenu', {});
> 
>   logger.warn('MENU STORE TEST', JSON.stringify(mainContent));
> ```

Do we need the code changes to this file, or will they be removed before finalizing this PR? If they are staying, I'd recommend changing this to `logger.debug` or something.
___
*[`src/shared/services/menu-store.service.ts` line 1 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVFnbp8FrToszrc181:-NpVFnbp8FrToszrc182:b-6hzvza) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service.ts#L1)):*
> ```XML
> import dataProviderService from '@shared/services/data-provider.service';
> ```

I discussed with Matt a while about the name of this service because we need to put it on the `papi`. `papi.menuStore` seems not super self-explanatory. But `papi.menus` seems like it would do more than this service does. We decided `papi.menuData` would be nice. What do you think about renaming all these files `menu-data.service.ts` and such and then exposing this on the `papi` as `papi.menuData`?
___
*[`src/shared/services/menu-store.service.ts` line 6 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVGQnfCTtTjv8wCPSh:-NpVGQnfCTtTjv8wCPSi:b-8utsld) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service.ts#L6)):*
> ```XML
>   menuStoreServiceObjectToProxy,
>   menuStoreServiceProviderName,
> } from './menu-store.service-model';
> ```

Path alias please :)
___
*[`src/shared/services/menu-store.service.ts` line 16 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVAama2j7Ho5slv0QF:-NpVAama2j7Ho5slv0QG:b-lq7i6x) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service.ts#L16)):*
> ```XML
>         try {
>           const provider = await dataProviderService.get(menuStoreServiceProviderName);
>           if (!provider) throw new Error('Menu service data provider undefined');
> ```

Probably best to reword this to "Menu **data** service" (or whatever this ends up being called) so it more accurately describes the problem.
___
*[`src/shared/services/menu-store.service.ts` line 34 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVBKVGEBFcDS09fAPU:-NpVBKVGEBFcDS09fAPV:b-cqk43h) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service.ts#L34)):*
> ```XML
>   objectToProxy = {},
> ): T {
>   // We are calling stuff off of an object which doesn't exist when we create this proxy.
> ```

Ah oops, we need to reword this explanation with our changes to `objectToProxy`. Basically I think now it is more like "objectToProxy will have only the synchronously accessed properties of `T`  [...]

2024-01-31 17:06 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747)* status: all files reviewed, 15 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`src/extension-host/services/menu-store.service-host.ts` line 96 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpV9IXT0ShaB5p0s3eI:-NpVLvOo7f4THNkF74Xz:bhmwphb) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L96)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Does this need to be exported? Probably best to avoid it if possible since I believe everyone should be using the `.service.ts`'s version of this, not this one, so all access is consistent.
</blockquote></details>

If I remove this export- we are not using the `menuStoreService`. If I remove the `menuStoreService`, we are not using `dataProvider`, only setting it in `initialize`
___
*[`src/extension-host/services/menu-store.service-host.test.tsx` line 5 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpV9pHoCrdz2fspsHWY:-NpVMW9F9n8m4viC4rhA:b-q5ndyl) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.test.tsx#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I imagine you probably can get rid of this now since you aren't using the node file system service anymore.
</blockquote></details>

Done Yes!
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 18 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVAEE68Wz26SVfuSFI:-NpVMbYL6B5eKkpRH5Ls:b-m3y1aq) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/renderer/components/platform-bible-toolbar.tsx#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do we need the code changes to this file, or will they be removed before finalizing this PR? If they are staying, I'd recommend changing this to `logger.debug` or something.
</blockquote></details>

We do not need these
___
*[`src/shared/services/menu-store.service.ts` line 1 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVFnbp8FrToszrc181:-NpVMwNo-ifz8nR4R6xN:b-hfghm4) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service.ts#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I discussed with Matt a while about the name of this service because we need to put it on the `papi`. `papi.menuStore` seems not super self-explanatory. But `papi.menus` seems like it would do more than this service does. We decided `papi.menuData` would be nice. What do you think about renaming all these files `menu-data.service.ts` and such and then exposing this on the `papi` as `papi.menuData`?
</blockquote></details>

Sounds good


<!-- Sent from Reviewable.io -->

2024-01-31 19:04 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747)* status: 3 of 21 files reviewed, 14 unresolved discussions (waiting on @jolierabideau and @tjcouch-sil)

___
*[`src/extension-host/services/menu-store.service-host.test.tsx` line 2 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVGVyV82cyJ-p8_i0Z:-NpVperm9bKn9-EO-RCT:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.test.tsx#L2)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Path alias please :)
</blockquote></details>

Done.
___
*[`src/extension-host/services/menu-store.service-host.test.tsx` line 5 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpV9pHoCrdz2fspsHWY:-NpVs6_Y-yVkhRktSpyk:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.test.tsx#L5)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Done Yes!
</blockquote></details>

Done.
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 18 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVAEE68Wz26SVfuSFI:-NpVs8qr2Qq-v8-RT-Pu:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/renderer/components/platform-bible-toolbar.tsx#L18)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

We do not need these
</blockquote></details>

Done.
___
*[`src/shared/services/menu-store.service.ts` line 1 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVFnbp8FrToszrc181:-NpVsCuOCHRx1KUDnw96:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service.ts#L1)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Sounds good
</blockquote></details>

Done.
___
*[`src/shared/services/menu-store.service.ts` line 6 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVGQnfCTtTjv8wCPSh:-NpVqeN48RvXbOoqAkkp:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service.ts#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Path alias please :)
</blockquote></details>

Done.
___
*[`src/shared/services/menu-store.service.ts` line 16 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVAama2j7Ho5slv0QF:-NpVrRru3iXyYM-vMgh1:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service.ts#L16)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Probably best to reword this to "Menu **data** service" (or whatever this ends up being called) so it more accurately describes the problem.
</blockquote></details>

Done.
___
*[`src/shared/services/menu-store.service.ts` line 34 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVBKVGEBFcDS09fAPU:-NpVrulB5sdSxFBjSnYs:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service.ts#L34)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ah oops, we need to reword this explanation with our changes to `objectToProxy`. Basically I think now it is more like "objectToProxy will have only the synchronously accessed properties of `T` on it, and this proxy makes the async methods that do not exist yet available synchronously so we have all of `T`". Or something like that...

Also would probably be good to make the parameter `objectToProxy: Partial<T> = {}` so people know they need to put stuff from `T` on it instead of just putting whatever they want.
</blockquote></details>

Done.
___
*[`src/extension-host/services/menu-store.service-host.ts` line 15 at r4](https://reviewable.io/reviews/paranext/paranext-core/747#-NpR9CnN50uJfPURA9cA:-NpVrxRw4UKd6607BiTh:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/36168ef64bbe9832e678104fe55b037c2fb66f63/src/extension-host/services/menu-store.service-host.ts#L15)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Path alias please :)
</blockquote></details>

Done.
___
*[`src/extension-host/services/menu-store.service-host.ts` line 30 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpRhL_79lEJEypzD9a5:-NpVnr7nDw9zd52TTmYv:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L30)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think you also need to be able to return web view menus for specific web views when people ask for them, not just the whole object of all the web view menus. You may need to adjust `loadAllMenuData` to account for this (or however you want to do it). I think it may be best to rework the `DataProviderDataTypes` here to provide one for the main menu and one for web view menus, then you can return the exact data type each one should be. For example, you could create `WebViewMenu: DataProviderDataTypes<string, WebViewMenu, never>` to provide menus for each web view. There are also the two default entries in the menu data, but I don't know that we really need to pass those around right now. Maybe we can implement that later if someone asks for it.
</blockquote></details>

Done.
___
*[`src/extension-host/services/menu-store.service-host.ts` line 65 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpV8zbeETSiz-23piLu:-NpVQzXv6ZYpm1MBg8RS:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L65)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Does this need to be used anywhere outside of this file? I think it would probably be best to remove `export` or remove this function entirely if possible. We are providing a way to get to the menu data via the data provider, and I don't currently think it would be a good idea to give another path to it. That way, all access is consistent.
</blockquote></details>

Done.
___
*[`src/extension-host/services/menu-store.service-host.ts` line 96 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpV9IXT0ShaB5p0s3eI:-NpVsdvqBMHYH5sL4K5e:b-8jexgh) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L96)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

If I remove this export- we are not using the `menuStoreService`. If I remove the `menuStoreService`, we are not using `dataProvider`, only setting it in `initialize`
</blockquote></details>

@jolierabideau This one is still left unresolved too
___
*[`src/shared/services/menu-store.service-model.ts` line 7 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVG_iZ67snCMS1OqT_:-NpVoCWH7sA7kbdE9aoU:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service-model.ts#L7)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Path alias please :)
</blockquote></details>

Done.
___
*[`src/shared/services/menu-store.service-model.ts` line 10 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVGvwQ8lrNdF5y0ptE:-NpVoHKp1MAGJdHuNG6X:b-896fix) ([raw file](https://github.com/paranext/p [...]

2024-02-01 00:13 UTC, tjcouch-sil reviewed
> Reviewed 11 of 18 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747)* status: all files reviewed, 7 unresolved discussions (waiting on @jolierabideau and @rolfheij-sil)

___
*[`lib/papi-dts/papi.d.ts` line 163 at r7](https://reviewable.io/reviews/paranext/paranext-core/747#-NpWpWroDXRyDC6JjWiR:-NpWpWrp0w02abZOgLb4:br80wa1) ([raw file](https://github.com/paranext/paranext-core/blob/cefa00dd648fa368fbfe897a7a213d2435abdf50/lib/papi-dts/papi.d.ts#L163)):*
> ```XML
>     export type WebViewDefinitionUpdateInfo = Partial<WebViewDefinitionUpdatableProperties>;
>     /**
>      * JSDOC SOURCE UseWebViewStateHook
> ```

Looks like there was a problem generating `papi.d.ts` and the edit script didn't finish. Do you see any errors when running `npm run build:types`?
___
*[`lib/platform-bible-utils/src/util.ts` line 195 at r7](https://reviewable.io/reviews/paranext/paranext-core/747#-NpWqKXz12cJKoRMwrWE:-NpWqKXz12cJKoRMwrWF:b-r6vkv0) ([raw file](https://github.com/paranext/paranext-core/blob/cefa00dd648fa368fbfe897a7a213d2435abdf50/lib/platform-bible-utils/src/util.ts#L195)):*
> ```XML
>  * object that is asynchronously fetched using a provided asynchronous function.
>  *
>  * @param getObject - A function that returns a Promise resolving to the object to be proxied.
> ```

These comments look awesome! Just a couple things to tweak:

1. `getObject` returns a promise resolving to the object whose asynchronous methods to call. It is technically not the object being proxied since `objectToProxy` is being passed into `new Proxy`.
2. `objectToProxy` is an optional object that is the object that is proxied. If a property is accessed that does exist on this object, it will be returned. If a property is accessed that does not exist on this object, it will be considered to be an asynchronous method called on the object returned from `getObject`.
___
*[`src/extension-host/services/menu-data.service-host.ts` line 16 at r7](https://reviewable.io/reviews/paranext/paranext-core/747#-NpWt-9N02Ia3SSVQBke:-NpWt-9N02Ia3SSVQBkf:buv8rbn) ([raw file](https://github.com/paranext/paranext-core/blob/cefa00dd648fa368fbfe897a7a213d2435abdf50/src/extension-host/services/menu-data.service-host.ts#L16)):*
> ```XML
> import logger from '@shared/services/logger.service';
> 
> export class MenuDataDataProviderEngine
> ```

If this is only exported for the sake of testing, please add it as a property of an object, export that object, and label that object with testing stuff (name and JSDoc) like in the localization service. Then you won't need to export this class directly because I don't think anyone else should need to access this engine.
___
*[`src/extension-host/services/menu-data.service-host.ts` line 42 at r7](https://reviewable.io/reviews/paranext/paranext-core/747#-NpWsJ687_19nnfl6IS0:-NpWsJ69995Jvm-m5xJb:bdrg1z0) ([raw file](https://github.com/paranext/paranext-core/blob/cefa00dd648fa368fbfe897a7a213d2435abdf50/src/extension-host/services/menu-data.service-host.ts#L42)):*
> ```XML
>     menuContent: MenuContent,
>   ): Promise<DataProviderUpdateInstructions<MenuDataDataTypes>> {
>     // throw new Error('setMenuData disabled');
> ```

Is there a reason to `return false` instead of throwing? I think it would probably be best to throw so we don't give people the impression that maybe they are actually able to update the data. It would also be best to set the `setData` type in the `DataProviderDataType` for `MenuData` (or whatever the future `DataProviderDataTypes` will be) to `never` like on [the time data provider](https://github.com/paranext/paranext-core/blob/dd0539c6c40a079a8ab492e854809bae523059cb/extensions/src/c-sharp-provider-test/index.d.ts#L5) to indicate it cannot be set (and then also update the method signatures on `IMenuDataService`).
___
*[`src/extension-host/services/menu-store.service-host.ts` line 30 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpRhL_79lEJEypzD9a5:-NpWsiRK7-LdODTwV6vC:b-shjt97) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L30)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I may be missing something, but I don't see these changes. We can discuss on a call soon if there's any confusion to clear up :)
___
*[`src/extension-host/services/menu-store.service-host.ts` line 96 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpV9IXT0ShaB5p0s3eI:-NpWuzzy1EjpSoms5PKe:b-a406sf) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L96)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

@jolierabideau This one is still left unresolved too
</blockquote></details>

Gotcha. I'd say for now it might be best to put an ignore somewhere and explain that we will need it later for disposing of the data provider. Usually, though, I would say let's just remove it all; just seems convoluted enough this time to warrant keeping it for something we almost certainly will do at some point. But feel free to just remove it, too. We can always add it back in later when we need it.


<!-- Sent from Reviewable.io -->

2024-02-01 18:42 UTC, tjcouch-sil reviewed
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747)* status: all files reviewed, 6 unresolved discussions (waiting on @jolierabideau and @rolfheij-sil)



<!-- Sent from Reviewable.io -->

2024-02-02 14:50 UTC, rolfheij-sil reviewed
Thanks for reviewing and all the help. I responded to your comments on behalf of Jolie, she was able to get most of the changes in yesterday

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747#-:-NpeHxQ38M_vLmMpq5Fg:b-pzryhu)* status: 15 of 21 files reviewed, 6 unresolved discussions (waiting on @jolierabideau and @tjcouch-sil)

___
*[`lib/papi-dts/papi.d.ts` line 163 at r7](https://reviewable.io/reviews/paranext/paranext-core/747#-NpWpWroDXRyDC6JjWiR:-NpZoFwM76l5r70VRBKi:b-o9wy5) ([raw file](https://github.com/paranext/paranext-core/blob/cefa00dd648fa368fbfe897a7a213d2435abdf50/lib/papi-dts/papi.d.ts#L163)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like there was a problem generating `papi.d.ts` and the edit script didn't finish. Do you see any errors when running `npm run build:types`?
</blockquote></details>

Yep, but it's fixed now
___
*[`lib/platform-bible-utils/src/util.ts` line 195 at r7](https://reviewable.io/reviews/paranext/paranext-core/747#-NpWqKXz12cJKoRMwrWE:-NpZr6YD9YwAOvpDjvRO:bie7uqi) ([raw file](https://github.com/paranext/paranext-core/blob/cefa00dd648fa368fbfe897a7a213d2435abdf50/lib/platform-bible-utils/src/util.ts#L195)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

These comments look awesome! Just a couple things to tweak:

1. `getObject` returns a promise resolving to the object whose asynchronous methods to call. It is technically not the object being proxied since `objectToProxy` is being passed into `new Proxy`.
2. `objectToProxy` is an optional object that is the object that is proxied. If a property is accessed that does exist on this object, it will be returned. If a property is accessed that does not exist on this object, it will be considered to be an asynchronous method called on the object returned from `getObject`.
</blockquote></details>

Done, thanks to Jolie
___
*[`src/extension-host/services/menu-data.service-host.ts` line 16 at r7](https://reviewable.io/reviews/paranext/paranext-core/747#-NpWt-9N02Ia3SSVQBke:-NpZvPz53RsyBS6ITdUl:bie7uqi) ([raw file](https://github.com/paranext/paranext-core/blob/cefa00dd648fa368fbfe897a7a213d2435abdf50/src/extension-host/services/menu-data.service-host.ts#L16)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

If this is only exported for the sake of testing, please add it as a property of an object, export that object, and label that object with testing stuff (name and JSDoc) like in the localization service. Then you won't need to export this class directly because I don't think anyone else should need to access this engine.
</blockquote></details>

Done, thanks to Jolie
___
*[`src/extension-host/services/menu-data.service-host.ts` line 42 at r7](https://reviewable.io/reviews/paranext/paranext-core/747#-NpWsJ687_19nnfl6IS0:-NpZsLND2w-khpPXBRIa:bie7uqi) ([raw file](https://github.com/paranext/paranext-core/blob/cefa00dd648fa368fbfe897a7a213d2435abdf50/src/extension-host/services/menu-data.service-host.ts#L42)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is there a reason to `return false` instead of throwing? I think it would probably be best to throw so we don't give people the impression that maybe they are actually able to update the data. It would also be best to set the `setData` type in the `DataProviderDataType` for `MenuData` (or whatever the future `DataProviderDataTypes` will be) to `never` like on [the time data provider](https://github.com/paranext/paranext-core/blob/dd0539c6c40a079a8ab492e854809bae523059cb/extensions/src/c-sharp-provider-test/index.d.ts#L5) to indicate it cannot be set (and then also update the method signatures on `IMenuDataService`).
</blockquote></details>

Done, thanks to Jolie
___
*[`src/extension-host/services/menu-store.service-host.ts` line 30 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpRhL_79lEJEypzD9a5:-NpeHPSa0zYAPWMOCjA0:byyqxtc) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L30)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I may be missing something, but I don't see these changes. We can discuss on a call soon if there's any confusion to clear up :)
</blockquote></details>

Whoops, yeah I was wrong. But should be fixed now though, thanks to Jolie
___
*[`src/extension-host/services/menu-store.service-host.ts` line 96 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpV9IXT0ShaB5p0s3eI:-NpZwSID-IOq1fnQwcZS:bie7uqi) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/extension-host/services/menu-store.service-host.ts#L96)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Gotcha. I'd say for now it might be best to put an ignore somewhere and explain that we will need it later for disposing of the data provider. Usually, though, I would say let's just remove it all; just seems convoluted enough this time to warrant keeping it for something we almost certainly will do at some point. But feel free to just remove it, too. We can always add it back in later when we need it.
</blockquote></details>

Done, thanks to Jolie


<!-- Sent from Reviewable.io -->

2024-02-05 17:57 UTC, tjcouch-sil requested changes
> Reviewed 2 of 6 files at r9, 10 of 10 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747)* status: all files reviewed, 10 unresolved discussions (waiting on @jolierabideau and @rolfheij-sil)

___
*[`lib/papi-dts/papi.d.ts` line 4218 at r10](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuCwpN-uqTVemTQypi:-NpuCwpN-uqTVemTQypj:bdru7c4) ([raw file](https://github.com/paranext/paranext-core/blob/d91a30458055ce847e2ee9645eb36e91167b49d8/lib/papi-dts/papi.d.ts#L4218)):*
> ```XML
>   import { IDataProvider } from '@papi/core';
>   /**
>    * Name used to register the data provider
> ```

Did you check in extensions if this JSDoc gets put on `papi.menuData.dataProviderName` appropriately? I have a hunch that  it doesn't currently. Maybe the comment needs to be JSDoc source and dest copied onto the property in `menuDataServiceObjectToProxy`? Not really sure what exactly would work, so it might take a bit of playing around with it.
___
*[`src/extension-host/services/menu-data.service-host.test.tsx` line 192 at r10](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuIB4SAYjJehWYnGi2:-NpuIB4SAYjJehWYnGi3:b-vv65uk) ([raw file](https://github.com/paranext/paranext-core/blob/d91a30458055ce847e2ee9645eb36e91167b49d8/src/extension-host/services/menu-data.service-host.test.tsx#L192)):*
> ```XML
> });
> 
> test('Set main menu data', async () => {
> ```

Probably would be nice to name this test a little more descriptively of what's happening like "Setting main menu data throws" or something. Not a big deal. Same with the "Set web view menu data" test below.
___
*[`src/extension-host/services/menu-data.service-host.ts` line 42 at r7](https://reviewable.io/reviews/paranext/paranext-core/747#-NpWsJ687_19nnfl6IS0:-NpuLjoG9L5Hz78vDJcR:b-eadb67) ([raw file](https://github.com/paranext/paranext-core/blob/cefa00dd648fa368fbfe897a7a213d2435abdf50/src/extension-host/services/menu-data.service-host.ts#L42)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done, thanks to Jolie
</blockquote></details>

It would be best to update these set methods' signatures to match the `DataProviderSetter` - see comment on `menu-data.service-model`
___
*[`src/extension-host/services/menu-data.service-host.ts` line 33 at r10](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuG4VW06JQ4ZeCZWde:-NpuG4VW06JQ4ZeCZWdf:b-34qpjo) ([raw file](https://github.com/paranext/paranext-core/blob/d91a30458055ce847e2ee9645eb36e91167b49d8/src/extension-host/services/menu-data.service-host.ts#L33)):*
> ```XML
>   }
> 
>   async getMainMenu(menuType: 'mainMenu'): Promise<MultiColumnMenu> {
> ```

You probably don't need `menuType` here. You may want to just make the selector parameter `undefined` or remove it and not have a parameter at all. Or maybe you could make overrides for it! Like the following:

```typscript
type IMenuDataService = {
...
/**
 * JSDOC SOURCE menuDataServiceGetMainMenu
 * ...
 */
getMainMenu(): Promise<MultiColumnMenu>
/** JSDOC DESTINATION menuDataServiceGetMainMenu */
getMainMenu(selector: undefined): Promise<MultiColumnMenu>
...
}
```
(See `use-dialog-callback.hook.ts` for a good example of overrides)

That way, people don't have to put any parameters if they don't want to since the parameter is unused. And you also cover the method signature for `DataProviderGetter`. If the DataProvider stuff gets upset when you do this, maybe you can instead just leave the selector as `undefined`
___
*[`src/extension-host/services/menu-data.service-host.ts` line 70 at r10](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuH8n8DKhRfxxkRTDn:-NpuH8n8DKhRfxxkRTDo:b-y0rnoh) ([raw file](https://github.com/paranext/paranext-core/blob/d91a30458055ce847e2ee9645eb36e91167b49d8/src/extension-host/services/menu-data.service-host.ts#L70)):*
> ```XML
>       this.mainMenuMap.set('mainMenu', mainMenuContent);
> 
>       // MenuData object contains MenuContent as a type so it can't tell if its specifically WebViewMenus
> ```

I think the menu data should come in as [`PlatformMenus`](https://github.com/paranext/paranext-core/blob/main/lib/platform-bible-utils/src/menus.model.ts#L117), so I don't think these type assertions should be necessary (except the `ReferencedItem` one below. That one unfortunately still needs to be there iirc).
___
*[`src/extension-host/services/menu-data.service-host.ts` line 74 at r10](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuHrj80JhahazCOitk:-NpuHrj80JhahazCOitl:b8vvdou) ([raw file](https://github.com/paranext/paranext-core/blob/d91a30458055ce847e2ee9645eb36e91167b49d8/src/extension-host/services/menu-data.service-host.ts#L74)):*
> ```XML
>       const webViewMenus = menuData.webViewMenus as WebViewMenus;
> 
>       // TODO: How to do this better?
> ```

This looks good! Only suggestion is, when looping over entries, usually we do the parameters of the function like this:

```typescript
Object.entries(webViewMenus).forEach(([key, value]) => {...});
```

You can destructure the array inline and name the array entries. `key` and `value` are commonly used, but you can name them how you like.
___
*[`src/shared/services/menu-data.service-model.ts` line 52 at r11](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuI_sXAYcvZGEv__Ys:-NpuI_sXAYcvZGEv__Yt:b-68gpue) ([raw file](https://github.com/paranext/paranext-core/blob/f5e84653d420d954940105f14634b5b90411875e/src/shared/services/menu-data.service-model.ts#L52)):*
> ```XML
>   getMainMenu: (menuType: 'mainMenu') => Promise<MultiColumnMenu>;
>   /**
>    * Set the menuContent of the main menu
> ```

This comment seems out of date - needs to say this data cannot be changed and this will always throw. Same with `setWebViewMenu`
___
*[`src/shared/services/menu-data.service-model.ts` line 73 at r11](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuO9Fe6LI4mrCGRUfK:-NpuO9Fe6LI4mrCGRUfL:b-bwuima) ([raw file](https://github.com/paranext/paranext-core/blob/f5e84653d420d954940105f14634b5b90411875e/src/shared/services/menu-data.service-model.ts#L73)):*
> ```XML
>    * @returns WebViewMenu object of web view menu content
>    */
>   getWebViewMenu: (webViewName: ReferencedItem) => Promise<WebViewMenu>;
> ```

The name for this should be `webViewType` to match other uses like in web view service's `getWebView` and `register`
___
*[`src/shared/services/menu-data.service-model.ts` line 79 at r11](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuJJ52CJOU9mKM9QPq:-NpuJJ52CJOU9mKM9QPr:b-34q8yh) ([raw file](https://github.com/paranext/paranext-core/blob/f5e84653d420d954940105f14634b5b90411875e/src/shared/services/menu-data.service-model.ts#L79)):*
> ```XML
>    * @returns Unsubscriber function
>    */
>   setWebViewMenu: () => Promise<DataProviderUpdateInstructions<MenuDataDataTypes>>;
> ```

Would be best to put parameters `webViewType: ReferencedItem, value: never` to match the real `DataProviderSetter` type so `IMenuDataService` will just have one definition for the method. I think, right now, this will make an overload on `setWebViewMenu` because `IDataProvider<MenuDataDataTypes>`'s `setWebViewMenu` has a different method signature. You can test to make sure it's right by making a fake object that you assert to this type and then typing in the method name and seeing what comes up from intellisense like this:

```typescript
const thing = {} as IMenuDataService;
thing.setWebViewMenu
```

Similar with `setMainMenu` but just with different selector type
___
*[`src/shared/services/menu-data.service-model.ts` line 88 at r11](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuLPCL3SCBwm-YTQHd:-NpuLPCL3SCBwm-YTQHe:b-h2vs9r) ([raw file](https://github.com/paranext/paranext-core/blob/f5e84653d420d954940105f14634b5b90411875e/src/shared/services/menu-data.service-model.ts#L88)):*
> ```XML
>    */
>   subscribeWebViewMenu: (
>     callback: (menuContent: WebView [...]

2024-02-05 20:56 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747)* status: 16 of 21 files reviewed, 9 unresolved discussions (waiting on @jolierabideau and @tjcouch-sil)

___
*[`lib/papi-dts/papi.d.ts` line 4218 at r10](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuCwpN-uqTVemTQypi:-NpugXwG-wqhgYIWbWWX:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/d91a30458055ce847e2ee9645eb36e91167b49d8/lib/papi-dts/papi.d.ts#L4218)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Did you check in extensions if this JSDoc gets put on `papi.menuData.dataProviderName` appropriately? I have a hunch that  it doesn't currently. Maybe the comment needs to be JSDoc source and dest copied onto the property in `menuDataServiceObjectToProxy`? Not really sure what exactly would work, so it might take a bit of playing around with it.
</blockquote></details>

Done.
___
*[`src/extension-host/services/menu-data.service-host.test.tsx` line 192 at r10](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuIB4SAYjJehWYnGi2:-Npup83iBq1-cLYD0pm3:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/d91a30458055ce847e2ee9645eb36e91167b49d8/src/extension-host/services/menu-data.service-host.test.tsx#L192)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Probably would be nice to name this test a little more descriptively of what's happening like "Setting main menu data throws" or something. Not a big deal. Same with the "Set web view menu data" test below.
</blockquote></details>

Done.
___
*[`src/extension-host/services/menu-data.service-host.ts` line 42 at r7](https://reviewable.io/reviews/paranext/paranext-core/747#-NpWsJ687_19nnfl6IS0:-NpuoZCcBcOST5v8Vouz:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/cefa00dd648fa368fbfe897a7a213d2435abdf50/src/extension-host/services/menu-data.service-host.ts#L42)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It would be best to update these set methods' signatures to match the `DataProviderSetter` - see comment on `menu-data.service-model`
</blockquote></details>

Done.
___
*[`src/extension-host/services/menu-data.service-host.ts` line 33 at r10](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuG4VW06JQ4ZeCZWde:-NpujiwXDCGL8VI-E4Pi:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/d91a30458055ce847e2ee9645eb36e91167b49d8/src/extension-host/services/menu-data.service-host.ts#L33)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You probably don't need `menuType` here. You may want to just make the selector parameter `undefined` or remove it and not have a parameter at all. Or maybe you could make overrides for it! Like the following:

```typscript
type IMenuDataService = {
...
/**
 * JSDOC SOURCE menuDataServiceGetMainMenu
 * ...
 */
getMainMenu(): Promise<MultiColumnMenu>
/** JSDOC DESTINATION menuDataServiceGetMainMenu */
getMainMenu(selector: undefined): Promise<MultiColumnMenu>
...
}
```
(See `use-dialog-callback.hook.ts` for a good example of overrides)

That way, people don't have to put any parameters if they don't want to since the parameter is unused. And you also cover the method signature for `DataProviderGetter`. If the DataProvider stuff gets upset when you do this, maybe you can instead just leave the selector as `undefined`
</blockquote></details>

Done.
___
*[`src/extension-host/services/menu-data.service-host.ts` line 70 at r10](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuH8n8DKhRfxxkRTDn:-NpuodSc5QuPHIpgjg5N:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/d91a30458055ce847e2ee9645eb36e91167b49d8/src/extension-host/services/menu-data.service-host.ts#L70)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think the menu data should come in as [`PlatformMenus`](https://github.com/paranext/paranext-core/blob/main/lib/platform-bible-utils/src/menus.model.ts#L117), so I don't think these type assertions should be necessary (except the `ReferencedItem` one below. That one unfortunately still needs to be there iirc).
</blockquote></details>

Done.
___
*[`src/extension-host/services/menu-data.service-host.ts` line 74 at r10](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuHrj80JhahazCOitk:-Npup0m_BRZCtp63McVs:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/d91a30458055ce847e2ee9645eb36e91167b49d8/src/extension-host/services/menu-data.service-host.ts#L74)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This looks good! Only suggestion is, when looping over entries, usually we do the parameters of the function like this:

```typescript
Object.entries(webViewMenus).forEach(([key, value]) => {...});
```

You can destructure the array inline and name the array entries. `key` and `value` are commonly used, but you can name them how you like.
</blockquote></details>

Done.
___
*[`src/shared/services/menu-data.service-model.ts` line 52 at r11](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuI_sXAYcvZGEv__Ys:-Npust0_80EEIxC4T6f7:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/f5e84653d420d954940105f14634b5b90411875e/src/shared/services/menu-data.service-model.ts#L52)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This comment seems out of date - needs to say this data cannot be changed and this will always throw. Same with `setWebViewMenu`
</blockquote></details>

Done.
___
*[`src/shared/services/menu-data.service-model.ts` line 73 at r11](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuO9Fe6LI4mrCGRUfK:-NpuuIff213nVwHOgqmd:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/f5e84653d420d954940105f14634b5b90411875e/src/shared/services/menu-data.service-model.ts#L73)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The name for this should be `webViewType` to match other uses like in web view service's `getWebView` and `register`
</blockquote></details>

Done.
___
*[`src/shared/services/menu-data.service-model.ts` line 79 at r11](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuJJ52CJOU9mKM9QPq:-Npuum4W4xIXfP6vjUYC:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/f5e84653d420d954940105f14634b5b90411875e/src/shared/services/menu-data.service-model.ts#L79)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Would be best to put parameters `webViewType: ReferencedItem, value: never` to match the real `DataProviderSetter` type so `IMenuDataService` will just have one definition for the method. I think, right now, this will make an overload on `setWebViewMenu` because `IDataProvider<MenuDataDataTypes>`'s `setWebViewMenu` has a different method signature. You can test to make sure it's right by making a fake object that you assert to this type and then typing in the method name and seeing what comes up from intellisense like this:

```typescript
const thing = {} as IMenuDataService;
thing.setWebViewMenu
```

Similar with `setMainMenu` but just with different selector type
</blockquote></details>

Done.
___
*[`src/shared/services/menu-data.service-model.ts` line 88 at r11](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuLPCL3SCBwm-YTQHd:-NpuvZlUCiAVjRilfBqA:b-vj425z) ([raw file](https://github.com/paranext/paranext-core/blob/f5e84653d420d954940105f14634b5b90411875e/src/shared/services/menu-data.service-model.ts#L88)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe this is missing a `selector` parameter. Same with `subscribeMainMenu`.
</blockquote></details>

Done. I don't think `subscribeMainMenu` needs a selector [...]

2024-02-05 22:59 UTC, tjcouch-sil requested changes
> Reviewed 2 of 5 files at r12, 2 of 3 files at r13, 10 of 10 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/shared/services/menu-data.service-model.ts` line 88 at r11](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuLPCL3SCBwm-YTQHd:-Npv9ILFEAtz0zU530XU:by9kbqg) ([raw file](https://github.com/paranext/paranext-core/blob/f5e84653d420d954940105f14634b5b90411875e/src/shared/services/menu-data.service-model.ts#L88)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done. I don't think `subscribeMainMenu` needs a selector, right? There's only one main menu. Also I'm not sure if I used the right type for the selector
</blockquote></details>

Sorry, I think I may have misled you a bit with my comment. I intended to indicate that these subscribe functions need a selector parameter but not necessarily literally `selector`. The selector for `subscribe<data_type>` methods must match the selector for the corresponding `get<data_type>` and `set<data_type>` methods. So for this method, you could just copy and paste `webViewType` and its JSDoc from `getWebViewMenu`.

You also need a selector parameter for `subscribeMainMenu`. The selector would be the same as the first parameter of the `getMainMenu` method, which is `undefined`. This method signature where `getMainMenu` has a parameter `undefined` exists even though it is not specified here since it is included as part of `IDataProvider<MenuDataDataTypes>`. This is what I was talking about earlier when I suggested overloading `getMainMenu` so there was one with no first parameter and one with `undefined` as the first parameter.

The reason you need a selector parameter even for `subscribeMainMenu` is that the `subscribe<data_type>` methods are generated and attached to data providers. The first parameter is the selector, which is passed through directly to the `get<data_type>` method. As such, you cannot skip the first parameter because the generated subscriber method won't realize you skipped it and will use the arguments passed into it incorrectly.

I would be happy to explain further on a call soon if desired :)
___
*[`src/shared/services/menu-store.service-model.ts` line 10 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVGeiM08PFawI7rueI:-Npv4J9M1ReZBV9Tyii6:b-ia0ysb) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service-model.ts#L10)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done. Is it better like this?
</blockquote></details>

Looks great. Thanks! I would recommend, though, that it would be best to use `JSDOC SOURCE` and `JSDOC DESTINATION` to copy the comment over instead of duplicating. Not a big deal at all. Do it if you want :)


<!-- Sent from Reviewable.io -->

2024-02-06 14:54 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/shared/services/menu-data.service-model.ts` line 88 at r11](https://reviewable.io/reviews/paranext/paranext-core/747#-NpuLPCL3SCBwm-YTQHd:-Npyt6fW6FAB6hlXtnAr:b3v6zcm) ([raw file](https://github.com/paranext/paranext-core/blob/f5e84653d420d954940105f14634b5b90411875e/src/shared/services/menu-data.service-model.ts#L88)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Sorry, I think I may have misled you a bit with my comment. I intended to indicate that these subscribe functions need a selector parameter but not necessarily literally `selector`. The selector for `subscribe<data_type>` methods must match the selector for the corresponding `get<data_type>` and `set<data_type>` methods. So for this method, you could just copy and paste `webViewType` and its JSDoc from `getWebViewMenu`.

You also need a selector parameter for `subscribeMainMenu`. The selector would be the same as the first parameter of the `getMainMenu` method, which is `undefined`. This method signature where `getMainMenu` has a parameter `undefined` exists even though it is not specified here since it is included as part of `IDataProvider<MenuDataDataTypes>`. This is what I was talking about earlier when I suggested overloading `getMainMenu` so there was one with no first parameter and one with `undefined` as the first parameter.

The reason you need a selector parameter even for `subscribeMainMenu` is that the `subscribe<data_type>` methods are generated and attached to data providers. The first parameter is the selector, which is passed through directly to the `get<data_type>` method. As such, you cannot skip the first parameter because the generated subscriber method won't realize you skipped it and will use the arguments passed into it incorrectly.

I would be happy to explain further on a call soon if desired :)
</blockquote></details>

Done  I believe
___
*[`src/shared/services/menu-store.service-model.ts` line 10 at r5](https://reviewable.io/reviews/paranext/paranext-core/747#-NpVGeiM08PFawI7rueI:-NpysE6BEEFu0KjqJE6O:b-9wlm3v) ([raw file](https://github.com/paranext/paranext-core/blob/efcebedf0532f8c49ba3b74a1441e965c9516cec/src/shared/services/menu-store.service-model.ts#L10)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks great. Thanks! I would recommend, though, that it would be best to use `JSDOC SOURCE` and `JSDOC DESTINATION` to copy the comment over instead of duplicating. Not a big deal at all. Do it if you want :)
</blockquote></details>

We did try that but it doesn't copy, and will just display JSDOC DESTINATION.


<!-- Sent from Reviewable.io -->

2024-02-06 15:28 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> woohoo!! Thanks again for all the hard work and perseverance on this! Great work!

> Reviewed 2 of 2 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/747#-:-Npz14kM-SoUjybAn8sl:b-5v5nib)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-06 15:43 UTC, merged