Async settings service
paranext/paranext-core pull request #752
Opened 2024-02-06 22:20 UTC by rolfheij-sil

2024-02-07 15:19 UTC, tjcouch-sil reviewed
> Reviewed 1 of 4 files at r2, 1 of 4 files at r3, 4 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752)* status: 6 of 9 files reviewed, 6 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/main/services/settings.service-host.ts` line 61 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3-GBz8PK_TAYlSr21:-Nq3-GBz8PK_TAYlSr22:bhwnw2t) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/main/services/settings.service-host.ts#L61)):*
> ```XML
>     // Assert type of the particular SettingName of the emitter.
>     // eslint-disable-next-line no-type-assertion/no-type-assertion
>     const emitter = onDidUpdateSettingEmitters.get(key);
> ```

You shouldn't need these emitters anymore because data providers include updates.
___
*[`src/main/services/settings.service-host.ts` line 75 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3260vAX92bZRAU1-N:-Nq3260vAX92bZRAU1-O:bnmlmbp) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/main/services/settings.service-host.ts#L75)):*
> ```XML
>     // Assert type of the particular SettingName of the emitter.
>     // eslint-disable-next-line no-type-assertion/no-type-assertion
>     const emitter = onDidUpdateSettingEmitters.get(key);
> ```

Since you won't have these emitters anymore, you'll need to send out an update via `this.notifyUpdate` like `this.notifyUpdate('')`.
___
*[`src/main/services/settings.service-host.ts` line 82 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq31eygBtf62QCAtAj7:-Nq31eyhDUEb7DC42t5Y:bjs220k) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/main/services/settings.service-host.ts#L82)):*
> ```XML
> 
>   // eslint-disable-next-line class-methods-use-this
>   async subscribe<SettingName extends SettingNames>(
> ```

You shouldn't need subscribe anymore because data providers include updates (note that subscribe is created on the local proxy of each data provider on each local process because you can't run the code across processes).
___
*[`src/shared/services/papi-core.service.ts` line 37 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq36I7R-seo8xG2K98p:-Nq36I7R-seo8xG2K98q:btjegqo) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/shared/services/papi-core.service.ts#L37)):*
> ```XML
> export type { IWebViewProvider } from '@shared/models/web-view-provider.model';
> 
> // TODO: Do we need this here? How to fix?
> ```

You can remove this since we will be using the data provider subscription stuff that has the event built in :)
___
*[`src/shared/services/settings.service-model.ts` line 18 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq36U-L1C9u4bOVCpqU:-Nq36U-L1C9u4bOVCpqV:b6z0u9a) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/shared/services/settings.service-model.ts#L18)):*
> ```XML
>    * Name used to register the data provider
>    *
>    * You can use this name
> ```

This needs more elaboration. You can probably do something very similar to the one in the menu data service model file
___
*[`src/shared/services/settings.service-model.ts` line 55 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq36yMi8mAKVbZgLcWT:-Nq36yMi8mAKVbZgLcWU:b-uayhxp) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/shared/services/settings.service-model.ts#L55)):*
> ```XML
> 
> /** All supported setting events */
> export type SettingEvent<SettingName extends SettingNames> =
> ```

You shouldn't need these event types or the emitters anymore :)


<!-- Sent from Reviewable.io -->

2024-02-07 19:27 UTC, tjcouch-sil reviewed
> Reviewed 1 of 3 files at r1, 1 of 6 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752)* status: all files reviewed, 9 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/declarations/papi-shared-types.ts` line 58 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3y3B19bEcs1R2Bf19:-Nq3y3B19bEcs1R2Bf1A:bitec5d) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/declarations/papi-shared-types.ts#L58)):*
> ```XML
>   export interface SettingTypes {
>     'platform.verseRef': ScriptureReference;
>     // 'platform.interfaceLanguage': InterfaceLanguage;
> ```

Does this need to be removed?
___
*[`src/main/services/settings.service-host.ts` line 48 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq40VaF2R0DvT7ggHej:-Nq40VaF2R0DvT7ggHek:ba3l9u4) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/main/services/settings.service-host.ts#L48)):*
> ```XML
>   ): Promise<DataProviderUpdateInstructions<SettingDataTypes>> {
>     localStorage.setItem(key, serialize(newSetting));
>     this.notifyUpdate('*');
> ```

Data provider engines' `set<data_type>` methods are modified to send an update automatically based on the return from the function. As such, there is an implicit `this.notifyUpdate('')` that runs when you return `true`, so this is not necessary.
___
*[`src/main/services/settings.service-host.ts` line 55 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq40k7EAeqrMQ03FHwn:-Nq40k7F1KKUT3S8YnlK:b-fs6rk5) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/main/services/settings.service-host.ts#L55)):*
> ```XML
>   async reset<SettingName extends SettingNames>(key: SettingName): Promise<boolean> {
>     localStorage.removeItem(key);
>     this.notifyUpdate('*');
> ```

Running an update with `'*'` will send out a notice to all listeners on a data provider that they need to update. Since this is specifically related to the `''` (empty string) data type, I'd recommend listing only `''` here like `this.notifyUpdate('')`. Though it is equivalent currently, changing it to the specific data type that is updating will prevent unnecessary update notifications in the future if we ever add other data types onto this data provider.
___
*[`src/main/services/settings.service-host.ts` line 56 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq41J2r1NAAUP4LhMTE:-Nq41J2r1NAAUP4LhMTF:bioexe3) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/main/services/settings.service-host.ts#L56)):*
> ```XML
>     localStorage.removeItem(key);
>     this.notifyUpdate('*');
>     return true;
> ```

This needs to return true if the setting was successfully removed and false if not. If this is too annoying to check or whatever, we can reconsider this design.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 22 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq4-BTe7tsqeOAeaB5x:-Nq4-BTe7tsqeOAeaB5y:bxmn4g5) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L22)):*
> ```XML
>  *   it in local storage, this parameter will be ignored.
>  *
>  *   Note: this parameter is internally assigned to a `ref`, so changing it will not cause any hooks
> ```

As mentioned below, this parameter no longer needs to be a ref. Additionally, some of these comments probably need a bit of a tune-up to match the new functionality. If it's interesting, you can look at my [`useProjectSetting`](https://github.com/paranext/paranext-core/blob/509-project-settings-service/src/renderer/hooks/papi-hooks/use-project-setting.hook.ts) JSDoc, but no pressure. Particularly useful may be the returned value descriptions as they have changed somewhat significantly.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 56 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq4-3Hz2HRm8v2Lpmh9:-Nq4-3Hz2HRm8v2LpmhA:b6lkgvh) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L56)):*
> ```XML
> ] => {
>   // Use defaultState as a ref so it doesn't update dependency arrays
>   const defaultStateRef = useRef(defaultState);
> ```

This ref stuff should be removed since it is no longer necessary. `useData` doesn't do something with its default value that would make it need a ref.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 59 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3ze98BnCvBN3Kr89T:-Nq3ze98BnCvBN3Kr89U:b-sdvv2b) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L59)):*
> ```XML
>   defaultStateRef.current = defaultState;
> 
>   /* eslint-disable no-type-assertion/no-type-assertion */
> ```

This needs a comment explaining why we are type asserting. If you're looking for a model, you might be able to say something sort-of similar to my comment on [`useProjectSetting`](https://github.com/paranext/paranext-core/blob/509-project-settings-service/src/renderer/hooks/papi-hooks/use-project-setting.hook.ts), but your situation is somewhat different.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 81 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3zP4_D5bgXs0AxzcX:-Nq3zP4_D5bgXs0AxzcY:bnjqekc) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L81)):*
> ```XML
>   }, [key]);
> 
>   return [setting, setSetting, resetSetting];
> ```

Would you mind also returning the `isLoading` value from `useData` here? Sorry; I changed my mind about this.
___
*[`src/shared/services/settings.service-model.ts` line 61 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq4-xcqER3wTNwPIemw:-Nq4-xcqER3wTNwPIemx:b-g78jrj) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/shared/services/settings.service-model.ts#L61)):*
> ```XML
>    *   key
>    * @returns The value of the specified setting, parsed to an object. Returns default setting if
>    *   setting does not exist
> ```

A number of these JSDocs are outdated. For example, this function needs to note that it can throw now. If you're interested, you can see my JSDocs on [`IProjectDataProvider`](https://github.com/paranext/paranext-core/blob/509-project-settings-service/src/declarations/papi-shared-types.ts#L178) to see some similar methods. No pressure of course.


<!-- Sent from Reviewable.io -->

2024-02-08 19:58 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752)* status: 7 of 12 files reviewed, 9 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/declarations/papi-shared-types.ts` line 58 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3y3B19bEcs1R2Bf19:-Nq8ElQN0pbhtBzx0-Po:b-15kqde) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/declarations/papi-shared-types.ts#L58)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Does this need to be removed?
</blockquote></details>

No we were hoping to add that setting as part of this task, so we have more than one setting to play around with. If that's okay.
___
*[`src/main/services/settings.service-host.ts` line 61 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3-GBz8PK_TAYlSr21:-Nq3EQKZ80I2UxDDhSx4:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/main/services/settings.service-host.ts#L61)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You shouldn't need these emitters anymore because data providers include updates.
</blockquote></details>

Done.
___
*[`src/main/services/settings.service-host.ts` line 75 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3260vAX92bZRAU1-N:-Nq3E_HvBspPgJ8cmCvg:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/main/services/settings.service-host.ts#L75)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since you won't have these emitters anymore, you'll need to send out an update via `this.notifyUpdate` like `this.notifyUpdate('')`.
</blockquote></details>

Done.
___
*[`src/main/services/settings.service-host.ts` line 82 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq31eygBtf62QCAtAj7:-Nq3Et5ABxX1IFfG53wJ:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/main/services/settings.service-host.ts#L82)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You shouldn't need subscribe anymore because data providers include updates (note that subscribe is created on the local proxy of each data provider on each local process because you can't run the code across processes).
</blockquote></details>

Done.
___
*[`src/main/services/settings.service-host.ts` line 48 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq40VaF2R0DvT7ggHej:-Nq8F2_E9AWTnWsUth_P:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/main/services/settings.service-host.ts#L48)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Data provider engines' `set<data_type>` methods are modified to send an update automatically based on the return from the function. As such, there is an implicit `this.notifyUpdate('')` that runs when you return `true`, so this is not necessary.
</blockquote></details>

Done.
___
*[`src/main/services/settings.service-host.ts` line 55 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq40k7EAeqrMQ03FHwn:-Nq8FAoxE2x9kgWlqT8X:b-vfw7ti) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/main/services/settings.service-host.ts#L55)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Running an update with `'*'` will send out a notice to all listeners on a data provider that they need to update. Since this is specifically related to the `''` (empty string) data type, I'd recommend listing only `''` here like `this.notifyUpdate('')`. Though it is equivalent currently, changing it to the specific data type that is updating will prevent unnecessary update notifications in the future if we ever add other data types onto this data provider.
</blockquote></details>

`this.notifyUpdate('')` is not allowed.
`Argument of type '""' is not assignable to parameter of type 'DataProviderUpdateInstructions<SettingDataTypes> | undefined'.ts(2345)`
___
*[`src/main/services/settings.service-host.ts` line 56 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq41J2r1NAAUP4LhMTE:-Nq8FiUG7640MmtZ8zIg:b-32w5iq) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/main/services/settings.service-host.ts#L56)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This needs to return true if the setting was successfully removed and false if not. If this is too annoying to check or whatever, we can reconsider this design.
</blockquote></details>

I added a to-do so we can pick this up later, when we've set up our new way to store the settings
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 22 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq4-BTe7tsqeOAeaB5x:-Nq8Q3o-BzJEqPhRSkAp:bh2v2z4) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L22)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

As mentioned below, this parameter no longer needs to be a ref. Additionally, some of these comments probably need a bit of a tune-up to match the new functionality. If it's interesting, you can look at my [`useProjectSetting`](https://github.com/paranext/paranext-core/blob/509-project-settings-service/src/renderer/hooks/papi-hooks/use-project-setting.hook.ts) JSDoc, but no pressure. Particularly useful may be the returned value descriptions as they have changed somewhat significantly.
</blockquote></details>

Done. I'm not a 100% sure if the way setting and resetting work are still as described in the comments here.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 56 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq4-3Hz2HRm8v2Lpmh9:-Nq8R5SVBLsQudnXmmM-:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L56)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This ref stuff should be removed since it is no longer necessary. `useData` doesn't do something with its default value that would make it need a ref.
</blockquote></details>

Done.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 59 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3ze98BnCvBN3Kr89T:-Nq9CL6ZCSdo3XM3MKHR:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L59)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This needs a comment explaining why we are type asserting. If you're looking for a model, you might be able to say something sort-of similar to my comment on [`useProjectSetting`](https://github.com/paranext/paranext-core/blob/509-project-settings-service/src/renderer/hooks/papi-hooks/use-project-setting.hook.ts), but your situation is somewhat different.
</blockquote></details>

Done.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 81 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3zP4_D5bgXs0AxzcX:-Nq8RPpU3X-LgH45WdeT:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L81)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Would you mind also returning the `isLoading` value from `useData` here? Sorry; I change [...]

2024-02-08 23:01 UTC, tjcouch-sil reviewed
> Reviewed 4 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/declarations/papi-shared-types.ts` line 58 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3y3B19bEcs1R2Bf19:-Nq9t5G7CTyoeT771_lr:bt04rts) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/declarations/papi-shared-types.ts#L58)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

No we were hoping to add that setting as part of this task, so we have more than one setting to play around with. If that's okay.
</blockquote></details>

It's fine to add another setting. I was just confused as to why it's commented out.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 22 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq4-BTe7tsqeOAeaB5x:-Nq9w1wYA7AC2m_4jLhZ:bw096ck) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L22)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done. I'm not a 100% sure if the way setting and resetting work are still as described in the comments here.
</blockquote></details>

Actually there isn't really a reason to explain all this anymore since it has changed as described in my comment above. If a setting's default somehow changes, it's now the job of the setting service to send out an update and to tell us to get the new value. It no longer relies on parameters of the hook or anything like that. As such, it would probably be best just to remove the lines that were moved from here to the first paragraph.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 59 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3ze98BnCvBN3Kr89T:-Nq9vIQy6xYcDFOr6oFb:b-50qzab) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L59)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This one is a bit tricky: actually it isn't a problem that it's unnamed. The issue comes from `SettingDataTypes` not actually having the data type on it because we're using custom methods. `useData` only sees the data types, but we know we have the `get`, `set`, and `subscribe` functions implemented that are necessary for `useData`.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 81 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3zP4_D5bgXs0AxzcX:-Nq9wW0aAZTQb1y3atIV:bsuxtnt) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L81)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! Sorry for the moving target :p
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 24 at r7](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq9vdQj67zn8CARKI1E:-Nq9vdQj67zn8CARKI1F:b-jpxnzt) ([raw file](https://github.com/paranext/paranext-core/blob/5340485eec652ad9d4a99d7d8bdcc6b6c69ce333/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L24)):*
> ```XML
>  *   updated every render
>  * @param defaultState The default state of the setting. If the setting already has a value set to
>  *   it in the settings storage, this parameter will be ignored.
> ```

This is unfortunately incorrect now due to the asynchronous nature of the setting service. The `defaultState` will be the very first value returned from the hook. Then once we get a setting value from the service, `defaultState` will never again be used. I suggest something along these lines or however you want to word it:

```typescript
@param defaultState The initial value to return while first awaiting the setting value
```
___
*[`src/shared/services/settings.service-model.ts` line 55 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq36yMi8mAKVbZgLcWT:-Nq9wfxxE0gZ3c_gdX7-:b7ue8ip) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/shared/services/settings.service-model.ts#L55)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You should be able to remove `UpdateSettingEvent` and `ResetSettingEvent` as well :)


<!-- Sent from Reviewable.io -->

2024-02-09 16:13 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/main/services/settings.service-host.ts` line 68 at r7](https://reviewable.io/reviews/paranext/paranext-core/752#-NqDbFKG8yGjpc6A2Pww:-NqDbFKG8yGjpc6A2Pwx:b8ofbn2) ([raw file](https://github.com/paranext/paranext-core/blob/5340485eec652ad9d4a99d7d8bdcc6b6c69ce333/src/main/services/settings.service-host.ts#L68)):*
> ```XML
>   async reset<SettingName extends SettingNames>(key: SettingName): Promise<boolean> {
>     localStorage.removeItem(key);
>     // this.notifyUpdate(''); TODO: Fix
> ```

@tjcouch-sil Can we look into this? We had a discussion about it before but Reviewable is hiding it from me for some reason. 
VS Code tells me `Argument of type '""' is not assignable to parameter of type 'DataProviderUpdateInstructions<SettingDataTypes> | undefined'.ts(2345)` when I enable this line
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 22 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq4-BTe7tsqeOAeaB5x:-NqDXI7t6BFaQc9_5kKb:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L22)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Actually there isn't really a reason to explain all this anymore since it has changed as described in my comment above. If a setting's default somehow changes, it's now the job of the setting service to send out an update and to tell us to get the new value. It no longer relies on parameters of the hook or anything like that. As such, it would probably be best just to remove the lines that were moved from here to the first paragraph.
</blockquote></details>

Done.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 59 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3ze98BnCvBN3Kr89T:-NqDZwIM2WiwZS3Pr36Z:b-vf6qzg) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L59)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This one is a bit tricky: actually it isn't a problem that it's unnamed. The issue comes from `SettingDataTypes` not actually having the data type on it because we're using custom methods. `useData` only sees the data types, but we know we have the `get`, `set`, and `subscribe` functions implemented that are necessary for `useData`.
</blockquote></details>

Thanks for explaining! The comment should be better like this.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 81 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3zP4_D5bgXs0AxzcX:-NqD_1JX7Aj7CmZrTZJg:bv0fp8h) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L81)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Thanks! Sorry for the moving target :p
</blockquote></details>

Lol don't worry. That's my punishment for creating draft PRs
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 24 at r7](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq9vdQj67zn8CARKI1E:-NqDXQEU8QeUz6DNminB:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/5340485eec652ad9d4a99d7d8bdcc6b6c69ce333/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L24)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is unfortunately incorrect now due to the asynchronous nature of the setting service. The `defaultState` will be the very first value returned from the hook. Then once we get a setting value from the service, `defaultState` will never again be used. I suggest something along these lines or however you want to word it:

```typescript
@param defaultState The initial value to return while first awaiting the setting value
```
</blockquote></details>

Done.
___
*[`src/shared/services/settings.service-model.ts` line 55 at r4](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq36yMi8mAKVbZgLcWT:-NqD_DbdCZJkoplD_AWL:b-h5g1tk) ([raw file](https://github.com/paranext/paranext-core/blob/1da3c05007f3f460ced511e32f80d61c7dccf3c3/src/shared/services/settings.service-model.ts#L55)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You should be able to remove `UpdateSettingEvent` and `ResetSettingEvent` as well :)
</blockquote></details>

Done. Good call


<!-- Sent from Reviewable.io -->

2024-02-09 16:35 UTC, tjcouch-sil reviewed
> Reviewed 1 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752)* status: 9 of 13 files reviewed, 5 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/main/services/settings.service-host.ts` line 55 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq40k7EAeqrMQ03FHwn:-Nq9toIf4MHlgdePnTVE:bpoj9vs) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/main/services/settings.service-host.ts#L55)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

`this.notifyUpdate('')` is not allowed.
`Argument of type '""' is not assignable to parameter of type 'DataProviderUpdateInstructions<SettingDataTypes> | undefined'.ts(2345)`
</blockquote></details>

Oh yeah, I forgot about this. Sorry about that. I believe this is a problem because `SettingDataTypes` doesn't actually have the `''` data type in it because we're doing custom more specific methods. Same kind of thing happened for me as well for project settings.

I fixed it by adding the data type in-line in the `DataProviderEngine` generic that I was extending: https://github.com/paranext/paranext-core/blob/509-project-settings-service/src/shared/models/project-data-provider-engine.model.ts#L53 feel free to do something similar or something different. However you do it, though, please include a comment explaining why you did it so we don't forget later :)
___
*[`src/main/services/settings.service-host.ts` line 68 at r7](https://reviewable.io/reviews/paranext/paranext-core/752#-NqDbFKG8yGjpc6A2Pww:-NqDiC5r6o8bMHP8TxwY:boft57e) ([raw file](https://github.com/paranext/paranext-core/blob/5340485eec652ad9d4a99d7d8bdcc6b6c69ce333/src/main/services/settings.service-host.ts#L68)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

@tjcouch-sil Can we look into this? We had a discussion about it before but Reviewable is hiding it from me for some reason. 
VS Code tells me `Argument of type '""' is not assignable to parameter of type 'DataProviderUpdateInstructions<SettingDataTypes> | undefined'.ts(2345)` when I enable this line
</blockquote></details>

Oh weird, the comment I wrote didn't get posted with the other comments yesterday. Will post now real quick so you have it (haven't looked at the rest of the PR yet)


<!-- Sent from Reviewable.io -->

2024-02-09 16:39 UTC, tjcouch-sil reviewed
> Reviewed 3 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 22 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq4-BTe7tsqeOAeaB5x:-NqDi_WpAy3QAKrAwIfz:b-dhupvr) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L22)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I think the second sentence from the previous comment should stay:

"Gets, sets and resets a setting on the papi. Also notifies subscribers when the setting changes and gets updated when the setting is changed by others.
"
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 59 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq3ze98BnCvBN3Kr89T:-NqDipeN8tnjMxJrGmNM:b-kwh4m9) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L59)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Thanks for explaining! The comment should be better like this.
</blockquote></details>

Perfect :) thanks!


<!-- Sent from Reviewable.io -->

2024-02-13 15:42 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/main/services/settings.service-host.ts` line 55 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq40k7EAeqrMQ03FHwn:-NqY0eD85V37HwuKpQmT:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/main/services/settings.service-host.ts#L55)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oh yeah, I forgot about this. Sorry about that. I believe this is a problem because `SettingDataTypes` doesn't actually have the `''` data type in it because we're doing custom more specific methods. Same kind of thing happened for me as well for project settings.

I fixed it by adding the data type in-line in the `DataProviderEngine` generic that I was extending: https://github.com/paranext/paranext-core/blob/509-project-settings-service/src/shared/models/project-data-provider-engine.model.ts#L53 feel free to do something similar or something different. However you do it, though, please include a comment explaining why you did it so we don't forget later :)
</blockquote></details>

Done.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 22 at r5](https://reviewable.io/reviews/paranext/paranext-core/752#-Nq4-BTe7tsqeOAeaB5x:-NqEjlDo22TMj41B8GKc:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2439c5ac406e2ba7226e731233bb9f4c9ff3eedf/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L22)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Sorry, I think the second sentence from the previous comment should stay:

"Gets, sets and resets a setting on the papi. Also notifies subscribers when the setting changes and gets updated when the setting is changed by others.
"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-13 20:04 UTC, tjcouch-sil requested changes
Awesome! Thanks for the updates.

> Reviewed 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752#-:-NqZ3UmJ8LU5qE4h4dk7:bv9dgbo)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/declarations/papi-shared-types.ts` line 58 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ1rsd5OA1vnLD77Ak:-NqZ1rsd5OA1vnLD77Al:b8cohfi) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/declarations/papi-shared-types.ts#L58)):*
> ```XML
>   export interface SettingTypes {
>     'platform.verseRef': ScriptureReference;
>     'platform.interfaceLanguage': string;
> ```

This is going to have to be a `string[]` in Katherine's work. She will need to change it as part of her issue. Since this didn't exist before and she may not have it on her radar, I recommend letting her know you added this and pointing her to this PR so she knows what she needs to change. Or whatever you want to do is fine. Feel free to take whatever course of action and to resolve this comment.
___
*[`src/main/services/settings.service-host.ts` line 82 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqYzrzjDbyhHxzQeMdt:-NqYzrzjDbyhHxzQeMdu:b3q9vdv) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/main/services/settings.service-host.ts#L82)):*
> ```XML
>   async reset<SettingName extends SettingNames>(key: SettingName): Promise<boolean> {
>     try {
>       if (this.settingsData[key]) {
> ```

For readability, I think it would be nice to change this to a guard clause returning false first, then doing the rest. And I think the last two lines in this function could be moved up with this other "success" code to make it easier to read as well. No action needed unless desired
___
*[`src/main/services/settings.service-host.ts` line 84 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqYzZTp8U9-QJMDFrJY:-NqYzZTp8U9-QJMDFrJZ:b-fkb80j) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/main/services/settings.service-host.ts#L84)):*
> ```XML
>       if (this.settingsData[key]) {
>         delete this.settingsData[key];
>         await nodeFS.writeFile(SETTINGS_FILE_URI, JSON.stringify(this.settingsData));
> ```

I think it would be nice to see saving settings to a file in a helper method or something instead of being duplicated here and in `set`, but it's no big deal. No action needed unless desired
___
*[`src/main/services/settings.service-host.ts` line 95 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ-CK84mKCNpbHaVCa:-NqZ-CK84mKCNpbHaVCb:b-w476fj) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/main/services/settings.service-host.ts#L95)):*
> ```XML
>   // Internal function used by get, does not need to use this
>   // eslint-disable-next-line class-methods-use-this
>   #getDefaultValueForKey<SettingName extends SettingNames>(
> ```

Since this doesn't use `this`, it could probably safely be moved out to be a function outside this class or made static or something. Not a big deal; just fyi
___
*[`src/main/services/settings.service-host.test.ts` line 73 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ15N62SAeevoBhAxy:-NqZ15N62SAeevoBhAxz:b-9ht57c) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/main/services/settings.service-host.test.ts#L73)):*
> ```XML
> });
> 
> test('Reset interfaceLanguage returns true', async () => {
> ```

These reset tests depend on some things being set up outside the test and certain things not running beforehand, so they do not really stand independently. I'd recommend either setting up the settings provider engine in a "before every test" jest function (can't remember how to do this offhand) to make sure the state is exactly what you expect every time you run this test or setting up the state in the engine at the start of the test and genericizing these tests. Probably would be more like "Reset a setting with a value returns true" and "Reset a setting with no value returns false"


<!-- Sent from Reviewable.io -->

2024-02-13 20:42 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/declarations/papi-shared-types.ts` line 58 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ1rsd5OA1vnLD77Ak:-NqZ7-rM-wpwXMQBU_aK:b4xy2w3) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/declarations/papi-shared-types.ts#L58)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is going to have to be a `string[]` in Katherine's work. She will need to change it as part of her issue. Since this didn't exist before and she may not have it on her radar, I recommend letting her know you added this and pointing her to this PR so she knows what she needs to change. Or whatever you want to do is fine. Feel free to take whatever course of action and to resolve this comment.
</blockquote></details>

Talked about it with Katherine, and changed it to `string[]` in our code
___
*[`src/main/services/settings.service-host.ts` line 82 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqYzrzjDbyhHxzQeMdt:-NqZ7IGz8veRFCjQmQUX:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/main/services/settings.service-host.ts#L82)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

For readability, I think it would be nice to change this to a guard clause returning false first, then doing the rest. And I think the last two lines in this function could be moved up with this other "success" code to make it easier to read as well. No action needed unless desired
</blockquote></details>

Done
___
*[`src/main/services/settings.service-host.ts` line 84 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqYzZTp8U9-QJMDFrJY:-NqZ847x5t6JU158MNsK:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/main/services/settings.service-host.ts#L84)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it would be nice to see saving settings to a file in a helper method or something instead of being duplicated here and in `set`, but it's no big deal. No action needed unless desired
</blockquote></details>

Done
___
*[`src/main/services/settings.service-host.ts` line 95 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ-CK84mKCNpbHaVCa:-NqZ8d7PE3S_u70RT5Lq:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/main/services/settings.service-host.ts#L95)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since this doesn't use `this`, it could probably safely be moved out to be a function outside this class or made static or something. Not a big deal; just fyi
</blockquote></details>

Done
___
*[`src/main/services/settings.service-host.test.ts` line 73 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ15N62SAeevoBhAxy:-NqZ9rAsCpRZhT3OhNYA:b-mo6sp6) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/main/services/settings.service-host.test.ts#L73)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

These reset tests depend on some things being set up outside the test and certain things not running beforehand, so they do not really stand independently. I'd recommend either setting up the settings provider engine in a "before every test" jest function (can't remember how to do this offhand) to make sure the state is exactly what you expect every time you run this test or setting up the state in the engine at the start of the test and genericizing these tests. Probably would be more like "Reset a setting with a value returns true" and "Reset a setting with no value returns false"
</blockquote></details>

I guess all tests, and not just the `reset` test, depend on how we've setup our engine and related objects at the top of the file, right?

I'm familiar with `set up` and `tear down` functions that are run before and after every test. I'm not sure if we could do that here though. Let's talk about it


<!-- Sent from Reviewable.io -->

2024-02-13 22:34 UTC, tjcouch-sil requested changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/declarations/papi-shared-types.ts` line 58 at r9](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ1rsd5OA1vnLD77Ak:-NqZ_6hy2oRCBm4_j57c:bs466u4) ([raw file](https://github.com/paranext/paranext-core/blob/4baf9a1443134e698408deac896688f2dd61bd54/src/declarations/papi-shared-types.ts#L58)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Talked about it with Katherine, and changed it to `string[]` in our code
</blockquote></details>

Thanks! Sorry for the inconvenience
___
*[`src/main/services/settings.service-host.ts` line 90 at r10](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ_klc1Qx6lEjp7k11:-NqZ_klc1Qx6lEjp7k12:b-m8iyru) ([raw file](https://github.com/paranext/paranext-core/blob/7c0d51d73309475578210bd3d1c2c01709aab2f9/src/main/services/settings.service-host.ts#L90)):*
> ```XML
>     try {
>       this.settingsData[key] = newSetting;
>       writeSettingsDataToFile(this.settingsData);
> ```

This should probably be `await`ed here and below (or if you feel it is particularly important not to wait on it, another option would be to try/catch and `await` and log an error with saving the settings if it fails all inside the `writeSettingsDataToFile` function. Less fail-safe, but you don't make people wait to save to file 🤷 can always be updated later anyway if we ever notice a problem, so not a huge deal whichever you choose).
___
*[`src/main/services/settings.service-host.ts` line 99 at r10](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ_Y7r5MNdI9c_7pUd:-NqZ_Y7r5MNdI9c_7pUe:b-9cgrr4) ([raw file](https://github.com/paranext/paranext-core/blob/7c0d51d73309475578210bd3d1c2c01709aab2f9/src/main/services/settings.service-host.ts#L99)):*
> ```XML
>   async reset<SettingName extends SettingNames>(key: SettingName): Promise<boolean> {
>     try {
>       if (!this.settingsData[key]) {
> ```

Oh I just realized this isn't properly working for `undefined`... Sorry I didn't notice before 😖 I think this needs to be `!(key in this.settingsData)` so you can reset from `undefined`


<!-- Sent from Reviewable.io -->

2024-02-14 13:37 UTC, rolfheij-sil reviewed
Thanks for the fast and good review as always

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752#-:-Nqbp03xDuxPkaHYMRCQ:bkj4sgz)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/main/services/settings.service-host.ts` line 90 at r10](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ_klc1Qx6lEjp7k11:-NqbommO9nLvbjomDZiJ:bi47uk5) ([raw file](https://github.com/paranext/paranext-core/blob/7c0d51d73309475578210bd3d1c2c01709aab2f9/src/main/services/settings.service-host.ts#L90)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This should probably be `await`ed here and below (or if you feel it is particularly important not to wait on it, another option would be to try/catch and `await` and log an error with saving the settings if it fails all inside the `writeSettingsDataToFile` function. Less fail-safe, but you don't make people wait to save to file 🤷 can always be updated later anyway if we ever notice a problem, so not a huge deal whichever you choose).
</blockquote></details>

Done. I simply forgot the await, sorry
___
*[`src/main/services/settings.service-host.ts` line 99 at r10](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ_Y7r5MNdI9c_7pUd:-NqboxOR0svzm1PRKpYl:bo2odm8) ([raw file](https://github.com/paranext/paranext-core/blob/7c0d51d73309475578210bd3d1c2c01709aab2f9/src/main/services/settings.service-host.ts#L99)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oh I just realized this isn't properly working for `undefined`... Sorry I didn't notice before 😖 I think this needs to be `!(key in this.settingsData)` so you can reset from `undefined`
</blockquote></details>

Done.. Good catch!


<!-- Sent from Reviewable.io -->

2024-02-14 14:53 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> wooo!!! Go team! Thanks again for the persistence and hard work, guys!

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/752#-:-Nqc5tzu8G3nel_WimZI:b30p9bs)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/main/services/settings.service-host.ts` line 90 at r10](https://reviewable.io/reviews/paranext/paranext-core/752#-NqZ_klc1Qx6lEjp7k11:-Nqc5loq217PAYcYWx2m:bwlkgx1) ([raw file](https://github.com/paranext/paranext-core/blob/7c0d51d73309475578210bd3d1c2c01709aab2f9/src/main/services/settings.service-host.ts#L90)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done. I simply forgot the await, sorry
</blockquote></details>

No worries; just wanted to share about the available options in case you had something in mind :) thanks!


<!-- Sent from Reviewable.io -->

2024-02-14 14:54 UTC, merged