738 improve localization service (pull request on new fixed branch)
paranext/paranext-core pull request #822
Opened 2024-03-28 22:44 UTC by katherinejensen00

Improve the localization service by having it check default and backup languages and keys as well as by switching from using network objects to data provider, and creating a convert book number to localized id utility.

2024-04-02 22:41 UTC, tjcouch-sil requested changes
Thanks for all the hard work!! :)

> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822#-:-NuVyAQF5r5ymqBnQ3aV:b4pyc2o)* status: all files reviewed, 13 unresolved discussions (waiting on @katherinejensen00)

___
*[`assets/localization/zh-hans.json` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuP5f7k3xEO6znhAdIS:-NuP5f7k3xEO6znhAdIT:beva76l) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/assets/localization/zh-hans.json#L2)):*
> ```JSON
> {
>   "Paratext.SBAFootnotePopupMenu.DrawMenu.\"Hide\"": "隐藏",
> ```

I think it might be best to have just whichever book strings we are using for now since this is a lot of data that we might never use. Same with `zh-hant.json`
___
*[`lib/platform-bible-utils/src/scripture-util.ts` line 132 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuP6jKC0glc4g_ckP2g:-NuP6jKC0glc4g_ckP2h:bog7b6n) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/lib/platform-bible-utils/src/scripture-util.ts#L132)):*
> ```XML
>   if (!startsWith(Intl.getCanonicalLocales(localizationLanguage)[0], 'zh'))
>     return getLocalizedString({
>       localizeKey: `LocalizedId.${id}`,
> ```

Would you mind going ahead and pulling the `km.xml` `LocalizedId.___` strings over from Paratext since that's the one example we found of this path being used?
___
*[`lib/platform-bible-utils/src/scripture-util.ts` line 142 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuP7Ssc-r7PT3uvwZWG:-NuP7Ssc-r7PT3uvwZWH:b-ghc7mu) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/lib/platform-bible-utils/src/scripture-util.ts#L142)):*
> ```XML
>   });
>   const parts = bookName.split('-');
>   // some entries had a second name inside ideographic parenthesis
> ```

We should use the string util function for `split` here and below
___
*[`src/main/services/localization.service-host.ts` line 46 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVOxddBUWsjaCjo3Fy:-NuVOxddBUWsjaCjo3Fz:b-y4gean) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L46)):*
> ```XML
>   if (!baseCode) {
>     if (shouldThrowIfNotFound())
>       throw new Error(`Localization service - No match for language code ${languageCode}`);
> ```

This error message looks outdated to me - would it be appropriate to update it to match what it is throwing?
___
*[`src/main/services/localization.service-host.ts` line 76 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVnzWEC1vLIAtM8Sot:-NuVnzWEC1vLIAtM8Sou:b-ok9l11) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L76)):*
> ```XML
> /** Map of BCP 47 code to localized values for that language */
> const languageLocalizedData = new Map<string, LocalizationData>();
> const localizedStringMetadata = new Map<string, LocalizedStringMetadata>();
> ```

It appears to me that there's just one of these. If so, it would probably be best to simplify this to just `LocalizedStringMetadata | undefined` instead of a map of it.
___
*[`src/main/services/localization.service-host.ts` line 124 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVOWQ_3hDzahfMYjyc:-NuVOWQ_3hDzahfMYjyd:b-uawirx) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L124)):*
> ```XML
> }
> 
> async function getCanonicalLocales(languageCode: string) {
> ```

Since this only works with one locale passed in, this should be renamed something like `getCanonicalLocale` to avoid confusion.
___
*[`src/main/services/localization.service-host.ts` line 156 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVqv-J0Th6uioW1yQZ:-NuVqv-J0Th6uioW1yQ_:b-kptz78) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L156)):*
> ```XML
>   if (standardizedLanguage === undefined) {
>     if (shouldThrowIfNotFound())
>       throw new Error(`Language code(s) invalid and/or does/do not exist`);
> ```

Should this say "language data..."?
___
*[`src/main/services/localization.service-host.ts` line 164 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVqGj9Em8zg9ZYJdgx:-NuVqGj9Em8zg9ZYJdgy:b-gvmccp) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L164)):*
> ```XML
>   if (languageData === undefined) {
>     if (shouldThrowIfNotFound())
>       throw new Error(`Language code(s) invalid and/or does/do not exist`);
> ```

Should this say "language data..."? Also might be good to make it a slightly different error message than the one above for ease of finding it if we hit it. Doesn't have to be dramatically different
___
*[`src/main/services/localization.service-host.ts` line 181 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVrCaaB70XIBBAV5F2:-NuVrCaaB70XIBBAV5F3:b-tjl3k0) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L181)):*
> ```XML
>   const metadata = localizationMetadata[localizeKey];
>   if (!metadata) {
>     if (shouldThrowIfNotFound()) logger.warn(`No metadata exists for ${localizeKey}`);
> ```

I don't think we need to worry about if no metadata exists for a key. There probably won't be in many cases. I'd suggest maybe jsut returning `metadata` and not worrying about if it's undefined.
___
*[`src/main/services/localization.service-host.ts` line 206 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVvTkH3JxY-UKtJHpS:-NuVvTkH3JxY-UKtJHpT:btg381e) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L206)):*
> ```XML
>   async getLocalizedString({ localizeKey, languagesToSearch = [] }: LocalizationSelector) {
>     const languages =
>       languagesToSearch.length > 0 ? languagesToSearch : await getDefaultLanguages();
> ```

It would be best not to modify the array parameter on a public-facing function like this. Please clone the array like `[...languagesToSearch]` before modifying (or don't modify - see other comment).
___
*[`src/main/services/localization.service-host.ts` line 214 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVtCf6AfIT_zRBNrMO:-NuVtCf6AfIT_zRBNrMP:bqkwsbe) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L214)):*
> ```XML
>     // Note: This should never happen, but if it does then there are no languages with data so just
>     // return the localize key so there is some text to display even if we can't find a localization
>     if (initialLanguageData === undefined) return localizeKey;
> ```

This should throw in development (`shouldThrowIfNotFound`)
___
*[`src/main/services/localization.service-host.ts` line 223 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVtlR30GFSQntkipsv:-NuVtlR30GFSQntkipsw:becg1w1) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L223)):*
> ```XML
>       const { fallbackKey } = metadata;
> 
>       // check fallback key in current language
> ```

Checking the fallback key should happen on each language in the list. I recommend putting this check into `findFirstLocalization` and simplifying this `getLocalizedString` function significantly since most of this code would then be in `find [...]

2024-04-05 16:31 UTC, lyonsil requested changes
There is a lot here. There are some adjustments needed, but overall it looks like good progress!

> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822#-:-Nuj5Cy-52nETr1bSeTu:b-upqxbn)* status: all files reviewed, 21 unresolved discussions (waiting on @katherinejensen00 and @tjcouch-sil)

___
*[`assets/localization/zh-hans.json` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuP5f7k3xEO6znhAdIS:-NuioKCT4RU9ipPxZRZd:b-27vinf) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/assets/localization/zh-hans.json#L2)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it might be best to have just whichever book strings we are using for now since this is a lot of data that we might never use. Same with `zh-hant.json`
</blockquote></details>

It seems likely to me that we will want to allow extensions to exist only to contribute localization files. This data could probably be packaged into a Chinese Simplified (or whatever) extension at that point.
___
*[`lib/platform-bible-utils/src/scripture-util.ts` line 109 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-Nuis2bJ6THsLahc_1eP:-Nuis2bJ6THsLahc_1eQ:b-lfubz1) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/lib/platform-bible-utils/src/scripture-util.ts#L109)):*
> ```XML
>  * Convert book number to a localized Id (a short description of the book). This should be used
>  * whenever a book ID (short code) is shown to the user. It is primarily needed for people who do
>  * not read Roman script well /// and need to have books identified in a alternate script (e.g.
> ```

extraneous `///`?
___
*[`lib/platform-bible-utils/src/scripture-util.ts` line 113 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuisEEcDTMZJNl_wIhV:-NuisEEcDTMZJNl_wIhW:be6j1yq) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/lib/platform-bible-utils/src/scripture-util.ts#L113)):*
> ```XML
>  *
>  * @param bookNumber
>  * @param localizationLanguage
> ```

Is `localizationLanguage` the BCP 47 locale? Is this the ISO 639-3 language code? It would be good to clarify that in the comments for this parameter. I think TJ recommended somewhere else calling this `locale` which I assume would be a BCP 47 locale. No matter which it is it would be good to document it here.
___
*[`lib/platform-bible-utils/src/scripture-util.ts` line 114 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuisZLV9SUhPfaG-TdH:-NuisZLV9SUhPfaG-TdI:b-vh28sl) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/lib/platform-bible-utils/src/scripture-util.ts#L114)):*
> ```XML
>  * @param bookNumber
>  * @param localizationLanguage
>  * @param getLocalizedString
> ```

Why do we need to pass in a function parameter here? I'm not saying you're wrong. It's just unusual. Maybe provide some details in the parameter description.
___
*[`src/@types/lib.es2016.intl.d.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuitI80E0vHdJEMqScJ:-NuitI80E0vHdJEMqScK:bcqxyht) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/%40types/lib.es2016.intl.d.ts#L1)):*
> ```XML
> // TODO: Remove this file when VSCode upgrade to Script 5.4 because Intl is typed in 5.4. See
> ```

This has only been an open issue for 4+ years. I'm sure it will be resolved shortly. :laughing: 
___
*[`src/main/services/localization.service-host.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuithDFDwsbI201E8fY:-NuithDFDwsbI201E8fZ:b-f5fxcs) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L24)):*
> ```XML
> // BCP 47 validation regex from https://stackoverflow.com/questions/7035825/regular-expression-for-a-language-tag-as-defined-by-bcp47
> const LANGUAGE_CODE_REGEX =
>   /^(?<grandfathered>(?:en-GB-oed|i-(?:ami|bnn|default|enochian|hak|klingon|lux|mingo|navajo|pwn|t(?:a[oy]|su))|sgn-(?:BE-(?:FR|NL)|CH-DE))|(?:art-lojban|cel-gaulish|no-(?:bok|nyn)|zh-(?:guoyu|hakka|min(?:-nan)?|xiang)))|(?:(?<language>(?:[A-Za-z]{2,3}(?:-(?<extlang>[A-Za-z]{3}(?:-[A-Za-z]{3}){0,2}))?)|[A-Za-z]{4}|[A-Za-z]{5,8})(?:-(?<script>[A-Za-z]{4}))?(?:-(?<region>[A-Za-z]{2}|[0-9]{3}))?(?:-(?<variant>[A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(?:-(?<extension>[0-9A-WY-Za-wy-z](?:-[A-Za-z0-9]{2,8})+))*)(?:-(?<privateUse>x(?:-[A-Za-z0-9]{1,8})+))?$/;
> ```

I'm not saying this regex is wrong, but I do find it humorous that after this change "klingon" will be part of our code.
___
*[`src/main/services/localization.service-host.ts` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-Nuj41g40Fkq9_b9pg-8:-Nuj41g40Fkq9_b9pg-9:boy81w2) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L35)):*
> ```XML
> }
> 
> async function getBaseLanguageCode(languageCode: string) {
> ```

This function parameter is likely a locale, not a language code technically. So I think the function is accepting a BCP 47 locale and returning the ISO 639 language code associated with it. Is that right? If so it might be good to add a one-liner comment for the function explaining that.
___
*[`src/main/services/localization.service-host.ts` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-Nuixvln-nA3-7B3-FAP:-NuixvloCVjPZn8lyLjJ:bklvvka) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L43)):*
> ```XML
>   }
> 
>   const baseCode = await getCanonicalLocales(match[1]);
> ```

If I understand this right, `match[1]` is intended to get the match group named "language".  Is that right? If so it would be better to use the syntax `match.groups.language` or something like that. There is an optional capture group named "grandfathered" that could come before and has more than a single language tag (e.g., "en-GB-oed"). If you happen to grab the "grandfathered" value I don't think you'll find any match.
___
*[`src/main/services/localization.service-host.ts` line 188 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-Nuj07G56SjZnOxgniYR:-Nuj07G56SjZnOxgniYS:bmn8t6e) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L188)):*
> ```XML
> 
> async function findFirstLocalization(localizeKey: string, languages: string[]) {
>   if (languages.length > 0) return undefined;
> ```

I haven't run this code, but it's sort of confusing that this check is `> 0` rather than `<= 0` or `=== 0`. I would think that if I've passed in a bunch of languages to find a key, I want to keep going as long as there are more languages. Once I run out (i.e., the array is empty) then I return `undefined`.

As mentioned later by TJ, it might be better to just iterate through the array and returning the first value found instead of modifying the array, anyway.


<!-- Sent from Reviewable.io -->

2024-04-08 16:01 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822)* status: all files reviewed, 21 unresolved discussions (waiting on @katherinejensen00 and @lyonsil)

___
*[`assets/localization/zh-hans.json` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuP5f7k3xEO6znhAdIS:-NuyMLLO59KPnwxuQGtt:bldsx6d) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/assets/localization/zh-hans.json#L2)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It seems likely to me that we will want to allow extensions to exist only to contribute localization files. This data could probably be packaged into a Chinese Simplified (or whatever) extension at that point.
</blockquote></details>

The reason I suggested removing most of these files was that I imagine we will not need to use 90+% of Paratext's localized strings even in the long run. I prefer to pull them in on an as-need basis.
___
*[`lib/platform-bible-utils/src/scripture-util.ts` line 114 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuisZLV9SUhPfaG-TdH:-NuyMdk5-uSwJ9CWlXzZ:bv8rzlz) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/lib/platform-bible-utils/src/scripture-util.ts#L114)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Why do we need to pass in a function parameter here? I'm not saying you're wrong. It's just unusual. Maybe provide some details in the parameter description.
</blockquote></details>

Agreed that we need JSDocs to explain this situation. The function parameter here is to provide the localized versions of the book ids and names asynchronously. This is a utility function in `platform-bible-utils`, so it needs to avoid accessing the `papi` directly.
___
*[`src/@types/lib.es2016.intl.d.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuitI80E0vHdJEMqScJ:-NuyN9RK0rCH6L8lUgWo:b-iazkti) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/%40types/lib.es2016.intl.d.ts#L1)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This has only been an open issue for 4+ years. I'm sure it will be resolved shortly. :laughing:
</blockquote></details>

The `Intl` stuff was proposed for most of that time. Recently it was finally added to TypeScript 5.4. Hopefully VS Code will update to 5.4 soon. It's out on their nightly build, so I bet it will come in their next release.
___
*[`src/main/services/localization.service-host.ts` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-Nuj41g40Fkq9_b9pg-8:-NuyQny9E_uuKVIubGAI:bneqbrq) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L35)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This function parameter is likely a locale, not a language code technically. So I think the function is accepting a BCP 47 locale and returning the ISO 639 language code associated with it. Is that right? If so it might be good to add a one-liner comment for the function explaining that.
</blockquote></details>

I think the intent of this function was to accept a BCP 47 locale and return its widest canonical locale (so like `en-GB` would reduce to `en`)


<!-- Sent from Reviewable.io -->

2024-04-22 18:51 UTC, katherinejensen00 reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822)* status: 17 of 40 files reviewed, 16 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`assets/localization/zh-hans.json` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuP5f7k3xEO6znhAdIS:-Nuz594GBULjxhu0isYv:b-77jaw) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/assets/localization/zh-hans.json#L2)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The reason I suggested removing most of these files was that I imagine we will not need to use 90+% of Paratext's localized strings even in the long run. I prefer to pull them in on an as-need basis.
</blockquote></details>

That makes a lot of sense and will hopefully prevent some  download size bloating.
___
*[`lib/platform-bible-utils/src/scripture-util.ts` line 109 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-Nuis2bJ6THsLahc_1eP:-NuzEtVwCt3Z5kCx_kHQ:bmqnifu) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/lib/platform-bible-utils/src/scripture-util.ts#L109)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

extraneous `///`?
</blockquote></details>

Absolutely extraneous. Good catch!
___
*[`lib/platform-bible-utils/src/scripture-util.ts` line 113 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuisEEcDTMZJNl_wIhV:-NuzG8QP90nZhuIK2pPM:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/lib/platform-bible-utils/src/scripture-util.ts#L113)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Is `localizationLanguage` the BCP 47 locale? Is this the ISO 639-3 language code? It would be good to clarify that in the comments for this parameter. I think TJ recommended somewhere else calling this `locale` which I assume would be a BCP 47 locale. No matter which it is it would be good to document it here.
</blockquote></details>

Done.
___
*[`lib/platform-bible-utils/src/scripture-util.ts` line 142 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuP7Ssc-r7PT3uvwZWG:-Nv3934j2dX8D6ZC4_sR:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/lib/platform-bible-utils/src/scripture-util.ts#L142)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We should use the string util function for `split` here and below
</blockquote></details>

Done.
___
*[`src/main/services/localization.service-host.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuithDFDwsbI201E8fY:-Nv39_14ElMJv_lI4og6:bkfr4tq) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L24)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm not saying this regex is wrong, but I do find it humorous that after this change "klingon" will be part of our code.
</blockquote></details>

That made me smile too. The Bible has been translated into Klingon. It would be fun to meet someone who had come to know the Lord through reading the Bible in Klingon. 
___
*[`src/main/services/localization.service-host.ts` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-Nuj41g40Fkq9_b9pg-8:-Nv3CHpwEzdy-nqjVFLz:bbv883i) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L35)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think the intent of this function was to accept a BCP 47 locale and return its widest canonical locale (so like `en-GB` would reduce to `en`)
</blockquote></details>

I can see how the wording is unclear. I will add a comment. Thanks for the example, TJ!
___
*[`src/main/services/localization.service-host.ts` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-Nuixvln-nA3-7B3-FAP:-Nv8Isl16WrJB3kvj4sZ:b-4a1nrm) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L43)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If I understand this right, `match[1]` is intended to get the match group named "language".  Is that right? If so it would be better to use the syntax `match.groups.language` or something like that. There is an optional capture group named "grandfathered" that could come before and has more than a single language tag (e.g., "en-GB-oed"). If you happen to grab the "grandfathered" value I don't think you'll find any match.
</blockquote></details>

Great point. Thanks!
___
*[`src/main/services/localization.service-host.ts` line 124 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVOWQ_3hDzahfMYjyc:-NvYI1A5621NJYxYMLW4:b-p9g1ji) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L124)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since this only works with one locale passed in, this should be renamed something like `getCanonicalLocale` to avoid confusion.
</blockquote></details>

Good Point
___
*[`src/main/services/localization.service-host.ts` line 156 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVqv-J0Th6uioW1yQZ:-NvYIERt1v-XErQURSbe:b-847em7) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L156)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should this say "language data..."?
</blockquote></details>

I can see how that would be confusing. My initial thinking was that the data can't be found because of invalid or nonexistent language codes, but that is not immediately obvious. I will change it. Thanks for pointing that out!
___
*[`src/main/services/localization.service-host.ts` line 188 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-Nuj07G56SjZnOxgniYR:-NvcNfaR3O6rqhLXlAZc:b-8ndil2) ([raw file](https://github.com/paranext/paranext-core/blob/1f972cdf29e3f08cd5f97b41041c04678745bad9/src/main/services/localization.service-host.ts#L188)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I haven't run this code, but it's sort of confusing that this check is `> 0` rather than `<= 0` or `=== 0`. I would think that if I've passed in a bunch of languages to find a key, I want to keep going as long as there are more languages. Once I run out (i.e., the array is empty) then I return `undefined`.

As mentioned later by TJ, it might be better to just iterate through the array and returning the first value found instead of modifying the array, anyway.
</blockquote></details>

You are so right about the if. I am not sure what happened there.

I modify the array because both moveToFirstLanguageWithData and findFirstLocalization can find languages that can't be used so we don't want to duplicate efforts by reexamining languages that won't work. A duplicate of the languages is created before this method is called so this is an internal array of languages I am just using to try to improve efficiency. 
Nevermind, I just talked to TJ and realized that was more of a C# way of thinking than a Javascript way of thinking. I am changing it now.
___
*[`src/main/services/localization.service-host.ts` line 206 at r1](https://reviewable.io/reviews/paranext/paranext-core/822#-NuVvTkH3JxY-UKtJHpS:-NvgauW_2swO134d7UPA:b-54wi91) ([raw file](https://github.com/paranext/paranext-core/blob/1 [...]

2024-04-22 22:09 UTC, tjcouch-sil requested changes
> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822)* status: all files reviewed, 8 unresolved discussions (waiting on @katherinejensen00 and @lyonsil)

___
*[`extensions/src/hello-world/src/web-views/hello-world.web-view.tsx` line 54 at r2](https://reviewable.io/reviews/paranext/paranext-core/822#-Nw6AOdE5Zh0YsltUWUb:-Nw6AOdE5Zh0YsltUWUc:b6gplx1) ([raw file](https://github.com/paranext/paranext-core/blob/d582b082af4f162121d2c9b9271d45ed184c4025/extensions/src/hello-world/src/web-views/hello-world.web-view.tsx#L54)):*
> ```XML
> };
> 
> // const localizedGenesis = localizationDataService.
> ```

Extraneous comment?
___
*[`lib/platform-bible-utils/package.json` line 43 at r2](https://reviewable.io/reviews/paranext/paranext-core/822#-Nw6An0q7fPhdFJYzYHX:-Nw6An0q7fPhdFJYzYHY:bfubapa) ([raw file](https://github.com/paranext/paranext-core/blob/f550b274160ea094942d8ed7bca18067d75ccba3/lib/platform-bible-utils/package.json#L43)):*
> ```JSON
>     "test": "jest --silent"
>   },
>   "peerDependencies": {},
> ```

I believe we need this in order to build `platform-bible-utils`
___
*[`lib/platform-bible-utils/src/scripture-util.ts` line 114 at r2](https://reviewable.io/reviews/paranext/paranext-core/822#-Nw6B5MFCiRe5Vwf92aw:-Nw6B5MFCiRe5Vwf92ax:bezvccc) ([raw file](https://github.com/paranext/paranext-core/blob/d582b082af4f162121d2c9b9271d45ed184c4025/lib/platform-bible-utils/src/scripture-util.ts#L114)):*
> ```XML
>  * @param bookNumber
>  * @param localizationLanguage in BCP 47 format
>  * @param getLocalizedString function that provides the localized versions of the book ids and names
> ```

The first sentence here is great. I recommend removing the sentence as it will not make sense to people who use `platform-bible-utils` and nothing else.
___
*[`release/app/package-lock.json` line 12 at r2](https://reviewable.io/reviews/paranext/paranext-core/822#-Nw6BOQ2-BCyEViCll-f:-Nw6BOQ2-BCyEViCll-g:b-foyvbq) ([raw file](https://github.com/paranext/paranext-core/blob/d582b082af4f162121d2c9b9271d45ed184c4025/release/app/package-lock.json#L12)):*
> ```JSON
>       "hasInstallScript": true,
>       "license": "MIT",
>       "devDependencies": {
> ```

I recommend reverting these changes and seeing what happens on running `npm i` as these changes may be incorrect. Would also recommend reverting the change to `release/app/package.json`, but it's not really important.


<!-- Sent from Reviewable.io -->

2024-04-23 19:36 UTC, katherinejensen00 reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822)* status: all files reviewed, 7 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`extensions/src/hello-world/src/web-views/hello-world.web-view.tsx` line 54 at r2](https://reviewable.io/reviews/paranext/paranext-core/822#-Nw6AOdE5Zh0YsltUWUb:-NwAgTO77Fib_ARAl78t:b8pelsu) ([raw file](https://github.com/paranext/paranext-core/blob/d582b082af4f162121d2c9b9271d45ed184c4025/extensions/src/hello-world/src/web-views/hello-world.web-view.tsx#L54)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Extraneous comment?
</blockquote></details>

Oops. Thanks!
___
*[`lib/platform-bible-utils/package.json` line 43 at r2](https://reviewable.io/reviews/paranext/paranext-core/822#-Nw6An0q7fPhdFJYzYHX:-NwAh5dp7fENtdsYVr_N:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/f550b274160ea094942d8ed7bca18067d75ccba3/lib/platform-bible-utils/package.json#L43)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe we need this in order to build `platform-bible-utils`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-23 21:50 UTC, tjcouch-sil submitted a review, later dismissed
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2024-04-23 22:02 UTC, lyonsil submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 19 of 23 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822#-:-NwByh5y7F0O3o9ZojYp:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-25 17:04 UTC, tjcouch-sil requested changes
> Reviewed 25 of 25 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822)* status: all files reviewed, 4 unresolved discussions (waiting on @katherinejensen00)

___
*[`extensions/package.json` line 44 at r4](https://reviewable.io/reviews/paranext/paranext-core/822#-NwLByKh1BVEw70SUCo4:-NwLByKh1BVEw70SUCo5:b-fjpfnd) ([raw file](https://github.com/paranext/paranext-core/blob/98bcd1a9dcfbea2ea3ef20efa0a69e216c20c0ee/extensions/package.json#L44)):*
> ```JSON
>     "@sillsdev/scripture": "^1.4.3",
>     "platform-bible-utils": "file:../lib/platform-bible-utils",
>     "typedoc": "^0.25.13"
> ```

This is not a dependency here and should be removed.
___
*[`lib/papi-dts/package.json` line 49 at r4](https://reviewable.io/reviews/paranext/paranext-core/822#-NwLCdGn4Lp9l09zrxS3:-NwLCdGn4Lp9l09zrxS4:b77slr1) ([raw file](https://github.com/paranext/paranext-core/blob/98bcd1a9dcfbea2ea3ef20efa0a69e216c20c0ee/lib/papi-dts/package.json#L49)):*
> ```JSON
>   "dependencies": {
>     "platform-bible-utils": "file:../platform-bible-utils",
>     "typedoc": "^0.25.13"
> ```

`typedoc` needs to be in `devDependencies`, not `dependencies`
___
*[`lib/platform-bible-react/package.json` line 61 at r4](https://reviewable.io/reviews/paranext/paranext-core/822#-NwLCWQJ6BMcwakGImxr:-NwLCWQJ6BMcwakGImxs:b77slr1) ([raw file](https://github.com/paranext/paranext-core/blob/98bcd1a9dcfbea2ea3ef20efa0a69e216c20c0ee/lib/platform-bible-react/package.json#L61)):*
> ```JSON
>     "tailwind-merge": "^2.2.2",
>     "tailwindcss-animate": "^1.0.7",
>     "typedoc": "^0.25.13"
> ```

`typedoc` needs to be in `devDependencies`, not `dependencies`
___
*[`lib/platform-bible-utils/package.json` line 45 at r4](https://reviewable.io/reviews/paranext/paranext-core/822#-NwLCjYcBXV_4je0BHBD:-NwLCjYcBXV_4je0BHBE:b77slr1) ([raw file](https://github.com/paranext/paranext-core/blob/98bcd1a9dcfbea2ea3ef20efa0a69e216c20c0ee/lib/platform-bible-utils/package.json#L45)):*
> ```JSON
>   "dependencies": {
>     "async-mutex": "^0.4.1",
>     "typedoc": "^0.25.13"
> ```

`typedoc` needs to be in `devDependencies`, not `dependencies`


<!-- Sent from Reviewable.io -->

2024-04-25 17:32 UTC, katherinejensen00 reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822)* status: all files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/package.json` line 44 at r4](https://reviewable.io/reviews/paranext/paranext-core/822#-NwLByKh1BVEw70SUCo4:-NwLDhbx-ATLYTaONIf5:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/98bcd1a9dcfbea2ea3ef20efa0a69e216c20c0ee/extensions/package.json#L44)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is not a dependency here and should be removed.
</blockquote></details>

Done.
___
*[`lib/papi-dts/package.json` line 49 at r4](https://reviewable.io/reviews/paranext/paranext-core/822#-NwLCdGn4Lp9l09zrxS3:-NwLE_eH326tii67pwnW:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/98bcd1a9dcfbea2ea3ef20efa0a69e216c20c0ee/lib/papi-dts/package.json#L49)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

`typedoc` needs to be in `devDependencies`, not `dependencies`
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/package.json` line 61 at r4](https://reviewable.io/reviews/paranext/paranext-core/822#-NwLCWQJ6BMcwakGImxr:-NwLJ2YZCcuw9i0j37o6:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/98bcd1a9dcfbea2ea3ef20efa0a69e216c20c0ee/lib/platform-bible-react/package.json#L61)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

`typedoc` needs to be in `devDependencies`, not `dependencies`
</blockquote></details>

Done.
___
*[`lib/platform-bible-utils/package.json` line 45 at r4](https://reviewable.io/reviews/paranext/paranext-core/822#-NwLCjYcBXV_4je0BHBD:-NwLJ3_AAV03M8IZx1lj:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/98bcd1a9dcfbea2ea3ef20efa0a69e216c20c0ee/lib/platform-bible-utils/package.json#L45)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

`typedoc` needs to be in `devDependencies`, not `dependencies`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-25 17:51 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822#-:-NwLNSTq-TgXw9NEYNpf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-25 19:44 UTC, lyonsil approved these changes
> Reviewed 19 of 25 files at r4, 5 of 5 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/822)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-25 19:53 UTC, merged