Move all of the test webviews and commands behind an env var
paranext/paranext-core pull request #886
Opened 2024-05-02 19:59 UTC by lyonsil

This change moves lots of test code behind an environment variable called "DEV_NOISY". Set that environment variable to "true" to see all of the same test webviews and commands that existed previously except for 2 commands named "test.addThree" and "test.squareAndConcat" that were registered inside of the renderer which have been removed. Note that you will want to clear local storage in the renderer when switching back and forth to see all webviews appropriately.

This change also fixes several small bugs with some built-in extensions.

2024-05-02 22:58 UTC, irahopkinson requested changes
Wow, thanks for all this work

> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/886#-:-NwvWqNeCbMHrPtW-0n7:b-qfo4b0)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`src/main/main.ts` line 128 at r1](https://reviewable.io/reviews/paranext/paranext-core/886#-NwvRxOl2wQoYxB_gfu_:-NwvRxOm2YsBVrvtUr6g:b-vczfyn) ([raw file](https://github.com/paranext/paranext-core/blob/0114b5324f68bd3d4c2fe817376cce4d46b69882/src/main/main.ts#L128)):*
> ```XML
> 
>     mainWindow.loadURL(
>       `${resolveHtmlPath('index.html')}${globalThis.isNoisyDevModeEnabled ? DEV_MODE_RENDERER_INDICATOR : ''}`,
> ```

BTW I thought we could just use `globalThis` even in the render, so I'm wondering why we needed to pass it this way?



_Code quote:_
```XML
DEV_MODE_RENDERER_INDICATOR
```
___
*[`src/renderer/services/papi-frontend.service.ts` line 60 at r1](https://reviewable.io/reviews/paranext/paranext-core/886#-NwvVDjV74nIWmLsoLGB:-NwvVDjV74nIWmLsoLGC:b-1sq1fx) ([raw file](https://github.com/paranext/paranext-core/blob/0114b5324f68bd3d4c2fe817376cce4d46b69882/src/renderer/services/papi-frontend.service.ts#L60)):*
> ```XML
>    * Miscellaneous utility functions and classes
>    */
>   utils: papiUtil,
> ```

Err... aren't we just importing this wherever we need it rather than accessing it from PAPI since its essentially an external package?


<!-- Sent from Reviewable.io -->

2024-05-02 23:02 UTC, irahopkinson reviewed
FYI I'm testing locally now but thought I'd give the feedback first.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/886#-:-NwvXgv9-zAXipAQObB5:bp16sot)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2024-05-02 23:47 UTC, irahopkinson reviewed
Tested fine locally .

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/886#-:-NwvgK1m0SeHbYW6R2Le:b-94scpi)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2024-05-03 14:28 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/886)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`src/main/main.ts` line 128 at r1](https://reviewable.io/reviews/paranext/paranext-core/886#-NwvRxOl2wQoYxB_gfu_:-NwynRVsAjBjiog17lAD:bihlxvq) ([raw file](https://github.com/paranext/paranext-core/blob/0114b5324f68bd3d4c2fe817376cce4d46b69882/src/main/main.ts#L128)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I thought we could just use `globalThis` even in the render, so I'm wondering why we needed to pass it this way?
</blockquote></details>

`globalThis` does work in the renderer, but the indicator of being in dev mode can't be set the same way in the browser and Node.js, and `globalThis` values from `main` don't automatically flow into all of the processes it creates. In the main process and extension host, we can use `process.env` to inspect environment variables, but that is only available in Node.js. In the renderer, there is no built-in way to check environment variables. So the main process needs to tell the renderer at start up whether it is in dev mode. Communicating from main to the renderer can be done in a few ways, but since it's just a one time thing done at process start up, I followed [advice that I found on StackOverflow](https://stackoverflow.com/questions/38335004/how-to-pass-parameters-from-main-process-to-render-processes-in-electron/38401579#38401579). I know I could also use Electron's IPC mechanism, but that is more heavyweight than I needed, and I need something I can run prior to any other code running in `index.tsx`. The URL option fit that nicely without much complication.

I know there are a lot of files in this PR, but if you look at every change I made to a file named `global-this.model.ts`, you'll see how `globalThis.isNoisyDevModeEnabled` is set in each of the TS processes. For C# everything was handled in one file, `Program.cs`. 
___
*[`src/renderer/services/papi-frontend.service.ts` line 60 at r1](https://reviewable.io/reviews/paranext/paranext-core/886#-NwvVDjV74nIWmLsoLGB:-NwyqI1A6xKTCtie3uxW:b8sn39h) ([raw file](https://github.com/paranext/paranext-core/blob/0114b5324f68bd3d4c2fe817376cce4d46b69882/src/renderer/services/papi-frontend.service.ts#L60)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Err... aren't we just importing this wherever we need it rather than accessing it from PAPI since its essentially an external package?
</blockquote></details>

Yes that can work, too. When `papiUtil` was removed initially (at the time of creating the separate lib), one of the built-in extensions that use it wasn't changed, so one of the test webviews has been broken for a while. I just put the utils back as they were to fix it, but I can go change the extension to import the lib and use the functions instead.


<!-- Sent from Reviewable.io -->

2024-05-03 20:20 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/886#-:-Nx-6HZH3CnZpFXdjAtz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/main/main.ts` line 128 at r1](https://reviewable.io/reviews/paranext/paranext-core/886#-NwvRxOl2wQoYxB_gfu_:-Nx-5zJf4Tu2JLuLAMT0:b-96ix1k) ([raw file](https://github.com/paranext/paranext-core/blob/0114b5324f68bd3d4c2fe817376cce4d46b69882/src/main/main.ts#L128)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

`globalThis` does work in the renderer, but the indicator of being in dev mode can't be set the same way in the browser and Node.js, and `globalThis` values from `main` don't automatically flow into all of the processes it creates. In the main process and extension host, we can use `process.env` to inspect environment variables, but that is only available in Node.js. In the renderer, there is no built-in way to check environment variables. So the main process needs to tell the renderer at start up whether it is in dev mode. Communicating from main to the renderer can be done in a few ways, but since it's just a one time thing done at process start up, I followed [advice that I found on StackOverflow](https://stackoverflow.com/questions/38335004/how-to-pass-parameters-from-main-process-to-render-processes-in-electron/38401579#38401579). I know I could also use Electron's IPC mechanism, but that is more heavyweight than I needed, and I need something I can run prior to any other code running in `index.tsx`. The URL option fit that nicely without much complication.

I know there are a lot of files in this PR, but if you look at every change I made to a file named `global-this.model.ts`, you'll see how `globalThis.isNoisyDevModeEnabled` is set in each of the TS processes. For C# everything was handled in one file, `Program.cs`.
</blockquote></details>

Yes, I saw that later in the code review, thanks for the explanation, good choice.


<!-- Sent from Reviewable.io -->

2024-05-03 20:36 UTC, merged