Switch `Button` and `TextField` to shadcn
paranext/paranext-core pull request #891
Opened 2024-05-10 18:28 UTC by dewert99

Works towards #889.

* Removes `variant` and `isFullWidth` from `TextFieldProps`
* `div`s and `span`s containing a row of `TextField`s will now need to use `className="pr-flex pr-place-items-center"` to center the `TextField`s.

2024-05-12 20:32 UTC, irahopkinson requested changes
Thanks for your good work on this.

While this looks good to me, I think someone more familiar with Shadcn should review this also.

FYI it's our habit to post code review requests for PRs in the `<appropriate>-reviews` channel in Discord. In this case it would be https://discord.com/channels/1064938364597436416/1082712343303159819

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/891#-:-NxiU656AZqTcwC3qPm9:bd0o7jc)* status: all files reviewed, 2 unresolved discussions (waiting on @dewert99)

___
*[`lib/platform-bible-react/src/components/button.component.tsx` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/891#-NxiSUnf5zOmhUraEvr4:-NxiSUnf5zOmhUraEvr5:b-fmul8i) ([raw file](https://github.com/paranext/paranext-core/blob/ee3d27d033c20cdd328c9ee67b1662462c64622e/lib/platform-bible-react/src/components/button.component.tsx#L25)):*
> ```XML
>  * Button a user can click to do something
>  *
>  * Thanks to Shadcn for heavy inspiration and documentation https://ui.shadcn.com/docs
> ```

BTW you could point this directly at the button docs, i.e. https://ui.shadcn.com/docs/components/button



_Code quote:_
```XML
https://ui.shadcn.com/docs
```
___
*[`lib/platform-bible-react/src/components/text-field.component.tsx` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/891#-NxiS-zzEcrd1ADkth_r:-NxiS-zzEcrd1ADkth_s:b-hnvz3k) ([raw file](https://github.com/paranext/paranext-core/blob/ee3d27d033c20cdd328c9ee67b1662462c64622e/lib/platform-bible-react/src/components/text-field.component.tsx#L71)):*
> ```XML
>         htmlFor={id}
>         className={hasError ? 'pr-text-red-600' : ''}
>       >{`${label}${isRequired ? '*' : ''}`}</ShadLabel>
> ```

Will this work properly for an RTL label?


<!-- Sent from Reviewable.io -->

2024-05-13 17:30 UTC, dewert99 reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/891)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`lib/platform-bible-react/src/components/text-field.component.tsx` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/891#-NxiS-zzEcrd1ADkth_r:-Nxmz053AHBRVlyrfGZM:b-cbrppl) ([raw file](https://github.com/paranext/paranext-core/blob/ee3d27d033c20cdd328c9ee67b1662462c64622e/lib/platform-bible-react/src/components/text-field.component.tsx#L71)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Will this work properly for an RTL label?
</blockquote></details>

I think so, both this version and the MUI version put the `*` on the left side of the label when inside a `div`/`span` with `dir="rtl"`


<!-- Sent from Reviewable.io -->

2024-05-13 23:57 UTC, irahopkinson requested changes
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/891)* status: all files reviewed, 1 unresolved discussion (waiting on @dewert99)

___
*[`lib/platform-bible-react/src/components/text-field.component.tsx` line 71 at r3](https://reviewable.io/reviews/paranext/paranext-core/891#-NxoN16OD87106_jkTx6:-NxoN16OD87106_jkTx7:bm5lgf4) ([raw file](https://github.com/paranext/paranext-core/blob/71bcf2647e072fe698449fe341dc27a3172f7f4f/lib/platform-bible-react/src/components/text-field.component.tsx#L71)):*
> ```XML
>       <ShadLabel
>         htmlFor={id}
>         className={`${hasError ? 'pr-text-red-600' : ''}${label ? '' : 'pr-hidden'}`}
> ```

I think you'll have a problem here when `hasError` is truthy and `label` is falsy because there won't be a space between the class names.


<!-- Sent from Reviewable.io -->

2024-05-14 15:54 UTC, jolierabideau requested changes
Thanks for working on this David! Left a couple comments about classNames but besides that it looks good to me!

> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/891#-:-NxrnivZ7qPWWggMmzvM:b-4zou3e)* status: all files reviewed, 3 unresolved discussions (waiting on @dewert99 and @irahopkinson)

___
*[`lib/platform-bible-react/src/components/button.component.tsx` line 40 at r3](https://reviewable.io/reviews/paranext/paranext-core/891#-NxrnZjQDYD2BThz0DKY:-NxrnZjQDYD2BThz0DKZ:b-vhy3jb) ([raw file](https://github.com/paranext/paranext-core/blob/71bcf2647e072fe698449fe341dc27a3172f7f4f/lib/platform-bible-react/src/components/button.component.tsx#L40)):*
> ```XML
>       id={id}
>       disabled={isDisabled}
>       className={`papi-button ${className ?? ''}`}
> ```

Same comment about `classNames`
___
*[`lib/platform-bible-react/src/components/text-field.component.tsx` line 71 at r3](https://reviewable.io/reviews/paranext/paranext-core/891#-NxoN16OD87106_jkTx6:-Nxrec8Q82UM9Gr-7ti5:b-tzvv5q) ([raw file](https://github.com/paranext/paranext-core/blob/71bcf2647e072fe698449fe341dc27a3172f7f4f/lib/platform-bible-react/src/components/text-field.component.tsx#L71)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I think you'll have a problem here when `hasError` is truthy and `label` is falsy because there won't be a space between the class names.
</blockquote></details>

In situations like this where we want to conditionally render `classNames` we can use the `cn` utility function. There is an example of using this in the (book chapter control `BookMenuItem`)[https://github.com/paranext/paranext-core/blob/8cb161001c8f2302729512ba9b52d0a55b61adcf/lib/platform-bible-react/src/components/book-chapter-control/book-menu-item.component.tsx#L48]
___
*[`lib/platform-bible-react/src/components/text-field.component.tsx` line 78 at r3](https://reviewable.io/reviews/paranext/paranext-core/891#-Nxrjgs94I54PjqaANhm:-NxrjgsAC0XlyOcTjTTT:bq32nkl) ([raw file](https://github.com/paranext/paranext-core/blob/71bcf2647e072fe698449fe341dc27a3172f7f4f/lib/platform-bible-react/src/components/text-field.component.tsx#L78)):*
> ```XML
>         placeholder={placeholder}
>         required={isRequired}
>         className={`papi-textfield ${className ?? ''} ${hasError ? 'pr-border-red-600' : ''}`}
> ```

Same comment here about the `cn` function and I think we can remove "papi-checkbox" since this doesn't correlate to any css `className` now


<!-- Sent from Reviewable.io -->

2024-05-14 19:22 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once you get all of @jolierabideau comments (you missed using `cn` on the button component).

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/891#-:-NxsYQ6oEvOf98HmLqgk:b-o39rs6)* status: all files reviewed, 2 unresolved discussions (waiting on @dewert99)



<!-- Sent from Reviewable.io -->

2024-05-14 20:57 UTC, dewert99 commented
*[`lib/platform-bible-react/src/components/text-field.component.tsx` line 78 at r3](https://reviewable.io/reviews/paranext/paranext-core/891#-Nxrjgs94I54PjqaANhm:-Nxst16VChYD-0eYNCn7:b-83rcov) ([raw file](https://github.com/paranext/paranext-core/blob/71bcf2647e072fe698449fe341dc27a3172f7f4f/lib/platform-bible-react/src/components/text-field.component.tsx#L78)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Same comment here about the `cn` function and I think we can remove "papi-checkbox" since this doesn't correlate to any css `className` now
</blockquote></details>

Do you mean remove "papi-textfield"? I don't see "papi-checkbox"


<!-- Sent from Reviewable.io -->

2024-05-14 21:05 UTC, jolierabideau reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/891)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dewert99 and @irahopkinson)

___
*[`lib/platform-bible-react/src/components/text-field.component.tsx` line 78 at r3](https://reviewable.io/reviews/paranext/paranext-core/891#-Nxrjgs94I54PjqaANhm:-Nxsv1FE0h8hz2Ao8fvb:b-q8puhu) ([raw file](https://github.com/paranext/paranext-core/blob/71bcf2647e072fe698449fe341dc27a3172f7f4f/lib/platform-bible-react/src/components/text-field.component.tsx#L78)):*
<details><summary><i>Previously, dewert99 (David Ewert) wrote…</i></summary><blockquote>

Do you mean remove "papi-textfield"? I don't see "papi-checkbox"
</blockquote></details>

Yes! Sorry about that


<!-- Sent from Reviewable.io -->

2024-05-14 23:55 UTC, irahopkinson submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/891)* status: all files reviewed, 2 unresolved discussions (waiting on @dewert99)



<!-- Sent from Reviewable.io -->

2024-05-15 18:04 UTC, jolierabideau approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-15 22:22 UTC, irahopkinson approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-17 02:13 UTC, merged

2024-05-19 23:29 UTC, tjcouch-sil commented
Hey @dewert99! Thanks for the hard work on these. Unfortunately, we didn't catch beforehand that there's a step we forgot to tell you about and make sure you completed before closing this PR: any time you make changes in `platform-bible-react`, you need to run `npm run build` from that folder or `npm run build:platform-bible-react` from repo root. That lints and builds these files to make sure they run correctly in Platform.Bible. Running that brought up some errors that I made very quick fixes for in #899. Please check that out, and feel free to make adjustments to the changes as you see fit. The search bar especially needs work now.

It would probably be best to get `platform-bible-react` building again asap, so my changes in that PR are rough and are just to get things running again so others aren't blocked from doing their work. Might be best to make a follow-up PR with more sensible changes when the time is right.

Sorry for the mix-up! Thanks!

2024-05-20 16:36 UTC, dewert99 commented
Sorry, I am currently away for a few days, so if this is urgent, maybe someone else could look at this.

2024-05-23 23:22 UTC, dewert99 commented
I'm back from my trip. Sorry my PR caused problems, thanks for fixing this, I didn't know about running `npm run build`. Do you think it would be a good idea to add `npm run build` to the CI? 

I tried running `npm run build` and working through the errors, and I was mostly able to reproduce your PR. The one part I'm not sure about is how you knew to fix `src/renderer/components/settings-dialog/settings-tab.component.tsx`, as it doesn't seem to cause an error when running `npm run build`.

You mentioned specifically to look about the search bar needs work, where would I see the search bar.

2024-05-24 12:55 UTC, jolierabideau commented
Hey @dewert99 welcome back! Sorry that I forgot to mention `npm run build` when we talked. I'm not sure if we have talked about adding it to the CI. I know that it is meant to be an external library and at some point it will be moved out of the core. 

I would imagine he was able to fix the `settings-tab.component.tsx` because he either searched for uses of the `SearchBar` or he started up the app and it threw an error in the `settings-tab.component.tsx` because we were using a prop on the `SearchBar` that doesn't exist anymore. 

You can see the `SearchBar` used in the [`settings-tab.component.tsx`](https://github.com/paranext/paranext-core/blob/994a218e7cdd265ba4ab1d394b937c84c6f2f438/src/renderer/components/settings-dialog/settings-tab.component.tsx#L352) When you first started the app, there were probably a couple of floating tabs in the middle, the settings tab was one of them. If you closed those you will need to [clear local storage](https://github.com/paranext/paranext/wiki/Troubleshooting-Guide#clear-localstorage) to see them appear in the middle again. You can also add it to the preview page in `platform-bible-react`, it's easier to test changes there since you don't have to rebuild, whereas to see your changes in the core you have to run `npm run build` every time. I thing the main thing is that the `SearchBar` is a `TextField` with a `MUI Paper` element behind it, and now that we removed `isFullWidth` the `TextField` and `Paper` are different lengths.

Another recent change is that the web views are now hidden behind an environment variable. So if you aren't seeing any web views then you need to set `DEV_NOISY=true`, you can see the thread in `platform-changes` in Discord for help on that if you need it.