Fix docs related to `npm install` when running the first time
paranext/paranext-core pull request #892
Opened 2024-05-10 22:15 UTC by lyonsil

David noticed that `npm install` doesn't work from the lib directories if it hasn't been run first from `paranext-core`. After the first time it works fine.

2024-05-12 19:51 UTC, irahopkinson requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/892)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`lib/platform-bible-react/README.md` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/892#-NxiKpVrEOa2HCdBHMXE:-NxiKpVrEOa2HCdBHMXF:bvk32z7) ([raw file](https://github.com/paranext/paranext-core/blob/2f2fe1c18040dd025952d98f6181ccd2ba0061cb/lib/platform-bible-react/README.md#L20)):*
> ```Markdown
> #### Setting up
> 
> To set up the dev environment to build, you must run the following from `paranext-core`:
> ```

I would change both these to "from the root of the repository" to make it more specific. When you clone a repo it defaults to calling the folder the same as the repo name but the clone command allows you to name it something else and of course you can rename the folder in the OS anytime. I know we advise against renaming since that potentially breaks other things but that doesn't mean people don't do it.



_Code quote:_
```Markdown
from `paranext-core`
```


<!-- Sent from Reviewable.io -->

2024-05-12 20:07 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/892)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`lib/platform-bible-react/README.md` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/892#-NxiKpVrEOa2HCdBHMXE:-NxiPLaN1Pj1F0m3mP7z:bv2vr24) ([raw file](https://github.com/paranext/paranext-core/blob/2f2fe1c18040dd025952d98f6181ccd2ba0061cb/lib/platform-bible-react/README.md#L20)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I would change both these to "from the root of the repository" to make it more specific. When you clone a repo it defaults to calling the folder the same as the repo name but the clone command allows you to name it something else and of course you can rename the folder in the OS anytime. I know we advise against renaming since that potentially breaks other things but that doesn't mean people don't do it.
</blockquote></details>

I was just trying to follow the wording from other parts of the README file:
```
Or you can build from `paranext-core`:
```


<!-- Sent from Reviewable.io -->

2024-05-12 23:18 UTC, tjcouch-sil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks for the good investigation!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/892#-:-Nxj5KAp1fDXOKkZnlEa:bo9bb04)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`lib/platform-bible-react/README.md` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/892#-NxiKpVrEOa2HCdBHMXE:-Nxj597I6Mip1w1kepQ7:b-3l8zzz) ([raw file](https://github.com/paranext/paranext-core/blob/2f2fe1c18040dd025952d98f6181ccd2ba0061cb/lib/platform-bible-react/README.md#L20)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I was just trying to follow the wording from other parts of the README file:
```
Or you can build from `paranext-core`:
```
</blockquote></details>

Maybe would be worth changing them all at once sometime, but pushing that kind of stuff off is always a win 😂


<!-- Sent from Reviewable.io -->

2024-05-13 00:14 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/892#-:-NxjIIsb3C7MVBgxT2BY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-13 00:14 UTC, merged