Hook in web view context into web view menu command call
paranext/paranext-core pull request #901
Opened 2024-05-20 07:13 UTC by tjcouch-sil

- Added web view id to web view menu commands
- Moved projectId(s) to saved web view definition
  - Should `projectId` and `projectIds` be separate or together in just one field? Couldn't decide, so I just went with both separate for now
- Spread saved web view definition into web view props instead of just updatable props and run function to access
- Allowed getting saved web view definitions from web view service
- Exercised this stuff with hello world extension
  - Moved web view service `projectId` onto web view definition
  - Added web view menu items to the hello world project web view to delete the project or open a viewer for that project

Resolves #866

Note: this PR builds on #895. Please get that in before this one. Thanks!

![image](https://github.com/paranext/paranext-core/assets/104016682/aceb5b48-91c5-46c3-9b84-4c5f989e6ea3)

2024-05-20 16:16 UTC, lyonsil requested changes
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901)* status: all files reviewed, 5 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLaR6o-I6rTNDPW9Ck:-NyLaR6o-I6rTNDPW9Cl:b-3vys6m) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/localizedStrings.json#L9)):*
> ```JSON
>       "%mainMenu_createNewHelloWorldProject%": "Create New Hello World Project",
>       "%mainMenu_deleteHelloWorldProject%": "Delete Hello World Project",
>       "%helloWorld_webViewMenu_project%": "Project",
> ```

Are there any simple cases like "Project" and "View" where you'd want to use some of the fallback options to use other localized strings? Seems like `%mainMenu_project%` is what you might want to either use directly instead of `%helloWorld_webViewMenu_project%` or fall back if there isn't another localized provided.
___
*[`extensions/src/hello-world/contributions/menus.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLbPFE1F93zGyt1IdX:-NyLbPFE1F93zGyt1IdY:b-aqsc33) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/menus.json#L6)):*
> ```JSON
>     "groups": {
>       "helloWorld.helloWorldProjects": {
>         "order": 1.5,
> ```

I was thinking that it might be nice to either establish a convention where an extension uses the same decimal value in all orders to avoid collisions with other extensions OR we make a change to the menu service to automatically calculate a decimal value through some hash code to avoid collisions. I think the convention might be better to give us more determinism between extensions. What do you think? If you agree with the convention, maybe update the order to be something like `1.8765` here, `1000.8765` for `helloWorld.projectSubmenu`, `1.8765` for `mainMenu_openHelloWorldProject`, etc.
___
*[`extensions/src/hello-world/src/main.ts` line 217 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLm3B337UqygmJXtIG:-NyLm3B337UqygmJXtIH:b-1n2sxc) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/src/main.ts#L217)):*
> ```XML
>     try {
>       return await papi.storage.readUserData(context.executionToken, allProjectDataStorageKey);
>     } catch {
> ```

Is there a reason to `try`/`catch` here instead of just letting the error flow through if it happens?
___
*[`extensions/src/hello-world/src/main.ts` line 391 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLd9Dp-bJVpX9r_ZvH:-NyLd9Dp-bJVpX9r_ZvI:b-n1fha8) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/src/main.ts#L391)):*
> ```XML
>     await helloWorldPdpefPromise,
>     await helloWorldProjectWebViewProviderPromise,
>     await helloWorldProjectViewerProviderPromise,
> ```

I was looking at all these sequential `awaits` and thinking about whether this is the pattern we'd want others to use. Do you think we should use a different pattern that leverages `Promise.all` to [demonstrate better error handling](https://stackoverflow.com/questions/45285129/any-difference-between-await-promise-all-and-multiple-await/54291660#54291660)?
___
*[`src/renderer/services/web-view.service-host.ts` line 640 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLiL5w20EG4ORI340O:-NyLiL5w20EG4ORI340P:b-5p6u5o) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/src/renderer/services/web-view.service-host.ts#L640)):*
> ```XML
>   // If update properties aren't specified, keep the original values
>   WEBVIEW_DEFINITION_UPDATABLE_PROPERTY_KEYS.forEach((key) => {
>     if (key in updateInfo && updatedWebViewDefinition[key] !== updateInfo[key]) {
> ```

One of these values is `projectIds`, and a different array will always not be equal even if the array contents are the same. Do we need to check for that here?


<!-- Sent from Reviewable.io -->

2024-05-20 23:17 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901)* status: 21 of 28 files reviewed, 5 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLaR6o-I6rTNDPW9Ck:-NyMv28x8RgI_7_tVhnm:b7ra11s) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/localizedStrings.json#L9)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Are there any simple cases like "Project" and "View" where you'd want to use some of the fallback options to use other localized strings? Seems like `%mainMenu_project%` is what you might want to either use directly instead of `%helloWorld_webViewMenu_project%` or fall back if there isn't another localized provided.
</blockquote></details>

Ah probably a good call. I put a couple fallbacks in! I do wonder if it would be good to make a new issue for a couple things, though:

1. localized string browser webview - maybe we can add an endpoint to the localized string service for querying it or something. Search string, pagination, etc. I can't imagine it would take very long to do all this. Just thinking it is rather challenging to find other appropriate localized strings right now even for me as a core dev who knows where all the files are.
2. no-fallback mode - I realized I don't think there's any way to tell which strings are using fallbacks in the UI. I'm thinking a no-fallback mode (maybe just a setting) would be helpful for ui translators who want to go in and play around with the ui to figure out which strings are high priority to translate
___
*[`extensions/src/hello-world/contributions/menus.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLbPFE1F93zGyt1IdX:-NyN9C7fALQu5Hh5i26k:b-lvue7q) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/menus.json#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I was thinking that it might be nice to either establish a convention where an extension uses the same decimal value in all orders to avoid collisions with other extensions OR we make a change to the menu service to automatically calculate a decimal value through some hash code to avoid collisions. I think the convention might be better to give us more determinism between extensions. What do you think? If you agree with the convention, maybe update the order to be something like `1.8765` here, `1000.8765` for `helloWorld.projectSubmenu`, `1.8765` for `mainMenu_openHelloWorldProject`, etc.
</blockquote></details>

Maybe we could alphabetize by extension name hash and then let order be individual to each extension...? I dunno; I had a note down to talk to you about this too haha it is very annoying. Another option we could consider is to let the order be like it is now but do some kind of collision avoidance (like hash alphabetize) instead of rejecting menus when there are collisions. My biggest issue after having used it a bit is that the contribution is rejected if the order already exists, and it's nearly impossible to know if another extension has the same order as yours.
___
*[`extensions/src/hello-world/src/main.ts` line 217 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLm3B337UqygmJXtIG:-NyNAQmh15ce2lkk0fQn:bt0pfpg) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/src/main.ts#L217)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Is there a reason to `try`/`catch` here instead of just letting the error flow through if it happens?
</blockquote></details>

`readUserData` throws if the file doesn't exist. I suppose we could change that if we want! I guess `undefined` could take its place since an empty text file would probably return an empty string. I dunno what an empty binary file would return though🤔 maybe an empty Buffer?
___
*[`extensions/src/hello-world/src/main.ts` line 391 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLd9Dp-bJVpX9r_ZvH:-NyNDnVI7T7ExptKkhvN:bp2g3en) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/src/main.ts#L391)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I was looking at all these sequential `awaits` and thinking about whether this is the pattern we'd want others to use. Do you think we should use a different pattern that leverages `Promise.all` to [demonstrate better error handling](https://stackoverflow.com/questions/45285129/any-difference-between-await-promise-all-and-multiple-await/54291660#54291660)?
</blockquote></details>

I think it would probably be worth taking some time to consider various options and going with something that will serve us well longer-term. This is a mess.

One thing I have considered is having people add to the registrations a tuple `[registrationPromise: Promise<Unsubscriber>, name: string]`. Then we could do nice `Promise.all` and make everything all nice and report errors in a way that is understandable. Then we could also use that name when running the unsubscribers when deactivating the extension instead of just telling them "hey the unsubscriber at index 2 (which by the way doesn't actually match your index 2 because we add `deactivate` as the 0th index and maybe some other stuff before your registrations) is throwing". But I'd say there are a number of options to consider, and I don't know that there is an obvious best solution right offhand.

Maybe we can file an issue and consider further when we can?
___
*[`src/renderer/services/web-view.service-host.ts` line 640 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLiL5w20EG4ORI340O:-NyNEhta1XItVH7XOIfO:bi6jrgg) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/src/renderer/services/web-view.service-host.ts#L640)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

One of these values is `projectIds`, and a different array will always not be equal even if the array contents are the same. Do we need to check for that here?
</blockquote></details>

I decided to go with the way React does it, which is reference equality `===`. I don't think it really matters much offhand. I'd say I'm more concerned that people would push to the array or something without actually updating the array than I am concerned that they would get an extra meaningless update, but I guess they'll probably notice it doesn't work if they just push. Hopefully, people will be used to immutable state because of React and will treat this right :grimacing:

Would also be interested to hear your opinion on if it makes sense to have two different fields `projectId?: string` and `projectIds?: string[]` or if we should just have one `projectIds?: string | string[]` or even just `projectIds?: string[]` in web view definitions. Part of me just wants one place to get the information about relevant project ids. But I do like being able to specify that you only deal with one project id at all. I dunno


<!-- Sent from Reviewable.io -->

2024-05-21 02:47 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901)* status: 21 of 28 files reviewed, 5 unresolved discussions (waiting on @lyonsil)

___
*[`src/renderer/services/web-view.service-host.ts` line 640 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLiL5w20EG4ORI340O:-NyO19cAEZqXWQq73EGd:bfo439h) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/src/renderer/services/web-view.service-host.ts#L640)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I decided to go with the way React does it, which is reference equality `===`. I don't think it really matters much offhand. I'd say I'm more concerned that people would push to the array or something without actually updating the array than I am concerned that they would get an extra meaningless update, but I guess they'll probably notice it doesn't work if they just push. Hopefully, people will be used to immutable state because of React and will treat this right :grimacing:

Would also be interested to hear your opinion on if it makes sense to have two different fields `projectId?: string` and `projectIds?: string[]` or if we should just have one `projectIds?: string | string[]` or even just `projectIds?: string[]` in web view definitions. Part of me just wants one place to get the information about relevant project ids. But I do like being able to specify that you only deal with one project id at all. I dunno
</blockquote></details>

While implementing these changes in the various extensions, I noticed a couple things:

- It's really nice not to have to determine if the field is a string or an array literally everywhere I use it
- It might be nice in some cases (like in the text collection) to have `projectIds` and then have one special `projectId`. In the case of the text collection, `projectIds` is all the projects open in verse view on the left and `projectId` is the specific project that's open in chapter view on the right. So menu commands for the text collection would work on the project open in chapter view. Pretty nice

Maybe it is worth having two fields :p


<!-- Sent from Reviewable.io -->

2024-05-21 15:10 UTC, lyonsil commented
*[`extensions/src/hello-world/src/main.ts` line 217 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLm3B337UqygmJXtIG:-NyQeR_i6fAEGVZBZXNc:bvir27z) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/src/main.ts#L217)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

`readUserData` throws if the file doesn't exist. I suppose we could change that if we want! I guess `undefined` could take its place since an empty text file would probably return an empty string. I dunno what an empty binary file would return though🤔 maybe an empty Buffer?
</blockquote></details>

It looks like this all bubbles up from `fs.promises.readFile`. It seems like we would want to have clearer ways to determine kinds of failures. "File not found" vs other exceptions (e.g., "device I/O error", "invalid execution token", etc.). Maybe this is just part of whatever we do with enhancing the storage API.


<!-- Sent from Reviewable.io -->

2024-05-21 15:29 UTC, lyonsil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> All my comments are resolved well enough. I answered one of your questions and am OK whichever approach you'd prefer to take.

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901#-:-NyQlDFWAjPt00pKIGRG:b-kg33zh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLaR6o-I6rTNDPW9Ck:-NyQcuh49PCFdTtTUh4N:b-j8ruc1) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/localizedStrings.json#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ah probably a good call. I put a couple fallbacks in! I do wonder if it would be good to make a new issue for a couple things, though:

1. localized string browser webview - maybe we can add an endpoint to the localized string service for querying it or something. Search string, pagination, etc. I can't imagine it would take very long to do all this. Just thinking it is rather challenging to find other appropriate localized strings right now even for me as a core dev who knows where all the files are.
2. no-fallback mode - I realized I don't think there's any way to tell which strings are using fallbacks in the UI. I'm thinking a no-fallback mode (maybe just a setting) would be helpful for ui translators who want to go in and play around with the ui to figure out which strings are high priority to translate
</blockquote></details>

Good ideas - those probably would be helpful.
___
*[`extensions/src/hello-world/contributions/menus.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLbPFE1F93zGyt1IdX:-NyQdFvp6cEn3Zt5z0tM:b-taqr63) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/menus.json#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Maybe we could alphabetize by extension name hash and then let order be individual to each extension...? I dunno; I had a note down to talk to you about this too haha it is very annoying. Another option we could consider is to let the order be like it is now but do some kind of collision avoidance (like hash alphabetize) instead of rejecting menus when there are collisions. My biggest issue after having used it a bit is that the contribution is rejected if the order already exists, and it's nearly impossible to know if another extension has the same order as yours.
</blockquote></details>

My main hesitation with using a hash to settle ordering is that you can't deterministically set order how you'd like it to be. There will always be some seeming randomness to ordering.

Resolving this for now, but I do think we'll need to do something.
___
*[`extensions/src/hello-world/src/main.ts` line 217 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLm3B337UqygmJXtIG:-NyQh2goAOkVw8i6BqSd:b-qwupfb) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/src/main.ts#L217)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It looks like this all bubbles up from `fs.promises.readFile`. It seems like we would want to have clearer ways to determine kinds of failures. "File not found" vs other exceptions (e.g., "device I/O error", "invalid execution token", etc.). Maybe this is just part of whatever we do with enhancing the storage API.
</blockquote></details>

Added comment to https://github.com/paranext/paranext-core/issues/898
___
*[`extensions/src/hello-world/src/main.ts` line 391 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLd9Dp-bJVpX9r_ZvH:-NyQi5iK4quOzlkMfffZ:b-3j67ca) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/src/main.ts#L391)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it would probably be worth taking some time to consider various options and going with something that will serve us well longer-term. This is a mess.

One thing I have considered is having people add to the registrations a tuple `[registrationPromise: Promise<Unsubscriber>, name: string]`. Then we could do nice `Promise.all` and make everything all nice and report errors in a way that is understandable. Then we could also use that name when running the unsubscribers when deactivating the extension instead of just telling them "hey the unsubscriber at index 2 (which by the way doesn't actually match your index 2 because we add `deactivate` as the 0th index and maybe some other stuff before your registrations) is throwing". But I'd say there are a number of options to consider, and I don't know that there is an obvious best solution right offhand.

Maybe we can file an issue and consider further when we can?
</blockquote></details>

https://github.com/paranext/paranext-core/issues/905
___
*[`src/renderer/services/web-view.service-host.ts` line 640 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLiL5w20EG4ORI340O:-NyQj6Kb8wTJEKufWD11:bym1aac) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/src/renderer/services/web-view.service-host.ts#L640)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

While implementing these changes in the various extensions, I noticed a couple things:

- It's really nice not to have to determine if the field is a string or an array literally everywhere I use it
- It might be nice in some cases (like in the text collection) to have `projectIds` and then have one special `projectId`. In the case of the text collection, `projectIds` is all the projects open in verse view on the left and `projectId` is the specific project that's open in chapter view on the right. So menu commands for the text collection would work on the project open in chapter view. Pretty nice

Maybe it is worth having two fields :p
</blockquote></details>

Yeah it's a little weird to have 2 fields. I think it would be a little cleaner to just have the array. If you want to make one of values in the array special, just specify it's the first item in the array. No need to make two different variables. But it's not a huge deal from my point of view. It just leaves things a little ambiguous (e.g., if I only have 1 project ID, should I also create an array with 1 item?, what does it mean as a general statement if I set both variables?, does it ever make sense to have the single project ID set to a value that isn't included in the array of project ID values?).


<!-- Sent from Reviewable.io -->

2024-05-23 01:53 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLaR6o-I6rTNDPW9Ck:-NyY5ZC32qwQf16A1IeY:b-qe5tac) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/localizedStrings.json#L9)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Good ideas - those probably would be helpful.
</blockquote></details>

#909 
#910

Think these would have any priority to speak of? Or forget about them as they fade into obscurity in the depths of the IDeaths Bucket?
___
*[`extensions/src/hello-world/contributions/menus.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLbPFE1F93zGyt1IdX:-NyY8P-D72yXJDzjt-Yw:b-vkcpfm) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/menus.json#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

My main hesitation with using a hash to settle ordering is that you can't deterministically set order how you'd like it to be. There will always be some seeming randomness to ordering.

Resolving this for now, but I do think we'll need to do something.
</blockquote></details>

#911 - uh oh! Look at that issue number! I guess it's time to call the police!
___
*[`extensions/src/hello-world/src/main.ts` line 391 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLd9Dp-bJVpX9r_ZvH:-NyY8aYaBfmH4if_QCUr:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/src/main.ts#L391)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

https://github.com/paranext/paranext-core/issues/905
</blockquote></details>

Thanks!
___
*[`src/renderer/services/web-view.service-host.ts` line 640 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLiL5w20EG4ORI340O:-NyY8i5h6O_KE1suSt_T:brqnp7s) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/src/renderer/services/web-view.service-host.ts#L640)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Yeah it's a little weird to have 2 fields. I think it would be a little cleaner to just have the array. If you want to make one of values in the array special, just specify it's the first item in the array. No need to make two different variables. But it's not a huge deal from my point of view. It just leaves things a little ambiguous (e.g., if I only have 1 project ID, should I also create an array with 1 item?, what does it mean as a general statement if I set both variables?, does it ever make sense to have the single project ID set to a value that isn't included in the array of project ID values?).
</blockquote></details>

We discussed and decided to go with just `projectIds`. Having both doesn't have clear inherent meaning.


<!-- Sent from Reviewable.io -->

2024-05-23 03:16 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/renderer/services/web-view.service-host.ts` line 640 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLiL5w20EG4ORI340O:-NyYOeEUBzWk1liovmMe:bdnjno4) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/src/renderer/services/web-view.service-host.ts#L640)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We discussed and decided to go with just `projectIds`. Having both doesn't have clear inherent meaning.
</blockquote></details>

Sadly, I encountered enough annoyances and weird things while implementing that I'm starting to be convinced it may be best to keep both fields again... Would you mind taking a look [at my writeup](https://www.typescriptlang.org/play/?#code/PQKhFgCgAIWgZAlgZwC7QPYDNoAcBOGAVgKYDG6iAJstPiQDYkBuAhgHbqobSoAWKaAHcSAI2jNEJIQDpoASRz9BI8ZOnQyHTOwYBPaH1bMSO0-SZtOUWHkKkK0agBon6ZHwwBXBlWijTflMsRHw0aA4-DF0DEk58A0R2Xj5TVnx8Vj0ZGwgYOAA5DFQSAC4FHGQMAFsSaNN2EhIaCOhkJIBzJjticko-VmQqskRWEr8hRH4UlTEJKSFXIINJhgZMLBL2XIiyMhIhlODQ8IJex2onZOVadMzYk2TEJVT6CLfqn1REXG6zh36tCSR3e9xy+Qq0D03mEHC4PCSVEQWhKbVw5GeyNYawM-DGUO8+GEc3UQmEGHwAGtaJNpp8GN9fqZ-n0nC1RF5UDsqBgDtB2MVDIgOnwGMK+OhWGiMSEyD0AWyIrR6rweF5kGkgS9ZmoFtB1c1oER1eh6s4dsh0SMsAYAAZedhUEghRpUW3QLAUkEhMLoOKoBLg2DAKCoPTo6AAdTEADUFgAFex9eQtAC80AA2mh8J0APyuGSF7OdDMAXVLAG4oMBgNAACoCWhYJoMW5CSlCdJ+AJaA0KD0t6BiymmeQAcmqvASnVVmhqoiSplExT48uTfgAFEE7IhqukDCyLn5PUSpap5tIAJTV2uRNcUFO0Df0xl-JNH5U4EgARy82Kc1S4BSqAcPsl6qh0JBBESSTcGYcjyOgzaMLQw6jhOHoUiM7AdG4dBjK8KQcDe0A8jOQhGEhLa0OwYxeJkDAITM7CUsS-JNH424+uEiIkAAHrOAQRKI3RwUJDpOi6hpVMSurSLQWjJJaMpYjiJGIliqLLKR0RjugnacJg6KZN80S0HBPLMR0NJTKuKrYEcoT3qgj7+OQrB9ni6A8gc7B6dAe4jm0cQaphRJBNU4I1tAADy0GTBqrhVLUyg4UOiBBfgDrsDOABEMXoskABKByEvs0BxtIJD4LlHqEJO24lHx6BkBgax9Ig0Rzj4USFSCh6UMkZBGLgJREqSJFesa4TpAuAbpIg+hGXEZgbCCJhhKYpLOcgUW1gA4hgM6sKkrATLZMzmeGJCuPImESW0NTmCQ2JLSIoScQIOG0HdRicTwlnAhSTrhTwgWmFM5JUksqTJHd-DeCKpqciRFH4pDQjeL4Q4YBgrFobOlk3FcmDQXgDCsPsyBLLj4IkQAQu5fYOdurDtp2+BUI0hxOtUZnzeMbkMBgiz9qwk4BB0SQ5WlcGY461VODgIhtJ4PXQCOJC4P4K7OSmESOnrNAkXeZ1+Mlpj8fNVwnnuplPNcqROa11S1Jw5k8PxvysMCnhkirsFxH46IYEys6eak1SlDeJEALRG+U56krQHhY34EeCHBGkooErwQ8qjR4Ok3xkD46TOZdskXmSggELuC1vRSlLkbZe3QO3Hed53DYYKFFE8AZ8L6qFxMhIwfhA2TrWcFbqEZaYbteHOruRCnavY32kMnstJmdewBetO0OFMCRXdn+3A1sghlC0JBjQMUt9Au27Tp+AKQ99raA2PhmAAMpbuiSGgF6E9tRAhooKEI7UJ7JB7B5EeedT7ny7oIAU0AOh-kyDPXO+IuInHQJfS4wIv7vhcjQQB5lUgBV7pQQCwE4SYFPLgM4dcxjMlIYqOCBokHII7s8A2BgWaR3eJbR4ERmGEFYaifEr027x2-jQROJIFhrzTsPXOmcESOk0rnaqaQPhfB+G+c4gJK5Jz1CoJuLdpheUMMYEgPDeHtx-H+dYu4gL4BAuwfYcge5908LCQyXCEGCDHtjSehFp5NVQHPIKi9l57kdKo9Wm8kIUkcU40O1Uxh7wPi+Ix7CTFsl2pCUeUhwkQKQotJgMCYYkAMHuAwn8MwKIAUrUiBxQiGjgdwyA0UnGd23OYjQghs45NlpRaAJCTEpgoa0QhE99JNxsvwNuRQSjlAbAcQImMPTlJaOkBogp+JkAYOqRAJg1oqg4CuaqcgYqF2GWSRpUNWK0lXPksOCzbiG2xDJF5g9VQkWUtaQRhchG90KQqagtxKHsPrgkVaXUKLIjssZHJZlVZqIwHseivi85OAgexQ0cEQr0RwegaZAJHy2hIj5Spc5OA+2SFS9cto5AAAkRYsGqjTCIzAjp+Bdr8TSM5twGk-EcUKLDqrfAOK4SGgg77ZJxHQcgNQX6GnfkCvptZp7tBBlMhR7pBgGwiFQJE9t-z+kRcQhRyBAE4FZQ+chOk+Taqicyo1pDZl7RIgAER4NCJeqVWLE1SAwXAHtNAUxzDaQwIsDYTFhuHBB2zeC7LCS0ZAXhhpEUoDffkPBhY4UVvQKgEkGGm3Zl2XM0AACCmxqokSMJINK3s9CGnSN4Q27ypXHHHk+DUS5GAi0vLdCIk4sA+3wEtaebb9ifXxK2sVuyNS4HSGwvZg7CVXCdIaA0WAfB00gCRO63F0Dv2RIad6nNuY0hTV4XAVBxm4QjcLKGvgxw0mURoM4kgQbfvQVBaMohKpkiPd4+2wgU0Bj0GKngkEuS6pBDmJGFdLhYHqtAEgtlFZDN-WSUO9taAbqGIaYEWGaggmfneL0BG5JkkkkkKYe8gP2tDNdKMsYFj+udCx6D6YADeRtkC5nKKB8DiYZktAAL5VhQ4mKCQd+0iKLpkFK1VkBQH1e4exVBJMLAkzx6QfGXSsa6sJ2TOn+bAdQIZ6QBUSPQGEwnaAY5WCiDIGOaA8moAkQAJowlbYEAGPApRzTWlbTIxIPr3tnEhmjFIn4EI4dQOQ6yrjcCYJkESDjIC6aNi5uzDmhBOdyTIBR0Bcx1uQPp0rlWfU0FzDIP+lYGaciOMkJ+NQgJH1wng2i6wnkdPM9BuC9BUD0SeLQegr0Vi4c5jZ-e+kTNCDMwJvedYMAlSm-gdgxmwO8f4zlQT0AhM2GgIWGQdWTAGbW+aGAonyhVbrS0prpZoDlAkid5oUBrMobuhgg4tBg3dWxtiMatFvgmDnXN1EzqyEOtnLgTrwJoL5cK-a4rGYkOlfK2ZRrMnqu1fq2ton1Lmutf-u1lDDZ0a3H8JDAIqAxquA5AWoDaBqka0RFKNmHYuxyHjGcuFyQwchbNXcLIa0mA4WmAARmEBdaa6AftSRgW4EidZyB8ByloVV2qhCEDSneDaB5e7tDy7OEahV2do9QEB1XsXOYZcFFKM4eXJz8Marsw5wUN0mRHb2UKYPFIkTJW8RHNLd3O9tMWHCZZoAAB99QKw14AlbIC1p9at0tFdaV7Tp8XG6JUbgmz4Jw-EPQy3wiqHAxt07W2dtQWmwAJkOw3k7FnkjCcu9d27zRSuPYvk17TkAAf+ZQ0UMkTBHcKTMtQfDVCl9SjuuLHofWZwOVynzHidDPFwlql6XKdc9wJFqgs7XjYq7bSMJQ+gULWQwqi7+f87j6HeJIPi0ZsL2mNStjnHagoD3jsQfyaB2kmj6g5yLU0BGjGmrjkAAFk4gl5aMkl0ogp8o+oSoqh6JypwNqpapU51Yjcm4SIlMthPpf8Olsxc09sxUqEWED4GNq5l4gJGhrACtbMRN7UlEjtpBpNKdaBZNiteCx9ygMx1cS9XAPMvMxxZDJIFD3MRREAxxPtRDTVStG8e8FMp9oogsl5Jc4JUd0AatMxPsCUelQo6xroABlMgHMUaYKPkevBMMfAKGXcSYvV0JNWggMeg+iGcaQ10EifgQgIQH5HDDICkcEQrDMRpAIIQ9cAsQsZjU7EgZIl1ZAT7dMNwwQjw8wssPQ7glbCINYLIpHYrRIzIprarTMGoyolMVImQdIqYWomTHIr7UbATDo4QhTaKGfNiRSPZIbJaPsV6Jog5OFdKcIByb5MKMxQjKfDrS9RNH3SZEbQeaNcGVaBZahN4D-Q-IJIwR2UwW5MIaADcDUJgRwFUOCbadHKhYaVgUaRWUkcdEiaMOxS5OCPmX4yZe4ngLiE3VAVwFFPNQQEyQiAXDmKgfQ2sOwp6FUG4voWgMcVQscWvVLTqHMMMKY4rDEgQMcEowrRoIQKY5ASMWyRMXEqYAwdMDMa7SYsfWnbEncCkekqY+QBWASdMckyk6k-gWkzksMGQXiPiGKLADcOuUUvQKYy8Eo-hGUnMOU7k3k6AAAPmgF-mvCewFLHyFL4BFLxOyAdA8GeFQA3GuwNM6KNJNPpJuxFX2BVLpPxKax5KdD4lcAV0vEVJIiGJVmMKoVeJYRzC3Wl0EU5kVj7W3FlNNIwwGC4CoTQGLjd39lMCfRfS0ioW0O73thNkNn+POOSD7UJHShMGQCAA) and letting me know what you think please? Thanks! I will say I think having `projectId` not in `projectIds` is my weakest and least intuitive case of all. Basically I just said "don't worry about it", but that probably isn't a great answer haha I guess we could constrain `projectId` to be one of `projectIds` if `projectIds` is defined, but I don't know that I really want to work that hard to make sure that is the case haha might not really be worth worrying about.

I kinda wonder if it would be worth changing the name `projectId` to `primaryProjectId`, but I dunno if it really matters. Might be a bit confusing either way. Maybe also renaming `projectIds` to `allProjectIds` and forcing `primaryProjectId` into `allProjectIds` if it isn't there would make it a bit more self-explanatory, but it's still a weird data model to have these two independent fields that have interconnected meaning. Maybe just sticking with the simpler case of not worrying about it is best...?


<!-- Sent from Reviewable.io -->

2024-05-23 14:07 UTC, lyonsil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLaR6o-I6rTNDPW9Ck:-Ny_djV-4dmBdOgWXe4J:bat5bu9) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/localizedStrings.json#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

#909 
#910

Think these would have any priority to speak of? Or forget about them as they fade into obscurity in the depths of the IDeaths Bucket?
</blockquote></details>

I added them to the `Internationalization` epic. I think that's probably the best way to track/prioritize them appropriately over time. Right now they are not high enough priority to do anything with IMO, but when we look back at what we can/might do for different areas it is good to recognize the things we discovered about an epic after creating all the original tickets for it.
___
*[`extensions/src/hello-world/contributions/menus.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLbPFE1F93zGyt1IdX:-Ny_eZWr5zGIemN1So9a:b-5uhv4p) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/menus.json#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

#911 - uh oh! Look at that issue number! I guess it's time to call the police!
</blockquote></details>

I added this to the `Menus` epic.
___
*[`src/renderer/services/web-view.service-host.ts` line 640 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLiL5w20EG4ORI340O:-Ny_fd7xESGR0Z7mlnqE:by8iotb) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/src/renderer/services/web-view.service-host.ts#L640)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Sadly, I encountered enough annoyances and weird things while implementing that I'm starting to be convinced it may be best to keep both fields again... Would you mind taking a look [at my writeup](https://www.typescriptlang.org/play/?#code/PQKhFgCgAIWgZAlgZwC7QPYDNoAcBOGAVgKYDG6iAJstPiQDYkBuAhgHbqobSoAWKaAHcSAI2jNEJIQDpoASRz9BI8ZOnQyHTOwYBPaH1bMSO0-SZtOUWHkKkK0agBon6ZHwwBXBlWijTflMsRHw0aA4-DF0DEk58A0R2Xj5TVnx8Vj0ZGwgYOAA5DFQSAC4FHGQMAFsSaNN2EhIaCOhkJIBzJjticko-VmQqskRWEr8hRH4UlTEJKSFXIINJhgZMLBL2XIiyMhIhlODQ8IJex2onZOVadMzYk2TEJVT6CLfqn1REXG6zh36tCSR3e9xy+Qq0D03mEHC4PCSVEQWhKbVw5GeyNYawM-DGUO8+GEc3UQmEGHwAGtaJNpp8GN9fqZ-n0nC1RF5UDsqBgDtB2MVDIgOnwGMK+OhWGiMSEyD0AWyIrR6rweF5kGkgS9ZmoFtB1c1oER1eh6s4dsh0SMsAYAAZedhUEghRpUW3QLAUkEhMLoOKoBLg2DAKCoPTo6AAdTEADUFgAFex9eQtAC80AA2mh8J0APyuGSF7OdDMAXVLAG4oMBgNAACoCWhYJoMW5CSlCdJ+AJaA0KD0t6BiymmeQAcmqvASnVVmhqoiSplExT48uTfgAFEE7IhqukDCyLn5PUSpap5tIAJTV2uRNcUFO0Df0xl-JNH5U4EgARy82Kc1S4BSqAcPsl6qh0JBBESSTcGYcjyOgzaMLQw6jhOHoUiM7AdG4dBjK8KQcDe0A8jOQhGEhLa0OwYxeJkDAITM7CUsS-JNH424+uEiIkAAHrOAQRKI3RwUJDpOi6hpVMSurSLQWjJJaMpYjiJGIliqLLKR0RjugnacJg6KZN80S0HBPLMR0NJTKuKrYEcoT3qgj7+OQrB9ni6A8gc7B6dAe4jm0cQaphRJBNU4I1tAADy0GTBqrhVLUyg4UOiBBfgDrsDOABEMXoskABKByEvs0BxtIJD4LlHqEJO24lHx6BkBgax9Ig0Rzj4USFSCh6UMkZBGLgJREqSJFesa4TpAuAbpIg+hGXEZgbCCJhhKYpLOcgUW1gA4hgM6sKkrATLZMzmeGJCuPImESW0NTmCQ2JLSIoScQIOG0HdRicTwlnAhSTrhTwgWmFM5JUksqTJHd-DeCKpqciRFH4pDQjeL4Q4YBgrFobOlk3FcmDQXgDCsPsyBLLj4IkQAQu5fYOdurDtp2+BUI0hxOtUZnzeMbkMBgiz9qwk4BB0SQ5WlcGY461VODgIhtJ4PXQCOJC4P4K7OSmESOnrNAkXeZ1+Mlpj8fNVwnnuplPNcqROa11S1Jw5k8PxvysMCnhkirsFxH46IYEys6eak1SlDeJEALRG+U56krQHhY34EeCHBGkooErwQ8qjR4Ok3xkD46TOZdskXmSggELuC1vRSlLkbZe3QO3Hed53DYYKFFE8AZ8L6qFxMhIwfhA2TrWcFbqEZaYbteHOruRCnavY32kMnstJmdewBetO0OFMCRXdn+3A1sghlC0JBjQMUt9Au27Tp+AKQ99raA2PhmAAMpbuiSGgF6E9tRAhooKEI7UJ7JB7B5EeedT7ny7oIAU0AOh-kyDPXO+IuInHQJfS4wIv7vhcjQQB5lUgBV7pQQCwE4SYFPLgM4dcxjMlIYqOCBokHII7s8A2BgWaR3eJbR4ERmGEFYaifEr027x2-jQROJIFhrzTsPXOmcESOk0rnaqaQPhfB+G+c4gJK5Jz1CoJuLdpheUMMYEgPDeHtx-H+dYu4gL4BAuwfYcge5908LCQyXCEGCDHtjSehFp5NVQHPIKi9l57kdKo9Wm8kIUkcU40O1Uxh7wPi+Ix7CTFsl2pCUeUhwkQKQotJgMCYYkAMHuAwn8MwKIAUrUiBxQiGjgdwyA0UnGd23OYjQghs45NlpRaAJCTEpgoa0QhE99JNxsvwNuRQSjlAbAcQImMPTlJaOkBogp+JkAYOqRAJg1oqg4CuaqcgYqF2GWSRpUNWK0lXPksOCzbiG2xDJF5g9VQkWUtaQRhchG90KQqagtxKHsPrgkVaXUKLIjssZHJZlVZqIwHseivi85OAgexQ0cEQr0RwegaZAJHy2hIj5Spc5OA+2SFS9cto5AAAkRYsGqjTCIzAjp+Bdr8TSM5twGk-EcUKLDqrfAOK4SGgg77ZJxHQcgNQX6GnfkCvptZp7tBBlMhR7pBgGwiFQJE9t-z+kRcQhRyBAE4FZQ+chOk+Taqicyo1pDZl7RIgAER4NCJeqVWLE1SAwXAHtNAUxzDaQwIsDYTFhuHBB2zeC7LCS0ZAXhhpEUoDffkPBhY4UVvQKgEkGGm3Zl2XM0AACCmxqokSMJINK3s9CGnSN4Q27ypXHHHk+DUS5GAi0vLdCIk4sA+3wEtaebb9ifXxK2sVuyNS4HSGwvZg7CVXCdIaA0WAfB00gCRO63F0Dv2RIad6nNuY0hTV4XAVBxm4QjcLKGvgxw0mURoM4kgQbfvQVBaMohKpkiPd4+2wgU0Bj0GKngkEuS6pBDmJGFdLhYHqtAEgtlFZDN-WSUO9taAbqGIaYEWGaggmfneL0BG5JkkkkkKYe8gP2tDNdKMsYFj+udCx6D6YADeRtkC5nKKB8DiYZktAAL5VhQ4mKCQd+0iKLpkFK1VkBQH1e4exVBJMLAkzx6QfGXSsa6sJ2TOn+bAdQIZ6QBUSPQGEwnaAY5WCiDIGOaA8moAkQAJowlbYEAGPApRzTWlbTIxIPr3tnEhmjFIn4EI4dQOQ6yrjcCYJkESDjIC6aNi5uzDmhBOdyTIBR0Bcx1uQPp0rlWfU0FzDIP+lYGaciOMkJ+NQgJH1wng2i6wnkdPM9BuC9BUD0SeLQegr0Vi4c5jZ-e+kTNCDMwJvedYMAlSm-gdgxmwO8f4zlQT0AhM2GgIWGQdWTAGbW+aGAonyhVbrS0prpZoDlAkid5oUBrMobuhgg4tBg3dWxtiMatFvgmDnXN1EzqyEOtnLgTrwJoL5cK-a4rGYkOlfK2ZRrMnqu1fq2ton1Lmutf-u1lDDZ0a3H8JDAIqAxquA5AWoDaBqka0RFKNmHYuxyHjGcuFyQwchbNXcLIa0mA4WmAARmEBdaa6AftSRgW4EidZyB8ByloVV2qhCEDSneDaB5e7tDy7OEahV2do9QEB1XsXOYZcFFKM4eXJz8Marsw5wUN0mRHb2UKYPFIkTJW8RHNLd3O9tMWHCZZoAAB99QKw14AlbIC1p9at0tFdaV7Tp8XG6JUbgmz4Jw-EPQy3wiqHAxt07W2dtQWmwAJkOw3k7FnkjCcu9d27zRSuPYvk17TkAAf+ZQ0UMkTBHcKTMtQfDVCl9SjuuLHofWZwOVynzHidDPFwlql6XKdc9wJFqgs7XjYq7bSMJQ+gULWQwqi7+f87j6HeJIPi0ZsL2mNStjnHagoD3jsQfyaB2kmj6g5yLU0BGjGmrjkAAFk4gl5aMkl0ogp8o+oSoqh6JypwNqpapU51Yjcm4SIlMthPpf8Olsxc09sxUqEWED4GNq5l4gJGhrACtbMRN7UlEjtpBpNKdaBZNiteCx9ygMx1cS9XAPMvMxxZDJIFD3MRREAxxPtRDTVStG8e8FMp9oogsl5Jc4JUd0AatMxPsCUelQo6xroABlMgHMUaYKPkevBMMfAKGXcSYvV0JNWggMeg+iGcaQ10EifgQgIQH5HDDICkcEQrDMRpAIIQ9cAsQsZjU7EgZIl1ZAT7dMNwwQjw8wssPQ7glbCINYLIpHYrRIzIprarTMGoyolMVImQdIqYWomTHIr7UbATDo4QhTaKGfNiRSPZIbJaPsV6Jog5OFdKcIByb5MKMxQjKfDrS9RNH3SZEbQeaNcGVaBZahN4D-Q-IJIwR2UwW5MIaADcDUJgRwFUOCbadHKhYaVgUaRWUkcdEiaMOxS5OCPmX4yZe4ngLiE3VAVwFFPNQQEyQiAXDmKgfQ2sOwp6FUG4voWgMcVQscWvVLTqHMMMKY4rDEgQMcEowrRoIQKY5ASMWyRMXEqYAwdMDMa7SYsfWnbEncCkekqY+QBWASdMckyk6k-gWkzksMGQXiPiGKLADcOuUUvQKYy8Eo-hGUnMOU7k3k6AAAPmgF-mvCewFLHyFL4BFLxOyAdA8GeFQA3GuwNM6KNJNPpJuxFX2BVLpPxKax5KdD4lcAV0vEVJIiGJVmMKoVeJYRzC3Wl0EU5kVj7W3FlNNIwwGC4CoTQGLjd39lMCfRfS0ioW0O73thNkNn+POOSD7UJHShMGQCAA) and letting me know what you think please? Thanks! I will say I think having `projectId` not in `projectIds` is my weakest and least intuitive case of all. Basically I just said "don't worry about it", but that probably isn't a great answer haha I guess we could constrain `projectId` to be one of `projectIds` if `projectIds` is defined, but I don't know that I really want to work that hard to make sure that is the case haha might not really be worth worrying about.

I kinda wonder if it would be worth changing the name `projectId` to `primaryProjectId`, but I dunno if it really matters. Might be a bit confusing either way. Maybe also renaming `projectIds` to `allProjectIds` and forcing `primaryProjectId` into `allProjectIds` if it isn't there would make it a bit more self-explanatory, but it's still a weird data model to have these two independent fields that have interconnected meaning. Maybe just sticking with the simpler case of not worrying about it is best...?
</blockquote></details>

I read through your writeup and understand the concerns. I think my concern with `projectId` and `projectIds` might come down to the fact that variable names `projectId` and `projectIds` aren't quite as useless as calling them `string` and `strings`, but it isn't far from there. 

Perhaps if we change their names to something  [...]

2024-05-24 00:56 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901)* status: 23 of 28 files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`extensions/src/hello-world/contributions/localizedStrings.json` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLaR6o-I6rTNDPW9Ck:-Nyc5Ky64HuiqA7vKPP2:bil7lsi) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/localizedStrings.json#L9)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I added them to the `Internationalization` epic. I think that's probably the best way to track/prioritize them appropriately over time. Right now they are not high enough priority to do anything with IMO, but when we look back at what we can/might do for different areas it is good to recognize the things we discovered about an epic after creating all the original tickets for it.
</blockquote></details>

Sounds good. Thanks!
___
*[`extensions/src/hello-world/contributions/menus.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLbPFE1F93zGyt1IdX:-Nyc5Jqm3z7OdmEpOhZf:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/menus.json#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I added this to the `Menus` epic.
</blockquote></details>

Thanks!
___
*[`src/renderer/services/web-view.service-host.ts` line 640 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLiL5w20EG4ORI340O:-NybMyVG1d1pl4NFp5pl:b4okofv) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/src/renderer/services/web-view.service-host.ts#L640)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I read through your writeup and understand the concerns. I think my concern with `projectId` and `projectIds` might come down to the fact that variable names `projectId` and `projectIds` aren't quite as useless as calling them `string` and `strings`, but it isn't far from there. 

Perhaps if we change their names to something like `selectedProjectId` and `projectIdsToOpen` that might clarify things better? Honestly if we can't come up with unambiguous meanings that will be obvious to devs, cover all the cases we have in mind clearly, and don't leave other cases without good solutions, then it seems like we're thinking about this incorrectly. Like maybe each webview just defines its own custom context object type with whatever fields it wants that its own commands understand and expect. Then everyone doesn't have to figure out their own interpretations of things and isn't locked into just these one or two values. They just write commands that expect to work with the specific object type they define.

I guess where I am with things is that we just have `projectId` and leave it up to anything that needs multiple projects to sort it out some other way or we come up with something that is less ambiguous than having two variables with nearly identical names and purposes. It seems like the case of having a single project ID is common enough that we can just lock that in, but anything else starts to get custom based on the extension/webview.
</blockquote></details>

Oh haha I hadn't read your comment yet and didn't realize you had already suggested just having `projectId` :joy: anyway I went ahead and removed `projectIds`.


<!-- Sent from Reviewable.io -->

2024-05-24 14:14 UTC, lyonsil approved these changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-27 16:09 UTC, Sebastian-ubs reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/hello-world/contributions/menus.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLbPFE1F93zGyt1IdX:-NyunsyfDbwSATGN9dT3:b-b6ls89) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/menus.json#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Is there a knowledge / decision document somewhere about this menu structure? I had in mind we decided that an extension cannot plugin to any location in the menu, but maybe I am wrongly remembering things here or not getting the problem you are discussing...


<!-- Sent from Reviewable.io -->

2024-05-27 23:48 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/901)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/hello-world/contributions/menus.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/901#-NyLbPFE1F93zGyt1IdX:-NywQHI4DJFtugtjy-1w:b7ch776) ([raw file](https://github.com/paranext/paranext-core/blob/e939f80ece3815848ecf5fdfe27d6e4d63722182/extensions/src/hello-world/contributions/menus.json#L6)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

Is there a knowledge / decision document somewhere about this menu structure? I had in mind we decided that an extension cannot plugin to any location in the menu, but maybe I am wrongly remembering things here or not getting the problem you are discussing...
</blockquote></details>

We discussed the menu design extensively in meetings long ago as it sounds like you remember. During those meetings (unfortunately, I'm not sure if it's documented anywhere), the consensus shifted from no extensibility into other menus to allowing extensibility into other menus.

Here are some comments on the menu design doc that indicate the shift from before our meetings to after our meetings. Dunno if there's much more than that. Maybe on another document:
- https://docs.google.com/document/d/1N9BVj5w1b3H90Sjjc1lRN2zbalL-beDHmh4jxxExtiw/edit?disco=AAAA4GzM2-o
- https://docs.google.com/document/d/1N9BVj5w1b3H90Sjjc1lRN2zbalL-beDHmh4jxxExtiw/edit?disco=AAAA3cCR3IA (note the "cannot" in the original comment text vs the "can" in the document text)
- https://docs.google.com/document/d/1N9BVj5w1b3H90Sjjc1lRN2zbalL-beDHmh4jxxExtiw/edit?disco=AAAA2eUYKN8


<!-- Sent from Reviewable.io -->

2024-05-27 23:49 UTC, merged