Reworked projectType to projectInterfaces, reworked ParatextStandard file system format to match Paratext 9
paranext/paranext-core pull request #918
Opened 2024-05-31 08:36 UTC by tjcouch-sil

- [Breaking] Reworked `projectType` to `projectInterface`s. `projectInterface`s are sets of methods on PDPs that are implemented by PDPs that say they support the `projectInterface`s listed. Now, multiple PDPs can provide the same project id with one or more `projectInterface`s. You can still only get one `projectInterface` at a time.
  - There is still one `ProjectMetadata` per project id. The `ProjectMetadata` provided by the project lookup service for a project includes all the `projectInterface`s available for that project and also includes information regarding which PDP factory says it provides which `projectInterface`s.
- Added `pdpFactoryId` filter props in project settings schema and on the filter type since that is more like the original `projectType` that we used to have
- Reworked `ParatextStandard`'s file system format to match Paratext 9's file system format. Now, projects are the same as project folders in `My Paratext 9 Projects` folder, and they're located in `~/.platform.bible/projects/Paratext 9 Projects`. No more `meta.json`!! 🎉
  - I just chose a directory for extension data for now. Hopefully we will get clarity from the Paratext team regarding which directory to use soon
- Added "Toggle Include My Paratext 9 Projects" menu item that you can click and then restart to see the projects in "C:/My Paratext 9 Projects" in Platform.Bible!! It even has a tooltip to explain it (pictured below)! Please proceed with caution ;)
- Made `SettingsServiceClient` on C# side that interacts with the settings service host. I called it "Client" because it isn't the actual Settings Service data provider. However, `ProjectSettingsService.cs` doesn't say "Client". But it's not a data provider. I dunno; open to thoughts on the name.
- Made registering request handlers on the `PapiClient` work in unit tests. Woo... 😴

Would especially love an eye on the conversions I did between data types in C#. I used `object` in some places. Then there were other places that seemed to use NewtonSoft's JSON stuff and other places that used .NET's built-in JSON stuff. I found that rather annoying and cumbersome. I also couldn't figure out how to deserialize .NET's `JsonElement` into a generic object that could be cast to the appropriate type, so I had to just return a `JsonElement` in `SettingsServiceClient.Get`. Would be interested to know if there are better things to do here.

Also if anyone knows the Linux directory for My Paratext 9 Projects, I could definitely throw that in. I just don't know what it is.

![image](https://github.com/paranext/paranext-core/assets/104016682/ce971ab7-ee6a-4f71-8971-d5f36d8d1ff5)

2024-05-31 18:14 UTC, lyonsil requested changes
Lots there - Good stuff!  You even added a bunch of unit tests! Is this really TJ? :wink: 

I added more comments in C# than in the TS code. I added some ideas for how to handle `SettingsServiceClient.Get` in a (more) generic way.

I think we could rename the `ServiceClients` directory to just `Services` and put client and server implementation there, leaving `Projects` to just things are are more central to projects. Then any other services we integrate with have a natural home. It's not a huge deal if we leave it or make this change IMO. Refactoring is a normal thing that happens from time to time, and no directory structure is perfect.

I don't think there is a Linux directory for "My Paratext 9 Projects." Or if there is it's more like "My Paratext Lite Projects." I don't think PT9 works on Linux at all. PT Lite has been filling in that gap.

> Reviewed 70 of 70 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/918#-:-NzEnJ7U95uxAutEyENG:bxnawxy)* status: all files reviewed, 22 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzDzfy5B9OJ1Ipj-n8U:-NzDzfy5B9OJ1Ipj-n8V:b9nae0w) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/LocalParatextProjects.cs#L18)):*
> ```Smalltalk
>     protected const string PROJECT_SETTINGS_FILE = "Settings.xml";
> 
>     protected static readonly List<string> _paratextProjectInterfaces = [ProjectInterface.Paratext];
> ```

Per our discussion, I'm assuming that splitting this interface into individual data types will come later.
___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzECzv_3E4fai_5sNT4:-NzECzv_3E4fai_5sNT5:bjfga2o) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/LocalParatextProjects.cs#L64)):*
> ```Smalltalk
>             try
>             {
>                 if (projectDetails.Metadata.ProjectInterfaces.Contains(ProjectInterface.Paratext))
> ```

I don't think we need this `if` check anymore. We are assuming that all projects we see in the new folder structure are Paratext projects, so there is no need to check any interfaces. In the previous design it was possible for multiple project types to be mixed together under the same subdirectory.
___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 141 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEEMvaBSs4fmFs0Zmv:-NzEEMvaBSs4fmFs0Zmw:b-mngeie) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/LocalParatextProjects.cs#L141)):*
> ```Smalltalk
>     /// </summary>
>     /// <returns>Enumeration of (ProjectMetadata, project directory) tuples for all projects</returns>
>     private IEnumerable<ProjectDetails> LoadAllProjectDetails(bool shouldIncludePT9Projects)
> ```

I know you have `IsWindows` checks in other places, but I would feel a little more comfortable here if you forced this `bool` to be `false` within this method if we're not on Windows.
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 70 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEGcBx3gWriisz_51k:-NzEGcBx3gWriisz_51l:b-wonihc) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProvider.cs#L70)):*
> ```Smalltalk
>         if (OperatingSystem.IsWindows())
>         {
>             var shouldIncludePT9ProjectsElement = SettingsServiceClient.GetSetting(PapiClient, "platformScripture.includeMyParatext9Projects");
> ```

Please move the setting name to a common location.
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEOAm-3C9BIH7gBUY3:-NzEOAm-3C9BIH7gBUY4:b-s8dlj0) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProvider.cs#L71)):*
> ```Smalltalk
>         {
>             var shouldIncludePT9ProjectsElement = SettingsServiceClient.GetSetting(PapiClient, "platformScripture.includeMyParatext9Projects");
>             shouldIncludePT9Projects = shouldIncludePT9ProjectsElement!.Value.GetBoolean();
> ```

If you don't change `GetSetting` to be generic for some reason, please remove this `!`. We actually should care if it's null.
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 175 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEONCw9py6k06S-14I:-NzEONCw9py6k06S-14J:b-6k8v06) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProvider.cs#L175)):*
> ```Smalltalk
>         IProjectStreamManager extensionStreamManager = CreateStreamManager(projectDetails);
>         return extensionStreamManager.GetDataStream(
>             $"${LocalParatextProjects.EXTENSION_DATA_SUBDIRECTORY}/{scope.ExtensionName}/{scope.DataQualifier}",
> ```

I think you've got an extra `$` here.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEOVcq4s3x8QG_B29U:-NzEOVcq4s3x8QG_B29V:b-wonihc) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L29)):*
> ```Smalltalk
>         if (OperatingSystem.IsWindows())
>         {
>             var shouldIncludePT9ProjectsElement = SettingsServiceClient.GetSetting(PapiClient, "platformScripture.includeMyParatext9Projects");
> ```

Please move the setting name to a common location.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 30 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEOjHO1Cw1u2yHlrQK:-NzEOjHO1Cw1u2yHlrQL:b-4n9q8p) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L30)):*
> ```Smalltalk
>         {
>             var shouldIncludePT9ProjectsElement = SettingsServiceClient.GetSetting(PapiClient, "platformScripture.includeMyParatext9Projects");
>             shouldIncludePT9Projects = shouldIncludePT9ProjectsElement!.Value.GetBoolean();
> ```

If you don't make `GetSetting` generic then please remove the `!`.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEOqbT3a5ui3oetd62:-NzEOqbT3a5ui3oetd63:b-8g00gl) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L41)):*
> ```Smalltalk
>             .GetAllProjectDetails()
>             .Select(pd => pd.Metadata)
>             .Where(m => m.ProjectInterfaces.Contains(ProjectInterface.Paratext))
> ```

I think we can remove this `Where` call.
___
*[`c-sharp/Projects/ProjectDataProviderFactory.cs` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEP-qu--4y-v_YOX16:-NzEP-qu--4y-v_YOX17:b-xlwfol) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ProjectDataProviderFactory.cs#L26)):*
> ```Smalltalk
>     {
>         await StartFactory();
>         var name = $"platform.pdpFactory-{string.Join(',', _projectInterfaces)}";
> ```

This is probably a case where we probably want to take a different approach, like having the subclass provide some name that gets appended here.
___
*[`c-sharp/Projects/ProjectDataProviderFactory.cs` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEPPSVClg23AJGGref:-NzEPPSVClg23AJGGreg:bow204g) ([raw file](https://github.com/paranext/ [...]

2024-06-03 04:29 UTC, tjcouch-sil reviewed
Yeah, I died a little bit inside. I did the file system rework in like an hour or so. Then I was pretty frustrated by the end of Friday that I had spent almost the whole day working on unit tests for it (settings service, I'm looking at you >.>)... Hoping to get a breath of fresh air before long.

Refactored to `Services`! Wasn't sure if you meant to suggest moving the project settings stuff there, too, but I went ahead and did them too.

Ah yes, good point. I think it would probably make sense to use this PT Lite directory. I don't know if we need to do that right this minute, but seems reasonable.

Thanks a bunch for all the time you spent carefully reviewing my gigantic PR. It really helped!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/918#-:-NzQXhWX2TRoE-52iDQW:b5uius2)* status: 41 of 76 files reviewed, 20 unresolved discussions (waiting on @github-advanced-security[bot] and @lyonsil)

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzDzfy5B9OJ1Ipj-n8U:-NzQ-NI3-WMFAvI0icKE:b5hm082) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/LocalParatextProjects.cs#L18)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Per our discussion, I'm assuming that splitting this interface into individual data types will come later.
</blockquote></details>

Yes indeed :) seemed like it could be a small follow-up PR. Maybe I'll do it while I make changes to all the repos, though, so we don't have to do two rounds of changes in each repo. We'll see!
___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzECzv_3E4fai_5sNT4:-NzQ-tPs5owfL1zVDr5b:b-qd0qdm) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/LocalParatextProjects.cs#L64)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I don't think we need this `if` check anymore. We are assuming that all projects we see in the new folder structure are Paratext projects, so there is no need to check any interfaces. In the previous design it was possible for multiple project types to be mixed together under the same subdirectory.
</blockquote></details>

Good idea! Done
___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 141 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEEMvaBSs4fmFs0Zmv:-NzQ0X_n2A-7UM3FaTfU:b-ydonj4) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/LocalParatextProjects.cs#L141)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I know you have `IsWindows` checks in other places, but I would feel a little more comfortable here if you forced this `bool` to be `false` within this method if we're not on Windows.
</blockquote></details>

Done. Good idea!
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 70 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEGcBx3gWriisz_51k:-NzQ1kTmAjLiOMR2AgQy:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProvider.cs#L70)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Please move the setting name to a common location.
</blockquote></details>

Done
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEOAm-3C9BIH7gBUY3:-NzQNZJI5rQmNaDUG6tG:b-p67e7o) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProvider.cs#L71)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If you don't change `GetSetting` to be generic for some reason, please remove this `!`. We actually should care if it's null.
</blockquote></details>

I went ahead and removed it anyway. Looks like maybe the deserialize throws if the json passed in is `"null"`, but I guess might as well make sure...?
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 175 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEONCw9py6k06S-14I:-NzQ1uVl7QMRw0mxnbaS:bywww8f) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProvider.cs#L175)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I think you've got an extra `$` here.
</blockquote></details>

😬 oops
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEOVcq4s3x8QG_B29U:-NzQ1yGoC-pZKw1kdarn:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L29)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Please move the setting name to a common location.
</blockquote></details>

Done.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 30 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEOjHO1Cw1u2yHlrQK:-NzQNkSL9BxFBZkI6RBw:bbxgkzp) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L30)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If you don't make `GetSetting` generic then please remove the `!`.
</blockquote></details>

Same comment as above
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEOqbT3a5ui3oetd62:-NzQ261GC0LhRxgIVMUl:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L41)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I think we can remove this `Where` call.
</blockquote></details>

Done.
___
*[`c-sharp/Projects/ProjectDataProviderFactory.cs` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEP-qu--4y-v_YOX16:-NzQ3ICn-5NsHZxuiv9f:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ProjectDataProviderFactory.cs#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This is probably a case where we probably want to take a different approach, like having the subclass provide some name that gets appended here.
</blockquote></details>

Done.
___
*[`c-sharp/Projects/ProjectDataProviderFactory.cs` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEPPSVClg23AJGGref:-NzQ3ImO8ws0kfB5HWW7:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ProjectDataProviderFactory.cs#L51)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Change to use the subclass provided name here.
</blockquote></details>

Done.
___
*[`c-sharp/Projects/ProjectMetadata.cs` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzE44cKAj53sCkYd653:-NzQ3eu3AJQ1zPJKcCf-:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/c-sharp/Projects/ProjectMetadata.cs#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This description should change.
</blockquote></details>

Done.
___
*[`c-sharp/Projects/ProjectMetadata.cs` line 44 at r1](https://reviewable [...]

2024-06-03 14:07 UTC, Sebastian-ubs commented
Question: Will "My Paratext 9 Projects" folder be included with write permissions (so should I backup and secure the content in case anything goes wrong)? I know that at a point in time the prototype code we took to Kenya delete some content in an exported project (not reproducible afterwards, but it happened).

2024-06-03 15:49 UTC, lyonsil requested changes
Except for a few small things this look good. Thanks for slogging through it all, including the unit tests!

The `Services` refactoring that you did is what I had in mind. Sorry for not being clearer in my description, but you deciphered my thoughts correctly. :)

To @Sebastian-ubs 's question, yes, this would include write permissions if you enable the checkbox. Presumably what you saw in Kenya was a bug that we'd want to track down, but I think having this feature is reasonable at least to consider. Users could choose to use S/R to move edits between PT9 and PT10 Studio, but I assume editing in place is simpler if we get any bugs worked out.

> Reviewed 35 of 35 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/918#-:-NzTlvsY8y9nvpwlCG0i:b-fduawq)* status: all files reviewed, 5 unresolved discussions (waiting on @github-advanced-security[bot] and @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 71 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzTc2LA3qlKKMSYQt4O:-NzTc2LA3qlKKMSYQt4P:b2kr933) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/c-sharp/Projects/ParatextProjectDataProvider.cs#L71)):*
> ```Smalltalk
>         if (OperatingSystem.IsWindows())
>         {
>             var shouldIncludePT9ProjectsElement = SettingsService.GetSettingValue<bool>(PapiClient, Settings.INCLUDE_MY_PARATEXT_9_PROJECTS);
> ```

minor nit - The variable is still named with `Element` as it was a `JsonElement` object but is now a `bool?`.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzTcZSOEhI8IxIRereD:-NzTcZSOEhI8IxIRereE:b-c1xrd6) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L30)):*
> ```Smalltalk
>         if (OperatingSystem.IsWindows())
>         {
>             var shouldIncludePT9ProjectsElement = SettingsService.GetSettingValue<bool>(PapiClient, Settings.INCLUDE_MY_PARATEXT_9_PROJECTS);
> ```

same minor nit as above
___
*[`lib/platform-bible-utils/src/string-util.ts` line 131 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzTlIEv9-Xw3yKzQTxF:-NzTlIEv9-Xw3yKzQTxG:b-s3dc5x) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/lib/platform-bible-utils/src/string-util.ts#L131)):*
> ```XML
>  * @returns Formatted string
>  */
> export function formatReplacementString(str: string, replacers: { [key: string]: string }): string {
> ```

Changes here make sense to me except for the one line mentioned in a separate comment, and the unit tests looks good. Given the complexity I'd be more comfortable if @katherinejensen00 has a chance to give it a once over, too, just to make sure some nuance wasn't missed.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 138 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzTk45n6WT8SZ0bzh5d:-NzTk45n6WT8SZ0bzh5e:b6cqgq9) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/lib/platform-bible-utils/src/string-util.ts#L138)):*
> ```XML
>     switch (charAt(updatedStr, i)) {
>       case '{':
>         if (charAt(updatedStr, i) === '{') {
> ```

This seems like an unnecessary `if` statement since the immediately preceding `switch` and `case` statements already check this.
___
*[`lib/platform-bible-utils/src/util.ts` line 250 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#-NzEcsLk14qtpM-q9bRb:-NzTh0Z9Emrri3XrzPVD:b-wmsiu5) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/lib/platform-bible-utils/src/util.ts#L250)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Done - oops, meant to but forgot to add one
</blockquote></details>

Good description!


<!-- Sent from Reviewable.io -->

2024-06-03 18:03 UTC, katherinejensen00 requested changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/918)* status: all files reviewed, 7 unresolved discussions (waiting on @github-advanced-security[bot], @lyonsil, and @tjcouch-sil)

___
*[`lib/platform-bible-utils/src/string-util.ts` line 131 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzTlIEv9-Xw3yKzQTxF:-NzUFkK-5W4n5EPYL7iN:beqyqld) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/lib/platform-bible-utils/src/string-util.ts#L131)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Changes here make sense to me except for the one line mentioned in a separate comment, and the unit tests looks good. Given the complexity I'd be more comfortable if @katherinejensen00 has a chance to give it a once over, too, just to make sure some nuance wasn't missed.
</blockquote></details>

I think this code looks good and is definitely easier to read than the regex.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 139 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzUEb7TCLOSyGAEnAc3:-NzUEb7TCLOSyGAEnAc4:b-ldh525) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/lib/platform-bible-utils/src/string-util.ts#L139)):*
> ```XML
>       case '{':
>         if (charAt(updatedStr, i) === '{') {
>           if (charAt(updatedStr, i - 1) !== '\\') {
> ```

Could this lead to an index of -1 if the first character is '{' ? Would that be a problem in typescript like it is in C# or would it be okay (it might be, just not sure)?
___
*[`lib/platform-bible-utils/src/string-util.ts` line 172 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzUF_7_ES52PrgNa0s0:-NzUF_7_ES52PrgNa0s1:by3s822) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/lib/platform-bible-utils/src/string-util.ts#L172)):*
> ```XML
>         break;
>       case '}':
>         if (charAt(updatedStr, i - 1) !== '\\') {
> ```

Same index potential to be -1 question as above


<!-- Sent from Reviewable.io -->

2024-06-03 22:18 UTC, tjcouch-sil reviewed
Yep, this integration includes permissions to read/write. Would be wise to backup the project with S/R before opening in P.B. It would be really cool to be able to make this work well with no issues; really I kinda just threw it in for now because it was convenient and easy. Hopefully we can tune it up. If not, we can just take it out.

Sounds like an important bug to fix!

> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/918#-:-NzV5joH8l847hMrECp3:b27jfx4)* status: 69 of 76 files reviewed, 5 unresolved discussions (waiting on @katherinejensen00 and @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 71 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzTc2LA3qlKKMSYQt4O:-NzV7BWYAHcPZTRSKQEb:b-wtn4w4) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/c-sharp/Projects/ParatextProjectDataProvider.cs#L71)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

minor nit - The variable is still named with `Element` as it was a `JsonElement` object but is now a `bool?`.
</blockquote></details>

Fixed - good catch
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzTcZSOEhI8IxIRereD:-NzV7EweEqjFPV8o8P1X:b-wtn4w4) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L30)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

same minor nit as above
</blockquote></details>

Fixed - good catch
___
*[`lib/platform-bible-utils/dist/index.js` line 1494 at r1](https://reviewable.io/reviews/paranext/paranext-core/918#gh-1621975924:-NzV7J_YEDn5KQwu5Zxd:b-n6left) ([raw file](https://github.com/paranext/paranext-core/blob/a5f61333d62ab843ea9a26d74bbee2de22423e59/lib/platform-bible-utils/dist/index.js#L1494)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Reworked format string function in hopes that it will fix this problem.
</blockquote></details>

Seems this is not flagged in latest build. Dismissing.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 138 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzTk45n6WT8SZ0bzh5d:-NzV7rok8uT3zPJ_B3Ah:bmp43q7) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/lib/platform-bible-utils/src/string-util.ts#L138)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This seems like an unnecessary `if` statement since the immediately preceding `switch` and `case` statements already check this.
</blockquote></details>

Oops! I reformatted it from `if`s to a `switch` and then forgot to take this one out haha fixed. Thanks!
___
*[`lib/platform-bible-utils/src/string-util.ts` line 139 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzUEb7TCLOSyGAEnAc3:-NzV7VMA2FFDNdunPJ6u:b-oxk6vj) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/lib/platform-bible-utils/src/string-util.ts#L139)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Could this lead to an index of -1 if the first character is '{' ? Would that be a problem in typescript like it is in C# or would it be okay (it might be, just not sure)?
</blockquote></details>

`charAt` returns an empty string out of bounds, so it's ok :) there's a unit test for this case. Thanks for taking a look!
___
*[`lib/platform-bible-utils/src/string-util.ts` line 172 at r2](https://reviewable.io/reviews/paranext/paranext-core/918#-NzUF_7_ES52PrgNa0s0:-NzV7c29DqQOoKm1btMj:b-oxk6vj) ([raw file](https://github.com/paranext/paranext-core/blob/506a70b07d0500372373e074d5c41261dd2e3004/lib/platform-bible-utils/src/string-util.ts#L172)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Same index potential to be -1 question as above
</blockquote></details>

`charAt` returns an empty string out of bounds, so it's ok :) there's a unit test for this case. Thanks for taking a look!


<!-- Sent from Reviewable.io -->

2024-06-03 23:47 UTC, lyonsil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/918#-:-NzVV7GvBcMR3QhAvGfc:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @katherinejensen00)



<!-- Sent from Reviewable.io -->

2024-06-04 12:21 UTC, katherinejensen00 approved these changes
> Reviewed 41 of 70 files at r1, 28 of 35 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/918)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-04 16:41 UTC, Sebastian-ubs commented
Thanks. I added https://github.com/paranext/paranext-core/issues/922 and will try to investigate further

2024-06-04 21:06 UTC, merged