Reworked PDPs to enable layering PDPs, added platform.base, added Scripture extender layering PDP, replaced name from ProjectMetadata with project setting platform.name
paranext/paranext-core pull request #930
Opened 2024-06-07 07:00 UTC by tjcouch-sil

- **[Breaking]** Reduced `IProjectDataProvider` and made `IBaseProjectDataProvider` the same as what it used to be. Same with `IProjectDataProviderEngine`/`IBaseProjectDataProviderEngine` and `ProjectDataProviderEngine`/`BaseProjectDataProviderEngine` classes
  - Created new concept of "Base PDP" vs "Layering PDP".
    - **Base PDP** (IBaseProjectDataProvider) has to implement `platform.base` (settings and extension data) and can provide its own project ids representing projects whose data it is managing.
    - **Layering PDP** (`IProjectDataProvider`) doesn't have particular implementation requirements; it provides whatever additional `projectInterface`s it wants on other existing projects. It does not provide its own project ids or manage its own data but rather adds functionality to existing project ids, likely often via `ExtensionData` on Base PDPs.
- **[Breaking]** Added new `projectInterface`: `platform.base`, the minimal required `projectInterface` a PDP must implement for its PDPF to be allowed to provide its own project ids. Now, every PDPF that wants to provide its own projects must implement `IBaseProjectDataProvider` and include it in its supported data types
- **[Breaking]** added new first parameter of `registerProjectDataProviderFactory` as `pdpFactoryId` since they are now important to be able to use between extensions.
- **[Breaking]** completely removed `ParatextStandard` `projectInterface`. It was replaced by more granular `projectInterface`s:
  - platformScripture.USFM_BCV
  - platformScripture.USX_Chapter
  - platformScripture.USJ_Chapter
- Added new Layering PDP Factory `platformScripture.scriptureExtenderPdpf` that adds the `platformScripture.USJ_Chapter` `projectInterface` to PDPs that have the `platformScripture.USX_Chapter` `projectInterface`
- **[Breaking]** Moved many Scripture-related types from `usfm-data-provider` extension module to `platform-scripture` extension module to prepare for removing USFM data provider at some point soon
- **[Breaking]** Removed first parameter `projectInterface` from `useProjectSetting`
- **[Breaking]** Removed `name` from `ProjectMetadata` and replaced with new project setting `[platform.name](http://platform.name/)`.
  - Name is not necessary for organizing and categorizing projects. It was previously in `ProjectMetadata` because it was a convenient shortcut to get to a characteristic of the project that would help humans to identify it. However, each PDPF could theoretically provide a different `name` for the same project, and there is essentially no way to tell which one is correct. Now, there is one unambiguous avenue through which to get the project's name.
- Added a network object version of the project lookup service so processes other than TypeScript don't have to reimplement all the crazy logic. The project lookup service still runs locally in TypeScript
- **[Breaking]** If you request a setting or project setting and it gives you the default, the default will now be localized if it is a localized string key
  - Honestly I'm not sure this was a good idea. Almost seems like it should be opt-in, not opt-out (but I'm lazy and don't want to add to the settings definitions...). Would like input on this

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-core/930)

2024-06-10 15:57 UTC, lyonsil requested changes
> Reviewed 13 of 76 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: 13 of 76 files reviewed, 5 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1ozsn7qFZG-FZ0Y7P:-O-1ozsn7qFZG-FZ0Y7Q:bkztr41) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/c-sharp/Projects/LocalParatextProjects.cs#L18)):*
> ```Smalltalk
>     protected const string PROJECT_SETTINGS_FILE = "Settings.xml";
> 
>     public static readonly List<string> ParatextProjectInterfaces = [ProjectInterfaces.Base, ProjectInterfaces.USFM_BCV, ProjectInterfaces.USX_Chapter];
> ```

This (having public member variables) is generally a frowned upon practice in C#. It's seen as OK for `const`s but not variables. Note that even though the list is readonly, the contents of the list are not, so anyone can change this.

The "normal" .NET way of doing this, if you need the list to be public, would be to either expose methods that do what you're looking for (e.g., "is something in the list?") or expose a getter that has a copy of the data so the original is untouched.
___
*[`c-sharp/Projects/ProjectDataProviderFactory.cs` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1qXke0Gi4OZv1IS0Z:-O-1qXke0Gi4OZv1IS0_:b-3908v2) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/c-sharp/Projects/ProjectDataProviderFactory.cs#L28)):*
> ```Smalltalk
>     {
>         await StartFactory();
>         var name = $"platform.pdpFactory-{_pdpfName}-pdpf";
> ```

Seems redundant to put `pdpFactory` at the start of the name and `pdpf` at the end, but it isn't that big of a deal.
___
*[`c-sharp/Projects/ProjectDetails.cs` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1qjxv02MKz2Ko3LjJ:-O-1qjxv02MKz2Ko3LjK:b-i4yjdu) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/c-sharp/Projects/ProjectDetails.cs#L1)):*
> ```Smalltalk
> using Paratext.Data.DBLServices;
> ```

I'm guessing this was not intentional.
___
*[`c-sharp/Services/ProjectSettings.cs` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1r37DCffXuNtqIk1T:-O-1r37DCffXuNtqIk1U:b-lxl44a) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/c-sharp/Services/ProjectSettings.cs#L33)):*
> ```Smalltalk
>         {
>             { PB_BOOKS_PRESENT, PT_BOOKS_PRESENT },
>             { PB_NAME, PT_NAME },
> ```

minor nit - these were in alphabetical order, so it would be nice to keep new additions also in alphabetical order
___
*[`c-sharp-tests/PapiTestBase.cs` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1rGHM0tstfw321V67:-O-1rGHM0tstfw321V68:b7lzdgh) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/c-sharp-tests/PapiTestBase.cs#L25)):*
> ```Smalltalk
>         #region Test setup/teardown
>         // Ignore warning here because child classes need this to be async
> #pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
> ```

Just return `Task.CompletedTask` instead of disabling the warning.


<!-- Sent from Reviewable.io -->

2024-06-10 17:55 UTC, lyonsil requested changes
> Reviewed 63 of 76 files at r1.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: all files reviewed, 10 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/package.json` line 82 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1u3wN0W5bdY_UX0Zp:-O-1u3wPE4H3WEl66KWP:b-twqble) ([raw file](https://github.com/paranext/paranext-core/blob/fb1ee0ce68ebcfc2100d1a23e34f86d055cadaf5/extensions/package.json#L82)):*
> ```JSON
>     "zip-folder-promise": "^1.2.0"
>   },
>   "workspaces": ["src/*"],
> ```

Was this intentional?
___
*[`extensions/src/platform-scripture/src/project-data-provider/scripture-utils/usj-to-usx.ts` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-2A-Xo1EKg5M_0yiqi:-O-2A-Xo1EKg5M_0yiqj:bkf3pum) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/extensions/src/platform-scripture/src/project-data-provider/scripture-utils/usj-to-usx.ts#L6)):*
> ```XML
> 
> /**
>  * Convert Scripture from USJ to USX. Adapted to TypeScript from this file:
> ```

Should this be part of `platform-bible-utils`?
___
*[`extensions/src/platform-scripture/src/types/platform-scripture.d.ts` line 384 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1v-Fh17i1dBoQSWJO:-O-1v-Fh17i1dBoQSWJP:b-l20hna) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/extensions/src/platform-scripture/src/types/platform-scripture.d.ts#L384)):*
> ```XML
> 
>   export interface ProjectDataProviderInterfaces {
>     'platformScripture.USFM_BCV': IUSFMBCVProjectDataProvider;
> ```

Would it be nice to spell out `BookChapterVerse` here to make it super clear to people who see it at first? I didn't understand the acronym at first when I saw it.
___
*[`src/shared/models/project-data-provider.model.ts` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-2Ebri2aJ-j934WLcz:-O-2Ebri2aJ-j934WLd-:bmqdc31) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/src/shared/models/project-data-provider.model.ts#L11)):*
> ```XML
>  * Provider must implement
>  */
> export const PROJECT_INTERFACE_PLATFORM_BASE = 'platform.base';
> ```

I think the string `platform.base` is used in a lot of places in this PR. Should we use this const instead? Not a huge deal either way.
___
*[`src/shared/models/project-lookup.service-model.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-2Fdt68kl0vl4Zr3x2:-O-2Fdt68kl0vl4Zr3x3:b6y8zda) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/src/shared/models/project-lookup.service-model.ts#L1)):*
> ```XML
> import networkObjectService from '@shared/services/network-object.service';
> ```

Why was so much code moved from `project-lookup.service.ts` to `project-lookup.service-model.ts`? This isn't really a `model` anymore, and the service itself is just re-exporting the code from the `model` file. In general I thought we were trying to keep types and constants in the `model` only. I know sometimes a bit more would get included when we had class definitions that needed to include functions, but I don't think that's the case here.


<!-- Sent from Reviewable.io -->

2024-06-10 20:47 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: all files reviewed, 10 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/package.json` line 82 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1u3wN0W5bdY_UX0Zp:-O-2sqNc6pLFRY-W34Cn:b-93z8vc) ([raw file](https://github.com/paranext/paranext-core/blob/fb1ee0ce68ebcfc2100d1a23e34f86d055cadaf5/extensions/package.json#L82)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Was this intentional?
</blockquote></details>

Indeed - workspaces should all be listed in the top-level `package.json`. This was erroneously added back in at some point.
___
*[`extensions/src/platform-scripture/src/project-data-provider/scripture-utils/usj-to-usx.ts` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-2A-Xo1EKg5M_0yiqi:-O-2szfzBb-sP-yxKQqE:b-dxz8ua) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/extensions/src/platform-scripture/src/project-data-provider/scripture-utils/usj-to-usx.ts#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Should this be part of `platform-bible-utils`?
</blockquote></details>

Ira and I plan to move this stuff into a new package from the bnf repo. This is here temporarily til we get that done. Currently the plan is to do that very soon and update this before merging this PR.
___
*[`src/shared/models/project-lookup.service-model.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-2Fdt68kl0vl4Zr3x2:-O-2tB4vD8P4ADT0_jc3:b-it2jym) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/src/shared/models/project-lookup.service-model.ts#L1)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Why was so much code moved from `project-lookup.service.ts` to `project-lookup.service-model.ts`? This isn't really a `model` anymore, and the service itself is just re-exporting the code from the `model` file. In general I thought we were trying to keep types and constants in the `model` only. I know sometimes a bit more would get included when we had class definitions that needed to include functions, but I don't think that's the case here.
</blockquote></details>

I moved a bunch of stuff to the model because it's the place where code gets run both locally on the service and remotely on the service host. We do similar things in localization service and iirc settings service, but this is definitely significantly more dramatic since literally the whole service runs locally for TS files. I guess maybe I could import the service inside the service host... 🤔 is that preferable to this...?


<!-- Sent from Reviewable.io -->

2024-06-10 21:28 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: 75 of 76 files reviewed, 8 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/shared/models/project-lookup.service-model.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-2Fdt68kl0vl4Zr3x2:-O-31fHZ0YgD0rhEHodi:b-sazxrk) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/src/shared/models/project-lookup.service-model.ts#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I moved a bunch of stuff to the model because it's the place where code gets run both locally on the service and remotely on the service host. We do similar things in localization service and iirc settings service, but this is definitely significantly more dramatic since literally the whole service runs locally for TS files. I guess maybe I could import the service inside the service host... 🤔 is that preferable to this...?
</blockquote></details>

What's the value in pushing this into the model so it runs everywhere locally? I understand that putting it in a network object makes it easier for other languages to not have to duplicate things, but the only reason to make it run locally (I think) is performance. It feels maybe like premature optimization to say this service (or most any of them right now) need to run everywhere for performance purposes. If it's not for performance, though, I'm not sure what the motivator is.


<!-- Sent from Reviewable.io -->

2024-06-10 21:49 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: 75 of 76 files reviewed, 7 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/shared/models/project-lookup.service-model.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-2Fdt68kl0vl4Zr3x2:-O-3774F7l9KaEdjjCPX:b3ds4qb) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/src/shared/models/project-lookup.service-model.ts#L1)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

What's the value in pushing this into the model so it runs everywhere locally? I understand that putting it in a network object makes it easier for other languages to not have to duplicate things, but the only reason to make it run locally (I think) is performance. It feels maybe like premature optimization to say this service (or most any of them right now) need to run everywhere for performance purposes. If it's not for performance, though, I'm not sure what the motivator is.
</blockquote></details>

I'm just going to resolve this for now because there is ambiguity in our conventions for where some of this code goes, and this doesn't need to hold you up.


<!-- Sent from Reviewable.io -->

2024-06-11 09:11 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: 72 of 81 files reviewed, 7 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/ProjectDetails.cs` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1qjxv02MKz2Ko3LjJ:-O-39Kim5HO6Dh5cPcJ_:brlf26s) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/c-sharp/Projects/ProjectDetails.cs#L1)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm guessing this was not intentional.
</blockquote></details>

Removed :)
___
*[`src/shared/models/project-lookup.service-model.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-2Fdt68kl0vl4Zr3x2:-O-39Mpg3Z6LbTxNDiY5:b9bb0ye) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/src/shared/models/project-lookup.service-model.ts#L1)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm just going to resolve this for now because there is ambiguity in our conventions for where some of this code goes, and this doesn't need to hold you up.
</blockquote></details>

Thanks! Sorry for the weirdness. Hopefully we can get this resolved (or at least make a pattern for moving forward) before too long


<!-- Sent from Reviewable.io -->

2024-06-11 20:49 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: 57 of 82 files reviewed, 6 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1ozsn7qFZG-FZ0Y7P:-O-5_8s51mrFlBEzWzy4:b-a7bi2v) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/c-sharp/Projects/LocalParatextProjects.cs#L18)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This (having public member variables) is generally a frowned upon practice in C#. It's seen as OK for `const`s but not variables. Note that even though the list is readonly, the contents of the list are not, so anyone can change this.

The "normal" .NET way of doing this, if you need the list to be public, would be to either expose methods that do what you're looking for (e.g., "is something in the list?") or expose a getter that has a copy of the data so the original is untouched.
</blockquote></details>

Hopefully done
___
*[`c-sharp/Projects/ProjectDataProviderFactory.cs` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1qXke0Gi4OZv1IS0Z:-O-5_IugCHEf1eRdOo5v:ba3dfob) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/c-sharp/Projects/ProjectDataProviderFactory.cs#L28)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Seems redundant to put `pdpFactory` at the start of the name and `pdpf` at the end, but it isn't that big of a deal.
</blockquote></details>

Removed
___
*[`c-sharp/Services/ProjectSettings.cs` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1r37DCffXuNtqIk1T:-O-5_NwC7_fa1kSv_WZA:b-886gsx) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/c-sharp/Services/ProjectSettings.cs#L33)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

minor nit - these were in alphabetical order, so it would be nice to keep new additions also in alphabetical order
</blockquote></details>

Fixed
___
*[`c-sharp-tests/PapiTestBase.cs` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1rGHM0tstfw321V67:-O-5_a4D4X526g8YTSXU:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/c-sharp-tests/PapiTestBase.cs#L25)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Just return `Task.CompletedTask` instead of disabling the warning.
</blockquote></details>

Done
___
*[`extensions/src/platform-scripture/src/types/platform-scripture.d.ts` line 384 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-1v-Fh17i1dBoQSWJO:-O-5aV92BN8zLkZhmZpo:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/extensions/src/platform-scripture/src/types/platform-scripture.d.ts#L384)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Would it be nice to spell out `BookChapterVerse` here to make it super clear to people who see it at first? I didn't understand the acronym at first when I saw it.
</blockquote></details>

Done
___
*[`src/shared/models/project-data-provider.model.ts` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/930#-O-2Ebri2aJ-j934WLcz:-O-5aX2s-PL0GUumEs-F:b704pgs) ([raw file](https://github.com/paranext/paranext-core/blob/d3df183bc40bebfb5408e210792dd331436d92f1/src/shared/models/project-data-provider.model.ts#L11)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I think the string `platform.base` is used in a lot of places in this PR. Should we use this const instead? Not a huge deal either way.
</blockquote></details>

Fixed in the places I could (in core code), but this is one of those unfortunate situations where we don't have real exports and imports in the extensions. As such, I left it alone in the extensions.


<!-- Sent from Reviewable.io -->

2024-06-11 22:18 UTC, lyonsil requested changes
> Reviewed 1 of 1 files at r2, 6 of 8 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 127 at r4](https://reviewable.io/reviews/paranext/paranext-core/930#-O-8Kbmu57CFAf3-cGUl:-O-8Kbmu57CFAf3-cGUm:b-aqii1y) ([raw file](https://github.com/paranext/paranext-core/blob/63dac238b0e74e8473053f0152b660a015a57f82/c-sharp/Projects/LocalParatextProjects.cs#L127)):*
> ```Smalltalk
>     #region Private properties and methods
> 
>     private bool _isInitialized = false;
> ```

By convention all member variables should be at the top of the class definition. "Properties" in C# are getters/setters. So all the variables here starting with an underscore should go at the top.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 2 at r4](https://reviewable.io/reviews/paranext/paranext-core/930#-O-8LhseCGxfWlCiVm5W:-O-8LhseCGxfWlCiVm5X:b-bkl8ov) ([raw file](https://github.com/paranext/paranext-core/blob/63dac238b0e74e8473053f0152b660a015a57f82/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L2)):*
> ```Smalltalk
> using System.Collections.Concurrent;
> using System.Dynamic;
> ```

Was this intentionally added?
___
*[`c-sharp/Projects/ScrTextExtensions.cs` line 11 at r4](https://reviewable.io/reviews/paranext/paranext-core/930#-O-8MFoVDs1NzdS3EdcV:-O-8MFoVDs1NzdS3EdcW:b-yvxx2f) ([raw file](https://github.com/paranext/paranext-core/blob/63dac238b0e74e8473053f0152b660a015a57f82/c-sharp/Projects/ScrTextExtensions.cs#L11)):*
> ```Smalltalk
>         return new(
>             scrText.Name,
>             new(scrText.Guid.ToString(), LocalParatextProjects.GetParatextProjectInterfaces()),
> ```

Paratext project IDs need to be compared in a case insensitive way. In the map we were using all the IDs were set to upper case via `ToUpperInvariant()`. I'm not sure if we want to do the same to the `Guid`s here (that aren't really GUIDs), but we should make sure that all the project identification/matching is done in a case insensitive way since Paratext is treating these as hex-encoded strings but Platform.Bible is treating them as strings.


<!-- Sent from Reviewable.io -->

2024-06-12 03:22 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: 69 of 85 files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 127 at r4](https://reviewable.io/reviews/paranext/paranext-core/930#-O-8Kbmu57CFAf3-cGUl:-O-9KkmHBR-E4aUE1igr:b3tjtkx) ([raw file](https://github.com/paranext/paranext-core/blob/63dac238b0e74e8473053f0152b660a015a57f82/c-sharp/Projects/LocalParatextProjects.cs#L127)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

By convention all member variables should be at the top of the class definition. "Properties" in C# are getters/setters. So all the variables here starting with an underscore should go at the top.
</blockquote></details>

Ah man I got mixed up. Thanks!
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 2 at r4](https://reviewable.io/reviews/paranext/paranext-core/930#-O-8LhseCGxfWlCiVm5W:-O-9KuM5-lD1Y4zV4wWc:b-6ysxtd) ([raw file](https://github.com/paranext/paranext-core/blob/63dac238b0e74e8473053f0152b660a015a57f82/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L2)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Was this intentionally added?
</blockquote></details>

No... These sneaky imports are annoying haha thanks!
___
*[`c-sharp/Projects/ScrTextExtensions.cs` line 11 at r4](https://reviewable.io/reviews/paranext/paranext-core/930#-O-8MFoVDs1NzdS3EdcV:-O-9Lykm-7gOrhI3cBbO:b-57pq6n) ([raw file](https://github.com/paranext/paranext-core/blob/63dac238b0e74e8473053f0152b660a015a57f82/c-sharp/Projects/ScrTextExtensions.cs#L11)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Paratext project IDs need to be compared in a case insensitive way. In the map we were using all the IDs were set to upper case via `ToUpperInvariant()`. I'm not sure if we want to do the same to the `Guid`s here (that aren't really GUIDs), but we should make sure that all the project identification/matching is done in a case insensitive way since Paratext is treating these as hex-encoded strings but Platform.Bible is treating them as strings.
</blockquote></details>

All the literal uses I could find related to the project ids are passed through HexId like when looking up a project in ScrTextCollection, so I'm assuming those are case insensitive. Of course, I'm not controlling here how the project ids are used. But all the uses in `LocalParatextProjects` are through HexId, and the only use outside that file is where the factory is returning all the projects' metadata (which is leaking case sensitivity to P.B as you mentioned above. I believe it was before and is now returning lower-case "guid"s, but it should be converting to HexIds when looking the projects up). Are you suggesting that we `ToUpperInvariant` the "guid" here and when loading the "guid" from Settings.xml maybe just to try to help with avoiding case sensitivity issues? Or just a reminder that we need to keep this in mind? I'm fine doing `ToUpperInvariant` if that's what you'd like! Done


<!-- Sent from Reviewable.io -->

2024-06-12 16:31 UTC, lyonsil submitted a review, later dismissed
> Reviewed 24 of 24 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 236 at r5](https://reviewable.io/reviews/paranext/paranext-core/930#-O-Btcfz6xVrTCaQ3x8e:-O-Btcfz6xVrTCaQ3x8f:bkfg2dq) ([raw file](https://github.com/paranext/paranext-core/blob/5fbf5be5cfd426206c1e9c38c9796e0bb9558574/c-sharp/Projects/ParatextProjectDataProvider.cs#L236)):*
> ```Smalltalk
>         // the folder name instead of Settings.Name.
>         // https://github.com/ubsicap/Paratext/blob/aaadecd828a9b02e6f55d18e4c5dda8703ce2429/ParatextData/ProjectSettingsAccess/ProjectSettings.cs#L1438
>         if (settingName == "Name")
> ```

Here and below it would be nice to use the settings name constants instead of hard coded strings. 
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 298 at r5](https://reviewable.io/reviews/paranext/paranext-core/930#-O-BvMGvAQLu9gXwdyX3:-O-BvMGvAQLu9gXwdyX4:b-ouuqw7) ([raw file](https://github.com/paranext/paranext-core/blob/5fbf5be5cfd426206c1e9c38c9796e0bb9558574/c-sharp/Projects/ParatextProjectDataProvider.cs#L298)):*
> ```Smalltalk
>         if (paratextSettingName == "Name")
>         {
>             // Don't set a lock because this is literally moving the whole folder (chances this will
> ```

It might be good to double check this (i.e., what locking, if any, we should be concerned about) with John W. All the locking done below was at Tim's behest.
___
*[`c-sharp/Projects/ScrTextExtensions.cs` line 11 at r4](https://reviewable.io/reviews/paranext/paranext-core/930#-O-8MFoVDs1NzdS3EdcV:-O-BvoAkEEKSqaseNOVq:b3vgrax) ([raw file](https://github.com/paranext/paranext-core/blob/63dac238b0e74e8473053f0152b660a015a57f82/c-sharp/Projects/ScrTextExtensions.cs#L11)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

All the literal uses I could find related to the project ids are passed through HexId like when looking up a project in ScrTextCollection, so I'm assuming those are case insensitive. Of course, I'm not controlling here how the project ids are used. But all the uses in `LocalParatextProjects` are through HexId, and the only use outside that file is where the factory is returning all the projects' metadata (which is leaking case sensitivity to P.B as you mentioned above. I believe it was before and is now returning lower-case "guid"s, but it should be converting to HexIds when looking the projects up). Are you suggesting that we `ToUpperInvariant` the "guid" here and when loading the "guid" from Settings.xml maybe just to try to help with avoiding case sensitivity issues? Or just a reminder that we need to keep this in mind? I'm fine doing `ToUpperInvariant` if that's what you'd like! Done
</blockquote></details>

My concern isn't with how Paratext will use the IDs, because as you say they convert the "GUIDs" to `HexId`s. My concern is that when we, in P.B, are doing ID comparisons we have to make sure those are being done in a way that ensures case sensitivity isn't important. I think my original approach to this was to always convert the project IDs to upper case in this C# code so normal string comparisons would work. If we get the ID comparisons wrong, then we can end up with errors where, for example, someone might ask for project data and we say "we don't know that project" even though we handed out the ID.

This might not be as prevalent in the code now that PSIs are no longer a thing. When PSIs were around, we had to check the ID on every call coming in.


<!-- Sent from Reviewable.io -->

2024-06-12 22:01 UTC, lyonsil submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2024-06-12 22:16 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 236 at r5](https://reviewable.io/reviews/paranext/paranext-core/930#-O-Btcfz6xVrTCaQ3x8e:-O-DScxY1PUrVJgAOVHc:btqtqs7) ([raw file](https://github.com/paranext/paranext-core/blob/5fbf5be5cfd426206c1e9c38c9796e0bb9558574/c-sharp/Projects/ParatextProjectDataProvider.cs#L236)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Here and below it would be nice to use the settings name constants instead of hard coded strings.
</blockquote></details>

Makes perfect sense! Thanks! I was thinking about making a const last night but decided I didn't care enough. Apparently 10:30 is too late for clean coding...
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 298 at r5](https://reviewable.io/reviews/paranext/paranext-core/930#-O-BvMGvAQLu9gXwdyX3:-O-DSldb1SJnDIAQInrT:bcgq5xy) ([raw file](https://github.com/paranext/paranext-core/blob/5fbf5be5cfd426206c1e9c38c9796e0bb9558574/c-sharp/Projects/ParatextProjectDataProvider.cs#L298)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It might be good to double check this (i.e., what locking, if any, we should be concerned about) with John W. All the locking done below was at Tim's behest.
</blockquote></details>

TBH I just threw this in here with my mental suppositions because I think there's nearly 0% chance changing this here will ever work. When would anyone have a project that only has the settings and ldml files? Dunno. I will message in Paratext discord, but this doesn't feel urgent enough to keep this PR on hold. I figure you probably share that sentiment so you didn't make this comment blocking
___
*[`c-sharp/Projects/ScrTextExtensions.cs` line 11 at r4](https://reviewable.io/reviews/paranext/paranext-core/930#-O-8MFoVDs1NzdS3EdcV:-O-DTJI-CjMD41JxiBCY:b-emqguq) ([raw file](https://github.com/paranext/paranext-core/blob/63dac238b0e74e8473053f0152b660a015a57f82/c-sharp/Projects/ScrTextExtensions.cs#L11)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

My concern isn't with how Paratext will use the IDs, because as you say they convert the "GUIDs" to `HexId`s. My concern is that when we, in P.B, are doing ID comparisons we have to make sure those are being done in a way that ensures case sensitivity isn't important. I think my original approach to this was to always convert the project IDs to upper case in this C# code so normal string comparisons would work. If we get the ID comparisons wrong, then we can end up with errors where, for example, someone might ask for project data and we say "we don't know that project" even though we handed out the ID.

This might not be as prevalent in the code now that PSIs are no longer a thing. When PSIs were around, we had to check the ID on every call coming in.
</blockquote></details>

I think we are currently using the ID case-insensitively by virtue of using ScrTextCollection to keep track of our projects instead of doing it ourselves. It always uses HexId. We aren't caching the ScrTexts anywhere outside of ScrTextCollection. So every time someone gets a project, it goes through HexId to the ScrTextCollection. Not bullet-proof, but I don't know what more to do at this point. Sound reasonable?


<!-- Sent from Reviewable.io -->

2024-06-12 22:40 UTC, lyonsil reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: 89 of 90 files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-06-12 22:41 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930)* status: 89 of 90 files reviewed, 1 unresolved discussion

___
*[`c-sharp/Projects/ScrTextExtensions.cs` line 11 at r4](https://reviewable.io/reviews/paranext/paranext-core/930#-O-8MFoVDs1NzdS3EdcV:-O-Db3B-2fItW-eKtVSs:b3ammp6) ([raw file](https://github.com/paranext/paranext-core/blob/63dac238b0e74e8473053f0152b660a015a57f82/c-sharp/Projects/ScrTextExtensions.cs#L11)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think we are currently using the ID case-insensitively by virtue of using ScrTextCollection to keep track of our projects instead of doing it ourselves. It always uses HexId. We aren't caching the ScrTexts anywhere outside of ScrTextCollection. So every time someone gets a project, it goes through HexId to the ScrTextCollection. Not bullet-proof, but I don't know what more to do at this point. Sound reasonable?
</blockquote></details>

Yep, makes sense. I think maybe this was important when we had the possibility of looking at non-Paratext projects, but for this code that's out of scope now.


<!-- Sent from Reviewable.io -->

2024-06-12 23:33 UTC, lyonsil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/930#-:-O-DnAIoEPZkAXQPs3JR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-12 23:36 UTC, merged