Storybook components
paranext/paranext-core pull request #96
Opened 2023-03-21 16:31 UTC by rolfheij-sil

This work adds 5 components, which are exposed to the PAPI, and can be explored using storybook.
Resolves #39 & Resolves #40

There is a known issue with the ComboBox component. The signature for its onChange event is not correct (see ComboBox.tsx line 38), and triggering its onFocus event (and probably others) in Storybook produces an error.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-core/96)

2023-03-22 02:40 UTC, irahopkinson requested changes
Wow, thanks for all your good work on this both of you. I have some questions and requested changes. Do note that not all my comments are blocking (check the icon top-right for each comment).

> Reviewed 13 of 30 files at r1, 9 of 22 files at r2, 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96#-:-NR69iQl5WMRIM2Mfb_g:bj48x3v)* status: all files reviewed, 22 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`.babelrc.json` line 16 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5htbC5YRdBDEEz0r1:-NR5htbC5YRdBDEEz0r2:b-plzele) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/.babelrc.json#L16)):*
> ```JSON
>   ],
>   "plugins": []
> }
> ```

Blank line at end of file is missing (note the red symbols).
___
*[`package.json` line 66 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5scDVEZgEgvKe9OIO:-NR5scDVEZgEgvKe9OIP:b-icxiyp) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L66)):*
> ```JSON
>     "start:data": "dotnet watch --project c-sharp/ParanextDataProvider.csproj",
>     "test": "jest",
>     "storybook": "storybook dev -p 6006",
> ```

When I run this I get the following error (truncated at page boundary:
![image.png](https://files.reviewableusercontent.io/images/reviewable/5582153/Pl-XlNxBi4RlHTOPcTszUBf-/image.png)
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5iYccACbulgO8yFFq:-NR5iYccACbulgO8yFFr:bfb2ezj) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
> ```JSON
>     "test": "jest",
>     "storybook": "storybook dev -p 6006",
>     "build-storybook": "storybook build"
> ```

To follow the established pattern rename this script `storybook:build`.
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5rrj0DF1xWcu5G6g-:-NR5rrj0DF1xWcu5G6g0:b-7cucl3) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
> ```JSON
>     "test": "jest",
>     "storybook": "storybook dev -p 6006",
>     "build-storybook": "storybook build"
> ```

When I run this I get the following error:
![image.png](https://files.reviewableusercontent.io/images/reviewable/5582153/24_R3DtLFy_FH16-pE-x-m3n/image.png)
___
*[`package.json` line 108 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5iuIP0xdW1-yk7GT9:-NR5iuIP0xdW1-yk7GTA:b-t892m8) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L108)):*
> ```JSON
>     "@pmmmwh/react-refresh-webpack-plugin": "^0.5.10",
>     "@svgr/webpack": "^6.5.1",
>     "@teamsupercell/typings-for-css-modules-loader": "^2.5.2",
> ```

Keep the alphabetical order of items. `npm` normally does this for you, but perhaps this occured due to a merge. Move this line and the one above to below `@storybook/...` items.
___
*[`package.json` line 170 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5jTsUBuIxfFBnfZkB:-NR5jTsV6nWbH5RrDmZ1:bfvq037) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L170)):*
> ```JSON
>     "sass": "^1.59.3",
>     "sass-loader": "^13.2.0",
>     "storybook": "^7.0.0-beta.60",
> ```

We don't tend to use beta versions in production. Just checking in on the reasons for using this at a beta version?
___
*[`.vscode/launch.json` line 63 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5pdPtBbTgzTzror2n:-NR5pdPtBbTgzTzror2o:b-1u4nun) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/.vscode/launch.json#L63)):*
> ```JSON
>       }
>     },
>       },
> ```

This is in the wrong place. VSCode can't launch anything at the moment. Move it to to below the storybook item (just before the next square bracket).
___
*[`src/renderer/components/papi-components/Button.tsx` line 32 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5wLDhD2fErT6g6qmu:-NR5wLDhD2fErT6g6qmv:b-kx4421) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/Button.tsx#L32)):*
> ```XML
>  */
> function Button({
>   primary = false,
> ```

See our [guidelines on naming booleans](https://github.com/paranext/paranext/wiki/Code-Style-Guide#typescript-specific-guidelines). Change to something like `isPrimary`. However if this is following a React naming convention then feel free to ignore this. E.g. I'm not asking you to rename `disabled` because that is a well known HTML attribute name even though it doesn't follow our naming guidelines (they are just guidelines, not rules).



_Code quote:_
```XML
primary
```
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 21 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR6--QQ6likh1P1h0Qf:-NR6--QQ6likh1P1h0Qg:b-dslyds) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/ComboBox.tsx#L21)):*
> ```XML
>    * @default false
>    */
>   error?: boolean;
> ```

See my comment above about our naming guidelines. Change this to `isError` or `hasError`.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 26 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR6-PjqErfs1OP9Po5_:-NR6-PjqErfs1OP9Po5a:b-7ptujt) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/ComboBox.tsx#L26)):*
> ```XML
>    * @default false
>    */
>   fullWidth?: boolean;
> ```

We could debate this one but following our naming guidelines here would mean users of this component could also follow the guidelines. So you could change this to `isFullWidth`.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 39 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR60_Rc49hl6p1xR-ik:-NR60_Rc49hl6p1xR-il:bktg5sg) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/ComboBox.tsx#L39)):*
> ```XML
>    */
>   onChange?: () => void; // This event handler does not have the suggested signature,
>   // but using the suggested one leads to additional MUI import, and I'm not sure if that's a great idea
> ```

What import does it add?
___
*[`src/renderer/components/papi-components/Slider.tsx` line 40 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR61qjjEADyIpdp7Ofo:-NR61qjk4P6CeIzAcPqP:b-hl0kn2) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/Slider.tsx#L40)):*
> ```XML
>    * @default false
>    */
>   marks?: boolean;
> ```

See my comment above about our naming guidelines. Another one that could be debated so you could change this to `hasMarks`.
___
*[`src/renderer/components/papi-components/Switch.tsx` line 9 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR62qU5AZxDvVHZO2cE:-NR62qU5AZxDvVHZO2cF:b-rqlnu1) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/Switch.tsx#L9)):*
> ```XML
>    * If `true`, the component is checked.
>    */
>   checked?: boolean;
> ```

See my comment above about our naming guidelines. Changing in this file to `isChecked`, `isPrimary`, `hasError`.

`checked` is debatable since that is a known HTML attribute, but since this is a switch rather than a checkbox I might argue for calling it `isOn`. 
___
*[`src/renderer/components/papi-components/Textfield.tsx` line 19 at r4](https://reviewable.io/reviews/paranext/paranext-core/ [...]

2023-03-22 11:12 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: all files reviewed, 21 unresolved discussions (waiting on @irahopkinson, @katherinejensen00, and @tjcouch-sil)

___
*[`.babelrc.json` line 16 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5htbC5YRdBDEEz0r1:-NR7uc7sEfaHV1Gl_rjj:b-886gsx) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/.babelrc.json#L16)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Blank line at end of file is missing (note the red symbols).
</blockquote></details>

Fixed
___
*[`package.json` line 66 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5scDVEZgEgvKe9OIO:-NR7ruuMBT-Ka2hw-CfQ:b-a4tw15) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L66)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

When I run this I get the following error (truncated at page boundary:
![image.png](https://files.reviewableusercontent.io/images/reviewable/5582153/Pl-XlNxBi4RlHTOPcTszUBf-/image.png)

</blockquote></details>

I think this is a known issue that has something to do with Webpack.
It is possible to run storybook like this:
`npm run storybook -- --debug-webpack`

@tjcouch-sil Can you tell us / Ira more about why we're running it like this?
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5iYccACbulgO8yFFq:-NR7sPd8-guczfGS1rKR:ba3xdsc) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

To follow the established pattern rename this script `storybook:build`.
</blockquote></details>

I think it should be `build:storybook`?
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5rrj0DF1xWcu5G6g-:-NR7szuK1cCcZzZcQIUx:b-x58qzj) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

When I run this I get the following error:
![image.png](https://files.reviewableusercontent.io/images/reviewable/5582153/24_R3DtLFy_FH16-pE-x-m3n/image.png)

</blockquote></details>

I get a different error when trying this build step. See below. I'm not sure if we even need this build step. @tjcouch-sil Do we need this?

![image.png](https://files.reviewableusercontent.io/images/reviewable/108285668/vlPiNfij6p8RL9UlBZDl13uI/image.png)
___
*[`package.json` line 108 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5iuIP0xdW1-yk7GT9:-NR7uf1N5qv48exIJCbz:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L108)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Keep the alphabetical order of items. `npm` normally does this for you, but perhaps this occured due to a merge. Move this line and the one above to below `@storybook/...` items.
</blockquote></details>

Done.
___
*[`package.json` line 170 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5jTsUBuIxfFBnfZkB:-NR7tjEwBiw7mu_GFxBU:b-sruujm) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L170)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

We don't tend to use beta versions in production. Just checking in on the reasons for using this at a beta version?
</blockquote></details>

@tjcouch-sil @katherinejensen00 Can you answer this one?
___
*[`.vscode/launch.json` line 63 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5pdPtBbTgzTzror2n:-NR7u_dy27TNfod1oXVY:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/.vscode/launch.json#L63)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is in the wrong place. VSCode can't launch anything at the moment. Move it to to below the storybook item (just before the next square bracket).
</blockquote></details>

Done.
___
*[`src/renderer/components/papi-components/Button.tsx` line 32 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5wLDhD2fErT6g6qmu:-NR7wzZR88UFQgpqFFxn:b-bppkes) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/Button.tsx#L32)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

See our [guidelines on naming booleans](https://github.com/paranext/paranext/wiki/Code-Style-Guide#typescript-specific-guidelines). Change to something like `isPrimary`. However if this is following a React naming convention then feel free to ignore this. E.g. I'm not asking you to rename `disabled` because that is a well known HTML attribute name even though it doesn't follow our naming guidelines (they are just guidelines, not rules).
</blockquote></details>

I've updated the names of the booleans that do not have a direct HTML/MUI counterpart
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 21 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR6--QQ6likh1P1h0Qf:-NR7yU9y8i7EZLYLPgQ7:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/ComboBox.tsx#L21)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

See my comment above about our naming guidelines. Change this to `isError` or `hasError`.
</blockquote></details>

Done.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 26 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR6-PjqErfs1OP9Po5_:-NR7yYuT2aEpvl_60wqi:bkfm7xr) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/ComboBox.tsx#L26)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

We could debate this one but following our naming guidelines here would mean users of this component could also follow the guidelines. So you could change this to `isFullWidth`.
</blockquote></details>

fullWidth is a prop on the MUI component, that we're exposing to the user of our combo box. Of course we can expose it as isFullWidth, but that might be confusing. Perhaps we should discuss conventions for these kinds of situations with the team?
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 39 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR60_Rc49hl6p1xR-ik:-NR7zYqQDFeuFx3oqMLp:bp0miga) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/ComboBox.tsx#L39)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

What import does it add?
</blockquote></details>

`AutocompleteChangeDetails` and `AutocompleteChangeReason`
Both are directly related to the Autocomplete component (which we've rebranded as Combobox), so maybe it's not a problem after all
___
*[`src/renderer/components/papi-components/Slider.tsx` line 40 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR61qjjEADyIpdp7Ofo:-NR7zp4B9ih5as9WCZun:b-537p8w) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/Slider.tsx#L40)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

See [...]

2023-03-22 11:15 UTC, rolfheij-sil reviewed
Thank you! And thanks for reviewing that much code this quick.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96#-:-NR80bQ47ZxOFaX5Xgco:b-uizcwu)* status: 32 of 43 files reviewed, 21 unresolved discussions (waiting on @irahopkinson, @katherinejensen00, and @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2023-03-22 14:32 UTC, katherinejensen00 reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: 28 of 43 files reviewed, 21 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`package.json` line 170 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5jTsUBuIxfFBnfZkB:-NR8iAaI6Vcy25a-qVI3:b-drpo53) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L170)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

@tjcouch-sil @katherinejensen00 Can you answer this one?
</blockquote></details>

The beta version had some features we needed and I think it solved a webpack configuration issue we were running into. By the time we get to release, the changes we care about should hopefully become part of a more stable release.
___
*[`src/stories/assets/code-brackets.svg` line  at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR66WjD4hmKkq2gyx6F:-NR8iqG-AKSl1krWepOv:bpsxrwf) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/stories/assets/code-brackets.svg#L)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

@katherinejensen00 Can you answer this one?
</blockquote></details>

Good question, @irahopkinson . Those were part of the initial storybook install and they use them on a sample page that we no longer need. We could just remove them if you think that would be best.


<!-- Sent from Reviewable.io -->

2023-03-22 17:06 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: 28 of 43 files reviewed, 21 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`package.json` line 66 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5scDVEZgEgvKe9OIO:-NR9FoeX1soVhSV3LMIO:byh55a1) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L66)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I think this is a known issue that has something to do with Webpack.
It is possible to run storybook like this:
`npm run storybook -- --debug-webpack`

@tjcouch-sil Can you tell us / Ira more about why we're running it like this?
</blockquote></details>

Ignore my previous comment. You should now be able to run it with `npm run storybook`


<!-- Sent from Reviewable.io -->

2023-03-22 19:24 UTC, irahopkinson requested changes
> Reviewed 14 of 15 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: all files reviewed, 3 unresolved discussions (waiting on @katherinejensen00, @rolfheij-sil, and @tjcouch-sil)

___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5iYccACbulgO8yFFq:-NR9clsg1Pm2Rri6BNl2:b-ckqzs7) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I think it should be `build:storybook`?
</blockquote></details>

No actually, `build:storybook` indicates its part of our build process (which I'm pretty sure its not). `storybook:build` indicates it's a build as part of the storybook set of scripts/processes.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 26 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR6-PjqErfs1OP9Po5_:-NR9epobEKL6RYKa1yrp:bi9iw5i) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/ComboBox.tsx#L26)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

fullWidth is a prop on the MUI component, that we're exposing to the user of our combo box. Of course we can expose it as isFullWidth, but that might be confusing. Perhaps we should discuss conventions for these kinds of situations with the team?
</blockquote></details>

That would be a good idea for you to raise that. Your reasoning is good for this PR.
___
*[`src/stories/assets/code-brackets.svg` line  at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR66WjD4hmKkq2gyx6F:-NR9gHun0kvdjTLr12Mo:bz7ldpm) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/stories/assets/code-brackets.svg#L)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Good question, @irahopkinson . Those were part of the initial storybook install and they use them on a sample page that we no longer need. We could just remove them if you think that would be best.
</blockquote></details>

Remember this is an public (open source) repo. Given it was part of a sample, it's likely that we would have appropriate rights but you would need to sight them (say in a `README.md` file). However if you don't need it then it's just YAGNI, remove them.


<!-- Sent from Reviewable.io -->

2023-03-22 21:51 UTC, katherinejensen00 reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: 31 of 45 files reviewed, 3 unresolved discussions (waiting on @irahopkinson, @rolfheij-sil, and @tjcouch-sil)

___
*[`src/stories/assets/code-brackets.svg` line  at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR66WjD4hmKkq2gyx6F:-NRAILvZ1BnvGb0sf4_v:b-72kpdm) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/stories/assets/code-brackets.svg#L)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Remember this is an public (open source) repo. Given it was part of a sample, it's likely that we would have appropriate rights but you would need to sight them (say in a `README.md` file). However if you don't need it then it's just YAGNI, remove them.
</blockquote></details>

That makes sense. I went ahead and removed them.


<!-- Sent from Reviewable.io -->

2023-03-22 23:35 UTC, tjcouch-sil requested changes
Thanks for all the hard work on this, guys! I haven't gotten through the whole PR yet, but I will continue working on it tomorrow. Just wanted to get these comments out for you to take a look at. Keep up the great work! This is awesome stuff.

> Reviewed 2 of 30 files at r1, 2 of 22 files at r2, 6 of 21 files at r4, 7 of 15 files at r5, 1 of 1 files at r6, 4 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96#-:-NRAf1i_1VbLSZwRUDaf:b-l4klvf)* status: 35 of 45 files reviewed, 16 unresolved discussions (waiting on @irahopkinson, @katherinejensen00, and @rolfheij-sil)

___
*[`.eslintrc.js` line 2 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9KsIp-IH-PG40gZcy:-NR9KsIp-IH-PG40gZcz:b-8nuhv8) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/.eslintrc.js#L2)):*
> ```JavaScript
> module.exports = {
>   extends: ['erb', 'plugin:storybook/recommended'], // https://github.com/electron-react-boilerplate/eslint-config-erb/blob/main/index.js
> ```

Please add comment link to the `plugin:storybook/recommended` config so we can easily access: https://github.com/storybookjs/eslint-plugin-storybook/blob/main/lib/configs/recommended.ts
___
*[`.eslintrc.js` line 14 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9KYS-AD83akkKz7_S:-NR9KYS06JKT5Ity3xu8:b75n4k6) ([raw file](https://github.com/paranext/paranext-core/blob/0fee0ee7ac620e08e95f895915c36172d1505c04/.eslintrc.js#L14)):*
> ```JavaScript
>     'react/jsx-filename-extension': 'off',
>     'react/react-in-jsx-scope': 'off',
> ```

Would you mind please adding this empty line back in? I suppose we should discuss style rules around `#region` tags, but let's keep it consistent for now if that's ok :)
___
*[`package.json` line 66 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5scDVEZgEgvKe9OIO:-NR9LosTCG7Yx1VDPV9r:bylqoq8) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L66)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Ignore my previous comment. You should now be able to run it with `npm run storybook`
</blockquote></details>

I know this is already resolved, but fyi `--debug-webpack` just prints out the final webpack configuration that storybook is using.
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5rrj0DF1xWcu5G6g-:-NR9MCuSEhKf0QOjkZHK:blugb0l) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I get a different error when trying this build step. See below. I'm not sure if we even need this build step. @tjcouch-sil Do we need this?

![image.png](https://files.reviewableusercontent.io/images/reviewable/108285668/vlPiNfij6p8RL9UlBZDl13uI/image.png)

</blockquote></details>

This is also resolved now, right?
___
*[`package.json` line 170 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5jTsUBuIxfFBnfZkB:-NR9MMr987OB4JwuLpn7:bx7d8n8) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L170)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

The beta version had some features we needed and I think it solved a webpack configuration issue we were running into. By the time we get to release, the changes we care about should hopefully become part of a more stable release.
</blockquote></details>

Yep, the full release version is not currently fully compatible with webpack 5 (I think you had to run with legacy dependency resolving or something weird), so we pulled the beta version for now. We can move to storybook 7 once it is released as it has webpack 5 support.
___
*[`.vscode/launch.json` line 69 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9NKhBBqFxbFSNqZF7:-NR9NKhBBqFxbFSNqZF8:b-6qqqi2) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/.vscode/launch.json#L69)):*
> ```JSON
>       "protocol": "inspector",
>       "runtimeExecutable": "npm",
>       "runtimeArgs": ["run", "storybook", "--", "--debug-webpack"],
> ```

We may want to remove `-- --debug-webpack` and let this launch command be consistent with the command-line `npm run storybook`.



_Code quote:_
```JSON
"--", "--debug-webpack"
```
___
*[`src/renderer/components/papi-components/Button.tsx` line 17 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9NwkP-OV8IzCHibxc:-NR9NwkP-OV8IzCHibxd:b-6vw3bq) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/Button.tsx#L17)):*
> ```XML
>    * Additional css classes to help with unique styling of the button
>    */
>   className?: string[];
> ```

React convention is that `className` is a `string`, not a `string[]`. Let's match convention here and in other places in this branch.
___
*[`src/renderer/components/papi-components/Button.tsx` line 44 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9PMlG11XLX8BElG5H:-NR9PMlG11XLX8BElG5I:b-kjtrzt) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/Button.tsx#L44)):*
> ```XML
>     <MuiButton
>       disabled={disabled}
>       className={['papi-button', mode, classNameString].join(' ')}
> ```

Consider using string template literals ([example](https://github.com/tjcouch-sil/paranext-poc/blob/1b21609ff445468b4b211e1db877131466afe08d/react-electron-poc/src/renderer/components/ScrRefSelector.tsx#L50)) when building the `className` - it's a more common convention in React when building `className` than maintaining an array and joining them. Though this is not a hard and fast rule, so we should discuss in code style discussions. Whatever you decide to do here, please also match in other places in this branch.

In this case, it would look something like `className={`papi-button ${mode} className`}` Note the formatting here is really weird. I'm trying to put back ticks in, but the markdown is eating them and removing the code block formatting. Here's a screenshot of the unformatted code:
![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/RJeWB6cOqK64Fqtc5biWGpfy/image.png)

If you wanted, you could also replace `mode` inside that `className` template literal with `isPrimary ? 'primary' : 'secondary'` and not even define a `mode` variable in the first place.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 26 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR6-PjqErfs1OP9Po5_:-NRATfwl-kcr-JyLfobz:brq2qf1) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/ComboBox.tsx#L26)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

That would be a good idea for you to raise that. Your reasoning is good for this PR.
</blockquote></details>

I think this should match our guidelines and use `isFullWidth` because we are making our own api that is not tied to MUI.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 25 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRATJa11o5kWTt2Csn4:-NRATJa11o5kWTt2Csn5:b-12wdet) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L25)):*
> ```XML
>    * @default false
>    */
>   hasError?: boolean;
> ```

What does this do? Does it provide an error message somewhere? Maybe consider changing this to `error?: string` where, if it is defined, it makes it look all error-y and also displays the error message somew [...]

2023-03-23 00:42 UTC, irahopkinson requested changes
> Reviewed 14 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: all files reviewed, 15 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5rrj0DF1xWcu5G6g-:-NRAreu30LG0HlZl2Nen:b-o5xghv) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is also resolved now, right?
</blockquote></details>

Nope, I still get the error.
___
*[`src/renderer/components/papi-components/Button.tsx` line 17 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9NwkP-OV8IzCHibxc:-NRAq4yT7p9TpYhYJHe7:b121yf2) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/Button.tsx#L17)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

React convention is that `className` is a `string`, not a `string[]`. Let's match convention here and in other places in this branch.
</blockquote></details>

Oh good spotting, I missed that. As an array it should be plural anyway, i.e. `classNames`. But TJ is right, go with the React convention.
___
*[`src/renderer/components/papi-components/Button.tsx` line 44 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9PMlG11XLX8BElG5H:-NRAq_hD-d6tBY6lJeNm:b-kexw87) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/Button.tsx#L44)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Consider using string template literals ([example](https://github.com/tjcouch-sil/paranext-poc/blob/1b21609ff445468b4b211e1db877131466afe08d/react-electron-poc/src/renderer/components/ScrRefSelector.tsx#L50)) when building the `className` - it's a more common convention in React when building `className` than maintaining an array and joining them. Though this is not a hard and fast rule, so we should discuss in code style discussions. Whatever you decide to do here, please also match in other places in this branch.

In this case, it would look something like `className={`papi-button ${mode} className`}` Note the formatting here is really weird. I'm trying to put back ticks in, but the markdown is eating them and removing the code block formatting. Here's a screenshot of the unformatted code:
![image.png](https://files.reviewableusercontent.io/images/reviewable/104016682/RJeWB6cOqK64Fqtc5biWGpfy/image.png)

If you wanted, you could also replace `mode` inside that `className` template literal with `isPrimary ? 'primary' : 'secondary'` and not even define a `mode` variable in the first place.
</blockquote></details>

@tjcouch-sil you can get the formatting you want if you use a tripple-backtick begining and end (even inline), i.e. ```className={`papi-button ${mode} className`}```.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 45 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRASA6S7PdBKTc-iKnX:-NRAs_gtEHOwtGo9tmxq:boaec8r) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L45)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Providing a handler with MUI data types is leaking MUI stuff out onto our API. We should ingest their `onChange` with our own intermediate `onChange` and then run the prop `onChange` with what we want to provide.
</blockquote></details>

What about just making our own copy of the type for now until we know what we need, i.e. `type ComboBoxChangeReason = AutocompleteChangeReason`?


<!-- Sent from Reviewable.io -->

2023-03-23 19:36 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: all files reviewed, 22 unresolved discussions (waiting on @katherinejensen00 and @tjcouch-sil)

___
*[`.eslintrc.js` line 2 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9KsIp-IH-PG40gZcy:-NRDS0bH5HTBwvCc9OHy:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/.eslintrc.js#L2)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please add comment link to the `plugin:storybook/recommended` config so we can easily access: https://github.com/storybookjs/eslint-plugin-storybook/blob/main/lib/configs/recommended.ts
</blockquote></details>

Done.
___
*[`.eslintrc.js` line 14 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9KYS-AD83akkKz7_S:-NREjxjk0_RNlCd-krrh:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/0fee0ee7ac620e08e95f895915c36172d1505c04/.eslintrc.js#L14)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Would you mind please adding this empty line back in? I suppose we should discuss style rules around `#region` tags, but let's keep it consistent for now if that's ok :)
</blockquote></details>

Done
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5iYccACbulgO8yFFq:-NRDSLPVBw0Jm748e3RX:b-x9hz3o) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

What does this script do? I see [`npm run build-storybook`](https://storybook.js.org/docs/react/api/cli-options#build-storybook); is this an alias for that maybe? If this is the command that publishes the storybook files to `storybook-static` or whatever that directory is called, maybe we can rename this to `package:storybook` or something similar? It isn't part of packaging the application itself, but I imagine we will probably want to serve these files for extension developers to use at some point.
</blockquote></details>

To be honest I don't know what it does, I guess it's part of the default/suggested configuration. @katherinejensen00 Do you know what this does?
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5rrj0DF1xWcu5G6g-:-NRDSX4FCzF2HDxUkol9:b-2sx52f) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nope, I still get the error.
</blockquote></details>

I think @katherinejensen00 got this same error. We're you able to resolve it Katherine?
___
*[`.vscode/launch.json` line 69 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9NKhBBqFxbFSNqZF7:-NRDSlljChK9QGublTGj:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/.vscode/launch.json#L69)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We may want to remove `-- --debug-webpack` and let this launch command be consistent with the command-line `npm run storybook`.
</blockquote></details>

Done
___
*[`src/renderer/components/papi-components/Button.tsx` line 17 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9NwkP-OV8IzCHibxc:-NRDStcpDN1oiHjB8fLO:b-z7jlai) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/Button.tsx#L17)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Oh good spotting, I missed that. As an array it should be plural anyway, i.e. `classNames`. But TJ is right, go with the React convention.
</blockquote></details>

As discussed we'll turn this (back) into a `string`.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 26 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR6-PjqErfs1OP9Po5_:-NRDUcZE2ucDhTkb247j:b-ayoolq) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/ComboBox.tsx#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think this should match our guidelines and use `isFullWidth` because we are making our own api that is not tied to MUI.
</blockquote></details>

Alright, I'll make sure all exposed props follow our guidelines.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 25 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRATJa11o5kWTt2Csn4:-NRDU2lB3zmSDjo3w8OF:b2zjnqn) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L25)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

What does this do? Does it provide an error message somewhere? Maybe consider changing this to `error?: string` where, if it is defined, it makes it look all error-y and also displays the error message somewhere. Or we can do this later.
</blockquote></details>

The MUI Textfield component has an error prop that we've exposed. I think all it does is change the styling of the Textfield to show the user that something is wrong with the input. Since the Combobox uses the Textfield, I thought it might be a good idea to add the prop here too
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 34 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRASWX99WH64h-oKvaF:-NRDUqep3vdimmYWXjPU:b8zqtuw) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L34)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

How does this get translated into UI that the dropdown displays? We need a type on this (and probably more explanation of how it works in the JSDoc comment above) so people know what they need to provide. We should likely make our own type and then have an intermediate step where we translate it into a type that MUI expects.
</blockquote></details>

Good question, I don't know how it gets translated. Any idea what type we should use? `String[]` should work, I guess?
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 45 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRASA6S7PdBKTc-iKnX:-NRDXSYA4doFUBX6m7vh:b-lmmcur) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L45)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

What about just making our own copy of the type for now until we know what we need, i.e. `type ComboBoxChangeReason = AutocompleteChangeReason`?
</blockquote></details>

I'll go with Ira's idea for now. I guess we will come back to this discussion later
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 82 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRAXR0r6Amot2M14P8M:-NRDVw8L30asGGis3VPT:bvhw4ix) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L82)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do we know what we're passing in here as `props`? It looks like the type is `object`, which offers almost no type safety. It looks like MUI [barely documents this in their documentation](https://mui.com/material-ui/api/autocomplete/#props) and [passes in a whole mess of props](https://github.com/mui/material-ui/blob/16efe9de [...]

2023-03-23 22:23 UTC, irahopkinson requested changes
> Reviewed 14 of 15 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: all files reviewed, 23 unresolved discussions (waiting on @katherinejensen00, @rolfheij-sil, and @tjcouch-sil)

___
*[`.eslintrc.js` line 2 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9KsIp-IH-PG40gZcy:-NRFRZrS4uYOExN93mSy:b2c4k6o) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/.eslintrc.js#L2)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This would be better like this:
```
  extends: [
     // https://github.com/electron-react-boilerplate/eslint-config-erb/blob/main/index.js
    // airbnb rules are embedded in erb https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb
    'erb',
    // https://github.com/storybookjs/eslint-plugin-storybook/blob/main/lib/configs/recommended.ts
    'plugin:storybook/recommended'
  ],
```
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5rrj0DF1xWcu5G6g-:-NRFSNIF1bsLr8RNpQMg:b-vt2adh) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I think @katherinejensen00 got this same error. We're you able to resolve it Katherine?
</blockquote></details>

I'm wondering if you get this to build you will solve the ComboBox error, or when you solve the ComboBox error this might build correctly. However if no one knows what it does or even uses it then take it out until its needed.
___
*[`src/renderer/components/papi-components/Button.tsx` line 34 at r9](https://reviewable.io/reviews/paranext/paranext-core/96#-NRFUIE886UWD5SSflbO:-NRFUIE886UWD5SSflbP:b-y1mpzf) ([raw file](https://github.com/paranext/paranext-core/blob/ff59bc6782089605a2927c4cd811f7ca29e6c839/src/renderer/components/papi-components/Button.tsx#L34)):*
> ```XML
> function Button({
>   isPrimary = false,
>   isDisabled: disabled,
> ```

This is more complicated to destructure this here and is not consistent with how its done in other components. Just use `isDisabled` below instead of destructuring here.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 45 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRASA6S7PdBKTc-iKnX:-NRFTG6VBMaO2bg4kdrc:b-lk1vwy) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L45)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I'll go with Ira's idea for now. I guess we will come back to this discussion later
</blockquote></details>

Drop the `Mui` prefix from both of these so Mui doesn't leak out to users of this component.
___
*[`src/renderer/components/papi-components/Switch.tsx` line 36 at r5](https://reviewable.io/reviews/paranext/paranext-core/96#-NRFV1XME6WR5yLSFMxU:-NRFV1XME6WR5yLSFMxV:b-bjc58r) ([raw file](https://github.com/paranext/paranext-core/blob/3c1072ef86fa452f5e68b93a8978fa240fdd8080/src/renderer/components/papi-components/Switch.tsx#L36)):*
> ```XML
>    * Optional click handler
>    */
>   onClick?: MouseEventHandler<HTMLButtonElement>;
> ```

Did I miss a discussion? I'm surprised to see this removed since `onClick` is the most used thing for any component.
___
*[`src/stories/Textfield.stories.ts` line 1 at r7](https://reviewable.io/reviews/paranext/paranext-core/96#-NRDrw3L-y9c-yH4Rak1:-NRFXsKr8_VaGV9A4VIf:bjdza4a) ([raw file](https://github.com/paranext/paranext-core/blob/eb4a3f7f60020dfc5be4764ced78f202391dc422/src/stories/Textfield.stories.ts#L1)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done
</blockquote></details>

Er... you still need to change the filename. Note my post above about how to do that in Windows rather than Git.
___
*[`src/renderer/components/papi-components/Textfield.tsx` line 60 at r7](https://reviewable.io/reviews/paranext/paranext-core/96#-NRDhxeB9ROsJJShYDlH:-NRFVYAZ7l7SOR5RYfIG:b9o8ofy) ([raw file](https://github.com/paranext/paranext-core/blob/eb4a3f7f60020dfc5be4764ced78f202391dc422/src/renderer/components/papi-components/Textfield.tsx#L60)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done
</blockquote></details>

This is not a Git problem but a Windows problem. So you don't need to add Git commits to fix it. I usually rename the file by adding a character, e.g. from `Texfield.ts` to `Text-field.ts`, then removing and changing case at the same time, i.e. to `TextField.ts`. If you go directly from `Texfield.ts` to `TextField.ts` Windows changes the name you see but not the underlying name on the filesystem so Git sees no change but we do see the change and assume Git has the issue. I'm also post this in Discord for others to note.


<!-- Sent from Reviewable.io -->

2023-03-24 14:27 UTC, tjcouch-sil requested changes
Thanks for the great updates!! Keep up the good work. Looking forward to more soon!

> Reviewed 14 of 15 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96#-:-NRJ-mzk-aaXJrlAi4i1:b15k50c)* status: all files reviewed, 14 unresolved discussions (waiting on @irahopkinson, @katherinejensen00, and @rolfheij-sil)

___
*[`src/renderer/components/papi-components/Button.tsx` line 34 at r9](https://reviewable.io/reviews/paranext/paranext-core/96#-NRFUIE886UWD5SSflbO:-NRIiBoh9XA78mpMtaqP:b-nvbgtv) ([raw file](https://github.com/paranext/paranext-core/blob/ff59bc6782089605a2927c4cd811f7ca29e6c839/src/renderer/components/papi-components/Button.tsx#L34)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is more complicated to destructure this here and is not consistent with how its done in other components. Just use `isDisabled` below instead of destructuring here.
</blockquote></details>

FYI this happens when you have an object being destructured and then rename one of the members of that object type. I guess TypeScript thinks it's being helpful by not renaming the variable created by the destructure. So you just kinda have to keep an eye out for this kind of thing when renaming type members. An easy tweak to fix this is to rename `disabled` to `isDisabled` on this line as well. Then it will have `isDisabled: isDisabled` on this line (and will use `isDisabled` below), so you can shorten it to just `isDisabled`
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 25 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRATJa11o5kWTt2Csn4:-NRIip6616HkQscg54Dm:b4bm941) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L25)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

The MUI Textfield component has an error prop that we've exposed. I think all it does is change the styling of the Textfield to show the user that something is wrong with the input. Since the Combobox uses the Textfield, I thought it might be a good idea to add the prop here too
</blockquote></details>

Gotcha. For some reason, I thought there was also a separate error prop of some sort that displayed the error string passed in to the user. If that doesn't exist, this is fine. Thanks!
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 34 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRASWX99WH64h-oKvaF:-NRIk-kMDu4T9FK4CNMF:bmtc1ez) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L34)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Good question, I don't know how it gets translated. Any idea what type we should use? `String[]` should work, I guess?
</blockquote></details>

https://mui.com/material-ui/react-autocomplete/#options-structure
Looks like they expect an array of objects that have `label: string` if you don't override their `getOptionLabel`. As such, I would be in favor of making `ComboBox` generic as I mention in a thread below. We can make it something like `type MyOptionType = string | { label: string } | Record<string, unknown>` and `ComboBox<T extends MyOptionType>`. Then we can explain that they need to put a label on each option unless they override `getOptionLabel`. Or we can not give them the option to override `getOptionLabel` right now and just tell them they have to provide a label like `type MyOptionType = string | { label: string }` - that might actually be a cleaner way for now :)
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 45 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRASA6S7PdBKTc-iKnX:-NRImllfExmpf65nvR7d:b-3425xo) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L45)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Drop the `Mui` prefix from both of these so Mui doesn't leak out to users of this component.
</blockquote></details>

I believe Ira was suggesting we declare new types that are simple aliases over the existing types. Like at the top of this file you would want to write `export type ComboBoxChangeDetails = MuiComboBoxChangeDetails;`, then you can use `ComboBoxChangeDetails` here. That way, it is our own type, and we can do what we want with it.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 82 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRAXR0r6Amot2M14P8M:-NRInE1Y3Two48zTj5EW:b84wliq) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L82)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I've tried to improve this but I don't think it's perfect yet. Perhaps we can have a look at it together
</blockquote></details>

Nah, this is great :) thanks!
___
*[`src/stories/ComboBox.stories.tsx` line 13 at r9](https://reviewable.io/reviews/paranext/paranext-core/96#-NRIoYhl3f-hESI6ghPz:-NRIoYhl3f-hESI6ghQ-:b-5sic92) ([raw file](https://github.com/paranext/paranext-core/blob/ff59bc6782089605a2927c4cd811f7ca29e6c839/src/stories/ComboBox.stories.tsx#L13)):*
> ```XML
>     hasError: { control: 'boolean' },
>     isFullWidth: { control: 'boolean' },
>     options: { control: 'text' },
> ```

I wonder if the problem with this story is that `options` should be an array of strings or an array of objects with a `label` member, not just text. Or maybe `text` here just means they will take whatever you put in it and parse it into an object.
___
*[`src/renderer/components/papi-components/Textfield.tsx` line 49 at r7](https://reviewable.io/reviews/paranext/paranext-core/96#-NRDiBuxBBcRjUme4GtD:-NRIo4og0-rzMT3fzs2U:b3oyoxz) ([raw file](https://github.com/paranext/paranext-core/blob/eb4a3f7f60020dfc5be4764ced78f202391dc422/src/renderer/components/papi-components/Textfield.tsx#L49)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I'm not really sure what it needs, it's a bit obscure. MUI decided what these event handlers should look like based on the TextField variant you choose (with the `variant` prop). So I don't know what we can say about these without knowing if we're dealing with an `outlined` or a `filled` TextField
</blockquote></details>

Do we particularly need to worry about variants right now? Is it just a stylistic difference, or is there functional difference as well? Why are there two different events fired based on the variant? Maybe we can look more closely at this together soon.


<!-- Sent from Reviewable.io -->

2023-03-24 20:23 UTC, katherinejensen00 reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: 34 of 46 files reviewed, 14 unresolved discussions (waiting on @irahopkinson, @katherinejensen00, @rolfheij-sil, and @tjcouch-sil)

___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5iYccACbulgO8yFFq:-NRKGx876DGXlLXcC2_n:b-udyo43) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

To be honest I don't know what it does, I guess it's part of the default/suggested configuration. @katherinejensen00 Do you know what this does?
</blockquote></details>

That is the default alias for storybook build. I renamed the alias as TJ suggested to avoid confusion so it doesn't look like it is part of the overall build process. The new command is npm run package:storybook
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5rrj0DF1xWcu5G6g-:-NRKHMsb5_UO86RQowNa:b-a4a7bh) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I'm wondering if you get this to build you will solve the ComboBox error, or when you solve the ComboBox error this might build correctly. However if no one knows what it does or even uses it then take it out until its needed.
</blockquote></details>

@irahopkinson Are you still getting this error after the latest changes? I don't think I have gotten this one before and I am having a hard time reproducing it. Maybe we can pair on it if you are still getting it.


<!-- Sent from Reviewable.io -->

2023-03-26 21:17 UTC, irahopkinson requested changes
Nearly there

> Reviewed 12 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96#-:-NRUk3so1RybF8GPtEyY:bah1tcu)* status: all files reviewed, 17 unresolved discussions (waiting on @katherinejensen00, @rolfheij-sil, and @tjcouch-sil)

___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5iYccACbulgO8yFFq:-NRU_HA7-KCPZPPFtikA:b-w1fwv2) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

That is the default alias for storybook build. I renamed the alias as TJ suggested to avoid confusion so it doesn't look like it is part of the overall build process. The new command is npm run package:storybook
</blockquote></details>

I wonder if you looked at the older comments before TJ's? This is definitely not part of our package process as the other 2 above that start with that script name `package`. Please change this back to how Rolf fixed it as `storybook:build`. Remember to change the README also.
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5rrj0DF1xWcu5G6g-:-NRUiVit8ipGuqT-uxsr:b2b4ig8) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

@irahopkinson Are you still getting this error after the latest changes? I don't think I have gotten this one before and I am having a hard time reproducing it. Maybe we can pair on it if you are still getting it.
</blockquote></details>

Actually I can't even do an `npm i` at this commit (however I can at the merge commit before this one) so that needs to be fixed first However I really can't see what would affect that in this latest commit, weird.

I did go back one commit, do the install then back to this latest commit and I still ge the same error.
___
*[`README.md` line 78 at r10](https://reviewable.io/reviews/paranext/paranext-core/96#-NRUdOsM344jYQvR8lrG:-NRUdOsM344jYQvR8lrH:b-ubj476) ([raw file](https://github.com/paranext/paranext-core/blob/ea67dc1798bb92c10148bbae0e07cf00ed94e72f/README.md#L78)):*
> ```Markdown
> ```
> 
> ## Storybook
> ```

Thanks for adding this to the README. Please move this section to somewhere below `##Publishing` as this relates to the section above `## Packaging for Production` and Storybook is unrelated to either of them so should not be in the middle of them.
___
*[`README.md` line 86 at r10](https://reviewable.io/reviews/paranext/paranext-core/96#-NRUe1QbC00p5y5JzBM3:-NRUe1QbC00p5y5JzBM4:b-hjgnff) ([raw file](https://github.com/paranext/paranext-core/blob/ea67dc1798bb92c10148bbae0e07cf00ed94e72f/README.md#L86)):*
> ```Markdown
> ```
> 
> To run storybook locally:
> ```

I would put this above the build so the 2 build options are documented together and how to run locally is probably what a developer needs to know first.
___
*[`src/renderer/components/papi-components/Button.tsx` line 33 at r10](https://reviewable.io/reviews/paranext/paranext-core/96#-NRUfFc58GVNSpshYyi-:-NRUfFc58GVNSpshYyi0:bww52g8) ([raw file](https://github.com/paranext/paranext-core/blob/ea67dc1798bb92c10148bbae0e07cf00ed94e72f/src/renderer/components/papi-components/Button.tsx#L33)):*
> ```XML
>  */
> function Button({
>   isPrimary = false,
> ```

Now that I've had more time to think about it, doesn't MUI have more than primary and secondary? I.e. you can have primary, secondary and neither, as well as outlined. That means a boolean can't describe the available options here. Unless we only mean to give them those 2 options?
___
*[`src/renderer/components/papi-components/TextField.tsx` line 72 at r10](https://reviewable.io/reviews/paranext/paranext-core/96#-NRUhXm1CW7iR9gy-w5G:-NRUhXm1CW7iR9gy-w5H:b-cxq25e) ([raw file](https://github.com/paranext/paranext-core/blob/ea67dc1798bb92c10148bbae0e07cf00ed94e72f/src/renderer/components/papi-components/TextField.tsx#L72)):*
> ```XML
>   onFocus,
>   onBlur,
> }: TextfieldProps) {
> ```

The type above has a capital `F`. Revert this change.



_Code quote:_
```XML
TextfieldProps
```


<!-- Sent from Reviewable.io -->

2023-03-26 21:39 UTC, irahopkinson commented
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5rrj0DF1xWcu5G6g-:-NRUqarvB7xXHTIxMhuh:b-dp1if4) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Actually I can't even do an `npm i` at this commit (however I can at the merge commit before this one) so that needs to be fixed first However I really can't see what would affect that in this latest commit, weird.

I did go back one commit, do the install then back to this latest commit and I still ge the same error.
</blockquote></details>

I traced the `npm i` issue down to the change of this file in this commit. I think there is a file corruption at the begining of the file. We might need to re-write this commit because we don't want that corruption in our repo. Let me know if you need help with this.


<!-- Sent from Reviewable.io -->

2023-03-27 11:19 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: all files reviewed, 17 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`.eslintrc.js` line 2 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9KsIp-IH-PG40gZcy:-NRXb3IlAMZU-_oMnTF5:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/.eslintrc.js#L2)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This would be better like this:
```
  extends: [
     // https://github.com/electron-react-boilerplate/eslint-config-erb/blob/main/index.js
    // airbnb rules are embedded in erb https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb
    'erb',
    // https://github.com/storybookjs/eslint-plugin-storybook/blob/main/lib/configs/recommended.ts
    'plugin:storybook/recommended'
  ],
```
</blockquote></details>

Done.
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5iYccACbulgO8yFFq:-NRXerXx5KJP2D-r_OUA:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I wonder if you looked at the older comments before TJ's? This is definitely not part of our package process as the other 2 above that start with that script name `package`. Please change this back to how Rolf fixed it as `storybook:build`. Remember to change the README also.
</blockquote></details>

Done.
___
*[`package.json` line 67 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NR5rrj0DF1xWcu5G6g-:-NRXfDEN41t4jXvGZDwd:b-udaoyf) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/package.json#L67)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I traced the `npm i` issue down to the change of this file in this commit. I think there is a file corruption at the begining of the file. We might need to re-write this commit because we don't want that corruption in our repo. Let me know if you need help with this.
</blockquote></details>

I think I was able to fix it, as per your instructions on Discord
___
*[`README.md` line 78 at r10](https://reviewable.io/reviews/paranext/paranext-core/96#-NRUdOsM344jYQvR8lrG:-NRXfgG8-29J-MRGRCgZ:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/ea67dc1798bb92c10148bbae0e07cf00ed94e72f/README.md#L78)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Thanks for adding this to the README. Please move this section to somewhere below `##Publishing` as this relates to the section above `## Packaging for Production` and Storybook is unrelated to either of them so should not be in the middle of them.
</blockquote></details>

Done.
___
*[`README.md` line 86 at r10](https://reviewable.io/reviews/paranext/paranext-core/96#-NRUe1QbC00p5y5JzBM3:-NRXfumZ99q8QUT07vJS:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/ea67dc1798bb92c10148bbae0e07cf00ed94e72f/README.md#L86)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I would put this above the build so the 2 build options are documented together and how to run locally is probably what a developer needs to know first.
</blockquote></details>

Done.
___
*[`src/renderer/components/papi-components/Button.tsx` line 44 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9PMlG11XLX8BElG5H:-NRXhZ03DmgYgpJYXVfg:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/Button.tsx#L44)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

@tjcouch-sil you can get the formatting you want if you use a tripple-backtick begining and end (even inline), i.e. ```className={`papi-button ${mode} className`}```.
</blockquote></details>

Done
___
*[`src/renderer/components/papi-components/Button.tsx` line 34 at r9](https://reviewable.io/reviews/paranext/paranext-core/96#-NRFUIE886UWD5SSflbO:-NRXhMyg9XfZyxvWC4A6:b-yha6mt) ([raw file](https://github.com/paranext/paranext-core/blob/ff59bc6782089605a2927c4cd811f7ca29e6c839/src/renderer/components/papi-components/Button.tsx#L34)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

FYI this happens when you have an object being destructured and then rename one of the members of that object type. I guess TypeScript thinks it's being helpful by not renaming the variable created by the destructure. So you just kinda have to keep an eye out for this kind of thing when renaming type members. An easy tweak to fix this is to rename `disabled` to `isDisabled` on this line as well. Then it will have `isDisabled: isDisabled` on this line (and will use `isDisabled` below), so you can shorten it to just `isDisabled`
</blockquote></details>

Done. Well spotted. I did as TJ described for all props that I've changed, but I slipped up with this one.
___
*[`src/renderer/components/papi-components/Button.tsx` line 33 at r10](https://reviewable.io/reviews/paranext/paranext-core/96#-NRUfFc58GVNSpshYyi-:-NRXgCv3AoZ68ojcXS-B:b-96fac8) ([raw file](https://github.com/paranext/paranext-core/blob/ea67dc1798bb92c10148bbae0e07cf00ed94e72f/src/renderer/components/papi-components/Button.tsx#L33)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Now that I've had more time to think about it, doesn't MUI have more than primary and secondary? I.e. you can have primary, secondary and neither, as well as outlined. That means a boolean can't describe the available options here. Unless we only mean to give them those 2 options?
</blockquote></details>

None of the MUI components that we use have a `primary` prop. I think it was added by us for the sake testing how to change a component's styling using a boolean prop. But we can use a different data type for it, or remove it altogether.
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 34 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRASWX99WH64h-oKvaF:-NRXi58J1RPYfeJdkdF-:b-n4v4uu) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L34)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

https://mui.com/material-ui/react-autocomplete/#options-structure
Looks like they expect an array of objects that have `label: string` if you don't override their `getOptionLabel`. As such, I would be in favor of making `ComboBox` generic as I mention in a thread below. We can make it something like `type MyOptionType = string | { label: string } | Record<string, unknown>` and `ComboBox<T extends MyOptionType>`. Then we can explain that they need to put a label on each option unless they override `getOptionLabel`. Or we can not give them the option to override `getOptionLabel` right now and just tell them they have to provide a label like `type MyOptionType = string | { label: string }` - that might actually be a cleaner way for now :)
</blockquote></details>

Let's pair on this one later today
___
*[`src/renderer/components/papi-components/ComboBox.tsx` line 45 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NRASA6S7PdBKTc-iKnX:-NRXizT-DJ6RF4l5U5Vi:bi5rj9t) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/src/renderer/components/papi-components/ComboBox.tsx#L45)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe Ira was suggesting we declare new types that are simple aliase [...]

2023-03-28 02:46 UTC, irahopkinson requested changes
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: all files reviewed, 11 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`.eslintrc.js` line 2 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9KsIp-IH-PG40gZcy:-NRa2b8m6oGgHxjQwfr5:b149atw) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/.eslintrc.js#L2)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Err... I don't see that it's done. Perhaps you missed staging it for the commit.
___
*[`src/renderer/components/papi-components/Button.tsx` line 33 at r10](https://reviewable.io/reviews/paranext/paranext-core/96#-NRUfFc58GVNSpshYyi-:-NRa1FHxCgRuB6tIIC6s:bno3nzz) ([raw file](https://github.com/paranext/paranext-core/blob/ea67dc1798bb92c10148bbae0e07cf00ed94e72f/src/renderer/components/papi-components/Button.tsx#L33)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

None of the MUI components that we use have a `primary` prop. I think it was added by us for the sake testing how to change a component's styling using a boolean prop. But we can use a different data type for it, or remove it altogether.
</blockquote></details>

I think what we want is just to remove it since it can be controlled with more options by including what we want in `className`.
___
*[`src/renderer/components/papi-components/Switch.tsx` line 36 at r5](https://reviewable.io/reviews/paranext/paranext-core/96#-NRFV1XME6WR5yLSFMxU:-NRa2x4KD2OinI3-MCD4:bcl80t9) ([raw file](https://github.com/paranext/paranext-core/blob/3c1072ef86fa452f5e68b93a8978fa240fdd8080/src/renderer/components/papi-components/Switch.tsx#L36)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Sorry, I removed it because I thought it was redundant because onChange is basically the same thing. I saw that the Slider also only has onChange and onChangeComitted. I can restore it if you want
</blockquote></details>

Yeah, I guess you are right for a switch (as opposed to a button). Lets leave it out for now since its dead easy to add back in should we find we need it, but leaving it out makes for less clutter of options.


<!-- Sent from Reviewable.io -->

2023-03-28 10:22 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: all files reviewed, 11 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`.eslintrc.js` line 2 at r6](https://reviewable.io/reviews/paranext/paranext-core/96#-NR9KsIp-IH-PG40gZcy:-NRbfcCgCFHvqDUBdVt2:b8byoac) ([raw file](https://github.com/paranext/paranext-core/blob/caba9247419888a5b9c7bd056d3c7e8917c94f5a/.eslintrc.js#L2)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Err... I don't see that it's done. Perhaps you missed staging it for the commit.
</blockquote></details>

Sorry, added it now!
___
*[`src/renderer/components/papi-components/Button.tsx` line 33 at r10](https://reviewable.io/reviews/paranext/paranext-core/96#-NRUfFc58GVNSpshYyi-:-NRbicwI9BwZafMPn34S:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/ea67dc1798bb92c10148bbae0e07cf00ed94e72f/src/renderer/components/papi-components/Button.tsx#L33)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I think what we want is just to remove it since it can be controlled with more options by including what we want in `className`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-28 15:30 UTC, tjcouch-sil requested changes
Looks great! We're so close!! Keep up the great work!

> Reviewed 1 of 12 files at r10, 3 of 6 files at r11, 5 of 7 files at r12, 6 of 6 files at r13, 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96#-:-NRcppB89lD8OIY0h8Yu:b-uogck9)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @rolfheij-sil)

___
*[`README.md` line 111 at r13](https://reviewable.io/reviews/paranext/paranext-core/96#-NRcmtIW9kYyYpxkC35G:-NRcmtIW9kYyYpxkC35H:b-rm7fjf) ([raw file](https://github.com/paranext/paranext-core/blob/c3ff3925f61a22e67597940599aba01bec092257/README.md#L111)):*
> ```Markdown
> 
> ```bash
> npm run storybook:build {path to storybook-static folder}
> ```

Might this need to be `npx http-server ./storybook-static` from https://github.com/paranext/paranext-core#formatting-and-linting ? And this would need to be run after `npm run storybook:build`, so it may be best to mention that you have to build it first.


<!-- Sent from Reviewable.io -->

2023-03-28 15:34 UTC, tjcouch-sil submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 12 files at r10, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96#-:-NRcqiNw0YsdE7646vCT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)



<!-- Sent from Reviewable.io -->

2023-03-28 19:37 UTC, irahopkinson requested changes
So close.

> Reviewed 5 of 7 files at r12, 6 of 6 files at r13, 4 of 5 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96#-:-NRdiDv_7ZhW_0JHJa7b:bejeub9)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/stories/Button.stories.tsx` line 17 at r15](https://reviewable.io/reviews/paranext/paranext-core/96#-NRdhmPO7eOsg8IOADVz:-NRdhmPO7eOsg8IOADW-:b-wr2o3x) ([raw file](https://github.com/paranext/paranext-core/blob/71bd5f4ba83169882103982f8aa4d80b93ec7044/src/stories/Button.stories.tsx#L17)):*
> ```XML
> type Story = StoryObj<typeof Button>;
> 
> export const Primary: Story = {
> ```

This now needs _'primary'_ in the 'className' (assuming you revert the CSS changes as suggested above). Same for Switch below.
___
*[`src/renderer/components/papi-components/button.css` line 10 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NRdgkbjAcCsUCbTg1TX:-NRdgkbjAcCsUCbTg1TY:bt0zkh2) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/button.css#L10)):*
> ```CSS
>   line-height: 1;
> }
> .papi-button.primary {
> ```

I'd revert these deletions. We still want to be able to specify `primary` or `secondary` or neither in the buttons `className`.
___
*[`src/renderer/components/papi-components/switch.css` line 5 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NRdhHxj8xAx_KwSlSvD:-NRdhHxj8xAx_KwSlSvE:b-z9byfg) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/switch.css#L5)):*
> ```CSS
> }
> 
> .papi-switch.primary {
> ```

Again I would revert these changes. We still want the option to select them using the switch's `className`.


<!-- Sent from Reviewable.io -->

2023-03-29 08:31 UTC, rolfheij-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[`README.md` line 111 at r13](https://reviewable.io/reviews/paranext/paranext-core/96#-NRcmtIW9kYyYpxkC35G:-NRgQofrCtnGI2fBDxmJ:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/c3ff3925f61a22e67597940599aba01bec092257/README.md#L111)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Might this need to be `npx http-server ./storybook-static` from https://github.com/paranext/paranext-core#formatting-and-linting ? And this would need to be run after `npm run storybook:build`, so it may be best to mention that you have to build it first.
</blockquote></details>

Done
___
*[`src/stories/Button.stories.tsx` line 17 at r15](https://reviewable.io/reviews/paranext/paranext-core/96#-NRdhmPO7eOsg8IOADVz:-NRgRk4i5t6xKOyOU3Tq:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/71bd5f4ba83169882103982f8aa4d80b93ec7044/src/stories/Button.stories.tsx#L17)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This now needs _'primary'_ in the 'className' (assuming you revert the CSS changes as suggested above). Same for Switch below.
</blockquote></details>

Done.
___
*[`src/renderer/components/papi-components/button.css` line 10 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NRdgkbjAcCsUCbTg1TX:-NRgRD-c7ursKsHsyLEu:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/button.css#L10)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I'd revert these deletions. We still want to be able to specify `primary` or `secondary` or neither in the buttons `className`.
</blockquote></details>

Done.
___
*[`src/renderer/components/papi-components/switch.css` line 5 at r4](https://reviewable.io/reviews/paranext/paranext-core/96#-NRdhHxj8xAx_KwSlSvD:-NRgRGG86P4LKwy-OBwC:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/960ff757292cc0a81c95a3983c4082a9e023bc45/src/renderer/components/papi-components/switch.css#L5)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Again I would revert these changes. We still want the option to select them using the switch's `className`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-29 21:41 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Alright, made it through, good job everyone!

FYI: I'm still getting the same error on `npm run storybook:build` but that doesn't need to hold up htis PR since it seems like its only me. @katherinejensen00 perhaps you could help me with that tomorrow.

> Reviewed 6 of 6 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96#-:-NRjIp_b7ui6aZHBGnUU:b1xnj76)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)



<!-- Sent from Reviewable.io -->

2023-03-30 10:06 UTC, rolfheij-sil reviewed
Thanks! And thank you guys for all the feedback :)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/96#-:-NRlyqDX4jXRmj15RnMY:b-v8wbra)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)



<!-- Sent from Reviewable.io -->

2023-03-30 10:06 UTC, merged